export const aiFamilyVersion='ai-families-1';
const bound=(x:number,a:number,b:number,int=false)=>{if(!Number.isFinite(x)||x<a||x>b||int&&!Number.isInteger(x))throw Error('Input outside declared specimen bounds');return x;};
function random(seed:number,stream=0){let s=(bound(seed,1,999,true)^(stream===1?0x6a09e667:stream===2?0xbb67ae85:0))>>>0;return ()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return (s+.5)/4294967296;};}
const gaussian=(r:()=>number)=>Math.sqrt(-2*Math.log(r()))*Math.cos(2*Math.PI*r());
export function fitLine(rows:{x:number;y:number}[]){if(!Array.isArray(rows)||rows.length<2||rows.length>128||rows.some(r=>!r||![r.x,r.y].every(x=>Number.isFinite(x)&&Math.abs(x)<=1e6)))throw Error('Invalid bounded regression examples');const n=rows.length,sx=rows.reduce((s,r)=>s+r.x,0),sy=rows.reduce((s,r)=>s+r.y,0),sxx=rows.reduce((s,r)=>s+r.x*r.x,0),sxy=rows.reduce((s,r)=>s+r.x*r.y,0),den=n*sxx-sx*sx;if(n<2||Math.abs(den)<1e-12)throw Error('Unidentifiable linear fit');const slope=(n*sxy-sx*sy)/den;return {slope,bias:(sy-slope*sx)/n};}
export function expertSpecimen(topK=1,capacity=4,skew=false){
 bound(topK,1,2,true);bound(capacity,1,8,true);
 const training=[[-3,-2,-1].map(x=>({x,y:-.5*x-1})),[1,2,3].map(x=>({x,y:2*x+1}))],experts=training.map(fitLine),counts=[0,0];
 const rows=(skew?[.25,.5,.75,1.25,1.5,2.5]:[-2.5,-1.5,-.5,.5,1.5,2.5]).map((x,i)=>{const scores=[-x,x],selected=[0,1].sort((a,b)=>scores[b]-scores[a]||a-b).slice(0,topK),max=Math.max(...selected.map(e=>scores[e])),den=selected.reduce((s,e)=>s+Math.exp(scores[e]-max),0);const routes=selected.map(e=>{const accepted=counts[e]<capacity;if(accepted)counts[e]++;return {expert:e,weight:Math.exp(scores[e]-max)/den,accepted,value:accepted?experts[e].slope*x+experts[e].bias:null};});const dropped=routes.some(r=>!r.accepted),prediction=dropped?null:routes.reduce((s,r)=>s+r.weight*r.value!,0),target=x<0?-.5*x-1:2*x+1;return {id:'reserved-'+i,x,scores,routes,prediction,target,absoluteError:prediction===null?null:Math.abs(prediction-target)};});
 const accepted=rows.filter(r=>r.prediction!==null);return {training,experts,rows,counts,accepted:accepted.length,dropped:rows.length-accepted.length,meanAbsoluteError:accepted.length?accepted.reduce((s,r)=>s+r.absoluteError!,0)/accepted.length:null,expertEvaluations:rows.flatMap(r=>r.routes).filter(r=>r.accepted).length,scope:'Fitted scalar experts, authored sign-sensitive router; no gate training or load-balancing optimizer. Any missing route rejects the token output, rather than silently renormalizing it.'};
}
export function recurrentSpecimen(retention=.7,resetAt=-1){
 bound(retention,-1.05,1.05);bound(resetAt,-1,15,true);const input=[1,0,0,0,-1,0,1,0,0,0,0,0,0,0,0,0],gain=.3;let state=0,lastReset=0;
 const rows=input.map((x,t)=>{const reset=t===resetAt;if(reset){state=0;lastReset=t;}const before=state;state=retention*state+gain*x;const contributions=input.slice(lastReset,t+1).map((u,j)=>({inputIndex:lastReset+j,input:u,kernel:gain*retention**(t-lastReset-j),value:u*gain*retention**(t-lastReset-j)}));return {t,input:x,before,reset,state,convolution:contributions.reduce((s,c)=>s+c.value,0),contributions};});
 return {retention,gain,input,rows,kernel:input.map((_,k)=>gain*retention**k),persistentScalars:1,scope:'An authored scalar linear time-invariant recurrence. It demonstrates the recurrence/convolution identity, not S4 or Mamba training, selective state updates or a learned long-memory guarantee.'};
}
export function spatialSpecimen(orientation:'vertical'|'horizontal'='vertical',offset=2,occlude=false){
 if(!['vertical','horizontal'].includes(orientation))throw Error('Unknown image');bound(offset,0,4,true);
 const pixels=Array.from({length:5},(_,i)=>Array.from({length:5},(_,j)=>Number((orientation==='vertical'?j:i)===offset&&(!occlude||i!==2))));
 const kernels=[[[0,1,0],[0,1,0],[0,1,0]],[[0,0,0],[1,1,1],[0,0,0]]];
 const outputs=kernels.map(kernel=>Array.from({length:3},(_,i)=>Array.from({length:3},(_,j)=>kernel.reduce((s,r,ki)=>s+r.reduce((z,k,kj)=>z+k*pixels[i+ki][j+kj],0),0))));
 const peaks=outputs.map(m=>Math.max(...m.flat())),prediction=peaks[0]===peaks[1]?'tie':peaks[0]>peaks[1]?'vertical':'horizontal';
 const patches=Array.from({length:9},(_,k)=>{const row=Math.floor(k/3),col=k%3;return {row,col,values:pixels.slice(row,row+3).flatMap(r=>r.slice(col,col+3))};});
 const query=patches[4].values,scores=patches.map(p=>p.values.reduce((s,x,i)=>s+x*query[i],0)/3),max=Math.max(...scores),den=scores.reduce((s,x)=>s+Math.exp(x-max),0),attention=scores.map(s=>Math.exp(s-max)/den),pooled=Array.from({length:9},(_,j)=>patches.reduce((s,p,i)=>s+attention[i]*p.values[j],0));
 return {pixels,kernels,outputs,peaks,prediction,correct:prediction===orientation,patches,query,scores,attention,pooled,convolutionMacs:2*3*3*3*3,attentionScoreMacs:9*9,scope:'Authored line filters and max-response classifier versus one content-addressed patch query with identity projections. No learned CNN, full ViT, position encoding or image recognition benchmark is claimed.'};
}
export function spectrumSpecimen(frequency=1000,sampleRate=8000,windowed=true){
 bound(frequency,0,7000);if(![8000,16000].includes(sampleRate))throw Error('Unknown sample rate');const n=32,signal=Array.from({length:n},(_,i)=>Math.sin(2*Math.PI*frequency*i/sampleRate)),window=signal.map((_,i)=>windowed?.5-.5*Math.cos(2*Math.PI*i/(n-1)):1),samples=signal.map((x,i)=>x*window[i]);
 const bins=Array.from({length:n/2+1},(_,k)=>{let real=0,imaginary=0;for(let i=0;i<n;i++){real+=samples[i]*Math.cos(2*Math.PI*k*i/n);imaginary-=samples[i]*Math.sin(2*Math.PI*k*i/n);}return {bin:k,hz:k*sampleRate/n,real,imaginary,power:(real*real+imaginary*imaginary)/n**2};});
 const strongest=bins.reduce((best,row)=>row.power>best.power?row:best,bins[0]);return {frequency,sampleRate,signal,window,samples,bins,strongest,hasSignalEnergy:samples.reduce((sum,x)=>sum+x*x,0)>1e-20,nyquist:sampleRate/2,durationSeconds:n/sampleRate,scope:'A sampled tone, Hann window and exact finite DFT. It exposes a speech/audio front-end prerequisite, not speech recognition, phonemes or language understanding.'};
}
export type NoiseRow={x0:number;epsilon:number;xt:number};
export function diffusionTraining(seed=11,biased=false){const rand=random(seed);let cumulative=1;return Array.from({length:12},(_,i)=>{const beta=.05+i*.035,alpha=1-beta;cumulative*=alpha;const abar=cumulative;const examples=Array.from({length:96},(_,j)=>{const x0=biased?1:j%2===0?-1:1,epsilon=gaussian(rand);return {x0,epsilon,xt:Math.sqrt(abar)*x0+Math.sqrt(1-abar)*epsilon};});return {t:i+1,beta,alpha,abar,examples};});}
export function predictNoise(examples:NoiseRow[],xt:number,neighbors=8){bound(neighbors,1,32,true);if(!Array.isArray(examples)||examples.length<neighbors||examples.length>2000||examples.some(r=>!r||![r.x0,r.epsilon,r.xt].every(x=>Number.isFinite(x)&&Math.abs(x)<=1e6))||!Number.isFinite(xt)||Math.abs(xt)>1e6)throw Error('Invalid denoising query');const selected=examples.map((r,id)=>({id,distance:Math.abs(r.xt-xt),epsilon:r.epsilon})).sort((a,b)=>a.distance-b.distance||a.id-b.id).slice(0,neighbors);return {epsilon:selected.reduce((s,r)=>s+r.epsilon,0)/neighbors,neighborIds:selected.map(r=>r.id)};}
export function diffusionSpecimen(seed=11,biased=false,neighbors=8,ablate=false){
 bound(seed,1,999,true);bound(neighbors,1,32,true);const training=diffusionTraining(11,biased),rand=random(seed,1);let x=gaussian(rand);const start=x,trace=[];
 for(let i=training.length-1;i>=0;i--){const stage=training[i],pred=predictNoise(stage.examples,x,neighbors),epsilon=ablate?0:pred.epsilon,previousAbar=i?training[i-1].abar:1,variance=stage.beta*(1-previousAbar)/(1-stage.abar),mean=(x-stage.beta*epsilon/Math.sqrt(1-stage.abar))/Math.sqrt(stage.alpha),noise=i?gaussian(rand):0,next=mean+Math.sqrt(variance)*noise;trace.push({t:stage.t,beta:stage.beta,abar:stage.abar,x,epsilon,neighborIds:pred.neighborIds,mean,variance,noise,next});x=next;}
 const evalRand=random(797,2),evaluation=training.map(stage=>{let mse=0,baseline=0;const examples:{x0:number;epsilon:number;xt:number;prediction:number}[]=[];for(let i=0;i<32;i++){const x0=i%2?-1:1,epsilon=gaussian(evalRand),xt=Math.sqrt(stage.abar)*x0+Math.sqrt(1-stage.abar)*epsilon,pred=predictNoise(stage.examples,xt,neighbors).epsilon;examples.push({x0,epsilon,xt,prediction:pred});mse+=(pred-epsilon)**2;baseline+=epsilon**2;}return {t:stage.t,count:32,mse:mse/32,zeroBaselineMse:baseline/32,examples};});
 return {training,trace,start,result:x,terminalAbar:training.at(-1)!.abar,initialization:'Standard normal prior is an approximation: the finite forward chain retains a nonzero clean-signal component.',distanceToTargetSupport:Math.min(Math.abs(x-1),Math.abs(x+1)),evaluation,scope:`A 12-step one-dimensional denoising chain with a ${neighbors}-neighbor noise regressor fitted by retaining original synthetic noisy examples. The target training distribution is two points, ±1 (or only +1 in the biased case). No neural network, image generator or paper benchmark is reproduced. A single generated sample does not measure distribution quality.`};
}
export const familyModes=['experts','recurrence','vision','spectrum','denoising'] as const;
export type FamilyInput={mode:typeof familyModes[number];topK:number;capacity:number;skew:boolean;retention:number;resetAt:number;orientation:'vertical'|'horizontal';offset:number;occlude:boolean;frequency:number;sampleRate:number;windowed:boolean;seed:number;biased:boolean;neighbors:number;ablate:boolean;cursor:number};
export const familyDefaults:FamilyInput={mode:'experts',topK:1,capacity:4,skew:false,retention:.7,resetAt:-1,orientation:'vertical',offset:2,occlude:false,frequency:1000,sampleRate:8000,windowed:true,seed:11,biased:false,neighbors:8,ablate:false,cursor:0};
export function normalizeFamilyInput(raw:unknown):FamilyInput{if(!raw||typeof raw!=='object')throw Error('Expected a family experiment');const s=raw as FamilyInput;if(Object.keys(s).sort().join()!==Object.keys(familyDefaults).sort().join()||!familyModes.includes(s.mode)||!['vertical','horizontal'].includes(s.orientation))throw Error('Unknown or missing family setting');for(const k of ['skew','occlude','windowed','biased','ablate'] as const)if(typeof s[k]!=='boolean')throw Error('Invalid toggle');for(const [k,a,b,int]of [['topK',1,2,true],['capacity',1,8,true],['retention',-1.05,1.05,false],['resetAt',-1,15,true],['offset',0,4,true],['frequency',0,7000,false],['sampleRate',8000,16000,true],['seed',1,999,true],['neighbors',1,32,true],['cursor',0,11,true]]as const)bound(s[k],a,b,int);if(![8000,16000].includes(s.sampleRate))throw Error('Unsupported sample rate');return {...s};}
export function familyRecord(input:FamilyInput,content:string){if(typeof content!=='string'||content.length>100)throw Error('Invalid source identity');return JSON.stringify({schemaVersion:1,modelVersion:aiFamilyVersion,content,inputs:normalizeFamilyInput(input)});}
export function readFamilyRecord(raw:string){if(new TextEncoder().encode(raw).length>12000)throw Error('Record exceeds 12,000 bytes');const r=JSON.parse(raw);if(!r||Object.keys(r).sort().join()!=='content,inputs,modelVersion,schemaVersion'||r.schemaVersion!==1||r.modelVersion!==aiFamilyVersion||typeof r.content!=='string'||r.content.length>100)throw Error('Incompatible family record');return {inputs:normalizeFamilyInput(r.inputs),content:r.content};}
