export const applicationDecisionsVersion='application-decisions-1';
export type DecisionInput={mode:'forecast'|'code';horizon:number;shift:number;ridge:number;leak:boolean;candidate:'identity'|'upper-only'|'ordered-clamp'|'reversed-clamp';suite:'examples'|'boundaries'};
export const decisionDefaults:DecisionInput={mode:'forecast',horizon:1,shift:4,ridge:.1,leak:false,candidate:'identity',suite:'examples'};
function ensure(v:unknown,m:string):asserts v{if(!v)throw Error(m);}
export function resolveDecisionInput(v:DecisionInput){ensure(v&&Object.keys(v).length===7&&Object.keys(v).every(k=>Object.hasOwn(decisionDefaults,k)),'Invalid application record fields');ensure(['forecast','code'].includes(v.mode)&&Number.isInteger(v.horizon)&&v.horizon>=1&&v.horizon<=8&&Number.isFinite(v.shift)&&v.shift>=-8&&v.shift<=8&&Number.isFinite(v.ridge)&&v.ridge>=.001&&v.ridge<=10&&typeof v.leak==='boolean'&&['identity','upper-only','ordered-clamp','reversed-clamp'].includes(v.candidate)&&['examples','boundaries'].includes(v.suite),'Invalid application input');return {...v};}
export function forecastSeries(shift=4){ensure(Number.isFinite(shift)&&shift>=-8&&shift<=8,'Invalid shift');return Array.from({length:48},(_,t)=>({id:`hour-${t}`,t,value:20+.15*t+3*Math.sin(2*Math.PI*t/12)+.2*Math.cos(1.73*t)+(t>=32?shift:0)}));}
export function solveSmallLinear(matrix:number[][],rhs:number[]){const n=rhs.length,a=matrix.map((r,i)=>[...r,rhs[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(a[i][k])>Math.abs(a[p][k]))p=i;ensure(Math.abs(a[p][k])>1e-12,'Singular teaching fit');[a[k],a[p]]=[a[p],a[k]];const d=a[k][k];for(let j=k;j<=n;j++)a[k][j]/=d;for(let i=0;i<n;i++)if(i!==k){const m=a[i][k];for(let j=k;j<=n;j++)a[i][j]-=m*a[k][j];}}return a.map(r=>r[n]);}
const forecastFeatures=(lag:number,t:number)=>[1,lag/30,Math.sin(2*Math.PI*t/12),Math.cos(2*Math.PI*t/12),t/48];
export function runForecast(v:DecisionInput=decisionDefaults){
 const input=resolveDecisionInput(v),series=forecastSeries(input.shift),training=series.slice(1,24).map(r=>({id:r.id,featureTime:r.t-1,features:forecastFeatures(series[r.t-1].value,r.t),target:r.value}));
 const normal=Array.from({length:5},(_,i)=>Array.from({length:5},(_,j)=>training.reduce((s,r)=>s+r.features[i]*r.features[j],0)+(i===j&&i>0?input.ridge:0))),rhs=Array.from({length:5},(_,i)=>training.reduce((s,r)=>s+r.features[i]*r.target,0)),weights=solveSmallLinear(normal,rhs);
 const predictions=[];for(let origin=23;origin+input.horizon<48;origin++){
  let value=series[origin].value;const trace=[];for(let h=1;h<=input.horizon;h++){const target=origin+h,features=forecastFeatures(value,target),predicted=features.reduce((s,x,j)=>s+x*weights[j],0);trace.push({target,lag:value,lagSource:h===1?`observed hour-${origin}`:`prediction hour-${target-1}`,features,predicted});value=predicted;}
  const target=origin+input.horizon,truth=series[target].value,forecast=input.leak?truth:value;
  predictions.push({id:`origin-${origin}-h${input.horizon}`,origin,target,truth,forecast,persistence:series[origin].value,error:forecast-truth,absoluteError:Math.abs(forecast-truth),baselineAbsoluteError:Math.abs(series[origin].value-truth),legal:!input.leak,trace});
 }
 const count=predictions.length,mae=predictions.reduce((s,r)=>s+r.absoluteError,0)/count,baselineMae=predictions.reduce((s,r)=>s+r.baselineAbsoluteError,0)/count;
 return{modelVersion:applicationDecisionsVersion,dataVersion:'synthetic-hourly-demand-1',input,series,training,weights,normal,rhs,predictions,metrics:{count,mae,baselineMae},validTemporalBoundary:!input.leak,scope:'A five-coefficient ridge regression fits hours 1–23 only, with an unpenalized intercept. Each later origin observes its own current value, then rolls its predictions forward without future measurements. Calendar phase and time are known in advance. Later observations inform only the next origin, never refit coefficients. All 48 hourly values are authored synthetic load units; overlapping rolling forecasts are correlated and provide development diagnostics, not independent confidence intervals.'};
}
export const codeCandidates={identity:'return x;', 'upper-only':'return Math.min(hi, x);','ordered-clamp':'return Math.min(hi, Math.max(lo, x));','reversed-clamp':'return Math.max(hi, Math.min(lo, x));'} as const;
export function executeCandidate(candidate:DecisionInput['candidate'],x:number,lo:number,hi:number){ensure(Object.hasOwn(codeCandidates,candidate)&&[x,lo,hi].every(Number.isFinite)&&lo<=hi,'Outside finite ordered-bound contract');if(candidate==='identity')return x;if(candidate==='upper-only')return Math.min(hi,x);if(candidate==='reversed-clamp')return Math.max(hi,Math.min(lo,x));return Math.min(hi,Math.max(lo,x));}
export function codeOracle(x:number,lo:number,hi:number){if(x<lo)return lo;if(x>hi)return hi;return x;}
export function runCodeContract(candidate:DecisionInput['candidate']='identity',suite:DecisionInput['suite']='examples'){
 ensure(['examples','boundaries'].includes(suite),'Unknown test suite');const examples=[[3,0,10],[7,0,10]],boundary=[[-1,0,10],[12,0,10],[0,0,10],[10,0,10],[-8,-5,-2],[-1,-5,-2],[4,4,4],[.2,.25,.75]];
 const rows=[...examples,...(suite==='boundaries'?boundary:[])].map(([x,lo,hi],i)=>{const expected=codeOracle(x,lo,hi),actual=executeCandidate(candidate,x,lo,hi);return{id:`case-${i}`,x,lo,hi,expected,actual,passed:actual===expected};});
 // Exhaustively check a declared finite integer contract; this is not a proof over all IEEE numbers.
 let total=0,failures=0;let first:null|{x:number;lo:number;hi:number;expected:number;actual:number}=null;for(let lo=-3;lo<=3;lo++)for(let hi=lo;hi<=3;hi++)for(let x=-5;x<=5;x++){total++;const expected=codeOracle(x,lo,hi),actual=executeCandidate(candidate,x,lo,hi);if(actual!==expected){failures++;first??={x,lo,hi,expected,actual};}}
 return{candidate,program:codeCandidates[candidate],suite,rows,passed:rows.filter(r=>r.passed).length,count:rows.length,boundedOracle:{total,failures,first},scope:'Four authored functions execute over a finite ordered-bound clamp contract. Displayed source corresponds to whitelisted functions; arbitrary code is not evaluated. This tests a proposed patch, not a code-generating model. NaN, infinities, unordered bounds and signed-zero identity are outside the declared task. A finite exhaustive grid is stronger than two examples but is not a proof over every real or floating-point input.'};
}
export function decisionRecord(inputs:DecisionInput,content:string){return JSON.stringify({schema:1,version:applicationDecisionsVersion,content,inputs:resolveDecisionInput(inputs)});}
export function readDecisionRecord(raw:string){ensure(typeof raw==='string'&&raw.length<=12000,'Oversized application record');const v=JSON.parse(raw);ensure(v&&Object.keys(v).length===4&&['schema','version','content','inputs'].every(k=>Object.hasOwn(v,k))&&v.schema===1&&v.version===applicationDecisionsVersion&&typeof v.content==='string'&&v.content.length<=128,'Incompatible application record');return{content:v.content,inputs:resolveDecisionInput(v.inputs)};}
