import catalog from './generated/catalog.json';
import type { RecordEntry, Chapter, AtlasRelation } from './atlas-authoring';
export type { RecordEntry, Chapter, AtlasRelation, RelationKind } from './atlas-authoring';
export type LessonSummary = Pick<RecordEntry,'id'|'level'|'name'|'shortName'|'role'|'scale'|'kind'|'branch'|'subbranch'|'workstream'|'labId'|'deepLabId'|'labScope'|'investigationId'|'prerequisites'|'related'|'check'> & {asset:string};
export const records=catalog.records as LessonSummary[];
export const byId=Object.fromEntries(records.map(r=>[r.id,r]));
export const chapters=catalog.chapters as Chapter[];
export const bands=catalog.bands, domains=catalog.domains, journeys=catalog.journeys;
export const relationshipEdges=catalog.relationshipEdges as AtlasRelation[];
export const contentPacks=catalog.contentPacks;
export const chapterFor=(id:string)=>chapters.find(c=>c.ids.includes(id))??chapters[0];
