import raw from './data/records.json';
import fabrication from './data/fabrication.json';
import architecture from './data/architecture.json';
import infrastructure from './data/infrastructure.json';
import infrastructureDepth from './data/infrastructure-depth.json';
import crg from './data/crg.json';
import {legacyEnrichments} from './legacy-enrichments';
export const contentPacks=[fabrication,architecture,infrastructure,crg,infrastructureDepth];
export type RecordEntry={labId?:string;branch?:string;subbranch?:string;prerequisites?:string[];learningObjective?:string;workstream?:string;visualFamily?:string;engineeringExample?:string;evidenceNotes?:string;id:string;level:string;name:string;shortName:string;role:string;description:string;specs:{label:string;value:string;context:string}[];interfaces:{name:string;direction:string;signal:string}[];tradeoff:string;whyAI:string;related:string[];sources:{title:string;url:string}[];scale:string;kind:string;mechanism:string[];misconception:string;check:{question:string;options:string[];answer:number;explanation:string};science?:{title:string;equation:string;explanation:string;assumptions:string}[];history?:{year:string|number;title:string;significance:string;source:{title:string;url:string}}[]};
export const records=[...raw.map(r=>({...r,...legacyEnrichments[r.id]})),...contentPacks.flatMap(p=>p.lessons as unknown as RecordEntry[])] as RecordEntry[];
export const byId=Object.fromEntries(records.map(r=>[r.id,r]));
export type RelationKind='prerequisite'|'related'|'part-of'|'assembled-into'|'executes'|'limited-by';
export type AtlasRelation={from:string;to:string;kind:RelationKind;label:string};
export const relationshipEdges:AtlasRelation[]=records.flatMap(r=>[
 ...(r.prerequisites||[]).filter(id=>byId[id]&&id!==r.id).map(id=>({from:id,to:r.id,kind:'prerequisite' as const,label:'builds into'})),
 ...r.related.filter(id=>byId[id]&&id!==r.id).map(id=>({from:r.id,to:id,kind:'related' as const,label:'related mechanism'}))
]);
export const bands=[{name:'Matter & fabrication',range:'Å → nm',color:'#a8b9fc'},{name:'Circuits & architecture',range:'nm → mm',color:'#7ce1d5'},{name:'Packaging & machines',range:'mm → m',color:'#ffc38b'},{name:'Connected infrastructure',range:'m → km',color:'#8eb8ff'},{name:'Executable software',range:'Operations & state',color:'#d1a3ef'},{name:'Learning & intelligence',range:'Representations & behavior',color:'#f1a9c1'}];
export const originalChapters=[
 {id:'atomic',band:0,name:'Atoms & crystal structure',scene:'atomic',scale:'10⁻¹⁰–10⁻⁹ m',title:'Where the machinery begins',summary:'Electronic states become bonds. Bonds become a crystal.',ids:'silicon-atom crystal-lattice',question:'How does matter acquire useful electronic behavior?',read:'The spheres indicate lattice sites. Bonds show neighboring relationships; electron clouds represent probability, not planetary orbits.'},
 {id:'materials',band:0,name:'Bands, carriers & materials',scene:'materials',scale:'Atomic → device scale',title:'Engineering the carriers',summary:'Energy bands, dopants, junctions, conductors, and insulators.',ids:'energy-bands doping pn-junction copper-conductor dielectric',question:'Why can a semiconductor switch while a wire conducts?',read:'Vertical separation in a band diagram represents energy. Carrier markers and junction regions are conceptual, not drawn to a geometric scale.'},
 {id:'fabrication',band:0,name:'Wafer fabrication',scene:'fabrication',scale:'300 mm wafer → nanoscale patterns',title:'A machine made by layers',summary:'Pattern, deposit, remove, planarize, and repeat.',ids:'silicon-wafer lithography cmp',question:'How do we manufacture billions of devices together?',read:'A wafer contains repeated die sites. The upper layers illustrate pattern transfer and surface processing; the visible grid is a sample, not a die count.'},
 {id:'devices',band:0,name:'Transistor anatomy',scene:'transistor',scale:'Nanometer features',title:'Control a channel with a field',summary:'Gate, dielectric, source, channel, drain. One controllable switch.',ids:'mosfet gate-stack channel source-drain contact spacer finfet gaa',question:'How does gate voltage control electrical current?',read:'The cutaway separates the gate from the channel with an insulating layer. Compare planar, fin, and surrounding-gate geometries through the component selector.'},
 {id:'logic',band:1,name:'Digital logic',scene:'logic',scale:'Device arrays → micrometers',title:'Switches become decisions',summary:'Complementary devices make stable logic levels.',ids:'inverter nand standard-cell clock',question:'How can continuous voltages represent discrete logic?',read:'Logic gates are functional groupings of transistors. Wires carry signals between gates; the display uses enlarged devices to expose connections.'},
 {id:'arithmetic',band:1,name:'Arithmetic circuits',scene:'arithmetic',scale:'Logic networks',title:'The anatomy of a calculation',summary:'Products and sums emerge from structured switching networks.',ids:'adder multiplier mac',question:'How do logic gates become matrix arithmetic?',read:'A small arithmetic array makes repeated multiply–accumulate work visible. It is a teaching circuit, not a reverse-engineered Tensor Core.'},
 {id:'bit-memory',band:1,name:'Memory cells & state',scene:'bit-memory',scale:'nm → μm',title:'Make a bit persist',summary:'Feedback stores a state. Charge stores a state. The tradeoffs differ.',ids:'flipflop sram dram-die',question:'What physically holds a bit, and for how long?',read:'A bank contains repeated cells and shared addressing wires. DRAM and SRAM use different cell mechanisms; select a record for that distinction.'},
 {id:'compute',band:1,name:'Parallel compute engines',scene:'die',scale:'Millimeter die structures',title:'A city of arithmetic',summary:'Scheduling, registers, and matrix engines share a silicon floor.',ids:'streaming-multiprocessor tensor-core register-file tensor-memory-accelerator',question:'How is an accelerator organized to keep many operations active?',read:'Compute neighborhoods repeat across the floorplan. Their count and proportions are illustrative; vendor specifications appear only in the field guide.'},
 {id:'memory-hierarchy',band:1,name:'On-chip memory hierarchy',scene:'cache',scale:'Local storage → shared cache',title:'Distance is part of the cost',summary:'Registers, scratchpads, and caches trade capacity against access cost.',ids:'shared-sram l1-cache l2-cache tensor-memory',question:'Why not use one enormous fast memory?',read:'Nested arrays show locality and sharing domains. Color traces a route through the hierarchy, not a cycle-accurate timing simulation.'},
 {id:'on-chip',band:1,name:'On-chip communication',scene:'die-network',scale:'Across a die',title:'Move the numbers',summary:'Metal routes, queues, controllers, and ports connect the work.',ids:'interconnect on-chip-network hbm-controller nvlink-port',question:'What happens between two arithmetic operations?',read:'The mesh shows possible transaction routes between functional regions. On-chip and off-chip links have different protocols and costs.'},
 {id:'integration',band:2,name:'Advanced packaging',scene:'package',scale:'Millimeters → centimeters',title:'The integrated package',summary:'Compute and memory, brought close together.',ids:'gpu-die interposer microbump package-substrate',question:'Why does packaging now matter as much as a smaller transistor?',read:'Pull apart the compute dies, fine routing platform, bumps, and substrate. This is a conceptual 2.5D assembly, not a proprietary product cross section.'},
 {id:'stacked-memory',band:2,name:'Stacked memory',scene:'memory-stack',scale:'Micrometers → millimeters',title:'Build memory upward',summary:'DRAM layers communicate through vertical connections.',ids:'hbm-stack through-silicon-via',question:'How do stacked dies create a wide memory interface?',read:'Explode the layers to see the vertical connection path. The teaching stack uses eight drawn layers; actual products specify their own stack height.'},
 {id:'thermal',band:2,name:'Package heat path',scene:'thermal',scale:'Die → coolant',title:'Every calculation has a heat path',summary:'Interfaces, spreading, and flowing coolant carry heat away.',ids:'thermal-interface heat-spreader coldplate',question:'Where does the energy go after computation?',read:'The cutaway exposes contact surfaces and coolant channels. Select each thermal element to follow temperature rise and thermal resistance.'},
 {id:'host',band:2,name:'Host & compute board',scene:'server',scale:'Centimeters → meters',title:'Build the computing node',summary:'Processors, memory, and control meet on a common platform.',ids:'host-cpu ddr-memory lpddr-memory compute-baseboard grace-blackwell-superchip',question:'What work surrounds the accelerator?',read:'The board is a functional assembly. Memory types and CPU–GPU links depend on configuration; their exact differences are recorded in the specifications.'},
 {id:'io',band:2,name:'I/O & management',scene:'io',scale:'Board → network',title:'A node needs a nervous system',summary:'Storage, networking, expansion, and management have distinct jobs.',ids:'pcie-interface network-adapter nvme-storage management-controller',question:'How do data, commands, and health information enter a node?',read:'Follow the board paths from interfaces to their endpoints. Data-plane traffic and management traffic are different flows.'},
 {id:'power',band:2,name:'Electrical power chain',scene:'power',scale:'Facility supply → chip rail',title:'Deliver current where it is needed',summary:'Convert, distribute, regulate, and decouple.',ids:'voltage-regulator power-supply power-shelf ups',question:'Why is power delivery a system architecture problem?',read:'Conversion stages step from facility distribution to low-voltage chip supplies. Geometry exposes stages, not an installation wiring plan.'},
 {id:'rack',band:3,name:'Rack-scale assembly',scene:'rack',scale:'Meters',title:'Make the rack a system',summary:'Compute trays, switches, cables, and shared services.',ids:'rack compute-tray nvlink-switch cable-cartridge',question:'How can many accelerators cooperate closely?',read:'The rack separates compute trays and switch trays. The assembly depicts the published 18-compute / 9-switch GB200 NVL72 reference structure.'},
 {id:'fabric',band:3,name:'Scale-out network',scene:'network',scale:'Rack → building',title:'The fabric between machines',summary:'Topology, optics, routing, and congestion set the communication cost.',ids:'leaf-switch spine-switch optics',question:'When does communication become the bottleneck?',read:'Leaf and spine layers show a small illustrative Clos network. A drawn link represents connectivity, not a literal cable count or guaranteed bandwidth.'},
 {id:'facility',band:3,name:'Data center infrastructure',scene:'datacenter',scale:'Building → grid',title:'The machine around the machines',summary:'Cooling loops, storage, electrical capacity, and operations.',ids:'cdu cooling-plant storage',question:'What makes sustained large-scale computation possible?',read:'Rack rows connect to cooling and support systems. Paths distinguish heat removal and data movement; facility layouts vary substantially.'},
 {id:'runtime',band:4,name:'Programs, kernels & precision',scene:'software',scale:'Program → machine instructions',title:'Make the hardware executable',summary:'Compilers lower operations; kernels schedule arithmetic and movement.',ids:'cuda compiler kernel quantization',question:'How does a tensor expression reach the silicon?',read:'The layers depict software lowering. These are abstractions executing on shared hardware, not physical layers piled inside a chip.'},
 {id:'distributed',band:4,name:'Distributed training',scene:'distributed',scale:'Across devices & nodes',title:'One computation, many machines',summary:'Partition, communicate, synchronize, and recover.',ids:'nccl parallelism checkpoint',question:'How does a training step remain coherent across devices?',read:'Device tiles exchange blocks and reductions. The flow illustrates a collective operation; communication volume depends on the chosen parallel strategy.'},
 {id:'serving',band:4,name:'Scheduling & inference',scene:'serving',scale:'Request → batched execution',title:'Turn capacity into responses',summary:'A scheduler manages queues, cached state, and latency.',ids:'scheduler serving kv-cache',question:'Why do throughput and responsiveness pull in different directions?',read:'Queued requests feed batched work and memory allocations. The timing is explanatory, not a production performance prediction.'},
 {id:'representation',band:5,name:'Tokens & representations',scene:'representation',scale:'Discrete IDs → vectors',title:'From symbols to geometry',summary:'Tokenization, learned embeddings, and position.',ids:'tokenizer embedding positional-encoding',question:'How does a sentence become an input to matrix arithmetic?',read:'Visible arrays are small slices of tensors. Their dimensions are teaching choices; the actual arrays usually have many more coordinates.'},
 {id:'transformer',band:5,name:'Transformer internals',scene:'model',scale:'Vectors → repeated blocks',title:'Inside a transforming representation',summary:'Attention, nonlinear features, residual paths, and expert routing.',ids:'attention feed-forward residual-normalization moe output-head',question:'How do layers exchange and transform information?',read:'Follow token representations through repeated blocks. Arcs show causal information paths, not proof of a model’s private reasoning.'},
 {id:'learning',band:5,name:'Learning & scaling',scene:'training',scale:'Examples → parameter updates',title:'Build capability through learning',summary:'Data, loss, optimization, feedback, and resource allocation.',ids:'training-data loss-optimizer post-training scaling-laws',question:'What changes between an untrained and a useful network?',read:'Forward computation produces a loss; backward derivatives guide an update. Scaling is an empirical relationship, not a guaranteed timetable for AGI.'},
 {id:'agent',band:5,name:'Agent systems & the frontier',scene:'agent',scale:'Model → environment',title:'The thinking machine as a system',summary:'Tools, observations, memory, evaluation, and open questions.',ids:'tool-loop evaluation astra',question:'What must be assembled around a model for reliable work?',read:'The model sits inside an execution-and-observation loop. Published capabilities are separated from undisclosed architecture and future possibilities.'},
].map(c=>({...c,ids:c.ids.split(' ')}));
export type Chapter=typeof originalChapters[number]&{parent?:string};
export const chapters:Chapter[]=[...originalChapters,...contentPacks.flatMap(p=>p.chapters) as Chapter[]].sort((a,b)=>a.band-b.band);
export const chapterFor=(id:string)=>chapters.find(c=>c.ids.includes(id))??chapters[0];
export const originalJourneys=[
 {id:'foundation',name:'From matter to a machine',subtitle:'Build the conceptual foundation, one scale at a time.',ids:'silicon-atom crystal-lattice doping mosfet inverter mac tensor-core gpu-die compute-baseboard rack tool-loop'.split(' ')},
 {id:'manufacture',name:'How it is made',subtitle:'Follow fabrication, interconnect, bonding, and assembly.',ids:'silicon-wafer lithography gate-stack cmp interconnect microbump interposer package-substrate compute-baseboard'.split(' ')},
 {id:'token',name:'Follow one token',subtitle:'Connect a model operation to physical arithmetic and memory.',ids:'tokenizer embedding attention kernel tensor-core register-file hbm-stack kv-cache output-head'.split(' ')},
 {id:'energy',name:'Follow the energy',subtitle:'From electrical supply to useful switching and rejected heat.',ids:'ups power-shelf power-supply voltage-regulator mosfet thermal-interface coldplate cdu cooling-plant'.split(' ')},
 {id:'training',name:'Follow a training step',subtitle:'Data, gradients, communication, and an updated model.',ids:'storage training-data loss-optimizer tensor-core parallelism nccl checkpoint scaling-laws evaluation'.split(' ')},
];

const path=(id:string,name:string,subtitle:string,ids:string[])=>({id,name,subtitle,ids:[...new Set(ids)].filter(x=>byId[x])});
export const journeys=[...originalJourneys,
 path('two-wafers','Two wafers to one AI system','Follow converging logic and memory production into an operating workload.',['silicon-wafer','lithography','mosfet','interconnect','dram-die','through-silicon-via','hbm-stack','hbm-stack-height-budget','hbm-bonding-process-selection','hbm-stack-thermal-yield','interposer','microbump','package-substrate','gpu-die','compute-baseboard','rack','cdu','compiler','memory-working-set-placement','serving','memory-system-qualification']),
 path('one-byte','Follow one byte','Storage, host memory, HBM, local memory, arithmetic and the network.',['storage','nvme-storage','ddr-memory','hbm-stack','hbm-controller','l2-cache','shared-sram','register-file','tensor-core','nccl']),
 path('one-watt','Follow one watt','From facility power to switching, temperature rise and heat rejection.',['ups','power-supply','power-shelf','voltage-regulator','mosfet','thermal-interface','heat-spreader','coldplate','cdu','cooling-plant']),
 path('manufacturing-order','Follow one manufacturing order','Design, production readiness, shared resources and allocation.',records.filter(r=>['W04','W08','W10'].includes(r.workstream||'')).map(r=>r.id)),
 path('waiting','Why the accelerator is waiting','Find the memory, input, scheduling or communication constraint.',['storage','host-cpu','hbm-controller','l2-cache','scheduler','parallelism','nccl','checkpoint','evaluation']),
 path('architecture-choice','Choose an architecture','Relate a workload to control, dataflow, locality and specialization.',records.filter(r=>r.workstream==='W07').map(r=>r.id)),
 path('model-to-hall','From a model to a hall','Turn a workload into memory, network, power and operating requirements.',['embedding','attention','moe','kv-cache','quantization','memory-working-set-placement','prefill-decode-tier-placement','compiler','kernel','parallelism','hbm-stack','memory-to-hall-propagation','rack','cdu','memory-system-qualification','storage']),
 path('memory-realization','Memory construction to useful AI','Connect HBM assembly, emerging HBF, workload placement and commissioned service.',['hbm-stack-height-budget','hbm-stack-thermal-yield','hbm-tc-ncf-route','hbm-mr-muf-route','hbm-hybrid-bond-route','hbm-bonding-process-selection','hbf-read-tier-contract','hbf-latency-prefetch','memory-working-set-placement','training-tier-placement','prefill-decode-tier-placement','moe-expert-tier-placement','memory-to-hall-propagation','memory-system-qualification','crg-verification-loop']),
 path('orbital','Could this workload run in orbit?','Close the energy, thermal, communications and reliability budgets.',records.filter(r=>r.workstream==='W12').map(r=>r.id)),
 path('computation-realization','Computation to physical realization','Carry one computational intent through CRG’s representation, architecture, chip, package, system and evidence boundaries.',records.filter(r=>r.workstream==='CRG').map(r=>r.id))].filter(j=>j.ids.length);
