import {normalizeArchitectureInput,referenceMultiply,architecturePresets} from './architecture-execution.ts';
export const commissioningVersion='commissioning-execution-1';
export type CommissioningInput={a:number[][];b:number[][];boot:'compatible'|'abi-mismatch';coherence:'coherent'|'noncoherent';sync:'both'|'skip-to-device'|'skip-to-cpu';fault:'none'|'wrong-mapping'|'unmapped-b'|'early-reuse'|'device-reset';resetAfterCells:number;resetPolicy:'stop'|'retry'};
export const commissioningDefaults:CommissioningInput={a:architecturePresets.two.a.map(r=>[...r]),b:architecturePresets.two.b.map(r=>[...r]),boot:'compatible',coherence:'noncoherent',sync:'both',fault:'none',resetAfterCells:2,resetPolicy:'retry'};
export type BufferId='A'|'B'|'C';
export type Translation={buffer:BufferId;iova:number;physical:number;bytes:number;read:boolean;write:boolean;epoch:number};
export type RuntimeBuffer={id:BufferId;virtual:number;physical:number;iova:number;bytes:number;cpu:number[];memory:number[];owner:'host'|'device';cpuDirty:boolean;cpuStale:boolean};
export type CommissioningState={phase:string;epoch:number;firmwareReady:boolean;discovered:boolean;resourcesClaimed:boolean;dmaEnabled:boolean;queueReady:boolean;process:string;buffers:RuntimeBuffer[];mappings:Translation[];descriptor:{id:string;epoch:number;published:boolean}|null;completion:{id:string;epoch:number;accepted:boolean}|null;deviceA:(number|null)[];deviceB:(number|null)[];deviceC:(number|null)[];published:number[]|null;activeMacs:number;executedMacs:number;discardedMacs:number;committedMacs:number;submittedAttempts:number;canceledAttempts:number;completedAttempts:number;readBytes:number;writeBytes:number;rejectedActions:number};
export type RuntimeAccess={kind:'cpu-write'|'dma-read'|'dma-write'|'mac';buffer:BufferId;iova:number|null;physical:number|null;word:number;value:number|null;detail:string};
export type CommissioningEvent={index:number;kind:string;label:string;issue:string|null;access:RuntimeAccess|null;state:CommissioningState};
export type CommissioningTrace={version:typeof commissioningVersion;input:CommissioningInput;reference:number[][];events:CommissioningEvent[];status:'complete'|'blocked'|'canceled'|'semantic-mismatch';finalOutput:number[][]|null;totals:Pick<CommissioningState,'executedMacs'|'discardedMacs'|'committedMacs'|'submittedAttempts'|'canceledAttempts'|'completedAttempts'|'readBytes'|'writeBytes'|'rejectedActions'>};
function ensure(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(message);}
export function normalizeCommissioningInput(value:unknown):CommissioningInput{
 ensure(value&&typeof value==='object'&&!Array.isArray(value),'Input must be an object.');const x=value as Record<string,unknown>;
 ensure(Object.keys(x).every(k=>['a','b','boot','coherence','sync','fault','resetAfterCells','resetPolicy'].includes(k)),'Unknown commissioning field.');const matrix=normalizeArchitectureInput({a:x.a,b:x.b});ensure(matrix.size===2,'This commissioning contract uses two 2×2 matrices.');
 ensure(x.boot==='compatible'||x.boot==='abi-mismatch','Unknown boot contract.');ensure(x.coherence==='coherent'||x.coherence==='noncoherent','Unknown coherence mode.');ensure(['both','skip-to-device','skip-to-cpu'].includes(x.sync as string),'Unknown visibility handoff.');ensure(['none','wrong-mapping','unmapped-b','early-reuse','device-reset'].includes(x.fault as string),'Unknown fault scenario.');ensure(Number.isInteger(x.resetAfterCells)&&(x.resetAfterCells as number)>=1&&(x.resetAfterCells as number)<=4,'Reset after 1–4 output cells.');ensure(x.resetPolicy==='stop'||x.resetPolicy==='retry','Unknown reset policy.');
 return {a:matrix.a,b:matrix.b,boot:x.boot,coherence:x.coherence,sync:x.sync as CommissioningInput['sync'],fault:x.fault as CommissioningInput['fault'],resetAfterCells:x.resetAfterCells as number,resetPolicy:x.resetPolicy};
}
/** Base addresses are 4096 bytes apart; only sixteen-byte regions are modeled. Not real page-granular IOMMU protection. */
export const commissioningAddressMap:ReadonlyArray<{id:BufferId;virtual:number;physical:number;iova:number}>=Object.freeze([{id:'A',virtual:0x1000,physical:0x4000,iova:0x8000},{id:'B',virtual:0x2000,physical:0x5000,iova:0x9000},{id:'C',virtual:0x3000,physical:0x6000,iova:0xA000}]);
export function translateDma(mappings:readonly Translation[],iova:number,bytes:number,access:'read'|'write',epoch:number):number{
 ensure(Number.isSafeInteger(iova)&&iova>=0&&Number.isSafeInteger(bytes)&&bytes>0,'DMA access must have integer byte address and positive length.');ensure(iova+bytes<=65536,'DMA request exceeds the teaching 16-bit address mask.');
 const matches=mappings.filter(m=>m.epoch===epoch&&iova>=m.iova&&iova+bytes<=m.iova+m.bytes);ensure(matches.length===1,'IOMMU range is absent, stale or ambiguous.');const m=matches[0];ensure(m[access],`IOMMU denies device ${access} permission.`);return m.physical+(iova-m.iova);
}
export function translateProcess(buffers:readonly RuntimeBuffer[],address:number,bytes:number):number{ensure(Number.isSafeInteger(address)&&Number.isSafeInteger(bytes)&&bytes>0,'Process access needs integer bytes.');const matches=buffers.filter(b=>address>=b.virtual&&address+bytes<=b.virtual+b.bytes);ensure(matches.length===1,'Process virtual address is outside its allocated buffer.');return matches[0].physical+(address-matches[0].virtual);}
export function canReuseBuffer(state:CommissioningState,id:BufferId):boolean{return state.buffers.find(b=>b.id===id)?.owner==='host';}
export function acceptsCompletion(state:CommissioningState,id:string,epoch:number):boolean{return state.completion?.accepted!==true&&state.queueReady&&state.descriptor?.published===true&&state.descriptor.id===id&&state.epoch===epoch&&state.descriptor.epoch===epoch&&state.deviceC.every(v=>v!==null)&&state.completedAttempts===0;}
const square=(values:number[])=>[values.slice(0,2),values.slice(2,4)];
export function buildCommissioningTrace(value:unknown):CommissioningTrace{
 const input=normalizeCommissioningInput(value),reference=referenceMultiply(input.a,input.b),events:CommissioningEvent[]=[];
 const state:CommissioningState={phase:'off',epoch:0,firmwareReady:false,discovered:false,resourcesClaimed:false,dmaEnabled:false,queueReady:false,process:'process-1',buffers:commissioningAddressMap.map(b=>({...b,bytes:16,cpu:Array(4).fill(b.id==='C'?-777:0),memory:Array(4).fill(b.id==='C'?-777:0),owner:'host',cpuDirty:false,cpuStale:false})),mappings:[],descriptor:null,completion:null,deviceA:Array(4).fill(null),deviceB:Array(4).fill(null),deviceC:Array(4).fill(null),published:null,activeMacs:0,executedMacs:0,discardedMacs:0,committedMacs:0,submittedAttempts:0,canceledAttempts:0,completedAttempts:0,readBytes:0,writeBytes:0,rejectedActions:0};
 const get=(id:BufferId)=>state.buffers.find(b=>b.id===id)!;
 const emit=(kind:string,label:string,issue:string|null=null,access:RuntimeAccess|null=null)=>{state.phase=kind;events.push({index:events.length,kind,label,issue,access,state:structuredClone(state)});};
 const issue=(kind:string,label:string)=>{state.rejectedActions++;emit(kind,label,label);};
 const out=(status:CommissioningTrace['status']):CommissioningTrace=>({version:commissioningVersion,input,reference,events,status,finalOutput:state.published?square(state.published):null,totals:{executedMacs:state.executedMacs,discardedMacs:state.discardedMacs,committedMacs:state.committedMacs,submittedAttempts:state.submittedAttempts,canceledAttempts:state.canceledAttempts,completedAttempts:state.completedAttempts,readBytes:state.readBytes,writeBytes:state.writeBytes,rejectedActions:state.rejectedActions}});
 emit('process','Process-1 owns three sixteen-byte buffers. Virtual pages and device address space are distinct. Inputs are exact signed integers.');
 for(const id of ['A','B'] as const){const b=get(id);b.cpu=(id==='A'?input.a:input.b).flat();b.cpuDirty=input.coherence==='noncoherent';if(input.coherence==='coherent')b.memory=[...b.cpu];emit('cpu-write',`CPU writes ${id} through its virtual address; ${input.coherence==='coherent'?'coherent memory observes the values':'the teaching CPU cache has dirty values while memory still contains zero'}.`,null,{kind:'cpu-write',buffer:id,iova:null,physical:translateProcess(state.buffers,b.virtual,16),word:0,value:null,detail:'Four exact int32-sized words; no real cache-line geometry.'});}
 const commission=()=>{
  emit('firmware','Device starts in a reset state. Firmware handoff advertises a teaching ABI and readiness; no signature or code is executed.');
  if(input.boot==='abi-mismatch'){issue('boot-rejected','Driver requires matrix-int32-v1; advertised matrix-int32-v2 is incompatible. No queue or DMA is enabled.');return false;}
  state.firmwareReady=true;emit('abi-accepted','Advertised matrix-int32-v1 contract is accepted. This compatibility check does not authenticate firmware.');
  state.discovered=true;emit('discovery','A declared teaching device identity matches this driver. The register resource is discovered; no PCI configuration transaction is simulated.');
  state.resourcesClaimed=true;emit('resources','Driver claims the register window and validates the assumed 16-bit DMA mask. These resources are separate from process data buffers.');
  state.mappings=state.buffers.filter(b=>input.fault!=='unmapped-b'||b.id!=='B').map(b=>({buffer:b.id,iova:b.iova,physical:input.fault==='wrong-mapping'&&b.id==='B'?get('A').physical:b.physical,bytes:16,read:b.id!=='C',write:b.id==='C',epoch:state.epoch}));
  emit('iommu-map',input.fault==='wrong-mapping'?'B IOVA is incorrectly mapped to A physical storage. Permissions allow this alias; the IOMMU does not know tensor identity.':'Device-visible ranges map to physical buffers with separate read/write permissions. This translation installation is not a Linux DMA API call.');
  if(input.sync!=='skip-to-device'){for(const id of ['A','B'] as const){const b=get(id);b.memory=[...b.cpu];b.cpuDirty=false;}emit('sync-to-device','Input memory is made visible before device ownership. In coherent mode values already agree; ordering and lifetime still matter.');}
  else emit('sync-to-device-skipped',`Visibility handoff is deliberately omitted. ${input.coherence==='noncoherent'?'Device memory remains stale.':'Coherent values are visible, but descriptor publication still needs ordering.'}`);
  state.dmaEnabled=true;state.queueReady=true;emit('queue-ready','Resource and ABI gates are satisfied; queue and DMA engine become ready. No buffer was consumed before readiness.');return true;
 };
 if(!commission())return out('blocked');
 let retry=false;
 for(let attempt=0;attempt<2;attempt++){
  if(retry){state.deviceA.fill(null);state.deviceB.fill(null);state.deviceC.fill(null);state.completion=null;state.descriptor=null;get('C').cpu.fill(-777);get('C').memory.fill(-777);get('C').cpuStale=false;if(!commission())return out('blocked');}
  ensure(state.queueReady&&state.dmaEnabled&&state.resourcesClaimed&&state.firmwareReady,'Cannot submit before commissioning.');
  state.descriptor={id:'matrix-job-1',epoch:state.epoch,published:false};emit('descriptor','Driver prepares one descriptor: stable job ID, epoch and A/B/C IOVAs. Preparation is not yet publication.');
  for(const b of state.buffers)b.owner='device';state.descriptor.published=true;state.submittedAttempts++;emit('submit','Ordered publication transfers buffer ownership to the live queue. Descriptor fields precede its valid flag; coherence alone is not this ordering rule.');
  if(input.fault==='early-reuse'){ensure(!canReuseBuffer(state,'B'),'Expected device ownership.');issue('reuse-rejected','CPU attempts to overwrite B for a new job before completion. The ownership guard rejects it; neither cached nor memory data changes.');}
  if(retry){ensure(!acceptsCompletion(state,'matrix-job-1',state.epoch-1),'Old completion must not be accepted.');issue('old-completion-rejected','A previously queued host-side notification refers to the canceled epoch. It is rejected; the reset device is not generating a new old-epoch completion.');}
  for(const id of ['A','B'] as const)for(let word=0;word<4;word++){
   const b=get(id),address=b.iova+word*4;let physical:number;
   try{physical=translateDma(state.mappings,address,4,'read',state.epoch);}catch(error){issue('dma-fault',`${id}[${word}] read rejected: ${error instanceof Error?error.message:'mapping failure'} No value is supplied to arithmetic.`);state.queueReady=false;state.dmaEnabled=false;state.canceledAttempts++;for(const b of state.buffers)b.owner='host';state.mappings=[];emit('fault-quiesced','This bounded protection-fault path acknowledges a stopped engine before clearing mappings and returning buffers. No result is published.');return out('blocked');}
   const backing=state.buffers.find(b=>physical>=b.physical&&physical+4<=b.physical+b.bytes);ensure(backing,'Translated physical storage is absent.');const offset=(physical-backing.physical)/4,value=backing.memory[offset];ensure(Number.isInteger(offset),'Unaligned teaching word.');(id==='A'?state.deviceA:state.deviceB)[word]=value;state.readBytes+=4;emit('dma-read',`Device ${id}[${word}] reads ${value} from physical ${backing.id}[${offset}].`,null,{kind:'dma-read',buffer:id,iova:address,physical,word,value,detail:`Logical ${id} → physical ${backing.id}; permissions do not verify semantic identity.`});
  }
  let reset=false;
  for(let cell=0;cell<4;cell++){
   const i=Math.floor(cell/2),j=cell%2;let sum=0;
   for(let k=0;k<2;k++){const a=state.deviceA[2*i+k],b=state.deviceB[2*k+j];ensure(a!==null&&b!==null,'Arithmetic cannot consume an unread word.');sum+=a*b;state.activeMacs++;state.executedMacs++;emit('mac',`C[${i},${j}] accumulates ${a} × ${b} → ${sum}.`,null,{kind:'mac',buffer:'C',iova:null,physical:null,word:cell,value:sum,detail:`k=${k}; arithmetic uses actual delivered values, never the independent reference.`});}
   const c=get('C'),physical=translateDma(state.mappings,c.iova+4*cell,4,'write',state.epoch);c.memory[cell]=sum;state.deviceC[cell]=sum;state.writeBytes+=4;if(input.coherence==='coherent')c.cpu[cell]=sum;else c.cpuStale=true;emit('dma-write',`Device writes C[${i},${j}] = ${sum}. ${input.coherence==='coherent'?'CPU-visible bits agree; ownership still belongs to the device.':'CPU cached output still needs a visibility handoff.'}`,null,{kind:'dma-write',buffer:'C',iova:c.iova+4*cell,physical,word:cell,value:sum,detail:'A physical write is not yet an accepted job completion.'});
   if(input.fault==='device-reset'&&attempt===0&&cell+1===input.resetAfterCells){
    emit('reset-needed','Device reports reset-needed while the attempt is uncommitted. The host cannot infer successful completion or assume no writes occurred.','The existing attempt cannot be published.');state.queueReady=false;state.dmaEnabled=false;state.firmwareReady=false;state.discovered=false;state.resourcesClaimed=false;state.canceledAttempts++;state.discardedMacs+=state.activeMacs;state.activeMacs=0;state.descriptor=null;state.mappings=[];for(const b of state.buffers)b.owner='host';state.epoch++;emit('reset-acknowledged','Reset completion establishes quiescence in this contract. Old queue/mappings are retired; partial output is uncommitted and its arithmetic is counted as discarded.');reset=true;break;
   }
  }
  if(reset){if(input.resetPolicy==='stop')return out('canceled');retry=true;continue;}
  state.completion={id:'matrix-job-1',epoch:state.epoch,accepted:false};emit('completion-posted','All four output writes precede completion publication. A notification identifies the record to inspect; it does not supply the numerical result.');
  ensure(acceptsCompletion(state,state.completion.id,state.completion.epoch),'Completion contract rejected.');state.completion.accepted=true;emit('completion-validated','Host verifies job ID and current epoch against the live descriptor. A valid completion and visible output are separate gates.');
  if(input.sync!=='skip-to-cpu'){get('C').cpu=[...get('C').memory];get('C').cpuStale=false;emit('sync-to-cpu',input.coherence==='coherent'?'Coherent CPU output values already agree. Completion and ownership are still required before consumption.':'CPU output cache is refreshed from memory before its values are read.');}else emit('sync-to-cpu-skipped',`Output handoff is omitted. ${input.coherence==='noncoherent'?'A host read will use the stale sentinel cache.':'Coherent output values agree, but completion/ownership gates are still required.'}`);
  for(const b of state.buffers)b.owner='host';state.published=[...get('C').cpu];state.completedAttempts++;state.committedMacs+=state.activeMacs;state.activeMacs=0;emit('publish','The consumer reads the actual CPU-visible C buffer once. Compare it against the independent fixture reference; completion does not prove the correct tensor was mapped.');
  state.mappings=[];state.descriptor=null;state.queueReady=false;state.dmaEnabled=false;emit('release','After completion, DMA mappings and the queue are released. Buffers can be reused; register resources remain claimed by this driver.');
  return out(state.published.every((v,i)=>v===reference.flat()[i])?'complete':'semantic-mismatch');
 }
 throw new Error('Finite retry bound exceeded.');
}
