/** Original teaching corpus → train-only byte BPE → reproducible masked packed batches. */
import {createAutomationEnvironment} from './automation-fixtures.ts';
import {canonicalJson,exactObject} from './automation-contracts.ts';
export const dataLineageVersion='data-lineage-1' as const;
export const lineageCorpusVersion='authored-maintenance-families-1' as const;
export const byteBpeVersion='field-bounded-byte-bpe-1' as const;
export type LineageSplit='train'|'development'|'evaluation';
export type SourceDocument={id:string;familyId:string;sourceId:string;variant:string;prompt:string;response:string};
const manuals=createAutomationEnvironment().manuals;
const doc=(id:string,familyId:string,variant:string,prompt:string,response:string):SourceDocument=>({id,familyId,sourceId:'authored-'+familyId,variant,prompt,response});
export const lineageCorpus:SourceDocument[]=[
 doc('fan7-original','fan-seven','original reference','Which filter does FAN-7 need?',manuals[0].text),
 doc('fan7-mirror','fan-seven','exact mirror','Which filter does FAN-7 need?',manuals[0].text),
 doc('fan7-spacing','fan-seven','whitespace variant','  Which  filter does FAN-7 need?\n',manuals[0].text.replaceAll(' ','  ')),
 doc('fan9-original','fan-nine','original reference','Which filter does FAN-9 need?',manuals[1].text),
 doc('fan9-uppercase','fan-nine','case variant','WHICH FILTER DOES FAN-9 NEED?',manuals[1].text.toUpperCase()),
 doc('coolant-original','coolant-check','original reference','How is the coolant check recorded?','Record inlet temperature and outlet temperature before the pump check.'),
 doc('coolant-reworded','coolant-check','near duplicate','How is the coolant check recorded?','Record inlet temperature and outlet temperature before the pump inspection.'),
 doc('power-original','power-check','original reference','How is the power check recorded?','Record the isolated supply voltage before the fixture check.'),
 doc('power-mirror','power-check','exact mirror','How is the power check recorded?','Record the isolated supply voltage before the fixture check.'),
 doc('optics-original','optics-check','original reference','What does the optical fixture report?','The authored optical fixture reports a blue status lamp.'),
 doc('robot-original','robot-check','original reference','What is the robot fixture goal?','The fictional robot fixture moves to the marked empty bay.'),
 doc('sensor-original','sensor-check','Unicode reference','What does the sensor fixture label mean?','The label ΔT means a temperature difference; this is a teaching symbol.'),
];
export const lineageOrigin={authoredOn:'2026-09-07',actorType:'agent',rights:'Original fictional examples, including two manuals already authored for incident-017. No external training text or personal data.',families:'Family IDs describe shared source lineage before any normalization, deduplication or tokenization. They are authored ground truth for this fixture, not an inferred real-world provenance service.',scope:'The BPE vocabulary is independent of the lifecycle decoder’s fixed nine whitespace tokens. No model consumes these BPE batches in this experience.'} as const;
export type LineageInput={splitStrategy:'family'|'document';splitSeed:number;normalization:'verbatim'|'whitespace'|'lowercase';deduplicateTraining:boolean;merges:number;sampleSeed:number;cursor:number;batchDocuments:number;blockSize:number;objective:'all-targets'|'response-only'};
export const lineageDefaults:LineageInput={splitStrategy:'family',splitSeed:7,normalization:'whitespace',deduplicateTraining:true,merges:32,sampleSeed:29,cursor:0,batchDocuments:2,blockSize:32,objective:'response-only'};
const assert=(ok:unknown,message:string):void=>{if(!ok)throw Error(message);};
const int=(x:unknown,a:number,b:number)=>typeof x==='number'&&Number.isInteger(x)&&x>=a&&x<=b;
export function normalizeLineageInput(value:unknown):LineageInput{exactObject(value,Object.keys(lineageDefaults));for(const [k,a,b]of [['splitSeed',1,999],['sampleSeed',1,999],['cursor',0,1000],['merges',0,40],['batchDocuments',1,4]]as const)assert(int(value[k],a,b),'Invalid lineage '+k);assert(['family','document'].includes(String(value.splitStrategy))&&['verbatim','whitespace','lowercase'].includes(String(value.normalization))&&['all-targets','response-only'].includes(String(value.objective))&&[16,32,64].includes(Number(value.blockSize))&&typeof value.blockSize==='number'&&typeof value.deduplicateTraining==='boolean','Invalid lineage mode or block size');return structuredClone(value) as LineageInput;}
/** Content checksum, not a cryptographic signature. */
export function lineageChecksum(value:unknown){let h=2166136261;for(const c of canonicalJson(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
function shuffle<T>(values:T[],seed:number){let state=seed>>>0;const result=[...values];for(let i=result.length-1;i>0;i--){state=(Math.imul(1664525,state)+1013904223)>>>0;const j=Math.floor(state/4294967296*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
export function assignLineageSplits(documents:SourceDocument[],strategy:LineageInput['splitStrategy'],seed:number){assert(['family','document'].includes(strategy)&&int(seed,1,999),'Invalid split configuration');assert(documents.length>=5&&documents.length<=64&&new Set(documents.map(x=>x.id)).size===documents.length,'Distinct source documents required');const groups=Array.from(new Set(documents.map(x=>strategy==='family'?x.familyId:x.id))).sort();assert(groups.length>=5,'At least five split units required');const order=shuffle(groups,seed),trainCount=Math.floor(order.length*.6),developmentCount=Math.max(1,Math.floor(order.length*.2));return documents.map(source=>{const position=order.indexOf(strategy==='family'?source.familyId:source.id),split:LineageSplit=position<trainCount?'train':position<trainCount+developmentCount?'development':'evaluation';return{...source,split};});}
export function normalizeLineageText(text:string,mode:LineageInput['normalization']){assert(typeof text==='string'&&new TextEncoder().encode(text).length<=2000,'Bounded source field required');assert(['verbatim','whitespace','lowercase'].includes(mode),'Unknown normalization');const clean=mode==='verbatim'?text:text.trim().replace(/\s+/gu,' ');return mode==='lowercase'?clean.toLowerCase():clean;}
export type PreparedDocument=SourceDocument&{split:LineageSplit;normalizedPrompt:string;normalizedResponse:string;excludedFromTraining:boolean;duplicateOf:string|null};
const documentText=(d:PreparedDocument)=>JSON.stringify([d.normalizedPrompt,d.normalizedResponse]);
function shingles(d:PreparedDocument){const words=(d.normalizedPrompt+' '+d.normalizedResponse).split(/\s+/u).filter(Boolean);return new Set(words.slice(0,-2).map((_,i)=>words.slice(i,i+3).join(' ')));}
export function lineageDuplicates(documents:PreparedDocument[]){const pairs:{left:string;right:string;family:boolean;exact:boolean;near:boolean;jaccard:number;crossSplit:boolean;splits:LineageSplit[]}[]=[];for(let i=0;i<documents.length;i++)for(let j=i+1;j<documents.length;j++){const a=documents[i],b=documents[j],sa=shingles(a),sb=shingles(b),union=new Set([...sa,...sb]).size,jaccard=union?[...sa].filter(x=>sb.has(x)).length/union:0,family=a.familyId===b.familyId,exact=documentText(a)===documentText(b),near=!exact&&jaccard>=.5;if(family||exact||near)pairs.push({left:a.id,right:b.id,family,exact,near,jaccard,crossSplit:a.split!==b.split,splits:[a.split,b.split]});}return pairs;}
export const bpeSpecial={pad:0,bos:1,eos:2,separator:3} as const;
export type BpeField={id:string;documentId:string;split:LineageSplit;text:string};
export type BpeMerge={id:number;left:number;right:number;pairCount:number;applications:number;bytes:number[]};
export type ByteBpe={version:typeof byteBpeVersion;trainingFieldIds:string[];trainingDocumentIds:string[];merges:BpeMerge[];tokenBytes:number[][];checksum:string};
const rawBytes=(text:string)=>{for(let i=0;i<text.length;i++){const c=text.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const next=text.charCodeAt(++i);assert(next>=0xdc00&&next<=0xdfff,'Text contains an unpaired Unicode surrogate');}else assert(c<0xdc00||c>0xdfff,'Text contains an unpaired Unicode surrogate');}return Array.from(new TextEncoder().encode(text));};
function replacePair(tokens:number[],left:number,right:number,id:number){const result:number[]=[];let applications=0;for(let i=0;i<tokens.length;i++){if(tokens[i]===left&&tokens[i+1]===right){result.push(id);applications++;i++;}else result.push(tokens[i]);}return{tokens:result,applications};}
export function trainByteBpe(fields:BpeField[],budget:number):ByteBpe{
 assert(int(budget,0,40)&&Array.isArray(fields)&&fields.length>0&&fields.length<=128,'Bounded training fields and merge budget required');assert(new Set(fields.map(x=>x.id)).size===fields.length&&fields.every(x=>x.split==='train'&&typeof x.id==='string'&&typeof x.documentId==='string'&&typeof x.text==='string'&&rawBytes(x.text).length<=2000),'Tokenizer fitting accepts unique training fields only');
 let sequences=fields.map(x=>rawBytes(x.text).map(b=>b+4));const tokenBytes=[[],[],[],[],...Array.from({length:256},(_,i)=>[i])],merges:BpeMerge[]=[];
 for(let step=0;step<budget;step++){const counts=new Map<string,{left:number;right:number;count:number}>();for(const tokens of sequences)for(let j=0;j<tokens.length-1;j++){const left=tokens[j],right=tokens[j+1],key=left+':'+right,old=counts.get(key);counts.set(key,{left,right,count:(old?.count??0)+1});}const best=[...counts.values()].sort((a,b)=>b.count-a.count||a.left-b.left||a.right-b.right)[0];if(!best||best.count<2)break;const id=tokenBytes.length,bytes=[...tokenBytes[best.left],...tokenBytes[best.right]];tokenBytes.push(bytes);let applications=0;sequences=sequences.map(tokens=>{const merged=replacePair(tokens,best.left,best.right,id);applications+=merged.applications;return merged.tokens;});merges.push({id,left:best.left,right:best.right,pairCount:best.count,applications,bytes});}
 const model={version:byteBpeVersion,trainingFieldIds:fields.map(x=>x.id),trainingDocumentIds:[...new Set(fields.map(x=>x.documentId))],merges,tokenBytes};return{...model,checksum:lineageChecksum(model)};
}
export function encodeByteBpe(text:string,model:ByteBpe){assert(typeof text==='string'&&rawBytes(text).length<=2000,'Bounded text required');let tokens=rawBytes(text).map(x=>x+4);for(const merge of model.merges)tokens=replacePair(tokens,merge.left,merge.right,merge.id).tokens;return tokens;}
export function decodeByteBpe(tokens:number[],model:ByteBpe){assert(tokens.every(x=>int(x,4,model.tokenBytes.length-1)),'Only content tokens can be decoded as text');return new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(tokens.flatMap(x=>model.tokenBytes[x])));}
export function displayBpeToken(id:number,model:ByteBpe){if(id<4)return ['<pad>','<bos>','<eos>','<sep>'][id];const bytes=model.tokenBytes[id];assert(!!bytes,'Unknown token');try{return JSON.stringify(new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(bytes)));}catch{return 'bytes '+bytes.map(x=>x.toString(16).padStart(2,'0')).join(' ');}}
export type EncodedDocument={documentId:string;tokens:number[];sections:('boundary'|'prompt'|'response')[];responseMask:number[];promptTokenCount:number;responseTokenCount:number};
export function encodeLineageDocument(document:PreparedDocument,model:ByteBpe):EncodedDocument{const prompt=encodeByteBpe(document.normalizedPrompt,model),response=encodeByteBpe(document.normalizedResponse,model),tokens=[1,...prompt,3,...response,2],sections:EncodedDocument['sections']=['boundary',...prompt.map(()=>'prompt' as const),'boundary',...response.map(()=>'response' as const),'boundary'];return{documentId:document.id,tokens,sections,responseMask:tokens.slice(1).map((_,i)=>Number(i+1>prompt.length+1)),promptTokenCount:prompt.length,responseTokenCount:response.length};}
export type SampleDraw={documentId:string;epoch:number;positionInEpoch:number;globalCursor:number;instanceId:string};
export function sampleLineageDocuments(ids:string[],seed:number,cursor:number,count:number):SampleDraw[]{assert(ids.length>0&&new Set(ids).size===ids.length&&int(seed,1,999)&&int(cursor,0,1000)&&int(count,1,4),'Invalid sampler state');const sorted=[...ids].sort();return Array.from({length:count},(_,i)=>{const globalCursor=cursor+i,epoch=Math.floor(globalCursor/ids.length),positionInEpoch=globalCursor%ids.length,order=shuffle(sorted,(seed^Math.imul(epoch+1,0x9e3779b1))>>>0),documentId=order[positionInEpoch];return{documentId,epoch,positionInEpoch,globalCursor,instanceId:`draw-${globalCursor}:${documentId}`};});}
export type PackedSlot={slot:number;globalIndex:number|null;token:number;target:number;documentId:string|null;instanceId:string|null;documentPosition:number|null;section:EncodedDocument['sections'][number]|'padding';targetPosition:number|null;lossMask:0|1;attentionAllowed:number[]};
export function packLineageBatch(encoded:EncodedDocument[],draws:SampleDraw[],blockSize:number,objective:LineageInput['objective']){
 assert([16,32,64].includes(blockSize)&&['all-targets','response-only'].includes(objective),'Invalid packing configuration');const byId=new Map(encoded.map(x=>[x.documentId,x]));
 const stream=draws.flatMap(draw=>{const doc=byId.get(draw.documentId);assert(!!doc,'Sampled document missing from encoded corpus');return doc!.tokens.map((token,position)=>({token,documentId:draw.documentId,instanceId:draw.instanceId,position,section:doc!.sections[position],responseTarget:position>doc!.promptTokenCount+1}));});
 const blocks:PackedSlot[][]=Array.from({length:Math.ceil(stream.length/blockSize)},(_,block)=>Array.from({length:blockSize},(_,slot)=>{const index=block*blockSize+slot,source=stream[index],next=stream[index+1];if(!source)return{slot,globalIndex:null,token:0,target:0,documentId:null,instanceId:null,documentPosition:null,section:'padding',targetPosition:null,lossMask:0,attentionAllowed:[]};const sameDocument=next?.instanceId===source.instanceId,lossMask:0|1=sameDocument&&(objective==='all-targets'||next.responseTarget)?1:0;return{slot,globalIndex:index,token:source.token,target:sameDocument?next.token:0,documentId:source.documentId,instanceId:source.instanceId,documentPosition:source.position,section:source.section,targetPosition:sameDocument?next.position:null,lossMask,attentionAllowed:Array.from({length:slot+1},(_,j)=>j).filter(j=>stream[block*blockSize+j]?.instanceId===source.instanceId)};}));
 return{blocks,realTokens:stream.length,totalSlots:blocks.length*blockSize,paddingTokens:blocks.length*blockSize-stream.length,trainedTargets:blocks.flat().reduce((s,x)=>s+x.lossMask,0),crossBlockTargets:blocks.flat().filter(x=>x.slot===blockSize-1&&x.lossMask===1).length};
}
export function buildDataLineage(raw:unknown){
 const input=normalizeLineageInput(raw),assigned=assignLineageSplits(lineageCorpus,input.splitStrategy,input.splitSeed),seen=new Map<string,string>();
 const documents:PreparedDocument[]=assigned.map(d=>{const normalizedPrompt=normalizeLineageText(d.prompt,input.normalization),normalizedResponse=normalizeLineageText(d.response,input.normalization),key=JSON.stringify([normalizedPrompt,normalizedResponse]),duplicateOf=d.split==='train'?seen.get(key)??null:null;if(d.split==='train'&&!seen.has(key))seen.set(key,d.id);return{...d,normalizedPrompt,normalizedResponse,duplicateOf,excludedFromTraining:input.deduplicateTraining&&duplicateOf!==null};});
 const eligible=documents.filter(d=>d.split==='train'&&!d.excludedFromTraining),fields=eligible.flatMap(d=>[{id:d.id+':prompt',documentId:d.id,split:d.split,text:d.normalizedPrompt},{id:d.id+':response',documentId:d.id,split:d.split,text:d.normalizedResponse}]),tokenizer=trainByteBpe(fields,input.merges),encoded=documents.map(d=>encodeLineageDocument(d,tokenizer)),draws=sampleLineageDocuments(eligible.map(d=>d.id),input.sampleSeed,input.cursor,input.batchDocuments),packing=packLineageBatch(encoded,draws,input.blockSize,input.objective),duplicates=lineageDuplicates(documents);
 const manifest={version:dataLineageVersion,corpusVersion:lineageCorpusVersion,corpusChecksum:lineageChecksum(lineageCorpus),splitAssignments:documents.map(d=>({id:d.id,familyId:d.familyId,split:d.split})),excluded:documents.filter(d=>d.excludedFromTraining).map(d=>({id:d.id,duplicateOf:d.duplicateOf})),normalization:input.normalization,tokenizer:{version:byteBpeVersion,checksum:tokenizer.checksum,trainingDocumentIds:tokenizer.trainingDocumentIds,trainingFieldIds:tokenizer.trainingFieldIds,merges:tokenizer.merges.map(m=>({id:m.id,left:m.left,right:m.right,pairCount:m.pairCount,applications:m.applications})),vocabularySize:tokenizer.tokenBytes.length},sampler:{seed:input.sampleSeed,cursor:input.cursor,nextCursor:input.cursor+input.batchDocuments,draws},packing:{blockSize:input.blockSize,objective:input.objective,realTokens:packing.realTokens,totalSlots:packing.totalSlots,trainedTargets:packing.trainedTargets,blockChecksums:packing.blocks.map(lineageChecksum)}};
 return{input,documents,duplicates,tokenizer,encoded,draws,packing,manifest};
}
export function encodeLineageRecord(input:LineageInput,sourceContent:string){assert(typeof sourceContent==='string'&&sourceContent.length<=100,'Invalid source content identity');const result=buildDataLineage(input);return JSON.stringify({schemaVersion:1,modelVersion:dataLineageVersion,sourceContent,input:result.input,manifest:result.manifest});}
export function readLineageRecord(raw:string){assert(typeof raw==='string'&&rawBytes(raw).length<=20000,'Lineage record exceeds 20,000 bytes');const value:unknown=JSON.parse(raw);exactObject(value,['schemaVersion','modelVersion','sourceContent','input','manifest']);assert(value.schemaVersion===1&&value.modelVersion===dataLineageVersion&&typeof value.sourceContent==='string'&&value.sourceContent.length<=100,'Incompatible lineage record');const result=buildDataLineage(value.input);assert(canonicalJson(value.manifest)===canonicalJson(result.manifest),'Recorded corpus, merges, sampler or packed batch do not reproduce this model');return{input:result.input,sourceContent:value.sourceContent as string,manifest:result.manifest};}
