/** Dimensioned, deliberately bounded educational models. No proprietary defaults. */
const nonnegative=(x:number,name:string)=>{if(!Number.isFinite(x)||x<0)throw new RangeError(`${name} must be finite and nonnegative`);return x;};
const positive=(x:number,name:string)=>{nonnegative(x,name);if(x===0)throw new RangeError(`${name} must be positive`);return x;};
const fraction=(x:number,name:string)=>{nonnegative(x,name);if(x>1)throw new RangeError(`${name} must be ≤1`);return x;};
export function waferYield(diameterMm:number,edgeMm:number,dieMm2:number,defectsCm2:number,cluster=3){
 const d=positive(diameterMm,'diameter')-2*nonnegative(edgeMm,'edge exclusion');positive(d,'usable diameter');positive(dieMm2,'die area');nonnegative(defectsCm2,'defect density');positive(cluster,'cluster factor');
 const gross=Math.max(0,Math.floor(Math.PI*d*d/(4*dieMm2)-Math.PI*d/Math.sqrt(2*dieMm2)));
 const exposure=dieMm2/100*defectsCm2,poisson=Math.exp(-exposure),clustered=(1+exposure/cluster)**(-cluster);
 return {gross,poisson,clustered,good:gross*poisson,clusteredGood:gross*clustered};
}
export function patternWindow(wavelengthNm:number,na:number,k1=.4,k2=.5){positive(wavelengthNm,'wavelength');positive(na,'NA');positive(k1,'k1');positive(k2,'k2');return {resolutionNm:k1*wavelengthNm/na,depthNm:k2*wavelengthNm/(na*na)};}
export function cmpResult(initialNm:number,rateNmMin:number,timeMin:number,variation:number){nonnegative(initialNm,'film');nonnegative(rateNmMin,'rate');nonnegative(timeMin,'time');fraction(variation,'variation');const removal=rateNmMin*timeMin;return {nominal:Math.max(0,initialNm-removal),thick:Math.max(0,initialNm-removal*(1-variation)),thin:Math.max(0,initialNm-removal*(1+variation)),overpolish:Math.max(0,removal-initialNm)};}
export function assemblyYield(incoming:number,bondYield:number,stages:number,finalYield:number){nonnegative(incoming,'incoming screened assemblies');fraction(bondYield,'stage yield');fraction(finalYield,'final yield');if(!Number.isInteger(stages)||stages<1)throw new RangeError('stages must be a positive integer');const counts=[incoming];for(let i=0;i<stages;i++)counts.push(counts.at(-1)!*bondYield);counts.push(counts.at(-1)!*finalYield);return counts;}
export function hbmIntensity(bits:number,relative:number,yieldFraction:number,mode:'geometric'|'empirical'){nonnegative(bits,'normalized demand');positive(relative,'relative intensity');positive(yieldFraction,'yield');fraction(yieldFraction,'yield');return bits*relative/(mode==='geometric'?yieldFraction:1);}
export type CapacityInput={logic:number;hbm:number;interposer:number;substrate:number;assembly:number;logicPer:number;hbmPer:number;yield:number};
export function packageCapacity(v:CapacityInput){Object.entries(v).forEach(([k,n])=>nonnegative(n,k));positive(v.logicPer,'logic/package');positive(v.hbmPer,'HBM/package');fraction(v.yield,'assembly yield');const stages=[{name:'Logic dies',rate:v.logic/v.logicPer},{name:'HBM stacks',rate:v.hbm/v.hbmPer},{name:'Interposers',rate:v.interposer},{name:'Substrates',rate:v.substrate},{name:'Assembly',rate:v.assembly}];const raw=Math.min(...stages.map(s=>s.rate));return {stages,raw,good:raw*v.yield,limiting:stages.filter(s=>Math.abs(s.rate-raw)<1e-8).map(s=>s.name)};}
export function capacityRamp(v:CapacityInput,months:number,qualificationMonth:number,rampMonths:number,demand:number){if(!Number.isInteger(months)||months<1)throw new RangeError('months');nonnegative(qualificationMonth,'qualification');positive(rampMonths,'ramp');nonnegative(demand,'demand');const cap=packageCapacity(v);let inventory=0,backlog=0;return Array.from({length:months},(_,i)=>{const ready=i+1>=qualificationMonth;const ramp=ready?Math.min(1,(i+2-qualificationMonth)/rampMonths):0;const produced=cap.good*ramp;const requested=demand+backlog;const delivered=Math.min(inventory+produced,requested);inventory=inventory+produced-delivered;backlog=requested-delivered;return {month:i+1,ready,ramp,produced,delivered,inventory,backlog};});}
export function matmulTraffic(n:number,tile:number,bytes=2){positive(n,'matrix width');positive(tile,'tile width');positive(bytes,'bytes');const t=Math.min(n,tile);return {flops:2*n**3,naiveBytes:(2*n**3+n*n)*bytes,tiledBytes:(2*n*n*Math.ceil(n/t)+n*n)*bytes,idealResidentBytes:3*n*n*bytes};}
export function memoryFootprint(paramsB:number,weightBits:number,batch:number,layers:number,context:number,kvHeads:number,headDim:number,kvBytes:number,training=false){[paramsB,weightBits,batch,layers,context,kvHeads,headDim,kvBytes].forEach(v=>positive(v,'memory input'));const weights=paramsB*1e9*weightBits/8;const kv=2*batch*layers*context*kvHeads*headDim*kvBytes;const optimizer=training?paramsB*1e9*12:0;return {weights,kv,optimizer,total:weights+kv+optimizer};}
export function ringAllReduce(bytes:number,ranks:number,gbps:number,latencyUs:number){nonnegative(bytes,'payload');positive(gbps,'bandwidth');nonnegative(latencyUs,'latency');if(!Number.isInteger(ranks)||ranks<1)throw new RangeError('ranks');const traffic=2*(ranks-1)/ranks*bytes;return {traffic,seconds:traffic/(gbps*1e9)+2*(ranks-1)*latencyUs*1e-6};}
export function hallWork(facilityMW:number,pue:number,rackKW:number,readyFraction:number,utilization:number,ratePerRack:number){nonnegative(facilityMW,'facility power');if(!Number.isFinite(pue)||pue<1)throw new RangeError('PUE must be ≥1');positive(rackKW,'rack power');fraction(readyFraction,'readiness');fraction(utilization,'utilization');nonnegative(ratePerRack,'work rate');const itMW=facilityMW/pue,racks=Math.floor(itMW*1000/rackKW),ready=Math.floor(racks*readyFraction);return {itMW,racks,ready,workRate:ready*utilization*ratePerRack,dayMWh:facilityMW*24};}
export function checkpointWork(intervalMinutes:number,checkpointMinutes:number,mtbfHours:number,restartMinutes:number){positive(intervalMinutes,'interval');nonnegative(checkpointMinutes,'checkpoint duration');positive(mtbfHours,'mean time between failures');nonnegative(restartMinutes,'restart');const overhead=checkpointMinutes/intervalMinutes+(intervalMinutes/2+restartMinutes)/(mtbfHours*60);return {overhead,retainedFraction:Math.max(0,1-overhead)};}
export function orbitalBudget(powerKW:number,tempK:number,emissivity:number,absorbedWm2:number,sunFraction:number,solarEfficiency:number,storageEfficiency:number,linkGbps:number,duty:number,requiredTBday:number,altitudeKm:number){positive(powerKW,'power');positive(tempK,'radiator temperature');positive(emissivity,'emissivity');fraction(emissivity,'emissivity');nonnegative(absorbedWm2,'absorbed flux');positive(sunFraction,'sun fraction');fraction(sunFraction,'sun fraction');positive(solarEfficiency,'solar efficiency');fraction(solarEfficiency,'solar efficiency');positive(storageEfficiency,'storage efficiency');fraction(storageEfficiency,'storage efficiency');nonnegative(linkGbps,'link rate');fraction(duty,'contact duty');nonnegative(requiredTBday,'required data');nonnegative(altitudeKm,'altitude');const flux=emissivity*5.670374419e-8*tempK**4-absorbedWm2;const solarW=powerKW*1000*(sunFraction+(1-sunFraction)/storageEfficiency)/sunFraction;const tbday=linkGbps*1e9/8*86400*duty/1e12;return {radiatorM2:flux>0?powerKW*1000/flux:null,solarM2:solarW/(1361*solarEfficiency),eclipseKWh:powerKW*(1-sunFraction)*1.5/storageEfficiency,tbday,linkMargin:tbday-requiredTBday,zenithMs:altitudeKm/299792.458*1000};}
export function siliconEconomics(nreMillion:number,volume:number,waferPrice:number,goodDies:number,packageCost:number,packageYield:number,softwareMillion:number){nonnegative(nreMillion,'NRE');positive(volume,'volume');nonnegative(waferPrice,'wafer cost');positive(goodDies,'good dies');nonnegative(packageCost,'assembly/test cost');positive(packageYield,'package yield');fraction(packageYield,'package yield');nonnegative(softwareMillion,'software cost');return {manufacturing:(waferPrice/goodDies+packageCost)/packageYield,development:(nreMillion+softwareMillion)*1e6/volume,total:(waferPrice/goodDies+packageCost)/packageYield+(nreMillion+softwareMillion)*1e6/volume};}
