import {simulateOperatingHall,OPERATING_HALL_VERSION,type OperatingHallScenario,type HallAdmission} from './operating-hall.ts';
import {buildCommissioningTrace,commissioningDefaults,commissioningVersion} from './commissioning-execution.ts';
import {createLifecycleRun,lifecycleModelVersion,lifecycleFingerprint,lifecycleParameterCount,lifecycleExamples,readLifecycleCheckpoint,serializeLifecycleCheckpoint,type LifecycleRun} from './model-lifecycle.ts';
import {createDistributedTrainingRun,beginDistributedRound,computeRankContribution,submitRankContribution,commitDistributedRound,serializeDistributedTrainingRun,readDistributedTrainingRun,distributedLifecycleVersion,type DistributedTrainingRun,type RankContribution} from './model-lifecycle-distributed.ts';

export const factoryVersion='factory-actual-checkpoint-1';
export const factoryModels={factory:factoryVersion,decoder:lifecycleModelVersion,distributed:distributedLifecycleVersion,commissioning:commissioningVersion,hall:OPERATING_HALL_VERSION} as const;
export type FactoryInput={seed:number;rounds:number;checkpointEvery:number;fault:'none'|'rank-stop'|'after-update'|'checkpoint-write'|'checkpoint-commit';faultRound:number;recover:boolean;readiness:'ready'|'firmware-mismatch'|'wrong-mapping';readyDelayS:number;slowRankDelayS:number;networkBytesS:number;networkLatencyS:number;storageBytesS:number;storageLimitBytes:number;feedLimitW:number;coolantFlowKgS:number};
export const factoryDefaults:FactoryInput={seed:7,rounds:3,checkpointEvery:2,fault:'checkpoint-write',faultRound:2,recover:true,readiness:'ready',readyDelayS:.2,slowRankDelayS:.3,networkBytesS:8192,networkLatencyS:.02,storageBytesS:65536,storageLimitBytes:1000000,feedLimitW:200,coolantFlowKgS:.01};
export const factoryConstants={jobId:'FACTORY-DECODER-01',ranks:2,parameters:lifecycleParameterCount,secondsPerValidTarget:.01,optimizerS:.02,checkpointCommitS:.05,recoveryWaitS:.4,packagesPerRack:2,runPackageW:50,checkpointPackageW:10,recoveryPackageW:5,auxiliaryRackW:20,conversionEfficiency:.9,pue:1.2,specificHeatJkgK:4180,maxCoolantRiseK:5} as const;
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
function exactKeys(v:unknown,keys:string[],name:string):asserts v is Record<string,unknown>{ensure(v&&typeof v==='object'&&!Array.isArray(v),name+' must be an object.');ensure(Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k)),name+' has unknown or missing fields.');}
export function normalizeFactoryInput(value:unknown):FactoryInput{
 exactKeys(value,Object.keys(factoryDefaults),'Factory inputs');const v=value as unknown as FactoryInput;
 const range=(key:keyof FactoryInput,min:number,max:number,integer=false)=>{const x=v[key];ensure(typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max&&(!integer||Number.isInteger(x)),`${key} must be ${integer?'an integer ':''}in [${min}, ${max}].`);};
 range('seed',1,10000,true);range('rounds',1,4,true);range('checkpointEvery',1,3,true);range('faultRound',1,v.rounds,true);range('readyDelayS',0,5);range('slowRankDelayS',0,2);range('networkBytesS',1024,131072,true);range('networkLatencyS',0,.5);range('storageBytesS',8192,1048576,true);range('storageLimitBytes',10000,4000000,true);range('feedLimitW',0,500);range('coolantFlowKgS',0,.05);
 ensure(['none','rank-stop','after-update','checkpoint-write','checkpoint-commit'].includes(v.fault),'Invalid fault.');ensure(['ready','firmware-mismatch','wrong-mapping'].includes(v.readiness),'Invalid readiness case.');ensure(typeof v.recover==='boolean','Recovery must be boolean.');return {...v};
}
export type FactoryPhase='readiness'|'source-read'|'rank-compute'|'network'|'optimizer'|'checkpoint-write'|'checkpoint-commit'|'recovery-wait'|'recovery-read';
export type FactoryPower={itW:number;facilityW:number;coolantHeatW:number;facilityOverheadW:number;coolantRiseK:number};
export type FactoryCounters={elapsedS:number;itEnergyJ:number;facilityEnergyJ:number;coolantHeatJ:number;facilityOverheadJ:number;executedUpdates:number;rolledBackUpdates:number;retainedUpdates:number;durableUpdates:number;rankComputations:number;rolledBackRankComputations:number;pendingRankComputations:number;rankBusyS:number;rankIdleSlotS:number;networkBytes:number;checkpointWriteBytes:number;checkpointReadBytes:number;sourceReadBytes:number;abortedCheckpointBytes:number;checkpointsCommitted:number;faults:number;barrierRejections:number};
export type FactoryCheckpoint={id:string;updates:number;bytes:number;fingerprint:string;raw:string;committedAtS:number};
export type FactoryStaging={updates:number;expectedBytes:number;writtenBytes:number;status:'writing'|'written'|'aborted'};
export type FactorySnapshot={jobId:string;generation:number;liveAvailable:boolean;liveUpdates:number;durableUpdates:number;optimizerStep:number;rng:number;dataDraws:number;fingerprint:string;weights:number[];moments:number[];squares:number[];roundId:string|null;ranks:{rank:number;status:'computing'|'computed'|'submitted';tokens:number;targets:number;finishAfterS:number;payloadBytes:number;firstNumerator:number|null}[];staging:FactoryStaging|null;counters:FactoryCounters};
export type FactoryEvent={index:number;atS:number;kind:string;detail:string;snapshot:FactorySnapshot};
export type FactorySegment={startS:number;endS:number;phase:FactoryPhase;detail:string;power:FactoryPower;networkBytes:number;checkpointWriteBytes:number;checkpointReadBytes:number;sourceReadBytes:number;start:FactoryCounters;end:FactoryCounters};
export type FactoryResult={modelVersion:typeof factoryVersion;input:FactoryInput;sourceIdentity:string;admission:HallAdmission;commissioning:{status:string;output:number[][]|null;events:number};powers:Record<'run'|'checkpoint'|'recovery'|'off',FactoryPower>;events:FactoryEvent[];segments:FactorySegment[];checkpoints:FactoryCheckpoint[];abortedCheckpoints:FactoryStaging[];final:FactoryCounters;finalRun:DistributedTrainingRun|null;durableRun:DistributedTrainingRun;status:'complete'|'blocked'|'stopped';reason:string;faultTriggered:boolean;equivalence:{weights:number;moments:number;squares:number;rngMatches:boolean;cursorMatches:boolean}|null};
export function factoryUtf8Bytes(raw:string){return new TextEncoder().encode(raw).byteLength;}
export function factoryHallScenario(input:FactoryInput):OperatingHallScenario{
 const c=factoryConstants;return {kind:'synthetic-operating-hall',version:OPERATING_HALL_VERSION,workload:{kind:'synthetic-fixed-global-workload',id:'factory-admission-probe',label:'Admission-only probe; not decoder operations',operationsPerStep:1,memoryBytesPerStep:1,networkBytesPerStep:0,checkpointBytes:1,assumptions:['Only admission and power coefficients are used; probe work, time and energy are discarded.']},installed:{racks:1,packagesPerRack:c.packagesPerRack},electrical:{facilityFeedLimitW:input.feedLimitW,rackBusV:48,rackInputLimitA:5,packageBusV:1,packageRailLimitA:60,conversionEfficiency:c.conversionEfficiency,pue:c.pue,auxiliaryRackW:c.auxiliaryRackW,packageRunW:c.runPackageW,packageCheckpointW:c.checkpointPackageW,packageRecoveryW:c.recoveryPackageW},cooling:{massFlowKgS:input.coolantFlowKgS,specificHeatJkgK:c.specificHeatJkgK,maxRiseK:c.maxCoolantRiseK},service:{computeOpsPerPackageS:1,memoryBytesPerPackageS:1,networkBytesPerRackS:input.networkBytesS,networkHallLimitBytesS:input.networkBytesS,checkpointBytesPerRackS:input.storageBytesS,checkpointHallLimitBytesS:input.storageBytesS,communication:'serialized'},commissioning:{electrical:0,thermal:0,fabric:0,software:0,operations:0},checkpoint:{intervalRunS:100,commitLatencyS:c.checkpointCommitS},faults:[],durationS:1,sampleS:1};
}
/** Reuse hall admission; reproduce its documented phase-power boundary from the same scenario parameters. */
export function factoryHallAdapter(input:FactoryInput){const scenario=factoryHallScenario(input),probe=simulateOperatingHall(scenario),admission=probe.admission,e=scenario.electrical;const power=(packageW:number):FactoryPower=>{const itW=admission.admittedRacks*(scenario.installed.packagesPerRack*packageW+e.auxiliaryRackW)/e.conversionEfficiency;return {itW,facilityW:itW*e.pue,coolantHeatW:itW,facilityOverheadW:itW*(e.pue-1),coolantRiseK:input.coolantFlowKgS?itW/(input.coolantFlowKgS*scenario.cooling.specificHeatJkgK):0};};return {admission,powers:{run:power(e.packageRunW),checkpoint:power(e.packageCheckpointW),recovery:power(e.packageRecoveryW),off:{itW:0,facilityW:0,coolantHeatW:0,facilityOverheadW:0,coolantRiseK:0}}};}
const zero=():FactoryCounters=>({elapsedS:0,itEnergyJ:0,facilityEnergyJ:0,coolantHeatJ:0,facilityOverheadJ:0,executedUpdates:0,rolledBackUpdates:0,retainedUpdates:0,durableUpdates:0,rankComputations:0,rolledBackRankComputations:0,pendingRankComputations:0,rankBusyS:0,rankIdleSlotS:0,networkBytes:0,checkpointWriteBytes:0,checkpointReadBytes:0,sourceReadBytes:0,abortedCheckpointBytes:0,checkpointsCommitted:0,faults:0,barrierRejections:0});
const vectorError=(a:number[],b:number[])=>Math.max(...a.map((x,i)=>Math.abs(x-b[i])));
/** Independent orchestration path: no faults, clocks, storage or hall counters. Core checks each reduction against its centralized objective. */
export function factoryReference(input:FactoryInput,source:LifecycleRun=createLifecycleRun({seed:input.seed})){let run=createDistributedTrainingRun(source);for(let i=0;i<input.rounds;i++){run=beginDistributedRound(run);for(const rank of run.round!.ranks)run=submitRankContribution(run,computeRankContribution(run,rank.rank));run=commitDistributedRound(run);}return run;}

export function buildFactoryExecution(value:FactoryInput=factoryDefaults,source?:LifecycleRun):FactoryResult{
 const input=normalizeFactoryInput(value),sourceRun=source??createLifecycleRun({seed:input.seed}),{admission,powers}=factoryHallAdapter(input);let run=createDistributedTrainingRun(sourceRun),liveAvailable=false,generation=1,staging:FactoryStaging|null=null,ranks:FactorySnapshot['ranks']=[],faultTriggered=false;
 const events:FactoryEvent[]=[],segments:FactorySegment[]=[],checkpoints:FactoryCheckpoint[]=[],abortedCheckpoints:FactoryStaging[]=[],c=zero();
 const initialRaw=serializeDistributedTrainingRun(run);let durable:FactoryCheckpoint={id:'checkpoint-0',updates:0,bytes:factoryUtf8Bytes(initialRaw),fingerprint:lifecycleFingerprint(run.state.weights),raw:initialRaw,committedAtS:0};checkpoints.push(durable);
 const snapshot=():FactorySnapshot=>({jobId:factoryConstants.jobId,generation,liveAvailable,liveUpdates:run.commits,durableUpdates:durable.updates,optimizerStep:run.state.optimizerStep,rng:run.rng,dataDraws:run.dataDraws,fingerprint:lifecycleFingerprint(run.state.weights),weights:[...run.state.weights],moments:[...run.state.moments],squares:[...run.state.squares],roundId:run.round?.id??null,ranks:structuredClone(ranks),staging:staging?{...staging}:null,counters:{...c}});
 const emit=(kind:string,detail:string)=>events.push({index:events.length,atS:c.elapsedS,kind,detail,snapshot:snapshot()});
 const advance=(phase:FactoryPhase,dt:number,detail:string,traffic:Partial<Pick<FactoryCounters,'networkBytes'|'checkpointWriteBytes'|'checkpointReadBytes'|'sourceReadBytes'>>={},busyRanks=0)=>{ensure(dt>=0&&Number.isFinite(dt),'Invalid modeled duration.');const power=phase==='readiness'?powers.off:phase.startsWith('checkpoint')?powers.checkpoint:phase.startsWith('recovery')||phase==='source-read'?powers.recovery:powers.run,start={...c};c.elapsedS+=dt;c.itEnergyJ+=power.itW*dt;c.facilityEnergyJ+=power.facilityW*dt;c.coolantHeatJ+=power.coolantHeatW*dt;c.facilityOverheadJ+=power.facilityOverheadW*dt;if(phase==='rank-compute'){c.rankBusyS+=busyRanks*dt;c.rankIdleSlotS+=(2-busyRanks)*dt;}for(const key of ['networkBytes','checkpointWriteBytes','checkpointReadBytes','sourceReadBytes'] as const)c[key]+=traffic[key]??0;segments.push({startS:start.elapsedS,endS:c.elapsedS,phase,detail,power,networkBytes:traffic.networkBytes??0,checkpointWriteBytes:traffic.checkpointWriteBytes??0,checkpointReadBytes:traffic.checkpointReadBytes??0,sourceReadBytes:traffic.sourceReadBytes??0,start,end:{...c}});};
 const finish=(status:FactoryResult['status'],reason:string):FactoryResult=>{let equivalence:FactoryResult['equivalence']=null;if(status==='complete'){const reference=factoryReference(input,sourceRun);equivalence={weights:vectorError(run.state.weights,reference.state.weights),moments:vectorError(run.state.moments,reference.state.moments),squares:vectorError(run.state.squares,reference.state.squares),rngMatches:run.rng===reference.rng,cursorMatches:run.dataDraws===reference.dataDraws};}return {modelVersion:factoryVersion,input,sourceIdentity:lifecycleFingerprint(sourceRun.weights),admission,commissioning:{status:commission.status,output:commission.finalOutput,events:commission.events.length},powers,events,segments,checkpoints,abortedCheckpoints,final:{...c},finalRun:liveAvailable?structuredClone(run):null,durableRun:readDistributedTrainingRun(durable.raw),status,reason,faultTriggered,equivalence};};
 const commission=buildCommissioningTrace({...commissioningDefaults,boot:input.readiness==='firmware-mismatch'?'abi-mismatch':'compatible',fault:input.readiness==='wrong-mapping'?'wrong-mapping':'none'});
 emit('offered',`${factoryConstants.jobId}: ${input.rounds} distributed updates requested. Checkpoint 0 is a provided source artifact; its prior creation is outside this run.`);
 if(!admission.admittedRacks){emit('admission-blocked',admission.reasons.join(' '));return finish('blocked','The declared facility or coolant limit admits no complete rack. No work or source read starts.');}
 advance('readiness',input.readyDelayS,'Assumed gate delay; commissioning test time/energy is outside the modeled incremental job boundary.');
 if(commission.status!=='complete'){emit('readiness-blocked',`Runtime commissioning returned ${commission.status}. The test operation cannot certify this job as ready.`);return finish('blocked','Runtime contract failed; a declared resource budget alone does not admit model execution.');}
 if(durable.bytes>input.storageLimitBytes){emit('storage-blocked',`Provided source needs ${durable.bytes} B; capacity is ${input.storageLimitBytes} B.`);return finish('blocked','The provided source checkpoint does not fit the declared storage boundary.');}
 emit('admitted','One synthetic rack and the runtime self-test pass. The two logical ranks each have one declared package slot.');
 advance('source-read',durable.bytes/input.storageBytesS,'Load complete provided source state.',{sourceReadBytes:durable.bytes});run=readDistributedTrainingRun(durable.raw);liveAvailable=true;emit('source-loaded','Weights, moments, optimizer step and sampler state loaded together.');
 const fault=()=>{faultTriggered=true;c.faults++;const lost=run.commits-durable.updates;c.rolledBackUpdates+=lost;c.rolledBackRankComputations+=2*lost+c.pendingRankComputations;c.pendingRankComputations=0;c.retainedUpdates=durable.updates;if(staging){staging={...staging,status:'aborted'};c.abortedCheckpointBytes+=staging.writtenBytes;abortedCheckpoints.push({...staging});}liveAvailable=false;emit('job-fault',`All workers stop. ${lost} volatile optimizer updates and the current rank contributions are unavailable. The last committed artifact remains checkpoint ${durable.updates}.`);run=structuredClone(readDistributedTrainingRun(durable.raw));ranks=[];staging=null;if(!input.recover){emit('stopped','Automatic recovery is disabled. Only the committed artifact remains; no model result is published.');return false;}advance('recovery-wait',factoryConstants.recoveryWaitS,'Assumed group repair/relaunch delay.');advance('recovery-read',durable.bytes/input.storageBytesS,'Read the last fully committed artifact.',{checkpointReadBytes:durable.bytes});run=readDistributedTrainingRun(durable.raw);generation++;liveAvailable=true;emit('restored',`Generation ${generation} resumes checkpoint ${durable.updates}, including optimizer moments, step ${run.state.optimizerStep}, RNG ${run.rng} and cursor ${run.dataDraws}.`);return true;};
 while(run.commits<input.rounds){
  run=beginDistributedRound(run);const round=run.round!,number=round.number,contributions=new Map<number,RankContribution>();
  ranks=round.ranks.map(r=>{const examples=r.exampleIds.map(id=>lifecycleExamples('train','copy').find(e=>e.id===id)!);const targets=examples.reduce((sum,e)=>sum+e.tokens.length-1,0);return {rank:r.rank,status:'computing',tokens:targets,targets,finishAfterS:targets*factoryConstants.secondsPerValidTarget+(r.rank===1?input.slowRankDelayS:0),payloadBytes:0,firstNumerator:null};});
  emit('round-reserved',`Round ${number} reserves four examples once: ${round.examples.join(', ')}. All weights remain at optimizer step ${run.state.optimizerStep}.`);
  const completions=[...ranks].sort((a,b)=>a.finishAfterS-b.finishAfterS||a.rank-b.rank),lastFinish=Math.max(...ranks.map(r=>r.finishAfterS)),faultAt=lastFinish*.5,failHere=!faultTriggered&&input.fault==='rank-stop'&&number===input.faultRound;let elapsed=0,interrupted=false;
  for(const r of completions){if(failHere&&faultAt<r.finishAfterS){advance('rank-compute',faultAt-elapsed,'Whole-job fault interrupts the unfinished rank.',{},ranks.filter(x=>x.status==='computing').length);interrupted=true;break;}advance('rank-compute',r.finishAfterS-elapsed,`Concurrent rank interval ending at rank ${r.rank}.`,{},ranks.filter(x=>x.status==='computing').length);elapsed=r.finishAfterS;const contribution=computeRankContribution(run,r.rank);contributions.set(r.rank,contribution);Object.assign(ranks[r.rank],{status:'computed',payloadBytes:factoryUtf8Bytes(JSON.stringify(contribution)),firstNumerator:contribution.gradientSum[0]});c.rankComputations++;c.pendingRankComputations++;emit('rank-computed',`Rank ${r.rank}: ${contribution.tokens} valid targets, ${contribution.gradientSum.length} actual gradient numerators. Other ranks may still be computing.`);}
  if(interrupted){if(!fault())return finish('stopped','Job stopped before the optimizer barrier.');continue;}
  for(const r of ranks){const contribution=contributions.get(r.rank)!;advance('network',input.networkLatencyS+r.payloadBytes/input.networkBytesS,`Rank ${r.rank} sends one complete UTF-8 JSON contribution to the central reducer; payload is counted once.`,{networkBytes:r.payloadBytes});run=submitRankContribution(run,JSON.parse(JSON.stringify(contribution)) as RankContribution);r.status='submitted';emit('rank-delivered',`Rank ${r.rank} delivered ${r.payloadBytes} teaching-transport bytes. Its ${contribution.denominator} targets belong to this update.`);if(r.rank===0){let blocked=false;try{commitDistributedRound(run);}catch{blocked=true;}ensure(blocked,'Incomplete optimizer barrier unexpectedly passed.');c.barrierRejections++;emit('barrier-wait','An early commit is rejected: rank 1 has not delivered its complete current contribution. Weights and moments remain unchanged.');}}
  advance('optimizer',factoryConstants.optimizerS,'Assumed synchronized reduction, owner-update and reconstruction duration; the actual core result is checked against the centralized objective.');run=commitDistributedRound(run);c.executedUpdates++;c.retainedUpdates=run.commits;c.pendingRankComputations=0;emit('optimizer-committed',`Actual update ${run.commits} is complete in live memory. ${run.commits-durable.updates} updates remain volatile.`);
  if(!faultTriggered&&input.fault==='after-update'&&run.commits===input.faultRound){if(!fault())return finish('stopped','Correct live optimizer state was lost before a durable checkpoint.');continue;}
  const due=run.commits%input.checkpointEvery===0||run.commits===input.rounds;if(!due)continue;
  const raw=serializeDistributedTrainingRun(run),bytes=factoryUtf8Bytes(raw);if(durable.bytes+bytes>input.storageLimitBytes){emit('storage-blocked',`Copy-on-write needs ${durable.bytes} B of committed state plus ${bytes} B staged state; capacity ${input.storageLimitBytes} B. The older artifact stays intact.`);return finish('blocked','A replacement checkpoint cannot coexist with the last valid artifact. Live updates are retained but publication is blocked.');}
  staging={updates:run.commits,expectedBytes:bytes,writtenBytes:0,status:'writing'};emit('checkpoint-start',`Stage ${bytes} UTF-8 JSON bytes for actual state after update ${run.commits}. The old checkpoint is still authoritative.`);
  const cpFault=!faultTriggered&&run.commits>=input.faultRound&&(input.fault==='checkpoint-write'||input.fault==='checkpoint-commit');
  if(cpFault&&input.fault==='checkpoint-write'){const partial=Math.floor(bytes/2);advance('checkpoint-write',partial/input.storageBytesS,'Write only the first half of the new checkpoint.',{checkpointWriteBytes:partial});staging.writtenBytes=partial;emit('checkpoint-partial',`${partial}/${bytes} B written; this artifact cannot restore the model.`);if(!fault())return finish('stopped','Checkpoint write was incomplete.');continue;}
  advance('checkpoint-write',bytes/input.storageBytesS,'Write complete state while the training job is paused.',{checkpointWriteBytes:bytes});staging.writtenBytes=bytes;staging.status='written';emit('checkpoint-written','All bytes are staged. The commit marker has not completed; the old artifact remains authoritative.');
  if(cpFault&&input.fault==='checkpoint-commit'){advance('checkpoint-commit',factoryConstants.checkpointCommitS/2,'Failure before the atomic commit marker.');if(!fault())return finish('stopped','Written checkpoint lacked a completed commit marker.');continue;}
  advance('checkpoint-commit',factoryConstants.checkpointCommitS,'Blocking atomic commit marker; no checkpoint bytes move.');durable={id:`checkpoint-${run.commits}-generation-${generation}`,updates:run.commits,bytes,fingerprint:lifecycleFingerprint(run.state.weights),raw,committedAtS:c.elapsedS};checkpoints.push(durable);c.durableUpdates=run.commits;c.checkpointsCommitted++;staging=null;emit('checkpoint-committed',`Checkpoint ${run.commits} is now the authoritative complete artifact; previous storage may be reclaimed.`);
 }
 emit('published',`The durable ${input.rounds}-update artifact is ready for serving. Completion means the requested arithmetic and state survived, not model quality or production usefulness.`);return finish('complete','The requested actual updates are checkpointed and match the uninterrupted reference.');
}

export function sampleFactoryExecution(result:FactoryResult,atS:number){ensure(Number.isFinite(atS)&&atS>=0&&atS<=result.final.elapsedS,'Cursor is outside the trace.');const event=[...result.events].reverse().find(e=>e.atS<=atS)!,segment=result.segments.find(s=>atS>=s.startS&&atS<s.endS);if(!segment)return {event,segment:null,counters:{...event.snapshot.counters},fraction:0};const fraction=(atS-segment.startS)/(segment.endS-segment.startS),counters={...segment.start};for(const k of ['itEnergyJ','facilityEnergyJ','coolantHeatJ','facilityOverheadJ','rankBusyS','rankIdleSlotS','networkBytes','checkpointWriteBytes','checkpointReadBytes','sourceReadBytes'] as const)counters[k]+=(segment.end[k]-segment.start[k])*fraction;counters.elapsedS=atS;return {event,segment,counters,fraction};}
export function serializeFactoryInputs(input:FactoryInput){return JSON.stringify({schemaVersion:1,models:factoryModels,input:normalizeFactoryInput(input)},null,2);}
function checkModels(value:unknown){exactKeys(value,Object.keys(factoryModels),'Model dependencies');ensure(Object.entries(factoryModels).every(([key,version])=>value[key]===version),'The record uses another model dependency. Keep its original text.');}
export function readFactoryInputs(raw:string):FactoryInput{ensure(raw.length<=20000,'Factory input record exceeds 20,000 characters.');const record:unknown=JSON.parse(raw);exactKeys(record,['schemaVersion','models','input'],'Factory input record');ensure(record.schemaVersion===1,'Incompatible input schema.');checkModels(record.models);return normalizeFactoryInput(record.input);}
export function serializeFactoryWorkspace(input:FactoryInput,source:LifecycleRun){return JSON.stringify({schemaVersion:1,models:factoryModels,input:normalizeFactoryInput(input),sourceCheckpoint:JSON.parse(serializeLifecycleCheckpoint(source))});}
export function readFactoryWorkspace(raw:string){ensure(raw.length<=650000,'Factory workspace exceeds 650,000 characters.');const record:unknown=JSON.parse(raw);exactKeys(record,['schemaVersion','models','input','sourceCheckpoint'],'Factory workspace');ensure(record.schemaVersion===1,'Incompatible workspace schema.');checkModels(record.models);return {input:normalizeFactoryInput(record.input),sourceCheckpoint:readLifecycleCheckpoint(JSON.stringify(record.sourceCheckpoint))};}
