import {architecturePresets,architectureVersion} from './architecture-execution.ts';

export const matrixNetworkVersion='matrix-network-transfer-1' as const;
export const matrixNetworkLimits={maxTicks:512,maxRecordBytes:20000,maxCredits:4,maxFlits:10} as const;
export const matrixNetworkMetadata={experienceId:'network',schemaVersion:1,modelVersion:matrixNetworkVersion,sourceModelVersion:architectureVersion,scope:'Actual matrix operand bytes, identified bounded flits, receiver credits, assembly and matrix consumption; serial educational protocol with synthetic ticks.'};
export type MatrixNetworkInput={specimen:'two'|'three';tensor:'A'|'B';flitBytes:4|8|16;credits:1|2|3|4;linkTicks:number;creditTicks:number;receiverPauseTicks:number;consumeEveryTicks:number;fault:'none'|'omit'|'wrong-identity'|'duplicate'|'premature-consume'|'wrong-payload';faultSegment:number};
export const matrixNetworkDefaults:MatrixNetworkInput={specimen:'three',tensor:'B',flitBytes:8,credits:2,linkTicks:2,creditTicks:2,receiverPauseTicks:0,consumeEveryTicks:1,fault:'none',faultSegment:0};
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
function exact(value:unknown,names:string[],label:string):asserts value is Record<string,unknown>{ensure(value&&typeof value==='object'&&!Array.isArray(value),label+' must be an object');ensure(Object.keys(value).length===names.length&&names.every(k=>Object.hasOwn(value,k)),label+' has missing or unknown fields');}
const integer=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isInteger(v)&&v>=min&&v<=max;
export function normalizeMatrixNetworkInput(value:unknown):MatrixNetworkInput{
 exact(value,Object.keys(matrixNetworkDefaults),'Network input');for(const [key,values]of Object.entries({specimen:['two','three'],tensor:['A','B'],flitBytes:[4,8,16],credits:[1,2,3,4],fault:['none','omit','wrong-identity','duplicate','premature-consume','wrong-payload']}))ensure(values.includes(value[key] as never),'Invalid '+key);
 for(const [key,min,max]of [['linkTicks',1,8],['creditTicks',1,8],['receiverPauseTicks',0,24],['consumeEveryTicks',1,4]] as const)ensure(integer(value[key],min,max),'Invalid '+key);
 const n=value.specimen==='two'?2:3;ensure(integer(value.faultSegment,0,Math.ceil(n*n*4/(value.flitBytes as number))-1),'Fault segment exceeds this tensor/flit count');return {...value} as MatrixNetworkInput;
}
export function matrixNetworkWordBytes(value:number):number[]{ensure(integer(value,-2147483648,2147483647),'Expected a signed int32');const data=new Uint8Array(4);new DataView(data.buffer).setInt32(0,value,true);return [...data];}
export function matrixNetworkBytesWord(bytes:readonly number[]):number{ensure(Array.isArray(bytes)&&bytes.length===4&&Array.from(bytes).every(v=>integer(v,0,255)),'Expected four present byte values');return new DataView(Uint8Array.from(bytes).buffer).getInt32(0,true);}
/** Completeness gate used by both premature and ordinary consumer requests. */
export function inspectMatrixNetworkOperand(bytes:readonly (number|null)[],size:number){ensure(integer(size,2,3)&&Array.isArray(bytes)&&bytes.length===size*size*4,'Operand dimensions differ');ensure(Array.from(bytes).every(x=>x===null||integer(x,0,255)),'Operand contains invalid or absent array entries');const missingByteOffsets=Array.from(bytes.entries()).filter(([,v])=>v===null).map(([i])=>i);return{ready:missingByteOffsets.length===0,missingByteOffsets,matrix:missingByteOffsets.length?null:Array.from({length:size},(_,r)=>Array.from({length:size},(_,c)=>matrixNetworkBytesWord(bytes.slice(4*(r*size+c),4*(r*size+c)+4) as number[])))};}
export type MatrixNetworkFlit={sequence:number;segment:number;transferId:string;tensor:'A'|'B';offset:number;validBytes:number;bytes:number[]};
export type MatrixNetworkCounters={sentFlits:number;arrivedFlits:number;consumedFlits:number;acceptedFlits:number;rejectedFlits:number;creditsReturned:number;sentPayloadBytes:number;sentSlotBytes:number;arrivedSlotBytes:number;uniquePayloadBytes:number;backpressureTicks:number;pausedTicks:number;prematureAttempts:number;macs:number};
export type MatrixNetworkMac={index:number;outputId:string;aId:string;bId:string;row:number;column:number;k:number;a:number;b:number;product:number;before:number;after:number};
export type MatrixNetworkEvent={kind:'send'|'arrive'|'accept'|'reject'|'return-credit'|'backpressure'|'receiver-paused'|'consumer-blocked'|'ready'|'mac'|'publish'|'incomplete';message:string;sequence:number|null};
export type MatrixNetworkStep={tick:number;events:MatrixNetworkEvent[];credits:number;remainingSend:number[];inFlight:{sequence:number;segment:number;dueTick:number}[];receiver:number[];creditReturns:{sequence:number;dueTick:number}[];acceptedSegments:number[];destinationBytes:(number|null)[];counters:MatrixNetworkCounters;mac:MatrixNetworkMac|null;partialOutput:number[][];ready:boolean;published:boolean};
export const matrixNetworkAssumptions=[
 'One selected A or B buffer from the existing 2×2 or 3×3 matrix operation crosses one ordered link. The other input is already local. Actual signed int32 little-endian bytes are copied and consumed; no gradient, large-model or unrelated traffic substitutes for this operation.',
 'A credit reserves one receiver flit slot. A send spends one credit; an in-flight flit retains the reservation. Receiver dequeue, including rejected data, frees the slot and launches a delayed credit return. Credits + in-flight flits + queued flits + pending returns always equals the configured capacity.',
 'Each synthetic tick processes returned credits, link arrivals, at most one eligible receiver dequeue, at most one sender injection, readiness, and one later consumer MAC, in that order. Receiver dequeue occurs at ticks divisible by its service interval after its initial pause. Link and credit delays are positive integer ticks, not seconds, vendor cycles or measured throughput.',
 'The link is pipelined for one flit injection per tick. Flits use fixed declared byte slots; the last slot is zero-padded. Valid payload, padded slot bytes, duplicated/rejected traffic and unique accepted bytes have separate denominators. Metadata headers, credit-message bytes, arbitration, PHY coding, checksums and real transport framing have no byte/time cost here.',
 'The sender intentionally omits the chosen segment before injection in the omission fixture, so no credit is lost in transit. Wrong identity is rejected, duplicate identity is discarded, and a premature consumer attempt is blocked. There is no retransmission, probabilistic loss, routing, virtual channel allocation, congestion across multiple links or production protocol guarantee.',
 'Identity/range checks do not prove payload integrity. The wrong-payload fixture flips one data bit while keeping a valid header; accepted wrong bytes can change the result. An independent BigInt matrix calculation diagnoses the mismatch but never repairs the consumed operands. No CRC or authentication is claimed.',
 'Consumer MACs begin one tick after all unique identified segments are assembled; they can overlap trailing credits or a duplicate transfer. One MAC is assigned each tick, with exact bounded integer products/accumulations. This is an authored consumer schedule. Whole-run completion waits for network drainage and output publication; operand-ready, published and drained ticks are distinct.',
 'The finite FIFO and credit counters execute in one JavaScript process. Source buffers, destination and snapshots remain available for inspection; no device memory, network speed, energy or hardware fault measurements are made.',
];
export function buildMatrixNetwork(value:unknown){
 const input=normalizeMatrixNetworkInput(value),preset=architecturePresets[input.specimen],a=preset.a.map(r=>[...r]),b=preset.b.map(r=>[...r]),n=a.length,source=input.tensor==='A'?a:b;
 const workloadId=`matrix-${input.specimen}-int32-le-1`,transferId=`${workloadId}:${input.tensor}:transfer-0`,sourceBytes=source.flatMap(r=>r.flatMap(matrixNetworkWordBytes)),segmentCount=Math.ceil(sourceBytes.length/input.flitBytes),destination:(number|null)[]=sourceBytes.map(()=>null);
 const words=source.flatMap((row,r)=>row.map((value,c)=>({id:`${input.tensor}[${r},${c}]`,offset:4*(r*n+c),value,bytes:matrixNetworkWordBytes(value)})));
 const segments=Array.from({length:segmentCount},(_,segment)=>{const offset=segment*input.flitBytes,validBytes=Math.min(input.flitBytes,sourceBytes.length-offset);return{segment,offset,validBytes,bytes:[...sourceBytes.slice(offset,offset+validBytes),...Array(input.flitBytes-validBytes).fill(0)]};});
 const flits:MatrixNetworkFlit[]=[];
 for(const s of segments){if(input.fault==='omit'&&s.segment===input.faultSegment)continue;const flit:MatrixNetworkFlit={...s,bytes:[...s.bytes],sequence:flits.length,transferId,tensor:input.tensor};if(s.segment===input.faultSegment&&input.fault==='wrong-identity'){flit.transferId+=':stale';flit.tensor=input.tensor==='A'?'B':'A';}if(s.segment===input.faultSegment&&input.fault==='wrong-payload')flit.bytes[0]^=1;flits.push(flit);if(s.segment===input.faultSegment&&input.fault==='duplicate')flits.push({...flit,sequence:flits.length,bytes:[...flit.bytes]});}
 ensure(flits.length<=matrixNetworkLimits.maxFlits,'Flit budget exceeded');
 const counters:MatrixNetworkCounters={sentFlits:0,arrivedFlits:0,consumedFlits:0,acceptedFlits:0,rejectedFlits:0,creditsReturned:0,sentPayloadBytes:0,sentSlotBytes:0,arrivedSlotBytes:0,uniquePayloadBytes:0,backpressureTicks:0,pausedTicks:0,prematureAttempts:0,macs:0};
 let credits:number=input.credits,nextSend=0,readyTick:number|null=null,publishedTick:number|null=null,drainedTick:number|null=null,consumerA:number[][]|null=null,consumerB:number[][]|null=null;
 const inFlight:{sequence:number;segment:number;dueTick:number}[]=[],receiver:number[]=[],creditReturns:{sequence:number;dueTick:number}[]=[],accepted=new Set<number>(),partial=Array.from({length:n},()=>Array(n).fill(0) as number[]),steps:MatrixNetworkStep[]=[];
 for(let tick=0;tick<=matrixNetworkLimits.maxTicks;tick++){
  const events:MatrixNetworkEvent[]=[];let mac:MatrixNetworkMac|null=null;const event=(kind:MatrixNetworkEvent['kind'],message:string,sequence:number|null=null)=>events.push({kind,message,sequence});
  if(tick===0&&input.fault==='premature-consume'){const attempt=inspectMatrixNetworkOperand(destination,n);ensure(!attempt.ready&&attempt.matrix===null,'Premature consumer gate failed');counters.prematureAttempts++;event('consumer-blocked','Consumer requested operands before any identified destination bytes arrived; no MAC executed.');}
  while(creditReturns[0]?.dueTick<=tick){const r=creditReturns.shift()!;credits++;counters.creditsReturned++;event('return-credit','Receiver dequeue credit became visible to the sender.',r.sequence);}
  while(inFlight[0]?.dueTick<=tick){const f=inFlight.shift()!;receiver.push(f.sequence);counters.arrivedFlits++;counters.arrivedSlotBytes+=input.flitBytes;event('arrive','The reserved flit reached the finite receiver queue.',f.sequence);}
  if(receiver.length){if(tick<input.receiverPauseTicks){counters.pausedTicks++;event('receiver-paused','Receiver service is paused; buffered flits retain their credits.');}else if(tick%input.consumeEveryTicks===0){const sequence=receiver.shift()!,flit=flits[sequence],expected=segments[flit.segment];counters.consumedFlits++;creditReturns.push({sequence,dueTick:tick+input.creditTicks});
    const valid=expected&&flit.transferId===transferId&&flit.tensor===input.tensor&&flit.offset===expected.offset&&flit.validBytes===expected.validBytes&&flit.bytes.length===input.flitBytes;
    if(!valid||accepted.has(flit.segment)){counters.rejectedFlits++;event('reject',valid?'Duplicate segment discarded; destination bytes remain unchanged.':'Wrong transfer/tensor/range identity rejected; destination gap remains.',sequence);}
    else{for(let i=0;i<flit.validBytes;i++)destination[flit.offset+i]=flit.bytes[i];accepted.add(flit.segment);counters.acceptedFlits++;counters.uniquePayloadBytes+=flit.validBytes;event('accept',`Copied ${flit.validBytes} identified bytes into destination [${flit.offset}, ${flit.offset+flit.validBytes}).`,sequence);}
  }}
  if(nextSend<flits.length){if(credits>0){const f=flits[nextSend++];credits--;inFlight.push({sequence:f.sequence,segment:f.segment,dueTick:tick+input.linkTicks});counters.sentFlits++;counters.sentPayloadBytes+=f.validBytes;counters.sentSlotBytes+=input.flitBytes;event('send',`Sender spent one credit and injected ${f.validBytes} payload bytes in a ${input.flitBytes}-byte slot.`,f.sequence);}else{counters.backpressureTicks++;event('backpressure','Sender has pending work but no visible receiver credit.');}}
  if(readyTick===null&&accepted.size===segmentCount){ensure(destination.every(x=>x!==null),'Complete segment set has a byte gap');readyTick=tick;const operand=inspectMatrixNetworkOperand(destination,n);ensure(operand.ready&&operand.matrix,'Consumer operand is incomplete');const received=operand.matrix;consumerA=input.tensor==='A'?received:a.map(r=>[...r]);consumerB=input.tensor==='B'?received:b.map(r=>[...r]);event('ready','Every unique identified segment assembled; actual destination bytes are now eligible for consumption.');}
  if(readyTick!==null&&tick>readyTick&&counters.macs<n*n*n){const index=counters.macs,row=Math.floor(index/(n*n)),column=Math.floor(index/n)%n,k=index%n,av=consumerA![row][k],bv=consumerB![k][column],before=partial[row][column],product=av*bv,after=before+product;ensure(Number.isSafeInteger(after),'Accumulator left exact integer scope');partial[row][column]=after;mac={index,outputId:`C[${row},${column}]`,aId:`A[${row},${k}]`,bId:`B[${k},${column}]`,row,column,k,a:av,b:bv,product,before,after};counters.macs++;event('mac',`${mac.outputId}: ${before} + (${av} × ${bv}) = ${after}.`);if(counters.macs===n*n*n){publishedTick=tick;event('publish','All actual consumer MACs completed; C is available to its observer.');}}
  const drained=nextSend===flits.length&&inFlight.length===0&&receiver.length===0&&creditReturns.length===0;if(drained&&drainedTick===null)drainedTick=tick;
  if(drained&&readyTick===null)event('incomplete','Transport drained with missing accepted segments; consumer remains blocked and no output is published.');
  ensure(credits+inFlight.length+receiver.length+creditReturns.length===input.credits,'Credit conservation failed');ensure(receiver.length<=input.credits&&credits>=0,'Receiver capacity exceeded');
  steps.push({tick,events,credits,remainingSend:flits.slice(nextSend).map(f=>f.sequence),inFlight:structuredClone(inFlight),receiver:[...receiver],creditReturns:structuredClone(creditReturns),acceptedSegments:[...accepted].sort((a,b)=>a-b),destinationBytes:[...destination],counters:{...counters},mac,partialOutput:partial.map(r=>[...r]),ready:readyTick!==null,published:publishedTick!==null});
  if(drained&&(publishedTick!==null||readyTick===null))break;
 }
 ensure(steps.at(-1)!.tick<matrixNetworkLimits.maxTicks,'Bounded network did not drain');
 const reference=a.map(row=>b[0].map((_,column)=>Number(row.reduce((sum,x,k)=>sum+BigInt(x)*BigInt(b[k][column]),0n)))),finalOutput=publishedTick===null?null:partial.map(r=>[...r]),correct=finalOutput===null?null:JSON.stringify(finalOutput)===JSON.stringify(reference);
 return{version:matrixNetworkVersion,sourceVersion:architectureVersion,input,workloadId,transferId,a,b,sourceBytes,words,segments,flits,steps,finalOutput,reference,correct,consumerA,consumerB,outputWords:finalOutput?.flatMap((row,r)=>row.map((value,c)=>({id:`C[${r},${c}]`,value,bytes:matrixNetworkWordBytes(value)})))??[],status:finalOutput===null?'incomplete' as const:correct?'complete' as const:'output-mismatch' as const,totals:{...counters,expectedSegments:segmentCount,omittedSegments:input.fault==='omit'?1:0,payloadBytes:sourceBytes.length,paddedSlotBytes:segmentCount*input.flitBytes,readyTick,publishedTick,drainedTick,elapsedTicks:steps.at(-1)!.tick},assumptions:[...matrixNetworkAssumptions]};
}
export type MatrixNetworkResult=ReturnType<typeof buildMatrixNetwork>;
export function serializeMatrixNetworkRecord(input:MatrixNetworkInput){return JSON.stringify({schemaVersion:1,modelVersion:matrixNetworkVersion,sourceVersion:architectureVersion,input:normalizeMatrixNetworkInput(input)},null,2);}
export function readMatrixNetworkRecord(raw:string):MatrixNetworkInput{ensure(typeof raw==='string'&&new TextEncoder().encode(raw).length<=matrixNetworkLimits.maxRecordBytes,'Network record exceeds byte budget');const value:unknown=JSON.parse(raw);exact(value,['schemaVersion','modelVersion','sourceVersion','input'],'Network record');ensure(value.schemaVersion===1&&value.modelVersion===matrixNetworkVersion&&value.sourceVersion===architectureVersion,'Incompatible network record identity');return normalizeMatrixNetworkInput(value.input);}
