import type {ProcessRoute,ProcessStep} from './processes';
const step=(title:string,input:string,action:string,output:string,measure:string,why:string,lesson:string):ProcessStep=>({title,input,action,output,measure,why,lesson});
const routes:Record<string,ProcessRoute>={
 'hbm-tc-ncf-route':{id:'hbm-tc-ncf',name:'HBM thermocompression with non-conductive film',kind:'Representative bump/film sequence · no proprietary temperature, force or qualified tolerance',source:'https://news.samsung.com/global/samsung-develops-industry-first-36gb-hbm3e-12h-dram',steps:[
  step('Prepare the inputs','Screened bumped dies and compatible film','Verify surface condition, metallic interfaces, film state and handling route.','Traceable assembly inputs','Die identity, test coverage and surface condition','A screened die retains a defined coverage and residual escape risk.','hbm-stack-thermal-yield'),
  step('Prepare the film interface','Receiving and incoming die surfaces','Apply the non-conductive film at its specified wafer or die stage and preserve the intended interconnect geometry.','Film-prepared contact interface','Film thickness, uniformity and contamination','Film behavior affects support and flow; the metallic joints carry current.','hbm-tc-ncf-route'),
  step('Align and place','Film-prepared bumped die','Align the next die to its receiving pads while controlling die bow and handling force.','Aligned die pair','Placement error and warpage','Thin silicon and small joints couple mechanical control to electrical contact.','hbm-stack-height-budget'),
  step('Form the bonded interface','Aligned die pair','Apply the qualified thermal and force cycle for joint formation and polymer flow/cure.','Connected, supported die pair','Continuity, bond-line state and thermal/force history','TC-NCF is a specific thermocompression route, not every form of bump bonding.','hbm-tc-ncf-route'),
  step('Repeat and finish','Partly assembled stack','Repeat the selected stacking/finishing sequence, retaining genealogy and cumulative geometry.','Finished memory stack','Overall height, alignment accumulation and voids','Serial station occupancy is distinct from total fab cycle time.','hbm-bonding-process-selection'),
  step('Screen and qualify','Finished stack','Perform per-unit screening and separately evaluate product/process reliability with its defined method.','Accepted stack plus qualification evidence','Functional coverage, interface margins and reliability results','Initial pass yield does not establish every future system operating condition.','memory-system-qualification') ]},
 'hbm-mr-muf-route':{id:'hbm-mr-muf',name:'HBM mass reflow then molded underfill',kind:'Representative MR-MUF sequence · stabilization details depend on implementation',source:'https://news.skhynix.com/en/small-size-big-impact/',steps:[
  step('Prepare screened inputs','Thinned memory and base dies','Retain die maps and prepare the specified bump/surface condition.','Traceable assembly input set','Thickness variation, test coverage and surfaces','The route begins with known test scope, not perfect dies.','hbm-stack-thermal-yield'),
  step('Place and stabilize','Screened bumped dies','Align and stack the dies; use the stabilization steps required by the selected implementation.','Controlled pre-reflow stack','Placement error, bow and temporary hold','Advanced variants can change the placement and stabilization sequence.','hbm-mr-muf-route'),
  step('Reflow metal joints','Placed bump stack','Run the selected thermal operation to connect many metallic joints.','Electrically joined stack','Joint continuity, thermal history and shape','Reflow forms the electrical connection; molding is a separate operation.','hbm-mr-muf-route'),
  step('Fill and encapsulate','Reflowed stack','Fill inter-die spaces and the specified external regions with molding compound; manage flow, venting and cure.','Supported encapsulated stack','Fill completeness, voids and cure condition','Narrow gaps and trapped gas remain process constraints.','hbm-mr-muf-route'),
  step('Inspect and screen','Encapsulated memory','Inspect electrical paths, stack geometry and defects with appropriate methods.','Tested finished stack','Continuity, warpage, functional failures and test time','Batch reflow throughput can expose a slower fill, inspection or test station.','hbm-bonding-process-selection'),
  step('Release compatible output','Accepted stacks and product evidence','Release units under the qualified route and integrate only compatible package configurations.','Available qualified memory inputs','Yield denominator, compatibility and release status','A stack’s output rate and interface requirements propagate into package capacity.','memory-system-qualification') ]},
 'hbm-hybrid-bond-route':{id:'hbm-hybrid',name:'Hybrid-bond interface preparation and closure',kind:'Research-grounded reference · wafer-to-wafer and die-to-wafer are distinct routes',source:'https://www.imec-int.com/en/articles/wafer-wafer-hybrid-bonding-pushing-boundaries-400nm-interconnect-pitch',steps:[
  step('Create bonding surfaces','Completed circuitry and routing','Pattern the selected conductive pads and bonding dielectric.','Bonding metal/dielectric structure','Pad geometry, materials and layout','Hybrid bonding joins the conductive and dielectric interface without a solder-bump gap there.','hbm-hybrid-bond-route'),
  step('Planarize and measure','Patterned bonding surface','Polish and measure local copper topography, dielectric roughness and spatial variation.','Measured planarized interface','Copper recess, dishing, roughness and within-wafer variation','Average flatness cannot establish local bond readiness.','clean-planarize-surface'),
  step('Clean and preserve','Measured interface','Clean and prepare surfaces; for die-to-wafer, preserve their condition through singulation and die handling.','Prepared clean mating surfaces','Particle population, surface state and handling history','A wafer-to-wafer demonstration does not validate all die-to-wafer handling steps.','hbm-hybrid-bond-route'),
  step('Align and contact','Prepared mating surfaces','Align the selected pads and contact the surfaces using the chosen route.','Initially contacted structure','Overlay field, contact front and voids','Without a solder interface, solder self-alignment cannot be assumed.','hbm-hybrid-bond-route'),
  step('Anneal and close','Initially contacted structure','Complete the specified thermal process for the intended dielectric and conductive bond.','Permanently bonded interface','Thermal budget, electrical continuity and mechanical integrity','The process must fit the materials and completed circuitry.','hbm-hybrid-bond-route'),
  step('Verify and qualify','Bonded test structure or product','Inspect the interface and electrical paths; report whether evidence comes from a research vehicle or complete product.','Scoped bond and qualification evidence','Test population, reliability method and full-stack function','A small-pitch research result alone does not establish shipping HBM yield or cost.','hbm-bonding-process-selection') ]},
};
const placement:ProcessRoute={id:'memory-placement',name:'Working-set placement → useful system work',kind:'Logical state and physical transfers · HBF options remain conditional scenarios',source:'https://www.deepspeed.ai/tutorials/zero-offload/',steps:[
 step('Inventory live state','Model, task and service target','List weights, mutable KV, activations, optimizer state, experts and workspace with lifetimes and precision.','Dimensioned memory contract','Bytes, mutation, reuse distance and access size','Parameter count alone does not determine live memory demand.','memory-working-set-placement'),
 step('Assign residency','Live-state inventory and usable tiers','Place hot local tiles, active state and colder objects while reserving staging and metadata capacity.','Residency and capacity plan','Usable capacity and simultaneous occupancy','A proposed HBF tier requires its own access and software contract.','hbf-read-tier-contract'),
 step('Plan access and transfers','Resident and offloaded objects','Issue reads, prefetches and writes with granularity, latency and concurrency assumptions visible.','Transfer schedule','Useful bytes, outstanding data, misses and writes','Read bandwidth does not certify latency, endurance or write behavior.','hbf-latency-prefetch'),
 step('Execute the workload phase','Ready state and executable kernels','Run training, prefill, decode or expert work with correct dependencies and ownership.','Computed outputs and updated state','Step time, KV growth, expert misses and correctness','Each phase places different demands on the hierarchy.','prefill-decode-tier-placement'),
 step('Close the physical paths','Measured traffic and compute demand','Aggregate links and account for rack power, heat rejection and service contention.','System resource and energy result','Work-normalized bytes, watts and accepted rate','An optimization can move the bottleneck beyond the package.','memory-to-hall-propagation'),
 step('Verify retained service','Operating integrated system','Validate outputs and recovery, report the configuration and retain only accepted useful work.','Measured deployment evidence','Quality, latency, interruptions and retained work','Specification, qualification, commissioning and operational evidence are different gates.','memory-system-qualification') ]};
export function memoryRouteFor(id:string):ProcessRoute|undefined{
 if(routes[id])return routes[id];
 if(['hbf-read-tier-contract','hbf-latency-prefetch','memory-working-set-placement','training-tier-placement','prefill-decode-tier-placement','moe-expert-tier-placement','memory-to-hall-propagation','memory-system-qualification'].includes(id))return placement;
 return undefined;
}
export const memoryProcessRoutes=[...Object.values(routes),placement];
