import {type LifecycleExposureJournal} from './model-lifecycle-workspace.ts';
import {createLifecycleRun,validateLifecycleRun,lifecycleSupervisedObjective,lifecycleExamples,lifecycleRandom,lifecycleFingerprint,lifecycleParameterCount,lifecycleModelVersion,readLifecycleCheckpoint,type LifecycleRun,type LifecycleExample} from './model-lifecycle.ts';
export const distributedLifecycleVersion='distributed-causal-gradient-2';
export const distributedLifecycleLimits={batch:4,ranks:3,rounds:24,restartsPerRank:8,events:100,maxBytes:1400000} as const;
export type DistributedConfig={partition:'1+3'|'2+2'|'3+1'|'1+1+2';weighting:'token'|'sample';objective:'next-token'|'response-only';domain:'copy'|'swap';batchPolicy:'unequal-lengths'|'seeded'};
export const distributedLifecycleDefaults:DistributedConfig={partition:'1+3',weighting:'token',objective:'next-token',domain:'copy',batchPolicy:'unequal-lengths'};
export const distributedLifecycleMetadata={experienceId:'distributed',schemaVersion:1,modelVersion:distributedLifecycleVersion,sourceModelVersion:lifecycleModelVersion,scope:'Actual 423-parameter decoder gradients, owned reduce-scatter shards, owner optimizer updates, all-gather reconstruction and authored failure/restart barriers. No network, distributed runtime or hardware timing is measured.',checkpointKind:'Full source lifecycle checkpoint plus explicit four-example distributed rounds'};
type OptimizerState={weights:number[];moments:number[];squares:number[];optimizerStep:number};
export type RankContribution={roundId:string;rank:number;attempt:number;baseFingerprint:string;exampleIds:string[];samples:number;tokens:number;denominator:number;lossSum:number;gradientSum:number[];tapeNodes:number};
export type DistributedRank={rank:number;attempt:number;status:'ready'|'failed'|'submitted';exampleIds:string[];contribution:RankContribution|null};
export type DistributedEvent={sequence:number;kind:'begin'|'fail'|'restart'|'submit'|'reduce-scatter'|'shard'|'all-gather'|'commit';rank:number|null;attempt:number|null;message:string};
export type DistributedRound={id:string;number:number;phase:'collecting'|'committed';config:DistributedConfig;before:OptimizerState;rngBefore:number;rngAfter:number;examples:string[];ranks:DistributedRank[];events:DistributedEvent[];collective:DistributedCollective|null};
export type DistributedShardOwner={owner:number;start:number;end:number;paddedCount:number};
export type DistributedGradientShard=DistributedShardOwner&{roundId:string;attempts:number[];denominator:number;numerator:number[];gradient:number[]};
export type DistributedUpdatedShard=DistributedShardOwner&{roundId:string;attempts:number[];optimizerStep:number;weights:number[];moments:number[];squares:number[]};
export type DistributedCollective={roundId:string;attempts:number[];phase:'reducing'|'gathered';gradientShards:(DistributedGradientShard|null)[];updatedShards:DistributedUpdatedShard[];replicas:{rank:number;gradient:number[];weights:number[]}[]};
/** Equal padded blocks model count alignment; the final padding is never an optimizer parameter. */
export function distributedShardOwners(ranks:number):DistributedShardOwner[]{ensure(finite(ranks,2,3,true),'Collective requires two or three ranks');const paddedCount=Math.ceil(lifecycleParameterCount/ranks);return Array.from({length:ranks},(_,owner)=>({owner,start:owner*paddedCount,end:Math.min((owner+1)*paddedCount,lifecycleParameterCount),paddedCount}));}
export type DistributedCommit={roundId:string;loss:number;denominator:number;gradient:number[];gradientNorm:number;clipScale:number;referenceMaxGradientError:number;referenceMaxWeightError:number;naiveMaxGradientError:number};
export type DistributedTrainingRun={schemaVersion:1;modelVersion:string;sourceCheckpoint:LifecycleRun;config:DistributedConfig;state:OptimizerState;rng:number;dataDraws:number;commits:number;round:DistributedRound|null;lastCommit:DistributedCommit|null;history:{roundId:string;loss:number;denominator:number;dataDraws:number;fingerprint:string}[]};
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
const finite=(x:unknown,min:number,max:number,integer=false)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max&&(!integer||Number.isInteger(x));
function keys(value:unknown,names:string[],label:string){ensure(value&&typeof value==='object'&&!Array.isArray(value),label+' must be an object');ensure(Object.keys(value).length===names.length&&names.every(k=>Object.hasOwn(value,k)),label+' has unknown or missing fields');}
function vector(value:unknown,label:string,positive=false):asserts value is number[]{ensure(Array.isArray(value)&&value.length===lifecycleParameterCount,label+' must have 423 entries');ensure(value.every(x=>finite(x,positive?0:-1e6,1e6)),label+' contains invalid values');}
const maxDiff=(a:number[],b:number[])=>a.reduce((m,x,i)=>Math.max(m,Math.abs(x-b[i])),0);
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const sourceExample=(id:string):LifecycleExample=>{const ex=lifecycleExamples('train','copy').concat(lifecycleExamples('train','swap')).find(e=>e.id===id);ensure(ex,'Only declared training examples may contribute');return ex;};
function optimizer(value:unknown):asserts value is OptimizerState{keys(value,['weights','moments','squares','optimizerStep'],'optimizer');const v=value as OptimizerState;vector(v.weights,'weights');ensure(v.weights.every(x=>Math.abs(x)<=100),'Weights exceed decoder bounds');vector(v.moments,'moments');vector(v.squares,'squares',true);ensure(finite(v.optimizerStep,0,624,true),'Invalid optimizer count');}
export function resolveDistributedConfig(value:Partial<DistributedConfig>={}):DistributedConfig{
 ensure(value&&typeof value==='object'&&!Array.isArray(value),'Invalid distributed configuration');ensure(Object.keys(value).every(k=>Object.hasOwn(distributedLifecycleDefaults,k)),'Unknown distributed option');const c={...distributedLifecycleDefaults,...value};ensure(['1+3','2+2','3+1','1+1+2'].includes(c.partition),'Invalid rank partition');ensure(['token','sample'].includes(c.weighting),'Invalid weighting');ensure(['next-token','response-only'].includes(c.objective),'Invalid objective');ensure(['copy','swap'].includes(c.domain),'Invalid domain');ensure(['unequal-lengths','seeded'].includes(c.batchPolicy),'Invalid batch policy');return c;
}
function event(round:DistributedRound,kind:DistributedEvent['kind'],message:string,rank:DistributedRank|null=null){ensure(round.events.length<distributedLifecycleLimits.events,'Event budget reached');round.events.push({sequence:round.events.length+1,kind,rank:rank?.rank??null,attempt:rank?.attempt??null,message});}
function summarize(weights:number[],ids:string[],config:DistributedConfig){
 const examples=ids.map(sourceExample),tokens=examples.reduce((s,e)=>s+(config.objective==='response-only'?e.mask.filter(Boolean).length:e.tokens.length-1),0),gradientSum=weights.map(()=>0);let lossSum=0,tapeNodes=0;
 // Per-example tapes make numerator/denominator ownership explicit at each rank.
 for(const ex of examples){const result=lifecycleSupervisedObjective(weights,[ex],config.objective==='response-only'),factor=config.weighting==='token'?result.targetCount:1;lossSum+=result.loss*factor;tapeNodes+=result.tapeNodes;for(let i=0;i<gradientSum.length;i++)gradientSum[i]+=result.gradient[i]*factor;}
 return{samples:examples.length,tokens,denominator:config.weighting==='token'?tokens:examples.length,lossSum,gradientSum,tapeNodes};
}
export function createDistributedTrainingRun(sourceCheckpoint:LifecycleRun=createLifecycleRun(),options:Partial<DistributedConfig>={}):DistributedTrainingRun{
 validateLifecycleRun(sourceCheckpoint);const source=structuredClone(sourceCheckpoint);return{schemaVersion:1,modelVersion:distributedLifecycleVersion,sourceCheckpoint:source,config:resolveDistributedConfig(options),state:{weights:[...source.weights],moments:[...source.moments],squares:[...source.squares],optimizerStep:source.optimizerStep},rng:source.rng,dataDraws:0,commits:0,round:null,lastCommit:null,history:[]};
}
function reserveBatch(rng:number,config:DistributedConfig){const pool=lifecycleExamples('train',config.domain),lengths=pool.map(e=>e.tokens.length),short=pool.filter(e=>e.tokens.length===Math.min(...lengths)),long=pool.filter(e=>e.tokens.length===Math.max(...lengths)),examples:string[]=[];for(let i=0;i<4;i++){const draw=lifecycleRandom(rng);rng=draw.state;const choices=config.batchPolicy==='seeded'?pool:i===0?short:long;examples.push(choices[Math.floor(draw.value*choices.length)].id);}return{rng,examples};}
export function beginDistributedRound(input:DistributedTrainingRun,patch:Partial<DistributedConfig>={}):DistributedTrainingRun{
 validateDistributedTrainingRun(input);ensure(!input.round||input.round.phase==='committed','Finish the active round before starting another');ensure(input.commits<distributedLifecycleLimits.rounds,'Distributed round budget reached');const run=structuredClone(input),config=resolveDistributedConfig({...run.config,...patch}),rngBefore=run.rng,reserved=reserveBatch(run.rng,config),examples=reserved.examples;run.rng=reserved.rng;
 const number=run.commits+1,id=`round-${number}-${lifecycleFingerprint(run.state.weights)}-${rngBefore}`,counts=config.partition.split('+').map(Number);let offset=0;
 const ranks=counts.map((count,rank)=>{const exampleIds=examples.slice(offset,offset+count);offset+=count;return{rank,attempt:1,status:'ready' as const,exampleIds,contribution:null};});
 run.config=config;run.dataDraws+=4;run.round={id,number,phase:'collecting',config,before:structuredClone(run.state),rngBefore,rngAfter:run.rng,examples,ranks,events:[],collective:null};event(run.round,'begin','Four training examples reserved; weights and optimizer remain unchanged until every rank contributes.');return run;
}
function active(input:DistributedTrainingRun,rank?:number){validateDistributedTrainingRun(input);ensure(input.round&&input.round.phase==='collecting','No collecting round');if(rank!==undefined)ensure(finite(rank,0,input.round.ranks.length-1,true),'Invalid rank');return input.round;}
export function computeRankContribution(input:DistributedTrainingRun,rank:number):RankContribution{
 const round=active(input,rank),r=round.ranks[rank];ensure(r.status==='ready','Rank must be ready to compute');return{roundId:round.id,rank,attempt:r.attempt,baseFingerprint:lifecycleFingerprint(round.before.weights),exampleIds:[...r.exampleIds],...summarize(round.before.weights,r.exampleIds,round.config)};
}
function validateContribution(c:unknown,round:DistributedRound,rank:DistributedRank,verifyNumbers=false):asserts c is RankContribution{
 keys(c,['roundId','rank','attempt','baseFingerprint','exampleIds','samples','tokens','denominator','lossSum','gradientSum','tapeNodes'],'contribution');const x=c as RankContribution;ensure(x.roundId===round.id&&x.rank===rank.rank&&x.attempt===rank.attempt,'Stale round, rank or attempt identity');ensure(x.baseFingerprint===lifecycleFingerprint(round.before.weights),'Stale weight identity');ensure(same(x.exampleIds,rank.exampleIds),'Contribution examples differ from rank assignment');ensure(x.samples===rank.exampleIds.length,'Sample denominator differs');const tokens=rank.exampleIds.map(sourceExample).reduce((s,e)=>s+(round.config.objective==='response-only'?e.mask.filter(Boolean).length:e.tokens.length-1),0);ensure(x.tokens===tokens&&x.denominator===(round.config.weighting==='token'?tokens:x.samples),'Invalid target/weight denominator');ensure(finite(x.lossSum,0,10000)&&finite(x.tapeNodes,1,1000000,true),'Invalid loss or graph count');vector(x.gradientSum,'gradient numerator');
 if(verifyNumbers){const expected=summarize(round.before.weights,rank.exampleIds,round.config);ensure(Math.abs(expected.lossSum-x.lossSum)<1e-10&&maxDiff(expected.gradientSum,x.gradientSum)<1e-10&&x.tapeNodes===expected.tapeNodes,'Contribution does not match the assigned model and batch');}
}
export function submitRankContribution(input:DistributedTrainingRun,contribution:RankContribution):DistributedTrainingRun{
 const round=active(input);ensure(finite(contribution?.rank,0,round.ranks.length-1,true),'Invalid rank');const r=round.ranks[contribution.rank];ensure(r.status==='ready','Rank is failed or already submitted');validateContribution(contribution,round,r,true);const run=structuredClone(input),target=run.round!.ranks[r.rank];target.status='submitted';target.contribution=structuredClone(contribution);event(run.round!,'submit',`Rank ${r.rank} submitted ${contribution.samples} examples and ${contribution.tokens} valid targets for attempt ${r.attempt}.`,target);return run;
}
export function failDistributedRank(input:DistributedTrainingRun,rank:number):DistributedTrainingRun{
 const round=active(input,rank);ensure(round.ranks[rank].status!=='failed','Rank is already failed');const run=structuredClone(input),r=run.round!.ranks[rank];r.status='failed';r.contribution=null;run.round!.collective=null;event(run.round!,'fail',`Rank ${rank} failed; uncommitted contribution and all in-flight owned shards were invalidated. No optimizer state changed.`,r);return run;
}
export function restartDistributedRank(input:DistributedTrainingRun,rank:number):DistributedTrainingRun{
 const round=active(input,rank);ensure(round.ranks[rank].status==='failed','Only failed ranks restart');ensure(round.ranks[rank].attempt<distributedLifecycleLimits.restartsPerRank+1,'Rank restart budget reached');const run=structuredClone(input),r=run.round!.ranks[rank];r.attempt++;r.status='ready';event(run.round!,'restart',`Rank ${rank} restarted at the same weights and reserved examples with attempt ${r.attempt}.`,r);return run;
}
function update(before:OptimizerState,gradient:number[],source:LifecycleRun){const norm=Math.hypot(...gradient),clipScale=Math.min(1,source.config.clipNorm/Math.max(norm,1e-30)),step=before.optimizerStep+1,moments:number[]=[],squares:number[]=[],weights=before.weights.map((w,i)=>{const g=gradient[i]*clipScale;moments[i]=.9*before.moments[i]+.1*g;squares[i]=.999*before.squares[i]+.001*g*g;const direction=source.config.optimizer==='sgd'?g:(moments[i]/(1-.9**step))/(Math.sqrt(squares[i]/(1-.999**step))+1e-8);return w-source.config.learningRate*direction;});return{state:{weights,moments,squares,optimizerStep:step},gradientNorm:norm,clipScale};}
export function centralizedDistributedReference(input:DistributedTrainingRun){
 validateDistributedTrainingRun(input);ensure(input.round,'No round to evaluate');const r=input.round,examples=r.examples.map(sourceExample);let loss:number,gradient:number[],denominator:number;
 if(r.config.weighting==='token'){const obj=lifecycleSupervisedObjective(r.before.weights,examples,r.config.objective==='response-only');loss=obj.loss;gradient=obj.gradient;denominator=obj.targetCount;}
 else{const values=examples.map(ex=>lifecycleSupervisedObjective(r.before.weights,[ex],r.config.objective==='response-only'));denominator=4;loss=values.reduce((s,v)=>s+v.loss,0)/4;gradient=r.before.weights.map((_,i)=>values.reduce((s,v)=>s+v.gradient[i],0)/4);}
 return{loss,gradient,denominator,...update(r.before,gradient,input.sourceCheckpoint)};
}
export function inspectDistributedReduction(input:DistributedTrainingRun){
 validateDistributedTrainingRun(input);ensure(input.round,'No round');const r=input.round,contributions=r.ranks.flatMap(rank=>rank.contribution?[rank.contribution]:[]),denominator=contributions.reduce((s,c)=>s+c.denominator,0);const gradient=r.before.weights.map((_,i)=>denominator?contributions.reduce((s,c)=>s+c.gradientSum[i],0)/denominator:0),naive=r.before.weights.map((_,i)=>contributions.length?contributions.reduce((s,c)=>s+c.gradientSum[i]/c.denominator,0)/contributions.length:0);return{complete:contributions.length===r.ranks.length&&r.ranks.every(rank=>rank.status==='submitted'),received:contributions.length,expected:r.ranks.length,denominator,loss:denominator?contributions.reduce((s,c)=>s+c.lossSum,0)/denominator:null,gradient,naive,naiveMaxGradientError:maxDiff(gradient,naive)};
}
function expectedGradientShard(round:DistributedRound,owner:number):DistributedGradientShard{
 const plan=distributedShardOwners(round.ranks.length)[owner];ensure(plan,'Invalid shard owner');ensure(round.ranks.every(r=>r.status==='submitted'&&r.contribution),'Reduce-scatter barrier: every current rank must submit');const denominator=round.ranks.reduce((n,r)=>n+r.contribution!.denominator,0),numerator=Array.from({length:plan.end-plan.start},(_,i)=>round.ranks.reduce((n,r)=>n+r.contribution!.gradientSum[plan.start+i],0));return{...plan,roundId:round.id,attempts:round.ranks.map(r=>r.attempt),denominator,numerator,gradient:numerator.map(n=>n/denominator)};
}
function validateGradientShard(value:unknown,round:DistributedRound,owner:number):asserts value is DistributedGradientShard{
 const expected=expectedGradientShard(round,owner);ensure(same(value,expected),'Stale, invalid or numerically incorrect owned gradient shard');
}
export function beginDistributedCollective(input:DistributedTrainingRun):DistributedTrainingRun{
 const round=active(input);ensure(!round.collective,'A reduce-scatter is already active');ensure(round.ranks.every(r=>r.status==='submitted'),'Reduce-scatter barrier: every current rank must submit');const run=structuredClone(input);run.round!.collective={roundId:round.id,attempts:round.ranks.map(r=>r.attempt),phase:'reducing',gradientShards:round.ranks.map(()=>null),updatedShards:[],replicas:[]};event(run.round!,'reduce-scatter','Rank-indexed owners reserve equal padded blocks; only real parameter positions are reduced and updated.');return run;
}
export function computeDistributedGradientShard(input:DistributedTrainingRun,owner:number):DistributedGradientShard{
 const round=active(input);ensure(round.collective?.phase==='reducing','Begin reduce-scatter first');ensure(finite(owner,0,round.ranks.length-1,true),'Invalid shard owner');ensure(round.collective.gradientShards[owner]===null,'Owner already submitted its shard');return expectedGradientShard(round,owner);
}
export function submitDistributedGradientShard(input:DistributedTrainingRun,shard:DistributedGradientShard):DistributedTrainingRun{
 const round=active(input);ensure(round.collective?.phase==='reducing','Begin reduce-scatter first');ensure(finite(shard?.owner,0,round.ranks.length-1,true),'Invalid shard owner');ensure(round.collective.gradientShards[shard.owner]===null,'Owner already submitted its shard');validateGradientShard(shard,round,shard.owner);const run=structuredClone(input);run.round!.collective!.gradientShards[shard.owner]=structuredClone(shard);event(run.round!,'shard',`Owner ${shard.owner} received reduced parameters [${shard.start}, ${shard.end}); denominator ${shard.denominator}.`,run.round!.ranks[shard.owner]);return run;
}
/** Ordered concatenation is the modeled gather; padded slots are stripped, never optimized. */
export function reconstructDistributedShards(shards:DistributedUpdatedShard[],round:DistributedRound):OptimizerState{
 const plans=distributedShardOwners(round.ranks.length);ensure(Array.isArray(shards)&&shards.length===plans.length,'All-gather barrier: missing owned parameter shard');const ordered=plans.map(p=>{const matches=shards.filter(s=>s.owner===p.owner);ensure(matches.length===1,'All-gather barrier: duplicate or missing owner');const s=matches[0];keys(s,['owner','start','end','paddedCount','roundId','attempts','optimizerStep','weights','moments','squares'],'updated shard');ensure(s.roundId===round.id&&same(s.attempts,round.ranks.map(r=>r.attempt))&&s.optimizerStep===round.before.optimizerStep+1,'Stale parameter shard round, attempt or step');ensure(s.start===p.start&&s.end===p.end&&s.paddedCount===p.paddedCount,'Incorrect parameter shard ownership');for(const key of ['weights','moments','squares'] as const)ensure(Array.isArray(s[key])&&s[key].length===p.end-p.start&&s[key].every(x=>finite(x,key==='squares'?0:-1e6,1e6)),'Invalid owned parameter values');return s;});return{weights:ordered.flatMap(s=>s.weights),moments:ordered.flatMap(s=>s.moments),squares:ordered.flatMap(s=>s.squares),optimizerStep:round.before.optimizerStep+1};
}
function executeOwnedUpdate(round:DistributedRound,source:LifecycleRun){
 const c=round.collective;ensure(c&&c.gradientShards.every(Boolean),'Owned-shard barrier: every current owner must submit before commit');const shards=c.gradientShards as DistributedGradientShard[];shards.forEach((s,i)=>validateGradientShard(s,round,i));const gradient=shards.flatMap(s=>s.gradient),norm=Math.hypot(...gradient),clipScale=Math.min(1,source.config.clipNorm/Math.max(norm,1e-30)),step=round.before.optimizerStep+1;
 // Each owner reads and advances only its retained slice of optimizer state.
 const updatedShards:DistributedUpdatedShard[]=shards.map(s=>{const weights:number[]=[],moments:number[]=[],squares:number[]=[];for(let local=0;local<s.gradient.length;local++){const i=s.start+local,g=s.gradient[local]*clipScale,m=.9*round.before.moments[i]+.1*g,v=.999*round.before.squares[i]+.001*g*g;moments.push(m);squares.push(v);const direction=source.config.optimizer==='sgd'?g:(m/(1-.9**step))/(Math.sqrt(v/(1-.999**step))+1e-8);weights.push(round.before.weights[i]-source.config.learningRate*direction);}return{owner:s.owner,start:s.start,end:s.end,paddedCount:s.paddedCount,roundId:round.id,attempts:[...c.attempts],optimizerStep:step,weights,moments,squares};});
 // Each replica reconstructs actual gradient and updated weight payloads from the owners.
 const replicas=round.ranks.map(r=>({rank:r.rank,gradient:shards.flatMap(s=>s.gradient),weights:reconstructDistributedShards(updatedShards,round).weights})),state=reconstructDistributedShards(updatedShards,round);return{gradient,gradientNorm:norm,clipScale,updatedShards,replicas,state};
}
/** Logical direct sender→owner/replica copies, not physical links, time or NCCL wire traffic. */
export function inspectDistributedCollective(input:DistributedTrainingRun){
 validateDistributedTrainingRun(input);ensure(input.round,'No round');const round=input.round,owners=distributedShardOwners(round.ranks.length),c=round.collective,transfers:{phase:'reduce-scatter'|'gradient-all-gather'|'weight-all-gather';from:number;to:number;start:number;end:number;values:number[];paddingZeros:number;logicalBytes:number}[]=[];
 if(c)for(const p of owners){const shard=c.gradientShards[p.owner];if(!shard)continue;for(const rank of round.ranks)if(rank.rank!==p.owner)transfers.push({phase:'reduce-scatter',from:rank.rank,to:p.owner,start:p.start,end:p.end,values:rank.contribution!.gradientSum.slice(p.start,p.end),paddingZeros:p.paddedCount-(p.end-p.start),logicalBytes:8*p.paddedCount});if(c.phase==='gathered')for(const rank of round.ranks)if(rank.rank!==p.owner){transfers.push({phase:'gradient-all-gather',from:p.owner,to:rank.rank,start:p.start,end:p.end,values:[...shard.gradient],paddingZeros:p.paddedCount-(p.end-p.start),logicalBytes:8*p.paddedCount});transfers.push({phase:'weight-all-gather',from:p.owner,to:rank.rank,start:p.start,end:p.end,values:[...c.updatedShards[p.owner].weights],paddingZeros:p.paddedCount-(p.end-p.start),logicalBytes:8*p.paddedCount});}}
 return{owners,received:c?.gradientShards.filter(Boolean).length??0,expected:owners.length,phase:c?.phase??'not-started',transfers,logicalBytes:transfers.reduce((n,t)=>n+t.logicalBytes,0),memory:owners.map(p=>({owner:p.owner,ownedParameters:p.end-p.start,ownedOptimizerScalars:2*(p.end-p.start),gradientShardScalars:p.end-p.start,replicatedWeightScalars:lifecycleParameterCount,paddedSlots:p.paddedCount-(p.end-p.start)}))};
}
export function commitDistributedRound(input:DistributedTrainingRun):DistributedTrainingRun{
 const round=active(input),reduction=inspectDistributedReduction(input);ensure(reduction.complete,'Optimizer barrier: every current rank must submit before commit');for(const r of round.ranks)validateContribution(r.contribution,round,r,true);
 // Existing callers retain one commit action; an explicitly started collective must finish every owner.
 let run=input;if(!round.collective){run=beginDistributedCollective(run);for(const r of round.ranks)run=submitDistributedGradientShard(run,computeDistributedGradientShard(run,r.rank));}
 const reference=centralizedDistributedReference(run),applied=executeOwnedUpdate(run.round!,run.sourceCheckpoint);ensure(maxDiff(reference.gradient,applied.gradient)<1e-9&&maxDiff(reference.state.weights,applied.state.weights)<1e-9,'Distributed result disagrees with centralized reference');run=structuredClone(run);run.state=applied.state;run.commits++;run.round!.phase='committed';Object.assign(run.round!.collective!,{phase:'gathered',updatedShards:applied.updatedShards,replicas:applied.replicas});run.lastCommit={roundId:round.id,loss:reduction.loss!,denominator:reduction.denominator,gradient:applied.gradient,gradientNorm:applied.gradientNorm,clipScale:applied.clipScale,referenceMaxGradientError:maxDiff(reference.gradient,applied.gradient),referenceMaxWeightError:maxDiff(reference.state.weights,applied.state.weights),naiveMaxGradientError:reduction.naiveMaxGradientError};run.history.push({roundId:round.id,loss:reduction.loss!,denominator:reduction.denominator,dataDraws:run.dataDraws,fingerprint:lifecycleFingerprint(run.state.weights)});event(run.round!,'all-gather','Each rank reconstructed the reduced gradient and updated weights from every owner; moments remain logically owner-local.');event(run.round!,'commit','All owned shards verified; one global clip, owner-local optimizer updates and one reconstructed optimizer step committed.');return run;
}
function validateCollective(round:DistributedRound,source:LifecycleRun,state:OptimizerState){
 const c=round.collective;if(!c){ensure(round.phase==='collecting','Committed round lacks owned collectives');return;}
 keys(c,['roundId','attempts','phase','gradientShards','updatedShards','replicas'],'collective');ensure(c.roundId===round.id&&same(c.attempts,round.ranks.map(r=>r.attempt)),'Stale collective attempts');ensure(round.ranks.every(r=>r.status==='submitted'),'Collective lacks current rank contributions');ensure(Array.isArray(c.gradientShards)&&c.gradientShards.length===round.ranks.length,'Incorrect owned gradient shard count');c.gradientShards.forEach((s,i)=>{if(s!==null)validateGradientShard(s,round,i);});
 if(round.phase==='collecting'){ensure(c.phase==='reducing'&&same(c.updatedShards,[])&&same(c.replicas,[]),'Optimizer shards or replicas changed before commit');}
 else{ensure(c.phase==='gathered','Committed collective is not gathered');const expected=executeOwnedUpdate(round,source);ensure(same(c.updatedShards,expected.updatedShards)&&same(c.replicas,expected.replicas),'Owned updates or all-gather replicas disagree');ensure(same(state,expected.state),'Committed optimizer disagrees with owned updates');}
}
export function validateDistributedTrainingRun(value:unknown):asserts value is DistributedTrainingRun{
 keys(value,['schemaVersion','modelVersion','sourceCheckpoint','config','state','rng','dataDraws','commits','round','lastCommit','history'],'distributed workspace');const v=value as DistributedTrainingRun;ensure(v.schemaVersion===1&&v.modelVersion===distributedLifecycleVersion,'Incompatible distributed workspace');validateLifecycleRun(v.sourceCheckpoint);keys(v.config,Object.keys(distributedLifecycleDefaults),'config');resolveDistributedConfig(v.config);optimizer(v.state);ensure(finite(v.commits,0,24,true)&&v.state.optimizerStep===v.sourceCheckpoint.optimizerStep+v.commits,'Invalid committed update count');ensure(finite(v.rng,1,0xffffffff,true)&&finite(v.dataDraws,0,96,true),'Invalid random/cursor state');ensure(Array.isArray(v.history)&&v.history.length===v.commits,'Invalid history length');for(const [historyIndex,h]of v.history.entries()){ensure(h.dataDraws===4*(historyIndex+1),'History cursor disagrees');keys(h,['roundId','loss','denominator','dataDraws','fingerprint'],'history');ensure(typeof h.roundId==='string'&&h.roundId.length<100&&finite(h.loss,0,1000)&&finite(h.denominator,1,32,true)&&finite(h.dataDraws,4,96,true)&&/^[0-9a-f]{8}$/.test(h.fingerprint),'Invalid history entry');}
 if(v.round){const r=v.round;keys(r,['id','number','phase','config','before','rngBefore','rngAfter','examples','ranks','events','collective'],'round');ensure(['collecting','committed'].includes(r.phase),'Invalid phase');const pending=Number(r.phase==='collecting');ensure(r.number===v.commits+pending&&v.dataDraws===4*(v.commits+pending),'Round cursor disagrees');ensure(same(r.config,v.config),'Round configuration differs');optimizer(r.before);ensure(r.before.optimizerStep===v.sourceCheckpoint.optimizerStep+r.number-1,'Wrong base optimizer step');ensure(finite(r.rngBefore,1,0xffffffff,true)&&r.rngAfter===v.rng,'Wrong round RNG');ensure(r.id===`round-${r.number}-${lifecycleFingerprint(r.before.weights)}-${r.rngBefore}`,'Wrong round identity');ensure(Array.isArray(r.examples)&&r.examples.length===4,'Four examples required');const reserved=reserveBatch(r.rngBefore,r.config);ensure(reserved.rng===r.rngAfter&&same(reserved.examples,r.examples),'Reserved batch disagrees with saved RNG and sampling policy');for(const id of r.examples){ensure(typeof id==='string','Invalid example identity');ensure(sourceExample(id).domain===r.config.domain,'Wrong training domain');}const counts=r.config.partition.split('+').map(Number);ensure(Array.isArray(r.ranks)&&r.ranks.length===counts.length,'Wrong rank count');let offset=0;for(const [i,rank]of r.ranks.entries()){keys(rank,['rank','attempt','status','exampleIds','contribution'],'rank');ensure(rank.rank===i&&finite(rank.attempt,1,9,true)&&['ready','failed','submitted'].includes(rank.status),'Invalid rank state');ensure(same(rank.exampleIds,r.examples.slice(offset,offset+counts[i])),'Rank assignment mismatch');offset+=counts[i];if(rank.status==='submitted')validateContribution(rank.contribution,r,rank);else ensure(rank.contribution===null,'Unsubmitted rank has contribution');}ensure(Array.isArray(r.events)&&r.events.length>0&&r.events.length<=100,'Invalid event count');for(const [i,e]of r.events.entries()){keys(e,['sequence','kind','rank','attempt','message'],'event');ensure(e.sequence===i+1&&['begin','fail','restart','submit','reduce-scatter','shard','all-gather','commit'].includes(e.kind)&&typeof e.message==='string'&&e.message.length<400,'Invalid event');ensure(e.rank===null||finite(e.rank,0,counts.length-1,true),'Invalid event rank');ensure(e.attempt===null||finite(e.attempt,1,9,true),'Invalid event attempt');}if(r.phase==='collecting')ensure(same(v.state,r.before),'Optimizer changed before commit');else ensure(r.ranks.every(x=>x.status==='submitted'),'Committed round lacks ranks');validateCollective(r,v.sourceCheckpoint,v.state);}
 else ensure(v.commits===0&&v.dataDraws===0&&v.history.length===0,'Missing active history');
 const original={weights:v.sourceCheckpoint.weights,moments:v.sourceCheckpoint.moments,squares:v.sourceCheckpoint.squares,optimizerStep:v.sourceCheckpoint.optimizerStep};if(v.commits===0)ensure(same(v.state,original),'Initial distributed state differs from source checkpoint');if(v.round?.number===1)ensure(same(v.round.before,original),'First round differs from source checkpoint');if(v.commits>0)ensure(v.history.at(-1)!.fingerprint===lifecycleFingerprint(v.state.weights),'Committed identity differs from current weights');
 if(v.lastCommit){const c=v.lastCommit;keys(c,['roundId','loss','denominator','gradient','gradientNorm','clipScale','referenceMaxGradientError','referenceMaxWeightError','naiveMaxGradientError'],'commit');vector(c.gradient,'committed gradient');ensure(v.commits>0&&c.roundId===v.history.at(-1)!.roundId&&finite(c.loss,0,1000)&&finite(c.denominator,1,32,true)&&finite(c.gradientNorm,0,1e6)&&finite(c.clipScale,0,1),'Invalid commit summary');for(const key of ['referenceMaxGradientError','referenceMaxWeightError','naiveMaxGradientError'] as const)ensure(finite(c[key],0,1e6),'Invalid difference');}else ensure(v.commits===0,'Missing commit summary');
}
export function serializeDistributedTrainingRun(run:DistributedTrainingRun){validateDistributedTrainingRun(run);const text=JSON.stringify(run);ensure(text.length<=distributedLifecycleLimits.maxBytes,'Distributed record too large');return text;}
export function readDistributedTrainingRun(text:string):DistributedTrainingRun{ensure(typeof text==='string'&&text.length<=distributedLifecycleLimits.maxBytes,'Distributed record too large');const result:unknown=JSON.parse(text);validateDistributedTrainingRun(result);if(result.round){for(const rank of result.round.ranks)if(rank.contribution)validateContribution(rank.contribution,result.round,rank,true);if(result.round.phase==='committed'){const reference=centralizedDistributedReference(result);ensure(maxDiff(reference.state.weights,result.state.weights)<1e-9&&maxDiff(reference.state.moments,result.state.moments)<1e-9&&maxDiff(reference.state.squares,result.state.squares)<1e-9,'Imported committed optimizer disagrees with centralized update');}}return structuredClone(result);}

/** Preserve final-test exposure independently of an imported training branch. */
export function retainDistributedExposure(run:DistributedTrainingRun,journal:LifecycleExposureJournal):DistributedTrainingRun{return {...run,sourceCheckpoint:journal.retain(run.sourceCheckpoint)};}
export function importDistributedWorkspace(text:string,journal:LifecycleExposureJournal,expectedRevision:number,currentRevision:number,config:Partial<DistributedConfig>={}):DistributedTrainingRun{
 ensure(typeof text==='string'&&text.length<=distributedLifecycleLimits.maxBytes,'Distributed record too large');const tag:unknown=JSON.parse(text);const candidate=tag&&typeof tag==='object'&&'modelVersion'in tag&&tag.modelVersion===lifecycleModelVersion?createDistributedTrainingRun(readLifecycleCheckpoint(text),config):readDistributedTrainingRun(text);
 ensure(expectedRevision===currentRevision,'The workspace changed during the file read; select the file again.');return retainDistributedExposure(candidate,journal);
}
