import {lifecycleDataVersion,lifecycleTokenizerVersion,lifecycleVocabulary,lifecycleExamples,type LifecycleExample,type LifecycleSplit,type LifecycleDomain} from './model-lifecycle-data.ts';
export * from './model-lifecycle-data.ts';
export const lifecycleModelVersion='causal-decoder-lifecycle-1';
export const lifecycleSchemaVersion=1;
export const lifecycleLimits={width:6,hidden:12,vocabulary:9,context:8,batch:2,maxUpdates:600,maxAdvance:40,maxCheckpointBytes:600000} as const;
export type LifecycleStage='pretrain'|'continue'|'sft'|'dpo'|'reward';
export type LifecycleConfig={seed:number;learningRate:number;optimizer:'adam'|'sgd';clipNorm:number;replayRate:number;beta:number;verifier:'correct'|'always-a'};
export const lifecycleDefaults:LifecycleConfig={seed:7,learningRate:.015,optimizer:'adam',clipNorm:1,replayRate:0,beta:.2,verifier:'correct'};
export const lifecycleSchemaMetadata={experienceId:'model-lifecycle',modelVersion:lifecycleModelVersion,schemaVersion:lifecycleSchemaVersion,dataVersion:lifecycleDataVersion,tokenizerVersion:lifecycleTokenizerVersion,limits:lifecycleLimits,checkpointKind:'full-training-state',timingBasis:'Actual JavaScript numerical computation; no vendor-cycle, device-speed or latency claim.',finalTestSeal:'Procedural exposure disclosure; fixture source remains inspectable.',optimizerSchedule:'Constant learning rate; moments and global optimizer counter persist across stage transitions.'} as const;
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
const keys=(value:unknown,allowed:string[],name:string)=>{ensure(value!==null&&typeof value==='object'&&!Array.isArray(value),`${name} must be an object.`);ensure(Object.keys(value).every(k=>allowed.includes(k)),`Unknown ${name} field.`);};
const finite=(n:unknown,min:number,max:number,name:string,integer=false):number=>{ensure(typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max&&(!integer||Number.isInteger(n)),`Invalid ${name}.`);return n;};
export function resolveLifecycleConfig(value:Partial<LifecycleConfig>={}):LifecycleConfig{
 keys(value,Object.keys(lifecycleDefaults),'configuration');const c={...lifecycleDefaults,...value};finite(c.seed,1,0xffffffff,'seed',true);finite(c.learningRate,.0001,.2,'learning rate');finite(c.clipNorm,.05,10,'gradient clip');finite(c.replayRate,0,1,'replay');finite(c.beta,.01,2,'reference beta');ensure(['adam','sgd'].includes(c.optimizer),'Invalid optimizer.');ensure(['correct','always-a'].includes(c.verifier),'Invalid verifier.');return c;
}
export const lifecycleStages:Record<LifecycleStage,{name:string;objective:string;data:string;mask:string}>={
 pretrain:{name:'Base pretraining',objective:'Mean next-token negative log likelihood',data:'Copy domain · training families only',mask:'Every shifted target, including prompt and end token'},
 continue:{name:'Domain continuation',objective:'Same next-token objective on a changed data mix',data:'Swap domain plus the selected copy replay fraction',mask:'Every shifted target'},
 sft:{name:'Supervised instruction tuning',objective:'Mean response-token negative log likelihood',data:'Swap demonstrations plus copy replay',mask:'Answer and end token only; prompt targets ignored'},
 dpo:{name:'Direct preference optimization',objective:'Negative log sigmoid of beta times policy/reference response log-odds difference',data:'Swap answer preferred to copy answer; synthetic labels',mask:'Both response sequences include answer and end token'},
 reward:{name:'Verifiable reward',objective:'Sampled REINFORCE loss plus exact two-action reference KL',data:'Training prompts; on-policy one-token a/b rollouts',mask:'Two-action answer distribution; no EOS or free-form rollout'},
};

/** Minimal reverse-mode scalar tape. Parent partials are captured at forward time. */
class Tape{
 v:number[]=[];g:number[]=[];parents:number[][]=[];partials:number[][]=[];
 node(value:number,parents:number[]=[],partials:number[]=[]){const i=this.v.length;this.v.push(value);this.g.push(0);this.parents.push(parents);this.partials.push(partials);return i;}
 add(a:number,b:number){return this.node(this.v[a]+this.v[b],[a,b],[1,1]);}
 mul(a:number,b:number){return this.node(this.v[a]*this.v[b],[a,b],[this.v[b],this.v[a]]);}
 scale(a:number,k:number){return this.node(this.v[a]*k,[a],[k]);}
 tanh(a:number){const v=Math.tanh(this.v[a]);return this.node(v,[a],[1-v*v]);}
 rsqrt(a:number){const v=1/Math.sqrt(this.v[a]);return this.node(v,[a],[-.5*v*v*v]);}
 sum(a:number[]){return this.node(a.reduce((s,i)=>s+this.v[i],0),a,a.map(()=>1));}
 logSoftmax(a:number[]){const max=Math.max(...a.map(i=>this.v[i])),exp=a.map(i=>Math.exp(this.v[i]-max)),z=exp.reduce((s,x)=>s+x,0),p=exp.map(x=>x/z),logz=max+Math.log(z);return a.map((i,j)=>this.node(this.v[i]-logz,a,p.map((x,k)=>(j===k?1:0)-x)));}
 softmax(a:number[]){const lp=this.logSoftmax(a);return lp.map(i=>{const p=Math.exp(this.v[i]);return this.node(p,[i],[p]);});}
 softplus(a:number){const x=this.v[a],p=x>=0?1/(1+Math.exp(-x)):Math.exp(x)/(1+Math.exp(x));return this.node(Math.max(x,0)+Math.log1p(Math.exp(-Math.abs(x))),[a],[p]);}
 backward(loss:number){this.g[loss]=1;for(let i=this.v.length-1;i>=0;i--)for(let j=0;j<this.parents[i].length;j++)this.g[this.parents[i][j]]+=this.g[i]*this.partials[i][j];}
}
const D=lifecycleLimits.width,H=lifecycleLimits.hidden,V=lifecycleLimits.vocabulary;
let parameterOffset=0;
function tensor(name:string,rows:number,columns:number){const t={name,rows,columns,offset:parameterOffset,size:rows*columns};parameterOffset+=t.size;return t;}
export const lifecycleTensors=[tensor('embedding',V,D),tensor('query',D,D),tensor('key',D,D),tensor('value',D,D),tensor('attentionOutput',D,D),tensor('feedForwardIn',D,H),tensor('feedForwardBias',1,H),tensor('feedForwardOut',H,D),tensor('feedForwardOutBias',1,D),tensor('unembedding',D,V),tensor('logitBias',1,V)];
export const lifecycleParameterCount=parameterOffset;
const layout=Object.fromEntries(lifecycleTensors.map(t=>[t.name,t]));
export function lifecycleParameterName(index:number){finite(index,0,parameterOffset-1,'parameter index',true);const t=lifecycleTensors.find(t=>index>=t.offset&&index<t.offset+t.size)!;return`${t.name}[${Math.floor((index-t.offset)/t.columns)},${(index-t.offset)%t.columns}]`;}
export function lifecycleRandom(state:number){let x=state>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return{state:x>>>0,value:(x>>>0)/4294967296};}
function checkWeights(w:unknown,name='weights'):asserts w is number[]{ensure(Array.isArray(w)&&w.length===parameterOffset,`Invalid ${name} shape.`);w.forEach(v=>finite(v,-100,100,name));}
type Forward={logits:number[][];logProbabilities:number[][];attention:number[][];hidden:number[][];embeddings:number[][];queries:number[][];keys:number[][];values:number[][]};
function forwardTape(t:Tape,p:number[],tokens:number[]):Forward{
 ensure(Array.isArray(tokens)&&tokens.length>=1&&tokens.length<=lifecycleLimits.context,'Invalid token count.');tokens.forEach(x=>finite(x,0,V-1,'token ID',true));
 const weight=(name:string,r:number,c:number)=>p[layout[name].offset+r*layout[name].columns+c];
 const linear=(x:number[],name:string,bias?:string)=>Array.from({length:layout[name].columns},(_,j)=>{const y=t.sum(x.map((i,k)=>t.mul(i,weight(name,k,j))));return bias?t.add(y,weight(bias,0,j)):y;});
 const norm=(x:number[])=>{const ms=t.add(t.scale(t.sum(x.map(i=>t.mul(i,i))),1/D),t.node(1e-5)),inv=t.rsqrt(ms);return x.map(i=>t.mul(i,inv));};
 const embeddings=tokens.map((id,pos)=>Array.from({length:D},(_,j)=>t.add(weight('embedding',id,j),t.node(.15*(j%2?Math.cos(pos/10000**((j-1)/D)):Math.sin(pos/10000**(j/D)))))));
 const normalized=embeddings.map(norm),queries=normalized.map(x=>linear(x,'query')),keys=normalized.map(x=>linear(x,'key')),values=normalized.map(x=>linear(x,'value'));
 const attention=queries.map((q,i)=>t.softmax(keys.slice(0,i+1).map(k=>t.scale(t.sum(q.map((v,j)=>t.mul(v,k[j]))),1/Math.sqrt(D)))));
 const hidden=embeddings.map((e,i)=>{const mixed=Array.from({length:D},(_,j)=>t.sum(attention[i].map((a,k)=>t.mul(a,values[k][j])))),projected=linear(mixed,'attentionOutput'),residual=e.map((a,j)=>t.add(a,projected[j])),ff=linear(linear(norm(residual),'feedForwardIn','feedForwardBias').map(v=>t.tanh(v)),'feedForwardOut','feedForwardOutBias');return residual.map((a,j)=>t.add(a,ff[j]));});
 const logits=hidden.map(x=>linear(x,'unembedding','logitBias')),logProbabilities=logits.map(x=>t.logSoftmax(x));return{embeddings,queries,keys,values,attention,hidden,logits,logProbabilities};
}
export function inspectLifecycleForward(weights:number[],tokens:number[]){checkWeights(weights);const t=new Tape(),p=weights.map(w=>t.node(w)),f=forwardTape(t,p,tokens);const values=(rows:number[][])=>rows.map(row=>row.map(i=>t.v[i]));return{...Object.fromEntries(Object.entries(f).map(([k,v])=>[k,values(v)])) as Record<keyof Forward,number[][]>,probabilities:f.logProbabilities.map(row=>row.map(i=>Math.exp(t.v[i]))),tapeNodes:t.v.length};}
export type LifecycleObjective={loss:number;gradient:number[];targetCount:number;tapeNodes:number;details:{name:string;value:number}[]};
export function lifecycleSupervisedObjective(weights:number[],examples:LifecycleExample[],responseOnly=false):LifecycleObjective{
 checkWeights(weights);ensure(examples.length>0&&examples.length<=4,'Need one to four examples.');const t=new Tape(),p=weights.map(w=>t.node(w)),terms:number[]=[];
 for(const ex of examples){checkExample(ex);const f=forwardTape(t,p,ex.tokens.slice(0,-1));for(let j=0;j<ex.tokens.length-1;j++)if(!responseOnly||ex.mask[j])terms.push(t.scale(f.logProbabilities[j][ex.tokens[j+1]],-1));}
 ensure(terms.length>0,'No trained targets.');const loss=t.scale(t.sum(terms),1/terms.length);t.backward(loss);return{loss:t.v[loss],gradient:p.map(i=>t.g[i]),targetCount:terms.length,tapeNodes:t.v.length,details:[{name:'Trained target denominator',value:terms.length}]};
}
function checkExample(ex:LifecycleExample){ensure(ex&&Array.isArray(ex.tokens)&&ex.tokens.length>=3&&ex.tokens.length<=9,'Invalid example length.');ex.tokens.forEach(x=>finite(x,0,V-1,'example token',true));ensure(ex.answerPosition===ex.tokens.length-3&&ex.answer===ex.tokens.at(-2),'Invalid answer position.');ensure(Array.isArray(ex.mask)&&ex.mask.length===ex.tokens.length-1&&ex.mask.every(x=>x===0||x===1),'Invalid loss mask.');}
function responseLog(t:Tape,p:number[],ex:LifecycleExample){checkExample(ex);const f=forwardTape(t,p,ex.tokens.slice(0,-1));return t.sum(f.logProbabilities.slice(ex.answerPosition).map((row,j)=>row[ex.tokens[ex.answerPosition+j+1]]));}
function opposite(ex:LifecycleExample){const tokens=[...ex.tokens];tokens[tokens.length-2]=ex.answer===1?2:1;return{...ex,tokens,answer:tokens[tokens.length-2]};}
export function lifecycleDpoObjective(weights:number[],reference:number[],chosen:LifecycleExample[],beta=.2):LifecycleObjective{
 checkWeights(weights);checkWeights(reference,'reference');finite(beta,.01,2,'beta');ensure(chosen.length>0&&chosen.length<=4,'Need one to four pairs.');const t=new Tape(),p=weights.map(w=>t.node(w)),terms:number[]=[],details:{name:string;value:number}[]=[];
 for(const ex of chosen){const rejected=opposite(ex),a=responseLog(t,p,ex),b=responseLog(t,p,rejected),rt=new Tape(),rp=reference.map(w=>rt.node(w)),ra=responseLog(rt,rp,ex),rb=responseLog(rt,rp,rejected),referenceOdds=rt.v[ra]-rt.v[rb],odds=t.add(t.add(a,t.scale(b,-1)),t.node(-referenceOdds)),margin=t.scale(odds,beta);terms.push(t.softplus(t.scale(margin,-1)));details.push({name:ex.id+' policy log odds',value:t.v[a]-t.v[b]},{name:ex.id+' reference log odds',value:referenceOdds},{name:ex.id+' beta-adjusted difference',value:t.v[margin]});}
 const loss=t.scale(t.sum(terms),1/terms.length);t.backward(loss);return{loss:t.v[loss],gradient:p.map(i=>t.g[i]),targetCount:chosen.length,tapeNodes:t.v.length,details};
}
export type LifecycleRollout={exampleId:string;action:number;probability:number;reward:number;baseline:number;advantage:number};
function rewardValue(action:number,answer:number,verifier:LifecycleConfig['verifier']){return Number(action===(verifier==='always-a'?1:answer));}
export function lifecycleRewardObjective(weights:number[],reference:number[],examples:LifecycleExample[],rng:number,beta=.2,verifier:LifecycleConfig['verifier']='correct'){
 checkWeights(weights);checkWeights(reference,'reference');ensure(examples.length>0&&examples.length<=4,'Need one to four reward prompts.');finite(rng,1,0xffffffff,'RNG',true);finite(beta,.01,2,'beta');ensure(['correct','always-a'].includes(verifier),'Invalid verifier.');
 const t=new Tape(),p=weights.map(w=>t.node(w)),terms:number[]=[],rollouts:LifecycleRollout[]=[],kls:number[]=[];
 for(const ex of examples){checkExample(ex);ensure(ex.answer===1||ex.answer===2,'Reward action must be a or b.');const f=forwardTape(t,p,ex.tokens.slice(0,ex.answerPosition+1)),lp=t.logSoftmax([f.logits.at(-1)![1],f.logits.at(-1)![2]]),prob=lp.map(i=>Math.exp(t.v[i]));const ref=inspectLifecycleForward(reference,ex.tokens.slice(0,ex.answerPosition+1)).logits.at(-1)!,max=Math.max(ref[1],ref[2]),z=Math.exp(ref[1]-max)+Math.exp(ref[2]-max),refLog=[ref[1]-max-Math.log(z),ref[2]-max-Math.log(z)];
  const baseline=prob.reduce((s,x,i)=>s+x*rewardValue(i+1,ex.answer,verifier),0),sampleTerms:number[]=[];
  for(let j=0;j<4;j++){const r=lifecycleRandom(rng);rng=r.state;const selected=r.value<prob[0]?0:1,action=selected+1,reward=rewardValue(action,ex.answer,verifier),advantage=reward-baseline;rollouts.push({exampleId:ex.id,action,probability:prob[selected],reward,baseline,advantage});sampleTerms.push(t.scale(lp[selected],-advantage));}
  const kl=t.sum(lp.map((v,j)=>{const q=t.node(prob[j],[v],[prob[j]]);return t.mul(q,t.add(v,t.node(-refLog[j])));}));kls.push(t.v[kl]);terms.push(t.add(t.scale(t.sum(sampleTerms),.25),t.scale(kl,beta)));
 }
 const loss=t.scale(t.sum(terms),1/terms.length);t.backward(loss);return{loss:t.v[loss],gradient:p.map(i=>t.g[i]),targetCount:rollouts.length,tapeNodes:t.v.length,details:[{name:'Mean exact two-action KL (nats)',value:kls.reduce((a,b)=>a+b,0)/kls.length},{name:'Sample mean reward',value:rollouts.reduce((s,r)=>s+r.reward,0)/rollouts.length}],rollouts,rng};
}
export type LifecycleEvaluation={split:LifecycleSplit;domain:LifecycleDomain;count:number;correct:number;answerLoss:number;tokenLoss:number;tokens:number;rows:{id:string;prompt:string;expected:number;predicted:number;probability:number;correct:boolean}[]};
function evaluateWeights(weights:number[],split:LifecycleSplit,domain:LifecycleDomain):LifecycleEvaluation{
 const examples=lifecycleExamples(split,domain);let loss=0,tokenLoss=0,tokens=0;const rows=examples.map(ex=>{const f=inspectLifecycleForward(weights,ex.tokens.slice(0,-1)),lp=f.logProbabilities[ex.answerPosition],predicted=lp.indexOf(Math.max(...lp));loss-=lp[ex.answer];for(let j=0;j<ex.tokens.length-1;j++){tokenLoss-=f.logProbabilities[j][ex.tokens[j+1]];tokens++;}return{id:ex.id,prompt:ex.text.split(' ').slice(0,ex.answerPosition+1).join(' '),expected:ex.answer,predicted,probability:Math.exp(lp[ex.answer]),correct:predicted===ex.answer};});return{split,domain,count:rows.length,correct:rows.filter(x=>x.correct).length,answerLoss:loss/rows.length,tokenLoss:tokenLoss/tokens,tokens,rows};
}
export type LifecycleStep={step:number;stage:LifecycleStage;loss:number;gradientNorm:number;clipScale:number;targets:number;exampleIds:string[];details:{name:string;value:number}[];rollouts:LifecycleRollout[]};
export type LifecycleRun={schemaVersion:1;modelVersion:string;dataVersion:string;tokenizerVersion:string;config:LifecycleConfig;stage:LifecycleStage;step:number;stageStep:number;rng:number;dataDraws:number;weights:number[];moments:number[];squares:number[];optimizerStep:number;reference:number[];parentFingerprint:string|null;history:LifecycleStep[];lastUpdate:{before:number[];gradient:number[];after:number[];tapeNodes:number}|null;finalOpened:boolean;finalReport:{atStep:number;fingerprint:string;copy:LifecycleEvaluation;swap:LifecycleEvaluation}|null};
export function lifecycleFingerprint(weights:number[]){checkWeights(weights);let h=2166136261;for(const c of weights.map(x=>x.toPrecision(17)).join(',')){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
export function createLifecycleRun(options:Partial<LifecycleConfig>={}):LifecycleRun{
 const config=resolveLifecycleConfig(options);let rng=config.seed;const weights=Array.from({length:parameterOffset},(_,i)=>{const r=lifecycleRandom(rng);rng=r.state;const t=lifecycleTensors.find(t=>i>=t.offset&&i<t.offset+t.size)!;return t.name.toLowerCase().includes('bias')?0:(r.value*2-1)*Math.sqrt(3/t.rows)*.45;});return{schemaVersion:1,modelVersion:lifecycleModelVersion,dataVersion:lifecycleDataVersion,tokenizerVersion:lifecycleTokenizerVersion,config,stage:'pretrain',step:0,stageStep:0,rng,dataDraws:0,weights,moments:weights.map(()=>0),squares:weights.map(()=>0),optimizerStep:0,reference:[...weights],parentFingerprint:null,history:[],lastUpdate:null,finalOpened:false,finalReport:null};
}
export function forkLifecycleRun(run:LifecycleRun,stage:LifecycleStage,patch:Partial<LifecycleConfig>={}):LifecycleRun{
 validateLifecycleRun(run);ensure(Object.hasOwn(lifecycleStages,stage),'Unknown training stage.');const next=structuredClone(run);next.config=resolveLifecycleConfig({...run.config,...patch});next.parentFingerprint=lifecycleFingerprint(run.weights);next.stage=stage;next.stageStep=0;next.reference=[...run.weights];return next;
}
export function advanceLifecycleRun(input:LifecycleRun,steps=1):LifecycleRun{
 validateLifecycleRun(input);finite(steps,1,lifecycleLimits.maxAdvance,'advance steps',true);ensure(input.step+steps<=lifecycleLimits.maxUpdates,'Update budget reached; start a new experiment.');const run=structuredClone(input);
 for(let n=0;n<steps;n++){
  const examples:LifecycleExample[]=[];for(let i=0;i<lifecycleLimits.batch;i++){const mix=lifecycleRandom(run.rng);run.rng=mix.state;const domain:LifecycleDomain=run.stage==='pretrain'||(['continue','sft'].includes(run.stage)&&mix.value<run.config.replayRate)?'copy':'swap',pool=lifecycleExamples('train',domain),draw=lifecycleRandom(run.rng);run.rng=draw.state;run.dataDraws++;examples.push(pool[Math.floor(draw.value*pool.length)]);}
  const obj=run.stage==='dpo'?lifecycleDpoObjective(run.weights,run.reference,examples,run.config.beta):run.stage==='reward'?lifecycleRewardObjective(run.weights,run.reference,examples,run.rng,run.config.beta,run.config.verifier):lifecycleSupervisedObjective(run.weights,examples,run.stage==='sft');
  if('rng' in obj)run.rng=obj.rng as number;const gradientNorm=Math.sqrt(obj.gradient.reduce((s,g)=>s+g*g,0)),clipScale=Math.min(1,run.config.clipNorm/Math.max(gradientNorm,1e-30)),before=[...run.weights];ensure(Number.isFinite(obj.loss)&&obj.gradient.every(Number.isFinite),'Non-finite training update; previous run preserved.');run.optimizerStep++;
  run.weights=run.weights.map((w,i)=>{const g=obj.gradient[i]*clipScale;run.moments[i]=.9*run.moments[i]+.1*g;run.squares[i]=.999*run.squares[i]+.001*g*g;const update=run.config.optimizer==='sgd'?g:(run.moments[i]/(1-.9**run.optimizerStep))/(Math.sqrt(run.squares[i]/(1-.999**run.optimizerStep))+1e-8);return w-run.config.learningRate*update;});checkWeights(run.weights);run.step++;run.stageStep++;
  run.history.push({step:run.step,stage:run.stage,loss:obj.loss,gradientNorm,clipScale,targets:obj.targetCount,exampleIds:examples.map(e=>e.id),details:obj.details,rollouts:'rollouts' in obj?obj.rollouts as LifecycleRollout[]:[]});run.lastUpdate={before,gradient:obj.gradient,after:[...run.weights],tapeNodes:obj.tapeNodes};
 }return run;
}
export function evaluateLifecycleRun(run:LifecycleRun,split:LifecycleSplit='development'){
 validateLifecycleRun(run);ensure(split!=='final'||run.finalOpened,'Final test remains sealed; reveal it explicitly.');return{copy:evaluateWeights(run.weights,split,'copy'),swap:evaluateWeights(run.weights,split,'swap')};
}
export function openLifecycleFinalTest(input:LifecycleRun):LifecycleRun{validateLifecycleRun(input);if(input.finalOpened)return structuredClone(input);const run=structuredClone(input);run.finalOpened=true;run.finalReport={atStep:run.step,fingerprint:lifecycleFingerprint(run.weights),copy:evaluateWeights(run.weights,'final','copy'),swap:evaluateWeights(run.weights,'final','swap')};return run;}
export function inspectLifecycleExample(run:LifecycleRun,example:LifecycleExample,responseOnly=run.stage==='sft'){
 validateLifecycleRun(run);ensure(example.split!=='final'||run.finalOpened,'Final inspection remains sealed.');return{example,forward:inspectLifecycleForward(run.weights,example.tokens.slice(0,-1)),objective:lifecycleSupervisedObjective(run.weights,[example],responseOnly),lossMask:example.tokens.slice(1).map((_,i)=>Number(!responseOnly||example.mask[i]===1))};
}
export function generateLifecycle(run:LifecycleRun,prompt:number[],mode:'greedy'|'sample'='greedy',seed=123){
 validateLifecycleRun(run);ensure(mode==='greedy'||mode==='sample','Unknown decoding mode.');finite(seed,1,0xffffffff,'generation seed',true);ensure(prompt.length>=1&&prompt.length<=7,'Generation prompt needs 1–7 tokens.');const tokens=[...prompt],steps:{input:number[];probabilities:number[];token:number}[]=[];let rng=seed;
 for(let i=0;i<2&&tokens.length<=lifecycleLimits.context;i++){const probabilities=inspectLifecycleForward(run.weights,tokens).probabilities.at(-1)!;let token=probabilities.indexOf(Math.max(...probabilities));if(mode==='sample'){const r=lifecycleRandom(rng);rng=r.state;let remaining=r.value;token=probabilities.length-1;for(let j=0;j<probabilities.length;j++){remaining-=probabilities[j];if(remaining<=0){token=j;break;}}}steps.push({input:[...tokens],probabilities,token});tokens.push(token);if(token===7)break;}return{tokens:tokens.slice(prompt.length),steps,rng,basis:'At most two autoregressive full-vocabulary tokens. Sampling has an independent RNG and changes no learned weights or training state.'};
}
export function lifecycleUnigramBaseline(split:LifecycleSplit='development',domain:LifecycleDomain='copy'){
 const counts=Array.from({length:V},()=>1);for(const ex of lifecycleExamples('train','copy'))for(const target of ex.tokens.slice(1))counts[target]++;const denominator=counts.reduce((a,b)=>a+b,0),p=counts.map(x=>x/denominator);let loss=0,n=0;for(const ex of lifecycleExamples(split,domain))for(const target of ex.tokens.slice(1)){loss-=Math.log(p[target]);n++;}return{tokenLoss:loss/n,counts,probabilities:p,denominator,basis:'Add-one-smoothed unigram fitted only on copy training targets; no context and no development/final fit.'};
}
const runKeys=['schemaVersion','modelVersion','dataVersion','tokenizerVersion','config','stage','step','stageStep','rng','dataDraws','weights','moments','squares','optimizerStep','reference','parentFingerprint','history','lastUpdate','finalOpened','finalReport'];
export function validateLifecycleRun(value:unknown):asserts value is LifecycleRun{
 keys(value,runKeys,'checkpoint');const r=value as LifecycleRun;ensure(runKeys.every(k=>Object.hasOwn(r,k)),'Incomplete checkpoint.');ensure(r.schemaVersion===1&&r.modelVersion===lifecycleModelVersion&&r.dataVersion===lifecycleDataVersion&&r.tokenizerVersion===lifecycleTokenizerVersion,'Checkpoint identity is incompatible.');resolveLifecycleConfig(r.config);ensure(Object.keys(r.config).length===Object.keys(lifecycleDefaults).length,'Incomplete configuration.');ensure(Object.hasOwn(lifecycleStages,r.stage),'Invalid stage.');finite(r.step,0,lifecycleLimits.maxUpdates,'step',true);finite(r.stageStep,0,r.step,'stage step',true);finite(r.rng,1,0xffffffff,'RNG',true);finite(r.dataDraws,0,lifecycleLimits.maxUpdates*2,'data cursor',true);ensure(r.dataDraws===r.step*2,'Data cursor disagrees with completed updates.');ensure(r.optimizerStep===r.step,'Optimizer step disagrees.');checkWeights(r.weights);checkWeights(r.moments,'moments');checkWeights(r.squares,'squares');ensure(r.squares.every(x=>x>=0),'Negative second moment.');checkWeights(r.reference,'reference');ensure(r.parentFingerprint===null||(typeof r.parentFingerprint==='string'&&/^[0-9a-f]{8}$/.test(r.parentFingerprint)),'Invalid parent fingerprint.');ensure(Array.isArray(r.history)&&r.history.length===r.step,'Invalid bounded history.');
 for(const [i,h] of r.history.entries()){keys(h,['step','stage','loss','gradientNorm','clipScale','targets','exampleIds','details','rollouts'],'history');ensure(h.step===i+1&&Object.hasOwn(lifecycleStages,h.stage),'Invalid history step.');finite(h.loss,-1000,1000,'loss');finite(h.gradientNorm,0,1e5,'gradient norm');finite(h.clipScale,0,1,'clip');finite(h.targets,1,32,'target count',true);ensure(Array.isArray(h.exampleIds)&&h.exampleIds.length===2&&h.exampleIds.every(id=>typeof id==='string'&&lifecycleExamples('train','copy').concat(lifecycleExamples('train','swap')).some(e=>e.id===id)),'Training history includes an invalid source.');ensure(Array.isArray(h.details)&&h.details.length<=8,'Invalid detail count.');for(const d of h.details){keys(d,['name','value'],'detail');ensure(typeof d.name==='string'&&d.name.length<160,'Invalid detail label.');finite(d.value,-1e6,1e6,'detail');}ensure(Array.isArray(h.rollouts)&&h.rollouts.length<=8,'Invalid rollout count.');for(const a of h.rollouts){keys(a,['exampleId','action','probability','reward','baseline','advantage'],'rollout');ensure(h.exampleIds.includes(a.exampleId),'Invalid rollout source.');finite(a.action,1,2,'action',true);finite(a.probability,0,1,'probability');finite(a.reward,0,1,'reward',true);finite(a.baseline,0,1,'baseline');finite(a.advantage,-1,1,'advantage');} }
 ensure(r.lastUpdate===null||r.step>0,'Unexpected update trace.');if(r.lastUpdate){keys(r.lastUpdate,['before','gradient','after','tapeNodes'],'last update');checkWeights(r.lastUpdate.before);checkWeights(r.lastUpdate.after);checkWeights(r.lastUpdate.gradient,'gradient');finite(r.lastUpdate.tapeNodes,1,100000,'tape nodes',true);ensure(r.lastUpdate.after.every((w,i)=>w===r.weights[i]),'Last update is stale.');}
 ensure(typeof r.finalOpened==='boolean','Invalid final-test state.');ensure(r.finalOpened||r.finalReport===null,'Sealed test cannot contain results.');if(r.finalReport){keys(r.finalReport,['atStep','fingerprint','copy','swap'],'final report');finite(r.finalReport.atStep,0,r.step,'final-test step',true);ensure(/^[0-9a-f]{8}$/.test(r.finalReport.fingerprint),'Invalid final fingerprint.');for(const domain of ['copy','swap'] as const){const e=r.finalReport[domain];keys(e,['split','domain','count','correct','answerLoss','tokenLoss','tokens','rows'],'evaluation');ensure(e.split==='final'&&e.domain===domain&&e.count===4,'Invalid final slice.');finite(e.correct,0,4,'correct',true);finite(e.answerLoss,0,1000,'answer loss');finite(e.tokenLoss,0,1000,'token loss');ensure(e.tokens===32&&Array.isArray(e.rows)&&e.rows.length===4,'Invalid final denominator.');for(const row of e.rows){keys(row,['id','prompt','expected','predicted','probability','correct'],'evaluation row');const ex=lifecycleExamples('final',domain).find(x=>x.id===row.id);ensure(ex&&row.prompt===ex.text.split(' ').slice(0,ex.answerPosition+1).join(' ')&&row.expected===ex.answer,'Invalid final case.');finite(row.predicted,0,V-1,'prediction',true);finite(row.probability,0,1,'probability');ensure(row.correct===(row.predicted===row.expected),'Invalid final correctness.');}ensure(e.correct===e.rows.filter(x=>x.correct).length&&new Set(e.rows.map(x=>x.id)).size===4,'Final result disagrees.');}}
}
export function serializeLifecycleCheckpoint(run:LifecycleRun){validateLifecycleRun(run);return JSON.stringify(run);}
export function readLifecycleCheckpoint(text:string):LifecycleRun{ensure(typeof text==='string'&&text.length<=lifecycleLimits.maxCheckpointBytes,'Checkpoint exceeds size limit.');const parsed:unknown=JSON.parse(text);validateLifecycleRun(parsed);return structuredClone(parsed);}
