import {inspectLifecycleForward,lifecycleFingerprint,lifecycleModelVersion} from './model-lifecycle.ts';
import {prefillLifecycleKv,appendLifecycleKv,type LifecycleKvCache} from './model-lifecycle-serving.ts';
export const lifecycleSpeculationVersion='authored-draft-target-greedy-1';
export const lifecycleSpeculationMetadata={modelVersion:lifecycleSpeculationVersion,sourceModelVersion:lifecycleModelVersion,proposalKind:'Two authored token IDs; no learned draft model',targetRule:'Binary64 target greedy argmax; first maximum wins ties',scope:'Exact bounded greedy verification and cache commit/discard, not stochastic speculative sampling or a measured speedup'} as const;
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
const argmax=(p:number[])=>p.indexOf(Math.max(...p));
export function referenceLifecycleGreedy(weights:number[],prompt:number[],maxNewTokens=2){ensure(Array.isArray(prompt)&&prompt.length>=1&&prompt.length<=7&&prompt.every(v=>Number.isInteger(v)&&v>=0&&v<9),'Invalid bounded prompt');ensure(maxNewTokens===1||maxNewTokens===2,'One or two generated tokens required');const context=[...prompt],output:number[]=[],probabilities:number[][]=[];for(let i=0;i<maxNewTokens;i++){const p=inspectLifecycleForward(weights,context).probabilities.at(-1)!,token=argmax(p);probabilities.push(p);output.push(token);if(token===7)break;context.push(token);}return{output,probabilities};}
export type LifecycleSpeculationTrace={modelVersion:string;fingerprint:string;proposalKind:string;prompt:number[];proposals:number[];verificationRows:{index:number;conditioningTokens:number[];proposal:number;targetGreedyToken:number;probabilities:number[];disposition:'accepted'|'rejected'|'unreached'}[];accepted:number;firstMismatch:number|null;output:number[];referenceOutput:number[];matchesReference:boolean;initialCache:LifecycleKvCache;tentativeCache:LifecycleKvCache;committedCache:LifecycleKvCache;discardedKvPositions:number;fallbackSteps:{index:number;conditioningTokens:number[];token:number;probabilities:number[]}[];processedTargetPositions:{prefill:number;tentative:number;recovery:number};events:string[]};
/** Verification is exact for greedy outputs; authored proposals have no probability model. */
export function verifyLifecycleDraft(weights:number[],prompt:number[],proposals:number[]):LifecycleSpeculationTrace{
 ensure(Array.isArray(proposals)&&proposals.length===2&&proposals.every(v=>Number.isInteger(v)&&v>=0&&v<9),'Exactly two valid authored draft tokens required');const reference=referenceLifecycleGreedy(weights,prompt),initialCache=prefillLifecycleKv(weights,prompt).cache,tentativeCache=appendLifecycleKv(weights,initialCache,proposals[0]).cache;
 const rows=[initialCache,tentativeCache].map((cache,index)=>({index,conditioningTokens:[...cache.tokens],proposal:proposals[index],targetGreedyToken:argmax(cache.last!.probabilities),probabilities:[...cache.last!.probabilities],disposition:'unreached' as 'accepted'|'rejected'|'unreached'}));
 let committedCache=initialCache,accepted=0,firstMismatch:number|null=null,recovery=0;const output:number[]=[],fallbackSteps:LifecycleSpeculationTrace['fallbackSteps']=[],events=['Compute target prompt cache.','Evaluate both authored proposal positions on a tentative target branch before deciding which prefix is valid.'];
 for(let i=0;i<2;i++){const p=committedCache.last!.probabilities,target=argmax(p);if(firstMismatch===null&&proposals[i]===target){rows[i].disposition='accepted';accepted++;output.push(proposals[i]);events.push(`Accept proposal ${i}: token ${proposals[i]} equals the target greedy token.`);}else{if(firstMismatch===null){firstMismatch=i;rows[i].disposition='rejected';events.push(`Reject proposal ${i} and discard its dependent proposal suffix.`);}output.push(target);fallbackSteps.push({index:i,conditioningTokens:[...committedCache.tokens],token:target,probabilities:[...p]});events.push(`Use actual target fallback token ${target} at output position ${i}.`);}if(target===7){events.push('EOS ends generation; no later proposal is committed.');break;}if(i===0){if(firstMismatch===null)committedCache=tentativeCache;else{committedCache=appendLifecycleKv(weights,initialCache,target).cache;recovery++;events.push('Discard the tentative wrong-prefix KV row and recompute the accepted fallback token before the next target prediction.');}}}
 const discardedKvPositions=committedCache.tokens.length>prompt.length&&committedCache.tokens[prompt.length]===tentativeCache.tokens[prompt.length]?0:1,matchesReference=JSON.stringify(output)===JSON.stringify(reference.output);ensure(matchesReference,'Verified output differs from independent target greedy reference');events.push(`Commit ${committedCache.tokens.length} processed target positions; discard ${discardedKvPositions} tentative KV position(s). The final emitted token is not fed back after the output limit.`);
 return{modelVersion:lifecycleSpeculationVersion,fingerprint:lifecycleFingerprint(weights),proposalKind:'Authored two-token proposal, not a learned draft',prompt:[...prompt],proposals:[...proposals],verificationRows:rows,accepted,firstMismatch,output,referenceOutput:reference.output,matchesReference,initialCache,tentativeCache,committedCache,discardedKvPositions,fallbackSteps,processedTargetPositions:{prefill:prompt.length,tentative:1,recovery},events};
}
