import {createLifecycleRun,validateLifecycleRun,readLifecycleCheckpoint,lifecycleFingerprint,lifecycleTensors,lifecycleModelVersion,lifecycleVocabulary,lifecycleExamples,lifecycleRandom,inspectLifecycleForward,type LifecycleRun} from './model-lifecycle.ts';
import {distributedLifecycleVersion,validateDistributedTrainingRun,readDistributedTrainingRun,type DistributedTrainingRun} from './model-lifecycle-distributed.ts';
import {type LifecycleExposureJournal} from './model-lifecycle-workspace.ts';
export const lifecycleServingVersion='causal-kv-serving-1';
export const lifecycleServingLimits={requests:3,context:8,maxNewTokens:2,steps:64,commands:67,maxBytes:1800000} as const;
export const lifecycleServingMetadata={experienceId:'serving',modelVersion:lifecycleServingVersion,schemaVersion:1,sourceModelVersion:lifecycleModelVersion,timingBasis:'Synthetic scheduling iterations; numerical decoder inference is real, wall-clock/GPU timing is not modeled.',memoryBasis:'KV payload per position: binary64 96 bytes; signed symmetric int4 codes 6 packed bytes plus two binary64 scales = 22 bytes. Fixed capacity is kvPositions × 96 bytes. Reconstructed diagnostic rows, JS objects, weights and other activations excluded.'} as const;
export type LifecycleKvFormat='binary64'|'int4-symmetric';
export type QuantizedKvRow={scale:number;codes:number[];packed:number[];reconstructed:number[];maxError:number};
export type LifecycleKvStep={position:number;inputToken:number;rawKey:number[];rawValue:number[];keyEncoding:QuantizedKvRow|null;valueEncoding:QuantizedKvRow|null;query:number[];key:number[];value:number[];scores:number[];attention:number[];hidden:number[];logits:number[];probabilities:number[];kvReadScalars:number;kvWrittenScalars:number;projectionMultiplyAdds:number;attentionMultiplyAdds:number};
export type LifecycleKvCache={modelVersion:string;fingerprint:string;format:LifecycleKvFormat;tokens:number[];keys:number[][];values:number[][];keyEncoding:(QuantizedKvRow|null)[];valueEncoding:(QuantizedKvRow|null)[];last:LifecycleKvStep|null};
const D=6,V=9,layout=Object.fromEntries(lifecycleTensors.map(t=>[t.name,t]));
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
function exact(v:unknown,names:string[],label:string){ensure(v&&typeof v==='object'&&!Array.isArray(v),label+' must be an object');ensure(Object.keys(v).length===names.length&&names.every(k=>Object.hasOwn(v,k)),label+' has unknown or missing fields');}
const bounded=(v:unknown,a:number,b:number,integer=false)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b&&(!integer||Number.isInteger(v));
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const maxDiff=(a:number[],b:number[])=>a.reduce((m,v,i)=>Math.max(m,Math.abs(v-b[i])),0);
export const lifecycleKvBytesPerPosition=(format:LifecycleKvFormat)=>{ensure(['binary64','int4-symmetric'].includes(format),'Invalid KV format');return format==='binary64'?96:22;};
export function quantizeLifecycleKvRow(values:number[]):QuantizedKvRow{ensure(Array.isArray(values)&&values.length===6&&values.every(v=>bounded(v,-1e6,1e6)),'Need six finite bounded values');const peak=Math.max(...values.map(Math.abs)),scale=peak===0?1:peak/7,codes=values.map(v=>Math.max(-7,Math.min(7,Math.sign(v)*Math.floor(Math.abs(v)/scale+.5)))),packed=Array.from({length:3},(_,i)=>(codes[i*2]&15)|((codes[i*2+1]&15)<<4)),reconstructed=codes.map(v=>v*scale);return{scale,codes,packed,reconstructed,maxError:maxDiff(values,reconstructed)};}
export function unpackLifecycleKvRow(packed:number[],scale:number){ensure(Array.isArray(packed)&&packed.length===3&&packed.every(v=>bounded(v,0,255,true))&&bounded(scale,Number.MIN_VALUE,1e6),'Invalid packed KV row');return packed.flatMap(v=>[v&15,v>>4]).map(v=>{const code=v>=8?v-16:v;ensure(code!==-8,'Unused signed code -8');return code*scale;});}
function softmax(x:number[]){const m=Math.max(...x),e=x.map(v=>Math.exp(v-m)),z=e.reduce((s,v)=>s+v,0);return e.map(v=>v/z);}
export function createLifecycleKvCache(weights:number[],format:LifecycleKvFormat='binary64'):LifecycleKvCache{lifecycleKvBytesPerPosition(format);return{format,keyEncoding:[],valueEncoding:[],modelVersion:lifecycleServingVersion,fingerprint:lifecycleFingerprint(weights),tokens:[],keys:[],values:[],last:null};}
function checkCache(cache:LifecycleKvCache,weights:number[]){exact(cache,['modelVersion','fingerprint','format','tokens','keys','values','keyEncoding','valueEncoding','last'],'KV cache');lifecycleKvBytesPerPosition(cache.format);for(const enc of [cache.keyEncoding,cache.valueEncoding])ensure(Array.isArray(enc)&&enc.length===cache.tokens.length,'Invalid KV encodings');ensure(cache.modelVersion===lifecycleServingVersion&&cache.fingerprint===lifecycleFingerprint(weights),'KV cache belongs to different weights or model');ensure(Array.isArray(cache.tokens)&&cache.tokens.length<=8&&cache.tokens.every(v=>bounded(v,0,8,true)),'Invalid cache tokens');for(const rows of [cache.keys,cache.values])ensure(Array.isArray(rows)&&rows.length===cache.tokens.length&&rows.every(row=>Array.isArray(row)&&row.length===6&&row.every(v=>bounded(v,-1e6,1e6))),'Invalid bounded KV rows');ensure((cache.tokens.length===0)===(cache.last===null),'Invalid cache trace');}
/** Only the new token's Q/K/V and position-wise layers are computed; past K/V are read unchanged. */
export function appendLifecycleKv(weights:number[],input:LifecycleKvCache,token:number):{cache:LifecycleKvCache;step:LifecycleKvStep}{
 checkCache(input,weights);ensure(input.tokens.length<8,'Context budget reached');ensure(bounded(token,0,8,true),'Invalid input token');const pos=input.tokens.length;
 const w=(name:string,r:number,c:number)=>weights[layout[name].offset+r*layout[name].columns+c];
 const linear=(x:number[],name:string,bias?:string)=>Array.from({length:layout[name].columns},(_,j)=>x.reduce((s,v,i)=>s+v*w(name,i,j),0)+(bias?w(bias,0,j):0));
 const norm=(x:number[])=>{const inv=1/Math.sqrt(x.reduce((s,v)=>s+v*v,0)/D+1e-5);return x.map(v=>v*inv);};
 const embedding=Array.from({length:D},(_,j)=>w('embedding',token,j)+.15*(j%2?Math.cos(pos/10000**((j-1)/D)):Math.sin(pos/10000**(j/D)))),normalized=norm(embedding),query=linear(normalized,'query'),rawKey=linear(normalized,'key'),rawValue=linear(normalized,'value'),keyEncoding=input.format==='int4-symmetric'?quantizeLifecycleKvRow(rawKey):null,valueEncoding=input.format==='int4-symmetric'?quantizeLifecycleKvRow(rawValue):null,key=keyEncoding?unpackLifecycleKvRow(keyEncoding.packed,keyEncoding.scale):rawKey,value=valueEncoding?unpackLifecycleKvRow(valueEncoding.packed,valueEncoding.scale):rawValue,keys=input.keys.concat([key]),values=input.values.concat([value]);
 const scores=keys.map(k=>query.reduce((s,q,j)=>s+q*k[j],0)/Math.sqrt(D)),attention=softmax(scores),mixed=Array.from({length:D},(_,j)=>attention.reduce((s,a,i)=>s+a*values[i][j],0)),projected=linear(mixed,'attentionOutput'),residual=embedding.map((v,j)=>v+projected[j]),ff=linear(linear(norm(residual),'feedForwardIn','feedForwardBias').map(Math.tanh),'feedForwardOut','feedForwardOutBias'),hidden=residual.map((v,j)=>v+ff[j]),logits=linear(hidden,'unembedding','logitBias');
 const step:LifecycleKvStep={position:pos,inputToken:token,rawKey,rawValue,keyEncoding,valueEncoding,query,key,value,scores,attention,hidden,logits,probabilities:softmax(logits),kvReadScalars:2*D*(pos+1),kvWrittenScalars:2*D,projectionMultiplyAdds:342,attentionMultiplyAdds:2*D*(pos+1)};
 return{cache:{modelVersion:lifecycleServingVersion,fingerprint:input.fingerprint,format:input.format,keyEncoding:input.keyEncoding.concat(keyEncoding),valueEncoding:input.valueEncoding.concat(valueEncoding),tokens:input.tokens.concat(token),keys,values,last:step},step};
}
export function prefillLifecycleKv(weights:number[],tokens:number[],initial=createLifecycleKvCache(weights)){ensure(Array.isArray(tokens)&&tokens.length>0&&tokens.length<=8,'Bounded prefill required');let cache=initial;const steps:LifecycleKvStep[]=[];for(const token of tokens){const next=appendLifecycleKv(weights,cache,token);cache=next.cache;steps.push(next.step);}return{cache,steps};}
export type ServingRequestSpec={id:string;exampleId:string;arrivalTick:number;maxNewTokens:1|2};
export type LifecycleServingConfig={kvFormat:LifecycleKvFormat;policy:'continuous'|'static';batchSlots:1|2|3;kvPositions:number;prefillChunk:number;decoding:'greedy'|'sample';samplingSeed:number;requests:ServingRequestSpec[]};
export const servingExampleOptions=lifecycleExamples('train','copy').concat(lifecycleExamples('development','copy'),lifecycleExamples('development','swap'));
export const lifecycleServingDefaults:LifecycleServingConfig={kvFormat:'binary64',policy:'continuous',batchSlots:2,kvPositions:16,prefillChunk:2,decoding:'greedy',samplingSeed:123,requests:[{id:'request-1',exampleId:servingExampleOptions[0].id,arrivalTick:0,maxNewTokens:2},{id:'request-2',exampleId:servingExampleOptions[14].id,arrivalTick:0,maxNewTokens:2},{id:'request-3',exampleId:servingExampleOptions[16].id,arrivalTick:2,maxNewTokens:2}]};
export function resolveLifecycleServingConfig(options:Partial<LifecycleServingConfig>={}):LifecycleServingConfig{ensure(options&&typeof options==='object'&&!Array.isArray(options)&&Object.keys(options).every(k=>Object.hasOwn(lifecycleServingDefaults,k)),'Unknown serving option');const c=structuredClone({...lifecycleServingDefaults,...options});lifecycleKvBytesPerPosition(c.kvFormat);ensure(['continuous','static'].includes(c.policy)&&['greedy','sample'].includes(c.decoding),'Invalid serving policy');ensure(bounded(c.batchSlots,1,3,true)&&bounded(c.kvPositions,4,24,true)&&bounded(c.prefillChunk,1,8,true)&&bounded(c.samplingSeed,1,1000000,true),'Invalid bounded serving configuration');ensure(Array.isArray(c.requests)&&c.requests.length>=1&&c.requests.length<=3,'Need one to three requests');const ids=new Set();for(const r of c.requests){exact(r,['id','exampleId','arrivalTick','maxNewTokens'],'request specification');ensure(typeof r.id==='string'&&/^[a-z][a-z0-9-]{0,30}$/.test(r.id)&&!ids.has(r.id),'Invalid or duplicate request identity');ids.add(r.id);ensure(servingExampleOptions.some(e=>e.id===r.exampleId),'Only declared training/development prompts may be served');ensure(bounded(r.arrivalTick,0,12,true)&&(r.maxNewTokens===1||r.maxNewTokens===2),'Invalid request bounds');}return c;}
export type ServingSource={kind:'lifecycle';checkpoint:LifecycleRun}|{kind:'distributed';checkpoint:DistributedTrainingRun};
export type ServingRequest={spec:ServingRequestSpec;prompt:number[];status:'pending'|'queued'|'active'|'complete'|'cancelled'|'rejected';reservation:number;promptCursor:number;cache:LifecycleKvCache|null;output:number[];rng:number;admittedAt:number|null;firstTokenAt:number|null;completedAt:number|null;stopReason:string|null};
export type ServingLane={requestId:string;phase:'prefill'|'decode';processedTokens:number[];kvBefore:number;kvAfter:number;generatedToken:number|null;referenceGreedyToken:number|null;greedyTokenMatchesReference:boolean|null;referenceMaxError:number;steps:LifecycleKvStep[];cacheAfter:LifecycleKvCache};
export type ServingEvent={sequence:number;tick:number;kind:'arrival'|'admit'|'reject'|'batch'|'token'|'complete'|'cancel'|'wait';requestIds:string[];message:string;occupiedPositions:number;reservedPositions:number};
export type ServingIteration={tick:number;lanes:ServingLane[];occupiedPeak:number;reservedPeak:number};
export type ServingCommand={kind:'step'}|{kind:'cancel';requestId:string};
export type LifecycleServingRun={schemaVersion:1;modelVersion:string;source:ServingSource;config:LifecycleServingConfig;tick:number;requests:ServingRequest[];commands:ServingCommand[];events:ServingEvent[];lastIteration:ServingIteration|null};
export const servingWeights=(run:LifecycleServingRun)=>run.source.kind==='lifecycle'?run.source.checkpoint.weights:run.source.checkpoint.state.weights;
export const servingSourceCheckpoint=(run:LifecycleServingRun)=>run.source.kind==='lifecycle'?run.source.checkpoint:run.source.checkpoint.sourceCheckpoint;
function checkSource(s:ServingSource){exact(s,['kind','checkpoint'],'serving source');if(s.kind==='lifecycle')validateLifecycleRun(s.checkpoint);else{ensure(s.kind==='distributed','Invalid source kind');validateDistributedTrainingRun(s.checkpoint);}}
export function servingMemory(run:LifecycleServingRun){const active=run.requests.filter(r=>r.status==='active'),occupied=active.reduce((s,r)=>s+(r.cache?.tokens.length??0),0),reserved=active.reduce((s,r)=>s+r.reservation,0);const bytesPerPosition=lifecycleKvBytesPerPosition(run.config.kvFormat),capacityPayloadBytes=run.config.kvPositions*96;return{occupiedPositions:occupied,reservedPositions:reserved,occupiedPayloadBytes:occupied*bytesPerPosition,reservedPayloadBytes:reserved*bytesPerPosition,capacityPayloadBytes,bytesPerPosition,capacityPositions:Math.floor(capacityPayloadBytes/bytesPerPosition)};}
function create(source:ServingSource,options:Partial<LifecycleServingConfig>):LifecycleServingRun{checkSource(source);const config=resolveLifecycleServingConfig(options);return{schemaVersion:1,modelVersion:lifecycleServingVersion,source:structuredClone(source),config,tick:0,requests:config.requests.map((spec,i)=>{const e=servingExampleOptions.find(e=>e.id===spec.exampleId)!,prompt=e.tokens.slice(0,e.answerPosition+1);return{spec:structuredClone(spec),prompt,status:'pending',reservation:prompt.length+spec.maxNewTokens-1,promptCursor:0,cache:null,output:[],rng:config.samplingSeed+i,admittedAt:null,firstTokenAt:null,completedAt:null,stopReason:null};}),commands:[],events:[],lastIteration:null};}
export function createLifecycleServingRun(checkpoint=createLifecycleRun(),options:Partial<LifecycleServingConfig>={}):LifecycleServingRun{return create({kind:'lifecycle',checkpoint},options);}
export function createDistributedServingRun(checkpoint:DistributedTrainingRun,options:Partial<LifecycleServingConfig>={}):LifecycleServingRun{return create({kind:'distributed',checkpoint},options);}
function emit(run:LifecycleServingRun,kind:ServingEvent['kind'],ids:string[],message:string,tick=run.tick){const memory=servingMemory(run);run.events.push({sequence:run.events.length+1,tick,kind,requestIds:ids,message,occupiedPositions:memory.occupiedPositions,reservedPositions:memory.reservedPositions});}
export const servingIsFinished=(run:LifecycleServingRun)=>run.requests.every(r=>['complete','cancelled','rejected'].includes(r.status));
function selectToken(p:number[],request:ServingRequest,mode:LifecycleServingConfig['decoding']){if(mode==='greedy')return p.indexOf(Math.max(...p));const draw=lifecycleRandom(request.rng);request.rng=draw.state;let left=draw.value;for(let i=0;i<p.length;i++){left-=p[i];if(left<=0)return i;}return V-1;}
function stepInternal(input:LifecycleServingRun):LifecycleServingRun{
 ensure(input.tick<64&&!servingIsFinished(input),'Serving trace is finished or step budget reached');const run=structuredClone(input),weights=servingWeights(run);
 for(const r of run.requests)if(r.status==='pending'&&r.spec.arrivalTick<=run.tick){r.status='queued';emit(run,'arrival',[r.spec.id],'Request arrived at the scheduling boundary.');}
 const waiting=run.requests.filter(r=>r.status==='queued').sort((a,b)=>a.spec.arrivalTick-b.spec.arrivalTick||run.requests.indexOf(a)-run.requests.indexOf(b));for(const r of waiting)if(r.reservation>servingMemory(run).capacityPositions){r.status='rejected';r.completedAt=run.tick;r.stopReason='Request worst-case KV reservation exceeds total capacity';emit(run,'reject',[r.spec.id],r.stopReason);}
 if(run.config.policy==='continuous'||!run.requests.some(r=>r.status==='active'))for(const r of waiting.filter(r=>r.status==='queued')){const mem=servingMemory(run);if(run.requests.filter(x=>x.status==='active').length>=run.config.batchSlots||mem.reservedPositions+r.reservation>servingMemory(run).capacityPositions)break;r.status='active';r.admittedAt=run.tick;r.cache=createLifecycleKvCache(weights,run.config.kvFormat);emit(run,'admit',[r.spec.id],`Reserved ${r.reservation} KV positions before execution; FIFO admission.`);}
 const active=run.requests.filter(r=>r.status==='active'),iteration:ServingIteration={tick:run.tick,lanes:[],occupiedPeak:servingMemory(run).occupiedPositions,reservedPeak:servingMemory(run).reservedPositions};
 if(active.length)emit(run,'batch',active.map(r=>r.spec.id),'Each logical batch lane runs one prefill chunk or one autoregressive decode step.');else emit(run,'wait',[],'No active request; advance one synthetic scheduling iteration.');
 for(const r of active){const phase=r.promptCursor<r.prompt.length?'prefill':'decode',processed=phase==='prefill'?r.prompt.slice(r.promptCursor,r.promptCursor+run.config.prefillChunk):[r.output.at(-1)!],before=r.cache!.tokens.length,result=prefillLifecycleKv(weights,processed,r.cache!),ref=inspectLifecycleForward(weights,result.cache.tokens).probabilities.at(-1)!,difference=maxDiff(ref,result.cache.last!.probabilities);if(run.config.kvFormat==='binary64')ensure(difference<1e-10,'Cached inference differs from the full-prefix reference');r.cache=result.cache;if(phase==='prefill')r.promptCursor+=processed.length;iteration.occupiedPeak=Math.max(iteration.occupiedPeak,servingMemory(run).occupiedPositions);let generatedToken:number|null=null;
  if(r.promptCursor===r.prompt.length){generatedToken=selectToken(r.cache.last!.probabilities,r,run.config.decoding);r.output.push(generatedToken);r.firstTokenAt??=run.tick+1;emit(run,'token',[r.spec.id],`Generated ${lifecycleVocabulary[generatedToken]} from actual cached probabilities.`,run.tick+1);}
  iteration.lanes.push({requestId:r.spec.id,phase,processedTokens:processed,kvBefore:before,kvAfter:r.cache.tokens.length,generatedToken,referenceGreedyToken:generatedToken===null?null:ref.indexOf(Math.max(...ref)),greedyTokenMatchesReference:generatedToken===null?null:result.cache.last!.probabilities.indexOf(Math.max(...result.cache.last!.probabilities))===ref.indexOf(Math.max(...ref)),referenceMaxError:difference,steps:result.steps,cacheAfter:structuredClone(result.cache)});
 }
 // Release only after all logical lanes have executed so peak accounting does not borrow freed slots within a batch.
 for(const r of active)if(r.output.at(-1)===7||r.output.length===r.spec.maxNewTokens){r.status='complete';r.completedAt=run.tick+1;r.stopReason=r.output.at(-1)===7?'EOS':'Requested output limit';r.cache=null;emit(run,'complete',[r.spec.id],`${r.stopReason}; released the entire KV reservation.`,run.tick+1);}
 ensure(iteration.occupiedPeak<=iteration.reservedPeak&&iteration.reservedPeak<=servingMemory(run).capacityPositions,'KV capacity invariant failed');run.lastIteration=iteration;run.tick++;run.commands.push({kind:'step'});return run;
}
function cancelInternal(input:LifecycleServingRun,id:string){const run=structuredClone(input),r=run.requests.find(r=>r.spec.id===id);ensure(r&&['pending','queued','active'].includes(r.status),'Only pending, queued or active requests can be cancelled');r.status='cancelled';r.completedAt=run.tick;r.stopReason='Cancelled by learner';r.cache=null;emit(run,'cancel',[id],'Cancelled request and released any reserved and occupied KV positions.');run.commands.push({kind:'cancel',requestId:id});return run;}
/** Fast bounded structure validation; import additionally replays and compares all computed state. */
export function validateLifecycleServingRun(v:unknown):asserts v is LifecycleServingRun{
 exact(v,['schemaVersion','modelVersion','source','config','tick','requests','commands','events','lastIteration'],'serving record');const r=v as LifecycleServingRun;ensure(r.schemaVersion===1&&r.modelVersion===lifecycleServingVersion,'Incompatible serving record');checkSource(r.source);exact(r.config,Object.keys(lifecycleServingDefaults),'configuration');resolveLifecycleServingConfig(r.config);ensure(bounded(r.tick,0,64,true),'Invalid serving tick');ensure(Array.isArray(r.commands)&&r.commands.length<=67,'Command budget exceeded');let steps=0;for(const c of r.commands){ensure(c&&typeof c==='object','Invalid command');if(c.kind==='step'){exact(c,['kind'],'step');steps++;}else{exact(c,['kind','requestId'],'cancel');ensure(c.kind==='cancel'&&r.config.requests.some(q=>q.id===c.requestId),'Invalid cancellation');}}ensure(steps===r.tick,'Tick and command count disagree');ensure(Array.isArray(r.requests)&&r.requests.length===r.config.requests.length,'Request count differs');ensure(Array.isArray(r.events)&&r.events.length<=400,'Event budget exceeded');for(const [i,q]of r.requests.entries()){exact(q,['spec','prompt','status','reservation','promptCursor','cache','output','rng','admittedAt','firstTokenAt','completedAt','stopReason'],'request');ensure(same(q.spec,r.config.requests[i]),'Request specification differs');const ex=servingExampleOptions.find(e=>e.id===q.spec.exampleId)!;ensure(same(q.prompt,ex.tokens.slice(0,ex.answerPosition+1))&&q.reservation===q.prompt.length+q.spec.maxNewTokens-1,'Prompt or reservation differs');ensure(['pending','queued','active','complete','cancelled','rejected'].includes(q.status),'Invalid request status');ensure(bounded(q.promptCursor,0,q.prompt.length,true)&&Array.isArray(q.output)&&q.output.length<=q.spec.maxNewTokens&&q.output.every(x=>bounded(x,0,8,true))&&bounded(q.rng,1,0xffffffff,true),'Invalid request cursor or output');ensure((q.status==='active')===(q.cache!==null),'Only active requests own KV state');if(q.cache){checkCache(q.cache,servingWeights(r));ensure(q.cache.format===r.config.kvFormat,'Cache format differs from configuration');ensure(q.cache.tokens.length<=q.reservation,'KV state exceeds reservation');}for(const t of [q.admittedAt,q.firstTokenAt,q.completedAt])ensure(t===null||bounded(t,0,r.tick,true),'Invalid request time');ensure(q.stopReason===null||(typeof q.stopReason==='string'&&q.stopReason.length<120),'Invalid stop reason');}const memory=servingMemory(r);ensure(memory.occupiedPositions<=memory.reservedPositions&&memory.reservedPositions<=memory.capacityPositions,'Capacity exceeded');ensure(r.requests.filter(q=>q.status==='active').length<=r.config.batchSlots,'Batch slot capacity exceeded');
}
export function stepLifecycleServingRun(run:LifecycleServingRun){validateLifecycleServingRun(run);return stepInternal(run);}
export function cancelLifecycleServingRequest(run:LifecycleServingRun,id:string){validateLifecycleServingRun(run);ensure(run.commands.length<67,'Command budget reached');return cancelInternal(run,id);}
export function finishLifecycleServingRun(input:LifecycleServingRun){validateLifecycleServingRun(input);let run=input;while(!servingIsFinished(run))run=stepInternal(run);return run;}
export function serializeLifecycleServingRun(run:LifecycleServingRun){validateLifecycleServingRun(run);const text=JSON.stringify(run);ensure(text.length<=lifecycleServingLimits.maxBytes,'Serving record too large');return text;}
export function readLifecycleServingRun(text:string):LifecycleServingRun{ensure(typeof text==='string'&&text.length<=lifecycleServingLimits.maxBytes,'Serving record too large');const v:unknown=JSON.parse(text);validateLifecycleServingRun(v);if(v.source.kind==='distributed')readDistributedTrainingRun(JSON.stringify(v.source.checkpoint));let replay=create(v.source,v.config);for(const c of v.commands)replay=c.kind==='step'?stepInternal(replay):cancelInternal(replay,c.requestId);ensure(same(replay,v),'Serving state or trace disagrees with deterministic replay');return replay;}
export function retainServingExposure(run:LifecycleServingRun,journal:LifecycleExposureJournal):LifecycleServingRun{const source=run.source.kind==='lifecycle'?{...run.source,checkpoint:journal.retain(run.source.checkpoint)}:{...run.source,checkpoint:{...run.source.checkpoint,sourceCheckpoint:journal.retain(run.source.checkpoint.sourceCheckpoint)}};return{...run,source};}
export function importLifecycleServingWorkspace(text:string,journal:LifecycleExposureJournal,expectedRevision:number,currentRevision:number,config:Partial<LifecycleServingConfig>={}):LifecycleServingRun{
 ensure(typeof text==='string'&&text.length<=lifecycleServingLimits.maxBytes,'Serving record too large');const tag:unknown=JSON.parse(text);ensure(tag&&typeof tag==='object'&&'modelVersion'in tag,'Missing model identity');const candidate=tag.modelVersion===lifecycleModelVersion?createLifecycleServingRun(readLifecycleCheckpoint(text),config):tag.modelVersion===distributedLifecycleVersion?createDistributedServingRun(readDistributedTrainingRun(text),config):readLifecycleServingRun(text);ensure(expectedRevision===currentRevision,'The workspace changed during the file read; select the file again.');return retainServingExposure(candidate,journal);
}
