/** Stable public IDs used by lesson links, the workbench and validation. */
export const numericLabs=[
 {id:'hbm-stack-build',name:'Build an HBM stack',title:'Fit capacity, connections and heat into one stack',intro:'Add DRAM dies, thin them, and choose a bonding route. Capacity grows with die count; bandwidth still comes from the interface. Every numeric preset is synthetic.',
  latex:String.raw`\begin{aligned}h&=h_{\mathrm{base}}+h_{\mathrm{cap}}+n(t+g)\\C&=nD/8,\quad B_{\mathrm{eff}}=p\,r\,\eta/8\\Y_{\mathrm{cond}}&=y_d^n y_b^n y_f\\T_{j-1}&=T_j+Q_{<j}R_{\mathrm{segment}}\end{aligned}`,
  formula:'Stack height = base + cap + die count × (die thickness + bond gap). Capacity in GB = dies × Gbit per die / 8. Effective GB/s = data pins × Gbit/s per pin × efficiency / 8. Conditional survival = residual screened-die survival^dies × bond survival^interfaces × final-test survival. Each thermal segment adds the heat flowing through it times its thermal resistance.',
  sources:[{name:'SK hynix · TC–NCF and MR–MUF process context',url:'https://news.skhynix.com/en/rulebreaker-revolutions-mr-muf-unlocks-hbm-heat-control/'},{name:'imec · hybrid bonding and interface preparation',url:'https://www.imec-int.com/en/articles/wafer-wafer-hybrid-bonding-pushing-boundaries-400nm-interconnect-pitch'},{name:'MIT · heat-transfer fundamentals',url:'https://ocw.mit.edu/courses/2-051-introduction-to-heat-transfer-fall-2015/'}]},
 {id:'inference-placement',name:'Place inference memory',title:'Place the working set before asking how fast it runs',intro:'Keep read-only weights separate from mutable KV state. Allocate capacity across SRAM, HBM, host DRAM and an optional HBF read tier, then inspect the transfer paths.',
  latex:String.raw`\begin{aligned}M_W&=N_p b_W/8\\M_{\mathrm{KV}}&=2BLTH_{\mathrm{KV}}d_h s\\t_{\mathrm{read}}&=\frac{M}{\eta\min(\beta_{\mathrm{source}},\beta_{\mathrm{link}})}+\left\lceil\frac{\lceil M/c\rceil}{q}\right\rceil\tau\end{aligned}`,
  formula:'Weight bytes = parameter count × weight bits / 8. KV bytes = 2 × batch × layers × context × KV heads × head width × element bytes. Read service time = payload bytes / effective path bandwidth + access-latency waves. A wave serves at most q requests, each up to c bytes. Effective path bandwidth is efficiency × the smaller of source and link bandwidth.',
  sources:[{name:'Kwon et al. · KV-cache allocation and PagedAttention',url:'https://arxiv.org/abs/2309.06180'},{name:'NVIDIA · memory paths, transfer overhead and overlap',url:'https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html'},{name:'Sandisk · HBF’s inference-focused role',url:'https://www.sandisk.com/company/newsroom/blogs/2025/scaling-beyond-the-wall-inside-sandisks-high-bandwidth-flash-for-ai'}]},
 {id:'token-system-path',name:'Follow a token',title:'A token follows a critical path through the system',intro:'Follow one batched decode step through tensor arithmetic, the HBM/package path and inter-rank collectives. Change overlap and power assumptions without counting the same time twice.',
  latex:String.raw`\begin{aligned}t_{\mathrm{local}}&=\max(t_{\mathrm{math}},t_{\mathrm{memory}})\quad\text{(ideal overlap)}\\t_{\mathrm{step}}&=t_{\mathrm{launch}}+t_{\mathrm{local}}+t_{\mathrm{network}}+t_{\mathrm{sample}}\\E&=p\!\left(P_0t_{\mathrm{step}}+\sum_i\Delta P_i t_i\right)+P_h t_{\mathrm{step}}\end{aligned}`,
  formula:'With ideal tiled overlap, local time is the maximum of arithmetic and memory service times; without overlap it is their sum. Add dispatch, serialized collectives and sampling once. HBM and its package link carry the same memory path and use their minimum bandwidth, not two separately added times. Energy integrates baseline power over wall time and each incremental resource power over that resource’s active time, across all ranks, plus the host.',
  sources:[{name:'NVIDIA · transfer/computation overlap and performance analysis',url:'https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html'},{name:'NVIDIA NCCL · collective-operation semantics',url:'https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html'},{name:'Kwon et al. · serving workload and cached KV',url:'https://arxiv.org/abs/2309.06180'}]}
] as const;
export type NumericLabId=typeof numericLabs[number]['id'];
export function isNumericLab(id:string):id is NumericLabId{return numericLabs.some(l=>l.id===id);}
