/** A declared long-channel CMOS teaching specimen, not a foundry or modern-node compact model. */
export const processCellVersion='process-cell-acceptance-1';
export const cellConstants=Object.freeze({specimenId:'INV-01',supplyV:1.2,epsilon0Fpm:8.854e-12,oxideRelativePermittivity:3.9,channelLengthUm:2,nWidthUm:2,pWidthUm:6,nMobilityCm2PerVs:450,pMobilityCm2PerVs:150,depletionChargeCpm2:4e-4,thresholdInterceptV:.23,channelLengthModulation:0});
export type CellInput={oxideNominalNm:number;oxideOffsetPct:number;mobilityNScale:number;thresholdNShiftMv:number;fanout:number;externalLoadFf:number;oxideTolerancePct:number;noiseMinimumV:number;delayMaximumNs:number};
export const cellDefaults:CellInput={oxideNominalNm:10,oxideOffsetPct:0,mobilityNScale:1,thresholdNShiftMv:0,fanout:1,externalLoadFf:10,oxideTolerancePct:5,noiseMinimumV:.4,delayMaximumNs:1};
export type CellParameters={oxideNm:number;coxFpm2:number;gateCapF:number;loadCapF:number;betaN:number;betaP:number;thresholdNV:number;thresholdPV:number;mobilityNM2PerVs:number;mobilityPM2PerVs:number;switchingV:number};
export type TransferPoint={vin:number;vout:number|null;outputLowV:number;outputHighV:number;gain:number|null;branch:'n-off'|'p-off'|'p-triode'|'n-triode'|'ideal-transition'};
export type CellGate={id:'oxide'|'logic'|'noise'|'timing';title:string;pass:boolean;actual:number;limit:number;unit:string;reason:string};
export type CellResult={version:typeof processCellVersion;specimenId:string;input:CellInput;parameters:CellParameters;transfer:TransferPoint[];iv:{vds:number;nCurrentA:number;pCurrentMagnitudeA:number}[];noise:{vilV:number;vihV:number;volV:number;vohV:number;nmlV:number;nmhV:number};timing:{fall50Seconds:number;rise50Seconds:number;fall90to10Seconds:number;rise10to90Seconds:number};transitions:{progress:number;fallV:number;riseV:number;fallSeconds:number;riseSeconds:number}[];gates:CellGate[];accepted:boolean;stages:{id:string;title:string;specimenId:string;description:string}[]};
function ensure(c:unknown,m:string):asserts c{if(!c)throw new Error(m);}
export function normalizeCellInput(value:unknown):CellInput{
 ensure(value&&typeof value==='object'&&!Array.isArray(value),'Cell input must be an object.');const x=value as Record<string,unknown>;
 const bounds:Record<keyof CellInput,[number,number]>={oxideNominalNm:[8,16],oxideOffsetPct:[-20,20],mobilityNScale:[.5,1.5],thresholdNShiftMv:[-120,120],fanout:[0,4],externalLoadFf:[0,200],oxideTolerancePct:[1,20],noiseMinimumV:[.1,.6],delayMaximumNs:[.1,5]};
 ensure(Object.keys(x).every(k=>k in bounds),'Unknown cell input field.');for(const [k,[lo,hi]] of Object.entries(bounds))ensure(typeof x[k]==='number'&&Number.isFinite(x[k])&&(x[k] as number)>=lo&&(x[k] as number)<=hi,`${k} must be ${lo}…${hi}.`);ensure(Number.isInteger(x.fanout),'Fanout must be an integer.');ensure((x.fanout as number)>0||(x.externalLoadFf as number)>0,'A positive load capacitance is required.');return Object.fromEntries(Object.keys(bounds).map(k=>[k,x[k]])) as CellInput;
}
export function deriveCellParameters(value:unknown):CellParameters{
 const input=normalizeCellInput(value),c=cellConstants,oxideNm=input.oxideNominalNm*(1+input.oxideOffsetPct/100),coxFpm2=c.epsilon0Fpm*c.oxideRelativePermittivity/(oxideNm*1e-9),gateCapF=coxFpm2*(c.nWidthUm+c.pWidthUm)*c.channelLengthUm*1e-12,mobilityNM2PerVs=c.nMobilityCm2PerVs*1e-4*input.mobilityNScale,mobilityPM2PerVs=c.pMobilityCm2PerVs*1e-4,betaN=mobilityNM2PerVs*coxFpm2*c.nWidthUm/c.channelLengthUm,betaP=mobilityPM2PerVs*coxFpm2*c.pWidthUm/c.channelLengthUm,thresholdPV=c.thresholdInterceptV+c.depletionChargeCpm2/coxFpm2,thresholdNV=thresholdPV+input.thresholdNShiftMv*1e-3,switchingV=(Math.sqrt(betaP)*(c.supplyV-thresholdPV)+Math.sqrt(betaN)*thresholdNV)/(Math.sqrt(betaN)+Math.sqrt(betaP));
 ensure(thresholdNV>0&&thresholdPV>0&&thresholdNV+thresholdPV<c.supplyV,'Both devices must have a nonempty strong-inversion switching interval.');return {oxideNm,coxFpm2,gateCapF,loadCapF:input.fanout*gateCapF+input.externalLoadFf*1e-15,betaN,betaP,thresholdNV,thresholdPV,mobilityNM2PerVs,mobilityPM2PerVs,switchingV};
}
/** Nonnegative nMOS-style current magnitude. pMOS uses VSG, VSD and positive |VTp|. */
export function longChannelCurrent(beta:number,threshold:number,gateV:number,drainV:number):number{
 ensure([beta,threshold,gateV,drainV].every(Number.isFinite)&&beta>0&&threshold>0&&gateV>=0&&drainV>=0,'Current arguments must be finite nonnegative voltages and positive beta/threshold.');const u=gateV-threshold;if(u<=0)return 0;return drainV>=u?.5*beta*u*u:beta*(u*drainV-.5*drainV*drainV);
}
export function inverterTransfer(p:CellParameters,vin:number):TransferPoint{
 const vdd=cellConstants.supplyV;ensure(Number.isFinite(vin)&&vin>=0&&vin<=vdd,'Input voltage must be inside the supply rails.');const un=vin-p.thresholdNV,up=vdd-vin-p.thresholdPV;
 if(un<=0)return {vin,vout:vdd,outputLowV:vdd,outputHighV:vdd,gain:0,branch:'n-off'};
 if(up<=0)return {vin,vout:0,outputLowV:0,outputHighV:0,gain:0,branch:'p-off'};
 if(Math.abs(vin-p.switchingV)<1e-12)return {vin,vout:null,outputLowV:un,outputHighV:vdd-up,gain:null,branch:'ideal-transition'};
 let vout:number,gain:number,branch:TransferPoint['branch'];
 if(vin<p.switchingV){const r=p.betaN/p.betaP,d=Math.sqrt(Math.max(0,up*up-r*un*un)),drop=r*un*un/(up+d);vout=vdd-drop;gain=-(r*un+drop)/d;branch='p-triode';}
 else {const r=p.betaP/p.betaN,d=Math.sqrt(Math.max(0,un*un-r*up*up));vout=r*up*up/(un+d);gain=-(un===vout?Infinity:(vout+r*up)/(un-vout));branch='n-triode';}
 return {vin,vout,outputLowV:vout,outputHighV:vout,gain,branch};
}
/** C ∫dv / I(VDD,v), integrated exactly across triode/saturation. No ideal endpoint v=0. */
export function dischargeTimeSeconds(beta:number,threshold:number,capF:number,lowV:number,highV:number):number{
 const vdd=cellConstants.supplyV;ensure([beta,threshold,capF,lowV,highV].every(Number.isFinite)&&beta>0&&threshold>0&&threshold<vdd&&capF>0&&lowV>0&&highV>=lowV&&highV<=vdd,'Delay integral requires 0 < low ≤ high ≤ VDD and valid positive parameters.');const u=vdd-threshold;let integral=0;
 if(lowV<u){const hi=Math.min(highV,u);if(hi>lowV)integral+=Math.log((hi/(u-.5*hi))/(lowV/(u-.5*lowV)))/(beta*u);}
 if(highV>u){const lo=Math.max(lowV,u);if(highV>lo)integral+=(highV-lo)/(.5*beta*u*u);}
 return capF*integral;
}
/** Invert the same analytic step integral at a finite time; rails are approached asymptotically. */
export function outputAfterStep(p:CellParameters,direction:'fall'|'rise',seconds:number):number{
 ensure(Number.isFinite(seconds)&&seconds>=0,'Step time must be finite and nonnegative.');const beta=direction==='fall'?p.betaN:p.betaP,vt=direction==='fall'?p.thresholdNV:p.thresholdPV,vdd=cellConstants.supplyV;if(seconds===0)return direction==='fall'?vdd:0;let lo:number=1e-15,hi:number=vdd;
 for(let i=0;i<80;i++){const mid=(lo+hi)/2;if(dischargeTimeSeconds(beta,vt,p.loadCapF,mid,vdd)>seconds)lo=mid;else hi=mid;}const remaining=(lo+hi)/2;return direction==='fall'?remaining:vdd-remaining;
}
function unityGain(p:CellParameters,left:boolean):number{let lo=left?p.thresholdNV:p.switchingV+1e-9,hi=left?p.switchingV-1e-9:cellConstants.supplyV-p.thresholdPV;for(let i=0;i<70;i++){const mid=(lo+hi)/2,gain=Math.abs(inverterTransfer(p,mid).gain??Infinity);if(left?gain<1:gain>1)lo=mid;else hi=mid;}return (lo+hi)/2;}
export function buildCellAcceptance(value:unknown):CellResult{
 const input=normalizeCellInput(value),p=deriveCellParameters(input),vdd=cellConstants.supplyV,vilV=unityGain(p,true),vihV=unityGain(p,false),vohV=inverterTransfer(p,vilV).vout!,volV=inverterTransfer(p,vihV).vout!,noise={vilV,vihV,vohV,volV,nmlV:vilV-volV,nmhV:vohV-vihV};
 const timing={fall50Seconds:dischargeTimeSeconds(p.betaN,p.thresholdNV,p.loadCapF,vdd*.5,vdd),rise50Seconds:dischargeTimeSeconds(p.betaP,p.thresholdPV,p.loadCapF,vdd*.5,vdd),fall90to10Seconds:dischargeTimeSeconds(p.betaN,p.thresholdNV,p.loadCapF,vdd*.1,vdd*.9),rise10to90Seconds:dischargeTimeSeconds(p.betaP,p.thresholdPV,p.loadCapF,vdd*.1,vdd*.9)};
 const transfer=Array.from({length:241},(_,i)=>inverterTransfer(p,i/240*vdd));if(!transfer.some(t=>t.branch==='ideal-transition'))transfer.push(inverterTransfer(p,p.switchingV));transfer.sort((a,b)=>a.vin-b.vin);
 const lowOutput=inverterTransfer(p,.7*vdd).outputHighV,highOutput=inverterTransfer(p,.3*vdd).outputLowV,minNoise=Math.min(noise.nmlV,noise.nmhV),maxDelay=Math.max(timing.fall50Seconds,timing.rise50Seconds)*1e9,logicViolation=Math.max(lowOutput-.2*vdd,.8*vdd-highOutput);
 const gates:CellGate[]=[{id:'oxide',title:'Declared oxide tolerance',actual:Math.abs(input.oxideOffsetPct),limit:input.oxideTolerancePct,unit:'%',pass:Math.abs(input.oxideOffsetPct)<=input.oxideTolerancePct,reason:'Absolute evaluated thickness offset must fit the chosen nominal tolerance; this is one synthetic specimen, not a yield distribution.'},{id:'logic',title:'Declared logic interface',actual:logicViolation,limit:0,unit:'V excess',pass:logicViolation<=1e-12,reason:'Inputs ≤0.3 VDD must give outputs ≥0.8 VDD; inputs ≥0.7 VDD must give outputs ≤0.2 VDD. A positive excess violates either requirement.'},{id:'noise',title:'Unity-gain noise margins',actual:minNoise,limit:input.noiseMinimumV,unit:'V',pass:minNoise+1e-12>=input.noiseMinimumV,reason:'Both DC margins use actual unity-gain output levels; they must meet the declared minimum. No noise spectrum or error probability is calculated.'},{id:'timing',title:'Loaded 50% step delay',actual:maxDelay,limit:input.delayMaximumNs,unit:'ns',pass:maxDelay<=input.delayMaximumNs+1e-12,reason:'Both analytically integrated step delays must fit the chosen maximum. Input edges are instantaneous; no clock or commercial-node timing is inferred.'}];
 const stages=[{id:'oxide',title:'Evaluated oxide specimen',description:`Nominal ${input.oxideNominalNm} nm with ${input.oxideOffsetPct}% offset gives ${p.oxideNm} nm. This number is a synthetic scenario input, not a metrology result.`},{id:'electrical',title:'Capacitance and threshold',description:'One evaluated oxide capacitance changes gate/load capacitance, beta and the fixed-depletion-charge threshold term. The nMOS shift and mobility factor are independently declared perturbations.'},{id:'transfer',title:'Current balance and logic',description:'The inverter transfer balances nMOS and pMOS current. The λ=0 ideal transition has an output interval at its exact switching input, rather than a unique voltage.'},{id:'transition',title:'Loaded charging and discharging',description:'A constant lumped load changes voltage according to C dV/dt = I. The piecewise square-law current is integrated to 50% and 10–90% thresholds.'},{id:'acceptance',title:'Declared cell acceptance',description:'Oxide, logic, noise and timing gates are evaluated separately. Passing their conjunction applies only to this stated teaching contract.'}].map(s=>({...s,specimenId:cellConstants.specimenId}));
 return {version:processCellVersion,specimenId:cellConstants.specimenId,input,parameters:p,transfer,iv:Array.from({length:121},(_,i)=>{const vds=i/120*vdd;return {vds,nCurrentA:longChannelCurrent(p.betaN,p.thresholdNV,vdd,vds),pCurrentMagnitudeA:longChannelCurrent(p.betaP,p.thresholdPV,vdd,vds)};}),noise,timing,transitions:Array.from({length:100},(_,i)=>{const progress=i/100,remaining=vdd*(1-progress);return {progress,fallV:remaining,riseV:vdd-remaining,fallSeconds:dischargeTimeSeconds(p.betaN,p.thresholdNV,p.loadCapF,remaining,vdd),riseSeconds:dischargeTimeSeconds(p.betaP,p.thresholdPV,p.loadCapF,remaining,vdd)};}),gates,accepted:gates.every(g=>g.pass),stages};
}
export type CellInputRecord={schemaVersion:1;modelVersion:typeof processCellVersion;input:CellInput};
export function makeCellRecord(input:unknown):CellInputRecord{return {schemaVersion:1,modelVersion:processCellVersion,input:normalizeCellInput(input)};}
export function parseCellRecord(raw:string):CellInputRecord{ensure(raw.length<=65536,'Input record exceeds 64 KiB.');const x:unknown=JSON.parse(raw);ensure(x&&typeof x==='object'&&!Array.isArray(x),'Record must be an object.');const r=x as Record<string,unknown>;ensure(Object.keys(r).every(k=>['schemaVersion','modelVersion','input'].includes(k))&&r.schemaVersion===1&&r.modelVersion===processCellVersion,'Incompatible model/schema. The original record has not been changed.');return makeCellRecord(r.input);}
