/** Pure teaching arithmetic. No source observations or vendor timing are inferred by these functions. */
export const progressModelVersion='progress-evidence-2';
const check=(c:unknown,m:string)=>{if(!c)throw Error(m);};
const finite=(n:number,min:number,max:number,name:string,integer=false)=>{check(Number.isFinite(n)&&n>=min&&n<=max&&(!integer||Number.isInteger(n)),`Invalid ${name}.`);return n;};
export type GrowthOptions={scenario?:'compute-memory'|'compute-facility';memoryMetric?:'bandwidth'|'capacity';periodYears?:1|2;periods?:number;startYear?:number;computeFactor?:number;comparisonFactor?:number};
export function compareGrowthIndices(value:GrowthOptions={}){
 const defaults={scenario:'compute-memory' as const,memoryMetric:'bandwidth' as const,periodYears:2 as const,periods:5,startYear:2026,computeFactor:3,comparisonFactor:2};
 check(value&&typeof value==='object'&&!Array.isArray(value),'Growth options must be an object.');check(Object.keys(value).every(k=>Object.hasOwn(defaults,k)),'Unknown growth option.');
 const options={...defaults,...value};check(['compute-memory','compute-facility'].includes(options.scenario),'Unknown growth scenario.');check(['bandwidth','capacity'].includes(options.memoryMetric),'Unknown memory metric.');check([1,2].includes(options.periodYears),'A growth interval must be one or two years.');finite(options.periods,0,10,'period count',true);finite(options.startYear,1900,2200,'base year',true);finite(options.computeFactor,.1,10,'compute factor');finite(options.comparisonFactor,.1,10,'comparison factor');
 const memory=options.scenario==='compute-memory',comparisonLabel=memory?(options.memoryMetric==='bandwidth'?'Memory bandwidth':'Memory capacity'):'Commissioned IT capacity';
 const rows=Array.from({length:options.periods+1},(_,period)=>({period,year:options.startYear+period*options.periodYears,computeIndex:100*options.computeFactor**period,comparisonIndex:100*options.comparisonFactor**period,relativeIndexRatio:(options.computeFactor/options.comparisonFactor)**period}));
 return{modelVersion:progressModelVersion,options,scenarioLabel:memory?'Compute versus memory':'Compute versus facility IT capacity',comparisonLabel,basis:`Synthetic conditional assumptions: ${options.computeFactor}× compute versus ${options.comparisonFactor}× ${comparisonLabel.toLowerCase()} per ${options.periodYears}-year interval. These are adjustable assumptions, not an empirical law, fitted historical series or forecast.`,metrics:{compute:'Assumed peak dense FP16 FLOP/s per reference accelerator; keep the operation, precision and device boundary identical across periods.',comparison:memory?(options.memoryMetric==='bandwidth'?'Assumed memory-interface bandwidth in bytes/s per reference accelerator; keep the interface and raw-versus-payload convention identical across periods.':'Assumed memory capacity in bytes per reference accelerator; keep the memory tier, capacity convention and device boundary identical across periods.'):'Assumed commissioned facility IT-power capacity in MW; keep the commissioning and facility boundary identical across periods.'},period:`${options.periodYears} calendar years per step from ${options.startYear}; changing the interval reinterprets the factors and does not annualize them.`,normalization:'Each metric is independently indexed to 100 in the base year; no absolute hardware specification is supplied.',rows,limitation:'The ratio compares relative changes of independently normalized indices. It cannot establish an actual performance deficit, arithmetic intensity, usable FLOP/s, queue, efficiency or a physical conversion between unlike units. A memory-bandwidth index and a memory-capacity index describe different constraints.'};
}
// Quotient tolerance only repairs near-integer binary rounding (e.g. 0.3 / 0.1).
const wholeUnits=(budget:number,perUnit:number)=>{const q=budget/perUnit;return Math.floor(q+8*Number.EPSILON*Math.max(1,Math.abs(q)));};
export type Demand={id:string;units:number};
function checkDemands(ds:readonly Demand[]){check(Array.isArray(ds)&&ds.length<=100,'Invalid demand list.');const ids=new Set();for(const d of ds){check(typeof d.id==='string'&&d.id.length>0&&!ids.has(d.id),'Demand IDs must be nonempty and unique.');ids.add(d.id);finite(d.units,0,1e7,'demand',true);}}
export function allocateDivisibleUnits(capacity:number,demands:readonly Demand[],policy:'listed-order'|'proportional'='listed-order'){
 finite(capacity,0,1e7,'capacity',true);checkDemands(demands);check(['listed-order','proportional'].includes(policy),'Unknown allocation policy.');const requested=demands.reduce((s,d)=>s+d.units,0),available=Math.min(capacity,requested);let remaining=available;
 const rows=demands.map((d,index)=>{const ideal=policy==='proportional'?(requested?available*d.units/requested:0):0,allocated=policy==='listed-order'?Math.min(d.units,remaining):Math.floor(ideal);if(policy==='listed-order')remaining-=allocated;return{id:d.id,index,requested:d.units,ideal:policy==='proportional'?ideal:null,allocated,remainder:policy==='proportional'?ideal-allocated:0};});
 if(policy==='proportional'){remaining=available-rows.reduce((s,r)=>s+r.allocated,0);for(const row of [...rows].sort((a,b)=>b.remainder-a.remainder||a.index-b.index)){if(remaining>0&&row.allocated<row.requested){row.allocated++;remaining--;}}}
 return{capacity,policy,requested,allocated:rows.reduce((s,r)=>s+r.allocated,0),unused:capacity-rows.reduce((s,r)=>s+r.allocated,0),rows:rows.map(r=>({...r,unmet:r.requested-r.allocated})),policyScope:policy==='proportional'?'Integer largest-remainder apportionment, input order breaks exact ties; units can be split across requests.':'Requests served in input order with partial shipment allowed; no private customer priority is inferred.'};
}
export type PackageOptions={logicDies?:number;hbmStacks?:number;stacksPerPackage?:number;assemblySlots?:number;testSlots?:number;policy?:'listed-order'|'proportional';demands?:readonly Demand[]};
export function allocatePackageCapacity(value:PackageOptions={}){
 const o={logicDies:120,hbmStacks:640,stacksPerPackage:8,assemblySlots:90,testSlots:75,policy:'listed-order' as const,demands:[{id:'request-a',units:50},{id:'request-b',units:40},{id:'request-c',units:20}],...value};for(const k of Object.keys(value))check(['logicDies','hbmStacks','stacksPerPackage','assemblySlots','testSlots','policy','demands'].includes(k),'Unknown package option.');
 for(const k of ['logicDies','hbmStacks','assemblySlots','testSlots'] as const)finite(o[k],0,1e7,k,true);finite(o.stacksPerPackage,1,64,'stacks per package',true);
 const constraints={logicDies:o.logicDies,hbmEquivalents:Math.floor(o.hbmStacks/o.stacksPerPackage),assemblySlots:o.assemblySlots,testSlots:o.testSlots},capacity=Math.min(...Object.values(constraints)),allocation=allocateDivisibleUnits(capacity,o.demands,o.policy),made=allocation.allocated;
 return{modelVersion:progressModelVersion,options:o,basis:'Synthetic single-period package allocation. All dies/stacks are compatible and already qualified; each assembly and test slot completes one package. No yield loss, rework, lead time or vendor/customer data is modeled.',constraints,capacity,bindingConstraints:Object.keys(constraints).filter(k=>constraints[k as keyof typeof constraints]===capacity),allocation,used:{logicDies:made,hbmStacks:made*o.stacksPerPackage,assemblySlots:made,testSlots:made},remaining:{logicDies:o.logicDies-made,hbmStacks:o.hbmStacks-made*o.stacksPerPackage,assemblySlots:o.assemblySlots-made,testSlots:o.testSlots-made},scope:'Finite arithmetic illustrates complementarity and an allocation rule, not TSMC production, a wafer-equivalent conversion, observed availability or a customer queue.'};
}
export type HallOptions={installedRacks?:number;commissionedRacks?:number;facilityInputMW?:number;pue?:number;itMWPerRack?:number;coolingITMW?:number;policy?:'first-fit'|'strict-order';demands?:readonly Demand[]};
export function allocateHallCapacity(value:HallOptions={}){
 const o={installedRacks:12,commissionedRacks:9,facilityInputMW:1.2,pue:1.2,itMWPerRack:.1,coolingITMW:.85,policy:'first-fit' as const,demands:[{id:'job-a',units:5},{id:'job-b',units:4},{id:'job-c',units:3}],...value};for(const k of Object.keys(value))check(['installedRacks','commissionedRacks','facilityInputMW','pue','itMWPerRack','coolingITMW','policy','demands'].includes(k),'Unknown hall option.');
 finite(o.installedRacks,0,100000,'installed racks',true);finite(o.commissionedRacks,0,o.installedRacks,'commissioned racks',true);finite(o.facilityInputMW,0,10000,'facility input');finite(o.pue,1,5,'assumed PUE');finite(o.itMWPerRack,.001,10,'IT MW per rack');finite(o.coolingITMW,0,10000,'IT heat rejection');check(['first-fit','strict-order'].includes(o.policy),'Unknown hall policy.');checkDemands(o.demands);
 const itPowerBudgetMW=o.facilityInputMW/o.pue,constraints={installed:o.installedRacks,commissioned:o.commissionedRacks,power:wholeUnits(itPowerBudgetMW,o.itMWPerRack),cooling:wholeUnits(o.coolingITMW,o.itMWPerRack)},capacity=Math.min(...Object.values(constraints));let remaining=capacity,blocked=false;
 const rows=o.demands.map(d=>{const allocated=!blocked&&d.units<=remaining?d.units:0,reason=blocked?'Earlier request blocks strict-order admission.':allocated===d.units?'Entire request fits.':'Entire request does not fit remaining racks.';if(o.policy==='strict-order'&&allocated<d.units)blocked=true;remaining-=allocated;return{id:d.id,requested:d.units,allocated,unmet:d.units-allocated,remainingRacks:remaining,reason};});const allocated=capacity-remaining,itMW=allocated*o.itMWPerRack;
 return{modelVersion:progressModelVersion,options:o,basis:'Synthetic simultaneous admission of whole-rack jobs. PUE is a fixed scenario conversion factor, not a measured site value; all allocated IT power becomes heat. No network/memory compatibility, topology, priorities, job duration or wait times are modeled.',itPowerBudgetMW,constraints,capacity,bindingConstraints:Object.keys(constraints).filter(k=>constraints[k as keyof typeof constraints]===capacity),allocation:{rows,allocated,unused:remaining,unmet:rows.reduce((s,r)=>s+r.unmet,0)},loads:{itMW,facilityMW:itMW*o.pue,overheadMW:itMW*(o.pue-1),rejectedITHeatMW:itMW},scope:'First-fit skips an oversized waiting request; strict-order stops admitting subsequent requests. Neither is asserted to be an actual public-computing or commercial scheduler policy.'};
}
export function idealGateCharge(capacitanceF=2e-15,voltageV=.8){finite(capacitanceF,0,1,'capacitance');finite(voltageV,0,100,'voltage');return{capacitanceF,voltageV,chargeC:capacitanceF*voltageV,storedEnergyJ:.5*capacitanceF*voltageV**2,basis:'Ideal fixed capacitor, not transistor current, leakage or a historic device measurement.'};}
export function lumpedWireRC(resistivityOhmM=2e-8,lengthM=.001,crossSectionM2=1e-14,capacitancePerM=2e-10){finite(resistivityOhmM,0,1,'resistivity');finite(lengthM,0,1e3,'wire length');finite(crossSectionM2,1e-24,1,'cross section');finite(capacitancePerM,0,1,'capacitance per length');const resistanceOhm=resistivityOhmM*lengthM/crossSectionM2,capacitanceF=capacitancePerM*lengthM;return{resistanceOhm,capacitanceF,timeConstantS:resistanceOhm*capacitanceF,basis:'Synthetic uniform wire; lumped R×C timescale excludes distributed geometry, drivers, vias, size effects and coupling.'};}
export function parallelLinkBudget(lanes=256,bitsPerSecondPerLane=2e9,payloadFraction=.8){finite(lanes,1,100000,'lanes',true);finite(bitsPerSecondPerLane,0,1e15,'per-lane rate');finite(payloadFraction,0,1,'payload fraction');return{lanes,bitsPerSecondPerLane,payloadFraction,rawBytesPerSecond:lanes*bitsPerSecondPerLane/8,payloadBytesPerSecond:lanes*bitsPerSecondPerLane*payloadFraction/8,basis:'Synthetic independent lanes at an assumed sustained payload fraction, not a CoWoS or HBM specification.'};}
export function smallMatrixProduct(a:readonly (readonly number[])[]=[[1,2],[3,4]],b:readonly (readonly number[])[]=[[5,6],[7,8]]){
 const n=a.length;check((n===2||n===3)&&b.length===n&&a.every(r=>r.length===n)&&b.every(r=>r.length===n),'Matrices must be matching 2×2 or 3×3.');for(const v of [...a.flat(),...b.flat()])finite(v,-99,99,'matrix operand',true);const output=Array.from({length:n},()=>Array(n).fill(0)),products:{i:number;j:number;k:number;a:number;b:number;product:number;before:number;after:number}[]=[];
 for(let i=0;i<n;i++)for(let j=0;j<n;j++)for(let k=0;k<n;k++){const product=a[i][k]*b[k][j],before=output[i][j];output[i][j]+=product;products.push({i,j,k,a:a[i][k],b:b[k][j],product,before,after:output[i][j]});}return{a:a.map(r=>[...r]),b:b.map(r=>[...r]),output,macCount:products.length,products,basis:'Exact small integer result. Inspect R21 architecture-execution for synthetic scalar/vector/SIMT/systolic schedules; no vendor timing is inferred.'};
}
export function scalarAdamTrace(gradients:readonly number[]=[2,1],learningRate=.1,beta1=.9,beta2=.999,epsilon=1e-8,initial=1){check(gradients.length>0&&gradients.length<=100,'Need 1–100 gradients.');gradients.forEach(g=>finite(g,-100,100,'gradient'));finite(learningRate,0,1,'learning rate');finite(beta1,0,.9999,'beta1');finite(beta2,0,.9999,'beta2');finite(epsilon,1e-12,1,'epsilon');finite(initial,-100,100,'initial parameter');let m=0,v=0,parameter=initial;const steps=gradients.map((gradient,index)=>{const t=index+1,before=parameter;m=beta1*m+(1-beta1)*gradient;v=beta2*v+(1-beta2)*gradient**2;const correctedM=m/(1-beta1**t),correctedV=v/(1-beta2**t),update=learningRate*correctedM/(Math.sqrt(correctedV)+epsilon);parameter-=update;return{index,t,gradient,m,v,correctedM,correctedV,update,before,after:parameter};});return{steps,parameter,basis:'Authored scalar gradients demonstrate Adam moments and bias correction; not training loss, convergence evidence or the SGD classifier used in R26.'};}
export function streamingSoftmax(scores:readonly number[]=[1/Math.sqrt(2),0],values:readonly number[]=[10,20]){
 check(scores.length>0&&scores.length<=100&&scores.length===values.length,'Scores and values must have the same length, 1–100.');scores.forEach(s=>finite(s,-10000,10000,'score'));values.forEach(v=>finite(v,-1e10,1e10,'value'));const maximum=Math.max(...scores),exps=scores.map(s=>Math.exp(s-maximum)),sum=exps.reduce((a,b)=>a+b,0),weights=exps.map(e=>e/sum),reference=weights.reduce((a,w,i)=>a+w*values[i],0);let m=-Infinity,mass=0,numerator=0;
 const steps=scores.map((score,index)=>{const oldMax=Number.isFinite(m)?m:null,oldMass=mass,oldNumerator=numerator,nextMax=Math.max(m,score),rescale=mass?Math.exp(m-nextMax):0,newWeight=Math.exp(score-nextMax);mass=mass*rescale+newWeight;numerator=numerator*rescale+newWeight*values[index];m=nextMax;return{index,score,value:values[index],before:{maximum:oldMax,mass:oldMass,numerator:oldNumerator},rescale,newWeight,after:{maximum:m,mass,numerator},partialOutput:numerator/mass};});
 return{scores:[...scores],values:[...values],weights,reference,streamed:numerator/mass,steps,temporaryScoreWords:1,fullScoreRowWords:scores.length,basis:'Scalar one-row online softmax illustrates rescaling and unchanged output. It is not a complete FlashAttention kernel or measured HBM traffic; Q/K/V, state, output and hardware storage are excluded from temporary-score counts.'};
}
export function pagedKvAllocation(lengths:readonly number[]=[5,7,2],blockTokens=4,reservationPerRequest=8){check(lengths.length>0&&lengths.length<=100,'Need 1–100 request lengths.');lengths.forEach(n=>finite(n,0,1e6,'length',true));finite(blockTokens,1,1e6,'block size',true);finite(reservationPerRequest,Math.max(...lengths),1e6,'contiguous reservation',true);let nextBlock=0;const rows=lengths.map((liveTokens,request)=>{const blocks=Math.ceil(liveTokens/blockTokens),physicalBlockIds=Array.from({length:blocks},()=>nextBlock++),allocatedTokens=blocks*blockTokens;return{request,liveTokens,blocks,physicalBlockIds,allocatedTokens,unusedTokens:allocatedTokens-liveTokens};});const liveTokens=lengths.reduce((a,b)=>a+b,0),pagedTokens=nextBlock*blockTokens,contiguousTokens=lengths.length*reservationPerRequest;return{rows,liveTokens,blocks:nextBlock,pagedTokens,contiguousTokens,pagedUnusedTokens:pagedTokens-liveTokens,contiguousUnusedTokens:contiguousTokens-liveTokens,savedReservedTokens:contiguousTokens-pagedTokens,basis:'Synthetic token-slot allocation with fixed-size blocks; no sharing, metadata cost, quantization, multiple layers, scheduler or physical token-byte claim. A negative saving is possible under a different reservation convention.'};}
export function sourceFreshness(lastCheckedOn:string|null,cadenceDays:number,asOfDate:string){
 finite(cadenceDays,1,3660,'review cadence',true);
 const parse=(s:string)=>{check(/^\d{4}-\d{2}-\d{2}$/.test(s),'Date must be YYYY-MM-DD.');const ms=Date.parse(s+'T00:00:00Z');check(Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,10)===s,'Invalid date.');return ms;};
 const now=parse(asOfDate);if(lastCheckedOn===null)return{status:'baseline-review-needed',dueOn:null,asOfDate,basis:'No source-check date has been recorded.'};const last=parse(lastCheckedOn);check(last<=now,'Source check cannot be in the future.');const due=last+cadenceDays*86400000;return{status:now>=due?'recheck-due':'within-review-cadence',dueOn:new Date(due).toISOString().slice(0,10),asOfDate,basis:'A review cadence reminder, not proof that a source is current or a statement still holds.'};
}
