/** A finite authored recommendation experiment: no real user log, position model or fairness claim. */
export const rankingVersion='exposure-aware-ranking-1';
export type RankingInput={seed:number;policy:'uniform'|'popularity'|'zero-support';estimator:'observed'|'ips'|'clipped-ips';propensities:'known'|'assume-uniform';clipWeight:number;appeal:number;steps:number;regularization:number;k:number};
export const rankingDefaults:RankingInput={seed:7,policy:'popularity',estimator:'ips',propensities:'known',clipWeight:3,appeal:0,steps:300,regularization:.01,k:3};
export type RankingUser={id:string;hardware:number;models:number;split:'train'|'evaluation'};
export type RankingItem={id:string;title:string;hardware:number;models:number;popularity:number};
export const rankingUsers:readonly RankingUser[]=Object.freeze([{id:'train-01',hardware:1,models:0,split:'train'},{id:'train-02',hardware:0,models:1,split:'train'},{id:'train-03',hardware:.9,models:.1,split:'train'},{id:'train-04',hardware:.1,models:.9,split:'train'},{id:'train-05',hardware:.65,models:.35,split:'train'},{id:'train-06',hardware:.35,models:.65,split:'train'},{id:'evaluation-A',hardware:.8,models:.2,split:'evaluation'},{id:'evaluation-B',hardware:.2,models:.8,split:'evaluation'}]);
export const rankingItems:readonly RankingItem[]=Object.freeze([{id:'I01',title:'Silicon interfaces',hardware:1,models:0,popularity:.2},{id:'I02',title:'Memory systems',hardware:.9,models:.15,popularity:.4},{id:'I03',title:'Tensor proofs',hardware:0,models:1,popularity:.1},{id:'I04',title:'Model objectives',hardware:.15,models:.9,popularity:.35},{id:'I05',title:'Technology headlines',hardware:.2,models:.2,popularity:1},{id:'I06',title:'Product launch digest',hardware:.3,models:.3,popularity:.9},{id:'I07',title:'Compute co-design',hardware:.75,models:.75,popularity:.5},{id:'I08',title:'Application evaluation',hardware:.4,models:.6,popularity:.65}]);
export const rankingConstants={visits:2,trainingUsers:6,evaluationUsers:2,items:8,eligibleTrainingRows:96,potentialFeedbackSeed:331027,learningRate:.2,parameters:3,featureNames:['intercept','user–item topic match','item popularity']} as const;
function ensure(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
export function normalizeRankingInput(value:unknown):RankingInput{ensure(value&&typeof value==='object'&&!Array.isArray(value),'Ranking inputs must be an object.');const v=value as RankingInput;ensure(Object.keys(v).length===Object.keys(rankingDefaults).length&&Object.keys(rankingDefaults).every(k=>Object.hasOwn(v,k)),'Unknown or missing input field.');for(const [key,lo,hi,integer] of [['seed',1,10000,true],['clipWeight',1,20,false],['appeal',0,1,false],['steps',1,600,true],['regularization',0,.2,false],['k',1,8,true]] as const){const x=v[key];ensure(typeof x==='number'&&Number.isFinite(x)&&x>=lo&&x<=hi&&(!integer||Number.isInteger(x)),`Invalid ${key}.`);}ensure(['uniform','popularity','zero-support'].includes(v.policy),'Invalid logging policy.');ensure(['observed','ips','clipped-ips'].includes(v.estimator),'Invalid estimator.');ensure(['known','assume-uniform'].includes(v.propensities),'Invalid propensity choice.');return {...v};}
function random(seed:number){let state=seed>>>0;return()=>{state=(Math.imul(1664525,state)+1013904223)>>>0;return state/4294967296;};}
export function rankingFeatures(user:RankingUser,item:RankingItem):[number,number,number]{return [1,user.hardware*item.hardware+user.models*item.models,item.popularity];}
export function usefulnessGrade(user:RankingUser,item:RankingItem){const match=rankingFeatures(user,item)[1];return match>=.7?2:match>=.45?1:0;}
export function loggingProbability(item:RankingItem,policy:RankingInput['policy']){return policy==='uniform'?.6:policy==='zero-support'&&item.popularity<.5?0:.1+.8*item.popularity;}
export type ExposureRow={id:string;userId:string;itemId:string;visit:number;features:[number,number,number];propensity:number;exposureDraw:number;shown:boolean;click:0|1|null;authorPotentialClick:0|1;authorClickProbability:number;authorUsefulnessGrade:number};
export type RankingSample={id:string;features:[number,number,number];click:0|1;propensity:number};
export function createExposureLog(input:RankingInput):ExposureRow[]{const v=normalizeRankingInput(input),clickDraw=random(rankingConstants.potentialFeedbackSeed),exposureDraw=random(700001+v.seed),rows:ExposureRow[]=[];for(const user of rankingUsers.filter(u=>u.split==='train'))for(let visit=1;visit<=2;visit++)for(const item of rankingItems){const features=rankingFeatures(user,item),propensity=loggingProbability(item,v.policy),draw=exposureDraw(),base=.1+.8*features[1],q=(1-v.appeal)*base+v.appeal*(.1+.8*item.popularity),potential:0|1=clickDraw()<q?1:0,shown=draw<propensity;rows.push({id:`${user.id}/${item.id}/visit-${visit}`,userId:user.id,itemId:item.id,visit,features,propensity,exposureDraw:draw,shown,click:shown?potential:null,authorPotentialClick:potential,authorClickProbability:q,authorUsefulnessGrade:usefulnessGrade(user,item)});}return rows;}
export function observedRankingSamples(log:readonly ExposureRow[]):RankingSample[]{return log.filter(r=>r.shown).map(r=>{ensure(r.click===0||r.click===1,'An exposed row needs its actual binary feedback.');ensure(r.propensity>0&&r.propensity<=1,'An observed row needs positive valid logging probability.');return {id:r.id,features:[...r.features],click:r.click,propensity:r.propensity};});}
export function zeroSupportWorlds(log:readonly ExposureRow[]){const missing=log.filter(r=>r.propensity===0).length;if(!missing)return null;const worldZero=log.map(r=>r.propensity===0?{...r,authorPotentialClick:0 as const}:r),worldOne=log.map(r=>r.propensity===0?{...r,authorPotentialClick:1 as const}:r);return {unsupportedRows:missing,population:log.length,worldZeroMean:worldZero.reduce((s,r)=>s+r.authorPotentialClick,0)/log.length,worldOneMean:worldOne.reduce((s,r)=>s+r.authorPotentialClick,0)/log.length,identicalObservedSamples:JSON.stringify(observedRankingSamples(worldZero))===JSON.stringify(observedRankingSamples(worldOne))};}
export function rankingWeight(sample:RankingSample,input:RankingInput){if(input.estimator==='observed')return 1;const p=input.propensities==='known'?sample.propensity:.6;ensure(p>0&&p<=1,'Inverse propensity requires positive probability.');const inverse=1/p;return input.estimator==='clipped-ips'?Math.min(input.clipWeight,inverse):inverse;}
const sigmoid=(x:number)=>x>=0?1/(1+Math.exp(-x)):Math.exp(x)/(1+Math.exp(x));
const dot=(a:readonly number[],b:readonly number[])=>a.reduce((s,x,i)=>s+x*b[i],0);
export function rankingBinaryLoss(score:number,label:number){return Math.max(score,0)-label*score+Math.log1p(Math.exp(-Math.abs(score)));}
export function rankingObjective(theta:readonly number[],samples:readonly RankingSample[],input:RankingInput,eligible=96){ensure(theta.length===3&&theta.every(Number.isFinite),'Three finite fitted parameters required.');ensure(Number.isInteger(eligible)&&eligible>=samples.length&&eligible>0,'Invalid eligible population denominator.');const denominator=input.estimator==='observed'?samples.length:eligible,gradient=[0,0,0];let loss=0;ensure(denominator>0,'No exposed observations are available to fit.');for(const sample of samples){ensure(sample.features.length===3&&sample.features.every(Number.isFinite)&&(sample.click===0||sample.click===1),'Invalid observed sample.');const score=dot(theta,sample.features),weight=rankingWeight(sample,input),error=sigmoid(score)-sample.click;loss+=weight*rankingBinaryLoss(score,sample.click)/denominator;for(let j=0;j<3;j++)gradient[j]+=weight*error*sample.features[j]/denominator;}const dataLoss=loss;for(let j=1;j<3;j++){loss+=input.regularization*theta[j]**2/2;gradient[j]+=input.regularization*theta[j];}return {loss,dataLoss,gradient,denominator};}
export type RankingFit={theta:number[];history:{step:number;loss:number;dataLoss:number;gradientNorm:number;theta:number[]}[];samples:number;denominator:number;weightSum:number;weightSquareSum:number;effectiveSampleSize:number;largestWeight:number};
export function fitRanking(samples:readonly RankingSample[],input:RankingInput,eligible=96):RankingFit{ensure(samples.length>0,'No exposed observations are available to fit.');const v=normalizeRankingInput(input),history:RankingFit['history']=[];let theta=[0,0,0];for(let step=0;step<=v.steps;step++){const r=rankingObjective(theta,samples,v,eligible);if(step%10===0||step===v.steps)history.push({step,loss:r.loss,dataLoss:r.dataLoss,gradientNorm:Math.hypot(...r.gradient),theta:[...theta]});if(step<v.steps)theta=theta.map((x,j)=>x-rankingConstants.learningRate*r.gradient[j]);}const weights=samples.map(s=>rankingWeight(s,v)),weightSum=weights.reduce((a,b)=>a+b,0),weightSquareSum=weights.reduce((a,b)=>a+b*b,0);return {theta,history,samples:samples.length,denominator:v.estimator==='observed'?samples.length:eligible,weightSum,weightSquareSum,effectiveSampleSize:weightSquareSum?weightSum*weightSum/weightSquareSum:0,largestWeight:Math.max(...weights)};}
export type RankedItem={id:string;title:string;score:number;grade:number;gain:number;rank:number;discount:number;dcgContribution:number};
export function rankingMetrics(orderedGrades:readonly number[],k:number){ensure(Number.isInteger(k)&&k>=1&&k<=orderedGrades.length,'Invalid ranking cutoff.');ensure(orderedGrades.every(g=>Number.isInteger(g)&&g>=0&&g<=2),'Grades must be 0, 1 or 2.');const dcg=(grades:readonly number[])=>grades.slice(0,k).reduce((sum,g,i)=>sum+(2**g-1)/Math.log2(i+2),0),actual=dcg(orderedGrades),ideal=dcg([...orderedGrades].sort((a,b)=>b-a)),relevant=orderedGrades.filter(g=>g===2).length,hits=orderedGrades.slice(0,k).filter(g=>g===2).length;return {dcg:actual,idcg:ideal,ndcg:ideal?actual/ideal:0,hits,relevant,recall:relevant?hits/relevant:0,precision:hits/k,k};}
export function rankEvaluationUser(user:RankingUser,theta:readonly number[],k:number,baseline=false){ensure(user.split==='evaluation','Ranking evaluation is restricted to the disjoint evaluation users.');ensure(theta.length===3&&theta.every(Number.isFinite),'Ranking needs three finite score parameters.');const order=rankingItems.map(item=>({id:item.id,title:item.title,score:baseline?item.popularity:sigmoid(dot(theta,rankingFeatures(user,item))),grade:usefulnessGrade(user,item)})).sort((a,b)=>b.score-a.score||(a.id<b.id?-1:a.id>b.id?1:0)),items:RankedItem[]=order.map((r,i)=>({...r,gain:2**r.grade-1,rank:i+1,discount:1/Math.log2(i+2),dcgContribution:(2**r.grade-1)/Math.log2(i+2)}));return {userId:user.id,items,metrics:rankingMetrics(items.map(i=>i.grade),k)};}
export type RankingResult=ReturnType<typeof buildRankingApplication>;
export function buildRankingApplication(value:RankingInput=rankingDefaults){const input=normalizeRankingInput(value),log=createExposureLog(input),samples=observedRankingSamples(log),fit=fitRanking(samples,input,log.length),observedFit=fitRanking(samples,{...input,estimator:'observed'},log.length),evaluation=rankingUsers.filter(u=>u.split==='evaluation').map(user=>({user,selected:rankEvaluationUser(user,fit.theta,input.k),observed:rankEvaluationUser(user,observedFit.theta,input.k),baseline:rankEvaluationUser(user,fit.theta,input.k,true)})),unsupportedRows=log.filter(r=>r.propensity===0).length,weights=samples.map(s=>rankingWeight(s,input)),clippedRows=input.estimator==='clipped-ips'?samples.filter(s=>1/(input.propensities==='known'?s.propensity:.6)>input.clipWeight).length:0;
 const oracleClickLoss=log.reduce((sum,r)=>sum+rankingBinaryLoss(dot(fit.theta,r.features),r.authorPotentialClick),0)/log.length,knownIpsClickMean=samples.reduce((sum,s)=>sum+s.click/s.propensity,0)/log.length,observedClickMean=samples.reduce((sum,s)=>sum+s.click,0)/samples.length,authorPotentialClickMean=log.reduce((sum,r)=>sum+r.authorPotentialClick,0)/log.length;
 return {modelVersion:rankingVersion,input,log,samples,fit,observedFit,evaluation,zeroSupportWorlds:zeroSupportWorlds(log),diagnostics:{eligibleRows:log.length,shownRows:samples.length,unshownRows:log.length-samples.length,unsupportedRows,clippedRows,oracleClickLoss,observedClickMean,knownIpsClickMean,authorPotentialClickMean,weightSum:weights.reduce((a,b)=>a+b,0),fullSupport:unsupportedRows===0,correctPropensities:input.propensities==='known'||input.policy==='uniform',fixedScoreUnbiasedDesign:unsupportedRows===0&&(input.propensities==='known'||input.policy==='uniform')&&input.estimator==='ips',relevanceEqualsClick:false},summary:{users:evaluation.length,selectedNdcg:evaluation.reduce((s,e)=>s+e.selected.metrics.ndcg,0)/evaluation.length,observedNdcg:evaluation.reduce((s,e)=>s+e.observed.metrics.ndcg,0)/evaluation.length,baselineNdcg:evaluation.reduce((s,e)=>s+e.baseline.metrics.ndcg,0)/evaluation.length,selectedRecall:evaluation.reduce((s,e)=>s+e.selected.metrics.recall,0)/evaluation.length,baselineRecall:evaluation.reduce((s,e)=>s+e.baseline.metrics.recall,0)/evaluation.length}};
}
export function serializeRankingInputs(input:RankingInput){return JSON.stringify({schemaVersion:1,modelVersion:rankingVersion,input:normalizeRankingInput(input)},null,2);}
export function readRankingInputs(raw:string){ensure(raw.length<=20000,'Ranking input record exceeds 20,000 characters.');const r:unknown=JSON.parse(raw);ensure(r&&typeof r==='object'&&!Array.isArray(r),'Invalid record.');const x=r as Record<string,unknown>;ensure(Object.keys(x).length===3&&x.schemaVersion===1&&x.modelVersion===rankingVersion&&Object.hasOwn(x,'input'),'Incompatible ranking model or schema.');return normalizeRankingInput(x.input);}

export const rankingFormulas={
 score:String.raw`s_\theta(u,i)=\theta_0+\theta_1\langle a_u,b_i\rangle+\theta_2 p_i,\qquad \widehat c_{ui}=\sigma(s_\theta(u,i))`,
 observed:String.raw`\widehat R_{\mathrm{obs}}(\theta)=\frac{1}{n_{\mathrm{shown}}}\sum_{j:O_j=1}\ell(\theta;x_j,c_j)+\frac{\lambda}{2}(\theta_1^2+\theta_2^2)`,
 ips:String.raw`\widehat R(\theta)=\frac{1}{N}\sum_{j:O_j=1}w_j\,\ell(\theta;x_j,c_j)+\frac{\lambda}{2}(\theta_1^2+\theta_2^2)`,
 ndcg:String.raw`\operatorname{DCG}@k=\sum_{r=1}^{k}\frac{2^{g_r}-1}{\log_2(r+1)},\qquad \operatorname{NDCG}@k=\frac{\operatorname{DCG}@k}{\operatorname{IDCG}@k}`,
};
