import {retrievalDataset,type RetrievalDataset,type RetrievalQuestion,type ManualFact,type FactAttribute} from './application-data.ts';
export const retrievalModelVersion='lexical-cited-answer-1';
export type AnswerMode='top-passage'|'slot-filtered';
export type RetrievalCost={fixedLatencyUs:number;dictionaryProbeLatencyUs:number;contextTokenLatencyUs:number};
export type RetrievalOptions={topK?:number;minScore?:number;answerMode?:AnswerMode;queryId?:string;minimumTaskAccuracy?:number;maximumUnsupportedFraction?:number;latencyBudgetUs?:number;cost?:Partial<RetrievalCost>};
export type TermWeight={term:string;count:number;documentFrequency:number;idf:number;weight:number};
export type RetrievalIndex={documentCount:number;vocabulary:string[];documentFrequency:Record<string,number>;idf:Record<string,number>;documents:{documentId:string;tokens:string[];weights:TermWeight[];norm:number}[];fitBasis:string};
export type RankedDocument={documentId:string;score:number;dot:number;documentNorm:number;queryNorm:number;overlap:{term:string;queryWeight:number;documentWeight:number;product:number}[]};
export type CitedAnswer={text:string;fact:ManualFact;citation:{documentId:string;quote:string}};
export type AnswerGrade={answered:boolean;expectedAnswerAvailable:boolean;sourceSupported:boolean|null;answerValueCorrect:boolean|null;taskCorrect:boolean;citationChecks:{knownFact:boolean;correctDocument:boolean;exactFactFields:boolean;exactQuote:boolean}|null};
const defaults={topK:2,minScore:.1,answerMode:'slot-filtered' as AnswerMode,queryId:'question-03',minimumTaskAccuracy:.8,maximumUnsupportedFraction:0,latencyBudgetUs:100,cost:{fixedLatencyUs:50,dictionaryProbeLatencyUs:.05,contextTokenLatencyUs:1}};
const ensure=(condition:unknown,message:string)=>{if(!condition)throw Error(message);};
const range=(v:unknown,min:number,max:number,name:string,integer=false)=>ensure(typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max&&(!integer||Number.isInteger(v)),`Invalid ${name}.`);
export function resolveRetrievalOptions(value:RetrievalOptions={}){
 ensure(value&&typeof value==='object'&&!Array.isArray(value),'Options must be an object.');ensure(Object.keys(value).every(k=>Object.keys(defaults).includes(k)),'Unknown retrieval option.');
 const x={...defaults,...value,cost:{...defaults.cost,...value.cost}};range(x.topK,1,4,'topK',true);range(x.minScore,0,1,'minimum score');ensure(['top-passage','slot-filtered'].includes(x.answerMode),'Unknown answer mode.');ensure(typeof x.queryId==='string'&&x.queryId.length,'Invalid query ID.');range(x.minimumTaskAccuracy,0,1,'minimum task accuracy');range(x.maximumUnsupportedFraction,0,1,'unsupported fraction');range(x.latencyBudgetUs,0,1e6,'latency budget');
 if(value.cost!==undefined){ensure(value.cost&&typeof value.cost==='object'&&!Array.isArray(value.cost),'Cost must be an object.');ensure(Object.keys(value.cost).every(k=>Object.keys(defaults.cost).includes(k)),'Unknown retrieval cost.');}
 for(const [k,v]of Object.entries(x.cost))range(v,0,1e4,k);return x;
}
const stop=new Set(['what','is','the','a','an','of','for','to','in','how','many','does','do','are','from','who','and','with','its','this','please','s']);
const rawTokens=(text:string)=>text.toLowerCase().match(/[a-z0-9]+/g)||[];
export const retrievalTokens=(text:string)=>rawTokens(text).filter(t=>!stop.has(t));
const frequencies=(tokens:readonly string[])=>{const out:Record<string,number>=Object.create(null);for(const t of tokens)out[t]=(out[t]||0)+1;return out;};
export function fitRetrievalIndex(dataset:RetrievalDataset=retrievalDataset):RetrievalIndex{
 ensure(dataset.documents.length>0,'A document corpus is required.');const documentIds=new Set(),factIds=new Set();
 for(const d of dataset.documents){ensure(d.id&&!documentIds.has(d.id)&&d.text,'Documents need unique IDs and text.');documentIds.add(d.id);for(const f of d.facts){ensure(f.id&&!factIds.has(f.id)&&f.documentId===d.id&&d.text.includes(f.statement),'Facts must belong to their stated document.');factIds.add(f.id);}}
 const tokenRows=dataset.documents.map(d=>({documentId:d.id,tokens:retrievalTokens(d.text)})),df:Record<string,number>=Object.create(null);
 for(const d of tokenRows)for(const t of new Set(d.tokens))df[t]=(df[t]||0)+1;
 const vocabulary=Object.keys(df).sort(),idf=Object.fromEntries(vocabulary.map(t=>[t,Math.log(dataset.documents.length/df[t])]));
 const documents=tokenRows.map(d=>{const tf=frequencies(d.tokens),weights=Object.keys(tf).sort().map(term=>({term,count:tf[term],documentFrequency:df[term],idf:idf[term],weight:tf[term]*idf[term]}));return{...d,weights,norm:Math.sqrt(weights.reduce((s,w)=>s+w.weight*w.weight,0))};});
 return{documentCount:documents.length,vocabulary,documentFrequency:{...df},idf,documents,fitBasis:'Raw term frequency × ln(N/df), fitted on the reference documents only; query labels are not used.'};
}
function parseSlots(question:string,dataset:RetrievalDataset){
 const lower=question.toLowerCase(),entities=[...new Set(dataset.documents.flatMap(d=>d.facts.map(f=>f.entity)))];
 const mentioned=entities.map(entity=>({entity,position:lower.search(new RegExp('\\b'+entity.toLowerCase()+'\\b'))})).filter(x=>x.position>=0).sort((a,b)=>a.position-b.position);
 let attribute:FactAttribute|null=null;
 if(/\b(sampling|sample|sampled|interval|milliseconds)\b/.test(lower))attribute='sampleIntervalMs';
 else if(/\b(voltage|volts|input)\b/.test(lower))attribute='inputLimitV';
 else if(/\b(log|logs|retain|retains|retention|days)\b/.test(lower))attribute='logRetentionDays';
 return{entity:mentioned[0]?.entity??null,attribute,mentionedEntities:mentioned.map(x=>x.entity),rule:'First named known entity; explicit attribute keyword groups. No negation, coreference or general semantic understanding.'};
}
/** Answer construction consumes question text and documents, never expected answer labels. */
export function retrieveAndAnswer(question:string,value:RetrievalOptions={},dataset:RetrievalDataset=retrievalDataset,index:RetrievalIndex=fitRetrievalIndex(dataset)){
 ensure(typeof question==='string'&&question.length<=4000,'Question must be text of at most 4000 characters.');const options=resolveRetrievalOptions(value),tokens=retrievalTokens(question),tf=frequencies(tokens),known=Object.keys(tf).filter(t=>Object.hasOwn(index.idf,t)).sort(),ignoredTerms=[...new Set(tokens.filter(t=>!Object.hasOwn(index.idf,t)))];
 const queryWeights:TermWeight[]=known.map(term=>({term,count:tf[term],documentFrequency:index.documentFrequency[term],idf:index.idf[term],weight:tf[term]*index.idf[term]})),queryNorm=Math.sqrt(queryWeights.reduce((s,w)=>s+w.weight*w.weight,0));
 const ranked:RankedDocument[]=index.documents.map(d=>{const dw=new Map(d.weights.map(t=>[t.term,t.weight]));const overlap=queryWeights.filter(q=>(dw.get(q.term)||0)>0).map(q=>({term:q.term,queryWeight:q.weight,documentWeight:dw.get(q.term)!,product:q.weight*dw.get(q.term)!})),dot=overlap.reduce((s,t)=>s+t.product,0),score=queryNorm&&d.norm?Math.min(1,dot/(queryNorm*d.norm)):0;return{documentId:d.documentId,score,dot,documentNorm:d.norm,queryNorm,overlap};}).sort((a,b)=>b.score-a.score||(a.documentId<b.documentId?-1:a.documentId>b.documentId?1:0));
 const selected=ranked.filter(r=>r.score>0&&r.score>=options.minScore).slice(0,options.topK),slots=parseSlots(question,dataset),candidates=selected.flatMap(r=>dataset.documents.find(d=>d.id===r.documentId)!.facts);
 const chosen=options.answerMode==='top-passage'?candidates[0]:candidates.find(f=>f.entity===slots.entity&&f.attribute===slots.attribute);
 const answer:CitedAnswer|null=chosen?{text:chosen.statement,fact:{...chosen},citation:{documentId:chosen.documentId,quote:chosen.statement}}:null;
 const dictionaryProbes=index.documents.length*queryWeights.length,weightProducts=ranked.reduce((s,r)=>s+r.overlap.length,0),contextTokenCount=selected.reduce((s,r)=>s+rawTokens(dataset.documents.find(d=>d.id===r.documentId)!.text).length,0);
 const modeledLatencyUs=options.cost.fixedLatencyUs+dictionaryProbes*options.cost.dictionaryProbeLatencyUs+contextTokenCount*options.cost.contextTokenLatencyUs;
 return{question,tokens,ignoredTerms,queryWeights,queryNorm,ranked,selectedDocumentIds:selected.map(r=>r.documentId),slots,answer,selectionReason:answer?(options.answerMode==='top-passage'?'Copy the first fact from the highest-ranked surviving passage.':'Copy the first surviving fact matching the simple entity/attribute slots.'):(selected.length?'No surviving fact matches both parsed slots.':'No passage has a positive score at or above the selected threshold.'),resourceScenario:{basis:'Hypothetical per-query additive cost; not observed runtime, provider latency or tokenizer billing.',dictionaryProbes,weightProducts,contextTokenCount,contextTokenConvention:'ASCII word/number tokens before stop-word filtering; not LLM tokens.',modeledLatencyUs,latencyBudgetUs:options.latencyBudgetUs,latencyPassed:modeledLatencyUs<=options.latencyBudgetUs}};
}
export function gradeCitedAnswer(answer:CitedAnswer|null,question:RetrievalQuestion,dataset:RetrievalDataset=retrievalDataset):AnswerGrade{
 const expectedAnswerAvailable=question.expectedFactIds.length>0;
 if(!answer)return{answered:false,expectedAnswerAvailable,sourceSupported:null,answerValueCorrect:null,taskCorrect:!expectedAnswerAvailable,citationChecks:null};
 const actual=dataset.documents.flatMap(d=>d.facts).find(f=>f.id===answer.fact.id),doc=dataset.documents.find(d=>d.id===answer.citation.documentId);
 const citationChecks={knownFact:Boolean(actual),correctDocument:Boolean(actual&&doc&&actual.documentId===doc.id&&doc.facts.some(f=>f.id===actual.id)),exactFactFields:Boolean(actual&&(['id','documentId','entity','attribute','value','unit','statement'] as const).every(k=>answer.fact[k]===actual[k])),exactQuote:Boolean(actual&&doc&&answer.text===actual.statement&&answer.citation.quote===actual.statement&&doc.text.includes(answer.citation.quote))};
 const sourceSupported=Object.values(citationChecks).every(Boolean),answerValueCorrect=Boolean(actual&&citationChecks.exactFactFields&&question.expectedFactIds.includes(actual.id));
 return{answered:true,expectedAnswerAvailable,sourceSupported,answerValueCorrect,taskCorrect:sourceSupported&&answerValueCorrect,citationChecks};
}
export function evaluateRetrievalQuestions(questions:readonly RetrievalQuestion[],value:RetrievalOptions={},dataset:RetrievalDataset=retrievalDataset,index:RetrievalIndex=fitRetrievalIndex(dataset)){
 ensure(questions.length>0,'An evaluation split must not be empty.');const rows=questions.map(q=>{const trace=retrieveAndAnswer(q.question,value,dataset,index),grade=gradeCitedAnswer(trace.answer,q,dataset),retrievedExpected=q.expectedFactIds.length?dataset.documents.some(d=>trace.selectedDocumentIds.includes(d.id)&&d.facts.some(f=>q.expectedFactIds.includes(f.id))):null;return{queryId:q.id,note:q.note,expectedFactIds:[...q.expectedFactIds],trace,grade,retrievedExpected};});
 const count=rows.length,answered=rows.filter(r=>r.grade.answered).length,answerable=rows.filter(r=>r.grade.expectedAnswerAvailable).length,unanswerable=count-answerable,correct=rows.filter(r=>r.grade.taskCorrect).length,supported=rows.filter(r=>r.grade.sourceSupported===true).length,unsupported=rows.filter(r=>r.grade.sourceSupported===false).length,correctAnswer=rows.filter(r=>r.grade.answered&&r.grade.taskCorrect).length,correctAbstentions=rows.filter(r=>!r.grade.answered&&r.grade.taskCorrect).length;
 return{rows,metrics:{count,answered,abstained:count-answered,answerable,unanswerable,correct,incorrect:count-correct,taskAccuracy:correct/count,supportedAnswers:supported,unsupportedAnswers:unsupported,sourceSupportAmongAnswers:answered?supported/answered:null,unsupportedFractionAmongAnswers:answered?unsupported/answered:null,correctAnswersAmongAnswerable:answerable?correctAnswer/answerable:null,retrievalRecallAtK:answerable?rows.filter(r=>r.retrievedExpected===true).length/answerable:null,correctAbstentions,unanswerableAbstentionRecall:unanswerable?correctAbstentions/unanswerable:null}};
}
export function calibrateRetrievalPolicy(value:Pick<RetrievalOptions,'topK'|'answerMode'>={},dataset:RetrievalDataset=retrievalDataset){
 const index=fitRetrievalIndex(dataset),trials=Array.from({length:11},(_,i)=>{const minScore=i/10,metrics=evaluateRetrievalQuestions(dataset.tuning,{...value,minScore},dataset,index).metrics;return{minScore,metrics};}),best=[...trials].sort((a,b)=>b.metrics.taskAccuracy-a.metrics.taskAccuracy||b.minScore-a.minScore)[0];
 return{basis:'Only tuning questions and their labels select this threshold. Highest tuning task accuracy wins; ties prefer the higher threshold.',usedQueryIds:dataset.tuning.map(q=>q.id),trials,recommendedMinScore:best.minScore};
}
export function runRetrievalApplication(value:RetrievalOptions={},dataset:RetrievalDataset=retrievalDataset){
 const options=resolveRetrievalOptions(value),index=fitRetrievalIndex(dataset),all=[...dataset.tuning,...dataset.evaluation],ids=all.map(q=>q.id);ensure(new Set(ids).size===ids.length,'Tuning and evaluation query IDs must be disjoint.');const facts=new Set(dataset.documents.flatMap(d=>d.facts.map(f=>f.id)));for(const q of all)ensure(q.expectedFactIds.every(id=>facts.has(id)),'Unknown expected fact ID.');const selected=all.find(q=>q.id===options.queryId);ensure(selected,'Unknown selected query ID.');
 const tuning=evaluateRetrievalQuestions(dataset.tuning,options,dataset,index),evaluation=evaluateRetrievalQuestions(dataset.evaluation,options,dataset,index),selectedQuery=[...tuning.rows,...evaluation.rows].find(r=>r.queryId===options.queryId)!,calibration=calibrateRetrievalPolicy({topK:options.topK,answerMode:options.answerMode},dataset),m=evaluation.metrics;
 const accuracyPassed=m.taskAccuracy>=options.minimumTaskAccuracy,sourceSupportPassed=m.unsupportedFractionAmongAnswers===null?null:m.unsupportedFractionAmongAnswers<=options.maximumUnsupportedFraction;
 const nonzeroWeights=index.documents.reduce((s,d)=>s+d.weights.filter(w=>w.weight!==0).length,0);
 return{modelVersion:retrievalModelVersion,dataVersion:dataset.version,options,index,selectedQuery,tuning,evaluation,calibration,qualityGate:{basis:'User-selected criteria on the explicitly listed synthetic held-out query set; source support and task relevance are scored separately.',accuracyPassed,sourceSupportPassed,passed:accuracyPassed&&sourceSupportPassed===true},indexResourceScenario:{basis:'Sparse payload convention only: one 32-bit term ID and one binary64 weight per nonzero pair. Excludes strings, metadata, postings pointers, runtime objects and index construction.',documentCount:index.documentCount,vocabularySize:index.vocabulary.length,nonzeroWeights,sparsePairPayloadBytes:nonzeroWeights*12},limitations:['All reference facts describe a fictional manual; they are not real equipment specifications.','This is TF–IDF retrieval plus deterministic sentence selection, not a language model or a benchmark of general question answering.','Index fitting uses documents; threshold calibration uses only tuning queries. Repeatedly choosing settings after seeing held-out results makes those queries development feedback.','A citation can exactly support a copied sentence while that sentence answers the wrong entity or attribute. Such a response fails task correctness even with sourceSupportAmongAnswers = 1.','Exact support checks establish agreement with this closed corpus and fact schema, not truth in the world or semantic support for arbitrary generated prose.','The slot parser chooses the first named entity and narrow keywords. It deliberately does not solve negation, reference, paraphrase or competing entities.','Quality, abstention and hypothetical latency/payload estimates have separate denominators and assumptions. No vendor timing or broad capability claim is made.'],sourceIds:['stanford-tfidf','stanford-query-vectors','sklearn-leakage']};
}
export type RetrievalApplicationResult=ReturnType<typeof runRetrievalApplication>;
export type RetrievalTrace=ReturnType<typeof retrieveAndAnswer>;
