/** Authored navigation, not a chapter-band classifier or a progress store. */
export const studioLessonMapVersion = 1;
export const studioIds = ['fabrication','memory','architecture','realization','hall','applications','orbital','progress','foundations','learning','automation','machine','reliability','control','commissioning','retrieval','families','distributed','evaluation','decisions','cell','serving','data','factory','memory-workload','ranking','network','projection'] as const;
export type StudioId = typeof studioIds[number];
export type StudioLessonLink = Readonly<{lessonId:string;label:string;reason:string}>;
export type StudioExperienceGuide = Readonly<{
  id:StudioId;
  title:string;
  summary:string;
  entryLabel:string;
  /** Ordered reading destinations; these need not all recommend launching this experience. */
  lessonLinks:readonly StudioLessonLink[];
  /** Explicit subset only: no reverse link is inferred from a band, keyword or outbound link. */
  entryLessonIds:readonly string[];
}>;
export type LessonStudioEntry = Readonly<{experienceId:StudioId;label:string;reason:string}>;

export const studioExperienceGuides:Readonly<Record<StudioId,StudioExperienceGuide>> = {
  fabrication:{
    id:'fabrication',title:'Fabrication → acceptance',
    summary:'Keep one specimen in view through growth, deposition, resist and etch, then distinguish measurement, screened supply and acceptance.',
    entryLabel:'Trace fabrication and acceptance',
    lessonLinks:[
      {lessonId:'silicon-wafer',label:'Start with a wafer and die population',reason:'Locate the selected specimen within a declared wafer population.'},
      {lessonId:'thermal-oxidation-interface',label:'Growth and the original silicon surface',reason:'Compare added oxide with silicon consumed across the original surface.'},
      {lessonId:'cvd-pvd-film-transport',label:'A deposited film is a separate layer',reason:'Inspect added target-film thickness; deposition transport and chamber kinetics remain outside the example.'},
      {lessonId:'resist-track-development',label:'Exposure and development change different states',reason:'Follow continuous resist, latent solubility and the developed opening before target removal.'},
      {lessonId:'plasma-wet-etch-transfer',label:'Etch consumes target, mask and stop material',reason:'Change mask thickness or selectivity and account for the prescribed etch exposure.'},
      {lessonId:'fab-metrology-process-window',label:'Uncertainty and the acceptance decision',reason:'Change uncertainty without changing the material geometry and inspect pass, review and fail.'},
      {lessonId:'yield-wafer-defect-model',label:'From a wafer population to screened inputs',reason:'Separate cohort acceptance from the independent defect assumption and conserve the die denominator.'},
      {lessonId:'hbm-bonding-process-selection',label:'Separate package-interface evidence',reason:'Compare the illustrated interface geometry and independent alignment, electrical and mechanical readings.'},
      {lessonId:'memory-system-qualification',label:'Acceptance needs scoped evidence',reason:'Withhold qualification evidence while keeping the supply and geometry fixed.'},
      {lessonId:'known-good-die-test',label:'What known-good-die testing adds',reason:'Continue beyond the illustrative screening policy to test access, binning and evidence that this flow does not simulate.'},
    ],
    entryLessonIds:['silicon-wafer','thermal-oxidation-interface','cvd-pvd-film-transport','resist-track-development','plasma-wet-etch-transfer','fab-metrology-process-window','yield-wafer-defect-model','hbm-bonding-process-selection','memory-system-qualification'],
  },
  memory:{
    id:'memory',title:'Bit → memory system',
    summary:'Read a declared bank address, inspect its die and stack, and place weights, mutable KV and staging across memory tiers.',
    entryLabel:'Trace a bit through the memory system',
    lessonLinks:[
      {lessonId:'dram-cell-array-fabrication',label:'A bit in an addressed array',reason:'Compose a bit address through a synthetic array hierarchy; cell electrostatics and fabrication are not simulated.'},
      {lessonId:'hbm-channel-generation-ras',label:'Bank state changes the next read',reason:'Distinguish activation, a row hit and a row conflict in independent stacks; timing, refresh and ECC remain outside the command model.'},
      {lessonId:'hbm-base-phy-controller',label:'Array, stack interface and base',reason:'Locate an addressed die within the stack path; the diagram does not supply a vendor channel floorplan or PHY waveform.'},
      {lessonId:'hbm-stack-height-budget',label:'Count the layers and their height',reason:'Change die count and bonding route to inspect the same stack height, capacity and interface count.'},
      {lessonId:'hbm-stack-thermal-yield',label:'Height, heat and conditional stack output',reason:'Follow the shared layer geometry into temperatures, limits and the conditional good-stack boundary.'},
      {lessonId:'memory-working-set-placement',label:'Place weights, KV and staging separately',reason:'Change context, batch and weight precision, then inspect persistent residency and transient headroom.'},
      {lessonId:'hbf-read-tier-contract',label:'A read-only tier has a specific job',reason:'Place immutable weights in HBF while mutable KV and staging retain separate constraints.'},
      {lessonId:'memory-system-qualification',label:'Geometry and qualification are different evidence',reason:'Inspect the declared evidence gates without converting geometric overlap into invented yield or reliability.'},
      {lessonId:'memory-to-hall-propagation',label:'Continue from placement to system consequences',reason:'Follow the lesson into network, power and cooling boundaries beyond the stack view.'},
    ],
    entryLessonIds:['dram-cell-array-fabrication','hbm-channel-generation-ras','hbm-base-phy-controller','hbm-stack-height-budget','hbm-stack-thermal-yield','memory-working-set-placement','hbf-read-tier-contract','memory-system-qualification'],
  },
  architecture:{
    id:'architecture',title:'Operation → architecture',
    summary:'Compute one exact matrix product through scalar, vector, SIMT and systolic schedules and inspect operand reuse and transfers.',
    entryLabel:'Execute one operation four ways',
    lessonLinks:[
      {lessonId:'mac',label:'Inspect each multiply–accumulate',reason:'Follow operands and the exact before-and-after partial sum for every operation.'},
      {lessonId:'cpu-vector-matrix',label:'Scalar and vector organizations',reason:'Compare scalar work with vector groups and explicit work remapping when a slot is excluded.'},
      {lessonId:'simt-active-lanes',label:'SIMT work and active slots',reason:'Inspect active, excluded and edge slots; this teaching scheduler does not simulate real warp divergence or measured occupancy.'},
      {lessonId:'systolic-array-dataflow',label:'A wavefront carries operands to its neighbors',reason:'Trace arrival ticks, local reuse, fill, drain and edge tiles on a two- or three-wide array.'},
      {lessonId:'kernel-locality-fusion',label:'Reuse changes traffic at a declared boundary',reason:'Compare logical operand reads and neighbor hops; actual cache transactions and fusion are further topics in the lesson.'},
      {lessonId:'sharded-matmul-ownership',label:'Reconstruct a product across ranks',reason:'Extend the exact local product into partial-sum ownership, reduce-scatter and all-gather in a worked distributed example.'},
      {lessonId:'floating-point-reduction-order',label:'When algebraic equality is not bitwise equality',reason:'Inspect a binary32 reduction-order counterexample beyond the exact-integer arithmetic used in this experience.'},
      {lessonId:'chip-workload-contract',label:'Keep the operation contract explicit',reason:'Preserve C = AB while changing its execution organization; hardware speed and power are not inferred.'},
    ],
    entryLessonIds:['mac','cpu-vector-matrix','simt-active-lanes','systolic-array-dataflow','kernel-locality-fusion','chip-workload-contract'],
  },
  realization:{
    id:'realization',title:'RTL → physical artifact',
    summary:'Execute a verified small adder netlist, follow its register edges, and inspect the exported FPGA placement, routes and timing evidence.',
    entryLabel:'Inspect an adder from RTL to placed hardware',
    lessonLinks:[
      {lessonId:'adder',label:'Preserve the carry bit',reason:'Execute every four-bit input pair through an adder with a five-bit output.'},
      {lessonId:'flipflop',label:'State advances at register edges',reason:'Inspect simultaneous register updates and distinguish initial inspection fill from a hardware reset.'},
      {lessonId:'chip-rtl-verification',label:'Check the arithmetic contract',reason:'Connect authored RTL, formal evidence and independent simulation to the exported mapped netlist.'},
      {lessonId:'fpga-dsp-pipelines',label:'Inspect FPGA logic and register resources',reason:'Locate the actual LUT/register implementation and routed resources; this example does not use or model DSP blocks.'},
      {lessonId:'chip-physical-closure',label:'Placement, routing and timing have evidence',reason:'Inspect a routed FPGA and tool timing model; ASIC PDK closure and measured board timing remain outside the artifact.'},
      {lessonId:'chip-tapeout-productization',label:'What a placed artifact does not establish',reason:'Continue to bring-up and productization evidence that a verified FPGA adder alone cannot supply.'},
    ],
    entryLessonIds:['adder','flipflop','chip-rtl-verification','fpga-dsp-pipelines','chip-physical-closure'],
  },
  hall:{
    id:'hall',title:'Rack → retained work',
    summary:'Admit racks against electrical and cooling limits, dispatch after readiness, and follow one workload through checkpoints, faults and recovery.',
    entryLabel:'Trace rack service into retained work',
    lessonLinks:[
      {lessonId:'rack-power-conversion',label:'Power and current cross voltage boundaries',reason:'Keep package DC rails, rack DC input, conversion loss and facility power distinct.'},
      {lessonId:'coolant-loop-separation',label:'Heat removal needs flow and temperature rise',reason:'Close the ideal aggregate water heat balance for admitted IT power.'},
      {lessonId:'water-boundary-accounting',label:'Circulating flow is not water consumption',reason:'Change recirculating kg/s and inspect heat and temperature rise without claiming a consumptive water-use rate.'},
      {lessonId:'cluster-commissioning-gates',label:'Installed capacity still needs readiness',reason:'Delay or withhold the operations gate and account for the time before job dispatch.'},
      {lessonId:'checkpoint-retained-work',label:'Completed, retained and durable are different counts',reason:'Inspect atomic commitment, rollback, restore traffic and the checkpoint interval tradeoff.'},
      {lessonId:'retained-work-restart-boundary',label:'Check the work ledger at the restart boundary',reason:'Account for durable steps, volatile completed steps, unfinished work and discarded work at one observation horizon.'},
      {lessonId:'checkpoint',label:'A restart begins from committed state',reason:'Follow the most recent valid checkpoint through a prescribed fault and recovery pause.'},
      {lessonId:'storage-input-checkpoint-path',label:'Checkpoint bytes take time to write and restore',reason:'Separate checkpoint write/read traffic from the fixed workload memory and network paths.'},
      {lessonId:'facility-heat-rejection',label:'Continue beyond the ideal hall heat boundary',reason:'Study cooling-plant and environmental limits that the aggregate water balance does not solve.'},
      {lessonId:'grid-interconnection-readiness',label:'A facility-input limit needs real evidence',reason:'Continue from the synthetic feed budget to interconnection and deliverable-capacity evidence.'},
    ],
    entryLessonIds:['rack-power-conversion','coolant-loop-separation','water-boundary-accounting','cluster-commissioning-gates','checkpoint-retained-work','retained-work-restart-boundary','checkpoint','storage-input-checkpoint-path'],
  },
  applications:{
    id:'applications',title:'Data → evaluated application',
    summary:'Inspect a trained sensor classifier and a deterministic cited-answer pipeline, then separate fitting, decision rules, source support and task correctness.',
    entryLabel:'Fit a model and test the application result',
    lessonLinks:[
      {lessonId:'training-data',label:'Training and evaluation data have different roles',reason:'Fit normalization and gradients on authored training cases, then challenge a broken correlation with separate evaluation cases.'},
      {lessonId:'loss-optimizer',label:'Inspect a complete gradient update',reason:'Follow the logistic loss, per-row contributions, regularization and simultaneous parameter update.'},
      {lessonId:'evaluation',label:'Score the task at the right boundary',reason:'Separate held-out prediction errors, citation support, task correctness and appropriate abstention.'},
      {lessonId:'distributed-gradient-weighting',label:'Weight unequal distributed batches correctly',reason:'Extend a local gradient into a sample-weighted distributed update; averaging rank means changes the objective when batch counts differ.'},
      {lessonId:'speculative-decoding-verification',label:'Verify a proposed token before accepting it',reason:'Follow draft and target distributions through corrected speculative sampling; this is a worked extension beyond the deterministic retrieval example.'},
      {lessonId:'tool-loop',label:'Check the result of a retrieval step',reason:'Inspect a deterministic lexical retrieval-and-selection pipeline; a supported source can still supply the wrong entity’s fact.'},
    ],
    entryLessonIds:['training-data','loss-optimizer','evaluation','tool-loop'],
  },
  orbital:{
    id:'orbital',title:'Workload → orbital budgets',
    summary:'Follow synthetic computed products through prescribed sunlight, battery storage, radiator limits, contacts, backlog and resets.',
    entryLabel:'Test a workload against orbital budgets',
    lessonLinks:[
      {lessonId:'orbital-solar-storage',label:'Bridge eclipse with stored energy',reason:'Close one bus-energy ledger across prescribed sunlight and eclipse while keeping battery losses and limits explicit.'},
      {lessonId:'orbital-radiator-budget',label:'Electrical supply also needs heat rejection',reason:'Inspect an isothermal radiator bound, environmental heat and battery losses; temperature transients are not modeled.'},
      {lessonId:'orbital-link-contacts',label:'Ground delivery needs data and contact time',reason:'Follow useful bytes, receiver partial progress and onboard buffer backpressure under prescribed contacts.'},
      {lessonId:'orbital-radiation-recovery',label:'Reset events and rate context are separate',reason:'Compare scripted recovery losses with an explicitly separate effective-flux/Poisson readout.'},
      {lessonId:'orbital-evidence-status',label:'A budget calculation is one kind of evidence',reason:'Continue to the evidence ladder; passing finite-horizon teaching checks does not establish a flight-ready mission.'},
      {lessonId:'orbital-lifecycle-economics',label:'Continue to lifecycle questions outside this model',reason:'Study workload fit and lifecycle costs after identifying the physical budgets; no mission economics are calculated here.'},
    ],
    entryLessonIds:['orbital-solar-storage','orbital-radiator-budget','orbital-link-contacts','orbital-radiation-recovery'],
  },
  progress:{
    id:'progress',title:'Breakthroughs → capacity',
    summary:'Connect selected historical mechanisms to small worked examples, then distinguish dated capacity evidence from synthetic allocation policies.',
    entryLabel:'Explore breakthroughs and finite-capacity allocation',
    lessonLinks:[
      {lessonId:'interconnect-rc-materials',label:'Wiring becomes a limiting mechanism',reason:'Compare a synthetic wire RC timescale with the historical material/process evidence; the calculation is not a historical measurement.'},
      {lessonId:'systolic-array-dataflow',label:'Organization changes where operands are reused',reason:'Continue from the small matrix example to exact teaching schedules while retaining the historical datapath boundary.'},
      {lessonId:'loss-optimizer',label:'Optimizer state adds a different kind of work',reason:'Inspect authored scalar Adam moments and bias correction without treating them as a training convergence result.'},
      {lessonId:'attention-io-tiling',label:'Online rescaling preserves the attention result',reason:'Follow a small softmax calculation, then continue to the wider IO-aware kernel mechanism.'},
      {lessonId:'kv-cache',label:'Live tokens and allocated slots differ',reason:'Compare synthetic fixed-size KV blocks with fixed reservations; token slots are not a measured byte or latency result.'},
      {lessonId:'compatible-supply-capacity',label:'A package requires every compatible input',reason:'Explore finite logic-die, HBM, assembly and test bounds, with dated public evidence kept separate from the synthetic inventory.'},
      {lessonId:'production-ramp-allocation',label:'Supply and allocation need dates and policies',reason:'Compare explicit shipment policies and their unmet requests without inferring private customer queues from public statements.'},
      {lessonId:'topology-job-admission',label:'Whole jobs encounter finite rack capacity',reason:'Inspect first-fit and strict-order whole-rack allocation; network topology and actual scheduler policy are not simulated.'},
    ],
    // The broad historical route has no per-step URL yet. Its existing in-view links handle
    // individual mechanisms; contextual entry is reserved for the finite-capacity exercise.
    entryLessonIds:['compatible-supply-capacity','production-ramp-allocation','topology-job-admission'],
  },
  foundations:{"id": "foundations", "title": "Numbers → learning mechanisms", "summary": "Compute matrices, stable probabilities, finite encodings and contrasting learned or authored decision mechanisms.", "entryLabel": "Open mathematical foundations", "lessonLinks": [{"lessonId": "tensor-index-contracts", "label": "Tensor shapes, indices and contractions", "reason": "Trace every scalar contribution into one output and detect an incorrect contraction axis."}, {"lessonId": "linear-map-rank-subspace", "label": "Linear maps, rank and retained directions", "reason": "Identify the direction lost by a rank-one approximation and distinguish rank from matrix size."}, {"lessonId": "probability-conditioning-information", "label": "Probability, likelihood and stable information", "reason": "Convert logits to a normalized distribution, calculate target loss and explain why a common offset should not change either."}, {"lessonId": "floating-number-range-resolution", "label": "Floating-point range, resolution and rounding", "reason": "Encode a value in a declared miniature format and diagnose rounding, gradual underflow and overflow."}, {"lessonId": "sampling-estimation-uncertainty", "label": "Sampling variability and independent evidence", "reason": "Reconcile an exact sampling distribution with its mean and variance, and identify when a claimed sample count is not independent."}, {"lessonId": "ablation-reproduction-design", "label": "Controlled comparisons and confounded improvement", "reason": "Separate a changed treatment from a changed population, and identify a comparison that lacks support in the observed data."}, {"lessonId": "dataset-human-judgment-lineage", "label": "Human judgments, disagreement and dataset lineage", "reason": "Preserve original judgments through an adjudication rule and distinguish label availability from truth."}, {"lessonId": "tree-ensemble-baseline", "label": "A tree ensemble that learns residual corrections", "reason": "Fit a sequence of regression stumps, inspect their contributions and evaluate both a reserved task and a changed relationship."}, {"lessonId": "graph-message-passing", "label": "Graph message passing and node identity", "reason": "Compute normalized neighborhood aggregation and distinguish an edge change from a harmless node renaming."}, {"lessonId": "search-value-policy-boundary", "label": "Search, value estimates and selected actions", "reason": "Trace legal game actions through a bounded alternating-player search and distinguish terminal evidence from a truncated heuristic."}], "entryLessonIds": ["tensor-index-contracts", "linear-map-rank-subspace", "probability-conditioning-information", "floating-number-range-resolution", "sampling-estimation-uncertainty", "ablation-reproduction-design", "dataset-human-judgment-lineage", "tree-ensemble-baseline", "graph-message-passing", "search-value-policy-boundary"]},
  learning:{"id": "learning", "title": "Corpus → trained model", "summary": "Follow a small causal decoder through actual updates, checkpoint continuation, supervised tuning, preferences and separate development/final evaluation.", "entryLabel": "Build and train a small language model", "lessonLinks": [{"lessonId": "training-data", "label": "Trace training and evaluation families", "reason": "Inspect authored family splits and masks before they contribute to the optimizer."}, {"lessonId": "attention", "label": "Differentiate a causal attention block", "reason": "Follow actual values and gradients through the declared small trainable decoder."}, {"lessonId": "loss-optimizer", "label": "Inspect a computed gradient and update", "reason": "Compare Adam or SGD with the same actual reverse-mode gradients and clipping boundary."}, {"lessonId": "checkpoint", "label": "Resume the same training experiment", "reason": "Preserve weights, optimizer, random state and sampling cursor in a validated portable checkpoint."}, {"lessonId": "post-training", "label": "Fork the model into changed objectives", "reason": "Contrast continuation, response-only supervised loss, DPO and a bounded two-action reward loop."}, {"lessonId": "evaluation", "label": "Keep development and final evidence distinct", "reason": "Inspect development repeatedly and explicitly open a separate final test after recipe selection."}], "entryLessonIds": ["training-data", "attention", "loss-optimizer", "checkpoint", "post-training", "evaluation"]},
  automation:{"id": "automation", "title": "Request \u2192 verified action", "summary": "Execute fictional tools, enforce authority and recover an action committed before its acknowledgment arrived.", "entryLabel": "Run a recoverable automation workflow", "lessonLinks": [{"lessonId": "tool-loop", "label": "A proposal becomes an authorized action", "reason": "Separate schema validity, semantic context, authority, side-effect commitment and observation."}, {"lessonId": "evaluation", "label": "Check the final environment independently", "reason": "Compare the workflow\u2019s reported completion with actual asset, reservation and work-order state."}, {"lessonId": "checkpoint", "label": "Model and workflow state have different semantics", "reason": "Contrast a saved computational checkpoint with an event journal and separately durable action receipt."}, {"lessonId": "manufacturing-execution-dispatch", "label": "Act on an identified fictional asset", "reason": "Retain asset and evidence identity through a simulated controlled maintenance workflow."}, {"lessonId": "workflow-graphs-state", "label": "Run declared workflow transitions", "reason": "Inspect the same fictional incident under two authored policies and independently check its final state."}, {"lessonId": "durable-actions-idempotency", "label": "Reconcile a committed write after response loss", "reason": "Exercise keyed reservation receipts, retries, duplicate delivery and durable recovery."}, {"lessonId": "tool-contracts-schemas", "label": "Validate an actual typed action", "reason": "Submit schema failures to the local runtime and inspect their explicit rejection."}, {"lessonId": "tool-authority-identity", "label": "Enforce the declared action capability", "reason": "Compare a proposed action with the fictional principal, asset and allowed operation."}, {"lessonId": "untrusted-content-boundary", "label": "Test a malicious reference document", "reason": "Keep retrieved instructions from expanding authority while still validating permitted proposed actions."}, {"lessonId": "human-review-cancellation", "label": "Review or cancel a pending action", "reason": "Approve exact simulated actions and distinguish cancellation before and after commitment."}, {"lessonId": "telemetry-traces-evaluation", "label": "Read events and verify the final task", "reason": "Attribute transport, validation and task failures using the actual event journal and environment oracle."}], "entryLessonIds": ["tool-loop", "evaluation", "workflow-graphs-state", "durable-actions-idempotency", "tool-contracts-schemas", "tool-authority-identity", "untrusted-content-boundary", "human-review-cancellation", "telemetry-traces-evaluation"]},
  machine:{"id": "machine", "title": "Operation → timed memory", "summary": "Follow a declared matrix operation through lane addresses, shared banks, DMA mappings and legal timed DRAM commands.", "entryLabel": "Trace operations into memory events", "lessonLinks": [{"lessonId": "kernel-locality-fusion", "label": "Layout changes the required transactions", "reason": "Compare actual teaching address groups and bytes while preserving the exact matrix result."}, {"lessonId": "shared-sram", "label": "Inspect shared-bank accesses and broadcasts", "reason": "Follow each lane’s address into distinct words, bank service rounds and buffer ownership."}, {"lessonId": "hbm-controller", "label": "A read needs a legal command sequence", "reason": "Inspect ACT, PRE, read, write and refresh timing under explicit synthetic command constraints."}, {"lessonId": "gpu-occupancy-pipeline", "label": "Completion governs safe buffer reuse", "reason": "Track when copied operands are available and diagnose early consumption or in-flight reuse."}, {"lessonId": "pcie-interface", "label": "Map device addresses to a permitted buffer", "reason": "Inspect a declared IOVA-to-physical mapping and a failed unmapped operand access; this is not a PCIe packet simulation."}], "entryLessonIds": ["kernel-locality-fusion", "shared-sram", "hbm-controller", "gpu-occupancy-pipeline"]},
  reliability:{"title": "State \u2192 reliable work", "summary": "Trace tagged FIFO ownership across ideal clock domains, then decode damaged SECDED words and recover a checked consumer.", "entryLabel": "Inspect clock crossing and ECC recovery", "lessonLinks": [{"lessonId": "chip-rtl-verification", "label": "Check a tagged FIFO contract", "reason": "Follow accepted and consumed tags, ideal synchronizer delay and a deliberately failed reset contract."}, {"lessonId": "clock", "label": "Separate write and read clock edges", "reason": "Inspect two Gray pointer synchronizer stages; this exact state model does not simulate analog metastability."}, {"lessonId": "hbm-channel-generation-ras", "label": "Decode a damaged extended Hamming word", "reason": "Test single-bit correction, double-bit detection and an out-of-guarantee triple-bit miscorrection."}, {"lessonId": "retained-work-restart-boundary", "label": "Recover a consumer from a trusted checkpoint", "reason": "Reconcile computed, discarded and retained steps after detected corruption and a healthy replacement word."}], "entryLessonIds": ["chip-rtl-verification", "clock", "hbm-channel-generation-ras", "retained-work-restart-boundary"], "id": "reliability"},
  control:{"title": "Observation \u2192 controlled action", "summary": "Fit a small plant model, plan actions from delayed observations and evaluate the resulting 12-second episode.", "entryLabel": "Close a simulated sensor-to-action loop", "lessonLinks": [{"lessonId": "robot-feedback-control", "label": "Compare a learned model and feedback baseline", "reason": "Fit two dynamics parameters, enumerate constrained action sequences and measure actual simulated motion."}, {"lessonId": "robot-observation-frame", "label": "Separate sensed and true physical state", "reason": "Inspect noisy delayed position measurements and a stated finite-difference velocity estimator."}, {"lessonId": "robot-goal-plan-action", "label": "Inspect candidate futures before applying one action", "reason": "Compare feasible predicted paths with actual outcomes when the model, observation or deadline changes."}, {"lessonId": "embodied-policy-evidence", "label": "Keep calibration and episode evidence distinct", "reason": "A fitted nominal plant and a separate simulated episode supply different evidence; neither is a physical device trial."}], "entryLessonIds": ["robot-feedback-control", "robot-observation-frame", "robot-goal-plan-action"], "id": "control"},
  commissioning:{"title": "Boot \u2192 owned device work", "summary": "Follow a declared device contract, address mapping, cache visibility and completion through the same matrix operation.", "entryLabel": "Trace device setup, ownership and completion", "lessonLinks": [{"lessonId": "firmware-device-contract", "label": "Check the device before submitting work", "reason": "Follow a declared ABI and resource-readiness contract; this is not real firmware or cryptographic verification."}, {"lessonId": "process-dma-address-spaces", "label": "Inspect virtual, physical and device-visible addresses", "reason": "Trace the same A, B and C buffers through distinct address spaces in a bounded teaching device."}, {"lessonId": "iommu-buffer-identity", "label": "Separate permission from correct object identity", "reason": "Compare an unmapped address with a permitted address pointing to the wrong matrix."}, {"lessonId": "dma-visibility-ownership", "label": "Make memory visibility explicit", "reason": "Observe stale data if a noncoherent CPU/device cache boundary is not synchronized."}, {"lessonId": "device-completion-reset-epochs", "label": "Reject old completion after device reset", "reason": "Cancel partial output and retry under a new epoch while reconciling discarded and committed MACs."}], "entryLessonIds": ["firmware-device-contract", "process-dma-address-spaces", "iommu-buffer-identity", "dma-visibility-ownership", "device-completion-reset-epochs"], "id": "commissioning"},
  retrieval:{"title": "Learned retrieval \u2192 generated proposal", "summary": "Fit embeddings and a conditional token decoder, inspect the retrieved evidence and hand a frozen proposal to the durable runtime.", "entryLabel": "Train retrieval and inspect a generated proposal", "lessonLinks": [{"lessonId": "retrieval-indexing-evaluation", "label": "Fit and test a small learned retrieval index", "reason": "Inspect actual mean-pooled token embeddings and scores against a lexical baseline on a fictional corpus."}, {"lessonId": "retrieval-supported-generation", "label": "Generate from identified retrieved evidence", "reason": "Inspect a fitted token decoder, its context, token probabilities and separate task and support checks."}, {"lessonId": "embedding", "label": "Inspect learned retrieval vectors", "reason": "Follow updates to the small token embedding table and compare resulting passage scores."}, {"lessonId": "workflow-graphs-state", "label": "Carry a model proposal into the runtime", "reason": "Freeze the fitted model and generated proposal before applying the existing validation, authority and review boundary."}], "entryLessonIds": ["retrieval-indexing-evaluation", "retrieval-supported-generation", "embedding"], "id": "retrieval"},
  families:{"title": "Contrasting AI mechanisms", "summary": "Compute conditional expert routes, recurrent states, spatial filters, signal spectra and a learned denoising process.", "entryLabel": "Explore contrasting computational structures", "lessonLinks": [{"lessonId": "moe", "label": "Route to fitted experts under a capacity limit", "reason": "Separate fitted expert functions from an authored gate and count rejected outputs as well as accepted error."}, {"lessonId": "denoising-generative-objectives", "label": "Learn a scalar noise predictor and sample backward", "reason": "Follow actual noisy examples, nearest-neighbor predictions and a declared twelve-step reverse process."}, {"lessonId": "audio-sampling-spectrum", "label": "Inspect a sampled-signal front end", "reason": "Compute windowed tone samples and their DFT; this prerequisite does not recognize speech."}, {"lessonId": "spatial-filter-patch-attention", "label": "Contrast local filters and patch aggregation", "reason": "Compute authored image filters and one identity-projection attention query; this is not a trained visual-language model."}, {"lessonId": "scalar-state-space-recurrence", "label": "Unroll persistent state into a convolution", "reason": "Compare every recurrent state with an independent convolution and inspect a reset boundary."}], "entryLessonIds": ["moe", "denoising-generative-objectives", "scalar-state-space-recurrence", "spatial-filter-patch-attention", "audio-sampling-spectrum"], "id": "families"},
  distributed:{"id": "distributed", "title": "Examples \u2192 distributed update", "summary": "Compute actual gradients on unequal rank batches and commit one globally weighted optimizer update after the barrier.", "entryLabel": "Run a distributed training round", "lessonLinks": [{"lessonId": "parallelism", "label": "Partition four actual examples", "reason": "Split a named batch across two or three simulated ranks while retaining example and target counts."}, {"lessonId": "nccl", "label": "Reduce gradients with the right denominator", "reason": "Compare a token- or sample-weighted reduction with the centralized objective and a deliberately incorrect equal-rank mean."}, {"lessonId": "checkpoint", "label": "Preserve the optimizer and data cursor", "reason": "A portable round keeps the source model, moments, reserved examples, rank attempts and commit boundary."}, {"lessonId": "training-data", "label": "Count targets before averaging", "reason": "Unequal sequence lengths create unequal rank denominators even before a rank fails."}], "entryLessonIds": ["parallelism", "nccl"]},
  evaluation:{"id": "evaluation", "title": "Evaluate an identified system", "summary": "Inspect a fitted classifier, separate calibration, family overlap, score denominators and abstention.", "entryLabel": "Audit probabilities and decisions", "lessonLinks": [{"lessonId": "probability-calibration-abstention", "label": "Calibrate a frozen prediction", "reason": "Select temperature using a separate cohort and report conditional error alongside acceptance coverage."}, {"lessonId": "evaluation", "label": "Read each metric\u2019s denominator", "reason": "Reproduce the same audit rows, probabilities, decisions and source-family checks."}, {"lessonId": "model-artifact-rollout-drift", "label": "Identify the complete fitted artifact", "reason": "Bind coefficients, preprocessing, feature order and calibration to the result."}, {"lessonId": "data-quality-dedup-audit", "label": "Detect a renamed family copy", "reason": "Keep source-family identity across a changed sample ID and report the overlap."}], "entryLessonIds": ["probability-calibration-abstention", "evaluation"]},
  decisions:{"id": "decisions", "title": "Forecasts & code contracts", "summary": "Execute forward-time regression and bounded code tests against explicit task contracts.", "entryLabel": "Test an application\u2019s evidence boundary", "lessonLinks": [{"lessonId": "temporal-forecast-validation", "label": "Forecast only from available information", "reason": "Fit earlier hours and compare rolling multi-step predictions against persistence on the same target rows."}, {"lessonId": "coding-agent-patch-evidence", "label": "Execute a patch against the stated contract", "reason": "Distinguish two passing examples from boundary tests and an independently enumerated finite oracle."}, {"lessonId": "scientific-surrogate-validation", "label": "Separate fitted agreement from physical validity", "reason": "Use the forecast as a bounded fitted function; a scientific surrogate additionally needs its stated physical domain and validation evidence."}, {"lessonId": "evaluation", "label": "Interpret a result through its test boundary", "reason": "Follow the same specimen identity into denominator, baseline and failure interpretation."}], "entryLessonIds": ["temporal-forecast-validation", "coding-agent-patch-evidence"]},
  cell:{"id": "cell", "title": "Oxide \u2192 electrical acceptance", "summary": "Carry one synthetic inverter through coupled oxide, capacitance, current, logic and timing checks.", "entryLabel": "Inspect a process-to-cell electrical bridge", "lessonLinks": [{"lessonId": "oxide-to-cell-acceptance", "label": "Carry oxide variation into electrical behavior", "reason": "Evaluate the same oxide thickness in capacitance, threshold, current and declared acceptance gates."}, {"lessonId": "loaded-inverter-transition", "label": "Integrate a loaded switching transition", "reason": "Follow the model current through capacitance to actual analytic transition time and a timing gate."}, {"lessonId": "mosfet", "label": "Read the long-channel current assumptions", "reason": "Distinguish the evaluated long-channel square-law specimen from nanoscale devices and foundry qualification."}, {"lessonId": "inverter", "label": "Connect voltage transfer and logic margins", "reason": "Compare the static switching boundary and noise margins with the separate loaded transient."}], "entryLessonIds": ["oxide-to-cell-acceptance", "loaded-inverter-transition"]},
 serving:{"id": "serving", "title": "Checkpoint \u2192 serving queue", "summary": "Generate actual tokens from a learned checkpoint while preserving KV ownership, admission and release events.", "entryLabel": "Serve a learned decoder checkpoint", "lessonLinks": [{"lessonId": "serving", "label": "Admit requests into a finite decoder service", "reason": "Carry the same model into request arrival, admission, logical batching and explicit completion."}, {"lessonId": "kv-cache", "label": "Inspect the keys and values that are reused", "reason": "Compare actual incremental cache computations with a full-prefix reference."}, {"lessonId": "output-head", "label": "Generate and inspect actual token probabilities", "reason": "Preserve each request\u2019s random state and decode from its identified weights."}, {"lessonId": "scheduler", "label": "Follow reserved capacity and request lifetimes", "reason": "Separate queue waiting, active state, canceled work and released cache positions."}, {"lessonId": "checkpoint", "label": "Keep learning state separate from serving state", "reason": "Import the full source checkpoint or distributed committed state without changing trained parameters."}], "entryLessonIds": ["serving", "kv-cache", "output-head", "scheduler"]},
 data:{"id": "data", "title": "Source corpus → training batch", "summary": "Track source families, fit byte-pair merges on training fields and reconstruct sampled, masked batches.", "entryLabel": "Inspect corpus lineage and packed tokens", "lessonLinks": [{"lessonId": "training-data", "label": "Follow source families into separate splits", "reason": "Preserve original family identity while contrasting family and individual-document splits."}, {"lessonId": "data-quality-dedup-audit", "label": "Find duplicates before interpreting evaluation", "reason": "Inspect exact, normalized and near matches while preserving the original source IDs."}, {"lessonId": "tokenizer", "label": "Fit and apply a byte-pair vocabulary", "reason": "Learn adjacent byte merges only on retained training fields and inspect the exact merge order."}, {"lessonId": "sequence-packing-loss-denominators", "label": "Build a reproducible masked token batch", "reason": "Use the identified sampler cursor, shifted targets and isolated causal sequence boundaries."}, {"lessonId": "loss-optimizer", "label": "Count the targets the objective actually sees", "reason": "Response masks change the training denominator while retaining causal prompt context."}], "entryLessonIds": ["training-data", "data-quality-dedup-audit", "tokenizer", "sequence-packing-loss-denominators"]},
 factory:{"id": "factory", "title": "Learned state → reliable factory job", "summary": "Carry an actual decoder checkpoint through commissioning, resource admission, distributed updates and durable recovery.", "entryLabel": "Run an identified factory job", "lessonLinks": [{"lessonId": "cluster-commissioning-gates", "label": "Require correct device work before admission", "reason": "Check the actual matrix commissioning trace as well as separate feed and cooling limits."}, {"lessonId": "checkpoint-retained-work", "label": "Keep an actual durable model checkpoint", "reason": "Compare executed, rolled-back and retained optimizer updates using the same weights, moments and random state."}, {"lessonId": "storage-input-checkpoint-path", "label": "Commit complete bytes before calling work durable", "reason": "Serialize the full training record, stop an incomplete checkpoint and restore only a fully committed artifact."}, {"lessonId": "parallelism-communication-budget", "label": "Trace rank completion and network ownership", "reason": "Separate actual gradient computation from explicitly assumed rank durations and network service rates."}, {"lessonId": "retained-work-restart-boundary", "label": "Compare recovered state with a failure-free reference", "reason": "Check parameter, optimizer, random-state and data-cursor equivalence after recovery."}], "entryLessonIds": ["cluster-commissioning-gates", "checkpoint-retained-work", "storage-input-checkpoint-path", "retained-work-restart-boundary"]},
 "memory-workload":{"id": "memory-workload", "title": "Memory qualification → checked workload", "summary": "Carry identified matrix words through interface admission, staging, actual DRAM events, correction and independently checked output.", "entryLabel": "Follow memory bytes into checked arithmetic", "lessonLinks": [{"lessonId": "memory-system-qualification", "label": "Require separate package and interface evidence", "reason": "Compare the actual declared stack/interface gate with a separately injected byte fault; geometry does not invent an error rate."}, {"lessonId": "memory-working-set-placement", "label": "Place and stage the same identified matrix bytes", "reason": "Move read-only B data from an authored host/read tier into the destination allocation before issuing machine reads."}, {"lessonId": "hbm-controller", "label": "Follow the selected operation through memory events", "reason": "Trace physical word identity through the teaching DRAM schedule without equating its two-bank map to a vendor HBM hierarchy."}, {"lessonId": "hbm-channel-generation-ras", "label": "Correct or reject data before consuming it", "reason": "Apply explicit nibble-wise SECDED to 32-bit words and observe correction, blocked reads and out-of-guarantee wrong output."}, {"lessonId": "mac", "label": "Check the arithmetic after the data arrives", "reason": "Replay actual DMA-read and MAC events and compare the resulting matrix with the independent dense contract."}], "entryLessonIds": ["memory-system-qualification", "memory-working-set-placement", "hbm-controller", "hbm-channel-generation-ras"]},
 ranking:{"id": "ranking", "title": "Exposure → fitted ranking", "summary": "Fit a scorer on observed feedback and compare known-propensity weighting with popularity and held-out usefulness.", "entryLabel": "Inspect exposure, feedback and ranking", "lessonLinks": [{"lessonId": "recommendation-ranking-feedback", "label": "Separate exposure, clicks and usefulness", "reason": "Track an authored exposure log, fitted score and independently specified usefulness gains."}, {"lessonId": "training-data", "label": "Know which feedback is actually observed", "reason": "Missing feedback supplies no training label; zero exposure leaves outcomes unidentified."}, {"lessonId": "loss-optimizer", "label": "Inspect the weighted fitting objective", "reason": "Compare observed-only logistic gradients with known inverse-propensity weighting."}, {"lessonId": "evaluation", "label": "Score disjoint users with explicit denominators", "reason": "Compare per-user NDCG and recall with a popularity baseline without promising finite-sample improvement."}], "entryLessonIds": ["recommendation-ranking-feedback"]},
 network:{"id": "network", "title": "Matrix bytes → network completion", "summary": "Trace the actual selected matrix bytes through finite credits, delivery, assembly and checked consumer work.", "entryLabel": "Follow matrix bytes through a finite link", "lessonLinks": [{"lessonId": "network-adapter", "label": "Preserve operand bytes across an endpoint boundary", "reason": "Serialize the same signed matrix words, identify segments and assemble accepted destination bytes."}, {"lessonId": "leaf-switch", "label": "Observe finite queue capacity and backpressure", "reason": "Track outstanding credits and receiver service in a declared single-link teaching boundary, not a vendor switch."}, {"lessonId": "parallelism-communication-budget", "label": "Keep transport completion separate from useful work", "reason": "Count sent, received, rejected and missing data before allowing the selected arithmetic to consume it."}, {"lessonId": "mac", "label": "Compute from the received operand", "reason": "Compare actual consumer results with an independent original-matrix reference after transport interventions."}], "entryLessonIds": ["network-adapter", "leaf-switch"]},
 projection:{"id": "projection", "title": "Learned projection → machine trace", "summary": "Carry a real decoder query projection through an explicit tiled precision adapter into actual machine events.", "entryLabel": "Trace a learned projection through machine work", "lessonLinks": [{"lessonId": "tiny-causal-decoder", "label": "Select an operator from identified learned weights", "reason": "Extract the actual normalized input and query projection from a full checkpoint without changing its training state."}, {"lessonId": "tensor-index-contracts", "label": "Preserve dimensions through the selected projection", "reason": "Execute the full six-channel inner reduction as two three-by-three tiles with an explicit output slice."}, {"lessonId": "quantization", "label": "Measure error at the precision boundary", "reason": "Record symmetric integer scales and compare reconstructed output with the actual binary64 query slice."}, {"lessonId": "tensor-memory-accelerator", "label": "Move and consume the quantized tile bytes", "reason": "Follow real buffer ownership, DRAM commands and partial sums through the bounded machine implementation."}, {"lessonId": "attention", "label": "Continue from query projection to causal attention", "reason": "Locate the selected linear operator within attention while keeping masks and omitted operators explicit."}], "entryLessonIds": ["tiny-causal-decoder", "tensor-index-contracts", "quantization"]},
};

/** Ordered contextual reading. The caller supplies navigation/focus behavior. */
export function lessonsForStudio(id:StudioId):readonly StudioLessonLink[]{
  return studioExperienceGuides[id].lessonLinks;
}

/** Unknown or unrelated lessons deliberately have no contextual launch action. */
export function studiosForLesson(lessonId:string):readonly LessonStudioEntry[]{
  return studioIds.flatMap(id=>{
    const guide=studioExperienceGuides[id];
    if(!guide.entryLessonIds.includes(lessonId))return [];
    return [{experienceId:id,label:guide.entryLabel,reason:guide.lessonLinks.find(link=>link.lessonId===lessonId)!.reason}];
  });
}

/** Every experience has one desktop and mobile navigation home. */
export const studioGroups=[
 {name:"Foundations & learning",ids:["foundations","data","learning","distributed","serving","families"]},
 {name:"Applications & action",ids:["decisions","ranking","evaluation","applications","retrieval","automation","control"]},
 {name:"Silicon & hardware",ids:["cell","fabrication","realization","memory","memory-workload","architecture","machine","network","projection","reliability","commissioning"]},
 {name:"Infrastructure & progress",ids:["factory","hall","orbital","progress"]},
] as const satisfies readonly {name:string;ids:readonly StudioId[]}[];
