/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module atlas_adder(clk, a, b, q);
  input clk;
  wire clk;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [4:0] q;
  wire [4:0] q;
  wire [3:0] a_sampled;
  wire [3:0] \arithmetic.a ;
  wire [3:0] \arithmetic.b ;
  wire [4:0] \arithmetic.carry ;
  wire [4:0] \arithmetic.sum ;
  wire [3:0] b_sampled;
  wire q_SB_DFF_Q_1_D;
  wire [2:0] q_SB_DFF_Q_1_D_SB_LUT4_O_I3;
  wire q_SB_DFF_Q_2_D;
  wire q_SB_DFF_Q_3_D;
  wire q_SB_DFF_Q_4_D;
  wire q_SB_DFF_Q_D;
  wire [2:0] q_SB_DFF_Q_D_SB_LUT4_O_I3;
  wire [4:0] sum;
  SB_DFF a_sampled_SB_DFF_Q (
    .C(clk),
    .D(a[3]),
    .Q(a_sampled[3])
  );
  SB_DFF a_sampled_SB_DFF_Q_1 (
    .C(clk),
    .D(a[2]),
    .Q(a_sampled[2])
  );
  SB_DFF a_sampled_SB_DFF_Q_2 (
    .C(clk),
    .D(a[1]),
    .Q(a_sampled[1])
  );
  SB_DFF a_sampled_SB_DFF_Q_3 (
    .C(clk),
    .D(a[0]),
    .Q(a_sampled[0])
  );
  SB_DFF b_sampled_SB_DFF_Q (
    .C(clk),
    .D(b[0]),
    .Q(b_sampled[0])
  );
  SB_DFF b_sampled_SB_DFF_Q_1 (
    .C(clk),
    .D(b[1]),
    .Q(b_sampled[1])
  );
  SB_DFF b_sampled_SB_DFF_Q_2 (
    .C(clk),
    .D(b[3]),
    .Q(b_sampled[3])
  );
  SB_DFF b_sampled_SB_DFF_Q_3 (
    .C(clk),
    .D(b[2]),
    .Q(b_sampled[2])
  );
  SB_DFF q_SB_DFF_Q (
    .C(clk),
    .D(q_SB_DFF_Q_D),
    .Q(q[3])
  );
  SB_DFF q_SB_DFF_Q_1 (
    .C(clk),
    .D(q_SB_DFF_Q_1_D),
    .Q(q[2])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h3cc3)
  ) q_SB_DFF_Q_1_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(a_sampled[2]),
    .I2(b_sampled[2]),
    .I3(q_SB_DFF_Q_1_D_SB_LUT4_O_I3[2]),
    .O(q_SB_DFF_Q_1_D)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h175f)
  ) q_SB_DFF_Q_1_D_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(a_sampled[1]),
    .I1(a_sampled[0]),
    .I2(b_sampled[1]),
    .I3(b_sampled[0]),
    .O(q_SB_DFF_Q_1_D_SB_LUT4_O_I3[2])
  );
  SB_DFF q_SB_DFF_Q_2 (
    .C(clk),
    .D(q_SB_DFF_Q_2_D),
    .Q(q[1])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h965a)
  ) q_SB_DFF_Q_2_D_SB_LUT4_O (
    .I0(a_sampled[1]),
    .I1(a_sampled[0]),
    .I2(b_sampled[1]),
    .I3(b_sampled[0]),
    .O(q_SB_DFF_Q_2_D)
  );
  SB_DFF q_SB_DFF_Q_3 (
    .C(clk),
    .D(q_SB_DFF_Q_3_D),
    .Q(q[0])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) q_SB_DFF_Q_3_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(a_sampled[0]),
    .I3(b_sampled[0]),
    .O(q_SB_DFF_Q_3_D)
  );
  SB_DFF q_SB_DFF_Q_4 (
    .C(clk),
    .D(q_SB_DFF_Q_4_D),
    .Q(q[4])
  );
  SB_LUT4 #(
    .LUT_INIT(16'hc0fc)
  ) q_SB_DFF_Q_4_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(a_sampled[3]),
    .I2(b_sampled[3]),
    .I3(q_SB_DFF_Q_D_SB_LUT4_O_I3[2]),
    .O(q_SB_DFF_Q_4_D)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h3cc3)
  ) q_SB_DFF_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(a_sampled[3]),
    .I2(b_sampled[3]),
    .I3(q_SB_DFF_Q_D_SB_LUT4_O_I3[2]),
    .O(q_SB_DFF_Q_D)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h3f03)
  ) q_SB_DFF_Q_D_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(a_sampled[2]),
    .I2(b_sampled[2]),
    .I3(q_SB_DFF_Q_1_D_SB_LUT4_O_I3[2]),
    .O(q_SB_DFF_Q_D_SB_LUT4_O_I3[2])
  );
  assign q_SB_DFF_Q_1_D_SB_LUT4_O_I3[1:0] = { b_sampled[2], a_sampled[2] };
  assign q_SB_DFF_Q_D_SB_LUT4_O_I3[1:0] = { b_sampled[3], a_sampled[3] };
  assign \arithmetic.a  = a_sampled;
  assign \arithmetic.b  = b_sampled;
  assign \arithmetic.carry [0] = 1'h0;
  assign \arithmetic.sum [4] = \arithmetic.carry [4];
  assign sum = { \arithmetic.carry [4], \arithmetic.sum [3:0] };
endmodule
