import {useState} from 'react';
import {Button} from './ui/button';
import {Slider} from './ui/slider';
import {byId,contentPacks,records,relationshipEdges,type RecordEntry} from '../lib/atlas';
import {routeFor} from '../lib/processes';
import CRGBridge from './crg-bridge';
export type ViewMode='anatomy'|'process'|'dependencies';
export function ProcessControls({scene,recordId,index,onStep,onSelect}:{scene:string;recordId:string;index:number;onStep:(n:number)=>void;onSelect:(id:string)=>void}){
 const route=routeFor(scene,recordId),s=route.steps[index] ?? route.steps[0];
 return <div className="process-panel"><div className="process-panel-heading"><span className="eyebrow">PROCESS · {index+1}/{route.steps.length}</span><strong>{s.title}</strong></div><Slider min={0} max={route.steps.length-1} step={1} value={[index]} onValueChange={v=>onStep(Array.isArray(v)?v[0]:v)} aria-label="Manufacturing or execution step"/><div className="process-step-buttons">{route.steps.map((x,i)=><button key={x.title} onClick={()=>onStep(i)} aria-label={`Step ${i+1}: ${x.title}`} aria-current={i===index?'step':undefined}>{i+1}</button>)}</div><p aria-live="polite">{s.title}: {s.action}</p><dl><div><dt>Input</dt><dd>{s.input}</dd></div><div><dt>Output</dt><dd>{s.output}</dd></div><div><dt>Measure</dt><dd>{s.measure}</dd></div></dl><p className="process-why">{s.why}</p><div className="process-footer"><Button variant="outline" size="sm" onClick={()=>onSelect(s.lesson)}>Study {byId[s.lesson]?.shortName||s.lesson}</Button><a href={route.source} target="_blank" rel="noreferrer">Process context ↗</a></div><small>{route.name} · {route.kind}</small></div>;
}
const lanes=[
 {name:'Logic production',ids:['silicon-wafer','lithography','mosfet','interconnect','gpu-die'],type:'produced-by'},
 {name:'Memory production',ids:['dram-die','through-silicon-via','hbm-stack','hbm-controller'],type:'assembled-into'},
 {name:'Package convergence',ids:['interposer','microbump','package-substrate'],type:'assembled-into'},
 {name:'Operating system',ids:['compute-baseboard','rack','cdu','storage'],type:'powered / cooled / connected'},
 {name:'Useful workload',ids:['compiler','kernel','parallelism','serving','evaluation'],type:'executes / evaluates'}
];
export function DependencyView({selected,onSelect}:{selected:RecordEntry;onSelect:(id:string)=>void}){
 const edges=relationshipEdges.filter(e=>e.from===selected.id||e.to===selected.id).slice(0,16);
 const edgeCards=edges.map(e=>{const other=e.from===selected.id?e.to:e.from;return <button key={`${e.from}-${e.to}-${e.kind}`} className="typed-edge" onClick={()=>onSelect(other)}><span>{e.kind}</span><strong>{e.from===selected.id?'to':'from'} · {byId[other]?.shortName||other}</strong><small>{e.label}</small>{e.scope&&<small>{e.scope}</small>}</button>});
 return <div className="dependency-view"><h2>How the system comes together</h2><p>Logic and memory follow separate manufacturing routes. Their outputs converge with routing and substrates before system commissioning.</p><div className="dependency-lanes">{lanes.map(l=><section key={l.name}><h3>{l.name}<small>{l.type}</small></h3><div>{l.ids.map((id,i)=><span key={id}><button className={selected.id===id?'selected':''} onClick={()=>onSelect(id)}>{byId[id]?.shortName||id}</button>{i<l.ids.length-1&&<b aria-hidden="true">→</b>}</span>)}</div></section>)}</div><div className="dependency-current"><span className="eyebrow">SELECTED RELATIONSHIPS</span><h3>{selected.name}</h3><p>{selected.whyAI}</p><div className="typed-edge-list">{edgeCards.length?edgeCards:<span className="meta-explanation">No typed edge is asserted for this legacy node; use its interfaces and source notes.</span>}</div><div>{(selected.prerequisites||[]).filter(id=>byId[id]).map(id=><Button key={id} variant="outline" onClick={()=>onSelect(id)}>Prerequisite · {byId[id].shortName}</Button>)}{(selected.related||[]).filter(id=>byId[id]).map(id=><Button key={id} variant="ghost" onClick={()=>onSelect(id)}>{byId[id].shortName}</Button>)}</div></div><p className="meta-explanation">The graph shows distinct production, integration and functional relationships. A connecting arrow is not a claim that one company supplies another.</p></div>;
}
type Claim={id:string;title:string;statement:string;sourceId:string;lessonIds:string[];status:string;metric:string;value:string|number;unit:string;denominator:string;period:string;scope:string;limitations:string;checkedOn:string};
type Source={id:string;title:string;url:string;publisher:string;published:string;checkedOn:string;locator:string;scope:string};
export function EvidenceLibrary({onSelect}:{onSelect:(id:string)=>void}){
 const [status,setStatus]=useState('all'),[query,setQuery]=useState('');const claims=contentPacks.flatMap(p=>p.claims) as Claim[],sources=contentPacks.flatMap(p=>p.sources) as Source[];
 const visible=claims.filter(c=>(status==='all'||c.status===status)&&(`${c.title} ${c.statement} ${c.metric}`.toLowerCase().includes(query.toLowerCase())));
 return <div className="evidence-library"><div className="evidence-controls"><input aria-label="Search evidence" placeholder="Search capacity, memory, orbital…" value={query} onChange={e=>setQuery(e.target.value)}/><label>Evidence type<select value={status} onChange={e=>setStatus(e.target.value)}>{['all','observed','reported','forecast','announced','research','illustrative','unresolved'].map(s=><option key={s}>{s}</option>)}</select></label></div><p className="meta-explanation">Each statement retains its metric, scope and date. Historical company statements are dated snapshots. Forecasts and unresolved claims are explicitly marked.</p><div className="evidence-cards">{visible.map(c=>{const source=sources.find(s=>s.id===c.sourceId);return <article key={c.id}><span className={'claim-status '+c.status}>{c.status}</span><h3>{c.title}</h3><p>{c.statement}</p><dl><div><dt>Metric / basis</dt><dd>{[c.metric,c.value,c.unit,c.denominator].filter(Boolean).join(' · ')||'Qualitative statement'}</dd></div><div><dt>Applies to</dt><dd>{c.scope}</dd></div><div><dt>Period</dt><dd>{c.period}</dd></div></dl><p className="evidence-limit">{c.limitations}</p>{source&&<a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗<small>{source.published} · {source.locator}</small></a>}<small>Checked {c.checkedOn}</small><div className="claim-lessons">{c.lessonIds.filter(id=>byId[id]).map(id=><Button variant="ghost" key={id} onClick={()=>onSelect(id)}>Explore {byId[id].shortName}</Button>)}</div></article>;})}</div>{visible.length===0&&<p>No claims match these filters.</p>}</div>;
}
export function LessonDepth({record,onSelect}:{record:RecordEntry;onSelect:(id:string)=>void}){
 return <>{record.learningObjective&&<div className="learning-objective"><span className="eyebrow">AFTER THIS LESSON</span><p>{record.learningObjective}</p></div>}{record.workstream==='CRG'&&<CRGBridge/>}{record.engineeringExample&&<div className="science-card"><h3>Worked engineering example</h3><p>{record.engineeringExample}</p></div>}{record.prerequisites?.length? <div className="prerequisite-links"><h3>Build on these concepts</h3>{record.prerequisites.filter(id=>byId[id]).map(id=><button onClick={()=>onSelect(id)} key={id}>{byId[id].shortName} ↗</button>)}</div>:<p className="meta-explanation">Start here: no prior atlas lesson is required.</p>}{record.evidenceNotes&&<p className="evidence-limit">{record.evidenceNotes}</p>}</>;
}
export function Glossary(){const definitions=[['FEOL','Front end of line: device structures formed in and on the wafer.'],['MOL','Middle of line: contacts connecting devices to the wiring stack.'],['BEOL','Back end of line: metal wiring and vias above the devices.'],['TSV','Through-silicon via: an electrical connection passing through silicon.'],['HBM','High-bandwidth memory: stacked DRAM with a wide, close-coupled interface.'],['PHY','Physical interface circuitry handling signaling between endpoints.'],['PDK','Process design kit: process-specific models, rules and design support.'],['NRE','Non-recurring engineering: development expense before volume manufacture.'],['OSAT','Outsourced semiconductor assembly and test provider.'],['SIMT','Single instruction, multiple threads: grouped thread execution used in GPU programming.'],['PUE','Facility energy divided by IT equipment energy over a stated period.'],['FLOP/s','Floating-point operations per second, with precision and counting convention specified.'],['GB / GiB','GB is 10⁹ bytes; GiB is 2³⁰ bytes.'],['Capacity / bandwidth / latency','How much can be stored; how quickly data can move; how long one access takes.']];return <dl className="glossary">{definitions.map(([term,meaning])=><div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}<p>{records.length} lessons connect these terms to mechanisms, worked examples and evidence.</p></dl>;}
