import {incidentCorpusId} from '../lib/automation-learning-model';
import type {LearnedActionHandoff} from '../lib/automation-learned-bridge';
import {useEffect,useMemo,useState} from 'react';
import {Control,Details,Metrics,SourceLinks,number} from './studio-primitives';
import {automationCases,automationTask,automationMetrics,createAutomationScenario,evaluateAutomationEnvironment,replayAutomationJournal,runAutomationScenario,type AutomationScenario,type AutomationSnapshot} from '../lib/automation-execution';
import {automationCallFingerprint,executeAutomationTool,validateAutomationCall} from '../lib/automation-tools';
import {createAutomationEnvironment} from '../lib/automation-fixtures';
import {createAutomationWorkspace,type AutomationStorage} from '../lib/automation-journal';
import type {AutomationCommand} from '../lib/automation-execution';
import './automation-explorer.css';
const newId=()=>`run-${crypto.randomUUID()}`;
function browserStorage():AutomationStorage{try{return window.localStorage;}catch{return{getItem(){throw Error('Browser storage is unavailable. Durable execution needs writable local storage.');},setItem(){throw Error('Browser storage is unavailable.');}};}}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function observedSnapshot(snapshot:AutomationSnapshot,index:number):AutomationSnapshot {
 if(index>=snapshot.document.events.length-1)return snapshot;
 const document={...snapshot.document,events:snapshot.document.events.slice(0,index+1)};let environment=createAutomationEnvironment(document.scenario.caseId);
 for(const event of document.events)if(['tool-result','transport-timeout','service-replayed'].includes(event.kind)){
  const before=replayAutomationJournal({...document,events:document.events.slice(0,event.seq)});
  environment=executeAutomationTool(validateAutomationCall(before.pending!.call),environment,event.atMs).environment;
 }
 return{document,environment};
}
const done=(status:string)=>['completed','failed','canceled'].includes(status);
export default function AutomationExplorer({onSelect,handoff}:{onSelect?:(id:string)=>void;handoff?:LearnedActionHandoff|null}){
 const[workspace]=useState(()=>createAutomationWorkspace(browserStorage()));
 const[snapshot,setSnapshot]=useState<AutomationSnapshot|null>(()=>workspace.snapshot),[error,setError]=useState<string|null>(()=>workspace.error),[cursor,setCursor]=useState(0),[draft,setDraft]=useState<AutomationScenario>(()=>workspace.snapshot?.document.scenario??createAutomationScenario());
 const[notice,setNotice]=useState(''),[importing,setImporting]=useState(false),[exportedOlder,setExportedOlder]=useState<string|null|undefined>(undefined);
 const refresh=()=>{const value=workspace.snapshot;setSnapshot(value);setError(workspace.error);if(value)setCursor(value.document.events.length-1);};
 useEffect(()=>{if(!workspace.snapshot&&!workspace.error){workspace.start(createAutomationScenario({runId:newId()}));refresh();}else if(workspace.snapshot)setCursor(workspace.snapshot.document.events.length-1);},[workspace]);
 const start=()=>{if(importing)return;workspace.start({...draft,runId:newId()});refresh();setNotice('A new incident run starts from the same fictional environment. The previous raw record is retained for recovery.');};
 const advance=(command:AutomationCommand={kind:'next'})=>{workspace.advance(command);refresh();};
 const continueToReview=()=>{
  for(let i=0;i<250;i++){
   const current=workspace.snapshot;if(!current)break;const state=replayAutomationJournal(current.document);
   if(state.status==='awaiting-approval'||(done(state.status)&&!state.queue))break;
   workspace.advance();if(workspace.error)break;
  }
  refresh();
 };
 const current=snapshot?replayAutomationJournal(snapshot.document):null;
 const inspected=useMemo(()=>snapshot?observedSnapshot(snapshot,Math.min(cursor,snapshot.document.events.length-1)):null,[snapshot,cursor]);
 const at=inspected?replayAutomationJournal(inspected.document):null,verdict=inspected?evaluateAutomationEnvironment(inspected):null,metrics=inspected?automationMetrics(inspected):null;
 const comparison=useMemo(()=>snapshot?(['fixed-workflow','authored-policy'] as const).map(mode=>{const r=runAutomationScenario({...snapshot.document.scenario,mode});return{mode,state:replayAutomationJournal(r.document),metrics:automationMetrics(r),verdict:evaluateAutomationEnvironment(r)};}):[],[snapshot?.document.scenario]);
 const importFile=async(file:File|undefined)=>{
  if(!file)return;setImporting(true);setNotice('Reading the selected journal archive…');
  try{if(file.size>500000)throw Error('Archive exceeds 500,000 bytes.');const raw=await file.text();workspace.restore(raw);refresh();if(workspace.snapshot)setDraft(workspace.snapshot.document.scenario);setNotice(workspace.error?'Import did not replace the active run.':'Imported journal and external environment were independently replay-checked.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setImporting(false);}
 };
 return <section className="automation-explorer" aria-label="Durable incident automation">
  <div className="studio-heading"><h3>One incident becomes a verified action</h3><p>Execute a fictional maintenance workflow. Inspect the proposed tool call, schema, authority, exact human approval, service, receipt and final environment. The two baseline policies are authored code. A fitted proposal from the retrieval experience can enter the same runtime gates; its outer workflow remains authored.</p></div>
  <p className="studio-note"><strong>The task:</strong> {automationTask.description} All equipment, documents and service times are invented teaching fixtures. Corpus: {incidentCorpusId}; task: {automationTask.id}.</p>
  {handoff&&<div className="studio-task"><h4>Learned proposal ready for a new run</h4><p>Frozen local policy: <code>{handoff.model.policyId}</code>. Candidate reranker: {handoff.result.reranking?.version??'none'}. Generated tokens: <code>{handoff.result.text}</code>. This action starts a new fictional environment and preserves the prior run. It grants no approval. The incident case, call budget and synthetic times apply; the baseline policy selector does not change this frozen proposal. The schema-error case deliberately converts its numeric quantity to a string after generation.</p><button disabled={importing} onClick={()=>{workspace.start({...draft,runId:newId()},handoff);refresh();setNotice(workspace.error??'Started a run with the frozen learned handoff; runtime checks and human review remain required.');}}>Start run from learned proposal</button></div>}
  <div className="studio-layout"><aside className="studio-sidebar"><h4>Configure a new run</h4><label>Incident case<select value={draft.caseId} disabled={importing} onChange={e=>setDraft({...draft,caseId:e.target.value as AutomationScenario['caseId']})}>{automationCases.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><p>{automationCases.find(x=>x.id===draft.caseId)?.lesson}</p>
   <label>Execution policy<select value={draft.mode} disabled={importing} onChange={e=>setDraft({...draft,mode:e.target.value as AutomationScenario['mode']})}><option value="fixed-workflow">Fixed workflow</option><option value="authored-policy">Bounded authored policy</option></select></label>
   <Control label="Tool-call budget for new run" value={draft.maxCalls} min={1} max={12} onChange={maxCalls=>setDraft({...draft,maxCalls})} disabled={importing}/><Control label="Synthetic admission delay" value={draft.admissionDelayMs} min={0} max={1000} step={10} unit="ms" onChange={admissionDelayMs=>setDraft({...draft,admissionDelayMs})} disabled={importing}/><Control label="Assumed wait per human review" value={draft.approvalWaitMs} min={0} max={1000} step={50} unit="ms" onChange={approvalWaitMs=>setDraft({...draft,approvalWaitMs})} disabled={importing}/>
   <button onClick={start} disabled={importing}>Start configured run</button><p className="studio-note">These settings apply when a new run starts. Review wait is a synthetic timeline input, not the time you spend reading.</p>
  </aside><div className="studio-main">
   {error&&<p className="automation-error" role="alert">{error} The last committed journal and any already committed environment effect are retained. Export recovery data before clearing browser storage.</p>}
   {current&&snapshot&&<><p className="automation-live" aria-live="polite"><strong>Active run: {current.status.replaceAll('-',' ')}</strong> · {snapshot.document.learnedHandoff?'Fitted proposal / authored workflow':snapshot.document.scenario.mode==='fixed-workflow'?'Fixed workflow':'Bounded authored policy'} · {automationCases.find(x=>x.id===snapshot.document.scenario.caseId)?.label}</p>
    {snapshot.document.learnedHandoff&&<p className="studio-note">Saved learned policy: <code>{snapshot.document.learnedHandoff.model.policyId}</code> · {snapshot.document.learnedHandoff.corpusId} · {snapshot.document.learnedHandoff.taskId}. Candidate reranker: {snapshot.document.learnedHandoff.result.reranking?.version??'none'}. The frozen weights, request and proposal travel with this journal and survive reload. Model fitting and generation happened before this synthetic workflow clock started. <code>{snapshot.document.learnedHandoff.result.text}</code></p>}
    <div className="automation-actions"><button onClick={()=>advance()} disabled={importing||current.status==='awaiting-approval'||(done(current.status)&&!current.queue)}>Next transition</button><button onClick={continueToReview} disabled={importing||current.status==='awaiting-approval'||(done(current.status)&&!current.queue)}>Run to next review or stop</button><button onClick={()=>advance({kind:'cancel'})} disabled={importing||done(current.status)}>Request cancellation</button></div>
    {current.status==='awaiting-approval'&&current.pending&&<div className="automation-approval" role="region" aria-label="Review exact reservation"><h4>Approve this concrete reservation</h4><pre>{JSON.stringify(current.pending.call,null,2)}</pre><p>Approval binds every displayed field. It gives this action no additional tool capability. Declining stops this run before reservation service.</p><div className="automation-actions"><button disabled={importing} onClick={()=>advance({kind:'approve',fingerprint:automationCallFingerprint(current.pending!.call)})}>Approve this reservation</button><button disabled={importing} onClick={()=>advance({kind:'deny'})}>Decline reservation</button></div></div>}
    <h4>Inspect a recorded transition</h4><Control label="Journal entry" value={Math.min(cursor,snapshot.document.events.length-1)} min={0} max={snapshot.document.events.length-1} onChange={setCursor}/>
    {at&&inspected&&metrics&&verdict&&<><p><strong>Entry {cursor+1} · {number(at.atMs,0)} synthetic ms:</strong> {at.lastDetail}</p><div className="automation-pipeline" aria-label="State at selected journal entry">{[['Queue',`${at.queue} delivery pending`],['Worker',at.status.replaceAll('-',' ')],['Tool boundary',at.pending?`${at.pending.call.name}: ${at.pending.stage}`:'No pending call'],['Environment',`${inspected.environment.reservations.length} reservation / ${inspected.environment.workOrders.length} work order`]].map(([name,value])=><div key={name}><strong>{name}</strong><span>{value}</span></div>)}</div>
     <Metrics items={[["Task goal in selected environment",verdict.taskCorrect?'Satisfied':'Not satisfied'],["Citation support among work orders",verdict.sourceSupportDenominator?`${verdict.sourceSupported} / ${verdict.sourceSupportDenominator}`:'No work order to score'],["Proposed tool calls",String(metrics.calls)],["Recorded errors / denied calls",String(metrics.errors)],["Committed effects",String(metrics.committedEffects)],["Duplicate deliveries ignored",String(metrics.duplicateDeliveries)]]}/>
     <div className="studio-table-wrap" role="region" aria-label="Independent environment checks" tabIndex={0}><table className="studio-table"><caption>Independent task check: policy completion is not used as evidence</caption><thead><tr><th>Contract</th><th>Result at this entry</th></tr></thead><tbody>{verdict.checks.map(x=><tr key={x.label}><th>{x.label}</th><td className={'studio-status '+(x.passed?'pass':'fail')}>{x.passed?'Holds':'Not satisfied'}</td></tr>)}</tbody></table></div>
     <Details title="Actual fictional environment at the selected entry"><p>On a lost reply, a committed reservation exists even though the caller has no successful response. During recovery from a failed journal write, the latest environment can be ahead of the last durable journal event.</p><Metrics items={Object.entries(inspected.environment.stock).map(([part,n])=>[`${part} remaining`,String(n)])}/><pre className="studio-readout">{JSON.stringify({reservations:inspected.environment.reservations,workOrders:inspected.environment.workOrders,receipts:inspected.environment.receipts,exports:inspected.environment.exports},null,2)}</pre></Details>
     <Details title="Current caller observation and exact tool payload"><pre className="studio-readout">{JSON.stringify({pending:at.pending,observations:at.observations},null,2)}</pre></Details>
     <Details title="Time and payload accounting"><Metrics items={[["Elapsed recorded timeline",`${metrics.elapsedMs} ms`],["Queue admission",`${metrics.queueMs} ms`],["Recorded completed service",`${metrics.serviceMs} ms`],["Human review assumption",`${metrics.approvalMs} ms`],["Other / restart / validation",`${metrics.otherMs} ms`],["Proposed-call JSON payload",`${metrics.requestPayloadBytes} bytes`]]}/><p>This single worker serializes service. Elapsed time equals queue, service, review and other intervals. Costs are authored timing assumptions and UTF-8 JSON payload counts; they are not model tokens, network wire bytes, energy or vendor performance measurements.</p></Details>
    </>}
   </>}
  </div></div>
  {snapshot&&<><Details title={`Full durable journal · ${snapshot.document.events.length} transitions`}><div className="studio-table-wrap" role="region" aria-label="Automation event journal" tabIndex={0}><table className="studio-table"><thead><tr><th>Entry / synthetic time</th><th>Event</th><th>Consequence</th><th>Inspect</th></tr></thead><tbody>{snapshot.document.events.map(e=><tr key={e.seq} aria-current={cursor===e.seq?'step':undefined}><th>{e.seq+1} / {e.atMs} ms</th><td>{e.kind.replaceAll('-',' ')}</td><td>{e.detail}</td><td><button onClick={()=>setCursor(e.seq)}>Entry {e.seq+1}</button></td></tr>)}</tbody></table></div></Details>
   <h4>Same case, two authored execution designs</h4><p>Both comparison runs use this active case, budget and synthetic timings. The comparison automatically approves every exact reservation to isolate policy behavior; it does not approve anything in your active run. The authored policy can repair a schema error and look up a lost receipt, but its first-fact rule can choose the wrong entity.</p><div className="studio-table-wrap" role="region" aria-label="Workflow and authored policy comparison" tabIndex={0}><table className="studio-table"><thead><tr><th>Policy</th><th>Worker report</th><th>Independent task result</th><th>Supported orders</th><th>Calls / synthetic elapsed</th></tr></thead><tbody>{comparison.map(x=><tr key={x.mode}><th>{x.mode==='fixed-workflow'?'Fixed workflow':'Bounded authored policy'}</th><td>{x.state.status}</td><td>{x.verdict.taskCorrect?'Correct task':'Task incomplete or wrong'}</td><td>{x.verdict.sourceSupported} / {x.verdict.sourceSupportDenominator}</td><td>{x.metrics.calls} / {x.metrics.elapsedMs} ms</td></tr>)}</tbody></table></div>
  </>}
  <Details title="Saved incident journal and recovery"><p>The active journal and fictional external environment are saved separately in this browser. Reload resumes the recorded run. A result-write failure can leave the external commit ahead of the journal; retry recovers its original receipt. This is a local teaching storage port, not a production distributed database.</p><div className="automation-actions"><button disabled={!snapshot||importing} onClick={()=>{try{download('atlas-incident-journal.json',workspace.exportText());setNotice('Exported the current run and its external environment.');}catch(e){setError(String(e));}}}>Export incident journal</button><label className="automation-import">Import checked journal<input type="file" accept="application/json,.json" disabled={importing} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void importFile(file);}}/></label><button onClick={()=>{try{download('atlas-incident-recovery.json',workspace.recoveryText());setExportedOlder(workspace.olderRaw());setNotice('Exported exact raw active, environment and older recovery records.');}catch(e){setError(String(e));}}}>Export older / unreadable records</button>{exportedOlder!==undefined&&<button disabled={importing} onClick={()=>{if(workspace.clearExportedOlder(exportedOlder)){setExportedOlder(undefined);setNotice('Cleared the exported recovery list; the active run remains.');}setError(workspace.error);}}>Clear exported recovery list</button>}</div><p role="status">{notice}</p><p>Changing the case or importing preserves the prior raw record first. Recovery has a bounded capacity of 30 displaced records; a full or unwritable backup leaves the active run unchanged.</p></Details>
  <div className="studio-task"><h4>Predict the uncertain boundary</h4><p>Run “The write happened; the reply was lost.” Before recovery, predict stock, reservations and caller knowledge separately. Then try “Supported evidence, wrong machine”: explain how every citation can be supported while the final task is wrong. Transfer the reasoning to a duplicate payment or an interrupted robot goal.</p></div>
  {onSelect&&<div className="automation-actions">{[['tool-loop','Tool calls and observations'],['evaluation','Evaluate the task'],['checkpoint','What a checkpoint restores'],['runtime-device-dispatch','Queueing and completion']].map(([id,label])=><button key={id} onClick={()=>onSelect(id)}>{label} →</button>)}</div>}
  <SourceLinks items={[{title:'Temporal · Activities and idempotency',url:'https://docs.temporal.io/activities'},{title:'Temporal · Workflow history and replay',url:'https://docs.temporal.io/workflow-execution'},{title:'MCP 2026-07-28 · Tool contracts',url:'https://modelcontextprotocol.io/specification/2026-07-28/server/tools'},{title:'MCP 2026-07-28 · Authorization',url:'https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization'},{title:'τ-bench · Evaluate final task state',url:'https://arxiv.org/abs/2406.12045'}]}/>
 </section>;
}
