import {useMemo,useRef,useState} from 'react';
import {buildCommissioningTrace,commissioningDefaults,type CommissioningInput,type CommissioningState} from '../lib/commissioning-execution';
import {makeCommissioningRecord,parseCommissioningRecord,saveCommissioningRecord,exportOlderCommissioningRecords,commissioningRecordKey} from '../lib/commissioning-execution-record';
import './commissioning-execution.css';
const hex=(x:number)=>`0x${x.toString(16).toUpperCase().padStart(4,'0')}`;
const row=(v:(number|null)[])=>`[${v.slice(0,2).map(x=>x??'·').join(', ')}] [${v.slice(2,4).map(x=>x??'·').join(', ')}]`;
function initial(){try{const raw=typeof window==='undefined'?null:localStorage.getItem(commissioningRecordKey);return {input:raw?parseCommissioningRecord(raw).input:commissioningDefaults,message:raw?'Restored saved commissioning inputs.':'Use Save to retain these inputs on this device.',older:typeof window!=='undefined'&&exportOlderCommissioningRecords(localStorage)!==null};}catch(error){let older=false;try{older=exportOlderCommissioningRecords(localStorage)!==null;}catch{}return {input:commissioningDefaults,message:`Saved input was not applied: ${error instanceof Error?error.message:'storage unavailable'}. Current controls remain usable.`,older};}}
function download(raw:string,name:string){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function AddressMap({state}:{state:CommissioningState}){return <div className="commissioning-map"><svg viewBox="0 0 900 340" role="img" aria-labelledby="commissioning-map-title commissioning-map-desc"><title id="commissioning-map-title">Process virtual, physical and device addresses</title><desc id="commissioning-map-desc">Each left process buffer maps to physical storage in the middle. Right device ranges connect to the physical region actually selected by the current translation table. Wrong mapping connects device B to physical A. A complete table follows.</desc><text x="20" y="24">Process-1 virtual address</text><text x="335" y="24">Physical memory</text><text x="660" y="24">Device IOVA</text>{state.buffers.map((b,i)=>{const y=46+i*94,m=state.mappings.find(m=>m.buffer===b.id),target=m?state.buffers.findIndex(v=>v.physical===m.physical):i;return <g key={b.id}><path d={`M245 ${y+31} L322 ${y+31}`} className="cpu-path"/><path d={`M652 ${y+31} C614 ${y+31} 610 ${77+target*94} 576 ${77+target*94}`} className={m?m.physical!==b.physical?'bad-path':'dma-path':'unmapped-path'}/><rect x="12" y={y} width="233" height="66" rx="9"/><text x="24" y={y+25}>{b.id} · VA {hex(b.virtual)}</text><text x="24" y={y+49} className="map-small">CPU owner: {b.owner==='host'?'yes':'no · device owns'}</text><rect x="322" y={y} width="254" height="66" rx="9"/><text x="334" y={y+25}>{b.id} · PA {hex(b.physical)}</text><text x="334" y={y+49} className="map-small">{row(b.memory)}</text><rect x="652" y={y} width="236" height="66" rx="9"/><text x="664" y={y+25}>{b.id} · IOVA {hex(b.iova)}</text><text x="664" y={y+49} className="map-small">{m?`${m.read?'read':''}${m.write?'write':''} · epoch ${m.epoch}`:'No current translation'}</text></g>;})}</svg></div>;}
export default function CommissioningExecution({onSelect}:{onSelect?:(id:string)=>void}={}){
 const [start]=useState(initial),[input,setInput]=useState<CommissioningInput>(start.input),[cursor,setCursor]=useState(0),[message,setMessage]=useState(start.message),[older,setOlder]=useState(start.older),file=useRef<HTMLInputElement>(null);
 const result=useMemo(()=>buildCommissioningTrace(input),[input]),index=Math.min(cursor,result.events.length-1),event=result.events[index],s=event.state,update=(patch:Partial<CommissioningInput>)=>{setInput({...input,...patch});setCursor(0);},issues=result.events.filter(e=>e.issue),jump=(kind:string)=>{const e=result.events.find(e=>e.kind===kind);if(e)setCursor(e.index);};
 return <section className="commissioning-execution" aria-label="Commissioning, address spaces and device completion">
 <header><p className="commissioning-eyebrow">From a powered device to one accepted result</p><h3>Who owns this buffer, and which machine can see it?</h3><p>Follow the same exact 2×2 matrix job through a declared device ABI, driver resources, address translation, DMA, arithmetic and recovery. Each step is an event in a teaching protocol; it has no measured duration.</p></header>
 <div className="commissioning-input-matrices">{(['a','b'] as const).map(id=><fieldset key={id}><legend>Matrix {id.toUpperCase()} · signed integers</legend><div>{input[id].flat().map((v,k)=><input key={k} aria-label={`${id.toUpperCase()} row ${Math.floor(k/2)+1} column ${k%2+1}`} type="number" min="-99" max="99" step="1" value={v} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&Math.abs(n)<=99){const m=input[id].map(r=>[...r]);m[Math.floor(k/2)][k%2]=n;update({[id]:m});}}}/>)}</div></fieldset>)}<aside><strong>Independent mathematical reference</strong><p>{row(result.reference.flat())}</p><small>The device's arithmetic uses transferred values. This reference only checks the outcome.</small></aside></div>
 <div className="commissioning-controls"><label>Firmware handoff<select value={input.boot} onChange={e=>update({boot:e.target.value as CommissioningInput['boot']})}><option value="compatible">Compatible teaching ABI</option><option value="abi-mismatch">Incompatible ABI</option></select></label><label>Memory visibility<select value={input.coherence} onChange={e=>update({coherence:e.target.value as CommissioningInput['coherence']})}><option value="noncoherent">Separate CPU cache and memory</option><option value="coherent">Ideal coherent values</option></select></label><label>Visibility handoff<select value={input.sync} onChange={e=>update({sync:e.target.value as CommissioningInput['sync']})}><option value="both">Inputs to device + output to CPU</option><option value="skip-to-device">Omit input visibility handoff</option><option value="skip-to-cpu">Omit output visibility handoff</option></select></label><label>Failure specimen<select value={input.fault} onChange={e=>update({fault:e.target.value as CommissioningInput['fault']})}><option value="none">No injected failure</option><option value="wrong-mapping">B maps to A · permitted wrong buffer</option><option value="unmapped-b">B mapping is absent</option><option value="early-reuse">Attempt early reuse of B</option><option value="device-reset">Reset the device during the job</option></select></label>{input.fault==='device-reset'&&<><label>Reset after output cells<select value={input.resetAfterCells} onChange={e=>update({resetAfterCells:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>Reset recovery<select value={input.resetPolicy} onChange={e=>update({resetPolicy:e.target.value as CommissioningInput['resetPolicy']})}><option value="retry">Quiesce, reinitialize, retry once</option><option value="stop">Quiesce and stop without output</option></select></label></>}</div>
 <div className="commissioning-toolbar"><button onClick={()=>{setInput(commissioningDefaults);setCursor(0);}}>Default job</button><button onClick={()=>jump('submit')}>Inspect submission</button><button disabled={!issues.length} onClick={()=>setCursor(issues[0].index)}>First rejected or failed action</button><button onClick={()=>setCursor(result.events.length-1)}>Run outcome</button></div>
 <div className="commissioning-stepper"><button disabled={index===0} aria-label="Previous commissioning event" onClick={()=>setCursor(index-1)}>←</button><label>Event {index+1} / {result.events.length} · epoch {s.epoch}<input type="range" min="0" max={result.events.length-1} value={index} onChange={e=>setCursor(Number(e.target.value))}/></label><button disabled={index===result.events.length-1} aria-label="Next commissioning event" onClick={()=>setCursor(index+1)}>→</button></div>
 <div className={`commissioning-event ${event.issue?'has-issue':''}`} aria-live="polite"><strong>{event.kind.replaceAll('-',' ')}</strong><p>{event.label}</p></div>
 <div className="commissioning-gates">{[['Firmware ABI',s.firmwareReady],['Discovered',s.discovered],['Resources claimed',s.resourcesClaimed],['DMA enabled',s.dmaEnabled],['Queue ready',s.queueReady],['Completion accepted',s.completion?.accepted??false]].map(([label,yes])=><span className={yes?'ready':''} key={String(label)}>{yes?'●':'○'} {label}</span>)}</div>
 <AddressMap state={s}/><p className="commissioning-caption">Addresses are bytes; each modeled buffer occupies 16 bytes. The translation table uses declared byte ranges, not a real page-table format or hardware IOMMU protection granularity.</p>
 <div className="commissioning-buffer-grid">{s.buffers.map(b=><article key={b.id}><h4>Buffer {b.id} · owned by {b.owner}</h4><p>CPU-visible: <b>{row(b.cpu)}</b></p><p>Physical memory: <b>{row(b.memory)}</b></p><small>{b.cpuDirty?'CPU has newer dirty input.':b.cpuStale?'CPU output cache has not been refreshed.':'This buffer has no pending visibility discrepancy.'}</small></article>)}</div>
 <div className="commissioning-engine"><article><h4>Actual device operands</h4><p>A {row(s.deviceA)}</p><p>B {row(s.deviceB)}</p></article><article><h4>Device result cells written</h4><p>{row(s.deviceC)}</p><small>Written cells alone do not establish an accepted result.</small></article><article><h4>Published consumer result</h4><p>{s.published?row(s.published):'No result published at this event'}</p><small>Job: matrix-job-1 · active descriptor epoch {s.descriptor?.epoch??'none'}</small></article></div>
 {event.access&&<div className="commissioning-access"><strong>{event.access.kind} · logical {event.access.buffer}[{event.access.word}]</strong><p>{event.access.iova!==null?`IOVA ${hex(event.access.iova)} → `:''}{event.access.physical!==null?`physical ${hex(event.access.physical)} · `:''}value {event.access.value??'four-word buffer'}</p><small>{event.access.detail}</small></div>}
 <dl className="commissioning-ledger">{[['Executed MACs',s.executedMacs],['Active MACs',s.activeMacs],['Discarded MACs',s.discardedMacs],['Committed MACs',s.committedMacs],['DMA read bytes',s.readBytes],['DMA written bytes',s.writeBytes]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>{v}</dd></div>)}</dl><p>Executed = active + discarded + committed. “Committed” records the accepted attempt's arithmetic; the fixture separately checks semantic correctness.</p>
 <p className={`commissioning-outcome ${result.status==='semantic-mismatch'?'has-issue':''}`}>Full-run outcome: <strong>{result.status.replaceAll('-',' ')}</strong> · {result.finalOutput?row(result.finalOutput.flat()):'No published output'}. {result.status==='semantic-mismatch'?'The consumer read actual values that differ from the intended A×B result.':''}</p>
 <details><summary>Translation table and full state trace</summary><div className="commissioning-table" role="region" tabIndex={0} aria-label="Current device translation table"><table><thead><tr><th>Logical buffer</th><th>Process VA → PA</th><th>Device IOVA → actual PA</th><th>Permission / epoch</th></tr></thead><tbody>{s.buffers.map(b=>{const m=s.mappings.find(m=>m.buffer===b.id);return <tr key={b.id}><th>{b.id}</th><td>{hex(b.virtual)} → {hex(b.physical)}</td><td>{hex(b.iova)} → {m?hex(m.physical):'unmapped'}</td><td>{m?`${m.read?'read':''}${m.write?'write':''} / ${m.epoch}`:'none'}</td></tr>;})}</tbody></table></div><div className="commissioning-table" role="region" tabIndex={0} aria-label="Complete commissioning event trace"><table><thead><tr><th>Event</th><th>Epoch</th><th>Executed / discarded / committed MACs</th><th>Meaning</th></tr></thead><tbody>{result.events.map(e=><tr key={e.index} className={e.index===index?'selected':''}><th><button onClick={()=>setCursor(e.index)}>{e.index+1} · {e.kind}</button></th><td>{e.state.epoch}</td><td>{e.state.executedMacs} / {e.state.discardedMacs} / {e.state.committedMacs}</td><td>{e.label}</td></tr>)}</tbody></table></div></details>
 <div className="commissioning-task"><h4>Predict → trace → explain</h4><p>Keep A and B at their defaults. Map B to A, then remove B's mapping entirely. Which case completes with wrong arithmetic, and which never supplies a B operand? Next restore the map and reset after two output cells: explain why twelve executed MACs produce one eight-MAC accepted job.</p></div>
 <details><summary>Save and restore this specimen</summary><p>Records contain the complete inputs and model identity. Import changes this session; Save retains the inputs on this device. An incompatible older raw record is preserved before saved replacement.</p><div className="commissioning-toolbar"><button onClick={()=>{try{saveCommissioningRecord(localStorage,makeCommissioningRecord(input));setOlder(exportOlderCommissioningRecords(localStorage)!==null);setMessage('Saved commissioning inputs on this device.');}catch(error){setMessage(`Save failed: ${error instanceof Error?error.message:'storage unavailable'}. Live inputs and export remain usable.`);}}}>Save inputs</button><button onClick={()=>download(JSON.stringify(makeCommissioningRecord(input),null,2),'ai-atlas-commissioning-input.json')}>Export input record</button><button onClick={()=>file.current?.click()}>Import input record</button><button disabled={!older} onClick={()=>{try{const raw=exportOlderCommissioningRecords(localStorage);if(raw)download(raw,'ai-atlas-older-commissioning-input.txt');}catch(error){setMessage(`Older record export failed: ${error instanceof Error?error.message:'storage unavailable'}`);}}}>Export older saved input</button><input type="file" ref={file} accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>65536)throw new Error('File exceeds 64 KiB.');const r=parseCommissioningRecord(await f.text());setInput(r.input);setCursor(0);setMessage('Imported valid inputs for this session. Choose Save to retain them on this device.');}catch(error){setMessage(`Import rejected: ${error instanceof Error?error.message:'invalid file'}. Current inputs remain unchanged.`);}}}/></div></details><p className="commissioning-record-status" role="status">{message}</p>
 <details><summary>Contract, physics and security boundaries</summary><ul><li>This is a finite teaching state machine inspired by Linux 6.16 driver/DMA guidance and Virtio 1.3 readiness/reset rules. It is not an emulated or conforming PCI/Virtio device.</li><li>Firmware advertises an ABI string and readiness. No boot ROM, image loader, signature, key, measurement, attestation, secure boot or cryptographic verification is executed.</li><li>Virtual/physical/device bases are declared; the byte-range checker does not model page pinning, TLB/IOTLB walks, ATS/PASID, MMIO transaction ordering or real page-granular isolation.</li><li>Coherent mode means immediate shared values in this model. Noncoherent mode has two explicit copies. Neither runs a cache-coherence protocol, barriers on a CPU ISA, or a real Linux mapping call. The separate translation-install and visibility actions are teaching boundaries.</li><li>Reset acknowledgement means the device has stopped touching old buffers before reclamation. Retry assumes intact host inputs and a working reinitialized device. An old notification is already in the host inbox, not newly emitted by the reset device. External side-effecting jobs need an additional replay contract.</li><li>Exact signed integer arithmetic uses ±99 inputs and four-byte words. Events count ordering and work, not CPU instructions, clock cycles, bus packets, elapsed time, energy or hardware performance.</li></ul></details>
 <nav className="commissioning-toolbar" aria-label="Related runtime lessons">{[['firmware-device-contract','Device readiness'],['process-dma-address-spaces','Address spaces'],['iommu-buffer-identity','Buffer identity'],['dma-visibility-ownership','Visibility and ownership'],['device-completion-reset-epochs','Completion and reset']].map(([id,label])=><button key={id} disabled={!onSelect} onClick={()=>onSelect?.(id)}>{label}</button>)}</nav><ul className="commissioning-sources"><li><a href="https://docs.kernel.org/6.16/PCI/pci.html" target="_blank" rel="noreferrer">Linux 6.16 · PCI driver discovery, initialization and cleanup</a></li><li><a href="https://docs.kernel.org/6.16/core-api/dma-api-howto.html" target="_blank" rel="noreferrer">Linux 6.16 · address spaces, DMA visibility and ordering</a></li><li><a href="https://docs.oasis-open.org/virtio/virtio/v1.3/virtio-v1.3.html" target="_blank" rel="noreferrer">Virtio 1.3 · status, initialization and reset contracts</a></li></ul>
 </section>;
}
