import {useMemo,useState} from 'react';
import {Control,Details,Metrics,SourceLinks,Stepper,number} from './studio-primitives';
import PortableExperiment from './portable-experiment';
import {buildDataLineage,decodeByteBpe,displayBpeToken,encodeLineageRecord,lineageCorpus,lineageDefaults,lineageOrigin,readLineageRecord,type LineageInput} from '../lib/data-lineage';
import {lifecycleExamples,lifecycleVocabulary,lifecycleTokenizerVersion} from '../lib/model-lifecycle-data';
import './data-lineage-explorer.css';
export default function DataLineageExplorer({onSelect}:{onSelect?:(id:string)=>void}){
 const[input,setInput]=useState<LineageInput>(lineageDefaults),[documentId,setDocumentId]=useState(lineageCorpus[0].id),[block,setBlock]=useState(0),[attentionRow,setAttentionRow]=useState(0);
 const result=useMemo(()=>buildDataLineage(input),[input]),alternative=useMemo(()=>buildDataLineage({...input,splitStrategy:input.splitStrategy==='family'?'document':'family'}),[input]);
 const change=(patch:Partial<LineageInput>)=>{setInput(s=>({...s,...patch}));setBlock(0);setAttentionRow(0);};
 const source=result.documents.find(d=>d.id===documentId)!,encoded=result.encoded.find(d=>d.documentId===documentId)!,packed=result.packing.blocks[Math.min(block,result.packing.blocks.length-1)],selected=packed[Math.min(attentionRow,packed.length-1)];
 const cross=result.duplicates.filter(x=>x.crossSplit),alternateCross=alternative.duplicates.filter(x=>x.crossSplit),eligible=result.documents.filter(d=>d.split==='train'&&!d.excludedFromTraining),lifecycle=lifecycleExamples('train','copy')[0];
 return <section className="data-lineage-explorer" aria-label="Corpus lineage, tokenizer construction and packed batches"><div className="studio-heading"><h3>Follow the data into a batch</h3><p>Inspect original document families before transformation. Assign splits, diagnose duplicates, train byte-pair merges on training fields, encode prompt and response boundaries, then reconstruct a sampled packed batch from its seed and cursor.</p></div>
  <p className="studio-note">Twelve original fictional documents, seven authored source families. Two manuals are shared with incident-017. {lineageOrigin.rights} This experience constructs data and masks; it does not train or evaluate a language model.</p>
  <PortableExperiment storageKey="ai-atlas.data-lineage.v1" serialize={()=>encodeLineageRecord(input,__ATLAS_BUILD__.contentSha256)} restore={raw=>{const restored=readLineageRecord(raw);setInput(restored.input);setBlock(0);setAttentionRow(0);return restored.sourceContent===__ATLAS_BUILD__.contentSha256?'Inputs, tokenizer merges, sampler and packed-batch manifest reproduced.':'Compatible construction reproduced from earlier source content; current declared algorithms generated the same manifest.';}}/>
  <div className="studio-layout"><aside className="studio-sidebar"><h4>Construction rules</h4><label>Unit assigned to a split<select value={input.splitStrategy} onChange={e=>change({splitStrategy:e.target.value as LineageInput['splitStrategy']})}><option value="family">Whole source family</option><option value="document">Individual document · leakage challenge</option></select></label><Control label="Split seed" value={input.splitSeed} min={1} max={999} onChange={splitSeed=>change({splitSeed})}/><p>Shuffle the original family IDs or document IDs first. Assign floor(60%) to training, floor(20%) to development (at least one unit), and the rest to evaluation. Family proportions do not imply equal document counts.</p>
   <label>Text transformation after splitting<select value={input.normalization} onChange={e=>change({normalization:e.target.value as LineageInput['normalization']})}><option value="verbatim">Keep exact text</option><option value="whitespace">Trim and collapse whitespace</option><option value="lowercase">Collapse whitespace and lowercase</option></select></label><label className="studio-check"><input type="checkbox" checked={input.deduplicateTraining} onChange={e=>change({deduplicateTraining:e.target.checked})}/> Exclude repeated exact training pairs</label><p>Keep the first prompt/response pair in original document order. Evaluation data remain visible. Case and whitespace changes are lossy transformations, not universally harmless cleaning.</p>
   <Control label="Maximum learned BPE merges" value={input.merges} min={0} max={40} onChange={merges=>change({merges})}/><p>All 256 byte symbols exist before training. Only adjacent-pair merges learn from these retained training fields. Merges never cross prompt/response or document boundaries.</p>
   <h4>Reconstruct the sampler</h4><Control label="Sampling seed" value={input.sampleSeed} min={1} max={999} onChange={sampleSeed=>change({sampleSeed})}/><Control label="Global document cursor" value={input.cursor} min={0} max={1000} onChange={cursor=>change({cursor})}/><Control label="Documents sampled for this batch" value={input.batchDocuments} min={1} max={4} onChange={batchDocuments=>change({batchDocuments})}/><button disabled={input.cursor+input.batchDocuments>1000} onClick={()=>change({cursor:input.cursor+input.batchDocuments})}>Advance by this document batch</button><p>Each epoch shuffles all eligible training documents without replacement. Crossing an epoch boundary can revisit a document. Sampling starts over only when the explicit seed/cursor changes.</p>
   <label>Packed block length<select value={input.blockSize} onChange={e=>change({blockSize:Number(e.target.value)})}>{[16,32,64].map(n=><option key={n} value={n}>{n} input tokens</option>)}</select></label><label>Loss target selection<select value={input.objective} onChange={e=>change({objective:e.target.value as LineageInput['objective']})}><option value="all-targets">All within-document next tokens</option><option value="response-only">Response tokens and EOS only</option></select></label>
  </aside><div className="studio-main"><Metrics items={[["Retained training documents",`${eligible.length} / ${result.documents.filter(d=>d.split==='train').length}`],["Cross-split flagged pairs",String(cross.length)],["Learned merges / vocabulary",`${result.tokenizer.merges.length} / ${result.tokenizer.tokenBytes.length}`],["Actual sampled content tokens",String(result.packing.realTokens)],["Padding slots",`${result.packing.paddingTokens} / ${result.packing.totalSlots}`],["Active shifted targets",String(result.packing.trainedTargets)]]}/>
   <h4>1. Read the original source family</h4><label>Document to inspect<select value={documentId} onChange={e=>setDocumentId(e.target.value)}>{result.documents.map(d=><option key={d.id} value={d.id}>{d.id} · {d.split}</option>)}</select></label><p><strong>{source.familyId}</strong> · {source.variant} · source {source.sourceId} · {source.split}. {source.excludedFromTraining?`Excluded from fitting/sampling as an exact repeat of ${source.duplicateOf}.`:'Retained in its assigned split.'}</p><div className="lineage-text-pair"><div><h5>Original prompt / response</h5><pre>{JSON.stringify(source.prompt)}{'\n'}{JSON.stringify(source.response)}</pre></div><div><h5>Transformed prompt / response</h5><pre>{JSON.stringify(source.normalizedPrompt)}{'\n'}{JSON.stringify(source.normalizedResponse)}</pre></div></div><p>Split membership uses the original family/document identity; normalization did not decide it. {lineageOrigin.families}</p>
   <h4>2. Observe split leakage and duplicate evidence</h4><p>This {input.splitStrategy==='family'?'family':'document'} split has {cross.length} flagged pairs across splits. The same seed and transformation with {input.splitStrategy==='family'?'individual document':'whole-family'} assignment has {alternateCross.length}. A flag is an observable data relationship, not a measured effect on a model’s score.</p><div className="studio-table-wrap" role="region" aria-label="Duplicate and family relationships" tabIndex={0}><table className="studio-table"><thead><tr><th>Document pair</th><th>Evidence</th><th>3-word shingle Jaccard</th><th>Split boundary</th></tr></thead><tbody>{result.duplicates.map(p=><tr key={p.left+':'+p.right}><th>{p.left}<br/>{p.right}</th><td>{[p.family?'same source family':'',p.exact?'exact transformed pair':'',p.near?'near pair ≥ 0.5':''].filter(Boolean).join('; ')}</td><td>{number(p.jaccard,3)}</td><td>{p.crossSplit?`Crosses ${p.splits.join(' / ')}`:`Same ${p.splits[0]} split`}</td></tr>)}</tbody></table></div><p>Exact matching compares both transformed fields. Near matching uses set Jaccard overlap of contiguous three-word shingles, with a declared 0.5 threshold and case sensitivity inherited from the transformation. It is not semantic equivalence. Grouping known families does not guarantee that unrecognized related sources are absent.</p>
   <h4>3. Inspect encoded boundaries and target shifting</h4><p>Tokenizer {result.tokenizer.checksum}: {encoded.promptTokenCount} prompt tokens, {encoded.responseTokenCount} response tokens, plus BOS/SEP/EOS. Full content-byte decoding reconstructs each transformed field exactly. A byte token may be only part of a Unicode character; such tokens display their hexadecimal bytes.</p><div className="lineage-token-list" aria-label="Encoded document with loss targets">{encoded.tokens.map((id,i)=><div key={i}><small>position {i} · ID {id}</small><code>{displayBpeToken(id,result.tokenizer)}</code><span>{encoded.sections[i]}</span><span>{i<encoded.tokens.length-1?`next-target response mask: ${encoded.responseMask[i]}`:'No next target in this document'}</span></div>)}</div><Details title="Check the decoded field bytes"><pre>{decodeByteBpe(encoded.tokens.slice(1,1+encoded.promptTokenCount),result.tokenizer)}{'\n'}{decodeByteBpe(encoded.tokens.slice(encoded.promptTokenCount+2,-1),result.tokenizer)}</pre><p>BOS, SEP, EOS and PAD are structural IDs 1, 3, 2 and 0. Literal text such as “&lt;eos&gt;” still encodes as content bytes; it cannot inject a structural boundary.</p></Details>
   <h4>4. Read the actual sampled document indices</h4><div className="studio-table-wrap" role="region" aria-label="Deterministic document sampler" tabIndex={0}><table className="studio-table"><thead><tr><th>Global cursor</th><th>Epoch / position</th><th>Document</th><th>Independent packed instance</th></tr></thead><tbody>{result.draws.map(d=><tr key={d.instanceId}><td>{d.globalCursor}</td><td>{d.epoch} / {d.positionInEpoch}</td><td>{d.documentId}</td><td>{d.instanceId}</td></tr>)}</tbody></table></div>
   <h4>5. Inspect one packed block</h4><Stepper value={Math.min(block,result.packing.blocks.length-1)} max={result.packing.blocks.length-1} onChange={v=>{setBlock(v);setAttentionRow(0);}} label="Packed block"/><p>Slots concatenate the sampled documents in order. The last block pads with ID 0. A document can continue into the next block, but this specimen does not carry its previous-block attention context. Position IDs retain original document offsets. {result.packing.crossBlockTargets} active labels cross a block boundary while remaining inside the same document.</p><div className="studio-table-wrap" role="region" aria-label="Packed inputs and shifted targets" tabIndex={0}><table className="studio-table"><thead><tr><th>Slot / stream index</th><th>Document / position</th><th>Input token</th><th>Next target / position</th><th>Loss mask</th><th>Inspect attention</th></tr></thead><tbody>{packed.map(x=><tr key={x.slot}><th>{x.slot} / {x.globalIndex??'padding'}</th><td>{x.documentId??'none'} / {x.documentPosition??'—'}</td><td><code>{displayBpeToken(x.token,result.tokenizer)}</code></td><td><code>{displayBpeToken(x.target,result.tokenizer)}</code> / {x.targetPosition??'none'}</td><td>{x.lossMask}</td><td><button aria-pressed={x.slot===attentionRow} onClick={()=>setAttentionRow(x.slot)}>Row {x.slot}</button></td></tr>)}</tbody></table></div><p>EOS never trains the next document’s BOS. Prompt targets are masked only in response-only mode. A shifted target may sit just beyond the input block; it is a training label, never future context available to that block.</p>
   <div className="lineage-attention"><h5>Attention row {selected.slot} · {selected.instanceId??'padding'}</h5><p>Allowed keys: {selected.attentionAllowed.length?selected.attentionAllowed.join(', '):'none'}. Both the causal order and sampled-document instance must match. All future, other-document and padding keys are blocked.</p><div aria-label={`Allowed key slots for query slot ${selected.slot}`}>{packed.map(key=><span key={key.slot} className={selected.attentionAllowed.includes(key.slot)?'allowed':'blocked'} title={`Key ${key.slot}: ${selected.attentionAllowed.includes(key.slot)?'allowed':'blocked'}`}>{key.slot}</span>)}</div></div>
  </div></div>
  <Details title="Every split assignment and fitting decision"><div className="studio-table-wrap" role="region" aria-label="Corpus split manifest" tabIndex={0}><table className="studio-table"><thead><tr><th>Original document</th><th>Source family</th><th>Split</th><th>Tokenizer / sampler eligibility</th></tr></thead><tbody>{result.documents.map(d=><tr key={d.id}><th>{d.id}</th><td>{d.familyId}</td><td>{d.split}</td><td>{d.excludedFromTraining?`Excluded exact copy of ${d.duplicateOf}`:d.split==='train'?'Used in tokenizer fit and sampler':'Encoding only; never used in fitting'}</td></tr>)}</tbody></table></div></Details>
  <Details title="Actual merge-training trace"><p>Count adjacent pairs inside every retained training field. Choose the greatest count, breaking ties by numeric left then right ID. Replace non-overlapping occurrences left to right. Adjacent counts can exceed replacement applications for overlapping pairs such as “aaa”. Stop at the configured budget or when no pair repeats. This whole-field byte variant has no linguistic word pre-tokenizer and can merge across spaces within a field.</p><p>Fitting fields: {result.tokenizer.trainingFieldIds.join(', ')}. The byte inventory is fixed before this corpus; evaluation characters do not enlarge a learned alphabet.</p><div className="studio-table-wrap" role="region" aria-label="Learned byte-pair merges" tabIndex={0}><table className="studio-table"><thead><tr><th>New ID</th><th>Left + right</th><th>Bytes / displayed token</th><th>Pair count</th><th>Applied merges</th></tr></thead><tbody>{result.tokenizer.merges.map(m=><tr key={m.id}><th>{m.id}</th><td>{m.left} + {m.right}</td><td><code>{displayBpeToken(m.id,result.tokenizer)}</code><br/>{m.bytes.join(' ')}</td><td>{m.pairCount}</td><td>{m.applications}</td></tr>)}</tbody></table></div></Details>
  <Details title="Reconstructible construction manifest"><pre className="studio-readout">{JSON.stringify(result.manifest,null,2)}</pre><p>Save/export records include this computed manifest. Restore recomputes and checks corpus identity, split membership, exclusions, merge order, sampled instances and packed-block checksums. Checksums detect mismatches; they are not cryptographic signatures or evidence of consent/licensing.</p></Details>
  <Details title="Connect to the actual nine-token lifecycle corpus"><p>The separate lifecycle model uses <code>{lifecycleTokenizerVersion}</code>, a fixed whitespace vocabulary: {lifecycleVocabulary.join(', ')}. It performs no BPE training. These actual lifecycle fields are read from its existing corpus; this experience does not alter its vocabulary, weights or context-length contract.</p><pre>{lifecycle.text}{'\n'}token IDs: {JSON.stringify(lifecycle.tokens)}{'\n'}shifted response mask: {JSON.stringify(lifecycle.mask)}{'\n'}family: {lifecycle.familyId} · {lifecycle.split} · {lifecycle.domain}</pre><p>In both representations, predict token j+1 from input position j. A response-only mask selects the answer and EOS; it does not erase the prompt from causal context.</p></Details>
  <div className="studio-task"><h4>Predict a data boundary before observing it</h4><p>Keep the seed fixed and switch from families to individual documents. Find one exact evaluation duplicate of training data. Then change whitespace normalization and predict whether the spacing variant becomes an exact match. Increase merge count and inspect what changes in token IDs, sequence length, padding and masks. Finally advance the sampler and use the saved cursor to reconstruct that exact batch.</p></div>
  {onSelect&&<div className="lineage-actions">{[['training-data','Training data and provenance'],['dataset-human-judgment-lineage','Human judgment and lineage'],['tokenizer','Tokenization'],['evaluation','Evaluation boundaries'],['loss-optimizer','Masked training targets']].map(([id,label])=><button key={id} onClick={()=>onSelect(id)}>{label} →</button>)}</div>}
  <SourceLinks items={[{title:'Sennrich et al. · iterative pair merging, §3.2',url:'https://arxiv.org/html/1508.07909v5'},{title:'Lee et al. · duplicates and train/test overlap',url:'https://arxiv.org/abs/2107.06499'},{title:'scikit-learn · split units are groups rather than samples',url:'https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GroupShuffleSplit.html'},{title:'NVIDIA Megatron Bridge 0.3.1 · preserving packed sequence boundaries',url:'https://docs.nvidia.com/nemo/megatron-bridge/0.3.1/training/packed-sequences.html'}]}/>
 </section>;
}
