import {useMemo,useRef,useState} from 'react';
import {buildDecoderProjection,decoderProjectionDefaults,decoderProjectionExamples,decoderProjectionLimits,decoderProjectionModels,readDecoderProjection,sampleDecoderProjection,serializeDecoderProjection,type DecoderProjectionSelection} from '../lib/decoder-projection';
import {createLifecycleRun,type LifecycleRun} from '../lib/model-lifecycle';
import {createLifecycleExposureJournal} from '../lib/model-lifecycle-workspace';
import {Metrics,Stepper,Details,SourceLinks} from './studio-primitives';
import PortableExperiment from './portable-experiment';
import {Equation} from './equation';
import './decoder-projection.css';
const fmt=(v:number)=>v===0?'0':Math.abs(v)<.0001?v.toExponential(3):v.toLocaleString('en-US',{maximumFractionDigits:5});
function MatrixView({matrix,label,columns,rows,integer=false}:{matrix:number[][];label:string;columns?:string[];rows?:string[];integer?:boolean}){return <figure className="projection-matrix"><figcaption>{label}</figcaption><div className="projection-scroll" tabIndex={0} role="region" aria-label={label}><table><thead><tr><th scope="col">Index</th>{matrix[0].map((_,j)=><th scope="col" key={j}>{columns?.[j]??j}</th>)}</tr></thead><tbody>{matrix.map((row,i)=><tr key={i}><th scope="row">{rows?.[i]??i}</th>{row.map((x,j)=><td key={j} title={String(x)}>{integer?x:fmt(x)}</td>)}</tr>)}</tbody></table></div></figure>;}
export default function DecoderProjection({checkpoint,onSelect}:{checkpoint?:LifecycleRun;onSelect?:(id:string)=>void}){
 const [journal]=useState(()=>{try{return createLifecycleExposureJournal(localStorage);}catch{return createLifecycleExposureJournal();}}),[seed]=useState(()=>createLifecycleRun()),[localSource,setLocalSource]=useState<LifecycleRun|null>(null),[useSeed,setUseSeed]=useState(false),[selection,setSelection]=useState<DecoderProjectionSelection>(decoderProjectionDefaults),[eventIndex,setEventIndex]=useState(0),[cell,setCell]=useState(0),[notice,setNotice]=useState('');
 const source=useMemo(()=>journal.retain(localSource??(!useSeed&&checkpoint?checkpoint:seed)),[checkpoint,journal,localSource,seed,useSeed]),result=useMemo(()=>buildDecoderProjection(source,selection),[source,selection]),cursor=sampleDecoderProjection(result,Math.min(eventIndex,result.events.length-1)),tile=result.tiles[cursor.event.tile??1],row=Math.floor(cell/3),column=cell%3,revision=useRef(0),sourceRef=useRef(source),file=useRef<HTMLInputElement>(null);sourceRef.current=source;
 const change=(patch:Partial<DecoderProjectionSelection>)=>{revision.current++;setSelection(x=>({...x,...patch}));setEventIndex(0);};
 const restore=(raw:string)=>{const candidate=readDecoderProjection(raw);revision.current++;setLocalSource(journal.retain(candidate.checkpoint));setSelection(candidate.selection);setEventIndex(0);return 'Restored the complete source checkpoint and selection. The machine trace and projection error were recomputed.';};
 const examples=useMemo(decoderProjectionExamples,[]),current=cursor.event.machineEvent,activeTransactions=current?tile.machine.transactions.filter(t=>t.submittedNs<=current.timeNs&&t.completedNs>current.timeNs):[];
 return <section className="decoder-projection studio-panel" aria-labelledby="decoder-projection-heading">
  <header><p className="studio-kicker">Learned operator → explicit precision conversion → mapped machine work</p><h3 id="decoder-projection-heading">Follow a decoder query into the machine</h3><p>Carry real checkpoint values into one selected query projection. Six inner coordinates become two 3 × 3 products. Inspect the integer words that arrive, then compare their rescaled sum with the decoder’s original floating-point result.</p></header>
  <div className="projection-source"><strong>{localSource?'Restored complete checkpoint':!useSeed&&checkpoint?'Carried learning checkpoint':'Declared seed 7 · initialized weights'}</strong><p>Weight identity <code>{result.source.weightIdentity}</code> · optimizer step {result.source.optimizerStep} · sampler draws {result.source.dataDraws}. {result.source.optimizerStep===0?'These weights have not been trained.':'These are the supplied checkpoint weights; no training happens in this experience.'} Final-test exposure: {source.finalOpened?'previously opened; disclosure retained':'not opened'}. Only training and development prompts can be selected here.</p><div className="projection-actions">{checkpoint&&<button onClick={()=>{revision.current++;setLocalSource(null);setUseSeed(false);setEventIndex(0);}}>Use carried checkpoint</button>}<button onClick={()=>{revision.current++;setLocalSource(null);setUseSeed(true);setEventIndex(0);}}>Use initialized seed 7</button></div></div>
  <div className="projection-controls"><label>Prompt specimen<select value={selection.exampleId} onChange={e=>change({exampleId:e.target.value})}>{examples.map(ex=><option value={ex.id} key={ex.id}>{ex.split} · {ex.familyId}</option>)}</select></label><label>Maximum integer magnitude<select value={selection.quantizationMax} onChange={e=>change({quantizationMax:Number(e.target.value) as DecoderProjectionSelection['quantizationMax']})}>{[7,31,99].map(n=><option key={n} value={n}>−{n} to +{n}</option>)}</select></label><label>Bank placement<select value={selection.bankPlacement} onChange={e=>change({bankPlacement:e.target.value as DecoderProjectionSelection['bankPlacement']})}><option value="same-bank">A / B start in the same bank</option><option value="split-banks">A / B start in different banks</option></select></label><label>Staging slots<select value={selection.buffers} onChange={e=>change({buffers:Number(e.target.value) as 1|2})}><option value="1">1 · serialize slot reuse</option><option value="2">2 · permit safe overlap</option></select></label><label>Assumed refresh due interval<select value={selection.refreshEveryNs} onChange={e=>change({refreshEveryNs:Number(e.target.value) as DecoderProjectionSelection['refreshEveryNs']})}>{[0,64,96,160].map(n=><option key={n} value={n}>{n===0?'Disabled counterfactual':`${n} ns`}</option>)}</select></label><label>Injected mapping fault<select value={selection.fault} onChange={e=>change({fault:e.target.value as DecoderProjectionSelection['fault']})}><option value="none">Both tiles mapped</option><option value="unmapped-second-tile">Second tile B is unmapped</option></select></label></div>
  <p>Prompt: <code>{result.source.promptWords.join(' ')}</code>. Selected positions 0–2: <code>{result.source.promptWords.slice(0,3).join(' ')}</code>. The first three output channels are selected; every inner coordinate 0–5 still contributes. A shorter displayed matrix does not mean a shorter inner product.</p>
  <h4>First preserve shape and meaning</h4><p>The full query operator has shape {result.source.originalShape[0]} × 6 times 6 × 6. This slice is 3 × 6 times 6 × 3, producing 3 × 3. Its learned weights and activations are dimensionless numerical coordinates, not physical distances.</p>
  <div className="projection-pair"><MatrixView label="X · actual normalized embeddings (3 × 6)" matrix={result.normalized} columns={['k0','k1','k2','k3','k4','k5']} rows={result.source.promptWords.slice(0,3).map((w,i)=>`${i}: ${w}`)}/><MatrixView label="WQ · actual query weight columns (6 × 3)" matrix={result.queryWeights} columns={['q0','q1','q2']} rows={['k0','k1','k2','k3','k4','k5']}/></div>
  <Equation latex={'Q_{0:3,0:3}=X_{0:3,0:3}W_{Q,0:3,0:3}+X_{0:3,3:6}W_{Q,3:6,0:3}'} text="The selected query slice is the sum of two products, partitioned along the six-coordinate inner dimension." variables={[{symbol:'X',meaning:'Actual normalized, position-added token embeddings',unit:'dimensionless'},{symbol:'W_Q',meaning:'Actual checkpoint query projection weights',unit:'dimensionless'},{symbol:'0:3, 3:6',meaning:'Zero-based half-open index ranges: 0,1,2 and 3,4,5',unit:'indices'}]} note="The identity is exact before quantization, apart from the order of floating-point additions. Query projection does not mix token positions. Causal attention masking happens later."/>
  <h4>Then disclose the precision adapter</h4><p>For each operand tile, scale s = maximum absolute value / {selection.quantizationMax}; integer code q = round(x / s), with ties away from zero. The machine reads q as a four-byte signed integer. Rescaling q by s approximates the original value. All-zero tiles use s = 1 and q = 0.</p>
  <div className="projection-tile-summary">{result.tiles.map(t=><button key={t.index} aria-pressed={tile.index===t.index} onClick={()=>setEventIndex(result.events.find(e=>e.tile===t.index)!.index)}><strong>Tile {t.index+1} · k = {t.innerIndices.join(', ')}</strong><span>A scale {fmt(t.a.scale)} · B scale {fmt(t.b.scale)}</span><span>{t.machine.status} · {t.machine.totals.macs} completed MACs</span></button>)}</div>
  <Metrics items={[["Completed integer MACs",`${result.totals.completedMacs} / 54`],["Synthetic machine schedule",`${result.totals.machineScheduleNs} ns`],["Operand transaction reads",`${result.totals.readTransactionBytes} B`],["Output transaction writes",`${result.totals.writeTransactionBytes} B`],["Maximum query-slice error",result.errors?fmt(result.errors.maxAbsolute):'Unavailable · incomplete projection'],["Query-slice RMS error",result.errors?fmt(result.errors.rootMeanSquare):'Unavailable · incomplete projection']]}/>
  <p className="projection-boundary">Two independent machine invocations run sequentially. Their clocks restart at zero; the joined clock adds the second invocation’s offset. Normalization, quantization, initialization, scale transport, rescaling and host addition have no assigned service time here. These ns are neither browser speed nor full decoder latency.</p>
  <h4>Inspect delivery, ownership and accumulation</h4><Stepper value={Math.min(eventIndex,result.events.length-1)} max={result.events.length-1} onChange={setEventIndex} label="Projection event"/>
  <div className="projection-current" aria-live="polite"><strong>{cursor.event.kind==='combine'?'Host combination':`Tile ${(cursor.event.tile??0)+1}`} · joined machine clock {cursor.event.timeNs} ns{cursor.event.machineTimeNs!==null?` · local machine clock ${cursor.event.machineTimeNs} ns`:''}</strong><p>{cursor.event.label}</p><p>{cursor.completedMacs} / 54 integer MACs completed at this event. {cursor.accepted?'Both outputs are complete and the rescaled projection is accepted.':'The displayed rescaled accumulator is a partial preview; it is not an accepted projection output.'}</p></div>
  <div className="projection-triple"><MatrixView label={`Tile ${tile.index+1} · A integer words`} matrix={tile.a.codes} integer/><MatrixView label={`Tile ${tile.index+1} · B integer words`} matrix={tile.b.codes} integer/><MatrixView label={cursor.accepted?'Accepted rescaled sum':'Rescaled running accumulator'} matrix={cursor.partial}/></div>
  {current&&<div className="projection-owners">{current.state.buffers.map(slot=><article key={slot.index}><strong>Slot {slot.index} · {slot.phase}</strong><p>{slot.batchId??'No batch assigned'}</p><p>{Object.keys(slot.words).length} delivered named words currently retained.</p></article>)}<article><strong>Transaction queue / service</strong><p>{activeTransactions.filter(t=>t.serviceStartNs>current.timeNs).length} queued · {activeTransactions.filter(t=>t.serviceStartNs<=current.timeNs).length} in service</p><p>Open rows: {current.state.openRows.map((r,i)=>`bank ${i}: ${r??'closed'}`).join('; ')}. Output owner: {current.state.outputOwner}.</p></article></div>}
  <h4>Check one actual output coordinate</h4><label className="projection-cell">Selected query entry<select value={cell} onChange={e=>setCell(Number(e.target.value))}>{Array.from({length:9},(_,i)=><option key={i} value={i}>position {Math.floor(i/3)}, channel {i%3}</option>)}</select></label>
  <div className="projection-scroll" tabIndex={0} role="region" aria-label="Six inner-coordinate products"><table><thead><tr><th>Inner k</th><th>Actual X</th><th>Actual WQ</th><th>Integer product</th><th>Rescaled term</th></tr></thead><tbody>{Array.from({length:6},(_,k)=>{const t=result.tiles[Math.floor(k/3)],local=k%3;return <tr key={k}><th scope="row">{k} · tile {t.index+1}</th><td>{fmt(result.normalized[row][k])}</td><td>{fmt(result.queryWeights[k][column])}</td><td>{t.a.codes[row][local]} × {t.b.codes[local][column]}</td><td>{fmt(t.a.codes[row][local]*t.b.codes[local][column]*t.a.scale*t.b.scale)}</td></tr>;})}</tbody></table></div><p>These six terms explain the intended quantized calculation. The accepted result below comes from completed machine outputs, not from this explanatory table. The machine first accumulates integers per tile and then rescales; rounding can differ slightly from rescaling every term separately.</p>
  <div className="projection-pair"><MatrixView label="Actual decoder binary64 query slice · reference" matrix={result.reference}/>{result.output?<MatrixView label="Completed machine outputs · rescaled and summed" matrix={result.output}/>:<div className="projection-blocked"><strong>Complete projection unavailable</strong><p>The second tile cannot read its B mapping. A complete first tile cannot replace the missing inner coordinates.</p></div>}</div>
  <p>{result.errors?`For entry [${row},${column}]: signed error ${fmt(result.errors.signed[row][column])}; operand-quantization absolute bound ${fmt(result.errors.absoluteBound[row][column])}. Relative Frobenius error for these nine entries: ${result.errors.relativeFrobenius===null?'undefined because the reference is all zero':fmt(result.errors.relativeFrobenius)}.`:'Error metrics require both completed tile outputs.'} This measures one query slice. It does not measure answer quality, perplexity or the whole decoder.</p>
  <Details title="Exact word identity and traffic denominators"><p>Selected binary64 operands contain 36 values = {result.totals.selectedOriginalBinary64Bytes} B. Quantized operands contain 36 signed-int32 words = {result.totals.operandLogicalBytes} B, allocated as four padded 48 B buffers = {result.totals.operandAllocatedBytes} B across two separate invocations. Four binary64 scales add {result.totals.scalesBinary64Bytes} B outside machine traffic. There is no packed low-bit format; changing the code range does not change word size. Padding, repeated reads and output writes are separate quantities.</p><p>Addresses below belong to the selected tile’s independent machine address space. A is the normalized activation; B carries the listed original query-weight index. Four bytes are shown in little-endian order; mapped status comes from the actual machine mapping.</p><div className="projection-scroll" tabIndex={0} role="region" aria-label="Selected tile word identity"><table><thead><tr><th>Word</th><th>Original coordinate</th><th>Integer</th><th>Bytes (hex)</th><th>IOVA → physical</th><th>Mapped</th></tr></thead><tbody>{tile.words.concat(tile.outputWords).map(w=><tr key={`${w.tensor}-${w.row}-${w.column}`}><th scope="row">{w.tensor}[{w.row},{w.column}]</th><td>{w.tensor==='A'?'X':w.tensor==='B'?'WQ':'tile output'}[{w.sourceRow},{w.sourceColumn}]{w.weightIndex!==null?` · weight ${w.weightIndex}`:''}</td><td>{w.value}</td><td><code>{w.bytes.map(b=>b.toString(16).padStart(2,'0')).join(' ')}</code></td><td>{w.iova} → {w.physical}</td><td>{tile.machine.mappings.find(m=>m.tensor===w.tensor)?.mapped?'yes':'no'}</td></tr>)}</tbody></table></div><p>C rows are completed final integer tile outputs when available, independent of the inspection cursor. They are not the binary64 rescaled projection. Original checkpoint JSON size is unrelated to these declared numerical payload sizes.</p></Details>
  <Details title="Full event trace"><div className="projection-scroll projection-events" tabIndex={0} role="region" aria-label="Projection event trace"><table><thead><tr><th>Joined ns</th><th>Tile-local ns</th><th>Event</th><th>Inspect</th></tr></thead><tbody>{result.events.map(e=><tr key={e.index}><td>{e.timeNs}</td><td>{e.machineTimeNs??'excluded host work'}</td><td>{e.label}</td><td><button onClick={()=>setEventIndex(e.index)}>Here</button></td></tr>)}</tbody></table></div></Details>
  <div className="projection-task"><h4>Predict → trace → explain</h4><p>Lower the integer range and inspect the changed codes and query error. Predict which bytes change and why the transaction count stays fixed. Change bank placement or staging slots: check that the accepted numerical result stays the same while its synthetic schedule may change. Finally remove the second B mapping and identify the exact missing inner coordinates.</p></div>
  <PortableExperiment storageKey="atlas-decoder-query-machine-1" maxRecordBytes={decoderProjectionLimits.maxRecordBytes} serialize={()=>serializeDecoderProjection(journal.retain(source),selection)} restore={restore}/><div className="projection-actions"><button onClick={()=>file.current?.click()}>Import complete projection workspace file</button><input hidden type="file" ref={file} accept=".json,application/json" onChange={async e=>{const selected=e.target.files?.[0],atRevision=revision.current,atSource=sourceRef.current;e.target.value='';if(!selected)return;try{if(selected.size>decoderProjectionLimits.maxRecordBytes)throw Error('Workspace exceeds 650,000 bytes.');const raw=await selected.text();if(atRevision!==revision.current||atSource!==sourceRef.current)throw Error('Source or selection changed during file read; choose the file again.');setNotice(restore(raw));}catch(error){setNotice(`Import rejected: ${error instanceof Error?error.message:'invalid file'}. Current source and selection remain unchanged.`);}}}/></div><p role="status">{notice}</p><p>Saved and exported workspaces include the full source checkpoint and selection. Use file import for large records; the shared text-entry field is limited to 20,000 characters. Restores recompute results and retain prior final-test exposure.</p>
  <Details title="Sources, masks and model boundaries"><ul>{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul><p>The source’s response-only shifted loss mask is [{result.source.responseLossMask.join(', ')}], including response and end-token targets. It is shown for orientation and is not applied to this projection. The original decoder and machine models remain separately versioned.</p><SourceLinks items={[{title:'Zhang & Sennrich · Root Mean Square Layer Normalization (2019), abstract',url:'https://arxiv.org/abs/1910.07467'},{title:'Jacob et al. · Quantization and Training of Neural Networks (2017), §§2.1–2.2',url:'https://arxiv.org/html/1712.05877v1#S2.SS1'}]}/><p>The papers motivate RMS rescaling and scale-aware integer products. This specimen uses the existing toy decoder’s precise normalization and an authored symmetric per-tile adapter. It does not reproduce the paper’s full affine integer-only inference pipeline, calibration, training scheme or performance results.</p><code>{JSON.stringify(decoderProjectionModels)}</code></Details>
  <nav className="projection-actions" aria-label="Related projection lessons">{[['embedding','Token embeddings'],['attention','Query and attention'],['kernel-locality-fusion','Kernel locality'],['hbm-controller','Memory controller']].map(([id,label])=><button key={id} disabled={!onSelect} onClick={()=>onSelect?.(id)}>{label}</button>)}</nav>
 </section>;
}
