import {useState} from 'react';
import NumericWorkbench from './numeric-workbench';
import {numericLabs,isNumericLab} from '../lib/numeric-labs';
import {Button} from './ui/button';
import {Slider} from './ui/slider';
import * as M from '../lib/deep-math';
import {referenceSystem} from '../lib/reference-system';
import {Equation} from './equation';
import labEquations from '../lib/data/lab-equations.json';
type Field=[string,string,number,number,number,string];
type Lab={id:string;name:string;title:string;intro:string;fields:Field[];formula:string;limits:string;source:string};
export const deepLabs:Lab[]=[
 {id:'wafer',name:'Wafer yield',title:'From wafer area to good dies',intro:'Separate geometric die sites from random-defect survival. Compare Poisson and clustered-defect assumptions.',fields:[['diameter','Wafer diameter',100,300,50,'mm'],['edge','Edge exclusion',0,10,1,'mm'],['die','Die area',20,1000,20,'mm²'],['defects','Defect density',0,1,.02,'defects/cm²']],formula:'Y = exp(−A × D); clustered Y = (1 + AD/α)^(−α), α = 3',limits:'Area is converted from mm² to cm². Gross-die count is an edge-loss approximation, not an exact reticle layout. Parametric loss, scribe lanes, redundancy and defect correlation across layers require richer models.',source:'https://arxiv.org/abs/2203.12268'},
 {id:'pattern',name:'Patterning',title:'Resolution and the focus budget',intro:'Change wavelength and numerical aperture while holding illustrative process factors fixed.',fields:[['wavelength','Exposure wavelength',13.5,193,.5,'nm'],['na','Numerical aperture',.25,1.35,.01,'']],formula:'Resolution ≈ k₁ λ/NA; depth of focus ≈ k₂ λ/NA²',limits:'k₁ = 0.4 and k₂ = 0.5 are illustrative. Arbitrary wavelength/NA combinations are mathematical scenarios, not available tool configurations. This does not predict stochastic defects or a production exposure window.',source:'https://www.asml.com/en/technology/lithography-principles/rayleigh-criterion'},
 {id:'cmp',name:'CMP',title:'An average surface can hide local overpolish',intro:'Track the nominal site and two local removal-rate extremes through the same polish time.',fields:[['film','Starting film',100,1500,25,'nm'],['removal','Nominal removal rate',20,400,10,'nm/min'],['polish','Polish time',0,8,.1,'min'],['variation','Relative rate variation',0,.4,.01,'fraction']],formula:'Remaining thickness = max(0, initial thickness − rate × time)',limits:'Constant-rate illustration. Local topography, selectivity, dishing and erosion need pattern/material-dependent models; the envelope is not a qualified bonding specification.',source:'https://www.imec-int.com/en/articles/wafer-wafer-hybrid-bonding-pushing-boundaries-400nm-interconnect-pitch'},
 {id:'assembly',name:'Assembly yield',title:'Where screened parts become finished assemblies',intro:'Start with already screened incoming sets. Observe only the additional assembly and final-test losses.',fields:[['incoming','Screened input sets',100,10000,100,'sets'],['bondYield','Yield per assembly stage',.8,1,.005,'fraction'],['stages','Assembly stages',1,12,1,''],['finalYield','Final test yield',.8,1,.005,'fraction']],formula:'Finished assemblies = incoming sets × stage yield^stages × final yield',limits:'Independent equal stage yields, no rework. Raw die yield has already been accounted for before the screened input. Final counts are expected values rather than guaranteed integer output.',source:'https://arxiv.org/abs/2203.12268'},
 {id:'hbm',name:'HBM intensity',title:'Choose the denominator before multiplying',intro:'Compare geometric area per bit with empirical wafer supply per output bit. The empirical ratio already describes output.',fields:[['bits','Target output',1,20,1,'normalized bit units'],['relative','Illustrative relative intensity',1,5,.1,'×'],['stackYield','Additional stack yield',.5,1,.01,'fraction']],formula:'Geometric method: output × area ratio / yield. Empirical method: output × wafer-supply ratio.',limits:'The default ratio is synthetic, not Micron’s reported HBM3E comparison. Apply an extra yield penalty only if the original intensity excludes that loss. Stack height, package footprint and delivered bits are separate quantities.',source:'https://www.micron.com/products/memory/hbm/hbm3e'},
 {id:'capacity',name:'Capacity & queues',title:'Two supply streams, one package output',intro:'Logic dies and HBM stacks converge with interposers and substrates. A second view adds qualification, ramp time and demand backlog.',fields:[['logic','Known-good logic dies',0,24000,500,'dies/month'],['hbm','Known-good HBM stacks',0,120000,2000,'stacks/month'],['interposers','Ready interposers',0,16000,500,'units/month'],['substrates','Ready substrates',0,16000,500,'units/month'],['assemblyRate','Assembly starts',0,16000,500,'packages/month'],['yield','Final assembly yield',.5,1,.01,'fraction'],['qualification','Qualification release month',1,9,1,'month'],['ramp','Ramp duration',1,6,1,'months'],['demand','New demand',0,16000,500,'packages/month']],formula:'Good packages/month = final yield × min(component rates normalized to packages/month)',limits:'Illustrative package: 2 logic dies, 8 HBM stacks, 1 interposer and 1 substrate. One equivalent logic type; heterogeneous designs need separate die-type limits. The ramp mode is a synthetic 12-month scenario with no pre-release production, not a foundry queue forecast.',source:'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm'},
 {id:'dataflow',name:'Dataflow',title:'Reuse changes the traffic, not the answer',intro:'Compare an unblocked square matrix product with a simple tiled-memory model under identical arithmetic.',fields:[['n','Matrix width',64,4096,64,'elements'],['tile','Tile width',8,256,8,'elements']],formula:'Work ≈ 2n³ FLOP; tiled external traffic ≈ (2n³/t + n²) × bytes/element',limits:'Two bytes per input/output element in this idealized traffic model. Accumulator representation and store traffic differ in real kernels. An overwrite GEMM writes each output once in both models. Ceil(n/t) accounts for partial tiles; cache behavior, alignment and accumulator storage are omitted.',source:'https://docs.nvidia.com/cutlass/latest/media/docs/cpp/efficient_gemm.html'},
 {id:'footprint',name:'Model memory',title:'Weights and KV state compete for capacity',intro:'Keep parameter storage, cached context and training optimizer state in separate accounts.',fields:[['params','Parameters',1,200,1,'billion'],['weightBits','Weight precision',4,32,4,'bits'],['batch','Concurrent sequences',1,64,1,''],['context','Context length',1024,131072,1024,'tokens'],['layers','Layers',8,128,8,''],['kvHeads','KV heads',1,32,1,'']],formula:'Weights = parameters × bits/8; KV = 2 × batch × layers × tokens × KV heads × head width × bytes',limits:'Head width 128 and 2-byte KV. A separate training scenario adds 12 bytes/parameter for FP32 master weights and two optimizer moments. Activations, gradients, fragmentation and temporary workspaces are excluded, so displayed totals are partial budgets.',source:'https://arxiv.org/abs/2309.06180'},
 {id:'network',name:'Collectives',title:'Communication has a payload and a startup cost',intro:'A ring all-reduce exchanges blocks in reduction and gathering phases.',fields:[['payload','Payload per rank',.1,16,.1,'GB'],['ranks','Participating ranks',1,256,1,''],['bandwidth','Effective link bandwidth',10,400,10,'GB/s'],['latency','Per-step latency',1,50,1,'μs']],formula:'Time ≈ 2(p−1)/p × message bytes / bandwidth + 2(p−1) × latency',limits:'Decimal GB. Homogeneous ideal ring, with stated effective bandwidth; no congestion, hierarchy or computation overlap. Hardware topology and collective implementation can change this bound.',source:'https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html'},
 {id:'hall',name:'Hall → useful work',title:'Power capacity must meet operating readiness',intro:'Convert a facility power budget into powered racks, then apply explicit readiness and utilization assumptions.',fields:[['facility','Facility power',1,200,1,'MW'],['pue','PUE',1,2,.02,''],['rackPower','IT power per rack',20,200,5,'kW'],['ready','Ready fraction',0,1,.05,'fraction'],['utilization','Workload utilization',0,1,.05,'fraction'],['rate','Synthetic throughput per active rack',100,20000,100,'tokens/s']],formula:'IT MW = facility MW/PUE; work rate = ready racks × utilization × workload-specific rate',limits:'The token rate is a user-controlled synthetic workload assumption, not a conversion constant or hardware benchmark. Fixed rack power is a planning simplification. Quality, context, batching and latency targets must be fixed for real comparisons.',source:'https://www.iea.org/reports/key-questions-on-energy-and-ai'},
 {id:'orbital',name:'Orbital budgets',title:'Close energy, heat and data budgets together',intro:'Specify a payload and test its radiator, solar collection, eclipse storage and communications needs.',fields:[['payloadKW','Payload power',1,1000,5,'kW'],['temperature','Radiator temperature',250,400,5,'K'],['emissivity','Emissivity',.5,.95,.01,''],['absorbed','Absorbed environmental heat',0,300,10,'W/m²'],['sun','Sunlit orbit fraction',.5,1,.02,'fraction'],['solarEfficiency','Solar efficiency',.15,.4,.01,'fraction'],['link','Link rate',1,200,1,'Gbit/s'],['duty','Link duty fraction',.01,1,.01,'fraction'],['dataTB','Required daily transfer',1,1000,5,'TB/day'],['altitude','Altitude',300,1500,50,'km']],formula:'Net radiator flux = εσT⁴ − absorbed flux; area = power/net flux; daily bytes = link rate × contact time/8',limits:'Ideal emitting surface, explicit absorbed flux, no deployed structure/view-factor penalties. Solar irradiance 1,361 W/m²; storage round-trip efficiency 0.85; illustrative 90-minute orbit for eclipse energy. Link margin excludes protocol/weather loss. Zenith propagation is a geometric lower bound. Radiation hardening, redundancy, launches and replacement remain additional feasibility requirements.',source:'https://www.nasa.gov/smallsat-institute/sst-soa/thermal-control/'},
 {id:'economics',name:'Custom silicon cost',title:'Volume amortizes development; yield changes manufacturing cost',intro:'Explore an illustrative cost model instead of treating a custom chip as a free substitute.',fields:[['nre','Development & masks',10,500,10,'million $'],['software','Software investment',0,300,10,'million $'],['volume','Lifetime volume',10000,2000000,10000,'packages'],['waferPrice','Illustrative wafer cost',2000,30000,1000,'$'],['goodDies','Good dies per wafer',20,1000,20,''],['packageCost','Assembly & test cost',100,5000,100,'$/start'],['packageYield','Package yield',.5,1,.01,'fraction']],formula:'Unit cost = (wafer cost/good dies + assembly cost)/assembly yield + development/lifetime volume',limits:'Synthetic cost inputs, one logic die/package, excluding purchased HBM/other chiplets, board, operation and financing. Enter their cost separately in a real bill of materials. Does not describe foundry contracts or establish a make/buy business case.',source:'https://arxiv.org/abs/2203.12268'},
 {id:'recovery',name:'Reliability',title:'Busy time is not always retained progress',intro:'Checkpoint cost competes with work lost after interruptions. Move the checkpoint interval to see the tradeoff.',fields:[['interval','Checkpoint interval',1,120,1,'min'],['checkpoint','Checkpoint duration',.1,10,.1,'min'],['mtbf','System mean time between failures',1,200,1,'hours'],['restart','Restart duration',0,60,1,'min']],formula:'Approximate overhead = checkpoint time/interval + (interval/2 + restart time)/MTBF',limits:'Rare independent failures, uniform failure position, blocking checkpoints, constant recovery cost. Values near or above 100% overhead invalidate the useful approximation. Correlated failures, asynchronous checkpoints and changing job size require different models.',source:'https://cloud.google.com/blog/products/ai-machine-learning/elastic-training-and-optimized-checkpointing-improve-ml-goodput'},
 {id:'memory-growth',name:'Scaling metrics',title:'Compute, capacity and bandwidth are different curves',intro:'Inspect normalized historical-fit rates separately. The source samples and windows differ; extending the curves is an illustration.',fields:[['years','Illustrative interval',0,10,1,'years']],formula:'Normalized index = reported two-year multiplier^(years/2)',limits:'Gholami et al. Figure 1 reports ~3× compute, ~1.6× DRAM bandwidth and ~1.4× interconnect bandwidth per two years; Figure 2 separately reports ~2× single-GPU memory capacity. Different samples, periods and precision conventions; these are not universal laws or forecasts.',source:'https://arxiv.org/html/2403.14123v1'}
];
const defaults:Record<string,number>={diameter:300,edge:3,die:600,defects:.1,wavelength:13.5,na:.33,film:500,removal:100,polish:3,variation:.15,incoming:1000,bondYield:.98,stages:4,finalYield:.95,bits:4,relative:2.5,stackYield:.8,logic:12000,hbm:40000,interposers:7000,substrates:8000,assemblyRate:6500,yield:.95,qualification:3,ramp:3,demand:4000,n:1024,tile:64,params:70,weightBits:16,batch:8,context:8192,layers:80,kvHeads:8,payload:1,ranks:32,bandwidth:100,latency:5,facility:20,pue:1.2,rackPower:100,ready:.8,utilization:.65,rate:4000,payloadKW:100,temperature:325,emissivity:.9,absorbed:100,sun:.66,solarEfficiency:.3,link:50,duty:.2,dataTB:50,altitude:650,nre:100,software:50,volume:100000,waferPrice:15000,goodDies:100,packageCost:1000,packageYield:.9,interval:30,checkpoint:2,mtbf:24,restart:5,years:6};
const fmt=(n:number)=>n.toLocaleString(undefined,{maximumFractionDigits:2});
export default function DeepWorkbench({initial='capacity'}:{initial?:string}){
 const [mode,setMode]=useState(initial),[v,setV]=useState(defaults),[empirical,setEmpirical]=useState(true),[training,setTraining]=useState(false);const lab=deepLabs.find(l=>l.id===mode)!;
 const labTabs=<div className="deep-lab-tabs" aria-label="Engineering labs">{[...deepLabs,...numericLabs].map(l=><Button type="button" key={l.id} variant={mode===l.id?'default':'ghost'} onClick={()=>setMode(l.id)}>{l.name}</Button>)}</div>;
 if(isNumericLab(mode))return <div className="deep-workbench">{labTabs}<NumericWorkbench id={mode}/></div>;
 let results:[string,number|string,string][]=[],bars:{name:string;value:number}[]=[],table:{month:number;produced:number;delivered:number;inventory:number;backlog:number}[]=[];
 if(mode==='wafer'){const r=M.waferYield(v.diameter,v.edge,v.die,v.defects);results=[['Gross die estimate',r.gross,'sites'],['Poisson good dies',r.good,'expected dies'],['Clustered good dies',r.clusteredGood,'expected dies']];bars=[{name:'Poisson survival',value:r.poisson*100},{name:'Clustered survival',value:r.clustered*100}];}
 if(mode==='pattern'){const r=M.patternWindow(v.wavelength,v.na);results=[['Resolution estimate',r.resolutionNm,'nm'],['Depth of focus',r.depthNm,'nm']];}
 if(mode==='cmp'){const r=M.cmpResult(v.film,v.removal,v.polish,v.variation);results=[['Nominal-site residual',r.nominal,'nm'],['Slow local region',r.thick,'nm'],['Fast local region',r.thin,'nm'],['Excess nominal removal',r.overpolish,'nm equivalent removal']];}
 if(mode==='assembly'){const a=M.assemblyYield(v.incoming,v.bondYield,v.stages,v.finalYield);results=[['Finished assemblies',a.at(-1)!,'expected units'],['Lost screened sets',v.incoming-a.at(-1)!,'sets']];bars=a.map((value,i)=>({name:i===0?'Incoming':i===a.length-1?'Final test':`Stage ${i}`,value}));}
 if(mode==='hbm'){results=[['Normalized supply-demand index',M.hbmIntensity(v.bits,v.relative,v.stackYield,empirical?'empirical':'geometric'),'dimensionless index'],['Additional yield factor applied',empirical?'No':'Yes','']];}
 if(mode==='capacity'){const input={logic:v.logic,hbm:v.hbm,interposer:v.interposers,substrate:v.substrates,assembly:v.assemblyRate,logicPer:referenceSystem.package.logicDies,hbmPer:referenceSystem.package.hbmStacks,yield:v.yield};const r=M.packageCapacity(input);results=[['Steady good output',r.good,'packages/month'],['Binding constraint',r.limiting.join(' + '),'']];bars=r.stages.map(x=>({name:x.name,value:x.rate}));table=M.capacityRamp(input,12,v.qualification,v.ramp,v.demand);}
 if(mode==='dataflow'){const r=M.matmulTraffic(v.n,v.tile);results=[['Arithmetic',r.flops/1e9,'GFLOP'],['Unblocked traffic',r.naiveBytes/1e9,'GB'],['Tiled traffic',r.tiledBytes/1e9,'GB'],['Traffic reduction',r.naiveBytes/r.tiledBytes,'×']];}
 if(mode==='footprint'){const r=M.memoryFootprint(v.params,v.weightBits,v.batch,v.layers,v.context,v.kvHeads,128,2,training);results=[['Weights',r.weights/2**30,'GiB'],['KV cache',r.kv/2**30,'GiB'],['Optimizer/master state',r.optimizer/2**30,'GiB'],['Partial total',r.total/2**30,'GiB']];}
 if(mode==='network'){const r=M.ringAllReduce(v.payload*1e9,v.ranks,v.bandwidth,v.latency);results=[['Transferred per rank',r.traffic/1e9,'GB'],['Idealized collective time',r.seconds*1000,'ms']];}
 if(mode==='hall'){const r=M.hallWork(v.facility,v.pue,v.rackPower,v.ready,v.utilization,v.rate);results=[['Available IT power',r.itMW,'MW'],['Power-supported racks',r.racks,'racks'],['Ready racks',r.ready,'racks'],['Illustrative work rate',r.workRate,'tokens/s'],['Facility energy/day',r.dayMWh,'MWh']];}
 if(mode==='orbital'){const r=M.orbitalBudget(v.payloadKW,v.temperature,v.emissivity,v.absorbed,v.sun,v.solarEfficiency,.85,v.link,v.duty,v.dataTB,v.altitude);results=[['Ideal emitting area',r.radiatorM2??'No positive heat-rejection margin','m²'],['Solar collection area',r.solarM2,'m²'],['Eclipse storage energy',r.eclipseKWh,'kWh'],['Link payload bound',r.tbday,'TB/day'],['Link margin',r.linkMargin,'TB/day'],['Zenith one-way propagation',r.zenithMs,'ms']];}
 if(mode==='economics'){const r=M.siliconEconomics(v.nre,v.volume,v.waferPrice,v.goodDies,v.packageCost,v.packageYield,v.software);results=[['Manufacturing per good unit',r.manufacturing,'$'],['Amortized development',r.development,'$/unit'],['Partial unit cost',r.total,'$']];}
 if(mode==='recovery'){const r=M.checkpointWork(v.interval,v.checkpoint,v.mtbf,v.restart);results=[['Approximate overhead',r.overhead*100,'%'],['Retained progress fraction',r.retainedFraction*100,'%']];}
 if(mode==='memory-growth'){bars=[['Peak compute',3],['GPU capacity',2],['DRAM bandwidth',1.6],['Interconnect bandwidth',1.4]].map(([name,n])=>({name:String(name),value:Number(n)**(v.years/2)}));results=bars.map(b=>[b.name,b.value,'× normalized start']);}
 const max=Math.max(1,...bars.map(b=>b.value));
 return <div className="deep-workbench">{labTabs}<h3>{lab.title}</h3><p>{lab.intro}</p><div className="deep-lab-layout"><div>{lab.fields.map(([key,label,min,max,step,unit])=><label className="lab-control" key={key}><span>{label}<strong>{fmt(v[key])} {unit}</strong></span><Slider min={min} max={max} step={step} value={[v[key]]} onValueChange={x=>setV(s=>({...s,[key]:Array.isArray(x)?x[0]:x}))} aria-label={label}/></label>)}{mode==='hbm'&&<Button onClick={()=>setEmpirical(!empirical)} variant="outline">Method: {empirical?'empirical output ratio':'geometric area + yield'}</Button>}{mode==='footprint'&&<Button onClick={()=>setTraining(!training)} variant="outline">{training?'Include optimizer state':'Weights + KV serving view'}</Button>}<Button variant="ghost" onClick={()=>setV(defaults)}>Reset illustrative inputs</Button></div><div aria-live="polite" className="deep-results">{results.map(([label,value,unit])=><div className="deep-result" key={label}><span>{label}</span><strong>{typeof value==='number'?fmt(value):value}</strong><small>{unit}</small></div>)}{bars.length>0&&<div className="bar-comparison">{bars.map(b=><div key={b.name}><span>{b.name}<b>{fmt(b.value)}</b></span><i style={{width:`${100*b.value/max}%`}}/></div>)}</div>}</div></div>{table.length>0&&<div className="data-table-wrap"><table><caption>Illustrative ramp · expected units · no production before qualification</caption><thead><tr>{['Month','Produced','Delivered','Inventory','Backlog'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{table.map(r=><tr key={r.month}><th>{r.month}</th><td>{fmt(r.produced)}</td><td>{fmt(r.delivered)}</td><td>{fmt(r.inventory)}</td><td>{fmt(r.backlog)}</td></tr>)}</tbody></table></div>}<Equation latex={(labEquations as Record<string,string>)[mode]} text={lab.formula}/><p className="lab-assumption">{lab.limits}</p><a className="lab-source" href={lab.source} target="_blank" rel="noreferrer">Method and engineering context ↗</a></div>;
}
