import {useMemo,useRef,useState} from 'react';
import {buildFifoTrace,buildEccRecovery,fifoDefaults,eccDefaults,makeReliabilityRecord,parseReliabilityRecord,saveReliabilityRecord,olderReliabilityRecords,reliabilityRecordKey,type FifoInput,type EccInput} from '../lib/hardware-reliability';
import './hardware-reliability.css';
const bin=(x:number)=>x.toString(2).padStart(3,'0');
function init(){try{const raw=typeof window==='undefined'?null:window.localStorage.getItem(reliabilityRecordKey);return {record:raw?parseReliabilityRecord(raw):makeReliabilityRecord(fifoDefaults,eccDefaults),message:raw?'Restored the saved input record.':'Inputs are saved only when you choose Save.',older:typeof window!=='undefined'&&olderReliabilityRecords(window.localStorage)!==null};}catch(error){let older=false;try{older=olderReliabilityRecords(window.localStorage)!==null;}catch{}return {record:makeReliabilityRecord(fifoDefaults,eccDefaults),message:`Saved inputs were not applied: ${error instanceof Error?error.message:'storage unavailable'}. Current controls remain usable.`,older};}}
function download(raw:string,name:string){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Stepper({value,max,onChange,label}:{value:number;max:number;onChange:(v:number)=>void;label:string}){return <div className="reliability-stepper"><button disabled={value===0} aria-label="Previous reliability event" onClick={()=>onChange(value-1)}>←</button><label>{label}<input type="range" min="0" max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label><button disabled={value===max} aria-label="Next reliability event" onClick={()=>onChange(value+1)}>→</button><button onClick={()=>onChange(max)}>Outcome</button></div>;}
export default function HardwareReliability({onSelect}:{onSelect?:(id:string)=>void}={}){
 const [initial]=useState(init),[fifo,setFifo]=useState<FifoInput>(initial.record.fifo),[ecc,setEcc]=useState<EccInput>(initial.record.ecc),[tab,setTab]=useState<'fifo'|'ecc'>('fifo'),[fi,setFi]=useState(0),[ei,setEi]=useState(0),[message,setMessage]=useState(initial.message),[older,setOlder]=useState(initial.older),file=useRef<HTMLInputElement>(null);
 const ft=useMemo(()=>buildFifoTrace(fifo),[fifo]),et=useMemo(()=>buildEccRecovery(ecc),[ecc]),f=ft.events[Math.min(fi,ft.events.length-1)],e=et.events[Math.min(ei,et.events.length-1)];
 const updateF=(p:Partial<FifoInput>)=>{setFifo({...fifo,...p});setFi(0);},updateE=(p:Partial<EccInput>)=>{setEcc({...ecc,...p});setEi(0);};
 return <section className="hardware-reliability"><header><p className="reliability-kicker">Digital contracts · faults, validity and retained work</p><h3>When is a value safe to use?</h3><p>Inspect two bounded mechanisms: tagged data crossing clocks, and a protected word reaching a checkpointed consumer. Logical correctness, error detection and useful recovery have different boundaries.</p><p className="reliability-scope">Digital teaching traces only. Synchronizer stages do not simulate metastability; bit injections do not predict radiation rates, device aging or vendor HBM reliability.</p><p role="status">{message}</p></header>
 <div className="reliability-tabs" aria-label="Reliability mechanism"><button aria-pressed={tab==='fifo'} onClick={()=>setTab('fifo')}>Two clocks, one FIFO</button><button aria-pressed={tab==='ecc'} onClick={()=>setTab('ecc')}>ECC to consumer recovery</button></div>
 {tab==='fifo'?<><div className="reliability-controls"><label>Writer period (teaching ticks)<select value={fifo.writePeriod} onChange={ev=>updateF({writePeriod:Number(ev.target.value)})}>{[2,3,4,5,6,7].map(x=><option key={x}>{x}</option>)}</select></label><label>Reader period (teaching ticks)<select value={fifo.readPeriod} onChange={ev=>updateF({readPeriod:Number(ev.target.value)})}>{[2,3,4,5,6,7].map(x=><option key={x}>{x}</option>)}</select></label><label>Consumer schedule<select value={fifo.consumer} onChange={ev=>updateF({consumer:ev.target.value as FifoInput['consumer']})}><option value="ready">Ready at every read edge</option><option value="bursty">Ready 2 edges, blocked 2</option></select></label><label>Reset contract<select value={fifo.reset} onChange={ev=>updateF({reset:ev.target.value as FifoInput['reset']})}><option value="none">No reset</option><option value="both">Both domains · cancel pending</option><option value="reader-only">Reader only · unsafe contract</option></select></label><label>Reset at tick<input type="range" min="1" max="80" value={fifo.resetAt} onChange={ev=>updateF({resetAt:Number(ev.target.value)})}/><output>{fifo.resetAt}</output></label><label>Observation horizon<input type="range" min="40" max="240" step="10" value={fifo.horizon} onChange={ev=>updateF({horizon:Number(ev.target.value)})}/><output>{fifo.horizon} ticks</output></label></div>
 <div className="reliability-toolbar"><button onClick={()=>{setFifo({...fifoDefaults,reset:'reader-only'});setFi(0);}}>Inspect a broken reset</button><button onClick={()=>updateF({reset:'both'})}>Coordinate reset and cancellation</button><button onClick={()=>{setFifo(fifoDefaults);setFi(0);}}>Default FIFO</button></div>
 <Stepper value={Math.min(fi,ft.events.length-1)} max={ft.events.length-1} onChange={setFi} label={`Tick ${f.time} · event ${Math.min(fi,ft.events.length-1)+1} / ${ft.events.length}`}/><div className="reliability-event" aria-live="polite">{f.notes.join(' ')||'Pointer synchronization advances; no data transfer at this event.'}</div>
 <div className="reliability-clock-grid"><article><h4>Writer domain</h4><p>Edge: <b>{f.writeEdge?'yes':'no'}</b></p><p>Before edge: valid {Number(f.producerValid)}, ready {Number(f.writeReady)}</p><p>After edge: pointer <b>{bin(f.state.writePointer)}</b>, Gray <b>{bin(f.state.writeGray)}</b></p><p>Read pointer crossing into writer</p><div className="reliability-sync"><span>Stage 1<br/><b>{bin(f.state.readSyncInWriter[0])}</b></span><span>→</span><span>Stage 2<br/><b>{bin(f.state.readSyncInWriter[1])}</b></span></div><small>Writer's current full flag: {String(f.state.full)}</small></article><article><h4>Four physical slots</h4><div className="reliability-slots">{f.state.slots.map((tag,i)=><div key={i} className={tag&&f.state.expectedQueue.includes(tag)?'pending':'stale'}><span>Slot {i}</span><b>{tag??'Unwritten'}</b><small>{tag?f.state.expectedQueue.includes(tag)?'Accepted and pending':'Old bits; validity comes from pointers':'No valid tag'}</small></div>)}</div><small>The expected-tag list is an independent contract checker, not hardware FIFO control.</small></article><article><h4>Reader domain</h4><p>Edge: <b>{f.readEdge?'yes':'no'}</b></p><p>Before edge: valid {Number(f.readValid)}, ready {Number(f.consumerReady)}</p><p>After edge: pointer <b>{bin(f.state.readPointer)}</b>, Gray <b>{bin(f.state.readGray)}</b></p><p>Write pointer crossing into reader</p><div className="reliability-sync"><span>Stage 1<br/><b>{bin(f.state.writeSyncInReader[0])}</b></span><span>→</span><span>Stage 2<br/><b>{bin(f.state.writeSyncInReader[1])}</b></span></div><small>Reader's current empty flag: {String(f.state.empty)}</small></article></div>
 <dl className="reliability-metrics">{[['Accepted',f.state.accepted.length],['Validly consumed',f.state.consumed.length],['Canceled at reset',f.state.canceled.length],['Pending contract tags',f.state.expectedQueue.length]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>{v}</dd></div>)}</dl><p className="reliability-equation">Accepted = validly consumed + canceled + pending. Source values: {fifo.values.join(', ')}.</p>
 {ft.violation&&<div className="reliability-warning"><strong>Contract violation in this run</strong><p>{ft.violation}</p><button onClick={()=>setFi(ft.events.length-1)}>Inspect the counterexample</button><p>These are discrete reset/protocol errors. They do not measure metastability probability.</p></div>}
 <details><summary>Complete clock, transfer and pointer trace</summary><div className="reliability-table" role="region" tabIndex={0} aria-label="FIFO event trace"><table><thead><tr><th>Tick / clocks</th><th>Write / observed read</th><th>W / R pointers</th><th>Accepted / consumed / canceled / pending</th></tr></thead><tbody>{ft.events.map(ev=><tr key={ev.index} className={ev.index===f.index?'selected':''}><th>{ev.time} · {ev.writeEdge?'W':''}{ev.readEdge?'R':''}{ev.reset?' reset':''}</th><td>{ev.acceptedTag??'—'} / {ev.observedTag??'—'}{ev.correct===false?' · invalid':''}</td><td>{bin(ev.state.writePointer)} / {bin(ev.state.readPointer)}</td><td>{ev.state.accepted.length} / {ev.state.consumed.length} / {ev.state.canceled.length} / {ev.state.expectedQueue.length}</td></tr>)}</tbody></table></div></details>
 <div className="reliability-task"><h4>Predict → inspect → explain</h4><p>After a read frees a slot, why might the writer still report full? Follow the two receiving stages. Then reset only the reader: which tag should arrive next, and which tag is physically observed?</p></div>
 </>:<><div className="reliability-controls"><label>Four-bit payload<input type="range" min="0" max="15" value={ecc.payload} onChange={ev=>updateE({payload:Number(ev.target.value)})}/><output>{ecc.payload} · binary {ecc.payload.toString(2).padStart(4,'0')}</output></label><label>Inject at consumer step<select value={ecc.faultStep} onChange={ev=>updateE({faultStep:Number(ev.target.value)})}>{Array.from({length:ecc.steps},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><label>Checkpoint every<select value={ecc.checkpointEvery} onChange={ev=>updateE({checkpointEvery:Number(ev.target.value)})}>{[1,2,3,4].map(x=><option key={x} value={x}>{x} completed steps</option>)}</select></label><label>Detected-error policy<select value={ecc.recovery} onChange={ev=>updateE({recovery:ev.target.value as EccInput['recovery']})}><option value="stop">Stop before consuming</option><option value="restore-healthy">Restore intact checkpoint + healthy copy</option></select></label></div>
 <div className="reliability-toolbar"><button onClick={()=>updateE({flips:[]})}>Healthy</button><button onClick={()=>updateE({flips:[1]})}>One flip</button><button onClick={()=>updateE({flips:[1,2]})}>Two flips</button><button onClick={()=>updateE({flips:[1,2,3]})}>Three flips · exceed guarantee</button></div>
 <fieldset className="reliability-bit-select"><legend>Injected bit positions · choose up to three</legend>{Array.from({length:8},(_,i)=>i+1).map(p=><label key={p}><input type="checkbox" checked={ecc.flips.includes(p)} disabled={!ecc.flips.includes(p)&&ecc.flips.length===3} onChange={ev=>updateE({flips:ev.target.checked?[...ecc.flips,p]:ecc.flips.filter(x=>x!==p)})}/>{p}</label>)}</fieldset>
 <div className="reliability-codewords">{[['Encoded',et.encoded],['Received',et.received],['Decoder output bits',et.decoded.correctedBits]].map(([label,bits])=><div key={String(label)}><h4>{String(label)}</h4><div className="reliability-bits">{(bits as number[]).map((b,i)=><span key={i} className={ecc.flips.includes(i+1)&&label==='Received'?'flipped':''}><small>{i+1} · {({1:'p1',2:'p2',3:'d0',4:'p4',5:'d1',6:'d2',7:'d3',8:'p0'} as Record<number,string>)[i+1]}</small><b>{b}</b></span>)}</div></div>)}</div>
 <div className="reliability-parity">{et.decoded.parityChecks.map(c=><p key={c.mask}>Check {c.mask}: positions {c.positions.join(' ⊕ ')} → <strong>{c.value}</strong></p>)}<p>Syndrome = <b>{et.decoded.syndrome}</b> · overall parity = <b>{et.decoded.overallParity}</b></p><p>Decoder classification: <strong>{et.decoded.classification}</strong> · supplied payload: <strong>{et.decoded.payload??'none'}</strong></p></div>
 {!et.withinGuarantee&&<div className="reliability-warning"><strong>Outside the code's guarantee</strong><p>The decoder does not know how many bits were injected. This test fixture supplies the ground truth: decoded value {et.decoded.payload??'unavailable'} versus original {ecc.payload}. {et.fixtureTruthMatches===false?'The decoder reports a correction, but the value is wrong.':'This selected pattern does not establish protection against other higher-order errors.'}</p></div>}
 <Stepper value={Math.min(ei,et.events.length-1)} max={et.events.length-1} onChange={setEi} label={`Consumer event ${Math.min(ei,et.events.length-1)+1} / ${et.events.length}`}/><div className="reliability-event" aria-live="polite">{e.label}</div>
 <div className="reliability-recovery-path"><article><h4>Read / decoder</h4><p>{e.decoded?.classification??'No read at this event'}</p><strong>{e.decoded?.payload??'No value supplied'}</strong></article><article><h4>Current consumer</h4><p>{e.completedSteps} completed steps</p><strong>Sum {e.sum}</strong></article><article><h4>Intact checkpoint</h4><p>{e.checkpointSteps} recorded steps</p><strong>Sum {e.checkpointSum}</strong></article></div>
 <dl className="reliability-metrics">{[['Executed steps',e.executedSteps],['Discarded by restart',e.discardedSteps],['Currently completed',e.completedSteps],['Checkpointed',e.checkpointSteps]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>{v}</dd></div>)}</dl><p className="reliability-equation">Executed = currently completed + discarded. A failed read is counted separately from computation.</p><p>Run outcome: <strong>{et.status}</strong> · final sum <strong>{et.finalSum??'not published'}</strong> · independent fixture reference <strong>{et.referenceSum}</strong>.</p>
 <details><summary>Consumer and checkpoint ledger</summary><div className="reliability-table" role="region" tabIndex={0} aria-label="ECC consumer recovery trace"><table><thead><tr><th>Event / step</th><th>Sum / checkpoint sum</th><th>Executed / discarded / completed</th><th>Interpretation</th></tr></thead><tbody>{et.events.map(ev=><tr key={ev.index} className={ev.index===e.index?'selected':''}><th>{ev.kind} · {ev.step}</th><td>{ev.sum} / {ev.checkpointSum}</td><td>{ev.executedSteps} / {ev.discardedSteps} / {ev.completedSteps}</td><td>{ev.label}</td></tr>)}</tbody></table></div></details>
 <div className="reliability-task"><h4>Predict → inspect → explain</h4><p>For payload 9, two flips at step 4 and checkpoints every two steps, predict the discarded work. Inspect the restore: seven computations finish six valid steps. Then inject three flips and explain why the decoder's correction label is insufficient.</p></div>
 </>}
 <details><summary>Save, restore and export inputs</summary><p>Both mechanism inputs are included with model identity. Import changes this session only; choose Save to restore it automatically on this device next time. Incompatible old raw records are preserved before replacement.</p><div className="reliability-toolbar"><button onClick={()=>{try{saveReliabilityRecord(window.localStorage,makeReliabilityRecord(fifo,ecc));setOlder(olderReliabilityRecords(window.localStorage)!==null);setMessage('Saved the two mechanism inputs on this device.');}catch(error){setMessage(`Save failed: ${error instanceof Error?error.message:'storage unavailable'}. Live inputs and export remain available.`);}}}>Save inputs</button><button onClick={()=>download(JSON.stringify(makeReliabilityRecord(fifo,ecc),null,2),'ai-atlas-reliability-input.json')}>Export input record</button><button onClick={()=>file.current?.click()}>Import input record</button><button disabled={!older} onClick={()=>{try{const raw=olderReliabilityRecords(window.localStorage);if(raw)download(raw,'ai-atlas-older-reliability-input.txt');}catch(error){setMessage(`Older input export failed: ${error instanceof Error?error.message:'storage unavailable'}`);}}}>Export older saved input</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={async ev=>{const f=ev.target.files?.[0];ev.target.value='';if(!f)return;try{if(f.size>65536)throw new Error('File exceeds 64 KiB.');const r=parseReliabilityRecord(await f.text());setFifo(r.fifo);setEcc(r.ecc);setFi(0);setEi(0);setMessage('Imported valid inputs into this session. Choose Save to retain them on this device.');}catch(error){setMessage(`Import rejected: ${error instanceof Error?error.message:'invalid record'}. Current inputs remain unchanged.`);}}}/></div></details>
 <details><summary>Mathematical and physical boundaries</summary><ul><li>The FIFO uses four slots, modulo-eight pointers and two ideal receiving registers. Simultaneous edges sample pre-edge values. Full/empty decisions use the previous receiving-stage output, so they can be conservative.</li><li>Gray conversion changes one bit per ordinary pointer increment. Reset can change several bits and has a separately stated contract. No analog resolution time, skew, clock jitter, metastability probability or CDC signoff is calculated.</li><li>The ECC is a declared extended Hamming (8,4) code: parity at positions 1, 2, 4; data at 3, 5, 6, 7; overall even parity at 8. It corrects one bit and detects two. Higher-order patterns can be misclassified.</li><li>The consumer is a finite sum, not an AI model or an actual memory device. Checkpoint storage is assumed intact; it can still preserve an already wrong computed value. Recovery assumes a separately available healthy word and a one-shot fault; neither guarantee comes from SECDED.</li><li>Current completed work and checkpointed work are different. No recovery latency, fault rate, hardware repair, HBM physical ECC layout or radiation environment is inferred.</li><li>The FIFO and ECC experiments are separate mechanisms in this version. No unimplemented coupling between their state is implied.</li></ul></details>
 <nav className="reliability-toolbar" aria-label="Related lessons">{[['chip-rtl-verification','RTL verification'],['clock','Clock domains'],['hbm-channel-generation-ras','Memory RAS'],['retained-work-restart-boundary','Retained work']].map(([id,label])=><button key={id} disabled={!onSelect} onClick={()=>onSelect?.(id)}>{label}</button>)}</nav>
 <ul className="reliability-sources"><li><a href="https://github.com/lowRISC/opentitan/blob/master/hw/ip/prim/rtl/prim_fifo_async.sv" target="_blank" rel="noreferrer">OpenTitan asynchronous FIFO · handshakes, Gray pointers and receiving registers</a></li><li><a href="https://opentitan.org/book/util/design/index.html" target="_blank" rel="noreferrer">OpenTitan ECC generation and verification tools</a></li><li><a href="https://onlinelibrary.wiley.com/doi/10.1002/j.1538-7305.1950.tb00463.x" target="_blank" rel="noreferrer">Hamming, 1950 · publication record for error detecting and correcting codes</a></li></ul>
 </section>;
}
