import {useMemo,useRef,useState} from 'react';
import {architecturePresets} from '../lib/architecture-execution';
import {buildMachineExecution,machineDefaults,machineTiming,type MachineExecutionInput,type MachineExecution,type MachineEvent} from '../lib/machine-execution';
import {makeMachineRecord,parseMachineRecord,saveMachineRecord,exportOlderMachineRecords,machineRecordKey} from '../lib/machine-execution-record';
import './machine-execution.css';

function initialWorkspace(){
  try{const raw=typeof window==='undefined'?null:window.localStorage.getItem(machineRecordKey);return {input:raw?parseMachineRecord(raw).input:machineDefaults,message:raw?'Restored the saved input record.':'Change the layout, then follow the same values into memory and back.',older:typeof window!=='undefined'&&exportOlderMachineRecords(window.localStorage)!==null};}
  catch(error){let older=false;try{older=exportOlderMachineRecords(window.localStorage)!==null;}catch{}return {input:machineDefaults,message:`Saved inputs were not applied: ${error instanceof Error?error.message:'storage unavailable'}. Current controls remain usable.`,older};}
}
function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const fmt=(n:number)=>n.toLocaleString();
function MatrixGrid({name,matrix,edit,complete}:{name:string;matrix:readonly(readonly number[])[];edit?:(r:number,c:number,v:number)=>void;complete?:number[][]}){
  return <div className="machine-matrix"><h4>{name}</h4><div style={{gridTemplateColumns:`repeat(${matrix.length},minmax(0,1fr))`}}>{matrix.flatMap((row,r)=>row.map((v,c)=>edit?<input key={`${r}:${c}`} aria-label={`${name}, row ${r}, column ${c}`} type="number" step="1" min="-99" max="99" value={v} onChange={e=>{if(e.target.value!==''&&Number.isInteger(Number(e.target.value))&&Math.abs(Number(e.target.value))<=99)edit(r,c,Number(e.target.value));}}/>:<output key={`${r}:${c}`} className={complete?.[r][c]===matrix.length?'is-complete':''} aria-label={`${name}, row ${r}, column ${c}: ${v}; ${complete?.[r][c]===matrix.length?'complete':'partial'}`}>{v}</output>))}</div></div>;
}
function Timing({trace,event}:{trace:MachineExecution;event:MachineEvent}){
  const width=900,left=90,right=880,scale=(right-left)/Math.max(1,trace.totals.durationNs),x=(t:number)=>left+t*scale;
  return <figure className="machine-timing"><svg viewBox={`0 0 ${width} 205`} role="img" aria-label={`Declared memory and compute timeline. Cursor at ${event.timeNs} nanoseconds. A tabular command trace follows.`}><title>Serialized DRAM commands and overlapping compute. All durations are assumed nanoseconds.</title>{[0,1,2,3,4].map(i=><g key={i}><line x1={x(trace.totals.durationNs*i/4)} y1="25" x2={x(trace.totals.durationNs*i/4)} y2="170" className="grid"/><text x={x(trace.totals.durationNs*i/4)} y="192" textAnchor="middle">{Math.round(trace.totals.durationNs*i/4)} ns</text></g>)}<text x="4" y="57">DRAM</text><text x="4" y="110">Slot 0</text><text x="4" y="153">Slot 1</text>{trace.commands.map(c=><rect key={c.id} x={x(c.startNs)} y="39" width={Math.max(1,(c.endNs-c.startNs)*scale)} height="28" className={`command-${c.kind}`}><title>{c.kind}: {c.startNs}–{c.endNs} ns{c.bank===null?' all banks':` bank ${c.bank}`}</title></rect>)}{trace.batches.map(b=><g key={b.id}><rect x={x(b.submittedNs)} y={89+43*b.buffer} width={Math.max(1,(b.readyNs-b.submittedNs)*scale)} height="23" className="dma-window"><title>{b.id} DMA ownership {b.submittedNs}–{b.readyNs} ns</title></rect><rect x={x(b.computeStartNs)} y={89+43*b.buffer} width={Math.max(1,(b.computeEndNs-b.computeStartNs)*scale)} height="23" className="compute-window"><title>{b.id} shared reads and MAC {b.computeStartNs}–{b.computeEndNs} ns</title></rect></g>)}<line x1={x(event.timeNs)} x2={x(event.timeNs)} y1="15" y2="172" className="cursor"/></svg><figcaption><span>Violet: ACT/PRE · teal: read/write · amber: refresh</span><span>Muted: DMA owns slot · bright: shared reads + MAC</span></figcaption></figure>;
}
export default function MachineExecution({onSelect}:{onSelect?:(id:string)=>void}={}){
  const [workspace]=useState(initialWorkspace),[input,setInput]=useState<MachineExecutionInput>(workspace.input),[index,setIndex]=useState(0),[selectedBatch,setSelectedBatch]=useState(0),[message,setMessage]=useState(workspace.message),[older,setOlder]=useState(workspace.older);
  const fileRef=useRef<HTMLInputElement>(null),trace=useMemo(()=>buildMachineExecution(input),[input]),event=trace.events[Math.min(index,trace.events.length-1)],batch=trace.batches[Math.min(selectedBatch,trace.batches.length-1)];
  const change=(next:MachineExecutionInput)=>{setInput(next);setIndex(0);setSelectedBatch(0);};
  const patch=(p:Partial<MachineExecutionInput>)=>change({...input,...p});
  const jump=(kind:MachineEvent['kind'],batchId?:string)=>{const i=trace.events.findIndex(e=>e.kind===kind&&(!batchId||e.batchId===batchId));if(i>=0)setIndex(i);};
  const exportInput=()=>download(JSON.stringify(makeMachineRecord(input),null,2),'ai-atlas-machine-input.json');
  const save=()=>{try{saveMachineRecord(window.localStorage,makeMachineRecord(input));setOlder(exportOlderMachineRecords(window.localStorage)!==null);setMessage('Saved these inputs on this device. Export a record to keep a portable copy.');}catch(error){setMessage(`Could not save: ${error instanceof Error?error.message:'storage unavailable'}. Current controls and export remain available.`);}};
  const completedMacs=event.state.completedMacs.flat().reduce((a,b)=>a+b,0);
  const link=(id:string,label:string)=><button key={id} onClick={()=>onSelect?.(id)} disabled={!onSelect}>{label}</button>;
  return <section className="machine-execution" aria-labelledby="machine-title"><header><p className="machine-kicker">Connected execution · exact values, declared hardware</p><h3 id="machine-title">The matrix is correct. What is the machine waiting for?</h3><p>Follow C = AB from four teaching lanes through mapped addresses, 16-byte transfers, DRAM commands and owned staging slots. Every partial sum uses the values that actually arrived.</p><p className="machine-scope">This is a small synthetic machine: 4 lanes, 4 shared banks, 2 DRAM banks. Durations below are assumed nanoseconds, not measurements or a vendor speed comparison.</p><p className="machine-record-status" role="status">{message}</p></header>
  <div className="machine-toolbar"><button onClick={()=>change({...machineDefaults,a:architecturePresets.two.a,b:architecturePresets.two.b})}>2 × 2 example</button><button onClick={()=>change({...machineDefaults,a:architecturePresets.three.a,b:architecturePresets.three.b})}>Signed 3 × 3</button><button onClick={()=>patch({globalLayout:'column-major'})}>Try a strided B layout</button><button onClick={()=>{patch({fault:'none'});setMessage('Mapping and ownership guards restored. Follow the repaired operation to host completion.');}}>Restore safe operation</button></div>
  <div className="machine-matrices"><MatrixGrid name="A" matrix={trace.input.a} edit={(r,c,v)=>patch({a:trace.input.a.map((row,i)=>row.map((x,j)=>i===r&&j===c?v:x))})}/><span aria-hidden="true">×</span><MatrixGrid name="B" matrix={trace.input.b} edit={(r,c,v)=>patch({b:trace.input.b.map((row,i)=>row.map((x,j)=>i===r&&j===c?v:x))})}/><span aria-hidden="true">=</span><MatrixGrid name="C · at the cursor" matrix={event.state.partialOutput} complete={event.state.completedMacs}/></div>
  <div className="machine-controls">
   <label>B in global memory<select value={trace.input.globalLayout} onChange={e=>patch({globalLayout:e.target.value as 'row-major'|'column-major'})}><option value="row-major">Rows contiguous</option><option value="column-major">Columns contiguous</option></select></label>
   <label>First input word offset<select value={trace.input.alignmentBytes} onChange={e=>patch({alignmentBytes:Number(e.target.value) as 0|12})}><option value="0">0 B · segment aligned</option><option value="12">12 B · near segment edge</option></select></label>
   <label>A / B bank placement<select value={trace.input.bankPlacement} onChange={e=>patch({bankPlacement:e.target.value as 'same-bank'|'split-banks'})}><option value="same-bank">Different rows of bank 0</option><option value="split-banks">Bank 0 / bank 1</option></select></label>
   <label>Shared row padding<select value={trace.input.sharedPadding} onChange={e=>patch({sharedPadding:Number(e.target.value) as 0|1})}><option value="0">No extra word</option><option value="1">One extra word per row</option></select></label>
   <label>Staging slots<select value={trace.input.buffers} onChange={e=>patch({buffers:Number(e.target.value) as 1|2})}><option value="1">One · no reuse while owned</option><option value="2">Two · overlap when available</option></select></label>
   <label>Assumed MAC service<select value={trace.input.macNs} onChange={e=>patch({macNs:Number(e.target.value) as 2|8|24})}>{[2,8,24].map(v=><option key={v} value={v}>{v} ns per lane group</option>)}</select></label>
   <label>Refresh due grid<select value={trace.input.refreshEveryNs} onChange={e=>patch({refreshEveryNs:Number(e.target.value) as 0|64|96|160})}><option value="0">Disabled · counterfactual</option>{[64,96,160].map(v=><option key={v} value={v}>Every {v} assumed ns</option>)}</select></label>
   <label>Failure to inspect<select value={trace.input.fault} onChange={e=>patch({fault:e.target.value as MachineExecutionInput['fault']})}><option value="none">Safe operation</option><option value="unmapped-b">Missing B read mapping</option><option value="early-consume">Consume before DMA completes</option><option value="reuse-in-flight">Overwrite an owned slot</option></select></label>
  </div>
  <dl className="machine-metrics">{[['Host completion',trace.finalOutput?`${fmt(trace.totals.durationNs)} assumed ns`:'Blocked'],['MACs at cursor',`${completedMacs} / ${trace.input.size**3}`],['Input bytes: unique / lane requested',`${trace.totals.distinctInputBytes} / ${trace.totals.requestedReadBytes} B`],['DRAM read / write transfers',`${trace.totals.readTransactionBytes} / ${trace.totals.writeTransactionBytes} B`],['Shared read rounds',String(trace.totals.sharedRounds)],['Refresh operations',String(trace.totals.refreshes)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
  <div className="machine-cursor"><button onClick={()=>setIndex(Math.max(0,index-1))} disabled={index===0} aria-label="Previous machine event">←</button><label>Timing cursor · {event.timeNs} ns · event {Math.min(index,trace.events.length-1)+1} / {trace.events.length}<input type="range" min="0" max={trace.events.length-1} value={Math.min(index,trace.events.length-1)} onChange={e=>setIndex(Number(e.target.value))} aria-label="Machine event and timing cursor"/></label><button onClick={()=>setIndex(Math.min(trace.events.length-1,index+1))} disabled={index>=trace.events.length-1} aria-label="Next machine event">→</button><button onClick={()=>setIndex(trace.events.length-1)}>Completion</button></div>
  <p className="machine-event" aria-live="polite">{event.label}</p>
  {trace.input.fault!=='none'&&<div className="machine-warning"><strong>{trace.status==='mapping-blocked'?'This operation is blocked before DMA.':'The unsafe action is rejected; the safe schedule can still complete.'}</strong><p>{event.state.rejections.at(-1)||'Move to the failure event to inspect the guard and unchanged state.'}</p><button onClick={()=>jump(trace.status==='mapping-blocked'?'mapping-fault':'guard-rejected')}>Inspect the rejected action</button></div>}
  <div className="machine-path" aria-label="Mapped address to physical service to exact result">
   <article><span className="machine-stage">1 · Driver contract</span><h4>Address & permission</h4>{trace.mappings.map(m=><p key={m.tensor}><b>{m.tensor}</b> IOVA {m.iovaStart} → physical {m.physicalStart}<small>{m.lengthBytes} B · {m.permission} · {m.mapped?'mapped':'missing'}</small></p>)}<small>Inputs: {event.state.inputOwner}-owned</small></article>
   <article><span className="machine-stage">2 · DRAM structure</span><h4>Open rows at the cursor</h4><svg viewBox="0 0 270 215" role="img" aria-label={`Two symbolic DRAM banks. Bank 0 open row ${event.state.openRows[0]??'none'}; bank 1 open row ${event.state.openRows[1]??'none'}. Each row has four 16-byte segments.`}>{[0,1].map(bank=><g key={bank}><text x={bank*132+8} y="16">Bank {bank}</text>{Array.from({length:8},(_,r)=><g key={r}><text x={bank*132+5} y={38+r*22}>{r}</text>{[0,1,2,3].map(c=><rect key={c} x={bank*132+22+c*24} y={26+r*22} width="21" height="17" className={event.state.openRows[bank]===r?'row-open':'row-closed'}><title>Bank {bank}, row {r}, column {c}; physical segment {r*128+bank*64+c*16}</title></rect>)}</g>)}</g>)}</svg><small>ACT selects a row; tRCD still gates access. Symbolic positions; no vendor floorplan.</small></article>
   <article><span className="machine-stage">3 · Owned staging</span><h4>Completion precedes use</h4>{event.state.buffers.map(b=><div key={b.index} className={`machine-slot phase-${b.phase}`}><b>Slot {b.index} · {b.phase}</b><span>{b.batchId??'Available'}</span><small>{Object.keys(b.words).length} arrived operand words</small></div>)}<p>Free → DMA → ready → compute → free</p></article>
   <article><span className="machine-stage">4 · Compute & publish</span><h4>Exact partial sums</h4><p>{completedMacs} multiply–accumulates committed at this cursor.</p><p>{event.state.storedOutputs.length} / {trace.input.size**2} output words stored.</p><strong>Output owner: {event.state.outputOwner}</strong><small>{event.state.outputOwner==='cpu'?'Host may now consume C.':'Host must wait for all output writes.'}</small></article>
  </div>
  <Timing trace={trace} event={event}/>
  {batch&&<section className="machine-batch" aria-labelledby="machine-batch-title"><div className="machine-toolbar"><label id="machine-batch-title">Inspect one lane group<select value={Math.min(selectedBatch,trace.batches.length-1)} onChange={e=>setSelectedBatch(Number(e.target.value))}>{trace.batches.map(b=><option key={b.id} value={b.index}>{b.id} · reduction k={b.k} · slot {b.buffer}</option>)}</select></label><button onClick={()=>jump('acquire',batch.id)}>DMA begins</button><button onClick={()=>jump('ready',batch.id)}>Operands ready</button><button onClick={()=>jump('compute-end',batch.id)}>Partial sum commits</button></div>
   <div className="machine-lanes">{[0,1,2,3].map(lane=>{const l=batch.lanes.find(l=>l.lane===lane);return <article key={lane}><b>Lane {lane}</b>{l?<><span>C[{l.row},{l.column}], k={l.k}</span><strong>{l.a.value} × {l.b.value}</strong><small>{l.a.id} and {l.b.id}</small></>:<span>No output assigned</span>}</article>;})}</div>
   <div className="machine-table" role="region" tabIndex={0} aria-label="Operand address and transaction mapping"><table><caption>Selected group addresses · byte addresses; repeated operand IDs may broadcast</caption><thead><tr><th>Lane / operand</th><th>Value</th><th>IOVA → physical</th><th>16 B transaction</th><th>Shared word / bank</th></tr></thead><tbody>{batch.lanes.flatMap(l=>[l.a,l.b].map(o=>{const t=trace.transactions.find(t=>t.batchId===batch.id&&t.tensor===o.tensor&&o.physical>=t.physical&&o.physical<t.physical+16)!;return <tr key={`${l.lane}:${o.id}`}><th>{l.lane} · {o.id}</th><td>{o.value}</td><td>{o.iova} → {o.physical}</td><td>{t.id}<small>bank {t.address.bank}, row {t.address.row}, column {t.address.column}</small></td><td>{o.sharedByte/4} / {o.sharedBank}</td></tr>;}))}</tbody></table></div>
   <div className="machine-banks">{[0,1,2,3].map(bank=><article key={bank}><b>Shared bank {bank}</b>{(['A','B'] as const).map(t=>{const g=batch.sharedGroups.find(g=>g.tensor===t&&g.bank===bank);return <p key={t}>{t}: {g?`${g.distinctWords.length} distinct word${g.distinctWords.length===1?'':'s'} · ${g.rounds} round${g.rounds===1?'':'s'}${g.broadcast?' · repeated-word broadcast':''}`:'idle'}</p>;})}</article>)}</div><p>A and B are separate shared-read instructions. Their slowest-bank rounds add to <strong>{batch.sharedRounds} ns</strong> under the assumed 1 ns per round. Padding can help or hurt a particular layout.</p>
   <div className="machine-table" role="region" tabIndex={0} aria-label="Selected transaction delays"><table><caption>From queue arrival to available data · assumed ns</caption><thead><tr><th>Transaction</th><th>Submitted</th><th>Service start</th><th>Row state</th><th>Data burst</th><th>Complete</th></tr></thead><tbody>{trace.transactions.filter(t=>t.batchId===batch.id).map(t=><tr key={t.id}><th>{t.id}</th><td>{t.submittedNs}</td><td>{t.serviceStartNs}<small>{t.queueWaitNs} ns in queue / refresh wait</small></td><td>{t.rowDisposition}</td><td>{t.dataStartNs}–{t.dataEndNs}</td><td>{t.completedNs}</td></tr>)}</tbody></table></div>
  </section>}
  {event.macs.length>0&&<div className="machine-calculation"><h4>Committed from the arrived operands</h4>{event.macs.map(m=><p key={m.lane}>C[{m.row},{m.column}]: {m.before} + ({m.a} × {m.b}) = <strong>{m.after}</strong></p>)}</div>}
  <details><summary>Complete command trace and exact timing assumptions</summary><p>ACT→read/write: {machineTiming.tRCDNs} ns; precharge: {machineTiming.tRPNs} ns; minimum active time: {machineTiming.tRASNs} ns; read latency: {machineTiming.tCLNs} ns; write latency: {machineTiming.tCWLNs} ns; burst: {machineTiming.burstNs} ns; write recovery: {machineTiming.tWRNs} ns; refresh: {machineTiming.tRFCNs} ns. Service is FIFO and serialized, even across banks.</p><div className="machine-table" role="region" tabIndex={0} aria-label="DRAM command timeline"><table><thead><tr><th>Command</th><th>Bank / row</th><th>Start → end (ns)</th><th>Request / due time</th></tr></thead><tbody>{trace.commands.map(c=><tr key={c.id} className={event.commandId===c.id?'selected':''}><th>{c.kind}</th><td>{c.bank??'all'} / {c.row??'—'}</td><td>{c.startNs} → {c.endNs}</td><td>{c.transactionId??`refresh due ${c.refreshDueNs??'—'} ns`}{c.refreshLatenessNs!==undefined&&<small>{c.refreshLatenessNs} ns later than due grid</small>}</td></tr>)}</tbody></table></div></details>
  <details><summary>Save, restore and export the input record</summary><p>Saved inputs restore when this experience opens. Save explicitly after edits or import; the current session remains usable if storage is unavailable. The record includes the model identity and complete inputs. Derived results are recomputed.</p><div className="machine-toolbar"><button onClick={save}>Save inputs on this device</button><button onClick={exportInput}>Export current input record</button><button onClick={()=>fileRef.current?.click()}>Import input record</button><button disabled={!older} onClick={()=>{try{const raw=exportOlderMachineRecords(window.localStorage);if(raw)download(raw,'ai-atlas-older-machine-input.txt');}catch(error){setMessage(`Could not export older input: ${error instanceof Error?error.message:'storage unavailable'}`);}}}>Export older saved input</button><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>65536)throw new Error('Input record exceeds the 64 KiB limit.');const record=parseMachineRecord(await file.text());change(record.input);setMessage('Imported a valid input record for this session. Choose Save to retain it on this device.');}catch(error){setMessage(`Import rejected: ${error instanceof Error?error.message:'invalid input'}. Current inputs remain unchanged.`);}}}/></div></details>
  <details><summary>What is modeled, and what these results do not establish</summary><ul>{trace.assumptions.map(a=><li key={a}>{a}</li>)}</ul><p>Compare with the existing HBM explorer carefully: this 1 KiB address space is a different, explicitly declared teaching organization. No byte address can be passed between the two models without an adapter.</p></details>
  <div className="machine-task"><h4>Predict → inspect → explain</h4><p>Keep the signed matrix, switch B to columns-contiguous storage and predict the traffic change. Then add shared padding: why can local bank rounds rise while elapsed time stays the same? Finally, request reuse of a DMA-owned slot and locate the guard that keeps the result valid.</p><p>Reference C: {trace.reference.map(row=>`[${row.join(', ')}]`).join(' ')}. A reference answer is not permission to consume an unfinished output.</p></div>
  <nav className="machine-toolbar" aria-label="Continue the mechanism">{link('simt-active-lanes','Lane execution')}{link('compiler-layout-lowering','Layout lowering')}{link('hbm-controller','Memory controller')}{link('runtime-device-dispatch','Driver and dispatch')}{link('memory-working-set-placement','Working-set placement')}</nav>
  <ul className="machine-sources"><li><a href="https://docs.nvidia.com/cuda/archive/13.1.1/cuda-c-best-practices-guide/index.html" target="_blank" rel="noreferrer">CUDA 13.1.1 · transaction layout, shared banks and completion</a></li><li><a href="https://docs.kernel.org/core-api/dma-api-howto.html" target="_blank" rel="noreferrer">Linux DMA guide · addresses, mapping and ownership synchronization</a></li><li><a href="https://onlinedocs.microchip.com/oxy/GUID-B822915F-C375-4172-91BD-AB6F326EB783-en-US-1/GUID-F3B24B38-CBB2-434E-A89A-EC8BB4810756.html" target="_blank" rel="noreferrer">Microchip DDR controller · activation, precharge and row access</a></li><li><a href="https://github.com/CMU-SAFARI/ramulator2" target="_blank" rel="noreferrer">Ramulator 2 · trace-driven DRAM modeling context</a></li></ul>
 </section>;
}
