import {useMemo,useState} from 'react';
import {Control,Details,Metrics,SourceLinks,Stepper} from './studio-primitives';
import PortableExperiment from './portable-experiment';
import {buildMatrixNetwork,matrixNetworkDefaults,serializeMatrixNetworkRecord,readMatrixNetworkRecord,type MatrixNetworkInput} from '../lib/matrix-network';
import './matrix-network.css';
const hex=(bytes:readonly (number|null)[])=>bytes.map(b=>b===null?'··':b.toString(16).padStart(2,'0')).join(' ');
function Matrix({label,values}:{label:string;values:readonly (readonly number[])[]|null}){return <figure className="mn-matrix"><figcaption>{label}</figcaption>{values?<table><tbody>{values.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>:<p>No published output</p>}</figure>;}
export type MatrixNetworkExperienceProps={onSelect?:(id:string)=>void};
export default function MatrixNetworkExperience({onSelect}:MatrixNetworkExperienceProps){
 const[input,setInput]=useState<MatrixNetworkInput>({...matrixNetworkDefaults}),[cursor,setCursor]=useState(0);
 const result=useMemo(()=>buildMatrixNetwork(input),[input]),step=result.steps[Math.min(cursor,result.steps.length-1)],c=step.counters;
 const edit=(patch:Partial<MatrixNetworkInput>)=>{setInput(old=>{const next={...old,...patch},n=next.specimen==='two'?2:3;next.faultSegment=Math.min(next.faultSegment,Math.ceil(n*n*4/next.flitBytes)-1);return next;});setCursor(0);};
 return <section className="matrix-network" aria-label="Matrix bytes through a finite-credit network"><div className="studio-heading"><h3>When may the receiver use the matrix?</h3><p>Send the same A or B operand through a finite-credit link. Follow actual bytes from injection to assembly, then watch the destination values enter C = AB. Delays and credit returns use synthetic ticks.</p></div>
 <PortableExperiment storageKey="ai-atlas.matrix-network.v1" serialize={()=>serializeMatrixNetworkRecord(input)} restore={raw=>{const next=readMatrixNetworkRecord(raw);setInput(next);setCursor(0);return 'Validated settings restored; bytes, credits and consumer result recomputed.';}}/>
 <div className="studio-layout"><aside className="studio-sidebar"><label>Matrix specimen<select value={input.specimen} onChange={e=>edit({specimen:e.target.value as MatrixNetworkInput['specimen']})}><option value="two">2 × 2</option><option value="three">3 × 3</option></select></label><label>Operand transferred<select value={input.tensor} onChange={e=>edit({tensor:e.target.value as 'A'|'B'})}><option>A</option><option>B</option></select></label><label>Flit slot width<select value={input.flitBytes} onChange={e=>edit({flitBytes:Number(e.target.value) as 4|8|16})}>{[4,8,16].map(v=><option key={v} value={v}>{v} bytes</option>)}</select></label>
 <Control label="Receiver slots / credits" value={input.credits} min={1} max={4} onChange={v=>edit({credits:v as 1|2|3|4})}/><Control label="Link transit" value={input.linkTicks} min={1} max={8} unit="ticks" onChange={linkTicks=>edit({linkTicks})}/><Control label="Credit return" value={input.creditTicks} min={1} max={8} unit="ticks" onChange={creditTicks=>edit({creditTicks})}/><Control label="Initial receiver pause" value={input.receiverPauseTicks} min={0} max={24} unit="ticks" onChange={receiverPauseTicks=>edit({receiverPauseTicks})}/><Control label="Receiver service interval" value={input.consumeEveryTicks} min={1} max={4} unit="ticks" onChange={consumeEveryTicks=>edit({consumeEveryTicks})}/>
 <label>Failure fixture<select value={input.fault} onChange={e=>edit({fault:e.target.value as MatrixNetworkInput['fault']})}><option value="none">None</option><option value="omit">Omit one sender segment</option><option value="wrong-identity">Wrong transfer / tensor identity</option><option value="duplicate">Duplicate one segment</option><option value="premature-consume">Try consuming before delivery</option><option value="wrong-payload">Changed payload, valid identity</option></select></label><Control label="Affected segment" value={input.faultSegment} min={0} max={result.totals.expectedSegments-1} disabled={input.fault==='none'||input.fault==='premature-consume'} onChange={faultSegment=>edit({faultSegment})}/><button onClick={()=>edit({...matrixNetworkDefaults})}>Restore default transfer</button>
 <p className="studio-note">One credit reserves one flit slot, including while its data or return credit is in transit. A byte is data; a flit is a transfer slot; a credit is permission to occupy a receiver slot.</p></aside>
 <div className="studio-main"><div className="mn-inputs"><Matrix label="Original A" values={result.a}/><Matrix label="Original B" values={result.b}/></div><Stepper value={Math.min(cursor,result.steps.length-1)} max={result.steps.length-1} onChange={setCursor} label="Snapshot"/><div className="mn-actions"><button onClick={()=>setCursor(0)}>First tick</button><button onClick={()=>setCursor(result.steps.length-1)}>Inspect final state</button></div><p role="status" aria-live="polite"><strong>Tick {step.tick}</strong> · {step.published?'Consumer output published':step.ready?'Operand assembled; consumer is computing':'Consumer waiting for a complete identified operand'}. {step.events.map(e=>e.kind).join(' · ')||'No transfer or MAC at this tick.'}</p>
 <div className="mn-path" aria-label="Current ownership and credit state"><article><small>Sender</small><h4>{step.credits} / {input.credits} credits</h4><p>{step.remainingSend.length} flits waiting</p><code>{step.remainingSend.map(x=>'#'+x).join(' ')||'Queue empty'}</code></article><span aria-hidden="true">→</span><article><small>Link</small><h4>{step.inFlight.length} in flight</h4><ul>{step.inFlight.map(f=><li key={f.sequence}>#{f.sequence} · segment {f.segment} → tick {f.dueTick}</li>)}</ul></article><span aria-hidden="true">→</span><article><small>Receiver FIFO</small><h4>{step.receiver.length} / {input.credits} slots</h4><code>{step.receiver.map(x=>'#'+x).join(' ')||'Queue empty'}</code><p>{step.acceptedSegments.length} / {result.totals.expectedSegments} unique segments assembled</p></article><span aria-hidden="true">↩</span><article><small>Credit return path</small><h4>{step.creditReturns.length} pending</h4><ul>{step.creditReturns.map(r=><li key={r.sequence}>for #{r.sequence} → tick {r.dueTick}</li>)}</ul></article></div>
 <p className="mn-invariant">{step.credits} sender credits + {step.inFlight.length} in flight + {step.receiver.length} queued + {step.creditReturns.length} returns = <strong>{input.credits} reserved slots</strong>.</p><ul className="mn-events">{step.events.map((e,i)=><li key={i}><strong>{e.kind}</strong>{e.sequence!==null?' #'+e.sequence:''}: {e.message}{e.sequence!==null&&['send','accept','reject'].includes(e.kind)&&<code>{hex(result.flits[e.sequence].bytes)}</code>}</li>)}</ul>
 <Metrics items={[["Sent / arrived flits",c.sentFlits+' / '+c.arrivedFlits],["Accepted / rejected",c.acceptedFlits+' / '+c.rejectedFlits],["Unique destination bytes",c.uniquePayloadBytes+' / '+result.totals.payloadBytes],["Sent valid payload",c.sentPayloadBytes+' B'],["Sent padded slots",c.sentSlotBytes+' B'],["Sender backpressure",c.backpressureTicks+' ticks']]}/>
 <h4>The operand's byte identity</h4><p><code>{result.workloadId}</code> · transfer <code>{result.transferId}</code>. Null destination positions remain unavailable; they are never silently replaced with zero.</p><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Source to destination word bytes"><table className="studio-table"><thead><tr><th>Word</th><th>Byte offset</th><th>Original value</th><th>Source bytes</th><th>Destination bytes now</th></tr></thead><tbody>{result.words.map(w=><tr key={w.id}><th>{w.id}</th><td>{w.offset}</td><td>{w.value}</td><td><code>{hex(w.bytes)}</code></td><td><code>{hex(step.destinationBytes.slice(w.offset,w.offset+4))}</code></td></tr>)}</tbody></table></div>
 <h4>Consume the delivered values</h4><div className="mn-inputs"><Matrix label="Actual accumulated C at this tick" values={step.partialOutput}/><Matrix label="Published C at this tick" values={step.published?result.finalOutput:null}/></div>{step.mac?<p><code>{step.mac.outputId}</code>: {step.mac.before} + <code>{step.mac.aId}</code> ({step.mac.a}) × <code>{step.mac.bId}</code> ({step.mac.b}) = <strong>{step.mac.after}</strong>.</p>:<p>No MAC at this tick. {step.ready?'The next eligible consumer tick follows operand readiness.':'All identified segments must arrive before any MAC.'}</p>}
 <Details title="Independent original-matrix check and final boundaries"><Matrix label="BigInt reference from original A and B" values={result.reference}/><p>Computed run status: <strong>{result.status}</strong>. This final summary describes the complete recomputed run, separate from the selected tick. Payload identity checks can succeed while changed data produces the wrong C; this independent check detects the mismatch without repairing it.</p><Metrics items={[["Operand ready",result.totals.readyTick===null?'Never':'tick '+result.totals.readyTick],["Output published",result.totals.publishedTick===null?'Never':'tick '+result.totals.publishedTick],["Link and credits drained",'tick '+result.totals.drainedTick],["MACs",String(result.totals.macs)],["Expected unique payload",result.totals.payloadBytes+' B'],["One copy's padded slots",result.totals.paddedSlotBytes+' B']]}/></Details>
 <Details title="Every physical flit and its logical segment"><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Flit identities and numeric payload"><table className="studio-table"><thead><tr><th>Flit</th><th>Segment / offset</th><th>Identity</th><th>Valid bytes / slot</th><th>Actual bytes</th></tr></thead><tbody>{result.flits.map(f=><tr key={f.sequence}><td>#{f.sequence}</td><td>{f.segment} / {f.offset}</td><td><code>{f.transferId}</code></td><td>{f.validBytes} / {input.flitBytes}</td><td><code>{hex(f.bytes)}</code></td></tr>)}</tbody></table></div></Details>
 <Details title="Assumptions and limits"><ul>{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul><p>Identities: {result.version}; source operation {result.sourceVersion}. Timing is synthetic. This is not a NoC, Ethernet, TCP, RDMA, NCCL or gem5 implementation.</p></Details>
 <div className="studio-task"><h4>Predict which boundary fails</h4><p>With one credit, add a long receiver pause. Locate the first blocked send and the credit that eventually releases it. Then omit a segment, duplicate a segment, and change data while keeping valid identity. Explain which case blocks consumption, which changes traffic only, and which publishes a wrong result.</p></div><div className="mn-actions">{onSelect&&[['on-chip-network','Finite-credit transfer'],['dma-visibility-ownership','Buffer ownership'],['sharded-matmul-ownership','Matrix ownership']].map(([id,label])=><button key={id} onClick={()=>onSelect(id)}>{label} →</button>)}</div><SourceLinks items={[{title:'gem5 Garnet: flits, buffer credits and traversal lifecycle',url:'https://www.gem5.org/documentation/general_docs/ruby/garnet-2/'}]}/>
 </div></div></section>;
}
