import {useMemo,useState} from 'react';
import {buildMemoryWorkload,memoryWorkloadDefaults,encodeMemoryWorkloadRecord,readMemoryWorkloadRecord,type MemoryWorkloadInput} from '../lib/memory-workload-bridge';
import {Control,Details,Metrics,SourceLinks,Stepper,number} from './studio-primitives';
import PortableExperiment from './portable-experiment';
import './memory-workload-explorer.css';
const hex=(bytes:readonly number[])=>bytes.map(b=>b.toString(16).padStart(2,'0')).join(' ');
function MatrixView({title,value}:{title:string;value:readonly (readonly number[])[]|null}){return <div className="memory-workload-matrix"><strong>{title}</strong>{value?<table><tbody>{value.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>:<p>No published output</p>}</div>;}
export default function MemoryWorkloadExplorer({onSelect}:{onSelect?:(id:string)=>void}){
 const[input,setInput]=useState<MemoryWorkloadInput>({...memoryWorkloadDefaults}),[cursor,setCursor]=useState(0);
 const r=useMemo(()=>buildMemoryWorkload(input),[input]),healthy=useMemo(()=>buildMemoryWorkload({...input,fault:'none'}),[input]);
 const index=Math.min(cursor,r.events.length-1),event=r.events[index],word=r.workload.selectedWord,selectedRead=r.reads.find(x=>x.wordId===word.id);
 const edit=<K extends keyof MemoryWorkloadInput>(key:K,value:MemoryWorkloadInput[K])=>{setInput(x=>({...x,[key]:value}));setCursor(0);};
 const select=<K extends keyof MemoryWorkloadInput>(key:K,label:string,choices:readonly MemoryWorkloadInput[K][],disabled=false)=><label>{label}<select disabled={disabled} value={String(input[key])} onChange={e=>edit(key,(typeof input[key]==='number'?Number(e.target.value):e.target.value) as MemoryWorkloadInput[K])}>{choices.map(v=><option key={String(v)} value={String(v)}>{String(v)}</option>)}</select></label>;
 const phase=event.kind==='admission'||event.kind==='blocked'?'admit':event.kind.startsWith('staging')?'place':event.kind==='read-complete'||event.kind==='ecc-blocked'?'check':event.kind==='compute-start'||event.kind==='compute-end'?'consume':event.kind==='write-complete'||event.kind==='host-sync'?'publish':'read';
 return <section className="memory-workload"><div className="studio-heading"><h3>One matrix, from a qualified stack to a checked result</h3><p>Follow the same signed 32-bit operand through tier placement, DRAM transactions, refresh, a declared bit fault and the actual matrix consumer. Geometry decides admission; bit faults are separately injected. This bounded computation uses no device measurements or inferred error rates.</p></div>
 <PortableExperiment storageKey="ai-atlas.memory-workload.v1" serialize={()=>encodeMemoryWorkloadRecord(input)} restore={raw=>{const next=readMemoryWorkloadRecord(raw);setInput(next);setCursor(0);return 'Restored validated workload inputs. The byte path and output were recomputed.';}}/>
 <div className="studio-layout"><aside className="studio-sidebar"><h4>Stack and placement</h4><label>Matrix specimen<select value={input.specimen} onChange={e=>{setInput(x=>({...x,specimen:e.target.value as 'two'|'three',faultWord:0}));setCursor(0);}}><option value="two">2 × 2</option><option value="three">3 × 3</option></select></label>{select('route','Bonding route',['tc-ncf','mr-muf','hybrid'])}<label>Dies per stack<select value={input.dies} onChange={e=>{const dies=Number(e.target.value) as MemoryWorkloadInput['dies'];setInput(x=>({...x,dies,selectedDie:Math.min(x.selectedDie,dies-1)}));setCursor(0);}}>{[4,8,12,16].map(n=><option key={n}>{n}</option>)}</select></label><Control label="Selected payload die" value={input.selectedDie} min={0} max={input.dies-1} onChange={v=>edit('selectedDie',v)}/><Control label="One-axis registration offset" value={input.registrationOffsetUm} min={0} max={12} step={.1} unit="µm" onChange={v=>edit('registrationOffsetUm',v)}/>{select('qualification','Synthetic qualification evidence',['synthetic-pass','not-provided','synthetic-fail'])}{select('bTier','Original B location',['hbm','host-stage','read-tier-stage'])}{select('payloadBudgetBytes','Declared destination payload budget (B)',[32,64,96,144,192])}<h4>Read schedule</h4>{select('bankPlacement','Machine bank placement',['same-bank','split-banks'])}{select('buffers','DMA staging slots',[1,2])}{select('refreshEveryNs','Assumed refresh due interval (ns; 0 = off)',[0,64,96,160])}<p>Refresh off is a scheduling counterfactual. No retention failure is generated.</p><h4>Independent fault injection</h4>{select('protection','Consumer word protection',['secded','unchecked'])}{select('fault','Persistent codeword fault',['none','single-data','double-data','triple'])}{select('faultTensor','Selected operand tensor',['A','B'])}<Control label="Selected row-major word index" value={input.faultWord} min={0} max={input.specimen==='two'?3:8} onChange={v=>edit('faultWord',v)}/><Control disabled={input.fault==='none'} label="Faulted nibble in 32-bit word" value={input.faultNibble} min={0} max={7} onChange={v=>edit('faultNibble',v)}/><p>Single: position 3. Double: 3 and 5. Triple: 1, 2 and 3 in one 8-bit codeword. Position numbering starts at 1; nibble 0 contains the least significant four data bits.</p></aside>
 <div className="studio-main"><div className="memory-workload-matrices"><MatrixView title="Original A" value={r.workload.a}/><MatrixView title="Original B" value={r.workload.b}/><MatrixView title="Independent reference C" value={r.reference}/><MatrixView title="Actually published C" value={r.finalOutput}/></div><Metrics items={[["Run outcome",r.status],["Original-matrix check",r.correct===null?'No output to check':r.correct?'Matches':'Mismatch'],["Modeled boundary duration",`${number(r.totals.durationNs)} ns`],["Healthy comparison",healthy.status==='complete'?`${number(healthy.totals.durationNs)} ns`:`${healthy.status}`]]}/>
 <h4>Admission is separate from read correctness</h4><div className="memory-workload-stack"><svg viewBox="0 0 180 240" role="img" aria-label={`Stack height ${r.qualification.heightUm} micrometers; die ${input.selectedDie} selected. Width is schematic.`}>{r.qualification.layers.map(l=><rect key={l.id} x={l.kind==='interface'?35:20} y={220-l.zMaxUm*200/r.qualification.heightUm} width={l.kind==='interface'?110:140} height={(l.zMaxUm-l.zMinUm)*200/r.qualification.heightUm} fill={l.kind==='dram-die'?(l.selected?'#c5f6d4':'#789fc9'):l.kind==='interface'?'#e9bb8c':'#aec8ce'}><title>{l.label}: {number(l.zMinUm)}–{number(l.zMaxUm)} µm</title></rect>)}</svg><div><Metrics items={[["Stack gate",r.qualification.status],["Stack height",`${number(r.qualification.heightUm)} µm`],["Modeled peak temperature",`${number(r.qualification.peakC)} °C`],["One-axis contact overlap",`${number(r.qualification.overlapFraction*100)}%`],["Allocated payload budget",`${r.placement.allocatedBytes} / ${input.payloadBudgetBytes} B`],["Selected bond gap",`${r.qualification.gapUm} µm`]]}/><p>Vertical proportions follow the stack model; width is schematic. Known-good and post-bond evidence are fixed synthetic passes. The selected qualification remains separate. A positive overlap supplies no electrical timing or fault probability.</p></div></div>
 <h4>Inspect one continuous event trace</h4><ol className="memory-workload-phases">{[['admit','Admit'],['place','Place'],['read','Issue / refresh'],['check','Decode word'],['consume','Accumulate'],['publish','Publish']].map(([id,label])=><li key={id} aria-current={phase===id?'step':undefined}>{label}</li>)}</ol><Stepper value={index} max={r.events.length-1} onChange={setCursor} label="Event"/><p role="status"><strong>{event.timeNs} ns · {event.kind}</strong> — {event.label}</p><p>Machine clock: {event.machineTimeNs===null?'not started':`${event.machineTimeNs} ns`}. Host ownership: {event.published?'output published':'no output published at this event'}.</p><MatrixView title="Actual partial sums at this event" value={event.partialOutput}/>{event.macs.length>0&&<ul>{event.macs.map(m=><li key={m.lane}>Lane {m.lane}: C[{m.row},{m.column}], k={m.k}: {m.before} + ({m.a} × {m.b}) = {m.after}</li>)}</ul>}{event.reads.length>0&&<ul>{event.reads.map(x=><li key={x.wordId}>{x.wordId}: stored bytes <code>{hex(x.read.originalBytes)}</code> → {x.read.deliveredBytes?<><code>{hex(x.read.deliveredBytes)}</code> = {x.read.deliveredValue}</>:'detected uncorrectable; no value delivered'} {x.faultInjected?'(injected selected-word fault)':''}</li>)}</ul>}
 <Details title="All executed events"><div className="studio-table-wrap" role="region" aria-label="Joined memory event table" tabIndex={0}><table className="studio-table"><thead><tr><th>Time</th><th>Event</th><th>Effect</th></tr></thead><tbody>{r.events.map(e=><tr key={e.index}><td><button onClick={()=>setCursor(e.index)}>{e.timeNs} ns</button></td><td>{e.kind}</td><td>{e.label}</td></tr>)}</tbody></table></div></Details></div></div>
 <h4>The selected operand has one byte identity</h4><p><strong>{word.id} = {word.value}</strong> · little-endian bytes <code>{hex(word.bytes)}</code> · original tier {word.sourceTier}. Machine physical word address {word.physical}; selected-stack payload address {word.stackPayloadAddress}. The explicit translation is selected die × 2³¹ + machine byte address.</p><p className="studio-note">Stack view: {word.address.bankKey}, row {word.address.parts.row}, column {word.address.parts.column}. The machine scheduler uses a separate two-bank, 1 KiB map. These views identify the same word through a declared translation; their bank layouts are not asserted to match.</p>
 {selectedRead?<><p>First completed read of {word.id} in this computed trace: {selectedRead.timeNs} ns, {selectedRead.transactionId}. The code uses eight independent (8,4) words per 32-bit operand, with 100% additional code bits. It is not vendor ECC.</p><div className="studio-table-wrap" role="region" aria-label="Selected word ECC trace" tabIndex={0}><table className="studio-table"><thead><tr><th>Nibble</th><th>Encoded positions 1 → 8</th><th>Received positions 1 → 8</th><th>Syndrome / overall parity</th><th>Decoder report</th></tr></thead><tbody>{selectedRead.read.codewords.map((bits,i)=><tr key={i} className={i===input.faultNibble&&selectedRead.faultInjected?'memory-workload-fault':undefined}><th>{i}</th><td><code>{bits.join(' ')}</code></td><td><code>{selectedRead.read.received[i].join(' ')}</code></td><td>{selectedRead.read.decoded[i].syndrome} / {selectedRead.read.decoded[i].overallParity}</td><td>{selectedRead.read.decoded[i].classification}{input.protection==='unchecked'?' (diagnostic only; bypassed)':''}</td></tr>)}</tbody></table></div><p>Delivered value: {selectedRead.read.deliveredValue??'none'}. Three flips are outside the two-error guarantee: a reported correction can still deliver the wrong data. The independent matrix check does not fix the consumer’s output.</p></>:<p>No read of the selected word executed in this run.</p>}
 <h4>Placement and timing have explicit boundaries</h4><Metrics items={[["B source reads",`${r.placement.remoteSourceReadBytes} B`],["B staging writes",`${r.placement.destinationStagingWriteBytes} B`],["Machine DRAM reads",`${r.totals.readTransactionBytes} B`],["Machine output writes",`${r.totals.writeTransactionBytes} B`],["Pre-execution staging",`${r.totals.stagingNs} ns`],["Machine elapsed time",`${r.totals.machineElapsedNs} ns`],["Refresh service observed",`${r.totals.refreshes} issued / ${r.totals.refreshBusyNs} ns`],["Executed MACs",String(r.totals.macs)],["Decoder correction reports",String(r.totals.correctedNibbles)],["Output words narrowed to int32",String(r.totals.outputNarrowedWords)]]}/><p>{r.placement.scope} Full-buffer remote B staging costs an authored 20 ns startup + 8 ns per 16 B copy before the machine clock. Host and read-tier choices use the same assumed service; neither is a product comparison. Transaction timing excludes parity transfer and ECC logic. Accumulators remain exact within this bounded fixture; output stores narrow modulo 2³².</p>
 <Details title="Machine and joined command clocks"><p>Joined time includes pre-execution B staging. Refresh busy time is clipped to the observed machine horizon; issued service reservations remain separate.</p><div className="studio-table-wrap" role="region" aria-label="Memory command clock translation" tabIndex={0}><table className="studio-table"><thead><tr><th>Command</th><th>Machine interval (ns)</th><th>Joined interval (ns)</th></tr></thead><tbody>{r.commandTimeline.map(c=><tr key={c.id}><th>{c.kind} · {c.id}</th><td>{c.machineStartNs}–{c.machineEndNs}</td><td>{c.joinedStartNs}–{c.joinedEndNs}</td></tr>)}</tbody></table></div></Details><Details title="Exact staging bytes and output words"><div className="studio-table-wrap" role="region" aria-label="Byte transfer identity ledger" tabIndex={0}><table className="studio-table"><thead><tr><th>Object</th><th>Address / time</th><th>Bytes (hexadecimal)</th></tr></thead><tbody>{r.placement.staging.map(s=><tr key={s.index}><th>B source offset {s.sourceOffset}</th><td>→ stack payload {s.destinationStackAddress}; {s.startNs}–{s.endNs} ns</td><td><code>{hex(s.bytes)}</code></td></tr>)}{r.outputWords.map(w=><tr key={w.id}><th>{w.id} = {w.value}</th><td>stack payload {w.stackPayloadAddress}</td><td><code>{hex(w.bytes)}</code></td></tr>)}</tbody></table></div></Details>
 <Details title="Scope and model assumptions"><ul>{r.assumptions.map(x=><li key={x}>{x}</li>)}</ul><p>Identities: {r.workload.id}; {r.version}; {r.scheduleModelVersion}; {r.eccModelVersion}; {r.stackModelVersion}.</p></Details><div className="studio-task"><h4>Explain three different failures</h4><p>First remove qualification: why do no commands execute? Restore it and shrink the payload allocation budget: why does staging still need the full B allocation? Then inject a double data-bit fault: locate the read that prevents publication. Compare unchecked mode and three flips with SECDED. Refresh changes the schedule but does not remove this deliberately persistent fault.</p></div>
 <div className="studio-lesson-links">{[['memory-system-qualification','Qualification evidence'],['memory-working-set-placement','Working-set placement'],['hbm-channel-generation-ras','Refresh, ECC and RAS'],['hbm-controller','Controller commands']].map(([id,label])=><button disabled={!onSelect} key={id} onClick={()=>onSelect?.(id)}>{label} →</button>)}</div>
 <SourceLinks items={[{title:'OpenTitan · independent SECDED encoder/decoder and verification artifacts',url:'https://opentitan.org/book/util/design/index.html#ecc-generator-tool'},{title:'Microchip · DDR timing parameter definitions',url:'https://onlinedocs.microchip.com/oxy/GUID-AFCB5DCC-964F-4BE7-AA46-C756FA87ED7B-en-US-21/GUID-A29420D1-4E36-4920-B9BB-DD0B63F5E787.html'}]}/></section>;
}
