import {useEffect,useMemo,useRef,useState} from 'react';
import {Control,Details,Metrics,SourceLinks,number} from './studio-primitives';
import {createLifecycleRun,lifecycleVocabulary,lifecycleFingerprint,type LifecycleRun} from '../lib/model-lifecycle';
import {type DistributedTrainingRun} from '../lib/model-lifecycle-distributed';
import {createLifecycleExposureJournal} from '../lib/model-lifecycle-workspace';
import {createLifecycleServingRun,createDistributedServingRun,stepLifecycleServingRun,finishLifecycleServingRun,cancelLifecycleServingRequest,serializeLifecycleServingRun,importLifecycleServingWorkspace,retainServingExposure,servingMemory,servingWeights,servingSourceCheckpoint,servingIsFinished,servingExampleOptions,lifecycleServingDefaults,lifecycleServingLimits,type LifecycleServingRun,type LifecycleServingConfig} from '../lib/model-lifecycle-serving';
import {verifyLifecycleDraft,referenceLifecycleGreedy} from '../lib/model-lifecycle-speculation';
import './model-lifecycle-serving.css';
const message=(e:unknown)=>e instanceof Error?e.message:'Operation failed';
const words=(tokens:number[])=>tokens.map(t=>lifecycleVocabulary[t]).join(' ');
export type ModelLifecycleServingProps={checkpoint?:LifecycleRun;distributedCheckpoint?:DistributedTrainingRun;onSelect?:(id:string)=>void};
export default function ModelLifecycleServing({checkpoint,distributedCheckpoint,onSelect}:ModelLifecycleServingProps){
 const[journal]=useState(()=>{try{return createLifecycleExposureJournal(localStorage);}catch{return createLifecycleExposureJournal();}});
 const[run,setRun]=useState(()=>retainServingExposure(distributedCheckpoint?createDistributedServingRun(distributedCheckpoint):createLifecycleServingRun(checkpoint),journal)),[draft,setDraft]=useState<LifecycleServingConfig>(()=>structuredClone(lifecycleServingDefaults)),[selected,setSelected]=useState('request-1'),[draftTokens,setDraftTokens]=useState<number[]>([1,7]),[status,setStatus]=useState('Import a trained checkpoint, or inspect the initialized model. Advance one scheduling iteration to see requests arrive.'),[seed,setSeed]=useState(7),revision=useRef(0),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const put=(next:LifecycleServingRun)=>{revision.current++;setRun(retainServingExposure(next,journal));};
 const act=(fn:()=>LifecycleServingRun,text:string)=>{try{put(fn());setStatus(text);}catch(e){setStatus(`Current workspace preserved. ${message(e)}`);}};
 const importFile=async(file:File|undefined)=>{if(!file)return;const expected=revision.current;try{if(file.size>lifecycleServingLimits.maxBytes)throw Error('File exceeds the bounded size limit');const text=await file.text();if(!mounted.current)return;const next=importLifecycleServingWorkspace(text,journal,expected,revision.current,draft);put(next);setDraft(next.config);setSelected(next.requests[0].spec.id);setStatus('Validated source checkpoint and serving trace imported. Saved commands were replayed before replacing this workspace.');}catch(e){if(mounted.current)setStatus(`Import rejected; current workspace preserved. ${message(e)}`);}};
 const save=()=>{try{const text=serializeLifecycleServingRun(run),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`atlas-serving-iteration-${run.tick}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Exported full source checkpoint, serving configuration, request RNG, KV state and event commands.');}catch(e){setStatus(message(e));}};
 const memory=servingMemory(run),request=run.requests.find(r=>r.spec.id===selected)??run.requests[0],lane=run.lastIteration?.lanes.find(l=>l.requestId===request.spec.id),cache=request.cache??lane?.cacheAfter,last=cache?.last,finished=servingIsFinished(run),source=servingSourceCheckpoint(run);
 const speculation=useMemo(()=>verifyLifecycleDraft(servingWeights(run),request.prompt,draftTokens),[run.source,request.prompt,draftTokens]),fullGreedy=useMemo(()=>referenceLifecycleGreedy(servingWeights(run),request.prompt,request.spec.maxNewTokens),[run.source,request.prompt,request.spec.maxNewTokens]);
 const totals=useMemo(()=>({completed:run.requests.filter(r=>r.status==='complete').length,generated:run.requests.reduce((s,r)=>s+r.output.length,0)}),[run.requests]);
 const changeRequest=(i:number,patch:Partial<LifecycleServingConfig['requests'][number]>)=>setDraft({...draft,requests:draft.requests.map((r,j)=>j===i?{...r,...patch}:r)});
 return <section className="lifecycle-serving"><div className="studio-heading"><h3>From a learned checkpoint to a serving queue</h3><p>The same 423-parameter decoder generates real tokens. Keys and values from processed positions are reused while finite capacity determines which requests may enter the next logical batch.</p></div>
 <details className="studio-details"><summary>Serving workspace · iteration {run.tick}</summary><p>Import Model lifecycle, Distributed learning, or this serving record. A distributed import uses its current committed weights and retains its distinct update history. Inference changes no learned weights.</p><div className="mls-actions"><button onClick={save}>Export full record</button><label className="studio-file">Import checkpoint or record<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';void importFile(file);}}/></label>{checkpoint&&<button onClick={()=>act(()=>createLifecycleServingRun(checkpoint,draft),'Loaded the supplied lifecycle checkpoint and new serving configuration.')}>Use supplied checkpoint</button>}</div><p className="studio-note">{source.finalOpened?'Final-test exposure was already recorded. Importing an older checkpoint does not clear that disclosure.':'No final-test exposure is recorded for this source/browser journal.'} This experience serves training/development prompts and opens no final cases.</p></details>
 <p role="status" aria-live="polite" className="studio-note">{status}</p>
 <div className="studio-layout"><aside className="studio-sidebar"><h4>Next queue configuration</h4><label>Admission policy<select value={draft.policy} onChange={e=>setDraft({...draft,policy:e.target.value as LifecycleServingConfig['policy']})}><option value="continuous">Reconsider admission every iteration</option><option value="static">Wait for the current group to drain</option></select></label><Control label="Logical batch slots" min={1} max={3} value={draft.batchSlots} onChange={v=>setDraft({...draft,batchSlots:v as 1|2|3})}/><label>KV representation<select value={draft.kvFormat} onChange={e=>setDraft({...draft,kvFormat:e.target.value as LifecycleServingConfig['kvFormat']})}><option value="binary64">Binary64 K/V · 96 bytes / position</option><option value="int4-symmetric">Signed symmetric 4-bit K/V + scales · 22 bytes / position</option></select></label><Control label="Fixed KV byte capacity" unit="× 96 bytes" min={4} max={24} value={draft.kvPositions} onChange={v=>setDraft({...draft,kvPositions:v})}/><Control label="Prefill chunk per lane" unit="tokens" min={1} max={8} value={draft.prefillChunk} onChange={v=>setDraft({...draft,prefillChunk:v})}/><label>Token selection<select value={draft.decoding} onChange={e=>setDraft({...draft,decoding:e.target.value as LifecycleServingConfig['decoding']})}><option value="greedy">Greedy maximum probability</option><option value="sample">Sample full vocabulary</option></select></label><Control label="Independent sampling seed" min={1} max={300} value={draft.samplingSeed} onChange={v=>setDraft({...draft,samplingSeed:v})}/>
 <Details title="Choose three requests and arrivals">{draft.requests.map((r,i)=><fieldset key={r.id}><legend>{r.id}</legend><label>Prompt source<select value={r.exampleId} onChange={e=>changeRequest(i,{exampleId:e.target.value})}>{servingExampleOptions.map(e=><option key={e.id} value={e.id}>{e.split} · {e.domain} · {words(e.tokens.slice(0,e.answerPosition+1))}</option>)}</select></label><Control label={`${r.id} arrival`} unit="iterations" min={0} max={12} value={r.arrivalTick} onChange={v=>changeRequest(i,{arrivalTick:v})}/><Control label={`${r.id} output limit`} unit="tokens" min={1} max={2} value={r.maxNewTokens} onChange={v=>changeRequest(i,{maxNewTokens:v as 1|2})}/></fieldset>)}</Details>
 <button onClick={()=>act(()=>run.source.kind==='lifecycle'?createLifecycleServingRun(run.source.checkpoint,draft):importLifecycleServingWorkspace(JSON.stringify(run.source.checkpoint),journal,revision.current,revision.current,draft),'Started a fresh queue at the same frozen model weights. The displayed draft configuration is now applied.')}>Apply and restart queue</button><p className="studio-note">Controls apply when restarting or importing a source checkpoint. Current queue: {run.config.policy}, {run.config.batchSlots} slots, {run.config.kvPositions*96} bytes, {run.config.kvFormat} KV, prefill chunk {run.config.prefillChunk}.</p><Details title="Initialize a new untrained model"><Control label="Model seed" min={1} max={30} value={seed} onChange={setSeed}/><button onClick={()=>act(()=>createLifecycleServingRun(createLifecycleRun({seed}),draft),'Initialized untrained weights. Poor answers are expected; import a learned checkpoint to compare.')}>Initialize new model and queue</button></Details></aside>
 <div className="studio-main"><Metrics items={[["Scheduling iterations",String(run.tick)],["Completed requests",`${totals.completed} / ${run.requests.length}`],["Generated tokens",String(totals.generated)],["Occupied KV positions",`${memory.occupiedPositions} / ${memory.capacityPositions}`],["Reserved positions",`${memory.reservedPositions} / ${memory.capacityPositions}`],["Weight identity",lifecycleFingerprint(servingWeights(run))]]}/>
 <div className="mls-actions"><button disabled={finished} onClick={()=>act(()=>stepLifecycleServingRun(run),'Advanced one synthetic scheduling iteration; displayed outputs and KV states are actual decoder computations.')}>Advance one iteration</button><button disabled={finished} onClick={()=>act(()=>finishLifecycleServingRun(run),'Completed the bounded queue; remaining KV reservations were released.')}>Finish bounded queue</button></div>
 <p className="studio-note">One tick is an authored scheduling boundary, not a measured millisecond or GPU cycle. Lanes are computed serially in JavaScript. Batch changes illustrate admission and dependencies; they establish no device throughput ranking.</p>
 <div className="mls-capacity" aria-label={`KV memory: ${memory.occupiedPositions} occupied, ${memory.reservedPositions} reserved, ${memory.capacityPositions} capacity`}>{Array.from({length:memory.capacityPositions},(_,i)=><span key={i} className={i<memory.occupiedPositions?'occupied':i<memory.reservedPositions?'reserved':'free'}/>)}</div><p>{memory.occupiedPayloadBytes} bytes of live KV numeric payload; {memory.reservedPayloadBytes} bytes of reserved capacity; {memory.capacityPayloadBytes} bytes total. This format uses {memory.bytesPerPosition} payload bytes per position. Reserve prompt length + output limit − 1 positions: the last output needs no new cache entry unless it is fed back to predict another token.</p>
 <div className="mls-requests">{run.requests.map(r=>{const ex=servingExampleOptions.find(e=>e.id===r.spec.exampleId)!;return <article key={r.spec.id} className={r.spec.id===request.spec.id?'selected':''}><h4>{r.spec.id} · {r.status}</h4><code>{words(r.prompt)}</code><p>{ex.split} / {ex.domain} · reservation {r.reservation} positions</p><p>Generated: <strong>{r.output.length?words(r.output):'none yet'}</strong>. Expected first answer: {lifecycleVocabulary[ex.answer]}.{r.output.length>0&&` First-answer match: ${r.output[0]===ex.answer?'yes':'no'}.`}</p><p>Arrival {r.spec.arrivalTick}; admitted {r.admittedAt??'pending'}; first token {r.firstTokenAt??'pending'}; terminal {r.completedAt??'pending'}.{r.firstTokenAt!==null&&` First-token delay ${r.firstTokenAt-r.spec.arrivalTick} synthetic iterations.`}</p>{r.stopReason&&<p>{r.stopReason}</p>}<div className="mls-actions"><button aria-pressed={r.spec.id===request.spec.id} onClick={()=>setSelected(r.spec.id)}>Inspect request</button><button disabled={!['pending','queued','active'].includes(r.status)} onClick={()=>act(()=>cancelLifecycleServingRequest(run,r.spec.id),'Cancelled request; its live KV allocation and reservation were released.')}>Cancel request</button></div></article>;})}</div>
 {run.lastIteration&&<Details title={`Last logical batch · iteration ${run.lastIteration.tick}`}><p>Peak occupied positions {run.lastIteration.occupiedPeak}; reserved {run.lastIteration.reservedPeak}. All lanes complete before reservations are released. New requests enter at the next boundary.</p><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Actual prefill and decode steps"><table className="studio-table"><thead><tr><th>Request</th><th>Phase</th><th>Processed input</th><th>KV positions</th><th>New output</th><th>Maximum probability difference vs binary64</th><th>Same greedy token at this prefix?</th></tr></thead><tbody>{run.lastIteration.lanes.map(l=><tr key={l.requestId}><td>{l.requestId}</td><td>{l.phase}</td><td>{words(l.processedTokens)}</td><td>{l.kvBefore} → {l.kvAfter}</td><td>{l.generatedToken===null?'prefill incomplete':lifecycleVocabulary[l.generatedToken]}</td><td>{l.referenceMaxError.toExponential(2)}</td><td>{l.greedyTokenMatchesReference===null?'no output yet':l.greedyTokenMatchesReference?'yes':'no'}</td></tr>)}</tbody></table></div></Details>}
 <Details title={`Actual keys, values and probabilities · ${request.spec.id}`}>{cache&&last?<><p>KV format: {run.config.kvFormat}. Binary64 greedy output from the original prompt: <strong>{words(fullGreedy.output)}</strong>. The displayed queue may use sampling or approximate KV; compare its output with the explicitly named rule.</p><p>{request.cache?'Live serving cache.':'Last-iteration diagnostic snapshot after the live cache was released.'} Diagnostic snapshots, object overhead, source checkpoint and model weights are outside the modeled KV arena.</p><p>Position {last.position}; input {lifecycleVocabulary[last.inputToken]}. Query [{last.query.map(v=>number(v,4)).join(', ')}]. This token writes 12 K/V scalars and logically reads {last.kvReadScalars} K/V scalars across {cache.tokens.length} positions. The dense projections use 342 multiply-add pairs; attention uses {last.attentionMultiplyAdds}. Normalization, activation and softmax arithmetic are additional.</p><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Cached keys and values"><table className="studio-table"><thead><tr><th>Position/token</th><th>Key vector</th><th>Value vector</th><th>Current attention</th><th>Scale / packed bytes</th></tr></thead><tbody>{cache.tokens.map((t,i)=><tr key={i}><td>{i}: {lifecycleVocabulary[t]}</td><td>{cache.keys[i].map(v=>number(v,4)).join(', ')}</td><td>{cache.values[i].map(v=>number(v,4)).join(', ')}</td><td>{number(last.attention[i],6)}</td><td>{cache.keyEncoding[i]?<>K: {number(cache.keyEncoding[i]!.scale,6)} / {cache.keyEncoding[i]!.packed.join(', ')}<br/>V: {number(cache.valueEncoding[i]!.scale,6)} / {cache.valueEncoding[i]!.packed.join(', ')}</>:'binary64; no quantization'}</td></tr>)}</tbody></table></div><div className="mls-probabilities">{last.probabilities.map((p,i)=><div key={i}><code>{lifecycleVocabulary[i]}</code><meter min="0" max="1" value={p} aria-label={`${lifecycleVocabulary[i]} probability`}/><span>{number(p,6)}</span></div>)}</div></>:<p>Advance a batch containing this request to inspect its actual KV values. A completed request outside the latest batch has released its cache; its output and event record remain.</p>}</Details>
 <Details title="Authored draft → target verification → cache commit"><p>Propose two tokens for {request.spec.id}. These are learner-authored guesses, not a learned draft model. The verifier always uses the actual binary64 target greedy rule, independently of queue sampling or KV quantization. It computes conditional proposal positions, accepts only the matching prefix, discards invalid speculative state and produces actual target fallbacks.</p><div className="mls-actions">{draftTokens.map((token,i)=><label key={i}>Proposed token {i+1}<select value={token} onChange={e=>setDraftTokens(draftTokens.map((v,j)=>j===i?Number(e.target.value):v))}>{lifecycleVocabulary.map((v,j)=><option key={j} value={j}>{v}</option>)}</select></label>)}</div><Metrics items={[["Accepted proposal prefix",`${speculation.accepted} / 2`],["Verified output",words(speculation.output)],["Independent greedy reference",words(speculation.referenceOutput)],["Discarded tentative KV positions",String(speculation.discardedKvPositions)]]}/><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Draft target verification"><table className="studio-table"><thead><tr><th>Position</th><th>Proposed prefix</th><th>Proposal</th><th>Conditional target greedy</th><th>Proposal probability</th><th>Disposition</th></tr></thead><tbody>{speculation.verificationRows.map(r=><tr key={r.index}><td>{r.index}</td><td>{words(r.conditioningTokens)}</td><td>{lifecycleVocabulary[r.proposal]}</td><td>{lifecycleVocabulary[r.targetGreedyToken]}</td><td>{number(r.probabilities[r.proposal],6)}</td><td>{r.disposition}</td></tr>)}</tbody></table></div><p>Initial target cache: {words(speculation.initialCache.tokens)}. Tentative cache: {words(speculation.tentativeCache.tokens)}. Committed cache: {words(speculation.committedCache.tokens)}.</p>{speculation.fallbackSteps.map(f=><p key={f.index}>Fallback at output {f.index}: {lifecycleVocabulary[f.token]}, computed from {words(f.conditioningTokens)} with target probability {number(f.probabilities[f.token],6)}.</p>)}<ol>{speculation.events.map((e,i)=><li key={i}>{e}</li>)}</ol><p>Processed target positions: {speculation.processedTargetPositions.prefill} prefill + {speculation.processedTargetPositions.tentative} tentative + {speculation.processedTargetPositions.recovery} recovery. The output limit is two; no bonus token is generated. This exact greedy verification is distinct from stochastic speculative sampling, which requires proposal probabilities and a corrected rejection distribution. No learned draft, parallel kernel or measured acceleration is claimed. Proposal selectors are a diagnostic preview; the serving record preserves the queue separately.</p></Details>
 <Details title="Arrival, admission, generation and release trace"><ol className="mls-events">{run.events.map(e=><li key={e.sequence}><strong>{e.tick} · {e.kind} · {e.requestIds.join(', ')||'scheduler'}</strong> {e.message} <small>{e.occupiedPositions} occupied / {e.reservedPositions} reserved positions</small></li>)}</ol></Details>
 <Details title="Model assumptions and a useful comparison"><p>Set one request to emit one token and another to emit two, then compare continuous admission with waiting for the whole group to drain. Change KV capacity until a queued request must wait. A request larger than total capacity is rejected explicitly. Conservative worst-case reservations prevent mid-generation capacity deadlock; this is not paged allocation, preemption or prefix sharing.</p><p>Binary64 cache reuse preserves the same causal decoder arithmetic within numerical tolerance. The optional 4-bit cache quantizes each six-coordinate K or V row separately with scale max(abs(row))/7, nearest integer ties away from zero, signed codes −7…7, and two codes packed per byte. Dequantization changes attention numerically and can change outputs. Each row has a binary64 scale; total per-position payload is 6 packed code bytes + 16 scale bytes = 22 bytes. Zero rows use scale 1. This authored symmetric format is not KIVI’s asymmetric grouping algorithm. Each request has an independent sampling stream, so scheduling order does not change its random draws. Greedy/sample output quality still depends on the imported learned weights. Training and development prompt answers are visible feedback, not untouched-test evidence.</p><p>Binary64 KV payload is 2 × 1 layer × 1 head × 6 coordinates × 8 bytes = 96 bytes per processed position. The fixed byte budget is unchanged when choosing the 22-byte approximate format; more positions can then be reserved. Packed codes are actually encoded and decoded; reconstructed vectors remain diagnostic/runtime values outside this declared packed-payload budget. Logical vector reads/writes and multiply-add counts are explicit arithmetic accounting, not HBM transactions, JavaScript heap measurements or elapsed time.</p></Details>
 {onSelect&&<div className="mls-actions">{['kv-cache','scheduler','serving','tiny-causal-decoder','checkpoint'].map(id=><button key={id} onClick={()=>onSelect(id)}>{id.replaceAll('-',' ')}</button>)}</div>}
 <SourceLinks items={[{title:'Transformers cache mechanics and positions',url:'https://huggingface.co/docs/transformers/v4.57.1/cache_explanation'},{title:'Orca: iteration-level scheduling',url:'https://www.usenix.org/conference/osdi22/presentation/yu'},{title:'PagedAttention: generation phases and KV capacity',url:'https://arxiv.org/html/2309.06180v1'},{title:'KIVI: quantization error and cache representation',url:'https://arxiv.org/html/2402.02750v2'},{title:'Speculative decoding: target verification and correction',url:'https://proceedings.mlr.press/v202/leviathan23a.html'}]}/>
 </div></div></section>;
}
