import {useEffect,useMemo,useRef,useState} from 'react';
import {Control,Details,Metrics,SourceLinks,number} from './studio-primitives';
import {createLifecycleRun,inspectLifecycleForward,lifecycleExamples,lifecycleParameterName,lifecycleFingerprint,type LifecycleRun} from '../lib/model-lifecycle';
import {createDistributedTrainingRun,beginDistributedRound,beginDistributedCollective,computeDistributedGradientShard,submitDistributedGradientShard,inspectDistributedCollective,computeRankContribution,submitRankContribution,failDistributedRank,restartDistributedRank,commitDistributedRound,centralizedDistributedReference,inspectDistributedReduction,importDistributedWorkspace,retainDistributedExposure,serializeDistributedTrainingRun,distributedLifecycleDefaults,distributedLifecycleLimits,type DistributedConfig,type DistributedTrainingRun} from '../lib/model-lifecycle-distributed';
import {createLifecycleExposureJournal} from '../lib/model-lifecycle-workspace';
import './model-lifecycle-distributed.css';
const error=(e:unknown)=>e instanceof Error?e.message:'Operation failed.';
function accuracy(weights:number[],domain:'copy'|'swap'){return lifecycleExamples('development',domain).filter(e=>{const lp=inspectLifecycleForward(weights,e.tokens.slice(0,-1)).logProbabilities[e.answerPosition];return lp.indexOf(Math.max(...lp))===e.answer;}).length;}
export type DistributedModelLearningProps={checkpoint?:LifecycleRun;onSelect?:(id:string)=>void;onServing?:(run:DistributedTrainingRun)=>void};
export default function DistributedModelLearning({checkpoint,onSelect,onServing}:DistributedModelLearningProps){
 const[journal]=useState(()=>{try{return createLifecycleExposureJournal(localStorage);}catch{return createLifecycleExposureJournal();}});
 const[run,setRun]=useState(()=>retainDistributedExposure(createDistributedTrainingRun(checkpoint),journal)),[config,setConfig]=useState<DistributedConfig>(distributedLifecycleDefaults),[seed,setSeed]=useState(7),[parameter,setParameter]=useState(0),[status,setStatus]=useState('Choose an objective and rank split, then reserve four training examples.'),revision=useRef(0),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const put=(next:DistributedTrainingRun)=>{revision.current++;setRun(retainDistributedExposure(next,journal));};
 const act=(fn:()=>DistributedTrainingRun,message:string)=>{try{put(fn());setStatus(message);}catch(e){setStatus(`Current workspace preserved. ${error(e)}`);}};
 const ownership=useMemo(()=>run.round?inspectDistributedCollective(run):null,[run]);
 const round=run.round,collecting=round?.phase==='collecting',reduction=useMemo(()=>round?inspectDistributedReduction(run):null,[run,round]),reference=useMemo(()=>round?centralizedDistributedReference(run):null,[run,round]),dev=useMemo(()=>({copy:accuracy(run.state.weights,'copy'),swap:accuracy(run.state.weights,'swap')}),[run.state.weights]);
 const importFile=async(file:File|undefined)=>{if(!file)return;const before=revision.current;try{if(file.size>distributedLifecycleLimits.maxBytes)throw Error('Record exceeds the bounded size limit.');const text=await file.text();if(!mounted.current)return;const next=importDistributedWorkspace(text,journal,before,revision.current,config);put(next);setConfig(next.config);setStatus('Validated record imported. A source lifecycle checkpoint starts a separate four-example distributed branch.');}catch(e){if(mounted.current)setStatus(`Import rejected; current workspace preserved. ${error(e)}`);}};
 const save=()=>{try{const text=serializeDistributedTrainingRun(run),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`atlas-distributed-round-${run.commits}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Exported source checkpoint, rank attempts, optimizer, RNG, reserved batch and event history.');}catch(e){setStatus(error(e));}};
 return <section className="distributed-model-learning"><div className="studio-heading"><h3>One model update across uneven ranks</h3><p>Each rank differentiates the same 423-parameter decoder on its assigned training examples. A failed rank holds the optimizer at the previous checkpoint until every owned gradient shard is ready. Owners update their own optimizer slices, then every rank reconstructs the updated model.</p></div>
 <details className="studio-details"><summary>Distributed workspace · {run.commits} committed updates</summary><p>Import a full checkpoint from Model lifecycle or restore this complete distributed record. The four-example branch retains the source optimizer moments and RNG, with its own explicit cursor and event history.</p><div className="dml-actions"><button onClick={save}>Export record</button><label className="studio-file">Import checkpoint or record<input type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';void importFile(f);}}/></label>{checkpoint&&<button onClick={()=>act(()=>createDistributedTrainingRun(checkpoint,config),'Loaded the supplied lifecycle checkpoint; no distributed update has committed.')}>Use supplied lifecycle checkpoint</button>}</div></details>
 {onServing&&<div className="dml-actions"><button disabled={Boolean(collecting)} onClick={()=>{const next=retainDistributedExposure(run,journal);put(next);onServing(structuredClone(next));}}>Serve committed checkpoint</button></div>}
 <p className="studio-note" role="status" aria-live="polite">{status}</p><div className="studio-layout"><aside className="studio-sidebar"><fieldset disabled={Boolean(collecting)}><legend>Next global batch</legend><label>Rank assignment<select value={config.partition} onChange={e=>setConfig({...config,partition:e.target.value as DistributedConfig['partition']})}>{['1+3','2+2','3+1','1+1+2'].map(p=><option key={p} value={p}>{p} examples</option>)}</select></label><label>Global objective weighting<select value={config.weighting} onChange={e=>setConfig({...config,weighting:e.target.value as DistributedConfig['weighting']})}><option value="token">Each included token equally</option><option value="sample">Each sequence mean equally</option></select></label><label>Supervised targets<select value={config.objective} onChange={e=>setConfig({...config,objective:e.target.value as DistributedConfig['objective']})}><option value="next-token">All shifted next tokens</option><option value="response-only">Answer and EOS only</option></select></label><label>Training domain<select value={config.domain} onChange={e=>setConfig({...config,domain:e.target.value as 'copy'|'swap'})}><option value="copy">Copy</option><option value="swap">Swap</option></select></label><label>Batch selection<select value={config.batchPolicy} onChange={e=>setConfig({...config,batchPolicy:e.target.value as DistributedConfig['batchPolicy']})}><option value="unequal-lengths">Seeded: one short, three long</option><option value="seeded">Seeded draws from full training pool</option></select></label><button disabled={run.commits>=24} onClick={()=>act(()=>beginDistributedRound(run,config),'Reserved four actual training examples. No optimizer update until the rank barrier is complete.')}>Reserve next batch</button></fieldset>
 <Details title="Start from new random weights"><Control label="Initialization seed" min={1} max={30} value={seed} onChange={setSeed}/><button onClick={()=>act(()=>createDistributedTrainingRun(createLifecycleRun({seed}),config),'New source checkpoint initialized. The previous record can only be recovered if exported.')}>Initialize new branch</button></Details><p className="studio-note">Optimizer: {run.sourceCheckpoint.config.optimizer}; learning rate {run.sourceCheckpoint.config.learningRate}; global clipping norm {run.sourceCheckpoint.config.clipNorm}. Import a lifecycle checkpoint to carry a trained model and its actual optimizer state.</p></aside>
 <div className="studio-main"><Metrics items={[["Distributed commits",String(run.commits)],["Optimizer step",String(run.state.optimizerStep)],["Reserved examples",String(run.dataDraws)],["Copy development",`${dev.copy} / 8`],["Swap development",`${dev.swap} / 8`],["Weight identity",lifecycleFingerprint(run.state.weights)]]}/>
 {!round?<div className="studio-task"><h4>Predict before computing</h4><p>With one short sequence on rank 0 and three long sequences on rank 1, should the two local means receive equal weight? Reserve a batch, inspect its denominators, then fail a submitted rank before trying to commit.</p></div>:<><p><strong>Round {round.number}:</strong> {round.phase==='committed'?'one optimizer step committed':`${reduction!.received} / ${reduction!.expected} current rank contributions; weights are frozen`}. Reserved RNG advances only when choosing the batch; retrying a rank reuses the same examples and weights.</p>
 <div className="dml-ranks">{round.ranks.map(r=><article key={r.rank} className={`dml-rank ${r.status}`}><h4>Rank {r.rank} · attempt {r.attempt}</h4><p>{r.status} · {r.exampleIds.length} examples</p><ul>{r.exampleIds.map((id,i)=>{const e=lifecycleExamples('train',round.config.domain).find(x=>x.id===id)!;return <li key={i}><code>{e.text}</code><small>{id} · {round.config.objective==='response-only'?2:e.tokens.length-1} targets</small></li>;})}</ul><div className="dml-actions"><button disabled={!collecting||r.status!=='ready'} onClick={()=>act(()=>submitRankContribution(run,computeRankContribution(run,r.rank)),`Rank ${r.rank} computed and submitted its actual gradient numerator.`)}>Compute and submit</button><button disabled={!collecting||r.status==='failed'} onClick={()=>act(()=>failDistributedRank(run,r.rank),`Rank ${r.rank} failed. Its previous contribution is excluded from this uncommitted round.`)}>Fail rank</button><button disabled={!collecting||r.status!=='failed'||r.attempt>=9} onClick={()=>act(()=>restartDistributedRank(run,r.rank),`Rank ${r.rank} restarted; compute its replacement contribution at the same checkpoint.`)}>Restart</button></div></article>)}</div>
 <div className="dml-collective"><h4>Reduce-scatter → owner update → all-gather</h4><p>423 real parameters use {round.ranks.length} rank-indexed blocks. The two-rank case pads one unused slot with zero; padding is never a trainable parameter. The global denominator remains {reduction!.denominator || 'pending'}, regardless of shard length.</p>
 <div className="dml-actions"><button disabled={!collecting||!reduction!.complete||Boolean(round.collective)} onClick={()=>act(()=>beginDistributedCollective(run),'Reserved parameter ownership. Reduce each owner’s slice before the optimizer barrier.')}>Begin reduce-scatter</button>{ownership!.owners.map(p=><button key={p.owner} disabled={!collecting||!round.collective||Boolean(round.collective.gradientShards[p.owner])} onClick={()=>act(()=>submitDistributedGradientShard(run,computeDistributedGradientShard(run,p.owner)),`Owner ${p.owner} received its actual reduced slice. Model weights are still frozen.`)}>Reduce owner {p.owner}: {p.start}–{p.end-1}</button>)}</div>
 <div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Owned gradient and optimizer shards"><table className="studio-table"><thead><tr><th>Owner</th><th>Real parameters</th><th>Gradient slice</th><th>Owned optimizer scalars</th><th>Model reconstruction</th></tr></thead><tbody>{ownership!.memory.map(m=><tr key={m.owner}><td>{m.owner}</td><td>{m.ownedParameters} + {m.paddedSlots} padding</td><td>{round.collective?.gradientShards[m.owner]?'received':'waiting'}</td><td>{m.ownedOptimizerScalars} (m + v)</td><td>{round.collective?.phase==='gathered'?'423 weights + 423 gradient values':'waiting for commit'}</td></tr>)}</tbody></table></div><p>{ownership!.received} / {ownership!.expected} owned shards ready. One shared norm sets the clipping factor for every owner. A failed rank invalidates all pending shards, including shards already received from other owners.</p>
 <Details title="Logical transfers and the selected parameter"><p>These are direct sender-to-owner or owner-to-replica copies in one browser, using eight bytes per declared binary64 slot. The three phases include a gradient all-gather for inspection as well as the updated-weight all-gather. They are not a network algorithm, measured traffic, compressed checkpoint size or measured memory saving.</p><p>Logical payload so far: {ownership!.logicalBytes} bytes; {ownership!.transfers.length} remote copies. Full source snapshots and diagnostic arrays are also retained by this teaching implementation.</p><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Collective transfer payloads"><table className="studio-table"><thead><tr><th>Phase</th><th>Route</th><th>Range</th><th>Selected index {parameter}</th><th>Bytes</th></tr></thead><tbody>{ownership!.transfers.map((t,i)=><tr key={i}><td>{t.phase}</td><td>{t.from} → {t.to}</td><td>[{t.start}, {t.end}) + {t.paddingZeros} zero</td><td>{parameter>=t.start&&parameter<t.end?number(t.values[parameter-t.start],8):'outside slice'}</td><td>{t.logicalBytes}</td></tr>)}</tbody></table></div></Details></div>
 <div className="dml-barrier"><p><strong>Optimizer commit barrier</strong> · {round.phase==='committed'?'closed after one commit':ownership!.received===ownership!.expected?'all current owned shards received':'waiting for current rank contributions and owned shards'}</p><button disabled={!collecting||!reduction!.complete||ownership!.received!==ownership!.expected} onClick={()=>act(()=>commitDistributedRound(run),'Committed owner-local updates and reconstructed every replica from the owned shards. The centralized reference agrees within 1e−9.')}>Update owners and all-gather</button></div>
 <Details title="Inspect a real parameter gradient and denominator"><Control label="Parameter index" value={parameter} min={0} max={422} onChange={setParameter}/><p><code>{lifecycleParameterName(parameter)}</code>. Token weighting sums target losses; sample weighting first averages each sequence’s target loss, then gives each sequence equal weight.</p><div className="studio-table-wrap" tabIndex={0} role="region" aria-label="Per-rank actual gradient numerators"><table className="studio-table"><thead><tr><th>Rank</th><th>Examples</th><th>Targets</th><th>Weight denominator</th><th>Loss numerator</th><th>Gradient numerator</th><th>Local mean gradient</th></tr></thead><tbody>{round.ranks.map(r=>{const c=r.contribution;return <tr key={r.rank}><td>{r.rank}</td><td>{r.exampleIds.length}</td><td>{c?.tokens??'pending'}</td><td>{c?.denominator??'pending'}</td><td>{c?number(c.lossSum,6):'pending'}</td><td>{c?number(c.gradientSum[parameter],8):'pending'}</td><td>{c?number(c.gradientSum[parameter]/c.denominator,8):'pending'}</td></tr>;})}</tbody></table></div>
 <Metrics items={[["Received gradient mean",number(reduction!.gradient[parameter],8)],["Unweighted rank mean",number(reduction!.naive[parameter],8)],["Full centralized gradient",number(reference!.gradient[parameter],8)],["Before weight",number(round.before.weights[parameter],8)],["Current weight",number(run.state.weights[parameter],8)],["Centralized after weight",number(reference!.state.weights[parameter],8)]]}/><p>The received mean is incomplete until every rank contributes. The centralized values are a separate full-batch calculation at the same pre-update checkpoint.</p>{run.lastCommit&&run.lastCommit.roundId===round.id&&<p>Maximum gradient difference from centralized reference: {run.lastCommit.referenceMaxGradientError.toExponential(3)}. Maximum weight difference: {run.lastCommit.referenceMaxWeightError.toExponential(3)}. Equal-rank versus weighted gradient difference: {run.lastCommit.naiveMaxGradientError.toExponential(3)}. Global gradient norm {number(run.lastCommit.gradientNorm,6)}; clip multiplier {number(run.lastCommit.clipScale,6)}.</p>}</Details>
 <Details title="Failure, restart and commit event trace"><ol className="dml-events">{round.events.map(e=><li key={e.sequence}><strong>{e.sequence} · {e.kind}</strong> {e.message}</li>)}</ol></Details></>}
 <Details title="What this experiment establishes"><p>Ranks are simulated actors in one browser. Their gradients come from actual differentiable model computations, not supplied constants. The barrier, attempt identity and restart policy are authored transaction rules; they are not a claim that a production collective automatically survives a failed worker.</p><p>Only declared training examples enter this update. Development accuracy is feedback. No final-test cases are opened here. {run.sourceCheckpoint.finalOpened?'Final-test exposure was already recorded and remains disclosed across imports.':'This source checkpoint has no recorded final-test exposure.'} Payload, network latency, hardware FLOPs and distributed wall-clock speed are not measured. Duplicate and stale contributions are rejected; the record is schema-checked teaching state, not authenticated scientific evidence.</p><p>For token weighting, global gradient = sum of target-gradient numerators / total targets. For sample weighting, numerator = sum of per-sequence mean gradients and denominator = sequence count. Clip once after the complete reduction, then advance each retained optimizer slice at the same step. Every replica gathers the owner gradient and updated weight slices in rank order. This is educational logical sharding, not NCCL, DDP or a production ZeRO implementation.</p></Details>
 <div className="dml-actions">{onSelect&&['distributed-gradient-weighting','microbatch-equivalent-updates','checkpoint','reverse-mode-autodiff'].map(id=><button key={id} onClick={()=>onSelect(id)}>{id.replaceAll('-',' ')}</button>)}</div><SourceLinks items={[{title:'NCCL collective semantics and rank order',url:'https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html'},{title:'PyTorch DistributedDataParallel gradient averaging contract',url:'https://docs.pytorch.org/docs/2.14/generated/torch.nn.parallel.DistributedDataParallel.html'},{title:'PyTorch elastic restart semantics',url:'https://docs.pytorch.org/docs/2.14/elastic/run.html'},{title:'PyTorch autograd mechanics',url:'https://docs.pytorch.org/docs/2.14/notes/autograd.html'}]}/></div></div></section>;
}
