import {useState, type ReactNode} from 'react';
import {Button} from './ui/button';
import {Equation} from './equation';
import {numericLabs, type NumericLabId} from '../lib/numeric-labs';
import * as M from '../lib/numeric-math';
import './numeric-workbench.css';

type Field<T>=[keyof T,string,number,number,number,string];
const fmt=(n:number,digits=2)=>n.toLocaleString(undefined,{maximumFractionDigits:digits});
const bytes=(n:number)=>n>=M.GiB?`${fmt(n/M.GiB)} GiB`:`${fmt(n/M.MiB)} MiB`;
const ms=(s:number)=>`${fmt(s*1000,3)} ms`;
function Range({name,value,min,max,step=1,unit='',onChange}:{name:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(value:number)=>void}){
 return <label className="numeric-field"><span>{name}<output>{fmt(value,4)} {unit}</output></span><input type="range" aria-label={name} aria-valuetext={`${fmt(value,4)} ${unit}`} min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
}
function Select({name,value,options,onChange}:{name:string;value:string;options:readonly (readonly [string,string])[];onChange:(value:string)=>void}){return <label className="numeric-field"><span>{name}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>;}
function Toggle({name,value,onChange}:{name:string;value:boolean;onChange:(value:boolean)=>void}){return <label className="numeric-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span>{name}</span></label>;}
function Metric({name,value,unit}:{name:string;value:string;unit?:string}){return <div className="numeric-metric"><span>{name}</span><strong>{value}</strong>{unit&&<small>{unit}</small>}</div>;}
function Fields<T extends object>({fields,value,change}:{fields:Field<T>[];value:T;change:(patch:Partial<T>)=>void}){return <div className="numeric-fields">{fields.map(([key,name,min,max,step,unit])=><Range key={String(key)} name={name} value={value[key] as number} min={min} max={max} step={step} unit={unit} onChange={n=>change({[key]:n} as Partial<T>)}/>)}</div>;}
function Details({name,children,open=false}:{name:string;children:ReactNode;open?:boolean}){return <details className="numeric-details" open={open}><summary>{name}</summary><div>{children}</div></details>;}
function Result({children,error=false}:{children:ReactNode;error?:boolean}){return <p className={`numeric-status ${error?'numeric-status-error':''}`} role="status">{children}</p>;}
function SourceFooter({id,initialRoute}:{id:NumericLabId;initialRoute?:M.BondRoute}){const lab=numericLabs.find(l=>l.id===id)!;return <><Equation latex={lab.latex} text={lab.formula}/><div className="numeric-sources">{lab.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a>)}</div></>;}

function StackLab({initialRoute='tc-ncf'}:{initialRoute?:M.BondRoute}){
 const [v,setV]=useState<M.HbmStackInput>({...M.hbmStackDefaults,gapUm:M.bondRoutes[initialRoute].gapUm,interfaceKW:M.bondRoutes[initialRoute].interfaceKW}),[route,setRoute]=useState<M.BondRoute>(initialRoute),[layer,setLayer]=useState(8);const patch=(p:Partial<M.HbmStackInput>)=>setV(s=>({...s,...p})),r=M.hbmStack(v),selected=Math.min(layer,v.dies);
 return <>
  <div className="numeric-layout"><div>
   <Fields value={v} change={patch} fields={[
    ['dies','DRAM dies in stack',1,16,1,'dies'],['dieUm','Thinned DRAM thickness',20,100,1,'μm'],['dieGbit','Capacity per DRAM die',8,32,8,'Gbit']
   ]}/>
   <Select name="Apply an illustrative bonding preset" value={route} options={Object.entries(M.bondRoutes).map(([id,p])=>[id,p.name])} onChange={s=>{const key=s as M.BondRoute;setRoute(key);patch({gapUm:M.bondRoutes[key].gapUm,interfaceKW:M.bondRoutes[key].interfaceKW});}}/>
   <p>{M.bondRoutes[route].description}</p>
   <Range name="Interface gap" value={v.gapUm} min={0} max={25} step={.5} unit="μm" onChange={gapUm=>patch({gapUm})}/>
   <p className="numeric-note">The preset gap and thermal resistance are invented teaching inputs, not a measured ranking of these processes. Selecting a route leaves the yield assumptions unchanged.</p>
  </div><div>
   <div className="numeric-stack" role="group" aria-label={`${v.dies} DRAM dies on one base die; schematic, not to scale`}>
    <div className="numeric-stack-sink">Cooling boundary · {fmt(v.coolantC)} °C</div>
    {Array.from({length:v.dies},(_,i)=>v.dies-i).map(i=><button type="button" key={i} aria-pressed={i===selected} onClick={()=>setLayer(i)} className="numeric-stack-die"><span>DRAM {i}</span><span>{fmt(r.temperatures[i],1)} °C</span></button>)}
    <button type="button" aria-pressed={selected===0} onClick={()=>setLayer(0)} className="numeric-stack-base"><span>Base / interface die</span><span>{fmt(r.temperatures[0],1)} °C</span></button>
   </div>
   <p className="numeric-note">Select a layer. {selected===0?'Base die':`DRAM ${selected}`} is at {fmt(r.temperatures[selected],1)} °C in the one-dimensional model. All heat exits through the top; the drawing does not use a physical thickness scale.</p>
   <div className="numeric-metrics" aria-live="polite"><Metric name="Stack capacity" value={fmt(r.capacityGB)} unit="decimal GB"/><Metric name="Height / selected limit" value={`${fmt(r.heightUm)} / ${fmt(v.limitUm)}`} unit="μm"/><Metric name="Effective bus bandwidth" value={fmt(r.deliveredGBs)} unit="decimal GB/s · unchanged by die count"/><Metric name="Expected screened-set survival" value={`${fmt(r.conditionalYield*100)}%`} unit={`${fmt(r.expectedPer1000)} expected stacks per 1,000 input sets`}/></div>
  </div></div>
  <Result error={!r.withinLimits}>{r.heightMarginUm<0?`Height exceeds the chosen limit by ${fmt(-r.heightMarginUm)} μm. `:`Height margin: ${fmt(r.heightMarginUm)} μm. `}{r.thermalMarginC<0?`Peak temperature exceeds the chosen limit by ${fmt(-r.thermalMarginC)} °C.`:`Peak temperature: ${fmt(r.peakC,1)} °C, leaving ${fmt(r.thermalMarginC,1)} °C to the chosen limit.`} These limits are teaching constraints, not qualified package specifications.</Result>
  <Details name="Interconnect and height constraints"><Fields value={v} change={patch} fields={[
   ['dataPins','Active data signals',256,4096,256,'pins'],['pinGbps','Rate per signal',0,16,.5,'Gbit/s'],['efficiency','Payload efficiency',0,1,.05,'fraction'],['baseUm','Base-die height',50,200,10,'μm'],['capUm','Cap / top allowance',0,100,5,'μm'],['limitUm','Selected stack-height limit',400,1200,20,'μm']
  ]}/><p>There are {r.interfaces} modeled bond interfaces, including the base-to-DRAM interface. More storage layers do not automatically add external data pins or increase per-pin rate. Pin count omits power, ground, clock and redundant TSVs.</p></Details>
  <Details name="Conditional yield and distributed heat model"><Fields value={v} change={patch} fields={[
   ['residualDieYield','Residual die survival after screening',.95,1,.001,'fraction'],['bondYield','Survival per bond interface',.8,1,.001,'fraction'],['finalYield','Final stack-test survival',.8,1,.001,'fraction'],['diePowerW','Power per DRAM die',0,4,.1,'W'],['basePowerW','Base-die power',0,8,.1,'W'],['interfaceKW','Resistance per bond interface',0,.1,.002,'K/W'],['coolerKW','Top-to-coolant resistance',.1,5,.1,'K/W'],['coolantC','Cooling boundary',20,70,1,'°C'],['limitC','Selected peak-temperature limit',60,110,1,'°C']
  ]}/><p>Fixed die area {v.areaMm2} mm² and silicon conductivity {v.siliconWmK} W/(m·K). Each modeled die segment adds t/(kA) = {fmt(r.siliconKW,4)} K/W. Power is distributed: a segment carries only the heat generated below it, while the top cooling path carries {fmt(r.totalPowerW)} W.</p><p>The yield starts with screened incoming sets, so raw wafer yield is not charged again. Independent residual die, bonding and test probabilities omit correlated defects, redundancy, rework and test escapes. Passing this stack model does not establish accelerator-package yield.</p></Details>
  <p className="numeric-note">This is a steady one-dimensional heat network. It omits lateral paths, local hot spots, gradients within a die, warpage, stress, temperature-dependent properties and transients. No real product limit or safety margin is predicted.</p>
  <Button type="button" variant="ghost" onClick={()=>{setV(M.hbmStackDefaults);setRoute('tc-ncf');setLayer(8);}}>Reset stack inputs</Button>
 </>;
}

const workloadFields:Field<M.Workload>[]=[['paramsB','Parameter count',0,200,1,'billion'],['weightBits','Weight precision',4,32,4,'bits'],['batch','Concurrent sequences',1,64,1,'sequences'],['context','Cached context per sequence',0,131072,1024,'tokens'],['layers','Transformer layers',8,128,8,'layers'],['kvHeads','KV heads',1,32,1,'heads'],['headDim','Values per head',32,256,32,'values'],['kvElementBytes','KV element size',1,4,1,'bytes']];
function Tier({name,capacity,parts,note,children}:{name:string;capacity:number;parts:{name:string;bytes:number}[];note:string;children:ReactNode}){const used=parts.reduce((sum,p)=>sum+p.bytes,0);return <section className="numeric-tier"><h4>{name}</h4><div className="numeric-tier-summary"><strong>{bytes(used)}</strong><span>of {bytes(capacity)}</span></div><div className="numeric-capacity-track" role="img" aria-label={`${name}: ${bytes(used)} allocated of ${bytes(capacity)}`}>{parts.map((p,i)=><i key={p.name} className={`numeric-part-${i}`} style={{width:`${capacity?Math.min(100,p.bytes/capacity*100):0}%`}}/>)}</div><dl>{parts.map(p=><div key={p.name}><dt>{p.name}</dt><dd>{bytes(p.bytes)}</dd></div>)}</dl><p>{note}</p>{children}</section>;}
function PlacementLab(){
 const [v,setV]=useState(M.placementDefaults),r=M.placeInference(v),patch=(p:Partial<M.PlacementInput>)=>setV(s=>({...s,...p}));
 const field=(key:keyof M.PlacementInput,name:string,min:number,max:number,step:number,unit:string)=><Range name={name} value={v[key] as number} min={min} max={max} step={step} unit={unit} onChange={n=>patch({[key]:n})}/>;
 const missing=Object.entries(r.missing).filter(([,n])=>n>1e-5);
 return <>
  <Fields<M.Workload> value={v} change={patch} fields={workloadFields.slice(0,4)}/>
  <Details name="KV shape, workspace and tensor-tile assumptions"><Fields<M.Workload> value={v} change={patch} fields={workloadFields.slice(4)}/><Fields value={v} change={patch} fields={[
   ['workspaceGiB','Reserved HBM workspace',0,16,.25,'GiB'],['tileMiB','SRAM tensor-tile scratch',0,256,4,'MiB']
  ]}/><p>Raw weight storage excludes quantization metadata and padding. KV stores one key and one value for every cached token in every layer. Workspace and a reusable SRAM tile are separate allocations; this is a conventional dense decoder, not a description of Astra.</p></Details>
  <div className="numeric-policy"><Select name="HBM allocation priority" value={v.policy} options={[["kv-first","Mutable KV first"],["weights-first","Read-only weights first"]]} onChange={s=>patch({policy:s as M.PlacementInput['policy']})}/><Toggle name="Use HBF for spilled read-only weights" value={v.useHbf} onChange={useHbf=>patch({useHbf})}/></div>
  <div className="numeric-tiers">
   <Tier name="SRAM" capacity={r.caps.sram} parts={[{name:'Reusable tile',bytes:r.sram.tile}]} note="A small active tensor tile, not the full model or a second weight copy.">{field('sramMiB','SRAM capacity',0,256,4,'MiB')}<Details name="SRAM transfer assumptions">{field('sramGBs','SRAM service bandwidth',1000,40000,1000,'GB/s')}{field('sramLatencyUs','SRAM access latency',0,.1,.005,'μs')}</Details></Tier>
   <Tier name="HBM" capacity={r.caps.hbm} parts={[{name:'Weights',bytes:r.hbm.weights},{name:'Mutable KV',bytes:r.hbm.kv},{name:'Workspace / staging',bytes:r.hbm.workspace}]} note="Workspace is reserved first; the selected policy allocates the remaining space.">{field('hbmGiB','HBM capacity',0,256,8,'GiB')}<Details name="HBM and package-path assumptions">{field('hbmGBs','HBM source bandwidth',100,8000,100,'GB/s')}{field('packageGBs','Package path bandwidth',100,8000,100,'GB/s')}{field('hbmLatencyUs','HBM access latency',0,2,.1,'μs')}</Details></Tier>
   <Tier name="Host DRAM" capacity={r.caps.host} parts={[{name:'Spilled weights',bytes:r.host.weights},{name:'Spilled mutable KV',bytes:r.host.kv}]} note="Spilled KV takes priority here. Remaining host capacity can hold weights.">{field('hostGiB','Host DRAM capacity',0,1024,16,'GiB')}<Details name="Host transfer assumptions">{field('hostGBs','Host DRAM bandwidth',20,500,20,'GB/s')}{field('hostLinkGBs','Host-to-device link',8,256,8,'GB/s')}{field('hostLatencyUs','Host access latency',0,20,.5,'μs')}</Details></Tier>
   <Tier name="HBF read tier" capacity={r.caps.hbf} parts={[{name:'Read-only weights',bytes:r.hbf.weights}]} note={v.useHbf?'No mutable KV is allocated here. Flash’s write behavior is outside this read-tier contract.':'Disabled: spill weights to host DRAM if capacity permits.'}>{field('hbfGiB','HBF capacity when enabled',0,2048,32,'GiB')}<Details name="Synthetic HBF transfer assumptions">{field('hbfGBs','HBF source bandwidth',50,2000,50,'GB/s')}{field('hbfLinkGBs','HBF-to-device link',50,2000,50,'GB/s')}{field('hbfLatencyUs','HBF read latency',1,200,1,'μs')}</Details></Tier>
  </div>
  <Result error={!r.feasible}>{r.feasible?'The selected working set and staging reservation fit this allocation. ':`This allocation is not executable. ${missing.map(([name,n])=>`${bytes(n)} of ${name} unplaced`).join('; ')}${missing.length?'. ':''}`}{!r.stagingFits&&`Staging needs ${bytes(r.requiredStagingBytes)}, more than the reserved ${bytes(r.hbm.workspace)}. `}One next token per sequence adds {bytes(r.size.append)} of mutable KV; this capacity check is for the selected current context.</Result>
  <Details name="Read granularity, prefetch and service assumptions" open><Fields value={v} change={patch} fields={[
   ['chunkMiB','Transfer-request chunk',.25,64,.25,'MiB'],['concurrency','Concurrent read requests',1,32,1,'requests'],['efficiency','Payload bandwidth efficiency',.1,1,.05,'fraction']
  ]}/><p>This conservative service model adds payload time and latency waves without overlap between them. Read latency is charged once per request wave. Concurrent requests reduce latency waves; they do not multiply the bandwidth ceiling. Reserved staging must hold up to one chunk per concurrent request, capped by the remote payload.</p></Details>
  <div className="numeric-service"><h4>{r.feasible?'One decode read pass':'Hypothetical partial read pass'} · one shared weight read per batch</h4>{(['hbm','host','hbf'] as const).map(key=><div key={key}><strong>{key==='hbm'?'HBM / package path':key==='host'?'Host DRAM / host link':'HBF / device link'}</strong><span>{ms(r.times[key].seconds)}</span><small>{fmt(r.times[key].effectiveGBs)} effective GB/s · {fmt(r.times[key].waves)} latency waves</small></div>)}</div>
  <div className="numeric-metrics" aria-live="polite"><Metric name={r.feasible?'Ideal pipeline bound in this model':'Hypothetical partial pipeline'} value={ms(r.pipelinedReadSeconds)}/><Metric name={r.feasible?"Conservative serial read service":"Hypothetical partial serial service"} value={ms(r.serialReadSeconds)}/><Metric name="Largest service-time component" value={r.limiting==='hbm'?'HBM / package':r.limiting==='host'?'Host DRAM':'HBF'}/></div>
  <p className="numeric-note">All capacities and rates are user-controlled synthetic values, including HBF. HBF augments the hierarchy here; it is not a universal DRAM replacement. Timings are read-service scenarios, not token latency. They exclude compute, KV appends, page migration, write amplification, endurance, contention and pipeline fill/drain. The ideal pipeline bound within this model takes the maximum of the three resource times; conservative serial service adds them. Neither is measured HBF behavior. An infeasible placement has only hypothetical partial service estimates; no achievable latency is asserted. Remote bytes incur an HBM staging write and a later HBM read—two actual transfers. The HBM/package path uses its minimum bandwidth once. SRAM’s selected tile service is {ms(r.times.sram.seconds)}; repeated tile reuse is not included in these external read-pass estimates.</p>
  <Button type="button" variant="ghost" onClick={()=>setV(M.placementDefaults)}>Reset placement inputs</Button>
 </>;
}

function TokenLab(){
 const [v,setV]=useState(M.tokenDefaults),[selected,setSelected]=useState(1),r=M.tokenSystem(v),patch=(p:Partial<M.TokenInput>)=>setV(s=>({...s,...p})),stage=r.timeline[selected];
 return <>
  <Fields<M.Workload> value={v} change={patch} fields={workloadFields.slice(0,4)}/>
  <div className="numeric-policy"><Select name="Tensor-parallel ranks" value={String(v.ranks)} options={[1,2,4,8,16,32].map(n=>[String(n),String(n)])} onChange={n=>patch({ranks:Number(n)})}/><Toggle name="Allow ideal tiled compute / memory overlap" value={v.overlap} onChange={overlap=>patch({overlap})}/></div>
  <Fields value={v} change={patch} fields={[
   ['computeTFLOPS','Arithmetic rate per rank',50,1000,25,'TFLOP/s'],['hbmGBs','HBM bandwidth per rank',100,8000,100,'GB/s'],['packageGBs','Package path per rank',100,8000,100,'GB/s'],['hbmGiB','Resident HBM per rank',8,256,8,'GiB']
  ]}/>
  <Result error={!r.fitsMemory}>{r.fitsMemory?`Resident weights, KV and 2 GiB workspace use ${bytes(r.residentBytes)} per rank, within ${fmt(v.hbmGiB)} GiB.`:`The resident model exceeds HBM by ${bytes(-r.capacityMarginBytes)} per rank. Timings below are hypothetical and need an offload strategy before execution.`} {r.kvPartitions} KV partitions serve {v.ranks} ranks{v.ranks>r.kvPartitions?'; KV is replicated across rank groups.':'.'}</Result>
  <div className="numeric-metrics" aria-live="polite"><Metric name={r.fitsMemory?"Batched decode-step time":"Hypothetical resident-step time"} value={ms(r.seconds)} unit={`${v.batch} new tokens across ${v.batch} sequences`}/><Metric name="Aggregate throughput" value={fmt(r.tokensPerSecond)} unit="tokens/s · not single-sequence speed"/><Metric name="Energy per output token" value={fmt(r.perTokenJ,3)} unit="joules · synthetic power model"/><Metric name="Average system power" value={fmt(r.averageW)} unit={`watts · ${v.ranks} ranks plus host`}/></div>
  <section className="numeric-timeline" aria-label="Shared critical-path timeline in milliseconds"><h4>{r.fitsMemory?"One wall-clock axis":"Hypothetical resident timeline"} · 0 to {ms(r.seconds)}</h4><p>Rows that occupy the same horizontal time overlap. Layer work is aggregated here; real layers interleave arithmetic and collectives. Select a stage to inspect its role.</p>{r.timeline.map((s,i)=><div className="numeric-time-row" key={s.id}><Button type="button" variant={selected===i?'secondary':'ghost'} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{s.name}</Button><span>{ms(s.start)} → {ms(s.start+s.duration)}</span><div className="numeric-time-track" role="img" aria-label={`${s.name}: starts ${ms(s.start)}, takes ${ms(s.duration)}`}><i className={selected===i?'selected':''} style={{left:`${r.seconds?s.start/r.seconds*100:0}%`,width:`${r.seconds?s.duration/r.seconds*100:0}%`}}/></div></div>)}</section>
  <div className="numeric-stage-detail" aria-live="polite"><h4>{stage.name} · {ms(stage.duration)}</h4><p>{stage.detail}</p><div className="numeric-actions"><Button type="button" variant="outline" onClick={()=>setSelected(s=>Math.max(0,s-1))} disabled={selected===0}>Previous stage</Button><Button type="button" variant="outline" onClick={()=>setSelected(s=>(s+1)%r.timeline.length)}>{selected===r.timeline.length-1?'Restart token path':'Next stage'}</Button></div></div>
  <div className="numeric-ledger"><h4>Bytes and work per rank</h4><dl>{[
   ['Read-only weights',bytes(r.weightBytes)],['Prior KV reads',bytes(r.kvReadBytes)],['New mutable KV writes',bytes(r.kvAppendBytes)],['Activation traffic allowance',bytes(r.activationTraffic)],['HBM / package traffic',bytes(r.memoryBytes)],['Dense + attention work',`${fmt((r.denseFlops+r.attentionFlops)/1e9)} GFLOP`],['Collective payload per operation',bytes(r.collectivePayload)],['Actual ring traffic',bytes(r.networkTraffic)],['Local limiting component',r.localBottleneck],['Wall time saved by selected overlap',ms(r.overlapSavedSeconds)]
  ].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl></div>
  <Details name="Network, model shape and execution assumptions"><Fields value={v} change={patch} fields={[
   ['layers','Transformer layers',8,128,8,'layers'],['networkGBs','Effective network link rate',10,400,10,'GB/s'],['networkLatencyUs','Latency per ring step',0,20,.5,'μs'],['collectivesPerLayer','All-reduces per layer',0,2,1,'collectives'],['efficiency','Shared rate efficiency',.1,1,.05,'fraction'],['memoryLatencyUs','Memory startup per layer',0,5,.1,'μs'],['launchUs','Dispatch time',0,200,5,'μs'],['sampleUs','Sampling / readout time',0,200,5,'μs']
  ]}/><p>Fixed {v.queryHeads} query heads × {v.headDim} values ({r.hidden}-wide activations), {v.kvHeads} KV heads, {v.kvElementBytes}-byte KV and {v.activationBytes}-byte communicated activations. Parameter count and layer count are independent teaching controls. Each batch reads shared weights once. Dense work is approximately 2 × parameters × batch; QK and AV add 4 × batch × layers × context × query heads × head width FLOP. Weight/work sharding is ideal; KV shards across the smaller of ranks and KV heads.</p><p>There are {r.collectives} selected all-reduces. An ideal ring moves 2(p−1)/p times each payload per rank and has 2(p−1) startup steps. Collectives are serialized with local work. Perfect local overlap is a tiled steady-state idealization; dependencies, finite tiles and scheduling can reduce it.</p></Details>
  <Details name="Incremental power and energy assumptions"><Fields value={v} change={patch} fields={[
   ['baseW','Baseline power per rank',0,200,5,'W'],['computeW','Additional arithmetic power',0,600,10,'W'],['memoryW','Additional memory/path power',0,200,5,'W'],['networkW','Additional network power per rank',0,100,5,'W'],['hostW','Host power allowance',0,200,5,'W']
  ]}/><p>Incremental powers are added only while their resources are active. Baseline power is charged once over wall time. Simultaneous compute and memory can consume both increments while time is counted once. These are constant synthetic powers, not TDP, telemetry, or a temperature model.</p></Details>
  <p className="numeric-note">This is one dense-model decode step with resident weights, equal context lengths and no inter-request queue. It excludes prefill, embeddings/normalization details, expert routing, quantization overhead, pipeline fill/drain, faults and variable sampling. Faster throughput does not imply improved answer quality. The byte ledger includes physical HBM traffic once, and the package link constrains that same path rather than adding a duplicate transfer time.</p>
  <Button type="button" variant="ghost" onClick={()=>{setV(M.tokenDefaults);setSelected(1);}}>Reset token-path inputs</Button>
 </>;
}

export default function NumericWorkbench({id,initialRoute}:{id:NumericLabId;initialRoute?:M.BondRoute}){const lab=numericLabs.find(l=>l.id===id)!;return <section className="numeric-workbench" data-numeric-lab={id}><h3>{lab.title}</h3><p className="numeric-intro">{lab.intro}</p>{id==='hbm-stack-build'?<StackLab initialRoute={initialRoute}/>:id==='inference-placement'?<PlacementLab/>:<TokenLab/>}<SourceFooter id={id}/></section>;}
