import {useMemo,useState} from 'react';
import {Control,Details,Metrics,SourceLinks,number} from './studio-primitives';
import {defaultFitOptions,evaluateLearnedRetrieval,evaluationPairs,fitIncidentModel,incidentCorpus,incidentCorpusId,inferIncident,learningPairs,tuningPairs,type ContextCondition,type FitOptions,type LearningRequest,type RetrievalMethod} from '../lib/automation-learning-model';
import {createLearnedHandoff,validateLearnedHandoff,type LearnedActionHandoff} from '../lib/automation-learned-bridge';
import './retrieval-learning-explorer.css';
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function RetrievalLearningExplorer({onSelect,onAutomation}:{onSelect?:(id:string)=>void;onAutomation?:(handoff:LearnedActionHandoff)=>void}){
 const[options,setOptions]=useState<FitOptions>(defaultFitOptions),[model,setModel]=useState(()=>fitIncidentModel()),[request,setRequest]=useState<LearningRequest>({query:'reserve parts for fan seven',method:'learned',condition:'retrieved'}),[token,setToken]=useState(0),[notice,setNotice]=useState('');
 const result=useMemo(()=>inferIncident(model,request),[model,request]),heldout=useMemo(()=>evaluateLearnedRetrieval(model),[model]),tuning=useMemo(()=>evaluateLearnedRetrieval(model,tuningPairs),[model]);
 const step=result.steps[Math.min(token,result.steps.length-1)],handoff=useMemo(()=>createLearnedHandoff(model,request),[model,request]);
 const comparison=useMemo(()=>(['retrieved','wrong','missing','stale'] as const).map(condition=>({condition,result:inferIncident(model,{...request,condition})})),[model,request]);
 const dirty=JSON.stringify(options)!==JSON.stringify(model.options);
 const importProposal=async(file:File|undefined)=>{if(!file)return;try{if(file.size>250000)throw Error('Fitted proposal exceeds 250,000 bytes.');const imported=validateLearnedHandoff(JSON.parse(await file.text()));setModel(imported.model);setOptions(imported.model.options);setRequest(imported.request);setToken(0);setNotice('Imported frozen weights and request. Generated tokens were recomputed and matched; this grants no workflow approval.');}catch(error){setNotice(`Import left the displayed model unchanged: ${error instanceof Error?error.message:String(error)}`);}};
 return <section className="retrieval-learning-explorer" aria-label="Learned retrieval and bounded action proposal">
  <div className="studio-heading"><h3>Learn a reference, then propose an action</h3><p>Fit a small numerical model in this browser. Learned query and passage embeddings rank two manuals. A fitted conditional token decoder uses the selected text representation and its previous token to generate a five-token reservation sentence. The incident workflow then checks any proposal independently.</p></div>
  <p className="studio-note">Shared task <strong>incident-017</strong>: reserve two FILTER-A units for FAN-7 and create its work order. Corpus <code>{incidentCorpusId}</code>. These are invented fixtures. This is a six-dimensional mean-embedding model and linear softmax decoder, with no attention or general language-model capability. Its vocabulary and task differ from the model-lifecycle experiment.</p>
  <div className="studio-layout"><aside className="studio-sidebar"><h4>Fit numerical parameters</h4>
   <Control label="Retriever gradient updates" value={options.retrievalSteps} min={0} max={800} step={20} onChange={retrievalSteps=>setOptions({...options,retrievalSteps})}/>
   <Control label="Decoder gradient updates" value={options.decoderSteps} min={0} max={800} step={10} onChange={decoderSteps=>setOptions({...options,decoderSteps})}/>
   <Control label="Learning rate" value={options.learningRate} min={.05} max={.8} step={.05} onChange={learningRate=>setOptions({...options,learningRate})}/>
   <Control label="Initialization seed" value={options.seed} min={1} max={50} onChange={seed=>setOptions({...options,seed})}/>
   <button onClick={()=>{setModel(fitIncidentModel(options));setNotice('Applied full-batch gradient descent to training data; held-out queries did not update weights.');}}>Fit configured model</button><p className="studio-note">{dirty?'Controls have changed. The displayed model remains frozen until fitting.':'Displayed results use the fitted settings.'} Zero updates exposes random initialization. Rates and update counts are dimensionless teaching controls.</p>
   <h4>Run frozen inference</h4><label>Request text<input value={request.query} maxLength={200} onChange={e=>setRequest({...request,query:e.target.value})}/></label><p>The target incident remains FAN-7 even if this request names another machine.</p>
   <label>Passage ranking<select value={request.method} onChange={e=>setRequest({...request,method:e.target.value as RetrievalMethod})}><option value="learned">Fitted dual mean encoder</option><option value="lexical">Unique token overlap baseline</option></select></label>
   <label>Separate candidate reranking<select value={request.rerank??'none'} onChange={e=>setRequest({...request,rerank:e.target.value as LearningRequest['rerank']})}><option value="none">Keep retrieval order</option><option value="entity-match">Authored query-entity match</option></select></label><p>The optional rule recognizes FAN-7 / fan seven and FAN-9 / fan nine. It promotes matching asset metadata among the two retrieved candidates; it does not learn scores, understand negation or resolve requests naming both.</p>
   <label>Context intervention<select value={request.condition} onChange={e=>setRequest({...request,condition:e.target.value as ContextCondition})}><option value="retrieved">Use top-ranked current manual</option><option value="wrong">Force the other current manual</option><option value="missing">Remove reference context</option><option value="stale">Use a deliberately stale quantity</option></select></label><p>These interventions occur after retrieval and any optional reranking. They reveal what retrieval, context and the authored revision gate each contribute.</p>
  </aside><div className="studio-main">
   <p className="retrieval-identity">Frozen policy <code>{model.policyId}</code> · {model.options.retrievalSteps} retriever / {model.options.decoderSteps} decoder updates</p>
   <Metrics items={[["Training retrieval loss",number(model.retrievalLoss.at(-1)!.loss,5)],["Teacher-forced decoder loss",number(model.decoderLoss.at(-1)!.loss,5)],["Held-out retrieval queries",`${heldout.filter(x=>x.correct).length} / ${heldout.length}`],["Generated fields fit incident-017",result.taskCorrect?'Yes':'No'],["Generated facts supported by context",result.sourceSupported?'Yes':'No'],["Authored proposal gate",result.accepted?'May enter runtime':'Abstains']]}/>
   <h4>1. Inspect the ranked reference index</h4><div className="studio-table-wrap" role="region" aria-label="Reference ranking" tabIndex={0}><table className="studio-table"><thead><tr><th>Passage</th><th>{request.method==='learned'?'Embedding dot product':'Distinct matching tokens'}</th><th>Softmax of scores</th><th>Current text</th></tr></thead><tbody>{result.ranked.map(x=><tr key={x.documentId}><th>{x.documentId}</th><td>{number(x.score,4)}</td><td>{number(x.probability*100,2)}%</td><td>{incidentCorpus.find(d=>d.id===x.documentId)!.text}</td></tr>)}</tbody></table></div><p>Softmax normalizes these two scores; it is not a calibrated probability of truth. Ties use document ID order. Query words outside the training vocabulary are dropped: {result.unknownTokens.join(', ')||'none'}.</p>
   <h4>2. Inspect the separate candidate selection</h4>{result.reranking?<><p><code>{result.reranking.version}</code> · Authored rule; recognized query entity: {result.reranking.queryEntity??'none or ambiguous'}. {result.reranking.reason}</p><div className="studio-table-wrap" role="region" aria-label="Candidate reranking trace" tabIndex={0}><table className="studio-table"><thead><tr><th>Candidate</th><th>Initial rank</th><th>Entity matches query?</th><th>After reranking</th></tr></thead><tbody>{result.reranking.candidates.map(x=><tr key={x.documentId}><th>{x.documentId}</th><td>{x.retrievalRank}</td><td>{x.entityMatch?'Yes':'No'}</td><td>{x.rerankedRank}</td></tr>)}</tbody></table></div></>:<p>Reranking is off. The decoder uses the original retrieval order before the selected context intervention.</p>}<p>This stage preserves the candidate set and initial scores. It cannot recover a source that retrieval omitted, establish factual support or grant runtime authority.</p>
   <h4>3. Read the actual decoder context</h4><blockquote>{result.context?.text??'No context: the decoder receives the zero vector.'}</blockquote><p>{result.context?.id??'No source ID'} · {result.context?(result.context.current?'current authored revision':'stale authored revision'):'absent'}</p>
   <h4>4. Inspect generated tokens</h4><p className="retrieval-output"><code>{result.text}</code></p><p>The decoder runs even with missing context, so learned biases can still produce fluent-looking fields. A separate authored gate can refuse to pass them onward.</p>
   <Control label="Generated token position" value={Math.min(token,result.steps.length-1)} min={0} max={result.steps.length-1} onChange={setToken}/><p>Position {step.position+1}; previous token <code>{step.previous}</code>; selected <code>{step.chosen}</code>.</p><div className="retrieval-probabilities" aria-label={`Conditional token distribution at position ${step.position+1}`}>{step.distribution.map(x=><div key={x.token}><code>{x.token}</code><meter min={0} max={1} value={x.probability} aria-label={`Probability of ${x.token}`}/><span>{number(x.probability*100,2)}%</span></div>)}</div>
   <h4>5. Cross the model-to-action boundary</h4><p>{result.reason}</p><pre className="studio-readout">{JSON.stringify(result.parsed?{name:'reserve_part',arguments:{...result.parsed,evidenceId:result.context?.id??null,idempotencyKey:'incident-017:reservation'}}:{error:'No parseable bounded action'},null,2)}</pre><p>Field parsing, source-revision checking, tool schema, capability checks, exact human review and durable receipts are authored software. The generated proposal never approves itself. Source support and correct incident fields above are independent diagnostics; the runtime still checks the actual final inventory and work order.</p>
   <div className="retrieval-actions">{onAutomation&&<button onClick={()=>{onAutomation(handoff);setNotice('Sent the frozen proposal to the workflow view. Start its new run there, then inspect runtime checks and review.');}}>Inspect this proposal in the durable workflow →</button>}<button onClick={()=>{download('atlas-fitted-incident-proposal.json',JSON.stringify(handoff,null,2));setNotice('Exported frozen model weights, request and recomputable generated proposal. This is a model handoff, not a workflow journal or human approval.');}}>Export fitted proposal</button><label className="retrieval-import">Import fitted proposal<input type="file" accept="application/json,.json" onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void importProposal(file);}}/></label></div><p role="status">{notice}</p>
  </div></div>
  <Details title="What actually learns, and what is authored"><p>Separate query and document token embeddings are averaged into six numbers. Full-batch cross entropy increases the score of each labeled training passage relative to the other passage. The decoder is then fit with those document embeddings frozen. Its input is six context values, a previous-token one-hot vector, a five-position one-hot vector and a bias. A learned linear projection plus softmax predicts each next token. Training supplies the correct prior token (teacher forcing); inference feeds back the selected token. Greedy generation can therefore accumulate errors.</p><p>The two supervised action sentences and the ten labeled request pairs are authored examples. Six dimensions, mean pooling, five output positions, token vocabulary, grammar, deterministic greedy selection and outer workflow are fixed design choices. No chain of thought is generated or inferred. No model sees the independent final-state checker.</p><div className="studio-table-wrap" role="region" aria-label="Fitted representation coordinates" tabIndex={0}><table className="studio-table"><caption>All six learned coordinates; axes have no assigned physical or semantic units</caption><thead><tr><th>Representation</th>{Array.from({length:6},(_,i)=><th key={i}>Coordinate {i+1}</th>)}</tr></thead><tbody><tr><th>Request</th>{result.queryVector.map((x,i)=><td key={i}>{number(x,4)}</td>)}</tr>{result.ranked.map(x=><tr key={x.documentId}><th>{x.documentId}</th>{x.vector.map((v,i)=><td key={i}>{number(v,4)}</td>)}</tr>)}</tbody></table></div></Details>
  <Details title="Training and held-out evidence"><p>Vocabulary and parameter updates use ten training requests plus the two reference texts only. Two tuning requests are displayed separately; this version has no tuned probability threshold. Four evaluation requests are distinct recombinations of a familiar vocabulary and the same two entities. This measures narrow fixture retrieval, not generalization to unseen machines or broad language understanding. Repeatedly changing controls after observing this set also makes it development feedback.</p><div className="studio-table-wrap" role="region" aria-label="Training and evaluation examples" tabIndex={0}><table className="studio-table"><thead><tr><th>Split</th><th>Request</th><th>Target passage</th><th>Frozen retrieval result</th></tr></thead><tbody>{learningPairs.map(x=><tr key={x.query}><th>Training</th><td>{x.query}</td><td>{x.documentId}</td><td>Used in updates</td></tr>)}{[...tuning.map(x=>({...x,split:'Tuning'})),...heldout.map(x=>({...x,split:'Evaluation'}))].map(x=><tr key={x.query}><th>{x.split}</th><td>{x.query}</td><td>{x.documentId}</td><td>{x.predicted} / {x.correct?'correct':'incorrect'}</td></tr>)}</tbody></table></div><p>{evaluationPairs.length} held-out requests are a tiny diagnostic set. The action decoder is trained on two exact target sentences; successful generation here is not held-out language generation.</p><div className="retrieval-losses">{[['Retriever',model.retrievalLoss],['Decoder',model.decoderLoss]].map(([name,points])=><div key={String(name)}><h5>{String(name)} loss, natural-log units per target</h5><div className="studio-table-wrap" role="region" aria-label={`${name} loss trace`} tabIndex={0}><table className="studio-table"><thead><tr><th>Gradient update</th><th>Mean cross entropy</th></tr></thead><tbody>{(points as typeof model.retrievalLoss).map(x=><tr key={x.step}><td>{x.step}</td><td>{number(x.loss,6)}</td></tr>)}</tbody></table></div></div>)}</div></Details>
  <Details title="Same frozen model, four context interventions"><div className="studio-table-wrap" role="region" aria-label="Context intervention comparison" tabIndex={0}><table className="studio-table"><thead><tr><th>Intervention</th><th>Generated tokens</th><th>Context support</th><th>Incident fields</th><th>Proposal gate</th></tr></thead><tbody>{comparison.map(x=><tr key={x.condition}><th>{x.condition}</th><td><code>{x.result.text}</code></td><td>{x.result.sourceSupported?'Supported':'Unsupported'}</td><td>{x.result.taskCorrect?'Correct':'Wrong'}</td><td>{x.result.accepted?'May enter runtime':'Abstains'}</td></tr>)}</tbody></table></div></Details>
  <div className="studio-task"><h4>Explain which boundary catches the error</h4><p>Use the top-ranked FAN-7 source, then force the other manual. Predict source support and incident correctness separately. Remove context: does generation stop on its own, or does an authored gate stop the proposal? Finally compare lexical overlap with the fitted index on “reserve parts for fan nine,” then enable the authored entity reranker. Explain which stage changed the selected reference without changing the learned weights. Name both fans and observe the rule’s explicit ambiguity limit.</p></div>
  {onSelect&&<div className="retrieval-actions">{[['retrieval-indexing-evaluation','Retrieval and its denominator'],['tool-contracts-schemas','Typed tool boundaries'],['tool-authority-identity','Authority and identity'],['durable-actions-idempotency','Durable actions'],['loss-optimizer','Loss and updates']].map(([id,label])=><button key={id} onClick={()=>onSelect(id)}>{label} →</button>)}</div>}
  <SourceLinks items={[{title:'Passage Re-ranking with BERT · contrasting learned reranker (not implemented here)',url:'https://arxiv.org/abs/1901.04085'},{title:'Dense Passage Retrieval · learned dual-encoder retrieval',url:'https://arxiv.org/abs/2004.04906'},{title:'Bengio et al. · true prior tokens during training versus generated prior tokens at inference',url:'https://arxiv.org/abs/1506.03099'},{title:'Retrieval-Augmented Generation · conditioning generation on retrieved evidence',url:'https://arxiv.org/abs/2005.11401'},{title:'scikit-learn · keep preprocessing and fitting out of test data',url:'https://scikit-learn.org/stable/common_pitfalls.html#data-leakage'}]}/>
 </section>;
}
