import {useMemo, useState} from 'react';

type Specimen={id:string;name:string;family:string;status:string;asOf:string;processDisclosure:string;execution:string;memory:string;interconnect:string;software:string;workloadFit:string;limits:string;source:{title:string;url:string}};
const specimens:Specimen[]=[
 {id:'xeon-6',name:'Intel Xeon 6 P-core',family:'CPU',status:'public product family',asOf:'2024–2025',processDisclosure:'Intel discloses product process families and tile strategy; exact layout is configuration-specific.',execution:'Out-of-order scalar/vector cores with cache-coherent host responsibilities.',memory:'Multi-level cache and DDR5-class host memory; capacity depends on platform.',interconnect:'PCIe/CXL and socket/platform fabrics vary by SKU.',software:'x86 ecosystem, compilers, libraries and server operating systems.',workloadFit:'Serial control, preprocessing, orchestration and general-purpose services.',limits:'Do not compare core counts or throughput directly with accelerator products.',source:{title:'Intel Xeon 6 overview',url:'https://www.intel.com/content/www/us/en/products/details/processors/xeon/xeon-6.html'}},
 {id:'blackwell',name:'NVIDIA Blackwell GPU',family:'GPU',status:'publicly announced/product family',asOf:'2024–2025',processDisclosure:'Multi-die package and system-level disclosures are public; exact implementation details remain product-specific.',execution:'SIMT streaming multiprocessors with tensor and vector execution.',memory:'HBM-attached accelerator memory; capacity and bandwidth depend on the product configuration.',interconnect:'High-bandwidth scale-up links plus PCIe/network paths.',software:'CUDA, libraries, kernels, graph compilers and collective communication.',workloadFit:'Dense/sparse tensor work, training, inference and simulation with a mature software stack.',limits:'Vendor peak numbers use precision and workload definitions that must be matched before comparison.',source:{title:'NVIDIA Blackwell platform',url:'https://www.nvidia.com/en-us/data-center/technologies/blackwell-architecture/'}},
 {id:'mi300x',name:'AMD Instinct MI300X',family:'GPU',status:'public product',asOf:'2023–2025',processDisclosure:'AMD describes chiplet packaging and HBM integration; package partitions and SKU limits are the comparison boundary.',execution:'GPU compute units with matrix acceleration and programmable kernels.',memory:'HBM3-attached memory with product-specific capacity/bandwidth disclosures.',interconnect:'Infinity Fabric and host/network interfaces depend on platform.',software:'ROCm, HIP, libraries, compilers and framework integrations.',workloadFit:'Large-model inference and training where HBM capacity, kernels and software fit.',limits:'Software maturity and kernel porting effort are workload-dependent; no universal ranking follows.',source:{title:'AMD Instinct MI300X',url:'https://www.amd.com/en/products/accelerators/instinct/mi300/mi300x.html'}},
 {id:'tpu-v6e',name:'Google TPU v6e',family:'TPU',status:'public cloud offering',asOf:'2024–2025',processDisclosure:'Google publishes system and programming abstractions; internal process and package details are not a public SKU specification.',execution:'Systolic/matrix-oriented tensor processing with a compiler-managed programming model.',memory:'High-bandwidth accelerator memory and host/system memory are exposed through the cloud topology.',interconnect:'Pod-scale interconnect and host paths are part of the service boundary.',software:'XLA, JAX, PyTorch/XLA and Google Cloud scheduling interfaces.',workloadFit:'Training and inference with graph shapes and compiler paths that map well to TPU execution.',limits:'Cloud service measurements include software and scheduling context; hardware-only comparisons are incomplete.',source:{title:'Google Cloud TPU v6e',url:'https://cloud.google.com/tpu/docs/v6e'}},
 {id:'trainium2',name:'AWS Trainium2',family:'Custom accelerator',status:'public cloud offering',asOf:'2024–2025',processDisclosure:'AWS describes the accelerator and UltraServer system boundary; detailed die and package drawings are not universal disclosures.',execution:'Purpose-built training/inference engines with compiler-managed data movement.',memory:'High-bandwidth local memory and host/network paths are exposed by the instance configuration.',interconnect:'NeuronLink and cloud fabric roles are distinct from general Ethernet.',software:'AWS Neuron compiler, runtime, libraries and framework integrations.',workloadFit:'AWS-hosted training and inference where Neuron support and service placement fit.',limits:'Cloud price/performance depends on instance, region, utilization and software version.',source:{title:'AWS Trainium2',url:'https://aws.amazon.com/ai/machine-learning/trainium/'}},
 {id:'maia-100',name:'Microsoft Maia 100',family:'Custom accelerator',status:'publicly disclosed design',asOf:'2023–2024',processDisclosure:'Microsoft describes an AI accelerator and platform role; exact process and current deployment capacity are not fully public.',execution:'Matrix-focused AI accelerator with a dataflow-oriented memory hierarchy.',memory:'On-package and system memory roles are architecture-specific; public materials define the design boundary.',interconnect:'Designed for datacenter scale-up and platform integration.',software:'Microsoft compiler/runtime stack and model-serving integration.',workloadFit:'Provider-controlled training and inference workloads selected for the software/hardware path.',limits:'Public architecture descriptions do not establish broad benchmark parity or current fleet share.',source:{title:'Microsoft Maia 100',url:'https://www.microsoft.com/en-us/research/project/maia/'}},
 {id:'mtia',name:'Meta MTIA',family:'Custom accelerator',status:'publicly disclosed family',asOf:'2023–2025',processDisclosure:'Meta publishes selected architecture and workload goals; exact manufacturing and deployment details differ by generation.',execution:'Inference-oriented accelerator organization tuned for Meta recommendation and generative workloads.',memory:'Memory hierarchy is co-designed with target models; capacity and bandwidth are generation-specific.',interconnect:'Datacenter host and scale-out integration is part of the platform design.',software:'Meta internal compiler, kernel and fleet software; public interfaces are more limited than CUDA.',workloadFit:'High-volume provider workloads with stable operators and controlled deployment.',limits:'A provider-specific accelerator should be compared by workload and service boundary, not a generic FLOP label.',source:{title:'Meta MTIA architecture',url:'https://engineering.fb.com/2023/05/18/data-center-engineering/mtia-meta-training-and-inference-accelerator/'}},
 {id:'wafer-scale',name:'Cerebras WSE',family:'Wafer-scale',status:'public system architecture',asOf:'2019–2025',processDisclosure:'Wafer-scale integration is public at the system level; detailed process yield and replacement policy are not fully disclosed.',execution:'Large spatial array with local memory and communication across a wafer-sized compute surface.',memory:'On-wafer SRAM and attached system memory roles are architecturally distinct.',interconnect:'On-wafer fabric and system-scale links create a different communication boundary from package-level accelerators.',software:'Cerebras software stack and graph/compiler path.',workloadFit:'Large, regular workloads that benefit from local communication and a single logical surface.',limits:'Wafer-scale capacity, yield, partitioning and workload mapping are not interchangeable with package-level accelerators.',source:{title:'Cerebras Wafer-Scale Engine',url:'https://www.cerebras.ai/chip'}},
];
const families=['all',...new Set(specimens.map(s=>s.family))];
export default function SpecimenComparison(){
 const [family,setFamily]=useState('all'),[selected,setSelected]=useState<string[]>(specimens.slice(0,2).map(s=>s.id));
 const visible=useMemo(()=>specimens.filter(s=>family==='all'||s.family===family),[family]);
 const toggle=(id:string)=>setSelected(xs=>xs.includes(id)?xs.filter(x=>x!==id):xs.length<3?[...xs,id]:[...xs.slice(1),id]);
 const compared=selected.map(id=>specimens.find(s=>s.id===id)).filter(Boolean) as Specimen[];
 const fields:[keyof Specimen,string][]=[['execution','Execution model'],['memory','Memory boundary'],['interconnect','Interconnect'],['software','Software path'],['workloadFit','Workload fit'],['limits','Comparison limits']];
 return <div className="specimen-comparison"><p className="meta-explanation">Choose up to three public specimens. Cards use a common vocabulary; they do not create a vendor leaderboard. “Unknown” stays visible when a provider does not disclose a boundary.</p><div className="comparison-controls"><label>Family<select value={family} onChange={e=>setFamily(e.target.value)}>{families.map(x=><option key={x}>{x}</option>)}</select></label><span>{compared.length}/3 selected</span></div><div className="specimen-picker">{visible.map(s=><button key={s.id} className={selected.includes(s.id)?'selected':''} onClick={()=>toggle(s.id)}><strong>{s.name}</strong><small>{s.family} · {s.status}</small><em>{s.asOf}</em></button>)}</div>{compared.length>0&&<div className="comparison-table-wrap"><table className="comparison-table"><caption>Common comparison axes · source context retained per specimen</caption><thead><tr><th>Axis</th>{compared.map(s=><th key={s.id}>{s.name}<small>{s.family}</small></th>)}</tr></thead><tbody><tr><th>Public boundary</th>{compared.map(s=><td key={s.id}>{s.processDisclosure}</td>)}</tr>{fields.map(([field,label])=><tr key={field}><th>{label}</th>{compared.map(s=><td key={s.id}>{String(s[field])}</td>)}</tr>)}</tbody></table></div>}<div className="specimen-sources">{compared.map(s=><a key={s.id} href={s.source.url} target="_blank" rel="noreferrer">{s.name}: {s.source.title} ↗</a>)}</div><button className="ghost-button" onClick={()=>setSelected([])}>Clear comparison</button></div>;
}
