import {lazy, Suspense, useState, type ReactNode} from 'react';
import ResourceBoundary from './resource-boundary';
import type {ProcessDrawing} from '../lib/process-mechanisms';
const Spatial=lazy(()=>import('./process-spatial'));
export const number=(value:number,digits=2)=>Number.isFinite(value)?value.toLocaleString(undefined,{maximumFractionDigits:digits}):'Unavailable';
export function Metrics({items}:{items:[string,string][]}){return <dl className="studio-metrics">{items.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>;}
export function Control({label,value,min,max,step=1,onChange,unit='',disabled=false}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;disabled?:boolean;onChange:(v:number)=>void}){return <label className="studio-control"><span>{label}<output>{number(value,4)} {unit}</output></span><input type="range" disabled={disabled} aria-label={label} min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;}
export function Stepper({value,max,onChange,label='Step'}:{value:number;max:number;onChange:(v:number)=>void;label?:string}){return <div className="studio-stepper"><button disabled={value===0} onClick={()=>onChange(value-1)} aria-label={`Previous ${label.toLowerCase()}`}>←</button><label>{label} {value+1} / {max+1}<input type="range" min="0" max={max} value={value} aria-label={label} onChange={e=>onChange(Number(e.target.value))}/></label><button disabled={value===max} onClick={()=>onChange(value+1)} aria-label={`Next ${label.toLowerCase()}`}>→</button></div>;}
export function Details({title,children}:{title:string;children:ReactNode}){return <details className="studio-details"><summary>{title}</summary>{children}</details>;}
export function Drawing({drawing}:{drawing:ProcessDrawing}){const[spatial,setSpatial]=useState(false);return <figure className="studio-drawing"><div className="studio-view-switch"><button aria-pressed={!spatial} onClick={()=>setSpatial(false)}>Cross-section</button><button aria-pressed={spatial} onClick={()=>setSpatial(true)}>Inspect in 3D</button></div>{spatial?<ResourceBoundary name="optional spatial drawing"><Suspense fallback={<p>Loading spatial inspection…</p>}><Spatial drawing={drawing} selected=""/></Suspense></ResourceBoundary>:<svg viewBox="0 0 600 360" role="img" aria-label={drawing.caption}>{drawing.shapes.map((s,i)=>s.kind==='line'?<line key={i} x1={s.x} y1={s.y} x2={s.x+s.w} y2={s.y+s.h} stroke={s.color} strokeWidth="1.5"><title>{s.label}</title></line>:s.kind==='circle'?<circle key={i} cx={s.x} cy={s.y} r={s.w/2} fill={s.color}><title>{s.label}</title></circle>:<rect key={i} x={s.x} y={s.y} width={s.w} height={s.h} fill={s.color} stroke="#091822" strokeWidth=".4"><title>{s.label}</title></rect>)}</svg>}<figcaption>{drawing.caption}<small>{drawing.scale}</small></figcaption><div className="studio-legend">{Array.from(new Map(drawing.shapes.filter(s=>s.label).map(s=>[s.label!,s.color])).entries()).map(([label,color])=><span key={label}><i style={{background:color}}/>{label}</span>)}</div></figure>;}
export function SourceLinks({items}:{items:{title:string;url:string}[]}){return <ul className="studio-sources">{items.map(x=><li key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.title} ↗</a></li>)}</ul>;}
