import {createContext,useContext,useEffect,useRef,useState,type ReactNode,type Dispatch,type SetStateAction} from 'react';
import {createStudioWorkspace,studioRecordLimit,type StudioValues} from '../lib/studio-record';
const identity=()=>({content:__ATLAS_BUILD__.contentSha256,models:__ATLAS_BUILD__.modelVersions});
type Store={values:StudioValues;seed:(field:string,value:unknown)=>void;write:(field:string,value:unknown)=>void};
const Context=createContext<Store>({values:{},seed:()=>{},write:()=>{}});
export function useStudioState<T>(field:string,initial:T|(()=>T)):[T,Dispatch<SetStateAction<T>>]{
 const store=useContext(Context),[value,setValue]=useState<T>(()=>Object.hasOwn(store.values,field)?structuredClone(store.values[field]) as T:typeof initial==='function'?(initial as ()=>T)():initial),observed=useRef({field,value});
 // Register defaults without treating mount/StrictMode effect replay as a learner edit.
 useEffect(()=>{store.seed(field,value);if(observed.current.field!==field||!Object.is(observed.current.value,value)){observed.current={field,value};store.write(field,value);}},[field,value,store]);
 return[value,setValue];
}
export default function StudioRecordStore({children}:{children:ReactNode}){
 const [status,setStatus]=useState(''),[revision,setRevision]=useState(0),[ready,setReady]=useState(false),file=useRef<HTMLInputElement>(null),workspace=useRef<ReturnType<typeof createStudioWorkspace>|null>(null);
 if(!workspace.current)workspace.current=createStudioWorkspace({identity:identity(),storage:{getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v),removeItem:k=>localStorage.removeItem(k)},onStatus:setStatus});
 const work=workspace.current,generation=work.generation,store:Store={values:work.values,seed:(field,value)=>work.seed(field,value,generation),write:(field,value)=>work.write(field,value,generation)};
 useEffect(()=>{work.initialize();setReady(true);const save=()=>work.flush();window.addEventListener('pagehide',save);return()=>{window.removeEventListener('pagehide',save);work.stop();};},[work]);
 const exportWork=()=>{try{const blob=new Blob([work.exportText()],{type:'application/json'}),url=URL.createObjectURL(blob),a=window.document.createElement('a');a.href=url;a.download='ai-atlas-engineering-work.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setStatus((e as Error).message);}};
 const exportOlder=()=>{try{const blob=new Blob([work.exportOlderText()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=window.document.createElement('a');a.href=url;a.download='ai-atlas-older-saved-record.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setStatus((e as Error).message);}};
 const importWork=async(f:File)=>{const ticket=work.beginImport();try{if(f.size>studioRecordLimit)throw Error('The record is too large.');work.importText(await f.text(),ticket);setRevision(x=>x+1);setStatus('Imported inputs restored. Previous workspace saved for recovery.');}catch(e){setStatus((e as Error).message+' Current inputs were preserved.');}};
 const restorePrevious=()=>{try{work.restorePrevious();setRevision(x=>x+1);setStatus('Previous workspace restored. Displaced inputs are the recovery copy.');}catch(e){setStatus((e as Error).message+' Current inputs were preserved.');}};
 return <><details className="studio-workspace"><summary>Saved engineering workspace</summary><div className="studio-workbar"><button disabled={!ready} onClick={exportWork}>Export inputs</button><button disabled={!ready} onClick={()=>file.current?.click()}>Import inputs</button><button disabled={!ready} onClick={restorePrevious}>Restore previous workspace</button>{work.olderRecordCount>0&&<button disabled={!ready} onClick={exportOlder}>Export older saved {work.olderRecordCount===1?'record':'records'}</button>}<input ref={file} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importWork(f);e.target.value='';}}/><small role="status">{status}</small></div><p className="studio-note">Inputs persist on this device. Export them for another device; import keeps one recovery copy. Older or incompatible records are preserved separately before new inputs replace them. Their recovery export keeps the original text; multiple records download together. Imports require this content edition and model versions. Each experience has its own specimen and workload. Lesson links select an experience, while the record carries its numerical state.</p></details>{ready?<Context.Provider key={revision} value={store}>{children}</Context.Provider>:<p>Restoring engineering workspace…</p>}</>;
}
