import test from 'node:test';
import assert from 'node:assert/strict';
import {commissioningDefaults as d,buildCommissioningTrace as run,normalizeCommissioningInput,translateDma,translateProcess,canReuseBuffer,acceptsCompletion} from '../src/lib/commissioning-execution.ts';
import {makeCommissioningRecord,parseCommissioningRecord,saveCommissioningRecord,exportOlderCommissioningRecords,commissioningRecordKey,commissioningRecoveryKey} from '../src/lib/commissioning-execution-record.ts';
const at=(r,kind)=>r.events.find(e=>e.kind===kind);
function invariants(r){for(const e of r.events){const s=e.state;assert.equal(s.executedMacs,s.activeMacs+s.discardedMacs+s.committedMacs);const active=s.submittedAttempts-s.canceledAttempts-s.completedAttempts;assert.ok(active>=0&&active<=1);assert.ok(s.completedAttempts<=1);assert.equal(s.readBytes%4,0);assert.equal(s.writeBytes%4,0);if(['dma-read','mac','dma-write'].includes(e.kind)){assert.ok(s.firmwareReady&&s.discovered&&s.resourcesClaimed&&s.dmaEnabled&&s.queueReady);assert.ok(s.descriptor.published);assert.ok(s.buffers.every(b=>b.owner==='device'));}if(s.published){assert.ok(s.completion.accepted);assert.equal(s.completion.epoch,s.epoch);assert.equal(s.completedAttempts,1);}}}
test('default delivered operands yield eight MACs and the exact result',()=>{const r=run(d);assert.equal(r.status,'complete');assert.deepEqual(r.finalOutput,[[19,22],[43,50]]);assert.equal(r.events.filter(e=>e.kind==='mac').length,8);assert.deepEqual(r.totals,{executedMacs:8,discardedMacs:0,committedMacs:8,submittedAttempts:1,canceledAttempts:0,completedAttempts:1,readBytes:32,writeBytes:16,rejectedActions:0});invariants(r);});
test('256 binary matrix pairs match independent hand-calculated products',()=>{const matrices=Array.from({length:16},(_,x)=>[[x&1,(x>>1)&1],[(x>>2)&1,(x>>3)&1]]);for(const a of matrices)for(const b of matrices){const r=run({...d,a,b});assert.deepEqual(r.finalOutput,[[a[0][0]*b[0][0]+a[0][1]*b[1][0],a[0][0]*b[0][1]+a[0][1]*b[1][1]],[a[1][0]*b[0][0]+a[1][1]*b[1][0],a[1][0]*b[0][1]+a[1][1]*b[1][1]]]);}});
test('480 commissioning, handoff and reset cases preserve ownership and work',()=>{for(const boot of ['compatible','abi-mismatch'])for(const coherence of ['coherent','noncoherent'])for(const sync of ['both','skip-to-device','skip-to-cpu'])for(const fault of ['none','wrong-mapping','unmapped-b','early-reuse','device-reset'])for(const resetAfterCells of [1,2,3,4])for(const resetPolicy of ['stop','retry'])invariants(run({...d,boot,coherence,sync,fault,resetAfterCells,resetPolicy}));});
test('ABI rejection precedes resources, submissions and DMA',()=>{const r=run({...d,boot:'abi-mismatch'});assert.equal(r.status,'blocked');assert.equal(r.totals.submittedAttempts,0);assert.equal(r.totals.readBytes,0);assert.ok(r.events.every(e=>!e.state.queueReady&&!e.state.dmaEnabled));});
test('virtual and device addresses converge on bytes without conflating namespaces',()=>{const s=at(run(d),'submit').state;for(const b of s.buffers)for(let offset=0;offset<16;offset++)assert.equal(translateProcess(s.buffers,b.virtual+offset,1),translateDma(s.mappings,b.iova+offset,1,b.id==='C'?'write':'read',0));assert.throws(()=>translateProcess(s.buffers,0x8000,4));assert.throws(()=>translateDma(s.mappings,0x1000,4,'read',0));});
test('translation checks endpoints, direction, epoch, mask and ambiguous mappings',()=>{const s=at(run(d),'submit').state;assert.equal(translateDma(s.mappings,0x800c,4,'read',0),0x400c);for(const [addr,bytes,mode,epoch] of [[0x800d,4,'read',0],[0x8000,4,'write',0],[0xa000,4,'read',0],[0x8000,4,'read',1],[65535,4,'read',0],[0x8000,0,'read',0],[0x8000,NaN,'read',0]])assert.throws(()=>translateDma(s.mappings,addr,bytes,mode,epoch));assert.throws(()=>translateDma([...s.mappings,s.mappings[0]],0x8000,4,'read',0));});
test('permitted wrong B mapping computes A squared without a protection exception',()=>{const r=run({...d,fault:'wrong-mapping'});assert.equal(r.status,'semantic-mismatch');assert.deepEqual(r.finalOutput,[[7,10],[15,22]]);assert.deepEqual(r.reference,[[19,22],[43,50]]);assert.equal(r.totals.rejectedActions,0);for(const e of r.events.filter(e=>e.kind==='dma-read'&&e.access.buffer==='B'))assert.ok(e.access.physical>=0x4000&&e.access.physical<0x4010);});
test('missing B supplies no arithmetic value and quiesces before returning ownership',()=>{const r=run({...d,fault:'unmapped-b'});assert.equal(r.status,'blocked');assert.equal(r.finalOutput,null);assert.equal(r.totals.readBytes,16);assert.equal(r.totals.executedMacs,0);assert.ok(at(r,'dma-fault').state.buffers.every(b=>b.owner==='device'));assert.ok(r.events.at(-1).state.buffers.every(b=>b.owner==='host'));assert.equal(r.events.at(-1).state.mappings.length,0);});
test('omitted noncoherent input/output handoffs expose actual stale values',()=>{const a=run({...d,sync:'skip-to-device'}),b=run({...d,sync:'skip-to-cpu'});assert.deepEqual(a.finalOutput,[[0,0],[0,0]]);assert.deepEqual(b.finalOutput,[[-777,-777],[-777,-777]]);assert.equal(a.status,'semantic-mismatch');assert.equal(b.status,'semantic-mismatch');assert.deepEqual(at(b,'completion-posted').state.buffers[2].memory,[19,22,43,50]);});
test('coherent data visibility preserves publication and lifetime requirements',()=>{for(const sync of ['both','skip-to-device','skip-to-cpu']){const r=run({...d,coherence:'coherent',sync,fault:'early-reuse'});assert.deepEqual(r.finalOutput,[[19,22],[43,50]]);assert.equal(r.totals.rejectedActions,1);assert.ok(!at(r,'descriptor').state.descriptor.published);assert.ok(at(r,'submit').state.descriptor.published);assert.ok(at(r,'descriptor').index<at(r,'submit').index);}});
test('early reuse rejection mutates neither cached nor memory buffer values',()=>{const r=run({...d,fault:'early-reuse'}),s=at(r,'submit').state,e=at(r,'reuse-rejected').state;assert.equal(canReuseBuffer(s,'B'),false);assert.deepEqual(s.buffers,e.buffers);assert.equal(canReuseBuffer(r.events.at(-1).state,'B'),true);});
test('two-cell reset discards four MACs and retries with one publication',()=>{const r=run({...d,fault:'device-reset'});assert.deepEqual(r.finalOutput,[[19,22],[43,50]]);assert.equal(r.totals.executedMacs,12);assert.equal(r.totals.discardedMacs,4);assert.equal(r.totals.committedMacs,8);assert.equal(r.totals.readBytes,64);assert.equal(r.totals.writeBytes,24);assert.equal(r.events.filter(e=>e.kind==='publish').length,1);const reset=at(r,'reset-acknowledged');assert.deepEqual(reset.state.buffers[2].memory,[19,22,-777,-777]);assert.equal(reset.state.epoch,1);assert.equal(reset.state.mappings.length,0);assert.ok(r.events.filter(e=>e.index>reset.index&&e.kind==='dma-read').every(e=>e.state.epoch===1));});
test('reset after any cell accounts even a fully written but uncommitted result',()=>{for(const resetAfterCells of [1,2,3,4]){const r=run({...d,fault:'device-reset',resetAfterCells});assert.equal(r.totals.executedMacs,8+resetAfterCells*2);assert.equal(r.totals.discardedMacs,resetAfterCells*2);assert.equal(r.totals.writeBytes,16+resetAfterCells*4);const stop=run({...d,fault:'device-reset',resetAfterCells,resetPolicy:'stop'});assert.equal(stop.status,'canceled');assert.equal(stop.finalOutput,null);assert.equal(stop.totals.committedMacs,0);assert.equal(stop.totals.discardedMacs,resetAfterCells*2);}});
test('wrong-job, old-epoch, premature and duplicate completion records fail',()=>{const r=run({...d,fault:'device-reset'});assert.equal(acceptsCompletion(at(r,'submit').state,'matrix-job-1',0),false);const posted=at(r,'completion-posted').state;assert.equal(acceptsCompletion(posted,'matrix-job-1',1),true);assert.equal(acceptsCompletion(posted,'matrix-job-1',0),false);assert.equal(acceptsCompletion(posted,'other-job',1),false);assert.equal(acceptsCompletion(at(r,'completion-validated').state,'matrix-job-1',1),false);assert.ok(at(r,'old-completion-rejected'));});
test('signed extrema stay exact and snapshots own their mutable arrays',()=>{const r=run({...d,a:[[99,-99],[-99,99]],b:[[99,99],[-99,-99]]});assert.deepEqual(r.finalOutput,[[19602,19602],[-19602,-19602]]);r.events[0].state.buffers[0].cpu[0]=12;assert.equal(r.events[1].state.buffers[0].cpu[0],99);assert.equal(d.a[0][0],1);});
test('invalid fields, sparse matrices and record versions are rejected',()=>{for(const x of [{...d,resetAfterCells:0},{...d,boot:'verified-signature'},{...d,extra:1},{...d,a:[[1,,],[3,4]]},{...d,b:[[1,2,3],[4,5,6],[7,8,9]]},{...d,sync:'none'}])assert.throws(()=>normalizeCommissioningInput(x));assert.throws(()=>parseCommissioningRecord('{"schemaVersion":1,"modelVersion":"old"}'));const r=makeCommissioningRecord(d);assert.deepEqual(parseCommissioningRecord(JSON.stringify(r)),r);r.input.a[0][0]=9;assert.equal(d.a[0][0],1);});
const storage=(initial={},fail=null)=>{const data={...initial};return {data,getItem:k=>data[k]??null,setItem:(k,v)=>{if(k===fail)throw new Error('quota');data[k]=v;}};};
test('saved replacement durably preserves incompatible raw text',()=>{const old=' old raw \n',s=storage({[commissioningRecordKey]:old});saveCommissioningRecord(s,makeCommissioningRecord(d));assert.equal(exportOlderCommissioningRecords(s),old);assert.deepEqual(parseCommissioningRecord(s.data[commissioningRecordKey]),makeCommissioningRecord(d));});
test('backup failure retains active input and corrupt recovery remains exportable',()=>{const old='old',s=storage({[commissioningRecordKey]:old},commissioningRecoveryKey);assert.throws(()=>saveCommissioningRecord(s,makeCommissioningRecord(d)));assert.equal(s.data[commissioningRecordKey],old);const b=storage({[commissioningRecordKey]:old,[commissioningRecoveryKey]:'unreadable'});assert.throws(()=>saveCommissioningRecord(b,makeCommissioningRecord(d)));assert.ok(exportOlderCommissioningRecords(b).includes('unreadable'));assert.equal(b.data[commissioningRecordKey],old);});

test('runtime lesson pack has five complete linked lessons and eight valid canonical math cards',async()=>{
 const fs=await import('node:fs');const katex=(await import('katex')).default;
 const pack=JSON.parse(fs.readFileSync(new URL('../src/lib/data/hardware-runtime-learning.json',import.meta.url),'utf8')),eq=JSON.parse(fs.readFileSync(new URL('../src/lib/data/equations-hardware-runtime-learning.json',import.meta.url),'utf8'));
 assert.equal(pack.lessons.length,5);assert.equal(Object.values(eq).flat().length,8);const sources=new Set(pack.sources.map(s=>s.id));const {loadAuthoredAtlas}=await import('./atlas-authoring.mjs');const atlas=await loadAuthoredAtlas();const ids=new Set([...atlas.records.map(r=>r.id),...pack.lessons.map(r=>r.id)]);
 for(const lesson of pack.lessons){assert.ok(lesson.description.length>500);assert.ok(lesson.mechanism.length>=3);assert.equal(lesson.science.length,eq[lesson.id].length);assert.equal(lesson.check.options.length,3);assert.ok(lesson.check.answer>=0&&lesson.check.answer<3);for(const id of [...lesson.prerequisites,...lesson.related])assert.ok(ids.has(id),id);for(const source of lesson.sourceIds)assert.ok(sources.has(source));for(const m of eq[lesson.id]){assert.equal(m.kind,'math');assert.ok(m.variables.length);katex.renderToString(m.latex,{throwOnError:true,strict:'error'});}}
 assert.deepEqual(pack.chapters.flatMap(c=>c.ids),pack.lessons.map(l=>l.id));for(const c of pack.claims){assert.ok(sources.has(c.sourceId));for(const id of c.lessonIds)assert.ok(ids.has(id));}
});
test('authored lesson numerical claims agree with the executable specimens',async()=>{
 const fs=await import('node:fs');const pack=JSON.parse(fs.readFileSync(new URL('../src/lib/data/hardware-runtime-learning.json',import.meta.url),'utf8'));
 for(const lesson of pack.lessons){const w=lesson.workedTrace;if(w.scenario){const patch=w.scenario==='abi-mismatch'?{boot:'abi-mismatch'}:w.scenario==='default'?{}:{fault:w.scenario};const r=run({...d,...patch});for(const [key,value] of Object.entries(w.expected??{})){const actual=key==='publishedResults'?r.events.filter(e=>e.kind==='publish').length:key in r?r[key]:r.totals[key];assert.deepEqual(actual,value,lesson.id+' '+key);}}
  if(lesson.id==='dma-visibility-ownership'){assert.deepEqual(run({...d,sync:'skip-to-device'}).finalOutput,w.expected.staleInputs);assert.deepEqual(run({...d,sync:'skip-to-cpu'}).finalOutput,w.expected.staleOutput);assert.equal(run({...d,fault:'early-reuse'}).totals.rejectedActions,w.expected.rejectedReuse);}
 }
});
