import test from 'node:test';import assert from 'node:assert/strict';
import {buildDecoderProjection,decoderProjectionDefaults,decoderProjectionExamples,decoderProjectionModels,normalizeDecoderProjectionSelection,projectionWordBytes,quantizeProjectionTile,readDecoderProjection,sampleDecoderProjection,serializeDecoderProjection} from '../src/lib/decoder-projection.ts';
import {advanceLifecycleRun,createLifecycleRun,inspectLifecycleForward,lifecycleFingerprint,lifecycleTensors,openLifecycleFinalTest} from '../src/lib/model-lifecycle.ts';
import {lifecycleExamples} from '../src/lib/model-lifecycle-data.ts';
const source=createLifecycleRun(),trained=advanceLifecycleRun(source,2),D=decoderProjectionDefaults;
const close=(a,b,tolerance=1e-12)=>assert.ok(Math.abs(a-b)<=tolerance,`${a} != ${b} within ${tolerance}`);
const matrixClose=(a,b,tolerance=1e-12)=>{assert.equal(a.length,b.length);for(let r=0;r<a.length;r++){assert.equal(a[r].length,b[r].length);for(let c=0;c<a[r].length;c++)close(a[r][c],b[r][c],tolerance);}};
const decode=bytes=>new DataView(Uint8Array.from(bytes).buffer).getInt32(0,true);
/** Independent original-operator reference: explicit coordinates, no adapter helpers. */
function originalReference(run,id){const ex=decoderProjectionExamples().find(x=>x.id===id),x=[],q=[];for(let p=0;p<3;p++){const row=[];let square=0;for(let k=0;k<6;k++){const positional=.15*(k%2?Math.cos(p/Math.pow(10000,(k-1)/6)):Math.sin(p/Math.pow(10000,k/6)));row.push(run.weights[ex.tokens[p]*6+k]+positional);square+=row[k]**2;}x.push(row.map(v=>v/Math.sqrt(square/6+.00001)));q.push([0,0,0]);for(let j=0;j<3;j++)for(let k=0;k<6;k++)q[p][j]+=x[p][k]*run.weights[54+k*6+j];}return{x,q};}
test('actual trained checkpoint identity, normalized operands and decoder query slice are preserved',()=>{const before=JSON.stringify(trained),r=buildDecoderProjection(trained),manual=originalReference(trained,D.exampleId);assert.equal(r.source.weightIdentity,lifecycleFingerprint(trained.weights));assert.equal(r.source.optimizerStep,2);assert.equal(r.source.dataDraws,4);matrixClose(r.normalized,manual.x);matrixClose(r.reference,manual.q);matrixClose(r.reference,inspectLifecycleForward(trained.weights,r.source.promptTokens).queries.slice(0,3).map(row=>row.slice(0,3)));assert.equal(r.floatExtractionMaxError,0);assert.deepEqual(r.source.originalShape,[5,6,6]);assert.deepEqual(r.source.selectedShape,[3,6,3]);assert.equal(JSON.stringify(trained),before);});
test('all six inner coordinates are used; a checkpoint with only the second half of WQ nonzero remains nonzero',()=>{const s=createLifecycleRun();for(let k=0;k<6;k++)for(let j=0;j<6;j++)s.weights[54+k*6+j]=k<3?0:(k-2)*(j+1)/10;const r=buildDecoderProjection(s),manual=originalReference(s,D.exampleId);matrixClose(r.reference,manual.q);assert.deepEqual(r.tiles.map(t=>t.innerIndices),[[0,1,2],[3,4,5]]);assert.ok(r.tiles[0].machine.finalOutput.flat().every(v=>v===0));assert.ok(r.tiles[1].machine.finalOutput.flat().some(v=>v!==0));matrixClose(r.output,r.tiles[1].dequantized);assert.ok(r.reference.flat().some(v=>v!==0));});
test('query weight orientation and token positions match exact source coordinates, including development prompts',()=>{for(const id of ['train-copy-b-v','development-copy-a-uv','development-copy-b-vvu']){const r=buildDecoderProjection(trained,{...D,exampleId:id}),ref=originalReference(trained,id);matrixClose(r.reference,ref.q);for(const t of r.tiles)for(const w of t.words){if(w.tensor==='B'){assert.equal(w.weightIndex,54+w.sourceRow*6+w.sourceColumn);assert.equal(t.b.original[w.row][w.column],trained.weights[w.weightIndex]);}else assert.equal(t.a.original[w.row][w.column],r.normalized[w.sourceRow][w.sourceColumn]);}}});
test('symmetric nearest rounding is ties-away-from-zero and zero is exactly represented',()=>{const q=quantizeProjectionTile([[-7,-.5,0],[.5,7,-2.5],[2.5,.49,-.49]],7);assert.equal(q.scale,1);assert.deepEqual(q.codes,[[-7,-1,0],[1,7,-3],[3,0,0]]);assert.equal(q.halfStep,.5);assert.equal(q.maxAbsError,.5);const z=quantizeProjectionTile([[0,0,0],[0,0,0],[0,0,0]],99);assert.equal(z.scale,1);assert.equal(z.halfStep,0);assert.deepEqual(z.reconstructed,z.original);assert.ok(quantizeProjectionTile([[Number.MIN_VALUE,0,0],[0,0,0],[0,0,0]],99).reconstructed.flat().every(Number.isFinite));});
test('quantization bound is independently checked over signed finite tile values',()=>{let rng=17;for(let n=0;n<80;n++){const x=Array.from({length:3},()=>Array.from({length:3},()=>{rng=(1664525*rng+1013904223)>>>0;return 200*rng/2**32-100;}));for(const maximum of [7,31,99]){const q=quantizeProjectionTile(x,maximum);for(let r=0;r<3;r++)for(let c=0;c<3;c++){assert.ok(Number.isInteger(q.codes[r][c])&&Math.abs(q.codes[r][c])<=maximum);close(q.reconstructed[r][c],q.codes[r][c]*q.scale);assert.ok(Math.abs(x[r][c]-q.reconstructed[r][c])<=q.halfStep+1e-13);}}}});
test('actual machine MAC operands decode from the exact named signed-int32 little-endian payload',()=>{const r=buildDecoderProjection(trained);for(const t of r.tiles){const words=new Map(t.words.map(w=>[`${w.tensor}[${w.row},${w.column}]`,w]));for(const w of t.words){assert.equal(w.bytes.length,4);assert.equal(decode(w.bytes),w.value);const m=t.machine.mappings.find(m=>m.tensor===w.tensor);assert.equal(w.physical,m.physicalStart+(w.row*3+w.column)*4);assert.equal(w.iova,m.iovaStart+(w.row*3+w.column)*4);}const expected=Array.from({length:3},()=>[0,0,0]);for(let i=0;i<3;i++)for(let j=0;j<3;j++)for(let k=0;k<3;k++)expected[i][j]+=decode(words.get(`A[${i},${k}]`).bytes)*decode(words.get(`B[${k},${j}]`).bytes);assert.deepEqual(t.machine.finalOutput,expected);for(const e of t.machine.events)for(const mac of e.macs){assert.equal(mac.a,decode(words.get(`A[${mac.row},${mac.k}]`).bytes));assert.equal(mac.b,decode(words.get(`B[${mac.k},${mac.column}]`).bytes));assert.equal(mac.after,mac.before+mac.a*mac.b);}for(const w of t.outputWords)assert.equal(decode(w.bytes),expected[w.row][w.column]);}});
test('two integer products rescale independently before addition; scales and errors have independent references',()=>{const r=buildDecoderProjection(trained,{...D,quantizationMax:7}),expected=Array.from({length:3},()=>[0,0,0]);for(const t of r.tiles)for(let row=0;row<3;row++)for(let col=0;col<3;col++)for(let k=0;k<3;k++)expected[row][col]+=t.a.reconstructed[row][k]*t.b.reconstructed[k][col];matrixClose(r.output,expected);let squares=0,referenceSquares=0;for(let i=0;i<3;i++)for(let j=0;j<3;j++){const error=r.output[i][j]-r.reference[i][j];squares+=error*error;referenceSquares+=r.reference[i][j]**2;close(r.errors.signed[i][j],error);assert.ok(Math.abs(error)<=r.errors.absoluteBound[i][j]+1e-12);}close(r.errors.rootMeanSquare,Math.sqrt(squares/9));close(r.errors.relativeFrobenius,Math.sqrt(squares/referenceSquares));assert.ok(r.tiles[0].a.scale!==r.tiles[1].a.scale);assert.ok(r.tiles[0].b.scale!==r.tiles[1].b.scale);});
test('integer range changes precision but never machine word size, MAC count or transfer denominators',()=>{const runs=[7,31,99].map(quantizationMax=>buildDecoderProjection(trained,{...D,quantizationMax}));for(const r of runs){assert.equal(r.totals.completedMacs,54);assert.equal(r.totals.operandLogicalBytes,36*4);assert.equal(r.totals.operandAllocatedBytes,4*48);assert.equal(r.totals.scalesBinary64Bytes,4*8);assert.equal(r.totals.selectedOriginalBinary64Bytes,36*8);assert.equal(r.totals.readTransactionBytes,832);assert.equal(r.totals.writeTransactionBytes,96);matrixClose(r.reference,runs[0].reference);}assert.notDeepEqual(runs[0].tiles[0].a.codes,runs[2].tiles[0].a.codes);assert.notEqual(runs[0].errors.maxAbsolute,runs[2].errors.maxAbsolute);});
test('bank, buffering and refresh controls change the machine schedule without changing query arithmetic',()=>{const baseline=buildDecoderProjection(source),durations=new Set();for(const bankPlacement of ['same-bank','split-banks'])for(const buffers of [1,2])for(const refreshEveryNs of [0,64,96,160]){const r=buildDecoderProjection(source,{...D,bankPlacement,buffers,refreshEveryNs});matrixClose(r.output,baseline.output,0);matrixClose(r.reference,baseline.reference,0);assert.equal(r.totals.completedMacs,54);durations.add(r.totals.machineScheduleNs);}assert.ok(durations.size>1);});
test('unmapped second tile has no accepted projection, fabricated error metric or combination event',()=>{const r=buildDecoderProjection(source,{...D,fault:'unmapped-second-tile'});assert.equal(r.status,'mapping-blocked');assert.equal(r.output,null);assert.equal(r.errors,null);assert.ok(r.tiles[0].dequantized);assert.equal(r.tiles[1].dequantized,null);assert.equal(r.tiles[1].outputWords.length,0);assert.equal(r.tiles[1].machine.totals.macs,0);assert.equal(r.totals.completedMacs,27);assert.equal(r.totals.writeTransactionBytes,48);assert.equal(r.events.filter(e=>e.kind==='combine').length,0);assert.equal(r.events.at(-1).machineEvent.kind,'mapping-fault');assert.equal(sampleDecoderProjection(r,r.events.length-1).accepted,false);});
test('event order disambiguates equal timestamps and exposes local versus joined clocks',()=>{const r=buildDecoderProjection(source);for(let i=0;i<r.events.length;i++){const e=r.events[i],sample=sampleDecoderProjection(r,i);assert.equal(e.index,i);if(i)assert.ok(e.timeNs>=r.events[i-1].timeNs);if(e.tile!==null)assert.equal(e.timeNs,r.tiles[e.tile].startNs+e.machineTimeNs);assert.equal(sample.accepted,e.kind==='combine');assert.ok(sample.completedMacs>=0&&sample.completedMacs<=54);}assert.equal(r.events.at(-1).kind,'combine');matrixClose(sampleDecoderProjection(r,r.events.length-1).partial,r.output,0);assert.equal(r.tiles[1].startNs,r.tiles[0].endNs);for(const i of [-1,.5,r.events.length,NaN])assert.throws(()=>sampleDecoderProjection(r,i));});
test('zero query weights produce a zero reference, zero output, and undefined relative error',()=>{const s=createLifecycleRun();for(let i=54;i<90;i++)s.weights[i]=0;const r=buildDecoderProjection(s);assert.ok(r.reference.flat().every(v=>v===0));assert.ok(r.output.flat().every(v=>v===0));assert.equal(r.errors.maxAbsolute,0);assert.equal(r.errors.relativeFrobenius,null);});
test('full trained checkpoint and exact selection roundtrip above 20k; outputs are recomputed',()=>{const selection={...D,exampleId:'development-copy-b-vu',quantizationMax:31,bankPlacement:'split-banks'},raw=serializeDecoderProjection(trained,selection);assert.ok(new TextEncoder().encode(raw).length>20000);const restored=readDecoderProjection(raw);assert.deepEqual(restored,{checkpoint:trained,selection});const a=buildDecoderProjection(trained,selection),b=buildDecoderProjection(restored.checkpoint,restored.selection);assert.deepEqual(b,a);restored.checkpoint.weights[0]=0;assert.notEqual(trained.weights[0],0);const forged=JSON.parse(raw);forged.output=[[100]];assert.throws(()=>readDecoderProjection(JSON.stringify(forged)),/fields/);});
test('source exposure remains disclosed and final-test prompts cannot be selected',()=>{const open=openLifecycleFinalTest(source),before=JSON.stringify(open),r=buildDecoderProjection(open);assert.equal(r.source.finalOpened,true);assert.equal(readDecoderProjection(serializeDecoderProjection(open)).checkpoint.finalOpened,true);assert.equal(JSON.stringify(open),before);assert.ok(decoderProjectionExamples().every(e=>e.split!=='final'));assert.throws(()=>buildDecoderProjection(open,{...D,exampleId:lifecycleExamples('final','copy')[0].id}),/final-test/);assert.equal(buildDecoderProjection(source).source.finalOpened,false);});
test('strict selection and envelope reject unknown fields, missing fields, bounds and model drift',()=>{for(const patch of [{quantizationMax:127},{quantizationMax:'99'},{buffers:3},{refreshEveryNs:1},{bankPlacement:'random'},{fault:'physical-rate'}, {exampleId:'final-copy-a-uvu'},{extra:true}])assert.throws(()=>normalizeDecoderProjectionSelection({...D,...patch}));for(const k of Object.keys(D)){const v={...D};delete v[k];assert.throws(()=>normalizeDecoderProjectionSelection(v));}for(const k of Object.keys(decoderProjectionModels)){const v=JSON.parse(serializeDecoderProjection(source));v.models[k]='old';assert.throws(()=>readDecoderProjection(JSON.stringify(v)),/identity/);}for(const mutate of [v=>{delete v.checkpoint},v=>{v.schemaVersion=2},v=>{v.models.extra='extra'},v=>{v.selection=[]},v=>{v.checkpoint.step=2}]){const v=JSON.parse(serializeDecoderProjection(source));mutate(v);assert.throws(()=>readDecoderProjection(JSON.stringify(v)));}});
test('source holes, erased values, invalid weights and oversized UTF-8 imports fail without mutation',()=>{for(const corrupt of [s=>{delete s.weights[2]},s=>{s.weights[0]=NaN},s=>{s.weights[0]=Infinity},s=>{s.weights[0]=101},s=>{s.reference[0]=undefined},s=>{s.moments[0]=null}]){const s=structuredClone(source);corrupt(s);assert.throws(()=>buildDecoderProjection(s));assert.throws(()=>serializeDecoderProjection(s));}assert.throws(()=>readDecoderProjection(' '.repeat(650001)),/650,000/);assert.throws(()=>readDecoderProjection('🧠'.repeat(162501)),/650,000/);assert.throws(()=>readDecoderProjection('not JSON'));});
test('word and tile helpers reject invalid shapes, nonintegers and sparse arrays',()=>{assert.deepEqual(projectionWordBytes(-99),[157,255,255,255]);assert.deepEqual(projectionWordBytes(2147483647),[255,255,255,127]);for(const v of [-2147483649,2147483648,NaN,Infinity,.5,'2'])assert.throws(()=>projectionWordBytes(v));for(const value of [[],[[1]],[[1,2,3],[4,5,6],[7,8,Infinity]],[[101,0,0],[0,0,0],[0,0,0]],Array(3)])assert.throws(()=>quantizeProjectionTile(value,99));const sparse=[[0,0,0],[0,0,0],[0,0,0]];delete sparse[1][0];assert.throws(()=>quantizeProjectionTile(sparse,99));});
test('quantization error bounds hold across source seeds, training and development choices',()=>{for(const seed of [1,7,19]){const s=seed===7?trained:createLifecycleRun({seed});for(const exampleId of ['train-copy-a-u','development-copy-b-vvu'])for(const quantizationMax of [7,31,99]){const r=buildDecoderProjection(s,{...D,exampleId,quantizationMax});for(let i=0;i<3;i++)for(let j=0;j<3;j++)assert.ok(Math.abs(r.errors.signed[i][j])<=r.errors.absoluteBound[i][j]+1e-12);}}});
