import test from 'node:test';
import assert from 'node:assert/strict';
import {Buffer} from 'node:buffer';
import {buildFactoryExecution,factoryDefaults,factoryConstants,factoryHallAdapter,factoryHallScenario,factoryUtf8Bytes,sampleFactoryExecution,normalizeFactoryInput,serializeFactoryInputs,readFactoryInputs,serializeFactoryWorkspace,readFactoryWorkspace,factoryModels} from '../src/lib/factory-execution.ts';
import {simulateOperatingHall} from '../src/lib/operating-hall.ts';
import {createLifecycleRun,advanceLifecycleRun,lifecycleExamples,lifecycleRandom,lifecycleSupervisedObjective,lifecycleFingerprint,openLifecycleFinalTest} from '../src/lib/model-lifecycle.ts';
import {createDistributedTrainingRun,beginDistributedRound,computeRankContribution,submitRankContribution,commitDistributedRound,readDistributedTrainingRun} from '../src/lib/model-lifecycle-distributed.ts';
import {createLifecycleExposureJournal} from '../src/lib/model-lifecycle-workspace.ts';
const close=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<=tol*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const vectorClose=(a,b,tol=1e-10)=>{assert.equal(a.length,b.length);a.forEach((x,i)=>close(x,b[i],tol));};
const noFault=buildFactoryExecution({...factoryDefaults,fault:'none'}),recovered=buildFactoryExecution();

/** Build transport artifacts from the numerical core, without factory scheduling or accounting.
 * Math transcendental results may differ in their last bits across JS runtimes, changing
 * JSON decimal lengths. Count the actual UTF-8 records; a byte/time golden is not portable.
 */
function baselineArtifacts(){
 let run=createDistributedTrainingRun(createLifecycleRun({seed:7}));
 const checkpoints=[{updates:0,raw:JSON.stringify(run)}],payloadBytes=[];
 for(let updates=1;updates<=3;updates++){
  run=beginDistributedRound(run);
  const contributions=run.round.ranks.map(rank=>computeRankContribution(run,rank.rank));
  for(const contribution of contributions){
   payloadBytes.push(Buffer.byteLength(JSON.stringify(contribution),'utf8'));
   run=submitRankContribution(run,contribution);
  }
  run=commitDistributedRound(run);
  if(updates===2||updates===3)checkpoints.push({updates,raw:JSON.stringify(run)});
 }
 return {checkpoints:checkpoints.map(cp=>({...cp,bytes:Buffer.byteLength(cp.raw,'utf8')})),payloadBytes};
}
const baseline=baselineArtifacts();

/** Independent full-batch objective, Adam arithmetic and RNG reservation: no factory/distributed scheduler helpers. */
function central(source,n){let weights=[...source.weights],moments=[...source.moments],squares=[...source.squares],rng=source.rng,step=source.optimizerStep;const pool=lifecycleExamples('train','copy'),lengths=pool.map(e=>e.tokens.length),short=pool.filter(e=>e.tokens.length===Math.min(...lengths)),long=pool.filter(e=>e.tokens.length===Math.max(...lengths));for(let round=0;round<n;round++){const examples=[];for(let i=0;i<4;i++){const draw=lifecycleRandom(rng);rng=draw.state;const choices=i===0?short:long;examples.push(choices[Math.floor(draw.value*choices.length)]);}const objective=lifecycleSupervisedObjective(weights,examples,false),scale=Math.min(1,source.config.clipNorm/Math.max(Math.hypot(...objective.gradient),1e-30));step++;weights=weights.map((w,i)=>{const g=objective.gradient[i]*scale;moments[i]=.9*moments[i]+.1*g;squares[i]=.999*squares[i]+.001*g*g;const direction=source.config.optimizer==='sgd'?g:(moments[i]/(1-.9**step))/(Math.sqrt(squares[i]/(1-.999**step))+1e-8);return w-source.config.learningRate*direction;});}return {weights,moments,squares,rng,step};}
function invariants(r){let time=0,it=0,facility=0,network=0,write=0,read=0,source=0,compute=0;for(const seg of r.segments){close(seg.startS,time);assert.ok(seg.endS>=seg.startS);const dt=seg.endS-seg.startS;time=seg.endS;it+=seg.power.itW*dt;facility+=seg.power.facilityW*dt;network+=seg.networkBytes;write+=seg.checkpointWriteBytes;read+=seg.checkpointReadBytes;source+=seg.sourceReadBytes;if(seg.phase==='rank-compute')compute+=dt;close(seg.power.facilityW,seg.power.itW+seg.power.facilityOverheadW);close(seg.power.itW,seg.power.coolantHeatW);if(seg.phase==='checkpoint-commit')assert.equal(seg.checkpointWriteBytes,0);}close(time,r.final.elapsedS);close(it,r.final.itEnergyJ);close(facility,r.final.facilityEnergyJ);close(facility,it*1.2);close(r.final.facilityEnergyJ,r.final.itEnergyJ+r.final.facilityOverheadJ);close(r.final.coolantHeatJ,r.final.itEnergyJ);close(r.final.rankBusyS+r.final.rankIdleSlotS,2*compute);assert.equal(network,r.final.networkBytes);assert.equal(write,r.final.checkpointWriteBytes);assert.equal(read,r.final.checkpointReadBytes);assert.equal(source,r.final.sourceReadBytes);for(const e of r.events){const c=e.snapshot.counters;assert.equal(c.executedUpdates,c.rolledBackUpdates+c.retainedUpdates,e.kind);assert.equal(c.rankComputations,c.rolledBackRankComputations+2*c.retainedUpdates+c.pendingRankComputations,e.kind);assert.ok(c.durableUpdates<=c.retainedUpdates,e.kind);assert.ok(c.facilityEnergyJ>=c.itEnergyJ);}if(r.status==='complete'){assert.equal(r.final.retainedUpdates,r.input.rounds);assert.equal(r.final.durableUpdates,r.input.rounds);assert.equal(r.finalRun.state.optimizerStep,r.finalRun.sourceCheckpoint.optimizerStep+r.input.rounds);assert.equal(r.finalRun.dataDraws,4*r.input.rounds);assert.deepEqual(r.equivalence,{weights:0,moments:0,squares:0,rngMatches:true,cursorMatches:true});}}

test('actual three-update result agrees with independent centralized objective and optimizer',()=>{const expected=central(createLifecycleRun(),3);vectorClose(noFault.finalRun.state.weights,expected.weights);vectorClose(noFault.finalRun.state.moments,expected.moments);vectorClose(noFault.finalRun.state.squares,expected.squares);assert.equal(noFault.finalRun.rng,expected.rng);assert.equal(noFault.finalRun.state.optimizerStep,expected.step);assert.notEqual(lifecycleFingerprint(expected.weights),noFault.sourceIdentity);invariants(noFault);});
test('carried trained source retains actual optimizer, RNG and exposure with no mutation',()=>{for(const optimizer of ['adam','sgd']){const source=openLifecycleFinalTest(advanceLifecycleRun(createLifecycleRun({seed:11,optimizer}),3)),before=JSON.stringify(source),r=buildFactoryExecution({...factoryDefaults,rounds:2},source),expected=central(source,2);assert.equal(JSON.stringify(source),before);assert.equal(r.sourceIdentity,lifecycleFingerprint(source.weights));assert.equal(r.finalRun.state.optimizerStep,5);assert.equal(r.finalRun.sourceCheckpoint.finalOpened,true);vectorClose(r.finalRun.state.weights,expected.weights);vectorClose(r.finalRun.state.moments,expected.moments);assert.equal(r.finalRun.rng,expected.rng);invariants(r);}});
test('hall power adapter matches existing model at all three physical power boundaries',()=>{const adapter=factoryHallAdapter(factoryDefaults),scenario=factoryHallScenario(factoryDefaults);scenario.service.computeOpsPerPackageS=.5;scenario.checkpoint.intervalRunS=1;scenario.faults=[{id:'probe',atS:1.2,recoveryDelayS:.2,cause:'worker-stop'}];scenario.durationS=3;const hall=simulateOperatingHall(scenario);assert.deepEqual(adapter.admission,hall.admission);for(const [name,phase] of [['run','run'],['checkpoint','checkpoint-write'],['recovery','recovery-read']]){const seg=hall.segments.find(s=>s.phase===phase);assert.ok(seg,phase);for(const key of ['itW','facilityW','coolantHeatW','facilityOverheadW','coolantRiseK'])close(adapter.powers[name][key],seg.rates[key]);}close(adapter.powers.run.facilityW,160);close(adapter.powers.checkpoint.facilityW,160/3);close(adapter.powers.recovery.facilityW,40);});
test('baseline wall time and energy follow a hand-derived exclusive schedule',()=>{
 assert.deepEqual(noFault.checkpoints.map(({updates,raw,bytes})=>({updates,raw,bytes})),baseline.checkpoints);
 assert.deepEqual(noFault.segments.filter(s=>s.phase==='network').map(s=>s.networkBytes),baseline.payloadBytes);
 const initial=baseline.checkpoints[0].bytes,bytes=baseline.checkpoints.slice(1).reduce((s,c)=>s+c.bytes,0),networkBytes=baseline.payloadBytes.reduce((sum,bytes)=>sum+bytes,0);
 const compute=3*(24*.01+.3),network=networkBytes/8192+6*.02,optimizer=3*.02,storage=bytes/65536,markers=2*.05,source=initial/65536;
 assert.equal(noFault.final.sourceReadBytes,initial);
 assert.equal(noFault.final.checkpointWriteBytes,bytes);
 assert.equal(noFault.final.networkBytes,networkBytes);
 close(noFault.final.elapsedS,.2+source+compute+network+optimizer+storage+markers);
 close(noFault.final.facilityEnergyJ,40*source+160*(compute+network+optimizer)+(160/3)*(storage+markers));
});
test('default partial-write recovery replays exactly two lost optimizer updates',()=>{
 const checkpoint=baseline.checkpoints.find(cp=>cp.updates===2),partialBytes=Math.floor(checkpoint.bytes/2);
 assert.equal(recovered.status,'complete');assert.equal(recovered.final.executedUpdates,5);assert.equal(recovered.final.rolledBackUpdates,2);assert.equal(recovered.final.rankComputations,10);assert.equal(recovered.final.rolledBackRankComputations,4);
 assert.deepEqual(recovered.abortedCheckpoints,[{updates:2,expectedBytes:checkpoint.bytes,writtenBytes:partialBytes,status:'aborted'}]);
 assert.equal(recovered.final.abortedCheckpointBytes,partialBytes);
 assert.equal(recovered.final.checkpointWriteBytes,partialBytes+baseline.checkpoints.slice(1).reduce((sum,cp)=>sum+cp.bytes,0));
 vectorClose(recovered.finalRun.state.weights,noFault.finalRun.state.weights,0);assert.equal(recovered.finalRun.rng,noFault.finalRun.rng);invariants(recovered);
});
test('all fault modes and checkpoint cadences preserve accounting and exact replay',()=>{for(const fault of ['none','rank-stop','after-update','checkpoint-write','checkpoint-commit'])for(const checkpointEvery of [1,2,3])for(const rounds of [2,3]){const r=buildFactoryExecution({...factoryDefaults,fault,checkpointEvery,rounds});invariants(r);assert.equal(r.faultTriggered,fault!=='none');}});
test('whole-job stop leaves only the earlier valid artifact and never publishes',()=>{for(const fault of ['rank-stop','after-update','checkpoint-write','checkpoint-commit']){const r=buildFactoryExecution({...factoryDefaults,fault,recover:false});assert.equal(r.status,'stopped');assert.equal(r.finalRun,null);assert.equal(r.durableRun.commits,0);assert.equal(r.final.checkpointReadBytes,0);assert.equal(r.final.durableUpdates,0);assert.ok(!r.events.some(e=>e.kind==='published'));invariants(r);}});
test('partial checkpoint bytes and a fully written uncommitted checkpoint cannot replace old state',()=>{const partial=buildFactoryExecution({...factoryDefaults,recover:false}),written=buildFactoryExecution({...factoryDefaults,fault:'checkpoint-commit',recover:false}),full=noFault.checkpoints.find(c=>c.updates===2).bytes;assert.equal(partial.final.checkpointWriteBytes,Math.floor(full/2));assert.equal(written.final.checkpointWriteBytes,full);assert.equal(partial.abortedCheckpoints[0].writtenBytes,Math.floor(full/2));assert.equal(written.abortedCheckpoints[0].writtenBytes,full);assert.equal(written.checkpoints.length,1);assert.equal(partial.checkpoints[0].raw,written.checkpoints[0].raw);assert.ok(written.events.find(e=>e.kind==='checkpoint-written').snapshot.durableUpdates===0);});
test('a completed earlier checkpoint restores weights, moments, cursor and RNG together',()=>{const r=buildFactoryExecution({...factoryDefaults,checkpointEvery:1}),first=r.checkpoints.find(c=>c.updates===1),saved=readDistributedTrainingRun(first.raw),restored=r.events.find(e=>e.kind==='restored').snapshot;assert.equal(r.final.rolledBackUpdates,1);assert.deepEqual(restored.weights,saved.state.weights);assert.deepEqual(restored.moments,saved.state.moments);assert.deepEqual(restored.squares,saved.state.squares);assert.equal(restored.rng,saved.rng);assert.equal(restored.dataDraws,saved.dataDraws);assert.equal(r.final.checkpointReadBytes,first.bytes);});
test('incomplete rank barrier leaves model and optimizer unchanged',()=>{const events=noFault.events;for(const e of events.filter(e=>e.kind==='barrier-wait')){const reserved=[...events.slice(0,e.index)].reverse().find(x=>x.kind==='round-reserved');assert.deepEqual(e.snapshot.weights,reserved.snapshot.weights);assert.deepEqual(e.snapshot.moments,reserved.snapshot.moments);assert.equal(e.snapshot.optimizerStep,reserved.snapshot.optimizerStep);assert.equal(e.snapshot.ranks.filter(r=>r.status==='submitted').length,1);}assert.equal(noFault.final.barrierRejections,3);});
test('rank failure counts finished gradients, separate partial elapsed slots, and concurrent wall time',()=>{const r=buildFactoryExecution({...factoryDefaults,fault:'rank-stop'}),fault=r.events.find(e=>e.kind==='job-fault');assert.equal(r.final.rankComputations,9);assert.equal(r.final.rolledBackRankComputations,3);assert.equal(fault.snapshot.ranks.filter(x=>x.status==='computed').length,1);assert.equal(fault.snapshot.ranks.filter(x=>x.status==='computing').length,1);const failedCompute=r.segments.filter(s=>s.phase==='rank-compute'&&s.endS<=fault.atS);close(failedCompute.slice(-2).reduce((sum,s)=>sum+s.endS-s.startS,0),.27);invariants(r);});
test('slower rank changes the schedule and energy but not model state or payload',()=>{const fast=buildFactoryExecution({...factoryDefaults,fault:'none',slowRankDelayS:0}),slow=buildFactoryExecution({...factoryDefaults,fault:'none',slowRankDelayS:1});close(slow.final.elapsedS-fast.final.elapsedS,3);close(slow.final.facilityEnergyJ-fast.final.facilityEnergyJ,480);assert.deepEqual(slow.finalRun,fast.finalRun);assert.equal(slow.final.networkBytes,fast.final.networkBytes);});
test('network throughput changes only serialization time; payload is counted once at transmission',()=>{const fast=buildFactoryExecution({...factoryDefaults,fault:'none',networkBytesS:16384});close(noFault.final.elapsedS-fast.final.elapsedS,noFault.final.networkBytes*(1/8192-1/16384));assert.deepEqual(noFault.finalRun,fast.finalRun);const delivered=noFault.events.filter(e=>e.kind==='rank-delivered').reduce((sum,e)=>{const rank=e.snapshot.ranks.find(r=>r.status==='submitted'&&(r.rank===1||e.snapshot.ranks[1].status!=='submitted'));return sum+(e.detail.startsWith('Rank 0')?e.snapshot.ranks[0].payloadBytes:e.snapshot.ranks[1].payloadBytes);},0);assert.equal(delivered,noFault.final.networkBytes);assert.equal(factoryUtf8Bytes('μ'),2);});
test('checkpoint capacity accounts for old and new versions without deleting the old artifact',()=>{const r=buildFactoryExecution({...factoryDefaults,storageLimitBytes:120000,fault:'none'});assert.equal(r.status,'blocked');assert.equal(r.final.retainedUpdates,2);assert.equal(r.final.durableUpdates,0);assert.equal(r.checkpoints.length,1);assert.equal(r.final.checkpointWriteBytes,0);assert.equal(r.finalRun.commits,2);invariants(r);const cp0=noFault.checkpoints[0],cp2=noFault.checkpoints[1],atLimit=buildFactoryExecution({...factoryDefaults,rounds:2,fault:'none',storageLimitBytes:cp0.bytes+cp2.bytes});assert.equal(atLimit.status,'complete');const short=buildFactoryExecution({...factoryDefaults,rounds:2,fault:'none',storageLimitBytes:cp0.bytes+cp2.bytes-1});assert.equal(short.status,'blocked');});
test('admission and runtime failures prevent actual model execution',()=>{for(const patch of [{feedLimitW:159.99},{coolantFlowKgS:0},{readiness:'firmware-mismatch'},{readiness:'wrong-mapping'},{storageLimitBytes:10000}]){const r=buildFactoryExecution({...factoryDefaults,...patch});assert.equal(r.status,'blocked');assert.equal(r.final.executedUpdates,0);assert.equal(r.final.rankComputations,0);assert.equal(r.final.networkBytes,0);assert.equal(r.final.sourceReadBytes,0);assert.equal(r.final.facilityEnergyJ,0);invariants(r);}assert.equal(buildFactoryExecution({...factoryDefaults,feedLimitW:160}).status,'complete');});
test('every exported committed artifact is an actual compatible full numerical checkpoint',()=>{for(const cp of recovered.checkpoints){assert.equal(cp.bytes,new TextEncoder().encode(cp.raw).length);const restored=readDistributedTrainingRun(cp.raw);assert.equal(restored.commits,cp.updates);assert.equal(lifecycleFingerprint(restored.state.weights),cp.fingerprint);assert.equal(restored.state.weights.length,423);assert.equal(restored.state.moments.length,423);assert.equal(restored.state.squares.length,423);}assert.deepEqual(readDistributedTrainingRun(recovered.checkpoints.at(-1).raw),recovered.finalRun);});
test('time cursor integrates partial traffic and energy without claiming a completed event early',()=>{const seg=noFault.segments.find(s=>s.phase==='network'),at=(seg.startS+seg.endS)/2,s=sampleFactoryExecution(noFault,at);close(s.fraction,.5);close(s.counters.networkBytes,seg.start.networkBytes+seg.networkBytes/2);close(s.counters.facilityEnergyJ,seg.start.facilityEnergyJ+seg.power.facilityW*(at-seg.startS));assert.ok(s.event.atS<=at);assert.ok(s.event.snapshot.ranks.every(r=>r.status!=='submitted'));const last=sampleFactoryExecution(noFault,noFault.final.elapsedS);assert.deepEqual(last.counters,noFault.final);assert.throws(()=>sampleFactoryExecution(noFault,-1));assert.throws(()=>sampleFactoryExecution(noFault,Infinity));});
test('strict inputs reject invalid dimensions, unknown fields and altered model identities',()=>{for(const patch of [{seed:0},{rounds:5},{faultRound:4},{checkpointEvery:1.5},{networkBytesS:0},{storageBytesS:NaN},{recover:1},{fault:'random'},{readiness:'any'},{unused:1}])assert.throws(()=>normalizeFactoryInput({...factoryDefaults,...patch}));assert.deepEqual(readFactoryInputs(serializeFactoryInputs(factoryDefaults)),factoryDefaults);const raw=JSON.parse(serializeFactoryInputs(factoryDefaults));raw.models.decoder='old';assert.throws(()=>readFactoryInputs(JSON.stringify(raw)));raw.models={...factoryModels};raw.extra=true;assert.throws(()=>readFactoryInputs(JSON.stringify(raw)));});
test('full portable workspace restores its trained source rather than silently restarting from seed',()=>{const source=advanceLifecycleRun(createLifecycleRun({seed:17}),2),raw=serializeFactoryWorkspace(factoryDefaults,source),restored=readFactoryWorkspace(raw);assert.deepEqual(restored.sourceCheckpoint,source);assert.deepEqual(restored.input,factoryDefaults);assert.notEqual(lifecycleFingerprint(restored.sourceCheckpoint.weights),lifecycleFingerprint(createLifecycleRun().weights));const damaged=JSON.parse(raw);delete damaged.sourceCheckpoint.moments;assert.throws(()=>readFactoryWorkspace(JSON.stringify(damaged)));const reordered=JSON.parse(raw);reordered.models=Object.fromEntries(Object.entries(factoryModels).reverse());assert.deepEqual(readFactoryWorkspace(JSON.stringify(reordered)),restored);});
test('procedural final-test exposure survives older factory workspace restoration through shared journal',()=>{const store=new Map(),journal=createLifecycleExposureJournal({getItem:key=>store.get(key)??null,setItem:(key,value)=>store.set(key,value)});journal.retain(openLifecycleFinalTest(createLifecycleRun()));const old=readFactoryWorkspace(serializeFactoryWorkspace(factoryDefaults,createLifecycleRun()));const source=journal.retain(old.sourceCheckpoint);assert.equal(source.finalOpened,true);const r=buildFactoryExecution({...factoryDefaults,rounds:1,faultRound:1},source);assert.equal(r.finalRun.sourceCheckpoint.finalOpened,true);});

test('checkpoint preserves actual gradient ownership, owner optimizer slices and gathered replicas',()=>{for(const result of [noFault,recovered]){const collective=result.finalRun.round.collective;assert.equal(collective.phase,'gathered');assert.deepEqual(collective.updatedShards.map(s=>[s.owner,s.start,s.end]),[[0,0,212],[1,212,423]]);assert.deepEqual(collective.updatedShards.flatMap(s=>s.weights),result.finalRun.state.weights);assert.deepEqual(collective.updatedShards.flatMap(s=>s.moments),result.finalRun.state.moments);assert.deepEqual(collective.updatedShards.flatMap(s=>s.squares),result.finalRun.state.squares);assert.equal(collective.replicas.length,2);for(const replica of collective.replicas)assert.deepEqual(replica.weights,result.finalRun.state.weights);assert.deepEqual(readDistributedTrainingRun(result.checkpoints.at(-1).raw).round.collective,collective);}});
