import test from 'node:test';import assert from 'node:assert/strict';
import {buildFifoTrace,fifoDefaults,grayEncode,grayDecode,normalizeFifoInput,encodeSecded,decodeSecded,buildEccRecovery,eccDefaults,normalizeEccInput,makeReliabilityRecord,parseReliabilityRecord} from '../src/lib/hardware-reliability.ts';
function auditFifo(t){
 let prev=null;for(const e of t.events){const s=e.state;assert.equal(s.accepted.length,s.consumed.length+s.canceled.length+s.expectedQueue.length);assert.equal(new Set(s.accepted).size,s.accepted.length);assert.equal(new Set(s.consumed).size,s.consumed.length);assert.ok(s.consumed.every(x=>!s.canceled.includes(x)));assert.ok(s.expectedQueue.length<=4);assert.ok(s.expectedQueue.every(id=>s.slots.includes(id)));assert.equal(s.writeGray,grayEncode(s.writePointer));assert.equal(s.readGray,grayEncode(s.readPointer));if(e.acceptedTag){assert.equal(e.writeEdge,true);assert.equal(e.writeReady,true);assert.equal(e.producerValid,true);}if(e.observedTag){assert.equal(e.readEdge,true);assert.equal(e.readValid,true);assert.equal(e.consumerReady,true);assert.equal(e.correct,true);assert.equal(e.observedValue,t.input.values[Number(e.observedTag.split('-')[1])]);}
  if(prev&&!e.reset){const p=prev.state;if(e.writeEdge){assert.deepEqual(s.readSyncInWriter,[p.readGray,p.readSyncInWriter[0]]);}else assert.deepEqual(s.readSyncInWriter,p.readSyncInWriter);if(e.readEdge){assert.deepEqual(s.writeSyncInReader,[p.writeGray,p.writeSyncInReader[0]]);}else assert.deepEqual(s.writeSyncInReader,p.writeSyncInReader);}
  prev=e;
 }
 assert.equal(t.violation,null);
}
test('Gray pointer cycle changes exactly one bit and decodes all eight states',()=>{for(let p=0;p<8;p++){assert.equal(grayDecode(grayEncode(p)),p);const diff=grayEncode(p)^grayEncode((p+1)%8);assert.ok(diff>0&&(diff&(diff-1))===0);}for(const x of [-1,8,.5,NaN])assert.throws(()=>grayEncode(x));});
test('default FIFO delivers all eight tagged values with conservative full/empty stalls',()=>{const t=buildFifoTrace(fifoDefaults);auditFifo(t);assert.equal(t.status,'complete');assert.deepEqual(t.totals,{accepted:8,consumed:8,canceled:0,pending:0,writeStalls:10,emptyReadEdges:2});});
test('360 clock/backpressure/reset scenarios retain exact ordering and cancellation accounting',()=>{for(let writePeriod=2;writePeriod<=7;writePeriod++)for(let readPeriod=2;readPeriod<=7;readPeriod++)for(const consumer of ['ready','bursty'])for(const resetAt of [0,1,7,23,40]){const t=buildFifoTrace({...fifoDefaults,writePeriod,readPeriod,consumer,reset:resetAt===0?'none':'both',resetAt:resetAt||1,horizon:240});auditFifo(t);assert.equal(t.status,'complete');}});
test('simultaneous edges sample pre-edge opposite-domain pointers',()=>{const t=buildFifoTrace({...fifoDefaults,writePeriod:2,readPeriod:2});auditFifo(t);const e=t.events.find(e=>e.time===2);assert.equal(e.state.writePointer,1);assert.deepEqual(e.state.writeSyncInReader,[0,0]);assert.equal(t.events.find(e=>e.time===4).state.writeSyncInReader[0],1);});
test('coordinated reset cancels outstanding tags instead of claiming their delivery',()=>{const t=buildFifoTrace({...fifoDefaults,reset:'both'});auditFifo(t);assert.equal(t.totals.canceled,3);assert.equal(t.totals.consumed,5);const e=t.events.find(e=>e.reset);assert.deepEqual(e.state.expectedQueue,[]);assert.deepEqual(e.state.slots,[null,null,null,null]);});
test('reader-only reset produces an actual out-of-order counterexample',()=>{const t=buildFifoTrace({...fifoDefaults,reset:'reader-only'});assert.equal(t.status,'contract-violation');const e=t.events.at(-1);assert.equal(e.time,35);assert.equal(e.observedTag,'tag-4');assert.equal(e.state.expectedQueue[0],'tag-2');assert.equal(e.correct,false);assert.equal(t.totals.consumed,2);});
test('a short horizon reports remaining tags rather than declaring completion',()=>{const t=buildFifoTrace({...fifoDefaults,values:Array(12).fill(3),readPeriod:7,consumer:'bursty',horizon:40});auditFifo(t);assert.equal(t.status,'incomplete');assert.ok(t.totals.pending>0);});
const flip=(bits,positions)=>bits.map((b,i)=>positions.includes(i+1)?b^1:b);
test('all 16 valid codewords have zero checks and recover their four data bits',()=>{for(let x=0;x<16;x++){const d=decodeSecded(encodeSecded(x));assert.equal(d.syndrome,0);assert.equal(d.overallParity,0);assert.equal(d.payload,x);assert.equal(d.classification,'clean');}});
test('all 128 single-bit errors are corrected, including the overall parity bit',()=>{for(let x=0;x<16;x++)for(let p=1;p<=8;p++){const original=encodeSecded(x),d=decodeSecded(flip(original,[p]));assert.equal(d.payload,x);assert.equal(d.correctedPosition,p);assert.deepEqual(d.correctedBits,original);}});
test('all 448 double-bit errors are detected and never supplied to the consumer',()=>{for(let x=0;x<16;x++)for(let p=1;p<=8;p++)for(let q=p+1;q<=8;q++){const d=decodeSecded(flip(encodeSecded(x),[p,q]));assert.equal(d.classification,'double-detected');assert.equal(d.payload,null);assert.equal(d.correctedPosition,null);}});
test('code construction agrees with a separately specified parity matrix',()=>{const H=[[1,0,1,0,1,0,1,0],[0,1,1,0,0,1,1,0],[0,0,0,1,1,1,1,0],[1,1,1,1,1,1,1,1]];for(let x=0;x<16;x++){const b=encodeSecded(x);for(const row of H)assert.equal(row.reduce((s,a,i)=>s+a*b[i],0)%2,0);}});
test('three-bit fixture can be miscorrected and its oracle mismatch remains explicit',()=>{const t=buildEccRecovery({...eccDefaults,flips:[1,2,3]});assert.equal(t.withinGuarantee,false);assert.equal(t.decoded.classification,'overall-corrected');assert.equal(t.decoded.payload,8);assert.equal(t.fixtureTruthMatches,false);assert.equal(t.status,'silent-corruption-in-fixture');assert.equal(t.finalSum,53);assert.equal(t.referenceSum,54);});
function auditRecovery(t){for(const e of t.events){assert.equal(e.executedSteps,e.completedSteps+e.discardedSteps);assert.ok(e.checkpointSteps<=e.completedSteps);if(e.kind==='compute')assert.notEqual(e.decoded.payload,null);if(e.kind==='restore'){assert.equal(e.completedSteps,e.checkpointSteps);assert.equal(e.sum,e.checkpointSum);}}}
test('double error restores a trusted checkpoint and recomputes lost work exactly once',()=>{const t=buildEccRecovery(eccDefaults);auditRecovery(t);assert.equal(t.finalSum,54);assert.deepEqual(t.totals,{executedSteps:7,discardedSteps:1,completedSteps:6,checkpointSteps:6,reads:8,restores:1});});
test('recovery ledger holds for every fault step, checkpoint interval and payload',()=>{for(let payload=0;payload<16;payload++)for(let faultStep=1;faultStep<=6;faultStep++)for(let checkpointEvery=1;checkpointEvery<=4;checkpointEvery++){const t=buildEccRecovery({...eccDefaults,payload,faultStep,checkpointEvery});auditRecovery(t);assert.equal(t.finalSum,payload*6);assert.equal(t.totals.restores,1);}});
test('stop policy exposes completed versus checkpointed work and publishes no final result',()=>{const t=buildEccRecovery({...eccDefaults,recovery:'stop'});auditRecovery(t);assert.equal(t.status,'blocked');assert.equal(t.finalSum,null);assert.equal(t.totals.completedSteps,3);assert.equal(t.totals.checkpointSteps,2);assert.equal(t.totals.discardedSteps,0);});
test('healthy and correctable words need no restart',()=>{for(const flips of [[],[1],[8]]){const t=buildEccRecovery({...eccDefaults,flips});auditRecovery(t);assert.equal(t.finalSum,54);assert.equal(t.totals.restores,0);assert.equal(t.totals.discardedSteps,0);}});
test('input and snapshots are copied; records restore only matching model identity',()=>{const r=makeReliabilityRecord(fifoDefaults,eccDefaults);assert.deepEqual(parseReliabilityRecord(JSON.stringify(r)),r);const f=buildFifoTrace(fifoDefaults);f.events[0].state.slots[0]='bad';assert.notEqual(f.events[1].state.slots[0],'bad');for(const patch of [{schemaVersion:2},{modelVersion:'old'},{extra:0}])assert.throws(()=>parseReliabilityRecord(JSON.stringify({...r,...patch})));});
test('invalid clocks, reset bounds, bit patterns and sparse arrays reject',()=>{for(const p of [{writePeriod:0},{readPeriod:8},{values:Array(2)},{values:[Infinity]},{reset:'magic'},{horizon:300},{resetAt:0},{extra:1}])assert.throws(()=>normalizeFifoInput({...fifoDefaults,...p}));for(const p of [{payload:16},{payload:-1},{flips:[1,1]},{flips:[9]},{flips:Array(1)},{flips:[1,2,3,4]},{steps:9},{faultStep:7},{checkpointEvery:0},{extra:1}])assert.throws(()=>normalizeEccInput({...eccDefaults,...p}));for(const b of [Array(8),Array(8).fill(2),[]])assert.throws(()=>decodeSecded(b));});
test('all codeword pairs establish minimum distance four',()=>{let minimum=8;for(let a=0;a<16;a++)for(let b=a+1;b<16;b++){const x=encodeSecded(a),y=encodeSecded(b);minimum=Math.min(minimum,x.filter((v,i)=>v!==y[i]).length);}assert.equal(minimum,4);});
import {saveReliabilityRecord,olderReliabilityRecords,reliabilityRecordKey,reliabilityRecoveryKey} from '../src/lib/hardware-reliability.ts';
const store=()=>{const m=new Map();return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,v)};};
test('incompatible raw reliability records survive replacement exactly',()=>{const s=store(),old='older\nraw input';s.setItem(reliabilityRecordKey,old);saveReliabilityRecord(s,makeReliabilityRecord(fifoDefaults,eccDefaults));assert.equal(olderReliabilityRecords(s),old);assert.deepEqual(parseReliabilityRecord(s.getItem(reliabilityRecordKey)),makeReliabilityRecord(fifoDefaults,eccDefaults));});
test('backup quota failure preserves the prior active reliability record',()=>{const s=store();s.setItem(reliabilityRecordKey,'prior');const fail={getItem:s.getItem,setItem:(k,v)=>{if(k===reliabilityRecoveryKey)throw new Error('quota');s.setItem(k,v);}};assert.throws(()=>saveReliabilityRecord(fail,makeReliabilityRecord(fifoDefaults,eccDefaults)),/quota/);assert.equal(s.getItem(reliabilityRecordKey),'prior');});
test('corrupt recovery storage remains exportable and cannot be overwritten by save',()=>{const s=store();s.setItem(reliabilityRecordKey,'prior');s.setItem(reliabilityRecoveryKey,'invalid backup');assert.deepEqual(JSON.parse(olderReliabilityRecords(s)).records,['invalid backup','prior']);assert.throws(()=>saveReliabilityRecord(s,makeReliabilityRecord(fifoDefaults,eccDefaults)));assert.equal(s.getItem(reliabilityRecordKey),'prior');});
