import test from 'node:test';
import assert from 'node:assert/strict';
import {buildMachineExecution as build,machineDefaults as defaults,machineTiming as timing,normalizeMachineInput as normalize,decodeMachineAddress,translateMachineAddress,machineEventAt} from '../src/lib/machine-execution.ts';
import {makeMachineRecord,parseMachineRecord,saveMachineRecord,exportOlderMachineRecords,machineRecordKey,machineRecoveryKey} from '../src/lib/machine-execution-record.ts';
const oracle=(a,b)=>a.map(row=>b[0].map((_,j)=>Number(row.reduce((s,x,k)=>s+BigInt(x)*BigInt(b[k][j]),0n))));
function audit(t){
 const n=t.input.size,expected=oracle(t.input.a,t.input.b);assert.deepEqual(t.reference,expected);if(t.status==='mapping-blocked'){assert.equal(t.finalOutput,null);assert.equal(t.transactions.length,0);return;}
 assert.deepEqual(t.finalOutput,expected);assert.equal(t.totals.macs,n**3);
 const macs=new Set(),completed=new Set();let previous=0;const acc=Array.from({length:n},()=>Array(n).fill(0));
 for(const e of t.events){assert.ok(e.timeNs>=previous);previous=e.timeNs;
  for(const m of e.macs){const id=[m.row,m.column,m.k].join(':');assert.ok(!macs.has(id));macs.add(id);assert.equal(m.a,t.input.a[m.row][m.k]);assert.equal(m.b,t.input.b[m.k][m.column]);assert.equal(m.before,acc[m.row][m.column]);acc[m.row][m.column]+=m.a*m.b;assert.equal(m.after,acc[m.row][m.column]);}
  assert.deepEqual(e.state.partialOutput,acc);
  if(e.kind==='read-complete'||e.kind==='write-complete'){assert.ok(!completed.has(e.transactionId));completed.add(e.transactionId);}
  for(const b of e.state.buffers){if(b.phase==='free'){assert.equal(b.batchId,null);assert.deepEqual(b.words,{});}else assert.ok(b.batchId);}
  if(e.state.outputOwner==='cpu')assert.equal(e.state.storedOutputs.length,n*n);
 }
 assert.equal(macs.size,n**3);assert.equal(completed.size,t.transactions.length);assert.equal(t.events.at(-1).kind,'host-sync');
 for(const b of t.batches){assert.ok(b.submittedNs<=b.readyNs);assert.ok(b.readyNs<=b.computeStartNs);assert.equal(b.computeEndNs-b.computeStartNs,b.sharedRounds+t.input.macNs);assert.equal(b.readyNs,Math.max(...b.transactionIds.map(id=>t.transactions.find(x=>x.id===id).completedNs)));}
 for(const x of t.transactions){assert.equal(x.iova%16,0);assert.equal(x.physical%16,0);assert.equal(x.dataEndNs-x.dataStartNs,timing.burstNs);assert.equal(x.completedNs-x.dataEndNs,x.direction==='write'?timing.tWRNs:0);assert.equal(x.queueWaitNs,x.serviceStartNs-x.submittedNs);assert.ok(x.queueWaitNs>=0);assert.equal(x.commandNs+(x.direction==='read'?timing.tCLNs:timing.tCWLNs),x.dataStartNs);assert.deepEqual(x.address,decodeMachineAddress(x.physical));for(const o of x.operands)assert.ok(o.physical>=x.physical&&o.physical+4<=x.physical+16);}
 assert.equal(t.totals.readTransactionBytes,t.transactions.filter(x=>x.direction==='read').length*16);assert.equal(t.totals.distinctInputBytes,n*n*8);assert.equal(t.totals.requestedReadBytes,n**3*8);
 // Independently check the declared command timing and open-row state, including refresh.
 const banks=[{row:null,act:-Infinity,closedAt:-Infinity},{row:null,act:-Infinity,closedAt:-Infinity}];let busy=0;
 for(const c of [...t.commands].sort((a,b)=>a.startNs-b.startNs)){
  assert.ok(c.startNs>=busy,`${c.kind} cannot overlap the serialized controller`);
  if(c.kind==='ACT'){const b=banks[c.bank];assert.equal(b.row,null);assert.ok(c.startNs>=b.closedAt);b.row=c.row;b.act=c.startNs;busy=c.endNs;}
  else if(c.kind==='PRE'){const b=banks[c.bank];assert.notEqual(b.row,null);assert.ok(c.startNs>=b.act+timing.tRASNs);b.row=null;b.closedAt=c.endNs;busy=c.endNs;}
  else if(c.kind==='PREA'){for(const b of banks){if(b.row!==null)assert.ok(c.startNs>=b.act+timing.tRASNs);b.row=null;b.closedAt=c.endNs;}busy=c.endNs;}
  else if(c.kind==='REF'){assert.ok(banks.every(b=>b.row===null));assert.equal(c.endNs-c.startNs,timing.tRFCNs);assert.equal(c.refreshLatenessNs,c.startNs-c.refreshDueNs);assert.ok(c.refreshLatenessNs>=0);busy=c.endNs;}
  else {const b=banks[c.bank];assert.equal(b.row,c.row);assert.ok(c.startNs>=b.act+timing.tRCDNs);busy=c.endNs;}
 }
}
test('signed default connects exact arithmetic to completed host-owned output',()=>{const t=build(defaults);audit(t);assert.deepEqual(t.finalOutput,[[2,5,-1],[5,1,10],[4,1,3]]);assert.deepEqual(t.totals,{durationNs:652,macs:27,requestedReadBytes:216,distinctInputBytes:72,readTransactionBytes:416,writeTransactionBytes:48,sharedRounds:18,refreshes:6,refreshBusyNs:72,computeBusyNs:90});});
test('every bounded geometry and timing combination preserves commands, ownership and output',()=>{for(const globalLayout of ['row-major','column-major'])for(const bankPlacement of ['same-bank','split-banks'])for(const alignmentBytes of [0,12])for(const sharedPadding of [0,1])for(const buffers of [1,2])for(const refreshEveryNs of [0,64,96,160])for(const macNs of [2,8,24])audit(build({...defaults,globalLayout,bankPlacement,alignmentBytes,sharedPadding,buffers,refreshEveryNs,macNs}));});
test('all binary 2×2 operand pairs agree with independent BigInt multiplication',()=>{const m=i=>[[i&1,(i>>1)&1],[(i>>2)&1,(i>>3)&1]];for(let a=0;a<16;a++)for(let b=0;b<16;b++){const t=build({...defaults,a:m(a),b:m(b)});assert.deepEqual(t.finalOutput,oracle(m(a),m(b)));}});
test('extreme signed entries and zero-valued completed results remain exact',()=>{for(const value of [-99,0,99]){const a=Array.from({length:3},()=>Array(3).fill(value));audit(build({...defaults,a,b:a}));}});
test('global layout changes traffic without changing mathematics',()=>{const a=build(defaults),b=build({...defaults,globalLayout:'column-major'});assert.deepEqual(a.finalOutput,b.finalOutput);assert.equal(a.totals.readTransactionBytes,416);assert.equal(b.totals.readTransactionBytes,480);assert.equal(b.totals.durationNs,724);});
test('two staging slots overlap DMA and compute; one slot cannot',()=>{const one=build({...defaults,buffers:1}),two=build(defaults);assert.ok(one.batches.every((b,i)=>i===0||b.submittedNs>=one.batches[i-1].computeEndNs));assert.ok(two.batches.some((b,i)=>i>0&&b.submittedNs<two.batches[i-1].computeEndNs));assert.equal(one.totals.durationNs,722);assert.ok(two.totals.durationNs<one.totals.durationNs);});
test('shared padding can add conflicts while memory still dominates elapsed time',()=>{const a=build(defaults),b=build({...defaults,sharedPadding:1});assert.equal(a.totals.sharedRounds,18);assert.equal(b.totals.sharedRounds,24);assert.equal(b.totals.durationNs,a.totals.durationNs);assert.ok(b.batches.some(b=>b.sharedGroups.some(g=>g.rounds>1)));});
test('same-address reads broadcast rather than becoming bank conflicts',()=>{const t=build(defaults);const g=t.batches[0].sharedGroups.find(g=>g.tensor==='A'&&g.lanes.length===3);assert.equal(g.distinctWords.length,1);assert.equal(g.rounds,1);assert.equal(g.broadcast,true);});
test('refresh occurs at legal boundaries and preserves data',()=>{const t=build({...defaults,refreshEveryNs:64});audit(t);assert.ok(t.commands.some(c=>c.kind==='REF'&&c.refreshLatenessNs>0));const no=build({...defaults,refreshEveryNs:0});assert.equal(no.totals.refreshes,0);assert.deepEqual(t.finalOutput,no.finalOutput);});
test('unsafe consumption and slot reuse are rejected without corrupting safe work',()=>{const good=build(defaults);for(const fault of ['early-consume','reuse-in-flight']){const t=build({...defaults,fault});audit(t);assert.equal(t.status,'complete-with-guard-rejection');const i=t.events.findIndex(e=>e.kind==='guard-rejected');assert.deepEqual(t.events[i].state.partialOutput,t.events[i-1].state.partialOutput);assert.equal(t.events[i].state.buffers[0].phase,'dma');assert.equal(t.events[i].macs.length,0);assert.deepEqual(t.finalOutput,good.finalOutput);assert.deepEqual(t.totals,good.totals);}});
test('missing input mapping blocks before any partially authorized DMA batch',()=>{const t=build({...defaults,fault:'unmapped-b'});audit(t);assert.equal(t.totals.macs,0);assert.equal(t.batches.length,0);assert.equal(t.events.at(-1).kind,'mapping-fault');assert.equal(t.events.at(-1).state.outputOwner,'device');assert.match(t.events.at(-1).label,/denied read/);});
test('range mapping distinguishes device addresses, physical addresses and permissions',()=>{const t=build(defaults);assert.equal(translateMachineAddress(t.mappings,8192,16,'read'),256);for(const args of [[8192,16,'write'],[12288,16,'read'],[8192+40,16,'read'],[4095,16,'read'],[4096,0,'read']])assert.throws(()=>translateMachineAddress(t.mappings,...args));});
test('synthetic byte address fields reconstruct every address in the declared space',()=>{for(let x=0;x<1024;x++){const d=decodeMachineAddress(x);assert.equal(d.row*128+d.bank*64+d.column*16+d.byteInTransaction,x);}for(const x of [-1,1024,NaN,1.5])assert.throws(()=>decodeMachineAddress(x));});
test('state snapshots are independent and a time cursor includes all same-time effects',()=>{const t=build(defaults);assert.equal(machineEventAt(t,0).kind,'command');assert.equal(machineEventAt(t,t.totals.durationNs).kind,'host-sync');const before=t.events[1].state.partialOutput[0][0];t.events[0].state.partialOutput[0][0]=1000;assert.equal(t.events[1].state.partialOutput[0][0],before);for(const x of [-1,Infinity,t.totals.durationNs+1])assert.throws(()=>machineEventAt(t,x));});
test('normalization rejects unknown fields, invalid controls and unsafe matrices',()=>{for(const p of [{buffers:3},{macNs:0},{refreshEveryNs:1},{alignmentBytes:4},{fault:'bad'},{sharedPadding:2},{globalLayout:'vendor'},{a:[[1,2],[3,Infinity]]},{size:2},{extra:true}])assert.throws(()=>normalize({...defaults,...p}));});
test('inputs and model-bound records round-trip without mutation',()=>{const before=JSON.stringify(defaults),t=build(defaults),r=makeMachineRecord(defaults);assert.equal(JSON.stringify(defaults),before);assert.deepEqual(build(JSON.parse(JSON.stringify(t.input))),t);assert.deepEqual(parseMachineRecord(JSON.stringify(r)),r);for(const r of [{schemaVersion:2},{modelVersion:'another'},{extra:true}])assert.throws(()=>parseMachineRecord(JSON.stringify({...makeMachineRecord(defaults),...r})));assert.throws(()=>parseMachineRecord(' '.repeat(65537)));});
const store=()=>{const m=new Map();return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,v),m};};
test('saving preserves incompatible raw input before replacing the active record',()=>{const s=store(),raw='{"modelVersion":"older","operand":-17}';s.setItem(machineRecordKey,raw);saveMachineRecord(s,makeMachineRecord(defaults));assert.equal(exportOlderMachineRecords(s),raw);assert.deepEqual(parseMachineRecord(s.getItem(machineRecordKey)),makeMachineRecord(defaults));});
test('backup failure leaves the incompatible active record intact',()=>{const s=store(),raw='old unreadable text';s.setItem(machineRecordKey,raw);const fail={getItem:s.getItem,setItem:(k,v)=>{if(k===machineRecoveryKey)throw new Error('quota');s.setItem(k,v);}};assert.throws(()=>saveMachineRecord(fail,makeMachineRecord(defaults)),/quota/);assert.equal(s.getItem(machineRecordKey),raw);});
test('multiple older inputs export their exact raw strings',()=>{const s=store();for(const raw of ['old\nfirst','old second']){s.setItem(machineRecordKey,raw);saveMachineRecord(s,makeMachineRecord(defaults));}assert.deepEqual(JSON.parse(exportOlderMachineRecords(s)).records,['old\nfirst','old second']);});
test('unreadable recovery storage is exportable verbatim and blocks destructive save',()=>{const s=store();s.setItem(machineRecoveryKey,'unreadable\nbackup');s.setItem(machineRecordKey,'older-active');const exported=JSON.parse(exportOlderMachineRecords(s));assert.deepEqual(exported.records,['unreadable\nbackup','older-active']);assert.throws(()=>saveMachineRecord(s,makeMachineRecord(defaults)));assert.equal(s.getItem(machineRecordKey),'older-active');});
