import test from 'node:test';
import assert from 'node:assert/strict';
import {architecturePresets} from '../src/lib/architecture-execution.ts';
import {buildMatrixNetwork,matrixNetworkDefaults as defaults,matrixNetworkLimits,normalizeMatrixNetworkInput,matrixNetworkWordBytes,matrixNetworkBytesWord,inspectMatrixNetworkOperand,serializeMatrixNetworkRecord,readMatrixNetworkRecord} from '../src/lib/matrix-network.ts';
const run=(patch={})=>buildMatrixNetwork({...defaults,...patch}),copy=x=>structuredClone(x);
function checkConservation(r){let lastAccepted=0,lastSent=0;for(const s of r.steps){const c=s.counters;assert.equal(s.credits+s.inFlight.length+s.receiver.length+s.creditReturns.length,r.input.credits);assert.ok(s.credits>=0&&s.credits<=r.input.credits);assert.ok(s.receiver.length<=r.input.credits);assert.equal(c.sentFlits,s.inFlight.length+s.receiver.length+c.consumedFlits);assert.equal(c.arrivedFlits,s.receiver.length+c.consumedFlits);assert.equal(c.consumedFlits,c.acceptedFlits+c.rejectedFlits);assert.equal(c.consumedFlits,c.creditsReturned+s.creditReturns.length);assert.equal(c.sentFlits+countersUnsent(s),r.flits.length);assert.equal(c.sentSlotBytes,c.sentFlits*r.input.flitBytes);assert.equal(c.arrivedSlotBytes,c.arrivedFlits*r.input.flitBytes);assert.equal(c.acceptedFlits,s.acceptedSegments.length);assert.equal(c.uniquePayloadBytes,s.destinationBytes.filter(x=>x!==null).length);assert.ok(c.acceptedFlits>=lastAccepted&&c.sentFlits>=lastSent);lastAccepted=c.acceptedFlits;lastSent=c.sentFlits;assert.ok(s.events.filter(e=>e.kind==='send').length<=1);assert.ok(s.events.filter(e=>e.kind==='accept'||e.kind==='reject').length<=1);if(!s.ready){assert.equal(c.macs,0);assert.equal(s.published,false);}if(s.mac){assert.ok(s.tick>r.totals.readyTick);assert.equal(s.mac.product,s.mac.a*s.mac.b);assert.equal(s.mac.after,s.mac.before+s.mac.product);}assert.ok(new Set(s.inFlight.map(f=>f.sequence)).size===s.inFlight.length);}const last=r.steps.at(-1);assert.equal(last.credits,r.input.credits);assert.equal(last.inFlight.length+last.receiver.length+last.creditReturns.length+last.remainingSend.length,0);assert.ok(r.totals.elapsedTicks<matrixNetworkLimits.maxTicks);}
const countersUnsent=s=>s.remainingSend.length;
// Oracle differs from the model's row-wise BigInt reduction and scheduled accumulation.
function columnReference(a,b){const result=Array.from({length:a.length},()=>Array(a.length).fill(0));for(let column=0;column<b.length;column++)for(let k=0;k<b.length;k++)for(let row=0;row<a.length;row++)result[row][column]+=a[row][k]*b[k][column];return result;}

test('the 2x2 source bytes, word identities and consumer dot products agree with hand arithmetic',()=>{for(const tensor of ['A','B']){const r=run({specimen:'two',tensor,flitBytes:4});assert.equal(r.workloadId,'matrix-two-int32-le-1');assert.deepEqual(r.finalOutput,[[1*5+2*7,1*6+2*8],[3*5+4*7,3*6+4*8]]);assert.equal(r.totals.macs,8);assert.equal(r.totals.payloadBytes,16);assert.equal(r.words[0].id,tensor+'[0,0]');assert.deepEqual(r.words[0].bytes,[tensor==='A'?1:5,0,0,0]);assert.deepEqual(r.outputWords[0].bytes,[19,0,0,0]);checkConservation(r);}});
test('signed little-endian conversion is independently checked at negative and sign-boundary values',()=>{assert.deepEqual(matrixNetworkWordBytes(-2),[254,255,255,255]);assert.deepEqual(matrixNetworkWordBytes(-2147483648),[0,0,0,128]);assert.equal(matrixNetworkBytesWord([255,255,255,255]),-1);assert.equal(matrixNetworkBytesWord([120,86,52,18]),0x12345678);for(const v of [NaN,Infinity,.5,2147483648,-2147483649])assert.throws(()=>matrixNetworkWordBytes(v));for(const bytes of [[0,0,0],new Array(4),[0,0,0,256],[0,0,0,-1]])assert.throws(()=>matrixNetworkBytesWord(bytes));});
test('independent column accumulation agrees for each specimen, tensor, flit width, credit count and delay boundary',()=>{for(const specimen of ['two','three'])for(const tensor of ['A','B'])for(const flitBytes of [4,8,16])for(const credits of [1,2,3,4])for(const linkTicks of [1,8]){const r=run({specimen,tensor,flitBytes,credits,linkTicks,creditTicks:8});assert.deepEqual(r.finalOutput,columnReference(r.a,r.b));assert.deepEqual(r.consumerA,r.a);assert.deepEqual(r.consumerB,r.b);assert.equal(r.correct,true);checkConservation(r);}});
test('single-credit timing has an independent stop-and-return recurrence',()=>{const r=run({specimen:'two',flitBytes:4,credits:1,linkTicks:2,creditTicks:3}),sends=r.steps.flatMap(s=>s.events.filter(e=>e.kind==='send').map(()=>s.tick));assert.deepEqual(sends,[0,5,10,15]);assert.equal(r.totals.readyTick,3*(2+3)+2);assert.equal(r.totals.drainedTick,17+3);assert.equal(r.totals.publishedTick,17+8);checkConservation(r);});
test('enough credits pipeline one flit per tick without equating injection width and latency',()=>{const r=run({specimen:'two',flitBytes:4,credits:4,linkTicks:3,creditTicks:2});assert.deepEqual(r.steps.flatMap(s=>s.events.filter(e=>e.kind==='send').map(()=>s.tick)),[0,1,2,3]);assert.equal(r.totals.readyTick,3+3);assert.equal(r.totals.publishedTick,6+8);assert.equal(r.totals.backpressureTicks,0);checkConservation(r);});
test('receiver pause retains finite slots and return latency blocks send until the credit arrives',()=>{const r=run({specimen:'two',flitBytes:4,credits:1,linkTicks:2,creditTicks:2,receiverPauseTicks:8});assert.equal(r.steps[7].receiver.length,1);assert.equal(r.steps[7].credits,0);assert.equal(r.steps[8].receiver.length,0);assert.deepEqual(r.steps[8].creditReturns,[{sequence:0,dueTick:10}]);assert.equal(r.steps[9].counters.sentFlits,1);assert.equal(r.steps[10].counters.sentFlits,2);assert.equal(r.totals.readyTick,20);assert.equal(r.totals.pausedTicks,6);assert.deepEqual(r.finalOutput,[[19,22],[43,50]]);checkConservation(r);});
test('receiver interval is evaluated on declared absolute eligible ticks',()=>{const r=run({specimen:'two',flitBytes:4,credits:1,linkTicks:2,creditTicks:1,consumeEveryTicks:4});assert.deepEqual(r.steps.flatMap(s=>s.events.filter(e=>e.kind==='accept').map(()=>s.tick)),[4,8,12,16]);assert.equal(r.totals.readyTick,16);checkConservation(r);});
test('partial last slot padding never creates extra destination bytes or trainable operands',()=>{const r=run({flitBytes:16});assert.equal(r.totals.payloadBytes,36);assert.equal(r.totals.expectedSegments,3);assert.equal(r.totals.paddedSlotBytes,48);assert.equal(r.totals.sentSlotBytes,48);assert.equal(r.flits[2].validBytes,4);assert.deepEqual(r.flits[2].bytes.slice(4),Array(12).fill(0));assert.equal(r.steps.at(-1).destinationBytes.length,36);assert.equal(r.totals.uniquePayloadBytes,36);checkConservation(r);});
test('each omitted segment leaves the exact destination hole, no MAC and all credits recovered',()=>{for(const specimen of ['two','three'])for(const flitBytes of [4,8,16]){const count=Math.ceil((specimen==='two'?16:36)/flitBytes);for(let faultSegment=0;faultSegment<count;faultSegment++){const r=run({specimen,flitBytes,faultSegment,fault:'omit'}),s=r.segments[faultSegment];assert.equal(r.status,'incomplete');assert.equal(r.finalOutput,null);assert.equal(r.totals.macs,0);assert.equal(r.totals.sentFlits,count-1);assert.equal(r.steps.at(-1).destinationBytes.filter(x=>x===null).length,s.validBytes);assert.equal(r.totals.sentPayloadBytes,r.totals.payloadBytes-s.validBytes);checkConservation(r);}}});
test('wrong transfer and tensor identity is rejected without copying any of that segment',()=>{const r=run({fault:'wrong-identity',faultSegment:2}),s=r.segments[2];assert.equal(r.totals.rejectedFlits,1);assert.equal(r.status,'incomplete');assert.ok(r.steps.at(-1).destinationBytes.slice(s.offset,s.offset+s.validBytes).every(x=>x===null));assert.equal(r.totals.sentPayloadBytes,36);assert.equal(r.totals.uniquePayloadBytes,28);assert.equal(r.totals.macs,0);checkConservation(r);});
test('duplicate delivery costs another slot but writes each identified destination byte only once',()=>{for(const faultSegment of [0,4]){const r=run({fault:'duplicate',faultSegment}),s=r.segments[faultSegment];assert.equal(r.totals.sentFlits,6);assert.equal(r.totals.acceptedFlits,5);assert.equal(r.totals.rejectedFlits,1);assert.equal(r.totals.sentPayloadBytes,36+s.validBytes);assert.equal(r.totals.sentSlotBytes,48);assert.equal(r.totals.uniquePayloadBytes,36);assert.deepEqual(r.finalOutput,run().finalOutput);checkConservation(r);}});
test('actual consumer completeness gate refuses every incomplete prefix including legitimate zero bytes',()=>{const r=run({specimen:'two'});for(let length=0;length<16;length++){const bytes=[...r.sourceBytes.slice(0,length),...Array(16-length).fill(null)],x=inspectMatrixNetworkOperand(bytes,2);assert.equal(x.ready,false);assert.equal(x.matrix,null);assert.equal(x.missingByteOffsets.length,16-length);}const ready=inspectMatrixNetworkOperand(r.sourceBytes,2);assert.equal(ready.ready,true);assert.deepEqual(ready.matrix,r.b);assert.throws(()=>inspectMatrixNetworkOperand(new Array(16),2));assert.throws(()=>inspectMatrixNetworkOperand(Array(16).fill(256),2));assert.throws(()=>inspectMatrixNetworkOperand(Array(36).fill(0),2));});
test('premature fixture invokes the same byte gate and computes only after identified assembly',()=>{const r=run({fault:'premature-consume'});assert.equal(r.steps[0].counters.prematureAttempts,1);assert.ok(r.steps[0].events.some(e=>e.kind==='consumer-blocked'));assert.equal(r.steps[0].counters.macs,0);assert.equal(r.steps[0].ready,false);assert.deepEqual(r.finalOutput,run().finalOutput);assert.equal(r.totals.publishedTick,run().totals.publishedTick);checkConservation(r);});
test('valid identity with altered payload feeds wrong real operands rather than the reference matrix',()=>{const r=run({specimen:'two',fault:'wrong-payload',faultSegment:0});assert.equal(r.consumerB[0][0],4);assert.deepEqual(r.finalOutput,[[1*4+2*7,22],[3*4+4*7,50]]);assert.deepEqual(r.reference,[[19,22],[43,50]]);assert.equal(r.status,'output-mismatch');assert.equal(r.totals.rejectedFlits,0);assert.ok(r.steps.some(s=>s.mac?.bId==='B[0,0]'&&s.mac.b===4));checkConservation(r);});
test('consumer start is tied to destination readiness, while trailing credits can drain concurrently',()=>{const r=run({specimen:'two',flitBytes:16,credits:1,linkTicks:1,creditTicks:8});assert.equal(r.totals.readyTick,1);assert.equal(r.steps[1].counters.macs,0);assert.equal(r.steps[2].counters.macs,1);assert.equal(r.totals.drainedTick,9);assert.equal(r.totals.publishedTick,9);checkConservation(r);});
test('all failure modes remain bounded at slow-link, slow-service, long-pause and flit-count extremes',()=>{for(const fault of ['none','omit','wrong-identity','duplicate','premature-consume','wrong-payload'])for(const credits of [1,4])for(const faultSegment of [0,8]){const r=run({flitBytes:4,credits,linkTicks:8,creditTicks:8,receiverPauseTicks:24,consumeEveryTicks:4,fault,faultSegment});assert.ok(r.steps.length<260);checkConservation(r);}});
test('record import is strict, bounded and recomputes source identity rather than trusting supplied outputs',()=>{const input={...defaults,flitBytes:16,faultSegment:2,fault:'duplicate'},raw=serializeMatrixNetworkRecord(input);assert.deepEqual(readMatrixNetworkRecord(raw),input);assert.deepEqual(buildMatrixNetwork(readMatrixNetworkRecord(raw)),run(input));for(const patch of [{schemaVersion:2},{modelVersion:'old'},{sourceVersion:'other'},{result:[[1]]},{input:{...input,credits:99999999}}])assert.throws(()=>readMatrixNetworkRecord(JSON.stringify({...JSON.parse(raw),...patch})));assert.throws(()=>readMatrixNetworkRecord(' '.repeat(20001)));assert.throws(()=>readMatrixNetworkRecord('🌍'.repeat(5001)));assert.throws(()=>readMatrixNetworkRecord('{}'));});
test('invalid choices and cross-field fault indices cannot trigger giant or ambiguous simulations',()=>{for(const patch of [{specimen:'four'},{tensor:'C'},{credits:0},{credits:5},{flitBytes:3},{flitBytes:16,faultSegment:3},{faultSegment:-1},{linkTicks:0},{creditTicks:9},{receiverPauseTicks:25},{consumeEveryTicks:0},{consumeEveryTicks:1.5},{fault:'random'},{linkTicks:Infinity},{extra:1}])assert.throws(()=>normalizeMatrixNetworkInput({...defaults,...patch}));});
test('mutation of a returned snapshot cannot change other snapshots, presets or replay',()=>{const saved=copy(architecturePresets),r=run(),expected=run();r.steps[0].destinationBytes[0]=255;r.steps[0].partialOutput[0][0]=99;r.words[0].bytes[0]=255;r.flits[0].bytes[0]=255;r.finalOutput[0][0]=99;assert.equal(r.steps[1].destinationBytes[0],null);assert.equal(r.steps[1].partialOutput[0][0],0);assert.deepEqual(architecturePresets,saved);assert.deepEqual(run(),expected);});
