import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {loadAuthoredAtlas} from './atlas-authoring.mjs';
const read=n=>JSON.parse(readFileSync(new URL('../src/lib/data/'+n,import.meta.url),'utf8'));
const pack=read('model-lifecycle-learning.json'),enrich=read('model-lifecycle-enrichments.json').entries,eqs=read('equations-model-lifecycle-learning.json');
const candidates=JSON.parse(readFileSync(new URL('../docs/model-lifecycle/curriculum/approved-candidates.json',import.meta.url),'utf8')).entries;
const atlas=await loadAuthoredAtlas(), byId=new Map([...atlas.records,...pack.lessons].map(x=>[x.id,x]));
const katex=createRequire(import.meta.url)('katex'),settings={displayMode:true,throwOnError:true,strict:'error',trust:false,maxExpand:300,maxSize:15};
const close=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
const numeric=id=>byId.get(id)?.engineeringExample||enrich[id].appendEngineeringExample;
function nodes(o){if(!o||typeof o!=='object')return[];return[o,...Object.entries(o).filter(([k])=>!['loc','token'].includes(k)).flatMap(([,v])=>Array.isArray(v)?v.flatMap(nodes):nodes(v))];}
test('all approved 37 new and 15 deepened IDs have exactly one disposition and canonical addition',()=>{
 assert.deepEqual(pack.lessons.map(x=>x.id).sort(),candidates.filter(x=>x.action==='new').map(x=>x.id).sort());
 assert.deepEqual(Object.keys(enrich).sort(),candidates.filter(x=>x.action==='deepen').map(x=>x.id).sort());
 assert.deepEqual(Object.keys(eqs).sort(),candidates.map(x=>x.id).sort());assert.equal(new Set(pack.lessons.map(x=>x.id)).size,37);
});
test('new records are substantive and all checks have a declared valid answer',()=>{
 for(const l of pack.lessons){for(const k of ['name','shortName','role','description','tradeoff','whyAI','scale','kind','misconception','learningObjective','engineeringExample','evidenceNotes'])assert.ok(typeof l[k]==='string'&&l[k].length>0,`${l.id}.${k}`);
 assert.ok(l.description.split(/\s+/).length>=65,l.id);assert.ok(l.engineeringExample.split(/\s+/).length>=30,l.id);assert.ok(l.mechanism.length>=3);assert.ok(l.sources.length&&l.science.length&&l.interfaces.length&&l.specs.length);for(const k of ['related','prerequisites','history'])assert.ok(Array.isArray(l[k]));assert.ok(l.check.answer>=0&&l.check.answer<l.check.options.length);assert.ok(l.check.explanation.length>30);
 }
 for(const [id,e]of Object.entries(enrich)){assert.deepEqual(Object.keys(e).sort(),['appendDescription','appendMechanism','appendEngineeringExample','appendEvidenceNotes','additionalChecks','additionalRelated','additionalSources','additionalScience'].sort());assert.ok(e.additionalScience.length===eqs[id].length);assert.ok(e.appendDescription.length>200);}
});
test('eight chapters have stable domains and exact nonoverlapping new-lesson ownership',()=>{assert.equal(pack.chapters.length,8);const ids=pack.chapters.flatMap(c=>{assert.equal(c.domainId,'learning-intelligence');assert.equal(c.band,5);return c.ids;});assert.deepEqual(ids.sort(),pack.lessons.map(l=>l.id).sort());});
test('combined authored prerequisites are valid, non-self, duplicate-free and acyclic',()=>{
 for(const r of byId.values())for(const id of r.prerequisites||[]){assert.ok(byId.has(id),r.id+' requires '+id);assert.notEqual(r.id,id);assert.equal(new Set(r.prerequisites).size,r.prerequisites.length);}
 const grey=new Set(),black=new Set();function visit(id,path=[]){assert.ok(!grey.has(id),'cycle '+path.concat(id).join(' → '));if(black.has(id))return;grey.add(id);for(const p of byId.get(id).prerequisites||[])visit(p,path.concat(id));grey.delete(id);black.add(id);}for(const id of byId.keys())visit(id);
 for(const r of pack.lessons)for(const id of r.related)assert.ok(byId.has(id));for(const e of Object.values(enrich))for(const id of e.additionalRelated)assert.ok(byId.has(id));
});
test('all equations strictly render with notation and no original entries are copied into additions',()=>{for(const [id,es]of Object.entries(eqs)){assert.equal(es.length,1);const e=es[0];assert.equal(e.kind,'math');assert.ok(e.variables.length);assert.equal(new Set(e.variables.map(v=>v.symbol)).size,e.variables.length);for(const v of e.variables)for(const k of ['symbol','meaning','unit'])assert.ok(v[k]);assert.ok(katex.renderToString(e.latex,settings).includes('<math'));assert.ok(e.text.length>20,id);}});
test('source claims reference existing lessons and checked primary locators without invented human review',()=>{
 const sources=new Map(pack.sources.map(s=>[s.id,s]));for(const c of pack.claims){assert.ok(sources.has(c.sourceId));assert.ok(c.limitations&&c.scope);for(const id of c.lessonIds)assert.ok(byId.has(id));}
 const manifest=JSON.parse(readFileSync(new URL('../docs/model-lifecycle/curriculum/source-review-manifest.json',import.meta.url),'utf8'));assert.equal(manifest.reviewDispositions.length,52);for(const s of manifest.sources){assert.ok(s.locator&&s.actor==='/root/curriculum_assessment');assert.equal(s.humanSpecialistReview,null);assert.equal(s.checkedOn,'2026-09-07');assert.ok(s.lessonIds.length&&s.claimIds.length);}
 for(const l of pack.lessons)for(const s of l.sources)assert.ok([...sources.values()].some(x=>x.url===s.url));
});
test('learners see scope, not leaked authoring or implementation directions',()=>{for(const l of pack.lessons){assert.doesNotMatch(l.description,/in the exploded view|show functional regions|render this|TODO|insert a diagram|storyboard/i);assert.ok(l.specs[0].value);assert.ok(l.evidenceNotes.includes('Mode:'));}for(const id of ['low-rank-adaptation','image-text-contrastive-learning','denoising-generative-objectives','action-conditioned-world-model'])assert.equal(byId.get(id).specs[0].value,'worked example');assert.match(byId.get('policy-gradient-kl-control').evidenceNotes,/not PPO or GRPO/);});
test('deduplication and mixture examples retain different item and exposure denominators',()=>{const a=new Set(['red','square','left']),b=new Set(['red','square','right']);close([...a].filter(x=>b.has(x)).length/new Set([...a,...b]).size,.5);close(1-9/12,.25);close(240*.75/100,1.8);close(240*.25/20,3);close(Math.sqrt(240*.75*.25),6.7082039325,1e-8);assert.ok((240*.25/20)>(240*.75/100));});
test('packing and unequal microbatch examples demonstrate noncommuting normalization and clipping',()=>{close((1+3+5)/7,9/7);assert.notEqual((2+1)/2,9/7);const correct=(2*3+5*-1)/7,localClip=(2*1+5*-1)/7;assert.ok(correct>0&&localClip<0);close(2-.7*correct,1.9);});
test('synthetic selection, byte encoding and slice retention calculations use explicit inventories',()=>{const answers=[4,5,4,6],selected=answers.filter(x=>x%2===0);close(selected.length/answers.length,.75);close(selected.filter(x=>x===4).length/selected.length,2/3);const unique=[...new Set(selected)];close(unique.filter(x=>x===4).length/unique.length,.5);assert.equal(Buffer.byteLength('cat'),3);assert.equal(Buffer.byteLength('猫'),3);close(84/110,.763636363636);close(4/10,.4);});
test('branched reverse derivatives, parameter count and causal NLL have independent arithmetic',()=>{const f=w=>(w*3+w)**2/2,h=1e-4;close((f(2+h)-f(2-h))/(2*h),32,1e-7);assert.equal(9*6+4*6*6+(6*12+12+12*6+6)+(6*9+9),423);close(-[.5,.25,.5].reduce((s,p)=>s+Math.log(p),0)/3,Math.log(16)/3);close(Math.exp(Math.log(16)/3),2.5198420997897464);});
test('clipping and AdamW example preserve global direction and separate decay',()=>{const g=[3,4],norm=Math.hypot(...g),clipped=g.map(x=>x/norm);assert.deepEqual(clipped,[.6,.8]);assert.deepEqual(clipped.map(x=>2-.1*x),[1.94,1.92]);close(2-.1-.1*.01*2,1.898);});
test('continuation and replay examples prove a conflict rather than general catastrophic forgetting',()=>{close(-Math.log(.8)+Math.log(.1),-2.0794415416798357);const q=.25,L=p=>-q*Math.log(p)-(1-q)*Math.log(1-p);assert.ok(L(q)<L(.1)&&L(q)<L(.8));close(-Math.log(q),1.3862943611198906);assert.ok(q<.5);});
test('KV payload scales linearly while an incompatible average can erase equivalent functions',()=>{const b=t=>2*2*t*2*4*2;assert.equal(b(128),8192);assert.equal(b(512),32768);const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);close(dot([1,-1],[.5,-.5]),1);close(dot([-1,1],[-.5,.5]),1);close(dot([0,0],[0,0]),0);});
test('SFT and pairwise losses preserve different denominators and score invariance',()=>{close((2+3+1+2+.4+.6)/6,1.5);close((.4+.6)/2,.5);const sig=x=>1/(1+Math.exp(-x)),d=Math.log(3);close(sig(d),.75);close(sig(5+d-5),.75);close(sig(d)-1,-.25);const dpo=-Math.log(sig(Math.log(.6/.5)-Math.log(.4/.5)));close(dpo,.5108256237659907);});
test('PPO advantage sign, reference KL and zero-variance group behavior are distinct',()=>{const clip=x=>Math.max(.8,Math.min(1.2,x)),term=a=>Math.min(1.4*a,clip(1.4)*a);close(term(2),2.4);close(term(-2),-2.8);close(.7*Math.log(.7/.5)+.3*Math.log(.3/.5),.08228287850505184);const group=rs=>{const m=rs.reduce((a,b)=>a+b)/rs.length,s=Math.sqrt(rs.reduce((a,b)=>a+(b-m)**2,0)/rs.length);return rs.map(r=>s?(r-m)/s:0);};assert.deepEqual(group([1,1,0,0]),[1,1,-1,-1]);assert.deepEqual(group([0,0,0,0]),[0,0,0,0]);});
test('proxy failure, low-rank product and teacher gradient counterexamples remain explicit',()=>{assert.ok(.1<.5&&3/4>2/4);const B=[1,2,0,-1],A=[1,0,2,0,0,-1],out=B.map(x=>x*A[2]);assert.deepEqual(out,[2,4,0,-2]);assert.equal(B.length+A.length,10);assert.deepEqual([.5-.75,.5-.25],[-.25,.25]);});
test('calibration coverage and judge agreement do not imply correctness',()=>{const ps=[.8,.6,.4,.2],ys=[1,0,1,0];close(ps.reduce((s,p,i)=>s+(p-ys[i])**2,0)/4,.2);const answer=ps.map((p,i)=>({c:Math.max(p,1-p),ok:Number(p>=.5)===ys[i]})).filter(r=>r.c>=.75);assert.equal(answer.length,2);assert.ok(answer.every(x=>x.ok));assert.equal(ps.filter(p=>Math.max(p,1-p)>=.9).length,0);const a=[1,1,1,0],b=[1,0,1,0],y=[1,1,0,0];close(a.filter((x,i)=>x===b[i]).length/4,.75);close(b.filter((x,i)=>x===y[i]).length/4,.5);});
test('retrieval mixture, candidate-set success and regression gates cannot substitute for one another',()=>{close(.7*.8+.3*.2,.62);close(1-.75**4,.68359375);const candidates=[false,true,false,false];assert.ok(candidates.some(Boolean));assert.equal(candidates[0],false);const accept=(accuracy,protectedFails)=>accuracy>=.9&&protectedFails===0;assert.equal(accept(19/20,1),false);});
test('contrastive normalization, visual projection, audio frames and WER reproduce authored values',()=>{close(-Math.log(Math.E/(Math.E+1)),.3132616875182228);const z=[[1,2],[3,4]],w=[[1,0,1],[0,1,-1]],project=z.map(row=>w[0].map((_,j)=>row.reduce((s,x,k)=>s+x*w[k][j],0)));assert.deepEqual(project,[[1,2,-1],[3,4,-1]]);assert.equal(1+Math.floor((16000-400)/160),98);close((1+0+1)/3,2/3);});
test('diffusion, flow, representation error and target EMA have different targets',()=>{close(Math.sqrt(.64)*2+Math.sqrt(.36)*-1,1);close((-1-(-.5))**2,.25);close(.75*-1+.25*2,-.25);close(2-(-1),3);close((Math.abs(2-1.5)+Math.abs(4-3))/2,.75);close(.9*2+.1*3,2.1);});
test('action-dependent rollout, imagined return and quantization retain physical boundaries',()=>{const step=(x,a,g)=>x+g*a;close(step(1,.5,2),2);close(step(1,-.5,2),0);let real=1,model=1;for(let i=0;i<5;i++){real=step(real,.5,2);model=step(model,.5,1.8);}close(real,6);close(model,5.5);close(1+.9*2,2.8);close(5-(-1),6);const width=(1-(-1))/4,bin=Math.floor((.3+1)/width),decoded=-1+(bin+.5)*width;assert.equal(bin,2);close(decoded,.25);close(decoded-.3,-.05);assert.ok(2>1);});
test('replanning example uses executed prefix and explicit timing assumptions',()=>{let x=0;x+=1;x+=1;assert.equal(x,2);assert.equal(x+1+1,4);assert.equal(x+1+1+1,5);close(2/10,.2);close(.05/.2,.25);});
test('existing-lesson additions preserve independent shared-gradient, softmax and routing arithmetic',()=>{assert.deepEqual([1+3,2-1],[4,1]);assert.deepEqual([4-2,1+1],[2,2]);const p=[.25,.75],v=[2,6],o=p.reduce((s,x,i)=>s+x*v[i],0);close(o,5);assert.deepEqual(p.map((x,i)=>x*(v[i]-o)),[-.75,.75]);close((1-.99**2)*2,.0398);assert.equal(6*12+12+12*6+6,162);close(Math.sqrt((9+16)/2),Math.sqrt(12.5));close(.01*3*(.25+1/9+1/36),.011666666666666667);});
test('Adam, payload, bounded scaling and Wilson equations have independently checked values',()=>{const g=.5,m=.1*g,v=.001*g*g,update=2-.1*(m/(1-.9))/(Math.sqrt(v/(1-.999))+1e-8);close(update,1.900000002,1e-9);assert.equal(423*8*3,10152);assert.equal(423*8*4,13536);close(1+4/Math.sqrt(16)+2/Math.sqrt(16),2.5);close(1+4/Math.sqrt(32)+2/Math.sqrt(32),2.0606601717798214);const n=4,p=1,z=1.96,c=(p+z*z/(2*n))/(1+z*z/n),w=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/(1+z*z/n);close(c-w,.5100999795960008);close(c+w,1);});
test('critical semantic grouping retains the entire RMS mean-square root and Adam epsilon outside its root',()=>{const rms=nodes(katex.__parse(eqs['residual-normalization'][0].latex,settings));const root=rms.find(n=>n.type==='sqrt');assert.ok(nodes(root).some(n=>n.text==='\\epsilon'));const adam=nodes(katex.__parse(eqs['loss-optimizer'][0].latex,settings));for(const r of adam.filter(n=>n.type==='sqrt'))assert.ok(!nodes(r).some(n=>n.text==='\\epsilon'));const wilson=nodes(katex.__parse(eqs.evaluation[0].latex,settings)).find(n=>n.type==='sqrt');assert.ok(nodes(wilson).filter(n=>n.type==='genfrac').length>=2);});
