import {createLifecycleExposureJournal,lifecycleWorkspaceKeys} from '../src/lib/model-lifecycle-workspace.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {createLifecycleRun,advanceLifecycleRun,lifecycleSupervisedObjective,lifecycleExamples,lifecycleTensors,inspectLifecycleForward,serializeLifecycleCheckpoint} from '../src/lib/model-lifecycle.ts';
import * as d from '../src/lib/model-lifecycle-distributed.ts';
const maxDiff=(a,b)=>a.reduce((m,x,i)=>Math.max(m,Math.abs(x-b[i])),0),near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`),copy=x=>structuredClone(x);
const setup=config=>d.beginDistributedRound(d.createDistributedTrainingRun(createLifecycleRun(),config));
const submitAll=run=>{for(let i=0;i<run.round.ranks.length;i++)if(run.round.ranks[i].status==='ready')run=d.submitRankContribution(run,d.computeRankContribution(run,i));return run;};
const finish=run=>d.commitDistributedRound(submitAll(run));
const ex=id=>lifecycleExamples('train','copy').concat(lifecycleExamples('train','swap')).find(e=>e.id===id);
// Independent ordinary-number objective uses forward probabilities, not reverse derivatives or rank reducers.
function referenceLoss(weights,round){const losses=round.examples.map(id=>{const e=ex(id),f=inspectLifecycleForward(weights,e.tokens.slice(0,-1));let sum=0,count=0;for(let i=0;i<e.tokens.length-1;i++){if(round.config.objective==='response-only'&&!e.mask[i])continue;sum-=f.logProbabilities[i][e.tokens[i+1]];count++;}return{sum,count};});return round.config.weighting==='sample'?losses.reduce((s,x)=>s+x.sum/x.count,0)/losses.length:losses.reduce((s,x)=>s+x.sum,0)/losses.reduce((s,x)=>s+x.count,0);}
function independentUpdate(before,gradient,config){let norm=0;for(const g of gradient)norm+=g*g;norm=Math.sqrt(norm);const scale=Math.min(1,config.clipNorm/Math.max(norm,1e-30)),step=before.optimizerStep+1,moments=[],squares=[],weights=[];for(let i=0;i<gradient.length;i++){const g=gradient[i]*scale,m=.9*before.moments[i]+.1*g,v=.999*before.squares[i]+.001*g*g;moments.push(m);squares.push(v);weights.push(before.weights[i]-config.learningRate*(config.optimizer==='sgd'?g:(m/(1-.9**step))/(Math.sqrt(v/(1-.999**step))+1e-8)));}return{weights,moments,squares,optimizerStep:step};}
test('source model, moments and RNG are retained without mutating the lifecycle checkpoint',()=>{const base=advanceLifecycleRun(createLifecycleRun({seed:9}),17),saved=serializeLifecycleCheckpoint(base),run=d.createDistributedTrainingRun(base);assert.deepEqual(run.state.weights,base.weights);assert.deepEqual(run.state.moments,base.moments);assert.equal(run.rng,base.rng);assert.equal(run.state.optimizerStep,17);assert.equal(serializeLifecycleCheckpoint(base),saved);});
test('default uneven ranks own one short and three long actual examples with 6 and 24 targets',()=>{const run=setup(),cs=run.round.ranks.map((_,i)=>d.computeRankContribution(run,i));assert.deepEqual(cs.map(c=>c.samples),[1,3]);assert.deepEqual(cs.map(c=>c.tokens),[6,24]);assert.deepEqual(cs.map(c=>c.denominator),[6,24]);assert.equal(run.dataDraws,4);assert.ok(cs.every(c=>c.tapeNodes>423));assert.ok(cs.some(c=>c.gradientSum.some(v=>v!==0)));});
for(const weighting of ['token','sample'])for(const objective of ['next-token','response-only'])test(`${weighting} ${objective}: every partition agrees with centralized objective and retained optimizer`,()=>{let reference;for(const partition of ['1+3','2+2','3+1','1+1+2']){const r=setup({weighting,objective,partition}),central=d.centralizedDistributedReference(r),done=finish(r),actual=done.lastCommit;near(actual.loss,referenceLoss(r.state.weights,r.round));assert.ok(maxDiff(actual.gradient,central.gradient)<1e-10);const expected=independentUpdate(r.state,central.gradient,r.sourceCheckpoint.config);assert.ok(maxDiff(expected.weights,done.state.weights)<1e-10);assert.ok(maxDiff(expected.moments,done.state.moments)<1e-10);if(reference)assert.ok(maxDiff(reference,done.state.weights)<1e-10);reference=done.state.weights;assert.equal(done.state.optimizerStep,1);assert.equal(done.commits,1);}});
test('actual weighted gradients pass independent finite differences across every tensor group',()=>{for(const weighting of ['token','sample']){const run=submitAll(setup({weighting})),gradient=d.inspectDistributedReduction(run).gradient;for(const tensor of lifecycleTensors){const index=tensor.offset+Math.floor(tensor.size/2),a=[...run.state.weights],b=[...a],h=1e-5;a[index]+=h;b[index]-=h;const fd=(referenceLoss(a,run.round)-referenceLoss(b,run.round))/(2*h);near(gradient[index],fd,2e-5);}}});
test('equal rank means are numerically wrong for the default token and sample objectives',()=>{for(const weighting of ['token','sample']){const r=submitAll(setup({weighting})),reduced=d.inspectDistributedReduction(r);assert.ok(reduced.naiveMaxGradientError>.001);assert.ok(maxDiff(reduced.gradient,d.centralizedDistributedReference(r).gradient)<1e-10);}});
test('token and sample objectives differ for unequal target lengths but response-only denominators coincide',()=>{const tok=d.centralizedDistributedReference(setup({weighting:'token'})),sample=d.centralizedDistributedReference(setup({weighting:'sample'}));assert.ok(maxDiff(tok.gradient,sample.gradient)>.001);const a=d.centralizedDistributedReference(setup({objective:'response-only',weighting:'token'})),b=d.centralizedDistributedReference(setup({objective:'response-only',weighting:'sample'}));assert.ok(maxDiff(a.gradient,b.gradient)<1e-12);});
test('missing contribution blocks optimizer commit and preserves all current model state',()=>{const run=setup(),saved=JSON.stringify(run),one=d.submitRankContribution(run,d.computeRankContribution(run,0));assert.throws(()=>d.commitDistributedRound(one),/barrier/);assert.deepEqual(one.state,run.state);assert.equal(one.commits,0);assert.equal(JSON.stringify(run),saved);});
test('failure after submission invalidates the uncommitted contribution and an old attempt is rejected',()=>{let run=setup();const stale=d.computeRankContribution(run,1);run=d.submitRankContribution(run,stale);const reserved=copy(run.round.examples),rng=run.rng,base=copy(run.state);run=d.failDistributedRank(run,1);assert.equal(run.round.ranks[1].contribution,null);assert.throws(()=>d.commitDistributedRound(run));run=d.restartDistributedRank(run,1);assert.throws(()=>d.submitRankContribution(run,stale),/attempt/);assert.deepEqual(run.round.examples,reserved);assert.equal(run.rng,rng);assert.deepEqual(run.state,base);assert.equal(run.round.ranks[1].attempt,2);});
test('failed restarted rank yields the same committed weights and moments as failure-free centralized work',()=>{const original=setup(),expected=finish(original);let failed=d.submitRankContribution(original,d.computeRankContribution(original,0));failed=d.failDistributedRank(failed,1);failed=d.restartDistributedRank(failed,1);failed=finish(failed);assert.deepEqual(failed.state,expected.state);assert.equal(failed.rng,expected.rng);assert.equal(failed.dataDraws,expected.dataDraws);assert.deepEqual(failed.lastCommit,expected.lastCommit);});
test('duplicate submissions, old rounds and second optimizer commits are rejected',()=>{let run=setup();const c=d.computeRankContribution(run,0);run=d.submitRankContribution(run,c);assert.throws(()=>d.submitRankContribution(run,c),/already submitted/);run=finish(run);assert.throws(()=>d.commitDistributedRound(run),/No collecting/);run=d.beginDistributedRound(run);assert.throws(()=>d.submitRankContribution(run,c),/Stale/);});
test('global clipping and nonzero Adam history agree with an independent update',()=>{const base=advanceLifecycleRun(createLifecycleRun({clipNorm:.05,seed:11}),23),r=d.beginDistributedRound(d.createDistributedTrainingRun(base)),central=d.centralizedDistributedReference(r),expected=independentUpdate(r.state,central.gradient,base.config),done=finish(r);assert.ok(done.lastCommit.clipScale<1);assert.equal(done.state.optimizerStep,24);assert.ok(maxDiff(done.state.weights,expected.weights)<1e-11);assert.ok(maxDiff(done.state.squares,expected.squares)<1e-11);});
test('SGD uses the same reduced gradient and retained moments with a single step',()=>{const base=createLifecycleRun({optimizer:'sgd',learningRate:.1}),r=d.beginDistributedRound(d.createDistributedTrainingRun(base)),c=d.centralizedDistributedReference(r),expected=independentUpdate(r.state,c.gradient,base.config),done=finish(r);assert.ok(maxDiff(done.state.weights,expected.weights)<1e-12);assert.ok(maxDiff(done.state.moments,expected.moments)<1e-12);assert.ok(maxDiff(done.state.squares,expected.squares)<1e-12);assert.equal(done.state.optimizerStep,expected.optimizerStep);});
test('partial round checkpoint resumes exact attempts, batch and RNG without extra draws',()=>{let run=setup();run=d.submitRankContribution(run,d.computeRankContribution(run,0));run=d.failDistributedRank(run,1);const serialized=d.serializeDistributedTrainingRun(run),restored=d.readDistributedTrainingRun(serialized);assert.deepEqual(restored,run);const a=finish(d.restartDistributedRank(run,1)),b=finish(d.restartDistributedRank(restored,1));assert.deepEqual(a,b);});
test('multiple committed rounds resume deterministically from the distributed record',()=>{let run=d.createDistributedTrainingRun();for(let i=0;i<3;i++)run=finish(d.beginDistributedRound(run));let restored=d.readDistributedTrainingRun(d.serializeDistributedTrainingRun(run));for(let i=0;i<3;i++){run=finish(d.beginDistributedRound(run));restored=finish(d.beginDistributedRound(restored));}assert.deepEqual(restored,run);assert.equal(run.dataDraws,24);});
test('tampered numerator, target denominator, source examples and unknown fields are rejected before mutation',()=>{const run=setup(),original=JSON.stringify(run),c=d.computeRankContribution(run,0);for(const mutate of [x=>x.gradientSum[4]+=.01,x=>x.lossSum+=.01,x=>x.denominator++,x=>x.exampleIds[0]='final-copy-a-uvu',x=>x.unknown=true,x=>x.tapeNodes++]){const bad=copy(c);mutate(bad);assert.throws(()=>d.submitRankContribution(run,bad));assert.equal(JSON.stringify(run),original);}});
test('malicious giant records and invalid cross-field state fail bounded validation',()=>{const run=setup();for(const mutate of [r=>r.state.weights.push(0),r=>r.round.ranks.push(...Array(100).fill(r.round.ranks[0])),r=>r.round.events=Array(101).fill(r.round.events[0]),r=>r.config.extra=1,r=>r.state.weights[0]=Infinity,r=>r.dataDraws=96,r=>r.round.rngAfter=r.rng=1,r=>r.round.examples[0]=r.round.examples[1],r=>r.round.before.weights[0]+=.1]){const bad=copy(run);mutate(bad);assert.throws(()=>d.validateDistributedTrainingRun(bad));}assert.throws(()=>d.readDistributedTrainingRun(' '.repeat(d.distributedLifecycleLimits.maxBytes+1)));});
test('import rejects corrupted submitted arithmetic and committed optimizer state',()=>{let run=submitAll(setup());let bad=copy(run);bad.round.ranks[0].contribution.gradientSum[0]+=.01;assert.throws(()=>d.readDistributedTrainingRun(JSON.stringify(bad)),/does not match/);run=d.commitDistributedRound(run);bad=copy(run);bad.state.moments[0]+=.1;assert.throws(()=>d.readDistributedTrainingRun(JSON.stringify(bad)),/optimizer disagrees/);});
test('restart and round budgets prevent unbounded simulations while preserving final valid state',()=>{let run=setup();for(let i=0;i<8;i++)run=d.restartDistributedRank(d.failDistributedRank(run,0),0);run=d.failDistributedRank(run,0);const saved=JSON.stringify(run);assert.throws(()=>d.restartDistributedRank(run,0),/budget/);assert.equal(JSON.stringify(run),saved);let bounded=d.createDistributedTrainingRun();for(let i=0;i<24;i++)bounded=finish(d.beginDistributedRound(bounded));assert.equal(bounded.commits,24);assert.throws(()=>d.beginDistributedRound(bounded),/budget/);assert.ok(d.serializeDistributedTrainingRun(bounded).length<d.distributedLifecycleLimits.maxBytes);});

test('workspace import retains independent final exposure and rejects stale or invalid changes before journal mutation',()=>{const bytes=new Map(),storage={getItem:k=>bytes.get(k)??null,setItem:(k,v)=>bytes.set(k,v)},journal=createLifecycleExposureJournal(storage),old=createLifecycleRun();const exposed={...old,finalOpened:true};let run=d.importDistributedWorkspace(JSON.stringify(exposed),journal,0,0);assert.equal(run.sourceCheckpoint.finalOpened,true);assert.equal(bytes.get(lifecycleWorkspaceKeys.exposure),'true');run=d.importDistributedWorkspace(JSON.stringify(old),journal,1,1);assert.equal(run.sourceCheckpoint.finalOpened,true);const fresh=createLifecycleExposureJournal(storage);assert.equal(d.importDistributedWorkspace(JSON.stringify(old),fresh,0,0).sourceCheckpoint.finalOpened,true);const clean=createLifecycleExposureJournal();assert.throws(()=>d.importDistributedWorkspace(JSON.stringify(exposed),clean,0,1),/changed/);assert.equal(clean.hasSeen(),false);assert.throws(()=>d.importDistributedWorkspace('{',clean,0,0));assert.equal(clean.hasSeen(),false);});

const startCollective=run=>d.beginDistributedCollective(submitAll(run));
const submitShards=run=>{for(const p of d.distributedShardOwners(run.round.ranks.length))if(!run.round.collective.gradientShards[p.owner])run=d.submitDistributedGradientShard(run,d.computeDistributedGradientShard(run,p.owner));return run;};
test('padded rank ownership covers every real parameter exactly once without optimizing the last dummy slot',()=>{for(const ranks of [2,3]){const owners=d.distributedShardOwners(ranks),indices=owners.flatMap(p=>Array.from({length:p.end-p.start},(_,i)=>p.start+i));assert.deepEqual(indices,Array.from({length:423},(_,i)=>i));assert.equal(new Set(owners.map(p=>p.paddedCount)).size,1);assert.deepEqual(owners.map(p=>p.end-p.start),ranks===2?[212,211]:[141,141,141]);assert.equal(owners.reduce((s,p)=>s+p.paddedCount-(p.end-p.start),0),ranks===2?1:0);}for(const r of [0,1,4,2.5,Infinity])assert.throws(()=>d.distributedShardOwners(r));});
test('actual owned numerators and every gathered replica independently match centralized gradients and Adam state',()=>{for(const partition of ['1+3','1+1+2'])for(const weighting of ['token','sample']){let run=startCollective(setup({partition,weighting}));const reference=d.centralizedDistributedReference(run);for(const owner of d.distributedShardOwners(run.round.ranks.length)){const shard=d.computeDistributedGradientShard(run,owner.owner);for(let i=0;i<shard.gradient.length;i++){const global=shard.start+i,numerator=run.round.ranks.reduce((sum,r)=>sum+r.contribution.gradientSum[global],0);near(shard.numerator[i],numerator,0);near(shard.gradient[i],reference.gradient[global],1e-10);}run=d.submitDistributedGradientShard(run,shard);}const expected=independentUpdate(run.round.before,reference.gradient,run.sourceCheckpoint.config),done=d.commitDistributedRound(run),c=done.round.collective;for(const shard of c.updatedShards){assert.equal(shard.optimizerStep,expected.optimizerStep);assert.ok(maxDiff(shard.weights,expected.weights.slice(shard.start,shard.end))<1e-10);assert.ok(maxDiff(shard.moments,expected.moments.slice(shard.start,shard.end))<1e-10);}for(const replica of c.replicas){assert.ok(maxDiff(replica.gradient,reference.gradient)<1e-10);assert.ok(maxDiff(replica.weights,expected.weights)<1e-10);assert.equal(replica.weights.length,423);}assert.deepEqual(d.reconstructDistributedShards([...c.updatedShards].reverse(),done.round),done.state);assert.deepEqual(d.readDistributedTrainingRun(d.serializeDistributedTrainingRun(done)),done);}});
test('an explicitly opened collective rejects missing owner shards without changing optimizer or filling them automatically',()=>{let run=startCollective(setup());run=d.submitDistributedGradientShard(run,d.computeDistributedGradientShard(run,0));const before=JSON.stringify(run);assert.throws(()=>d.commitDistributedRound(run),/Owned-shard barrier/);assert.equal(JSON.stringify(run),before);assert.equal(run.commits,0);assert.deepEqual(run.state,run.round.before);assert.throws(()=>d.beginDistributedCollective(run),/already active/);});
test('owned-shard failure invalidates the entire reduction; a restarted attempt cannot accept old shards',()=>{const original=startCollective(setup()),stale=d.computeDistributedGradientShard(original,0);let run=d.submitDistributedGradientShard(original,stale);run=d.failDistributedRank(run,1);assert.equal(run.round.collective,null);assert.deepEqual(run.state,original.state);run=d.restartDistributedRank(run,1);run=d.submitRankContribution(run,d.computeRankContribution(run,1));run=d.beginDistributedCollective(run);assert.throws(()=>d.submitDistributedGradientShard(run,stale),/Stale/);run=d.commitDistributedRound(submitShards(run));const reference=d.commitDistributedRound(submitShards(original));assert.deepEqual(run.state,reference.state);assert.equal(run.dataDraws,reference.dataDraws);assert.equal(run.rng,reference.rng);});
test('owned shard identity, denominator, range, padding, duplicate and arithmetic corruption are rejected',()=>{const run=startCollective(setup()),shard=d.computeDistributedGradientShard(run,0),before=JSON.stringify(run);for(const mutate of [s=>s.roundId+='old',s=>s.attempts[1]++,s=>s.owner=1,s=>s.start++,s=>s.end--,s=>s.paddedCount++,s=>s.denominator++,s=>s.numerator[0]+=.01,s=>s.gradient[0]+=.01,s=>s.extra=true,s=>s.gradient.push(0)]){const bad=copy(shard);mutate(bad);assert.throws(()=>d.submitDistributedGradientShard(run,bad));assert.equal(JSON.stringify(run),before);}const submitted=d.submitDistributedGradientShard(run,shard);assert.throws(()=>d.submitDistributedGradientShard(submitted,shard),/already submitted/);});
test('partial reduce-scatter checkpoint resumes exact owned state and all-gather',()=>{let run=startCollective(setup({partition:'1+1+2'}));run=d.submitDistributedGradientShard(run,d.computeDistributedGradientShard(run,1));const restored=d.readDistributedTrainingRun(d.serializeDistributedTrainingRun(run));assert.deepEqual(restored,run);assert.deepEqual(d.commitDistributedRound(submitShards(restored)),d.commitDistributedRound(submitShards(run)));});
test('all-gather rejects missing, duplicate, stale and cross-owner parameter payloads',()=>{const done=finish(setup()),payload=done.round.collective.updatedShards;assert.throws(()=>d.reconstructDistributedShards(payload.slice(0,1),done.round),/barrier/);assert.throws(()=>d.reconstructDistributedShards([payload[0],payload[0]],done.round),/barrier/);for(const mutate of [s=>s.roundId+='old',s=>s.attempts[0]++,s=>s.optimizerStep++,s=>s.start++,s=>s.end++,s=>s.weights.push(0),s=>s.squares[0]=-1]){const bad=copy(payload);mutate(bad[0]);assert.throws(()=>d.reconstructDistributedShards(bad,done.round));}});
test('strict checkpoint import recomputes owned gradients, updates and every replica before accepting them',()=>{const done=finish(setup());for(const mutate of [r=>r.round.collective.gradientShards[0].gradient[1]+=.1,r=>r.round.collective.updatedShards[1].moments[2]+=.1,r=>r.round.collective.replicas[1].weights[2]+=.1,r=>r.round.collective.replicas[0].gradient[3]+=.1,r=>r.round.collective.attempts[0]++,r=>r.round.collective.extra=true,r=>r.round.collective.gradientShards.pop(),r=>r.round.collective=null,r=>r.modelVersion='distributed-causal-gradient-1']){const bad=copy(done);mutate(bad);assert.throws(()=>d.readDistributedTrainingRun(JSON.stringify(bad)));}});
test('logical padded transfer and optimizer ownership accounting reconcile independently of checkpoint serialization',()=>{for(const partition of ['1+3','1+1+2']){const done=finish(setup({partition})),trace=d.inspectDistributedCollective(done),ranks=done.round.ranks.length,padded=Math.ceil(423/ranks),phaseBytes=ranks*(ranks-1)*padded*8;assert.equal(trace.logicalBytes,3*phaseBytes);assert.equal(trace.transfers.length,3*ranks*(ranks-1));for(const phase of ['reduce-scatter','gradient-all-gather','weight-all-gather'])assert.equal(trace.transfers.filter(t=>t.phase===phase).reduce((n,t)=>n+t.logicalBytes,0),phaseBytes);for(const t of trace.transfers){assert.notEqual(t.from,t.to);assert.equal(t.values.length+t.paddingZeros,padded);assert.equal(t.logicalBytes,8*padded);}assert.equal(trace.memory.reduce((n,m)=>n+m.ownedOptimizerScalars,0),846);assert.equal(trace.memory.reduce((n,m)=>n+m.replicatedWeightScalars,0),ranks*423);}});
test('the next batch releases old collective payloads without changing the committed source of its optimizer state',()=>{const done=finish(setup()),saved=JSON.stringify(done),next=d.beginDistributedRound(done);assert.equal(next.round.collective,null);assert.ok(next.round.ranks.every(r=>r.contribution===null));assert.deepEqual(next.round.before,done.state);assert.equal(JSON.stringify(done),saved);const oldShard=done.round.collective.gradientShards[0],ready=startCollective(next);assert.throws(()=>d.submitDistributedGradientShard(ready,oldShard),/Stale/);});
