import test from 'node:test';import assert from 'node:assert/strict';
import {cellConstants as c,cellDefaults as d,deriveCellParameters as derive,buildCellAcceptance as run,longChannelCurrent as current,inverterTransfer as vtc,dischargeTimeSeconds as delay,normalizeCellInput,makeCellRecord,parseCellRecord} from '../src/lib/process-cell-acceptance.ts';
import {makeProcessCellRecord,parseProcessCellRecord,saveProcessCellRecord,exportOlderProcessCellRecords,processCellRecordKey,processCellRecoveryKey} from '../src/lib/process-cell-acceptance-record.ts';
const near=(a,b,rel=1e-9)=>assert.ok(Math.abs(a-b)<=rel*Math.max(Math.abs(b),1e-30),`${a} ≈ ${b}`);
function independentQuadrature(beta,vt,cap,low,high,n=12000){const dx=(high-low)/n;const integrand=x=>cap/(beta*(x<c.supplyV-vt?(c.supplyV-vt)*x-x*x/2:(c.supplyV-vt)**2/2));let sum=integrand(low)+integrand(high);for(let i=1;i<n;i++)sum+=(i%2?4:2)*integrand(low+i*dx);return sum*dx/3;}
test('default units and expected quantities anchor the named specimen',()=>{const r=run(d);near(r.parameters.coxFpm2,.00345306);near(r.parameters.loadCapF,65.24896e-15);near(r.parameters.betaN,.0001553877);near(r.parameters.thresholdNV,.34583928457657853);near(r.timing.fall50Seconds,.699775851668897e-9);assert.equal(r.specimenId,'INV-01');assert.ok(r.stages.every(s=>s.specimenId===r.specimenId));assert.ok(r.accepted);});
test('oxide variation propagates consistently into capacitance, beta and fixed-charge threshold',()=>{const a=derive(d),b=derive({...d,oxideOffsetPct:20});near(b.oxideNm,12);near(b.coxFpm2/a.coxFpm2,1/1.2);near(b.gateCapF/a.gateCapF,1/1.2);near(b.betaN/a.betaN,1/1.2);near(b.thresholdNV-a.thresholdNV,c.depletionChargeCpm2*(1/b.coxFpm2-1/a.coxFpm2));});
test('current regimes join continuously, saturate at the declared overdrive and turn off',()=>{const p=derive(d),u=c.supplyV-p.thresholdNV;assert.equal(current(p.betaN,p.thresholdNV,p.thresholdNV,1),0);assert.equal(current(p.betaN,p.thresholdNV,c.supplyV,0),0);near(current(p.betaN,p.thresholdNV,c.supplyV,u),.5*p.betaN*u*u);near(current(p.betaN,p.thresholdNV,c.supplyV,u-1e-8),current(p.betaN,p.thresholdNV,c.supplyV,u+1e-8),1e-7);assert.equal(current(p.betaN,p.thresholdNV,c.supplyV,u),current(p.betaN,p.thresholdNV,c.supplyV,c.supplyV));});
test('balanced closed-form unity-gain points and conservative margins match',()=>{const r=run(d),vt=r.parameters.thresholdNV;near(r.parameters.switchingV,c.supplyV/2);near(r.noise.vilV,(3*c.supplyV+2*vt)/8);near(r.noise.vihV,c.supplyV-r.noise.vilV);near(r.noise.volV,(c.supplyV-2*vt)/8);near(r.noise.nmlV,c.supplyV/4+vt/2);near(r.noise.nmlV,r.noise.nmhV);near(vtc(r.parameters,r.noise.vilV).gain,-1);near(vtc(r.parameters,r.noise.vihV).gain,-1);});
test('ideal switching input exposes an interval of current-balanced outputs',()=>{const p=derive({...d,mobilityNScale:.7,thresholdNShiftMv:60}),point=vtc(p,p.switchingV);assert.equal(point.vout,null);assert.equal(point.gain,null);assert.ok(point.outputLowV<point.outputHighV);for(let i=0;i<=20;i++){const out=point.outputLowV+i/20*(point.outputHighV-point.outputLowV);near(current(p.betaN,p.thresholdNV,point.vin,out),current(p.betaP,p.thresholdPV,c.supplyV-point.vin,c.supplyV-out));}});
test('54 process/load corners satisfy branch current balance and exact noise definitions',()=>{for(const oxideOffsetPct of [-20,0,20])for(const mobilityNScale of [.5,1,1.5])for(const thresholdNShiftMv of [-120,0,120])for(const fanout of [1,4]){const r=run({...d,oxideOffsetPct,mobilityNScale,thresholdNShiftMv,fanout}),p=r.parameters;for(const t of r.transfer){if(t.vout===null)continue;const n=current(p.betaN,p.thresholdNV,t.vin,t.vout),pm=current(p.betaP,p.thresholdPV,c.supplyV-t.vin,c.supplyV-t.vout);assert.ok(Math.abs(n-pm)<1e-14);assert.ok(t.vout>=0&&t.vout<=c.supplyV);}near(r.noise.nmlV,r.noise.vilV-r.noise.volV);near(r.noise.nmhV,r.noise.vohV-r.noise.vihV);assert.equal(r.accepted,r.gates.every(g=>g.pass));}});
test('transfer analytic slopes match an independent centered numerical derivative',()=>{for(const patch of [{},{mobilityNScale:.7,thresholdNShiftMv:80},{oxideOffsetPct:20,mobilityNScale:1.4}]){const p=derive({...d,...patch});for(let i=1;i<120;i++){const x=i/100;if(Math.abs(x-p.switchingV)<.015||Math.abs(x-p.thresholdNV)<.015||Math.abs(x-(c.supplyV-p.thresholdPV))<.015)continue;const h=1e-6,derivative=(vtc(p,x+h).vout-vtc(p,x-h).vout)/(2*h);assert.ok(Math.abs(derivative-vtc(p,x).gain)<1e-6);}}});
test('analytic delays match independent Simpson integration across 54 process/load corners',()=>{for(const oxideOffsetPct of [-20,0,20])for(const mobilityNScale of [.5,1,1.5])for(const thresholdNShiftMv of [-120,0,120])for(const fanout of [1,4]){const r=run({...d,oxideOffsetPct,mobilityNScale,thresholdNShiftMv,fanout}),p=r.parameters;for(const [beta,vt] of [[p.betaN,p.thresholdNV],[p.betaP,p.thresholdPV]])for(const [lo,hi] of [[.6,1.2],[.12,1.08]])near(delay(beta,vt,p.loadCapF,lo,hi),independentQuadrature(beta,vt,p.loadCapF,lo,hi),2e-8);}});
test('constant saturation-current segment obeys CΔV/I and integration is additive',()=>{const p=derive(d),u=c.supplyV-p.thresholdNV;near(delay(p.betaN,p.thresholdNV,p.loadCapF,1,1.2),p.loadCapF*.2/(.5*p.betaN*u*u));near(delay(p.betaN,p.thresholdNV,p.loadCapF,.12,1.2),delay(p.betaN,p.thresholdNV,p.loadCapF,.12,u)+delay(p.betaN,p.thresholdNV,p.loadCapF,u,1.2));assert.equal(delay(p.betaN,p.thresholdNV,p.loadCapF,.6,.6),0);});
test('delay scales exactly with load while static transfer/noise does not',()=>{const a=run(d),b=run({...d,fanout:4});near(b.timing.fall50Seconds/a.timing.fall50Seconds,b.parameters.loadCapF/a.parameters.loadCapF);assert.deepEqual(a.noise,b.noise);assert.equal(b.gates.find(g=>g.id==='timing').pass,false);assert.ok(b.gates.filter(g=>g.id!=='timing').every(g=>g.pass));});
test('geometry failure and asymmetric electrical failures stay distinct',()=>{const geom=run({...d,oxideOffsetPct:20});assert.equal(geom.gates[0].pass,false);assert.ok(geom.gates.slice(1).every(g=>g.pass));const electrical=run({...d,mobilityNScale:.5,thresholdNShiftMv:120});assert.equal(electrical.gates[0].pass,true);assert.equal(electrical.gates.find(g=>g.id==='noise').pass,false);assert.equal(electrical.gates.find(g=>g.id==='timing').pass,false);assert.ok(electrical.parameters.switchingV>.6);});
test('transition timestamps advance monotonically and the 50% sample matches delay',()=>{const r=run({...d,mobilityNScale:.5});for(let i=1;i<r.transitions.length;i++){assert.ok(r.transitions[i].fallSeconds>r.transitions[i-1].fallSeconds);assert.ok(r.transitions[i].riseSeconds>r.transitions[i-1].riseSeconds);assert.ok(r.transitions[i].fallV<r.transitions[i-1].fallV);assert.ok(r.transitions[i].riseV>r.transitions[i-1].riseV);}near(r.transitions[50].fallSeconds,r.timing.fall50Seconds);near(r.transitions[50].riseSeconds,r.timing.rise50Seconds);assert.ok(r.transitions.at(-1).fallV>0);});
test('invalid process domains, zero load and finite-time zero-voltage endpoint are rejected',()=>{for(const x of [{...d,oxideNominalNm:1},{...d,mobilityNScale:NaN},{...d,fanout:.5},{...d,fanout:0,externalLoadFf:0},{...d,extra:2}])assert.throws(()=>normalizeCellInput(x));const p=derive(d);assert.throws(()=>delay(p.betaN,p.thresholdNV,p.loadCapF,0,1.2));assert.throws(()=>vtc(p,1.3));assert.throws(()=>current(-1,.3,1,1));});
test('portable records retain exact complete inputs and reject model mismatches',()=>{const r=makeCellRecord(d);assert.deepEqual(parseCellRecord(JSON.stringify(r)),r);assert.deepEqual(parseProcessCellRecord(JSON.stringify(r)),makeProcessCellRecord(d));assert.throws(()=>parseCellRecord(JSON.stringify({...r,modelVersion:'old'})));assert.throws(()=>parseProcessCellRecord(JSON.stringify({...r,input:{...d,fanout:-1}})));});
const store=(initial={},fail)=>{const data={...initial};return {data,getItem:k=>data[k]??null,setItem:(k,v)=>{if(k===fail)throw new Error('quota');data[k]=v;}};};
test('incompatible prior raw input is preserved before save and backup failure leaves active data',()=>{const s=store({[processCellRecordKey]:'old raw'});saveProcessCellRecord(s,makeProcessCellRecord(d));assert.equal(exportOlderProcessCellRecords(s),'old raw');const fail=store({[processCellRecordKey]:'old raw'},processCellRecoveryKey);assert.throws(()=>saveProcessCellRecord(fail,makeProcessCellRecord(d)));assert.equal(fail.data[processCellRecordKey],'old raw');});

test('finite-time inverse of the delay integral preserves the model clock and charge swing',async()=>{const {outputAfterStep}=await import('../src/lib/process-cell-acceptance.ts');for(const patch of [{},{fanout:4},{mobilityNScale:.5,thresholdNShiftMv:120}]){const r=run({...d,...patch}),p=r.parameters;near(outputAfterStep(p,'fall',r.timing.fall50Seconds),.6);near(outputAfterStep(p,'rise',r.timing.rise50Seconds),.6);assert.equal(outputAfterStep(p,'fall',0),1.2);assert.equal(outputAfterStep(p,'rise',0),0);for(const progress of [.1,.3,.7,.9,.99]){const time=delay(p.betaN,p.thresholdNV,p.loadCapF,1.2*(1-progress),1.2);near(outputAfterStep(p,'fall',time),1.2*(1-progress),1e-8);}}});
test('two complete lessons and eight canonical equations preserve valid graph references',async()=>{const fs=await import('node:fs'),katex=(await import('katex')).default;const pack=JSON.parse(fs.readFileSync(new URL('../src/lib/data/process-cell-learning.json',import.meta.url),'utf8')),eq=JSON.parse(fs.readFileSync(new URL('../src/lib/data/equations-process-cell-learning.json',import.meta.url),'utf8'));const {loadAuthoredAtlas}=await import('./atlas-authoring.mjs'),atlas=await loadAuthoredAtlas(),ids=new Set([...atlas.records.map(r=>r.id),...pack.lessons.map(r=>r.id)]);assert.equal(pack.lessons.length,2);assert.equal(Object.values(eq).flat().length,8);for(const l of pack.lessons){assert.ok(l.description.length>500);assert.equal(l.science.length,eq[l.id].length);assert.equal(l.check.options.length,3);for(const ref of [...l.prerequisites,...l.related])assert.ok(ids.has(ref),ref);for(const m of eq[l.id])katex.renderToString(m.latex,{strict:'error',throwOnError:true});}});
test('authored material-to-cell worked examples match current model values',async()=>{const fs=await import('node:fs');const pack=JSON.parse(fs.readFileSync(new URL('../src/lib/data/process-cell-learning.json',import.meta.url),'utf8'));for(const l of pack.lessons){const r=run({...d,...(l.workedTrace.scenario==='thicker-oxide'?{oxideOffsetPct:20}:{fanout:4})});for(const [key,value] of Object.entries(l.workedTrace.expected)){const actual=key in r?r[key]:key in r.parameters?r.parameters[key]:key in r.noise?r.noise[key]:r.timing[key];if(typeof value==='number')near(actual,value,1e-9);else assert.equal(actual,value);}}});
