'use client';
import { useCallback, useEffect, useMemo, useRef, useState, useLayoutEffect, lazy, Suspense } from 'react';
import { flushSync } from 'react-dom';
import { Atom, BookOpen, Box, ChevronDown, ChevronLeft, ChevronRight, Check, ExternalLink, Film, FlaskConical, History, Layers3, Maximize2, Network, Pause, Play, RotateCcw, Search, Tag, X, ScanLine, GraduationCap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const AtlasScene=lazy(()=>import('@/components/atlas-scene'));
const ProcessMechanism=lazy(()=>import('@/components/process-mechanism'));
const SciencePanel=lazy(()=>import('@/components/science-panel'));
import {restoreProgress,serializeProgress} from '@/lib/learning-progress';
import legacyCheckRevisions from '@/lib/data/legacy-check-revisions.json';
import {useLesson} from '@/lib/use-lesson';
import type {RecordEntry} from '@/lib/atlas';
import BandDiagram from '@/components/band-diagram';
import {parseAtlasHash,encodeAtlasHash} from '@/lib/url-state';
const Investigations=lazy(()=>import('@/components/investigations'));
import type {InvestigationId} from '@/lib/investigation-models';
const Lab=lazy(()=>import('@/components/lab'));
import { records,byId,chapters,chapterFor,bands,journeys } from '@/lib/atlas';
import originalMilestones from '@/lib/data/milestones.json';
import {contentPacks} from '@/lib/atlas';
import {ProcessControls,DependencyView,EvidenceLibrary,LessonDepth,Glossary,type ViewMode} from '@/components/atlas-exploration';
import CRGBridge from '@/components/crg-bridge';
const SpecimenComparison=lazy(()=>import('@/components/specimen-comparison'));
const GlobalAtlas=lazy(()=>import('@/components/global-atlas'));
import AtlasNavigation from '@/components/atlas-navigation';
import ResourceBoundary from '@/components/resource-boundary';
import ReadingGuide from '@/components/reading-guide';
const milestones=[...originalMilestones,...contentPacks.flatMap(p=>p.milestones) as typeof originalMilestones].sort((a,b)=>Number.parseFloat(String(a.year))-Number.parseFloat(String(b.year)));
const processScene=(scene:string,band:number)=>{if(['orbital-system','process-tool','fab-operations','design-flow'].includes(scene))return scene;if(['fabrication','process-wafer','process-tool','fab-operations'].includes(scene))return 'process-wafer';if(['transistor','device-crosssection'].includes(scene))return 'device-crosssection';if(['memory-stack','hbm-detail'].includes(scene))return 'hbm-detail';if(['package','package-route','signal-power'].includes(scene))return 'package-route';if(band===0)return 'device-crosssection';if(band===1||band>=4)return 'software-flow';return 'hall-system';};
export default function Home(){
 const [selected,setSelected]=useState('gpu-die'),[explode,setExplode]=useState(32),[isolated,setIsolated]=useState(false),[reset,setReset]=useState(0),[running,setRunning]=useState(true),[labels,setLabels]=useState(true),[xray,setXray]=useState(false);
 const [investigationId,setInvestigationId]=useState<InvestigationId>('manufacturing'),[sharedDocument,setSharedDocument]=useState(''),[sharedEncoded,setSharedEncoded]=useState('');
 const [modal,setModal]=useState(''),[query,setQuery]=useState(''),[tab,setTab]=useState('learn'),[openBands,setOpenBands]=useState([2]),[journey,setJourney]=useState(''),[step,setStep]=useState(0),[visited,setVisited]=useState<string[]>([]),[answers,setAnswers]=useState<Record<string,number>>({}),[ready,setReady]=useState(false);
 const [view,setView]=useState<ViewMode>('anatomy'),[processStep,setProcessStep]=useState(0),[overlay,setOverlay]=useState('structure');
 const [phone,setPhone]=useState(()=>window.matchMedia('(max-width: 800px)').matches),[modelActive,setModelActive]=useState(false),[lowPower,setLowPower]=useState(()=>window.matchMedia('(pointer: coarse)').matches);
 const restoringNavigation=useRef(true);
 const inspector=useRef<HTMLElement>(null),search=useRef<HTMLInputElement>(null),lessonHeading=useRef<HTMLHeadingElement>(null),stageRef=useRef<HTMLElement>(null),pendingLessonFocus=useRef(false);
 useEffect(()=>{const media=window.matchMedia('(max-width: 800px)');const update=()=>setPhone(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 const openModel=()=>{setModelActive(true);requestAnimationFrame(()=>{stageRef.current?.scrollIntoView({block:'start'});stageRef.current?.focus({preventScroll:true});});};
 const returnToLesson=()=>{setModelActive(false);requestAnimationFrame(()=>{lessonHeading.current?.focus({preventScroll:true});lessonHeading.current?.scrollIntoView({block:'start'});});};
 const loaded=useLesson(selected);
 const record:RecordEntry=loaded.lesson||{...(byId[selected]??records[0]),description:'',specs:[],interfaces:[],tradeoff:'',whyAI:'',sources:[],mechanism:[],misconception:''};
 const chapter=chapterFor(record.id),index=chapters.indexOf(chapter),band=bands[chapter.band],parts=chapter.ids.map(id=>byId[id]).filter(Boolean);
 const path=journeys.find(j=>j.id===journey);const pathIds=path?.ids.filter(id=>byId[id])??[];
 const select=useCallback((id:string,focus=true)=>{if(!byId[id])return;pendingLessonFocus.current=focus;if(focus)setModelActive(false);setSelected(id);setIsolated(false);setProcessStep(0);setOverlay('structure');setOpenBands(x=>[...new Set([...x,chapterFor(id).band])]);setVisited(v=>v.includes(id)?v:[...v,id]);setTab('learn');inspector.current?.scrollTo({top:0});},[]);
 useEffect(()=>{if(!ready||!loaded.lesson||modal||!pendingLessonFocus.current)return;let frame:number;const focus=()=>{if(document.querySelector('[data-slot=dialog-content]')){frame=requestAnimationFrame(focus);return;}if(!lessonHeading.current)return;pendingLessonFocus.current=false;lessonHeading.current.focus({preventScroll:true});if(phone)lessonHeading.current.scrollIntoView({block:'start'});else inspector.current?.scrollTo({top:0});};frame=requestAnimationFrame(focus);return()=>cancelAnimationFrame(frame);},[selected,ready,modal,phone,loaded.lesson]);
 const selectChapter=(id:string)=>{const c=chapters.find(c=>c.id===id);if(c){const first=c.ids.find(id=>byId[id]);if(first)select(first);}};
 useEffect(()=>{const restore=()=>{restoringNavigation.current=true;const u=parseAtlasHash(window.location.hash);if(byId[u.lesson]){select(u.lesson);setView(u.view);setModelActive(u.view!=='anatomy');setProcessStep(Math.min(5,u.processStep));setJourney(journeys.some(j=>j.id===u.path)?u.path:'');setStep(Math.min(u.pathStep,Math.max(0,(journeys.find(j=>j.id===u.path)?.ids.length||1)-1)));setModal(u.comparison?'compare':'');if(['switching','manufacturing','execution'].includes(u.investigation||'')){setInvestigationId(u.investigation as InvestigationId);try{setSharedDocument(u.scenario?atob(u.scenario.replace(/-/g,'+').replace(/_/g,'/')):'');setSharedEncoded(u.scenario||'');}catch{setSharedDocument('');setSharedEncoded('');}setModal('investigations');}}};queueMicrotask(()=>{try{const saved=restoreProgress(localStorage.getItem('ai-atlas-learning-v1')||'{}',records,legacyCheckRevisions);setVisited(saved.visited);setAnswers(saved.answers);}catch{}restore();setReady(true);});const hotkey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setModal('search');}};window.addEventListener('keydown',hotkey);window.addEventListener('hashchange',restore);return()=>{window.removeEventListener('keydown',hotkey);window.removeEventListener('hashchange',restore);};},[select]);
 useEffect(()=>{if(!ready)return;const hash=encodeAtlasHash({lesson:selected,view,processStep,path:journey,pathStep:step,comparison:modal==='compare'?'specimens':'',investigation:modal==='investigations'?investigationId:'',scenario:modal==='investigations'?sharedEncoded:''});if(window.location.hash!==hash){const prior=parseAtlasHash(window.location.hash);if(!restoringNavigation.current&&(prior.lesson!==selected||prior.path!==journey))history.pushState(null,'',hash);else history.replaceState(null,'',hash);}restoringNavigation.current=false;},[ready,selected,view,processStep,journey,step,modal,investigationId,sharedEncoded]);
 useEffect(()=>{if(ready)try{localStorage.setItem('ai-atlas-learning-v1',serializeProgress({visited,answers},records));}catch{}},[ready,visited,answers]);
 useEffect(()=>{if(modal==='search')setTimeout(()=>search.current?.focus(),100);},[modal]);
 const state=useRef({selected,explode,isolated,journey,step});useLayoutEffect(()=>{state.current={selected,explode,isolated,journey,step};},[selected,explode,isolated,journey,step]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  register({name:'search_atlas',description:'Read component matches from the AI atlas. Does not change the view.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(v:{query:string})=>{if(typeof v.query!=='string')throw Error('query must be a string');return records.filter(r=>v.query.toLowerCase().trim().split(/\s+/).every(term=>(r.name+' '+r.role+' '+r.id+' '+chapterFor(r.id).name).toLowerCase().includes(term))).slice(0,20).map(r=>({id:r.id,name:r.name,branch:chapterFor(r.id).name}));}});
  register({name:'navigate_atlas',description:'Select a component and configure its visible 3D assembly.',inputSchema:{type:'object',properties:{componentId:{type:'string'},explode:{type:'number',minimum:0,maximum:100},isolate:{type:'boolean'}},required:['componentId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(v:{componentId:string;explode?:number;isolate?:boolean})=>{if(!byId[v.componentId])throw Error('Unknown component ID');if(v.explode!==undefined&&(!Number.isFinite(v.explode)||v.explode<0||v.explode>100))throw Error('explode must be 0–100');if(v.isolate!==undefined&&typeof v.isolate!=='boolean')throw Error('isolate must be boolean');flushSync(()=>{select(v.componentId);if(v.explode!==undefined)setExplode(v.explode);if(v.isolate!==undefined)setIsolated(v.isolate);});return {componentId:v.componentId,branch:chapterFor(v.componentId).name,explode:v.explode??state.current.explode,isolate:v.isolate??false};}});
  register({name:'read_atlas_state',description:'Read the currently selected component and assembly controls.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state.current})});return()=>life.abort();
 },[select]);
 const matches=useMemo(()=>records.filter(r=>query.toLowerCase().trim().split(/\s+/).every(term=>(r.name+' '+r.role+' '+r.id+' '+chapterFor(r.id).name).toLowerCase().includes(term))),[query]);
 const startPath=(id:string)=>{const j=journeys.find(j=>j.id===id);if(!j)return;setJourney(id);setStep(0);select(j.ids.find(id=>byId[id])!);setModal('');};
 useEffect(()=>{const current=pathIds.indexOf(selected);if(current>=0)setStep(current);},[selected,journey]);
 const detour=Boolean(path&&pathIds[step]!==selected);
 const goStep=(n:number)=>{if(pathIds[n]){setStep(n);select(pathIds[n]);}};
 const answer=answers[record.id];const completed=records.filter(r=>answers[r.id]===r.check?.answer).length;
 const navigation=<AtlasNavigation chapterId={chapter.id} openBands={openBands} onToggle={i=>setOpenBands(x=>x.includes(i)?x.filter(n=>n!==i):[...x,i])} onChapter={id=>{selectChapter(id);if(modal==='contents')setModal('');}} onSelect={id=>{select(id);if(modal==='contents')setModal('');}} onModal={setModal} completed={completed} visited={visited.length} searchable={modal==='contents'}/>;
 return <main className="atlas-shell"><a className="skip-to-lesson" href="#lesson-heading" onClick={e=>{e.preventDefault();returnToLesson();}}>Skip to lesson</a><header className="topbar"><div className="brand"><a className="foundry-home" href="https://semiaifoundry.com/" aria-label="SemiAIFoundry home">semiAIfoundry</a><Atom size={27}/><strong>AI ATLAS</strong><span>THE MACHINERY OF INTELLIGENCE</span></div><div className="compact-actions"><Button variant="outline" onClick={()=>setModal('contents')}>Contents</Button><Button variant="ghost" onClick={()=>setModal('search')} aria-label="Find a component"><Search/></Button><Button variant="ghost" onClick={()=>setModal('menu')}>Menu</Button></div><div className="top-actions"><Button variant="ghost" className="search-launch" aria-label="Find a component" onClick={()=>setModal('search')}><Search/><span>Find a component</span><kbd>⌘ K</kbd></Button><Button variant="outline" onClick={()=>setModal('paths')}><BookOpen/><span className="label-long">Learning paths</span></Button><Button variant="outline" onClick={()=>{setSharedDocument('');setSharedEncoded('');setModal('investigations');}}><FlaskConical/><span>Investigations</span></Button><Button variant="ghost" onClick={()=>setModal('compare')}>Compare</Button><Button variant="ghost" onClick={()=>setModal('history')} aria-label="Historical breakthroughs"><History/></Button><Button variant="ghost" onClick={()=>setModal('evidence')}>Evidence</Button><Button variant="ghost" onClick={()=>setModal('global')}>Global</Button><Button variant="outline" onClick={()=>setModal('film')}><Film/><span className="label-long">The film</span></Button></div></header>
 <div className="workspace"><aside className="navigator"><div className="eyebrow nav-heading">NANO → MACRO → INTELLIGENCE</div>{navigation}</aside>
 <section className={`stage view-${view} ${modelActive?'model-active':''}`} ref={stageRef} tabIndex={-1} aria-label="Interactive model workspace"><div className="mobile-model-heading"><Button variant="outline" onClick={returnToLesson}><ChevronLeft/> Back to lesson</Button><span>Drag in the model to orbit</span></div><div className="stage-heading"><div className="eyebrow" style={{color:band.color}}>{String(index+1).padStart(2,'0')} / {chapter.scale.toUpperCase()}</div><h1>{chapter.title}</h1><p>{chapter.summary}</p><div className="view-modes" aria-label="Exploration view">{(['anatomy','process','dependencies'] as ViewMode[]).map(m=><button aria-pressed={view===m} key={m} onClick={()=>{setView(m);setProcessStep(0);setExplode(0);}}>{m==='anatomy'?'Anatomy':m==='process'?'Process':'Connections'}</button>)}</div></div><div className="view-actions"><Button variant={lowPower?'secondary':'ghost'} onClick={()=>setLowPower(!lowPower)} aria-pressed={lowPower} aria-label="Low power 3D">Eco</Button><Button size="icon" variant={labels?'secondary':'ghost'} onClick={()=>setLabels(!labels)} aria-label={labels?'Hide labels':'Show labels'} title="Labels"><Tag/></Button><Button size="icon" variant={xray?'secondary':'ghost'} onClick={()=>setXray(!xray)} aria-label="Toggle translucent cutaway" title="Translucent view"><ScanLine/></Button></div>
 <div className={view==='dependencies'?'stage-diagram':view==='process'?'process-scene':'anatomy-scene'}>{view==='dependencies'?<DependencyView selected={record} onSelect={select}/>:view==='process'?<ResourceBoundary name="process mechanism"><Suspense fallback={<p>Loading the process mechanism…</p>}><ProcessMechanism key={record.id} recordId={record.id} scene={processScene(chapter.scene,chapter.band)} index={processStep} onStep={setProcessStep} onSelect={select}/></Suspense></ResourceBoundary>:record.id==='energy-bands'&&view==='anatomy'?<BandDiagram/>:(!phone||modelActive)&&<ResourceBoundary name="3D viewer"><Suspense fallback={<p className="scene-loading">Loading the 3D model…</p>}><AtlasScene level={chapter.scene} records={parts} selected={record.id} onSelect={id=>select(id,false)} explode={explode} isolate={isolated} reset={reset} running={false} labels={labels} xray={xray} signal={undefined} overlay="structure" active={!modal&&(!phone||modelActive)} lowPower={lowPower}/></Suspense></ResourceBoundary>}</div>
 <div className={"stage-lower "+(view!=='anatomy'?'compact-lower':'')}>{path&&<div className="journey-bar"><div><span className="eyebrow">{detour?'PATH DETOUR · RETURN TO':'GUIDED PATH ·'} {step+1}/{pathIds.length}</span><strong>{path.name}</strong></div><Button size="icon" variant="ghost" disabled={step===0} onClick={()=>goStep(step-1)} aria-label="Previous path step"><ChevronLeft/></Button><Button size="icon" variant="ghost" disabled={!detour&&step===pathIds.length-1} onClick={()=>goStep(detour?step:step+1)} aria-label="Next path step"><ChevronRight/></Button><Button size="icon" variant="ghost" onClick={()=>setJourney('')} aria-label="Leave guided path"><X/></Button></div>}
 <div className={"assembly-selector "+(view!=='anatomy'?'visually-suppressed':'')}><span className="eyebrow">SELECT A COMPONENT</span><div>{parts.map(p=><button className={record.id===p.id?'selected':''} key={p.id} onClick={()=>select(p.id,false)}><span className="status-dot"/>{p.shortName}</button>)}</div></div><div className="scene-toolbar"><Button aria-label={isolated?'Show full assembly':'Isolate component'} variant={isolated?'default':'outline'} onClick={()=>setIsolated(!isolated)}><Maximize2/><span>Isolate</span></Button><Button variant="outline" onClick={()=>{setReset(reset+1);setExplode(0);setIsolated(false);setXray(false);}} aria-label="Reset assembly"><RotateCcw/></Button><div className="explode-control"><Layers3 size={17}/><span>Explode</span><Slider value={[explode]} onValueChange={v=>setExplode(Array.isArray(v)?v[0]:v)} max={100} aria-label="Explode assembly"/><output>{explode}%</output></div><Button variant="secondary" aria-label="Open numerical labs" onClick={()=>setModal('lab')}><FlaskConical/><span>Lab</span></Button></div><p className="gesture-hint">Drag to orbit · Schematic assembly. Connected investigations trace calculated quantities.</p></div>
 </section>
 <aside className="inspector" ref={inspector} aria-busy={!loaded.lesson}><div className="lesson-loading" role="status" hidden={Boolean(loaded.lesson)}><h2>{record.name}</h2><p>{loaded.error||'Loading the lesson…'}</p>{loaded.error&&<Button onClick={loaded.retry}>Retry lesson</Button>}</div>{loaded.lesson&&<><div className="inspector-top"><span className="eyebrow">COMPONENT FIELD GUIDE</span><span className="record-counter">{records.findIndex(r=>r.id===record.id)+1}/{records.length}</span></div><div className="lesson-breadcrumb">{band.name} → {chapter.parent||chapter.name} → {record.subbranch||record.shortName}</div><div className="component-kicker" style={{color:band.color}}><Box size={15}/>{chapter.name}</div><h2 id="lesson-heading" tabIndex={-1} ref={lessonHeading}>{record.name}</h2><p className="role">{record.role}</p><div className="mobile-learning-tools"><div className="model-preview"><Box size={38} aria-hidden="true"/><div><strong>{chapter.name} · 3D assembly</strong><p>Inspect the parts, follow the process, and explore their connections.</p></div><Button variant="outline" onClick={openModel}>Explore 3D</Button></div><div className="reader-actions"><Button variant="outline" onClick={()=>setModal('contents')}>Browse lessons</Button><Button variant="outline" onClick={()=>setModal('lab')}><FlaskConical/> Labs</Button></div>{path&&<div className="reader-path"><span>{path.name} · {detour?'Detour, resume ':''}{step+1}/{pathIds.length}</span><Button variant="outline" disabled={step===0} onClick={()=>goStep(step-1)} aria-label="Previous path lesson"><ChevronLeft/></Button><Button variant="outline" disabled={!detour&&step===pathIds.length-1} onClick={()=>goStep(detour?step:step+1)} aria-label="Next path lesson"><ChevronRight/></Button><Button variant="ghost" onClick={()=>setJourney('')}>Leave path</Button></div>}</div><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="detail-tabs"><TabsTrigger value="learn">Learn</TabsTrigger><TabsTrigger value="science">Science</TabsTrigger><TabsTrigger value="specs">Specs</TabsTrigger><TabsTrigger value="links">Connections</TabsTrigger></TabsList>
 <TabsContent value="learn">{record.investigationId&&<Button variant="outline" className="wide-button" onClick={()=>{setInvestigationId(record.investigationId!);setSharedDocument('');setSharedEncoded('');setModal('investigations');}}><FlaskConical/> Connect this lesson to an investigation</Button>}<LessonDepth record={record} onSelect={select}/><div className="detail-section first"><p>{record.description}</p></div><div className="detail-section"><h3>How it works</h3><ol className="mechanism">{record.mechanism?.map((s,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></div><div className="detail-section"><h3>Why it matters to AI</h3><p>{record.whyAI}</p></div><div className="misconception"><h3>Distinction to keep</h3><p>{record.misconception}</p></div>{record.check&&<div className="knowledge-check"><div className="eyebrow">CHECK YOUR UNDERSTANDING</div><h3>{record.check.question}</h3>{record.check.options.map((o,i)=><button key={i} aria-pressed={answer===i} className={(answer===i?'chosen ':'')+(answer!==undefined&&i===record.check.answer?'correct':'')} onClick={()=>setAnswers(a=>({...a,[record.id]:i}))}>{answer!==undefined&&i===record.check.answer?<Check size={14}/>:<span className="answer-letter">{'ABC'[i]}</span>}{o}</button>)}{answer!==undefined&&<p className="answer-feedback" role="status">{answer===record.check.answer?'Correct. ':'Try the highlighted explanation. '}{record.check.explanation}</p>}</div>}</TabsContent>
 <TabsContent value="science">{tab==='science'&&<ResourceBoundary name="science explanation"><Suspense fallback={<p>Loading the science…</p>}><SciencePanel record={record} chapter={chapter} onLab={()=>setModal('lab')}/></Suspense></ResourceBoundary>}</TabsContent>
 <TabsContent value="specs"><div className="detail-section first"><h3>Specifications & units</h3><p className="meta-explanation">Values belong to the configuration named below. A teaching example is labelled as such.</p></div><dl className="spec-list">{record.specs.map(s=><div key={s.label}><dt>{s.label}</dt><dd>{s.value}</dd><p>{s.context}</p></div>)}</dl><div className="detail-section"><h3>Tradeoff</h3><p>{record.tradeoff}</p></div></TabsContent>
 <TabsContent value="links"><div className="detail-section first"><h3>Interfaces</h3>{record.interfaces.map((i,n)=><div className="interface" key={n}><span>{i.direction==='in'?'IN':'OUT'}</span><div><h4>{i.name}</h4><p>{i.signal}</p></div></div>)}</div><div className="detail-section"><h3>Explore the relationships</h3>{record.related.filter(id=>byId[id]).map(id=><button className="related-link" key={id} onClick={()=>select(id)}><Network size={14}/><span>{byId[id].name}<small>{chapterFor(id).name}</small></span><ChevronRight size={15}/></button>)}</div><div className="detail-section"><h3>Move across scale</h3><div className="scale-neighbors">{index>0&&<button onClick={()=>selectChapter(chapters[index-1].id)}><ChevronLeft size={14}/>{chapters[index-1].name}</button>}{index<chapters.length-1&&<button onClick={()=>selectChapter(chapters[index+1].id)}>{chapters[index+1].name}<ChevronRight size={14}/></button>}</div></div></TabsContent></Tabs><div className="sources"><h3>Sources & further reading</h3>{record.sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span>{s.title}<ExternalLink size={11}/></a>)}</div>
 </>}</aside></div>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('');}}><DialogContent finalFocus={()=>{if(pendingLessonFocus.current&&lessonHeading.current){pendingLessonFocus.current=false;requestAnimationFrame(()=>lessonHeading.current?.scrollIntoView({block:'start'}));return lessonHeading.current;}return true;}} className={'atlas-modal '+(['film','lab','global','evidence','compare','investigations'].includes(modal)?'film-modal':'')+(modal==='investigations'?' investigation-modal':'')+(modal==='contents'?' contents-modal':'') }><DialogTitle>{({investigations:'From mechanism to consequence',contents:'Explore the atlas',menu:'Atlas destinations',search:'Find a component',paths:'Choose a learning path',history:'Breakthroughs that built the machine',lab:'The quantitative workbench',evidence:'Evidence, dates & current constraints',global:'Global AI infrastructure',compare:'Architecture & processing-unit comparison',glossary:'Glossary & units',film:'The Ascent',about:'How to read the AI Atlas'} as Record<string,string>)[modal]||'AI Atlas'}</DialogTitle><DialogDescription>{modal==='investigations'?'Three connected investigations with shared inputs, explicit models and saved learning work.':modal==='search'?'Search the constituent parts, mechanisms, and scales.':modal==='paths'?'Trace a complete process across the hierarchy. Your exploration and checks are saved on this device.':modal==='history'?'A selective chronology of enabling ideas and engineering breakthroughs. Dates describe the event named, not every precursor.':modal==='lab'?'Small, explicit models for exploring cause and effect. These are teaching calculations, not vendor performance predictions.':modal==='film'?'The cinematic companion: from attention and early GPTs toward the frontier.':`${bands.length} navigation bands contain ${chapters.length} branches and ${records.length} connected lessons.`}</DialogDescription>
 {modal==='investigations'&&<ResourceBoundary name="connected investigations"><Suspense fallback={<p>Loading the investigations…</p>}><Investigations onCaseChange={id=>{setInvestigationId(id);setSharedDocument('');setSharedEncoded('');}} onScenarioEdit={()=>{setSharedDocument('');setSharedEncoded('');}} initialId={investigationId} initialDocument={sharedDocument||undefined} onLesson={id=>{select(id);setModal('');}} onShare={async(id,serialized)=>{const encoded=btoa(serialized).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');setInvestigationId(id);setSharedEncoded(encoded);const hash=encodeAtlasHash({lesson:selected,view,processStep,path:journey,pathStep:step,comparison:'',investigation:id,scenario:encoded});const url=new URL(window.location.href);url.hash=hash;history.replaceState(null,'',hash);try{await navigator.clipboard.writeText(url.href);return true;}catch{return false;}}}/></Suspense></ResourceBoundary>}
 {modal==='contents'&&navigation}
 {modal==='menu'&&<div className="destination-menu">{[['investigations','Connected investigations'],['paths','Learning paths'],['lab','Numerical labs'],['compare','Compare architectures'],['history','Historical breakthroughs'],['evidence','Evidence & sources'],['global','Global infrastructure'],['glossary','Glossary & units'],['film','The Ascent film'],['about','How to read this atlas']].map(([id,label])=><Button key={id} variant="outline" onClick={()=>setModal(id)}>{label}<ChevronRight/></Button>)}<p>{completed} concepts checked · {visited.length}/{records.length} explored</p><a href="https://semiaifoundry.com/">SemiAIFoundry home ↗</a></div>}
 {modal==='search'&&<><div className="search-box"><Search size={19}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try gate, matrix, cooling, bandwidth…" aria-label="Search atlas"/></div><div className="search-results">{matches.length?matches.map(r=><button key={r.id} onClick={()=>{select(r.id);setModal('');}}><span><strong>{r.name}</strong><small>{chapterFor(r.id).name} · {r.role}</small></span><ChevronRight size={16}/></button>):<p className="empty-state">No matching components. Try a broader term such as memory, power, or training.</p>}</div></>}
 {modal==='paths'&&<div className="path-list">{journeys.map(j=><button key={j.id} onClick={()=>startPath(j.id)}><div className="path-icon"><BookOpen/></div><span><strong>{j.name}</strong><small>{j.subtitle}</small><em>{j.ids.filter(id=>byId[id]).length} connected lessons</em></span><ChevronRight/></button>)}</div>}
 {modal==='history'&&<div className="timeline">{milestones.map((h,i)=><div key={i}><time>{h.year}</time><article><h3>{h.title}</h3><p>{h.significance}</p><a href={h.source.url} target="_blank" rel="noreferrer">{h.source.title} ↗</a>{h.component&&byId[h.component]&&<button onClick={()=>{select(h.component);setModal('');}}>Explore {byId[h.component].shortName} <ChevronRight size={12}/></button>}</article></div>)}</div>}
 {modal==='lab'&&<ResourceBoundary name="numerical workbench"><Suspense fallback={<p>Loading numerical labs…</p>}><Lab key={record.id} initial={record.labId||'library'} deepInitial={record.deepLabId} scope={record.labScope} initialRoute={record.id==='hbm-mr-muf-route'?'mr-muf':record.id==='hbm-hybrid-bond-route'?'hybrid':'tc-ncf'}/></Suspense></ResourceBoundary>}
 {modal==='evidence'&&<EvidenceLibrary onSelect={id=>{select(id);setModal('');}}/>}
 {modal==='global'&&<ResourceBoundary name="global map"><Suspense fallback={<p>Loading the map…</p>}><GlobalAtlas/></Suspense></ResourceBoundary>}
 {modal==='compare'&&<ResourceBoundary name="architecture comparison"><Suspense fallback={<p>Loading comparisons…</p>}><SpecimenComparison/></Suspense></ResourceBoundary>}
 {modal==='glossary'&&<Glossary/>}
 {modal==='film'&&<iframe src={`${import.meta.env.BASE_URL}ascent.html`} title="The Ascent cinematic film" allow="autoplay; fullscreen" allowFullScreen/>}
 {modal==='about'&&<ReadingGuide/>}
 </DialogContent></Dialog>
 </main>;
}
