'use client';
import { useCallback, useEffect, useMemo, useRef, useState, useLayoutEffect, lazy, Suspense } from 'react';
import { flushSync } from 'react-dom';
import { Atom, BookOpen, Box, ChevronDown, ChevronLeft, ChevronRight, Check, ExternalLink, Film, FlaskConical, History, Layers3, Maximize2, Network, Pause, Play, RotateCcw, Search, Tag, X, ScanLine, GraduationCap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const AtlasScene=lazy(()=>import('@/components/atlas-scene'));
import {Equation} from '@/components/equation';
import originalEquations from '@/lib/data/equations-original.json';
import expansionEquations from '@/lib/data/equations-expansion.json';
import infraEquations from '@/lib/data/equations-infrastructure.json';
import type {MathDefinition} from '@/components/equation';
import {parseAtlasHash,encodeAtlasHash} from '@/lib/url-state';
const equations={...originalEquations,...expansionEquations,...infraEquations} as Record<string,MathDefinition[]>;
const Lab=lazy(()=>import('@/components/lab'));
import { records,byId,chapters,chapterFor,bands,journeys } from '@/lib/atlas';
import originalMilestones from '@/lib/data/milestones.json';
import {contentPacks} from '@/lib/atlas';
import {ProcessControls,DependencyView,EvidenceLibrary,GlobalAtlas,LessonDepth,Glossary,type ViewMode} from '@/components/atlas-exploration';
import CRGBridge from '@/components/crg-bridge';
import SpecimenComparison from '@/components/specimen-comparison';
const milestones=[...originalMilestones,...contentPacks.flatMap(p=>p.milestones) as typeof originalMilestones].sort((a,b)=>Number.parseFloat(String(a.year))-Number.parseFloat(String(b.year)));
const processScene=(scene:string,band:number)=>{if(['orbital-system','process-tool','fab-operations','design-flow'].includes(scene))return scene;if(['fabrication','process-wafer','process-tool','fab-operations'].includes(scene))return 'process-wafer';if(['transistor','device-crosssection'].includes(scene))return 'device-crosssection';if(['memory-stack','hbm-detail'].includes(scene))return 'hbm-detail';if(['package','package-route','signal-power'].includes(scene))return 'package-route';if(band===0)return 'device-crosssection';if(band===1||band>=4)return 'software-flow';return 'hall-system';};
export default function Home(){
 const [selected,setSelected]=useState('gpu-die'),[explode,setExplode]=useState(32),[isolated,setIsolated]=useState(false),[reset,setReset]=useState(0),[running,setRunning]=useState(true),[labels,setLabels]=useState(true),[xray,setXray]=useState(false);
 const [modal,setModal]=useState(''),[query,setQuery]=useState(''),[tab,setTab]=useState('learn'),[openBands,setOpenBands]=useState([2]),[journey,setJourney]=useState(''),[step,setStep]=useState(0),[visited,setVisited]=useState<string[]>([]),[answers,setAnswers]=useState<Record<string,number>>({}),[ready,setReady]=useState(false);
 const [view,setView]=useState<ViewMode>('anatomy'),[processStep,setProcessStep]=useState(0),[overlay,setOverlay]=useState('structure');
 const inspector=useRef<HTMLElement>(null),search=useRef<HTMLInputElement>(null);
 const record=byId[selected]??records[0],chapter=chapterFor(record.id),index=chapters.indexOf(chapter),band=bands[chapter.band],parts=chapter.ids.map(id=>byId[id]).filter(Boolean);
 const path=journeys.find(j=>j.id===journey);const pathIds=path?.ids.filter(id=>byId[id])??[];
 const select=useCallback((id:string)=>{if(!byId[id])return;setSelected(id);setIsolated(false);setProcessStep(0);setOverlay('structure');setOpenBands(x=>[...new Set([...x,chapterFor(id).band])]);setVisited(v=>v.includes(id)?v:[...v,id]);setTab('learn');inspector.current?.scrollTo({top:0});},[]);
 const selectChapter=(id:string)=>{const c=chapters.find(c=>c.id===id);if(c){const first=c.ids.find(id=>byId[id]);if(first)select(first);}};
 useEffect(()=>{const restore=()=>{const u=parseAtlasHash(window.location.hash);if(byId[u.lesson]){select(u.lesson);setView(u.view);setProcessStep(Math.min(5,u.processStep));setJourney(journeys.some(j=>j.id===u.path)?u.path:'');setStep(u.pathStep);if(u.comparison)setModal('compare');}};queueMicrotask(()=>{try{const saved=JSON.parse(localStorage.getItem('ai-atlas-learning-v1')||'{}');if(Array.isArray(saved.visited))setVisited(saved.visited.filter((id:string)=>byId[id]));if(saved.answers&&typeof saved.answers==='object')setAnswers(saved.answers);}catch{}restore();setReady(true);});const hotkey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setModal('search');}};window.addEventListener('keydown',hotkey);window.addEventListener('hashchange',restore);return()=>{window.removeEventListener('keydown',hotkey);window.removeEventListener('hashchange',restore);};},[select]);
 useEffect(()=>{if(!ready)return;const hash=encodeAtlasHash({lesson:selected,view,processStep,path:journey,pathStep:step,comparison:modal==='compare'?'specimens':''});if(window.location.hash!==hash)history.replaceState(null,'',hash);},[ready,selected,view,processStep,journey,step,modal]);
 useEffect(()=>{if(ready)try{localStorage.setItem('ai-atlas-learning-v1',JSON.stringify({visited,answers}));}catch{}},[ready,visited,answers]);
 useEffect(()=>{if(modal==='search')setTimeout(()=>search.current?.focus(),100);},[modal]);
 const state=useRef({selected,explode,isolated,journey,step});useLayoutEffect(()=>{state.current={selected,explode,isolated,journey,step};},[selected,explode,isolated,journey,step]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  register({name:'search_atlas',description:'Read component matches from the AI atlas. Does not change the view.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(v:{query:string})=>{if(typeof v.query!=='string')throw Error('query must be a string');return records.filter(r=>(r.name+' '+r.role+' '+r.id).toLowerCase().includes(v.query.toLowerCase())).slice(0,20).map(r=>({id:r.id,name:r.name,branch:chapterFor(r.id).name}));}});
  register({name:'navigate_atlas',description:'Select a component and configure its visible 3D assembly.',inputSchema:{type:'object',properties:{componentId:{type:'string'},explode:{type:'number',minimum:0,maximum:100},isolate:{type:'boolean'}},required:['componentId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(v:{componentId:string;explode?:number;isolate?:boolean})=>{if(!byId[v.componentId])throw Error('Unknown component ID');if(v.explode!==undefined&&(!Number.isFinite(v.explode)||v.explode<0||v.explode>100))throw Error('explode must be 0–100');if(v.isolate!==undefined&&typeof v.isolate!=='boolean')throw Error('isolate must be boolean');flushSync(()=>{select(v.componentId);if(v.explode!==undefined)setExplode(v.explode);if(v.isolate!==undefined)setIsolated(v.isolate);});return {componentId:v.componentId,branch:chapterFor(v.componentId).name,explode:v.explode??state.current.explode,isolate:v.isolate??false};}});
  register({name:'read_atlas_state',description:'Read the currently selected component and assembly controls.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state.current})});return()=>life.abort();
 },[select]);
 const matches=useMemo(()=>records.filter(r=>(r.name+' '+r.role+' '+r.description+' '+chapterFor(r.id).name).toLowerCase().includes(query.toLowerCase())),[query]);
 const startPath=(id:string)=>{const j=journeys.find(j=>j.id===id);if(!j)return;setJourney(id);setStep(0);select(j.ids.find(id=>byId[id])!);setModal('');};
 const goStep=(n:number)=>{if(pathIds[n]){setStep(n);select(pathIds[n]);}};
 const answer=answers[record.id];const completed=records.filter(r=>answers[r.id]===r.check?.answer).length;
 return <main className="atlas-shell"><header className="topbar"><div className="brand"><a className="foundry-home" href="https://semiaifoundry.com/" aria-label="SemiAIFoundry home">semiAIfoundry</a><Atom size={27}/><strong>AI ATLAS</strong><span>THE MACHINERY OF INTELLIGENCE</span></div><div className="top-actions"><Button variant="ghost" className="search-launch" aria-label="Find a component" onClick={()=>setModal('search')}><Search/><span>Find a component</span><kbd>⌘ K</kbd></Button><Button variant="outline" onClick={()=>setModal('paths')}><BookOpen/><span className="label-long">Learning paths</span></Button><Button variant="ghost" onClick={()=>setModal('compare')}>Compare</Button><Button variant="ghost" onClick={()=>setModal('history')} aria-label="Historical breakthroughs"><History/></Button><Button variant="ghost" onClick={()=>setModal('evidence')}>Evidence</Button><Button variant="ghost" onClick={()=>setModal('global')}>Global</Button><Button variant="outline" onClick={()=>setModal('film')}><Film/><span className="label-long">The film</span></Button></div></header>
 <div className="workspace"><aside className="navigator"><div className="eyebrow nav-heading">NANO → MACRO → INTELLIGENCE</div><nav aria-label="Atlas hierarchy">{bands.map((b,i)=><div key={b.name} className="band-group"><button className={'band-heading '+(chapter.band===i?'current':'')} onClick={()=>setOpenBands(x=>x.includes(i)?x.filter(n=>n!==i):[...x,i])} aria-expanded={openBands.includes(i)}><span className="band-mark" style={{background:b.color}}/><span>{b.name}<small>{b.range}</small></span><ChevronDown size={13} className={openBands.includes(i)?'expanded':''}/></button>{openBands.includes(i)&&<div className="branch-list">{[...new Set(chapters.filter(c=>c.band===i).map(c=>c.parent||'Foundations'))].map(parent=><details className="nested-domain" key={parent} open={parent==='Foundations'||parent===chapter.parent}><summary>{parent}</summary>{chapters.filter(c=>c.band===i&&(c.parent||'Foundations')===parent).map(c=><button className={'branch-link '+(chapter.id===c.id?'active':'')} key={c.id} onClick={()=>selectChapter(c.id)}><span>{c.name}</span><small>{c.ids.length}</small></button>)}</details>)}</div>}</div>)}</nav><div className="learning-progress"><GraduationCap size={17}/><div><strong>{completed} concepts checked</strong><span>{visited.length} / {records.length} explored</span></div></div><button className="atlas-about" onClick={()=>setModal('glossary')}>Glossary &amp; units</button><button className="atlas-about" onClick={()=>setModal('about')}>How to read this atlas <ExternalLink size={11}/></button></aside>
 <section className="stage"><div className="stage-heading"><div className="eyebrow" style={{color:band.color}}>{String(index+1).padStart(2,'0')} / {chapter.scale.toUpperCase()}</div><h1>{chapter.title}</h1><p>{chapter.summary}</p><div className="view-modes" aria-label="Exploration view">{(['anatomy','process','dependencies'] as ViewMode[]).map(m=><button aria-pressed={view===m} key={m} onClick={()=>{setView(m);setProcessStep(0);setExplode(0);}}>{m==='anatomy'?'Anatomy':m==='process'?'Process':'Connections'}</button>)}</div></div><div className="view-actions"><Button size="icon" variant={labels?'secondary':'ghost'} onClick={()=>setLabels(!labels)} aria-label={labels?'Hide labels':'Show labels'} title="Labels"><Tag/></Button><Button size="icon" variant={xray?'secondary':'ghost'} onClick={()=>setXray(!xray)} aria-label="Toggle translucent cutaway" title="Translucent view"><ScanLine/></Button><Button size="icon" variant="ghost" onClick={()=>setRunning(!running)} aria-label={running?'Pause flow':'Animate flow'}>{running?<Pause/>:<Play/>}</Button></div>
 <div className={view==='dependencies'?'stage-diagram':view==='process'?'process-scene':'anatomy-scene'}>{view==='dependencies'?<DependencyView selected={record} onSelect={select}/>:<Suspense fallback={<p className="scene-loading">Loading the 3D model…</p>}><AtlasScene level={view==='process'?processScene(chapter.scene,chapter.band):chapter.scene} records={parts} selected={record.id} onSelect={select} explode={explode} isolate={isolated} reset={reset} running={running} labels={labels&&view!=='process'} xray={xray} signal={view==='process'?processStep:undefined} overlay={overlay}/></Suspense>}</div>{view==='process'&&<ProcessControls recordId={record.id} scene={processScene(chapter.scene,chapter.band)} index={processStep} onStep={setProcessStep} onSelect={select}/>} 
 <div className={"stage-lower "+(view!=='anatomy'?'compact-lower':'')}>{path&&<div className="journey-bar"><div><span className="eyebrow">GUIDED PATH · {step+1}/{pathIds.length}</span><strong>{path.name}</strong></div><Button size="icon" variant="ghost" disabled={step===0} onClick={()=>goStep(step-1)} aria-label="Previous path step"><ChevronLeft/></Button><Button size="icon" variant="ghost" disabled={step===pathIds.length-1} onClick={()=>goStep(step+1)} aria-label="Next path step"><ChevronRight/></Button><Button size="icon" variant="ghost" onClick={()=>setJourney('')} aria-label="Leave guided path"><X/></Button></div>}
 <div className={"assembly-selector "+(view!=='anatomy'?'visually-suppressed':'')}><span className="eyebrow">SELECT A COMPONENT</span><div>{parts.map(p=><button className={record.id===p.id?'selected':''} key={p.id} onClick={()=>select(p.id)}><span className="status-dot"/>{p.shortName}</button>)}</div></div><div className="scene-toolbar"><Button aria-label={isolated?'Show full assembly':'Isolate component'} variant={isolated?'default':'outline'} onClick={()=>setIsolated(!isolated)}><Maximize2/><span>Isolate</span></Button><Button variant="outline" onClick={()=>{setReset(reset+1);setExplode(0);setIsolated(false);setXray(false);}} aria-label="Reset assembly"><RotateCcw/></Button><div className="explode-control"><Layers3 size={17}/><span>Explode</span><Slider value={[explode]} onValueChange={v=>setExplode(Array.isArray(v)?v[0]:v)} max={100} aria-label="Explode assembly"/><output>{explode}%</output></div><Button variant="secondary" aria-label="Open numerical labs" onClick={()=>setModal('lab')}><FlaskConical/><span>Lab</span></Button></div><div className="overlay-controls"><label>Trace<select aria-label="Physical flow overlay" value={overlay} onChange={e=>setOverlay(e.target.value)}>{['structure','bytes','power','heat','material'].map(x=><option key={x} value={x}>{x==='structure'?'Structure':x==='bytes'?'Data movement':x==='power'?'Electrical supply':x==='heat'?'Heat rejection':'Production flow'}</option>)}</select></label><span>{({structure:'Drag to orbit · Schematic geometry; dimensions exaggerated',bytes:'Bytes along a representative path · no implied transfer rate',power:'Electrical supply → load · voltage/current values belong to the selected system',heat:'Heat source → rejection path · power in W; temperatures in K or °C',material:'Process input → output · units tracked at each stage'} as Record<string,string>)[overlay]}</span></div></div>
 </section>
 <aside className="inspector" ref={inspector}><div className="inspector-top"><span className="eyebrow">COMPONENT FIELD GUIDE</span><span className="record-counter">{records.indexOf(record)+1}/{records.length}</span></div><div className="lesson-breadcrumb">{band.name} → {chapter.parent||chapter.name} → {record.subbranch||record.shortName}</div><div className="component-kicker" style={{color:band.color}}><Box size={15}/>{chapter.name}</div><h2>{record.name}</h2><p className="role">{record.role}</p><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="detail-tabs"><TabsTrigger value="learn">Learn</TabsTrigger><TabsTrigger value="science">Science</TabsTrigger><TabsTrigger value="specs">Specs</TabsTrigger><TabsTrigger value="links">Connections</TabsTrigger></TabsList>
 <TabsContent value="learn"><LessonDepth record={record} onSelect={select}/><div className="detail-section first"><p>{record.description}</p></div><div className="detail-section"><h3>How it works</h3><ol className="mechanism">{record.mechanism?.map((s,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></div><div className="detail-section"><h3>Why it matters to AI</h3><p>{record.whyAI}</p></div><div className="misconception"><h3>Distinction to keep</h3><p>{record.misconception}</p></div>{record.check&&<div className="knowledge-check"><div className="eyebrow">CHECK YOUR UNDERSTANDING</div><h3>{record.check.question}</h3>{record.check.options.map((o,i)=><button key={i} className={(answer===i?'chosen ':'')+(answer!==undefined&&i===record.check.answer?'correct':'')} onClick={()=>setAnswers(a=>({...a,[record.id]:i}))}>{answer!==undefined&&i===record.check.answer?<Check size={14}/>:<span className="answer-letter">{'ABC'[i]}</span>}{o}</button>)}{answer!==undefined&&<p className="answer-feedback">{answer===record.check.answer?'Correct. ':'Try the highlighted explanation. '}{record.check.explanation}</p>}</div>}</TabsContent>
 <TabsContent value="science"><div className="detail-section first"><h3>The engineering question</h3><p>{chapter.question}</p></div>{record.science?.map((s,i)=><div className="science-card" key={i}><h3>{s.title}</h3><Equation latex={equations[record.id]?.[i]?.latex} variables={equations[record.id]?.[i]?.variables} text={s.equation}/><p>{s.explanation}</p><small><strong>Assumptions · </strong>{s.assumptions}</small></div>)}<div className="detail-section"><h3>Engineering tradeoff</h3><p>{record.tradeoff}</p></div><div className="detail-section"><h3>Read the 3D model</h3><p>{chapter.read}</p><p className="scale-note">{record.scale}</p></div>{record.history?.map((h,i)=><div className="history-inline" key={i}><span>{h.year}</span><h3>{h.title}</h3><p>{h.significance}</p><a href={h.source.url} target="_blank" rel="noreferrer">{h.source.title} ↗</a></div>)}<Button variant="outline" className="wide-button" onClick={()=>setModal('lab')}><FlaskConical/> Explore a numerical lab</Button></TabsContent>
 <TabsContent value="specs"><div className="detail-section first"><h3>Specifications & units</h3><p className="meta-explanation">Values belong to the configuration named below. A teaching example is labelled as such.</p></div><dl className="spec-list">{record.specs.map(s=><div key={s.label}><dt>{s.label}</dt><dd>{s.value}</dd><p>{s.context}</p></div>)}</dl><div className="detail-section"><h3>Tradeoff</h3><p>{record.tradeoff}</p></div></TabsContent>
 <TabsContent value="links"><div className="detail-section first"><h3>Interfaces</h3>{record.interfaces.map((i,n)=><div className="interface" key={n}><span>{i.direction==='in'?'IN':'OUT'}</span><div><h4>{i.name}</h4><p>{i.signal}</p></div></div>)}</div><div className="detail-section"><h3>Explore the relationships</h3>{record.related.filter(id=>byId[id]).map(id=><button className="related-link" key={id} onClick={()=>select(id)}><Network size={14}/><span>{byId[id].name}<small>{chapterFor(id).name}</small></span><ChevronRight size={15}/></button>)}</div><div className="detail-section"><h3>Move across scale</h3><div className="scale-neighbors">{index>0&&<button onClick={()=>selectChapter(chapters[index-1].id)}><ChevronLeft size={14}/>{chapters[index-1].name}</button>}{index<chapters.length-1&&<button onClick={()=>selectChapter(chapters[index+1].id)}>{chapters[index+1].name}<ChevronRight size={14}/></button>}</div></div></TabsContent></Tabs><div className="sources"><h3>Sources & further reading</h3>{record.sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span>{s.title}<ExternalLink size={11}/></a>)}</div>
 </aside></div>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('');}}><DialogContent className={'atlas-modal '+(['film','lab','global','evidence'].includes(modal)?'film-modal':'') }><DialogTitle>{({search:'Find a component',paths:'Choose a learning path',history:'Breakthroughs that built the machine',lab:'The quantitative workbench',evidence:'Evidence, dates & current constraints',global:'Global AI infrastructure',compare:'Architecture & processing-unit comparison',glossary:'Glossary & units',film:'The Ascent',about:'How to read the AI Atlas'} as Record<string,string>)[modal]||'AI Atlas'}</DialogTitle><DialogDescription>{modal==='search'?'Search the constituent parts, mechanisms, and scales.':modal==='paths'?'Trace a complete process across the hierarchy. Your exploration and checks are saved on this device.':modal==='history'?'A selective chronology of enabling ideas and engineering breakthroughs. Dates describe the event named, not every precursor.':modal==='lab'?'Small, explicit models for exploring cause and effect. These are teaching calculations, not vendor performance predictions.':modal==='film'?'The cinematic companion: from attention and early GPTs toward the frontier.':`${bands.length} navigation bands contain ${chapters.length} branches and ${records.length} connected lessons.`}</DialogDescription>
 {modal==='search'&&<><div className="search-box"><Search size={19}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try gate, matrix, cooling, bandwidth…" aria-label="Search atlas"/></div><div className="search-results">{matches.length?matches.map(r=><button key={r.id} onClick={()=>{select(r.id);setModal('');}}><span><strong>{r.name}</strong><small>{chapterFor(r.id).name} · {r.role}</small></span><ChevronRight size={16}/></button>):<p className="empty-state">No matching components. Try a broader term such as memory, power, or training.</p>}</div></>}
 {modal==='paths'&&<div className="path-list">{journeys.map(j=><button key={j.id} onClick={()=>startPath(j.id)}><div className="path-icon"><BookOpen/></div><span><strong>{j.name}</strong><small>{j.subtitle}</small><em>{j.ids.filter(id=>byId[id]).length} connected lessons</em></span><ChevronRight/></button>)}</div>}
 {modal==='history'&&<div className="timeline">{milestones.map((h,i)=><div key={i}><time>{h.year}</time><article><h3>{h.title}</h3><p>{h.significance}</p><a href={h.source.url} target="_blank" rel="noreferrer">{h.source.title} ↗</a>{h.component&&byId[h.component]&&<button onClick={()=>{select(h.component);setModal('');}}>Explore {byId[h.component].shortName} <ChevronRight size={12}/></button>}</article></div>)}</div>}
 {modal==='lab'&&<Suspense fallback={<p>Loading numerical labs…</p>}><Lab initial="engineering"/></Suspense>}
 {modal==='evidence'&&<EvidenceLibrary onSelect={id=>{select(id);setModal('');}}/>}
 {modal==='global'&&<GlobalAtlas/>}
 {modal==='compare'&&<SpecimenComparison/>}
 {modal==='glossary'&&<Glossary/>}
 {modal==='film'&&<iframe src={`${import.meta.env.BASE_URL}ascent.html`} title="The Ascent cinematic film" allow="autoplay; fullscreen" allowFullScreen/>}
 {modal==='about'&&<div className="about-body"><p>This atlas connects physical components, manufacturing processes, software abstractions, and model behavior. They are different kinds of structures; each lesson identifies what its 3D view represents.</p><p>Start with a learning path, or open any branch in the hierarchy. Select a mesh or a component chip. Explode separates an assembly; isolate focuses a named part; the translucent view reveals internal relationships.</p><p>The field guide provides mechanisms, equations with assumptions, contextual specifications, interfaces, knowledge checks, and primary references. The workbench lets you vary inputs and examine small numerical models.</p><p>Hardware assemblies use public examples and conceptual geometry. They do not disclose Astra’s internal design or assert that a specific chip powers it. AGI remains an evaluation and research question.</p><p>Interaction design inspired by <a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">ashemag’s Human Atlas</a>. The component geometry and AI curriculum were created for this companion.</p><p>Published by <a href="https://semiaifoundry.com/">Semi AI Foundry, LLC</a>. <a href="https://github.com/SemiAIFoundry/ai-machinery-atlas/releases/download/v1.1.0/ai-machinery-atlas-v1.1.0-source.zip">Download source · v1.1.0</a> · <a href={`${import.meta.env.BASE_URL}licenses.html`}>MIT license &amp; third-party notices</a> · <a href={`${import.meta.env.BASE_URL}ascent.html`} target="_blank" rel="noreferrer">Watch The Ascent ↗</a>.</p><p className="meta-explanation">v1.1.0 reference edition · September 2026. Learning progress stays in this browser’s local storage.</p></div>}
 </DialogContent></Dialog>
 </main>;
}
